### ISSUE TITLE
Appending to file as optional parameter in to_file()

### ISSUE THREAD

**Issue by arredond** [geopandas/geopandas#1004]
I'm not sure how hard this would be, but having the option to append to an existing file (SHP, GPKG, GeoJSON, etc) would be a nice feature (for example, to avoid reading a large file, concating a few rows and then writing again).

Since GeoPandas [simply uses `fiona.open(filename, 'w')`](https://github.com/geopandas/geopandas/blob/master/geopandas/io/file.py#L101), this could be as simple as optionally switching `'w'` for `'a'`, although I do suppose doing some checks on the existing file's schema could be useful or even necessary. A simple example can be seen [in this gist by @robbibt](https://gist.github.com/robbibt/7639935045a1473c3af5a86ece4273f1).

I'd be happy to provide a PR, especially if someone wiser than me can provide a few pointers on best practices 😅

**Comment by jorisvandenbossche** [comment]
I think that would be certainly a welcome addition to `to_file`. We can provide a `mode` keyword for that, so the user can specify `mode='a'`. See also the docs about it: https://fiona.readthedocs.io/en/latest/manual.html#appending-data-to-existing-files

If you need any help for a PR, feel free to ask any questions! There are some contributing docs at https://geopandas.readthedocs.io/en/latest/contributing.html (although not everything in there is up to date). Important thing is that you will need to write some tests checking the behaviour.

**Comment by arredond** [comment]
Awesome! I'll get to it and hope to provide a PR soon enough

**Comment by kylebarron** [comment]
I'm also interested in this, particularly in appending to GeoJSONlines, see https://github.com/Toblerity/Fiona/issues/839

**Comment by kylebarron** [comment]
Also, Geopandas doesn't have to do any schema checks, because Fiona will do that itself: https://fiona.readthedocs.io/en/latest/manual.html#appending-data-to-existing-files.

It seems ok to just pass the mode through to Fiona, and then let Fiona catch any errors.
