### ISSUE TITLE
Running tests in pycharm environment

### ISSUE THREAD

**Issue by awa5114** [geopandas/geopandas#1005]
Dear all,

I would like to run the tests from within my pycharm IDE, hopefully so that I can write my own tests if I would like to submit a pull request. 

How can I achieve this? Thanks!

**Comment by jorisvandenbossche** [comment]
I am not familiar with PyCharm, so can't give exact advice. I would recommend searching for how to run python tests in pycharm. See eg https://stackoverflow.com/questions/6397063/how-do-i-configure-pycharm-to-run-py-test-tests

Note that in general, you can always run tests from the command line (separate command line or the console integrated in pycharm) using `pytest geopandas` from the repo directory.
