### ISSUE TITLE
BUG: GeoDataFrame.astype(..) does not return a GeoDataFrame when possible

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1006]
Using the `astype` method on a GeoDataFrame, looses the subclass and returns a plain DataFrame:

```
In [1]: import geopandas

In [2]: df = geopandas.read_file(geopandas.datasets.get_path('nybb')) 

In [3]: type(df)          
Out[3]: geopandas.geodataframe.GeoDataFrame

In [4]: df2 = df.astype({'BoroCode': str}) 

In [5]: type(df2)       
Out[5]: pandas.core.frame.DataFrame
```

One could argue that this is a bug in pandas (and can also probably solved in pandas), but on the short term, we can solve that by overriding `astype` in the GeoDataFrame class.

**Comment by awa5114** [comment]
`astype` is in the class definition for `pandas.core.generic.NDFrame` which is a superclass of `pandas.DataFrame`. What makes you think this might be a bug in pandas? The conversion seems to be done correctly:

```
df.astype({'BoroCode': str})['BoroCode'].values
array(['5', '4', '3', '1', '2'], dtype=object)
df['BoroCode'].values
array([5, 4, 3, 1, 2], dtype=int64)
```

**Comment by awa5114** [comment]
I just submitted a pull request to address this. Please let me know if it works...

**Comment by awa5114** [comment]
I just brought some changes to the pull request, but have lingering problems. Any help would be very much appreciated...
