### ISSUE TITLE
ENH: add affine_transform as method to GeoSeries

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1007]
We already have some of the `shapely.affinity` functions (https://shapely.readthedocs.io/en/stable/manual.html#affine-transformations) exposed on a GeoSeries (translate, scale, rotate), but the generic `affine_transform` is not. It would probably be useful to add this as well (see eg this [SO](https://gis.stackexchange.com/questions/323750/re-project-geojson-from-pixel-space-to-lat-long-in-python) question).

**Comment by donlo** [comment]
Would like to give a try on this enhancement!
I guess this enh would be achieved by adding method in GeoPandasBase and GeometryArray class respectively? Are there any other things that I shall be aware of?
Havent contributed directly to codebase before so forgive me for asking stupid questions lol

**Comment by asmith26** [comment]
Looks like this can be closed following https://github.com/geopandas/geopandas/pull/1008 ?
