### ISSUE TITLE
AppVeyor and local builds slightly different

### ISSUE THREAD

**Issue by awa5114** [geopandas/geopandas#1010]
I am trying to get my system to a state where it can replicate both the travis and AppVeyor builds. I would like to be able to test my work locally before I submit pull requests. For this I used the environment.yml file to setup a development environment. I then wrote a batch file to launch pycharm from the appropriate environment such that all necessary variables (eg `PROJ_LIB` and `GDAL_DATA` are defined during runtime (see [this issue](https://youtrack.jetbrains.com/issue/PY-35141)). I was able to run the tests within pycharm and get the same result as what I got from running `pytest` from anaconda prompt:

`=========================== 413 passed, 23 skipped, 7 xfailed, 2 warnings in 88.83 seconds ============================
`
but get a result different from the one in Travis, which is:

`======= 426 passed, 10 skipped, 7 xfailed, 22 warnings in 80.56 seconds ========`

I get a lot of warnings in pycharm like:

```
Traceback (most recent call last):
  File "fiona/_err.pyx", line 201, in fiona._err.GDALErrCtxManager.__exit__
fiona._err.CPLE_AppDefinedError: b'sqlite3_exec(CREATE VIRTUAL TABLE "rtree_test_datetime_geom" USING rtree(id, minx, maxx, miny, maxy)) failed: no such module: rtree'
Exception ignored in: 'fiona._shim.gdal_flush_cache'
Traceback (most recent call last):
```
Which I also don't see in Travis. 

Am I missing something? How can I get the build on my local machine to be just like the one in Travis? Thanks in advance.

**Comment by awa5114** [comment]
Also please take a look at my [stackexchange question](https://stackoverflow.com/questions/56370674/travis-ci-build-replication-on-windows-machine) related to this.

**Comment by awa5114** [comment]
I noticed that on my local system the following tests are skipped, but in the Travis build they are not:

 - test_read_postgis_binary
 - test_read_postgis_null_geom

I tried to debug them in PyCharm and I think the problem is related to this:

```
with sqlite3.connect(':memory:') as con:
    con.enable_load_extension(True)
    con.load_extension('mod_spatialite')
```

> Traceback (most recent call last):
>   File "<input>", line 3, in <module>
> sqlite3.OperationalError: The specified module could not be found.

Yet I do have `sqlite3` installed in my environment. The test is getting skipped because in the `try .... except` block an exception (the one above) is probably raised. 

I also came across [this post: ](https://stackoverflow.com/questions/8590599/sqlite-load-extension-fail-for-spatialite-in-python) which explains a bit more regarding problems with `mod_spatialite`. 

I think it is a bit overkill to go and install binaries and manually change the `PATH` variable. Is there a more proper way to deal with mod_spatialite? How does Travis do it?

**Comment by awa5114** [comment]
Allright... almost there. I was under the impression that AppVeyor was only testing for python 2, however upon a second look I realize there is also a python 3 build. The right environment files to use are `requirements.txt` and `requirements.test.txt` for Windows. 

When I reran the tests I saw that I was getting near identical results with the remote build on AppVeyor. However there is one lingering difference in one test:

In AppVeyor:

`geopandas/tests/test_pandas_methods.py::test_drop_duplicates_series XPASS [ 74%]`

On local machine:

`geopandas/tests/test_pandas_methods.py::test_drop_duplicates_series XFAIL [ 74%]`

I think it would be good to identify why this occurs. I checked on the upstream master and see that the test is marked with `xfail`:

```
@pytest.mark.xfail
def test_drop_duplicates_series():
    # currently, geoseries with identical values are not recognized as
    # duplicates
    dups = GeoSeries([Point(0, 0), Point(0, 0)])
    dropped = dups.drop_duplicates()
    assert len(dropped) == 1
```

Why then does it pass on the [AppVeyor build](https://ci.appveyor.com/project/jorisvandenbossche/geopandas-us6w0/builds/24872551/job/ieeq8g48q3y6ej1s)?

**Comment by awa5114** [comment]
I got it... finally. It turns out that the culprit was my cython version.... I had `cython 0.29.9` while in the AppVeyor build it uses `0.29.7`. I have two comments:

 - Does this mean that the more recent version of cython actually drops the duplicate point? If so it might render https://github.com/geopandas/geopandas/issues/521 obsolete?
 - The lesson learned here is that environments must be identical to produce identical test results. For cases where more recent packages are already installed which satisfy the requirements, this appears not to be overrided by a default package (i.e I had 0.29.9 installed and it fulfilled the requirement, but did not get replaced by 0.29.7). Perhaps it might be better to use a full spec file as detailed in the [conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments)? I am happy to submit a pull request for this, however I do not have access to the build parameters in AppVeyor (only used TeamCity before) so I would not be able to modify the build itself so that it uses the spec file.

**Comment by awa5114** [comment]
Upon second thought I think the fact that this test sometimes 'xfails' on my local machine may have more to do with pycharm than anything else... will update thread once I find the problem

**Comment by jorisvandenbossche** [comment]
Sorry for not responding here earlier. The drop_duplicates test was a flaky one due to a bug in pandas (and so was randomly sometimes passing and sometimes failing, hence the XPASS or XFAIL).
