### ISSUE TITLE
Unary predicates for overlapped points

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1011]
It seems like the all [unary predicates](http://geopandas.org/reference.html) are related to `Polygon`.  I think it might be a good idea to add one that tests if there is any (partly) overlapped point, like a unary predicate version of `geom_almost_equals` or something. I know `.duplicated()` won't work, so in the meantime is there a workaround?

**Comment by StevenLi-DS** [comment]
This is a workaround I can think of but it will be very slow for a long DataFrame. Is there any more efficient way to do this?

```python
import pandas as pd
import geopandas as gpd

# create geodata
data = {'latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
        'longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]}
df = pd.DataFrame(data=data)

# convert data to GeoDataFrame
geometry = gpd.points_from_xy(df.longitude, df.latitude)
gdf = gpd.GeoDataFrame(df, geometry=geometry)

# check if there is overlapped points other than itself
count = 0
for point in gdf.geometry:
    overlapped = gdf.geom_almost_equals(point).sum()
    count += overlapped
# return True if there is no overlapped points
count == len(gdf)
```

**Comment by jorisvandenbossche** [comment]
@StevenLi-DS can you give a bit more context on what you want to achieve, or what is not working?

You link to the unary predicates, but in what sense are they only valid for Polygons?

Is it basically `duplicated` that you want? (It doesn't work now, but it should be supported in the next version)

**Comment by StevenLi-DS** [comment]
Assume I have a dataset contains many points and I want to know if there are any overlapped points spatially. I guess `duplicated` could work. But does it basically just check the geometry columns as a string or something? What if I got two points that are very very close or half overlapped?

**Comment by jorisvandenbossche** [comment]
>  What if I got two points that are very very close or half overlapped?

If they are very close but not the same, then they do not overlap. Points cannot "overlap" without being the same, since they have no area?

**Comment by StevenLi-DS** [comment]
@jorisvandenbossche This makes sense. Then is there any way to tell if two points are very very close? Create a buffer around each point and use `geom_almost_equals`?

**Comment by jorisvandenbossche** [comment]
Possible options are calculating the distance between the points and setting a distance limit yourself, or you could use `geom_equals_exact` which takes a `tolerance` argument.
