### ISSUE TITLE
Help: Putting two shapefiles together with geopandas

### ISSUE THREAD

**Issue by juancruzms** [geopandas/geopandas#1013]
So i have two shapefiles which i have imported to my notebook using geopandas:

-map_df2 is a polygon map which contains the locations and limits of every neighboorhood in Buenos Aires.

-map_df contains a number of points which indicate the location of each public work that has been done in Buenos Aires during a certain time period.

I want to plot them together (map_df has to overlay/ be imposed on map_df2) but im not sure how to get this done.

I have tried to follow the geopandas documentation on this: http://geopandas.org/mapping.html#maps-with-layers

But so far, nothing has worked. I can plot both files separately as you can see in the images. But when i try to plot them together, nothing happens.
<img width="349" alt="new" src="https://user-images.githubusercontent.com/51389829/58923880-7258a680-86f6-11e9-9097-a685e8c1edea.png">

I have also tried to plot them on the same line, but to no avail:
<img width="362" alt="new2" src="https://user-images.githubusercontent.com/51389829/58923964-acc24380-86f6-11e9-8764-04097d9f44cd.png">

Any guidance will be appreciated (and will save me lots of headaches). Thank you!

**Comment by Lashuk1729** [comment]
Try the following code as you want to plot all the points(locations) from one map on to another map.
```
fig, ax = plt.subplots(figsize = (8,6))
ax.set_aspect('equal')
map_df.plot(ax = ax, alpha = 0.4, color = 'grey', edgecolor = 'black')
map_df2.geometry.plot(ax=ax, marker='o', color='red', alpha = 0.5, markersize=5)
```
Although I did not read the exact files but the process is same.
![image](https://user-images.githubusercontent.com/29592212/58952310-f707fb00-87b0-11e9-9e9d-430acfeaf698.png)

I hope this helps.

**Comment by juancruzms** [comment]
Hello Lashuk,

I tried using your code and i get the "Unknown property marker" attribute error.

I took some screenshots of the whole thing:

<img width="753" alt="new4" src="https://user-images.githubusercontent.com/51389829/58957878-7b796000-8756-11e9-8ea1-9f2527407396.png">

And finally:

<img width="502" alt="new3" src="https://user-images.githubusercontent.com/51389829/58957900-86cc8b80-8756-11e9-9379-8cb3974c400f.png">

What do you think might have caused this?

**Comment by juancruzms** [comment]
Hello Lashuk,

You code worked perfectly! I had been trying to figure this out for days. Thank you so much for your help, i appreciate it.

**Comment by martinfleis** [comment]
Glad to hear that. Issue resolved, closing.
