### ISSUE TITLE
Problem with Azimuthal Equidistant Projection

### ISSUE THREAD

**Issue by shalvat** [geopandas/geopandas#1014]
I tried to manually define Azimuthal Equidistant Projection by:

world = world.to_crs('+proj=laea +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs ') 

This suppose to be centered on the north pole. The output is below:

![image](https://user-images.githubusercontent.com/48362322/59371027-2df78700-8d44-11e9-9439-880ed5be3cd3.png)

If I change latitude to 80 degree. The result is as expected. 

![image](https://user-images.githubusercontent.com/48362322/59371119-6b5c1480-8d44-11e9-9dfc-e5b57c673587.png)

Is this some kind of a bug or it's me coding wrong?

Thank you!

**Comment by martinfleis** [comment]
Hi, thank you for the report. I don't think it is a bug. Just Antarctica. This projection causes the distortion of the shape of Antarctica to the level which is not legible as it covers whole map. You can see it if you plot with alpha `world.plot(alpha=0.5)`


![Unknown](https://user-images.githubusercontent.com/36797143/60036210-96305c00-96a6-11e9-9b22-345f04696c2c.png)


 I would recommend using the dataset without Antarctica.

    without = world.loc[world.continent != 'Antarctica']
    without.plot()

![Unknown2](https://user-images.githubusercontent.com/36797143/60036340-ead3d700-96a6-11e9-8b12-f2f884c7457b.png)
