### ISSUE TITLE
Working without descartes

### ISSUE THREAD

**Issue by toddrme2178** [geopandas/geopandas#1017]
I am trying to package geopandas for openSUSE.  The problem is the dependency on descartes.  It doesn't appear to be maintained upstream.  Worse, however, is that it doesn't have a license.  It says the license is "BSD", but there are a bunch of "BSD" licenses.  More importantly, all versions of the license forbid distributing the program without the license text, but there is no license text.  This makes it impossible for us to package it, and legally questionable for anyone else to use it at all.  There was a request to add a license [a year ago](https://bitbucket.org/sgillies/descartes/issues/5/license) with no response upstream.

I understand descartes is optional, but the tests don't run without it, and plotting doesn't work without it.  At the very least automatically disabling tests that depend on it when it isn't installed would be helpful, but considering the legal issues it may be better long-term to look for another solution.

**Comment by jorisvandenbossche** [comment]
Thanks for raising the concern. 

(cc @sgillies in case it reaches you here more easily)

Another option would be to include the code into geopandas itself. In the end, descartes is only around 80 lines of code (apart from tests etc).

For the plotting tests, we should indeed add a general skip if matplotlib/descartes are not installed (as both are optional). But as you indicate, this is only useful to "get tests passing", as without descartes no (polygon) plotting will actually work right now.

**Comment by toddrme2178** [comment]
@jorisvandenbossche You would have to re-implement it yourself.  Using the code directly has the same problem with packaging it: it doesn't have a license that says what you can and cannot do with it.

**Comment by toddrme2178** [comment]
This license issue seems to have been fixed upstream.  See upstream [bug 5](https://bitbucket.org/sgillies/descartes/issues/5/license).  It still may be an issue for those installing from pypi since there hasn't been a release with the license yet, and I already asked for a new release so hopefully that will be fixed soon.  But for our purposes the issue is resolved.

There may be other reasons you wish to avoid depending on descartes for your own purposes, and that is entirely up to you.  So I will leave this bug open.

**Comment by jorisvandenbossche** [comment]
The descartes dependency has been removed in the meantime (https://github.com/geopandas/geopandas/pull/1677), so this issue can be closed.
