### ISSUE TITLE
TypeError: invalid path: UnparsedPath, While reading shapefile

### ISSUE THREAD

**Issue by lokendrarathore** [geopandas/geopandas#1018]
I am trying to read a shapefile using `geopandas.read_file` but it gives an error. My commands are as follows:

`import geopandas as gp`
`fl=r"M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp"`
`data=gp.read_file(fl)`

The error I am getting is as follows:

`TypeError: invalid path: UnparsedPath(path='M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')`

**Comment by martinfleis** [comment]
Hi,
thank you for the report. I am looking at your question on SO (https://stackoverflow.com/questions/56697108/error-reading-shapefile-with-geopandas-in-python) and I don't think it is a GeoPandas issue. 
Try whether the issue persists if you open your file directly with Fiona.

    import fiona
    c = fiona.open('M:/rathore/vic_5km/L2_data/L2_data/DAMSELFISH_distributions.shp')

If so, you can try report it to Fiona, as it seems to be an issue on their side. It is hard to debug as it is not replicable.

**Comment by jorisvandenbossche** [comment]
This was also further discussed in https://github.com/Toblerity/Fiona/issues/767, so closing here
