### ISSUE TITLE
Windows + Python 2.7 CI build is broken (installation issue)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1022]
Just a note that currently Appveyor is red on master (and all PRs) due to an installation problem of the conda env. See eg https://ci.appveyor.com/project/jorisvandenbossche/geopandas-us6w0/builds/25467210/job/c50x207nmv6881nb

The underlying issue is that conda-forge doesn't support gdal for windows + Python 2.7, so it is mixing things with defaults. 

We could still try to do the full env from defaults. Or, alternatively, drop the windows python 2.7 build (eg replace with an extra py3 build). Python 2 is still tested on Travis for the time being (until we drop support).

**Comment by martinfleis** [comment]
> until we drop support

Are there specific plans when? We might want to announce it ahead.

**Comment by jorisvandenbossche** [comment]
No specific plans, opened an issue about it -> https://github.com/geopandas/geopandas/issues/1031
