### ISSUE TITLE
TST: maplassify test broken

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1025]
I suppose the recent mapclassify release now produces different output for some of the classifications, which broke our tests because we are checking the exact legend content (which is based on the mapclassify result).

See eg https://travis-ci.org/geopandas/geopandas/jobs/551597804, which gives:

```
_________________ TestMapclassifyPlotting.test_negative_legend _________________
self = <geopandas.tests.test_plotting.TestMapclassifyPlotting object at 0x7f30544255c0>
    def test_negative_legend(self):
        ax = self.df.plot(column='NEGATIVES', scheme='FISHER_JENKS', k=3,
                          cmap='OrRd', legend=True)
        labels = [t.get_text() for t in ax.get_legend().get_texts()]
        expected = [u'-10.00 - -3.41', u'-3.41 - 3.30', u'3.30 - 10.00']
>       assert labels == expected
E       AssertionError: assert ['-10.00 - -6...6.02 - 10.00'] == ['-10.00 - -3....3.30 - 10.00']
E         At index 0 diff: '-10.00 - -6.02' != '-10.00 - -3.41'
E         Left contains 2 more items, first extra item: '2.05 - 6.02'
E         Full diff:
E         + ['-10.00 - -3.41', '-3.41 - 3.30', '3.30 - 10.00']
E         - ['-10.00 - -6.02',
E         -  '-6.02 - -1.93',
E         -  '-1.93 - 2.05',
E         -  '2.05 - 6.02',
E         -  '6.02 - 10.00']
geopandas/tests/test_plotting.py:425: AssertionError
```

cc @ljwolf

**Comment by jorisvandenbossche** [comment]
Didn't try it locally yet, but now looking at the error message above, it seems that `k=3` was passed but that the output is no longer a list of three labels, but of 5. So in some way the specification of 3 classes is not recognized by mapclassify anymore.

**Comment by martinfleis** [comment]
I have found the reason. mapclassify is changing names of classifiers, so `Fisher_Jenks` is now deprecated in favour of `FisherJenks`. Because not every classifier allows predefined number of bins `k` we are checking it and drop `k` if it is not supported.

    spec = getspec(schemes[scheme].__init__)
            if 'k' not in spec.args:
                del classification_kwds['k']

`mc.classifiers.Fisher_Jenks.__init__` now yields mapclassify.classifiers.DeprecationHelper not classifier itself, so k is not in args and is dropped.

I can think of two things which should be done. 
1) Update `CLASSIFIERS` in mapclassify to reflect existing situation (cc @sjsrey).
2) We might want to check passed `scheme` arg and remove underscores.

**Comment by sjsrey** [comment]
The changes in mapclassify are for renaming to be consistent with PEP-8 (and some minor enhancements). The deprecated classifiers should return the same classification results, but they were changed to wrapper functions that return instances of the newly named classifiers. That strategy is inducing the breakage here. 

I could do a pr to reflect the new name changes here.  Let me know if that would be of interest. Alternatively, I could look into modification of `CLASSIFIERS` in mapclassify as @martinfleis suggests.

**Comment by sjsrey** [comment]
With the changes in [mapclassify](https://github.com/pysal/mapclassify/pull/40) and proposed in  [geopandas](https://github.com/geopandas/geopandas/compare/master...sjsrey:mcfix?expand=1), the tests are passing locally for me.

I will be cutting a release of mapclassify on pip later today. Will also [PR](https://github.com/geopandas/geopandas/compare/master...sjsrey:mcfix?expand=1) once that is done, if that helps?

**Comment by martinfleis** [comment]
Thanks for this work. This fixes our tests and import of classifiers, but we will not be able to provide any deprecation period. It just cutoff all renamed classifiers, because we are checking the validity of passed `scheme` argument against `mapclassify.classifiers.CLASSIFIERS`. I would rather do some additional work on our side to keep deprecation warning for some time (in line with mapclassify). Like transform inputs like `Fisher_Jenks` to `FisherJenks` while raising deprecation warning. That seems to be the cleanest solution for now. @jorisvandenbossche what do you think?

**Comment by jorisvandenbossche** [comment]
Yes, that sounds a good idea. It should not be that hard to map the existing names with underscores to the new names (although this probably needs to depend on the mapclassify version).

**Comment by ljwolf** [comment]
we can probably play with something like `mapclassify.classifiers.CLASSIFIERS.get(new_name, old_name)` to avoid explicit version checking against mapclassify?

**Comment by sjsrey** [comment]
> Thanks for this work. This fixes our tests and import of classifiers, but we will not be able to provide any deprecation period. It just cutoff all renamed classifiers, because we are checking the validity of passed `scheme` argument against `mapclassify.classifiers.CLASSIFIERS`. I would rather do some additional work on our side to keep deprecation warning for some time (in line with mapclassify). Like transform inputs like `Fisher_Jenks` to `FisherJenks` while raising deprecation warning. That seems to be the cleanest solution for now. @jorisvandenbossche what do you think?

Once mapclassify 2.1.1 is on conda, [this](https://github.com/sjsrey/geopandas/commit/177591be0209ecf317f3e9cfc7d8528e3d3197a0) should handle the test failure _and_ allow for the deprecation warnings.

**Comment by martinfleis** [comment]
Have you tried it? I think it will drop `k=3` in the next step because `spec = getspec(schemes[scheme].__init__)`  will give us `mapclassify.classifiers.DeprecationHelper` where `k` is not an argument.

    if classification_kwds['k'] is not None:
            try:
                from inspect import getfullargspec as getspec
            except ImportError:
                from inspect import getargspec as getspec
            spec = getspec(schemes[scheme].__init__)
            if 'k' not in spec.args:
                del classification_kwds['k']

**Comment by sjsrey** [comment]
I did run it locally with mapclassify 2.1.1 and all the tests in geopandas pass.
Because of the rewrite, `getspec(schemes[scheme].__init__)` should no longer return `mapclassify.classifiers.DeprecationHelper`.

**Comment by sjsrey** [comment]
> I did run it locally with mapclassify 2.1.1 and all the tests in geopandas pass.
> Because of the rewrite, `getspec(schemes[scheme].__init__)` should no longer return `mapclassify.classifiers.DeprecationHelper`.

It appears to be passing on travis for the [builds](https://travis-ci.org/sjsrey/geopandas/builds/551885216) that are using mapclassify 2.1.1.

**Comment by jorisvandenbossche** [comment]
@sjsrey thanks! I opened a PR from your commit, and added some changes to add compatibility for older versions / people specifying the older name.

**Comment by jorisvandenbossche** [comment]
PR is here: https://github.com/geopandas/geopandas/pull/1033

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/geopandas/geopandas/pull/1033

**Comment by jorisvandenbossche** [comment]
Would it be worth to do a 0.5.1 bug fix release with this patch?

**Comment by martinfleis** [comment]
I think it might be worth it. Having mapclassify 2.1.1. in env now breaks most of "old" plotting schemes without deprecation warning. Regarding #1033, do you want to keep backward compatibility with underscore names forever? It might cause incoherence in future. You might have `NewClassifier` added to mapclassify and while `fisher_jenks` and `fisherjenks` will both work, `new_classifier` will not (without bug fix from our side, but we added import from `mapclassify.classifiers.CLASSIFIERS` specifically for the reason of enabling "automatic" support of new schemes).

I would follow mapclassify's example and go for deprecation of underscores. So yes, release bug fix, but include deprecation warning for underscores.

**Comment by jorisvandenbossche** [comment]
> Regarding #1033, do you want to keep backward compatibility with underscore names forever?

Certainly not forever, but I thought to not yet warn right now. We still need the old option for people running older version of mapclassify anyway, so it would only be a warning depending on the version of mapclassify. 

Maybe doing the bug fix release with the PR as is (no warning), and then add a warning in master?

**Comment by martinfleis** [comment]
> Maybe doing the bug fix release with the PR as is (no warning), and then add a warning in master?

That sounds like a good plan to me.

**Comment by jorisvandenbossche** [comment]
Bugfix release is on pypi! https://pypi.org/project/geopandas/ 
(conda-forge will automatically follow shortly)
