### ISSUE TITLE
[Feature Request] add "projection" or "crs" arg in .plot()

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1028]
I often found myself changing the `crs` of a `GeoDataFrame` not because of any geometric reasons but simply want the plot to look better.  

I think it might be convenient  to use a `projection` or `crs` arg in the `.plot()` function than changing the `crs`

**Comment by ljwolf** [comment]
Would method chaining work well enough for you?

`usa.to_crs(epsg=5070).plot()`

**Comment by StevenLi-DS** [comment]
@ljwolf 
OMG...
Of course, this would work. (Asking stupid questions should be a symptom of lack of sleep)
feel free to close...😂
