### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1031]
We should decide on when to drop Python 2.7 support, so that we can announce it somewhat in advance.

Proposal: make the upcoming 0.6 release (https://github.com/geopandas/geopandas/issues/1001, with the ExtensionArray work) the last one to support Python 2. And then drop Python 2 for the 0.7 after that (which will probably be the initial cython work).

cc @geopandas/collaborators

**Comment by martinfleis** [comment]
Sounds good to me. I don't think there is a reason to keep the support for a longer period than this.
