### ISSUE TITLE
Vendoring descartes? (or take over functionality)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1039]
Triggered by https://github.com/conda-forge/geopandas-feedstock/pull/59, where matplotlib and descartes are removed from the packages that are automatically installed for geopandas (note: only for conda of course, not for pip), I was wondering if it would be an idea to vendor descartes. In the end, it is less than 100 lines of code and rather stable (not much changes over the last years).

Reason I was thinking this: people installing geopandas will quite often have matplotlib installed as well. But, plotting (polygons) still does not work out of the box in such a case, for that people have to install descartes as well. 
It would be nice if plotting "just works" (in case if matplotlib is already installed of course).

On the other hand, doing a `conda/pip install descartes` is also not that hard (it's an easy pure python package to install), certainly if we give a good error message. 
And you could say the same for mapclassify ..

cc @sgillies

**Comment by jorisvandenbossche** [comment]
We should at least update the installation notes (https://geopandas.readthedocs.io/en/latest/install.html) to make clearly mention how to install "essential" optional packages as well.

**Comment by sgillies** [comment]
👍 to vendoring or copying descartes. I don't have any plans to make another release of that project or keep it up to date with future versions of matplotlib, so bringing it inside geopandas could remove a fragile dependency.

**Comment by jorisvandenbossche** [comment]
@sgillies Thanks for that feedback, that's good to know

cc @ResidentMario might be relevant for you as well

**Comment by ResidentMario** [comment]
@jorisvandenbossche that's :+1: with me.

**Comment by jorisvandenbossche** [comment]
Another option would also be to take over maintenance (if that is something that @sgillies would be fine with)

@ResidentMario the "that's fine with me", was that towards the "vendoring descartes in geopandas" ? But, would you in such a case want to rely on the functionality for that from geopandas instead of relying on descartes (for the latest versions). 
If we are both using it, it would be good to have a single maintained version. So that could be included in geopandas, but as above, we could also keep it in descartes if we maintain it ourselves.

**Comment by martinfleis** [comment]
If we want to take over, does it make sense to keep it as a separate package if it is just 100 lines? I would vote for vendoring it in geopandas. It just complicates maintenance.

**Comment by ResidentMario** [comment]
`npm` has plenty of code packages that are 100 lines or less. There's less of a tradition of this in Python, but `descartes` does seem to me to be a package whose size crosses the threshold of having a feature-set large enough and complex enough to warrant being its own package.

Vendoring `descartes` would mean adding this functionality to `geopandas`, which would mean expanding the scope of the project somewhat. It would also mean that other projects that rely on `descartes`, the Python package, would fall behind the geopandas-vendored version of the library in code recency. And there's [a nontrivial amount of such projects](https://github.com/search?l=Python&o=desc&q=%22import+descartes%22&s=indexed&type=Code).

Overall I'm fine with either (1) vendoring it or (2) transferring ownership to e.g. `geopandas/descartes` and maintaining it as part of the `geopandas` org. But preference for the latter.

**Comment by jorisvandenbossche** [comment]
> adding this functionality to geopandas, which would mean expanding the scope of the project somewhat.

I think the expansion of scope is quite OK (we already have quite some code for handling the plotting). Looking at the descartes code again, and factoring away the code in there that is only needed for handling non-shapely geometries or other geom types, the code we need is basically:

```
from matplotlib.patches import PathPatch
from matplotlib.path import Path
from numpy import asarray, concatenate, ones


def PolygonPatch(polygon, **kwargs):

    def coding(ob):
        # The codes will be all "LINETO" commands, except for "MOVETO"s at the
        # beginning of each subpath
        n = len(getattr(ob, 'coords', None) or ob)
        vals = np.ones(n, dtype=Path.code_type) * Path.LINETO
        vals[0] = Path.MOVETO
        return vals

    vertices = np.concatenate(
        [np.asarray(polygon.exterior)[:, :2]] +
        [np.asarray(r)[:, :2] for r in polygon.interiors])
    codes = np.concatenate(
        [coding(polygon.exterior)] + [coding(r) for r in polygon.interiors])

    return PathPatch(Path(vertices, codes), **kwargs)
```

So if we include this functionality in geopandas, I would probably not even "vendor" descartes, but just include an adapted version of that in `plotting.py`.

**Comment by lwasser** [comment]
hey colleagues @jorisvandenbossche @martinfleis did you guys decide to vendor descartes? i'm asking because we ran into the issue in one of our packages of needing descartes and i'm trying to decide how to handle this dependency / separate install? What do you guys recommend? should we make it a dependency? we are essentially [testing geopandas plots](https://github.com/earthlab/matplotcheck/pull/188) and we test polygons! 
many thanks for any suggestions. 

@nkorinek just a note that i'm exploring options here for matplotcheck !!

**Comment by tacaswell** [comment]
If the full code really is just that snippet, this seems like something that can just go upstream in Matplotlib (but probably as a PathPatch sub-class rather than a camel-case function).  While we are trying to avoid growing the scope of Matplotlib, a 15 line class that supports a common data structure does not seem to be too heavy a of a lift to me.

I don't think we would want to add new Axes / pyplot API for it, just the class.

Could that code be pushed into shapely?

**Comment by martinfleis** [comment]
Getting back to this. After seeing the discussion in https://github.com/matplotlib/matplotlib/issues/16662 it seems that the best solution would be to include that snippet above in geopandas.

**Comment by jorisvandenbossche** [comment]
I opened https://github.com/geopandas/geopandas/pull/1677 to stop using descartes. Short term, that's certainly the best solution, as I also need to modify the code to keep plotting working with the Shapely 2.0 changes, and Sean indicated he is not planning to maintain or make any new release of descartes.

Longer term, I think it could still be worth thinking about having something similar in other projects. For example, matplotlib could have the code without relying on the exact geometry object structure, but eg expecting a exterior/interiors coordinate arrays. Also, Shapely will have to include some of descartes code to keep making its documention illustrations. 
(but strictly speaking, that's not geopandas' concern, so let's discuss that over there in those packages)

Probably something we should decide, though, is how "public" we make our version of PolygonPatch (for example for projects like geoplot that currently also use descartes, and will need an alternative)

**Comment by jorisvandenbossche** [comment]
PR is merged, so with the next geopandas release, we will no longer require `descartes` for plotting polygons!

A note to people / other pojects using the `descartes` package directly: it is no longer maintained, so you should best stop using it as well (@sgillies indicated above he doesn't intent to make more releases, and the repo on bitbucket also got lost in bitbucket's aggressive mercurial sunsetting). 
Now, the alternattive is only a few lines with matplotlib for a polygon:

```python
from matplotlib.patches import PathPatch
from matplotlib.path import Path

pach = PathPatch(
    Path.make_compound_path(
        Path(np.asarray(polygon.exterior.coords)[:, :2]),
        *[Path(np.asarray(ring.coords)[:, :2]) for ring in polygon.interiors]
    )
)
```

(for multipolgyon, need to repeat the compound path for each part)

**Comment by lwasser** [comment]
thank you  for  this update @jorisvandenbossche quick question: does `.plot()` still work for plotting polygons as it used  to? 
this is great to have one less dependency!! thank you for that!

**Comment by jorisvandenbossche** [comment]
> does .plot() still work for plotting polygons as it used to?

Certainly! That still works exactly the same as it used to be, but now it does that without needing the descartes dependency

**Comment by lwasser** [comment]
that's  so wonderful!! thank you for this @jorisvandenbossche   we will be sure to update to the newest  release once  it is out!! 🎉  !!!
