### ISSUE TITLE
DOC: Some methods (explode, collect) are missing in docs

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1052]
There are couple of methods in the code which are not included in the documentation (even though they have docstrings) like `explode()` and `collect()`. We should check which methods are missing and add them to reference guide and at least `explode()` should be included in the user guide as well.

I will do that myself, I just wanted to point out that it is happening, so we can think about possible prevention in the future.

**Comment by jorisvandenbossche** [comment]
> collect()

I was going to ask "do you mean dissolve() instead of collect()", because I wasn't even aware of this function :-)

`explode()` should indeed certainly be added to the reference (and somewhere in the user guide ideally as well, or an example).

**Comment by awa5114** [comment]
In an attempt to address this I tried to `make html` as the "Contributing to geopandas" part of the website suggests. Since I am cloning the `geopandas` project from my fork of the master repo, I am importing geopandas directly from my current working directory. My local clone then in turn imports supporting dependencies from a dedicated conda environment, which does not have `geopandas` installed. 

After installing `sphinx` in this dedicated environment, I navigated to the `doc` folder and did the following:

```
(geopandas-dev) D:\github_projects\geopandas\doc>make html
```

This gave me an error as shown below.  

```
Running Sphinx v2.1.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\geopandas-dev\lib\site-packages\sphinx\config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\geopandas-dev\lib\site-packages\sphinx\util\pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "D:\github_projects\geopandas\doc\source\conf.py", line 87, in <module>
    import geopandas
ModuleNotFoundError: No module named 'geopandas'
```
So then I tried making the html from a location where `geopandas` could be found.

```
(geopandas-dev) D:\github_projects\geopandas\doc>cd ../

(geopandas-dev) D:\github_projects\geopandas>.\doc\make.bat html
```
I got a new error this time:

```
Application error:
config directory doesn't contain a conf.py file (source)
```
I also did not find the `config.py` directory anywhere in the `geopandas` project. Could anyone please help? Thanks....

**Comment by martinfleis** [comment]
You can install your forked version of Geopandas to your env, that should resolve it.

    cd D:\github_projects\geopandas
    pip install .

However, if you did not make conda env from `environment.yml` in `doc` I would recommend doing it just for generating of html. We have pinned versions of dependencies and it also includes all sphinx extensions. Actually, ideally use `environment.yml` from #1054.

**Comment by martinfleis** [comment]
@awa5114 Do you plan to address this issue? I have started and then stopped after you mentioned that you are working on it. Just to know whether wait or proceed.

**Comment by awa5114** [comment]
I would like to work on it, but if it is something which needs to be fixed immediately I don't want to be an obstacle. I am new to making contributions and trying to finish off this one https://github.com/geopandas/geopandas/pull/1009 first. 

In any case if you don't mind leaving it to me I will get to it ASAP.

**Comment by martinfleis** [comment]
@awa5114 no rush, this is just documentation, nothing crucial. It is yours :). Thanks!

**Comment by awa5114** [comment]
It seems like the only way of working on the documentation is by creating a new environment `geopandas_docs` and `pip install .` to install local copy of `geopandas` into this new documentation environment. 

I would much rather keep all my geopandas contribution work in one environment called `geopandas-dev`, including the documentation. It seems inefficient to have to `pip install .` after every code update in order to work on the documentation.

Unfortunately, `make html` can only be run when inside the `doc` folder. `make html` also needs to be able to import `geopandas`, but if the current working directory is `docs`, `geopandas` is one level above and so cannot be found.

Is there a way to work on the documentation without having a separate environment dedicated to this purpose? Such that you wouldn't have to do `pip install .` after every `git pull`?

**Comment by martinfleis** [comment]
If your `geopandas-dev` environment is compatible with the one defined in `environment.yml` in `doc`, that should not be an issue. However, I generally recommend using separate environments. 

As our contributing guidelines say, you can use `python setup.py develop` instead of `pip install .`. That should only link the folder to your environment and every import of geopandas should read the latest changes in the code.

**Comment by awa5114** [comment]
My `geopandas-dev` environment is compatible with the one defined in `environment.yml` in `doc`. Also `python setup.py develop` seems to help. Previously I had only done `python setup.py`. Now the **local** geopandas is found from within the `doc` folder. However I still have a bunch of warnings and errors:

> <<<-------------------------------------------------------------------------
> reading sources... [100%] set_operations
> internal padding after D:\github_projects\geopandas\doc\source\aggregation_with_dissolve.rst:24: WARNING: image file not readable: savefigcontine
> nts1.png
> internal padding after D:\github_projects\geopandas\doc\source\aggregation_with_dissolve.rst:24: WARNING: image file not readable: savefigcontine
> nts2.png
> internal padding after D:\github_projects\geopandas\doc\source\data_structures.rst:20: WARNING: image file not readable: savefigworld_borders.png
> 
> internal padding after D:\github_projects\geopandas\doc\source\data_structures.rst:12: WARNING: image file not readable: savefigworld_centroids.p
> ng
> internal padding after D:\github_projects\geopandas\doc\source\geocoding.rst:36: WARNING: image file not readable: savefigboro_centers_over_bound
> s.png
> internal padding after D:\github_projects\geopandas\doc\source\indexing.rst:12: WARNING: image file not readable: savefigworld_southern.png
> internal padding after D:\github_projects\geopandas\doc\source\mapping.rst:19: WARNING: image file not readable: savefigworld_randomcolors.png
> internal padding after D:\github_projects\geopandas\doc\source\mapping.rst:13: WARNING: image file not readable: savefigworld_gdp_per_cap.png
> internal padding after D:\github_projects\geopandas\doc\source\mapping.rst:14: WARNING: image file not readable: savefigworld_pop_est.png
> internal padding after D:\github_projects\geopandas\doc\source\mapping.rst:18: WARNING: image file not readable: savefigworld_pop_est_fixed_legen
> d_height.png
> internal padding after D:\github_projects\geopandas\doc\source\mapping.rst:8: WARNING: image file not readable: savefigworld_gdp_per_cap_red.png
> internal padding after D:\github_projects\geopandas\doc\source\mapping.rst:8: WARNING: image file not readable: savefigworld_gdp_per_cap_quantile
> s.png
> internal padding after D:\github_projects\geopandas\doc\source\mapping.rst:16: WARNING: image file not readable: savefigcapitals.png
> internal padding after D:\github_projects\geopandas\doc\source\mapping.rst:10: WARNING: image file not readable: savefigcapitals_over_countries_1
> .png
> internal padding after D:\github_projects\geopandas\doc\source\mapping.rst:23: WARNING: image file not readable: savefigcapitals_over_countries_2
> .png
> D:\github_projects\geopandas\doc\source\projections.rst:28: WARNING: image file not readable: savefigworld_starting.png
> internal padding after D:\github_projects\geopandas\doc\source\projections.rst:31: WARNING: image file not readable: savefigworld_reproj.png
> D:\github_projects\geopandas\doc\source\reference\geopandas.GeoSeries.rst:11: WARNING: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'source/reference/geopandas.GeoSeries.examples'.
> D:\github_projects\geopandas\doc\source\reference\geopandas.overlay.rst:11: WARNING: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'source/reference/geopandas.overlay.examples'.
> D:\github_projects\geopandas\doc\source\reference\geopandas.sjoin.rst:11: WARNING: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'source/reference/geopandas.sjoin.examples'.
> D:\github_projects\geopandas\doc\source\reference\geopandas.tools.geocode.rst:11: WARNING: Problems with "include" directive path:
> InputError: [Errno 2] No such file or directory: 'source/reference/geopandas.tools.geocode.examples'.
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigoverlay_example.png
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigoverlay_example_union.png
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigoverlay_example_intersection.png
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigoverlay_example_symdiff.png
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigoverlay_example_difference.png
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigoverlay_example_identity.png
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigworld_basic.png
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigcapital_buffers.png
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigcountry_cores.png
> D:\github_projects\geopandas\doc\source\set_operations.rst:: WARNING: image file not readable: savefigcountry_peripheries.png
>

**Comment by martinfleis** [comment]
@awa5114 I assume that you are not changing any of these files, right? sphinx sometimes behaves weirdly in different environments. In the end, you are not pushing built docs anyway, only source rst files, so you might even happily ignore these. If the change you made renders correctly, it should be fine. We will check changes in PR later, to make sure that everything is correct.

**Comment by awa5114** [comment]
No, not changing any of these....

**Comment by awa5114** [comment]
No. Not changing any of these. I'm using a Windows machine. That shouldn't be a problem right?

**Comment by martinfleis** [comment]
@awa5114 not sure, I always fight with sphinx myself :). Check if the page you changed renders correctly. If you don't change anything else, you can ignore these warnings for now.

**Comment by StevenLi-DS** [comment]
Just a note: 
the `dissolve` method is also missing from the reference page http://geopandas.org/reference.html
