### ISSUE TITLE
ENH: add rename_geometry() method

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1053]
As @jorisvandenbossche mentioned in #1038, we should have a `rename_geometry()` method, because currently renaming the geometry column needs something like `.rename(columns={'my_geom': 'geometry'}).set_geometry('geometry')`. 

It should not be complicated to do it.

I imagine something like `df.rename_geometry('new_name')` to make it as simple as possible.

**Comment by aalva14** [comment]
Hi I will be looking into this.

**Comment by awa5114** [comment]
@martinfleis  Do you guys reserve issues for specific users like @aalva14 in this case or can anyone jump in and suggest a pull request?

**Comment by jorisvandenbossche** [comment]
Since @aalva14 commented first, let's give them some time to do a PR.

**Comment by awa5114** [comment]
sounds good.

**Comment by awa5114** [comment]
Shouldn't this issue be closed? It seems like the changes have been merged with no problems?

**Comment by martinfleis** [comment]
Yes. Closing, thanks!
