### ISSUE TITLE
Install GeoPandas 5.0 from Conda

### ISSUE THREAD

**Issue by JimShady** [geopandas/geopandas#1055]
Continuing discussion from here:

https://github.com/geopandas/geopandas/issues/1003#issuecomment-510525667

It seems I need to update GeoPandas to v.5 using Conda to improve performance of to_crs(). Could someone suggest how please?

    conda install -c conda-forge geopandas=5.0
    Solving environment: failed
    
    PackagesNotFoundError: The following packages are not available from current channels:
    
      - geopandas=5.0

Thanks.

**Comment by martinfleis** [comment]
Current geopandas version is 0.5.0, not 5.0. You have to pin it as `geopandas=0.5.0`.

**Comment by JimShady** [comment]
Sorry about that. Thanks. Now installed. It's likely I'll see speed improvements of ``to_crs`` now ?

**Comment by martinfleis** [comment]
You should, there has been some work done in #962. If not, let us know. As this issue is about installing, which is now resolved I will close it. If you want to discuss `to_crs` performance more, follow @jorisvandenbossche advice and open a new issue specifically for that.
