### ISSUE TITLE
Lat Long order is wrong in WKT example

### ISSUE THREAD

**Issue by meetyg** [geopandas/geopandas#1060]
In regards to documentation of converting WKT format to geopandas GeoDataFrame, the order of LAT LONG is wrong.
See #690 
In the WKT POINT, you put the Lat first, amd then Long. It should be the opposite. 
When plotting the WKT example, and comparing it to the simple Long Lat example, you can clearly see that the WKT points are not placed where they should be.

From what I understand, WKT should follow the WGS84 standard.
See for example: https://www.drupal.org/project/geo/issues/511370

**Comment by leblancfg** [comment]
Offending lines are: https://github.com/geopandas/geopandas/blob/a20ac9c816e809fa021ed5fb7309b7f09b2acb64/examples/create_geopandas_from_pandas.py#L64-L69

Plotting the GeoDataFrame for the example would be a good idea too.
