### ISSUE TITLE
ask for help "how geodataframe implemented" (any process return an geodataframe with crs)

### ISSUE THREAD

**Issue by yxdragon** [geopandas/geopandas#1069]
Hi, geopandas's devolopers, may be this question should not be asked here, but I am a little tired to find the maillist, sorry!

I am writting a ui framework for image and dataframe analysis, [ImagePy](https://github.com/Image-Py/imagepy), It support image and dataframe well, and give a friendly activity ui. So I want to write some plugin wrapper geopandas and gdal, then build a tool like arcgis.

I see geodataframe extends the dataframe, and add some other properties, such as crs. It is very pythonic, but gdal is not as friendly as geopandas, So I want build a geo image analysis library based on numpy, use scikit-image, opencv for image processing. Python has many function for image process, but now I must make a dictionary for re build the result. (got img from dictionary, do some process, got an new numpy array, then treat the transfrom matrix, crs, then build a dictionary). 

So my question is *How can I add transform matrix and crs in numpy object, and when I do any process, the result would has the crs automotely* (just like geodataframe do). maybe it is not esay, any advice or tips is ok.

**Comment by jorisvandenbossche** [comment]
Hi @yxdragon sorry for the late reply

> How can I add transform matrix and crs in numpy object, and when I do any process, the result would has the crs automotely (just like geodataframe do). maybe it is not esay, any advice or tips is ok.

If you want something like that (having metadata attached to an array), I think subclassing numpy array or creating a "duck array" (that can hold a numpy array under the hood) is needed, which can be quite some work. 
However, I would encourage to look at existing libraries that already partly provide this. One this `rasterio` which is a pythonic interface to GDAL and works with numpy arrays (https://rasterio.readthedocs.io/en/stable/), and the other is `xarray` which already provides a array-like data structures which can hold metadata like CRS (http://xarray.pydata.org/en/stable/index.html). There are already a lot of people using combining xarray and rasterio for working with raster data.

**Comment by snowman2** [comment]
For reference: https://github.com/corteva/rioxarray

**Comment by jorisvandenbossche** [comment]
Closing this issue as there is nothing directly actionable for geopandas
