### ISSUE TITLE
geoseries copy

### ISSUE THREAD

**Issue by mattijn** [geopandas/geopandas#1070]
As is mentioned in the [docstring](https://github.com/geopandas/geopandas/blob/master/geopandas/geoseries.py#L230:L237) of `geoseries.copy`:

```python
def copy(self, order='C'):
    """
    Make a copy of this GeoSeries object
    Parameters
    ----------
    deep : boolean, default True
        Make a deep copy, i.e. also copy data
    Returns
    -------
    copy : GeoSeries
    """
```

But this doesn't work:
```python
import geopandas
gs = geopandas.GeoSeries([1, 2, 3])
gs.copy(deep=True)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-69-6889712626ae> in <module>
      1 import geopandas
      2 gs = geopandas.GeoSeries([1, 2, 3])
----> 3 gs.copy(deep=True)

TypeError: copy() got an unexpected keyword argument 'deep'
```

**Comment by jorisvandenbossche** [comment]
Thanks for the report, the docstring and the actual function are indeed not matching. We can fix that, but from looking at the comment in the `GeoSeries.copy` implementation:

https://github.com/geopandas/geopandas/blob/8c42164559173972e7a4bafe705bbb2987d15d47/geopandas/geoseries.py#L246

it seems we can simply remove this function now (and directly inherit from pandas, which should have the correct docstring)

PRs always welcome!
