### ISSUE TITLE
Spatial join error after using `explode()`

### ISSUE THREAD

**Issue by HTenkanen** [geopandas/geopandas#1074]
@jorisvandenbossche There is a specific situation that produces an error with `.sjoin()`. 

I receive a following error: 
```
  File "C:\Hyapp\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 1330, in set_names
    raise TypeError("Must pass list-like as `names`.")

TypeError: Must pass list-like as `names`.
```

I was able to narrow this down, and the error only happens after using `df.explode()` function to turn MultiPolygons into multiple Polygons. 

Here is an example to produce the error using some data from OSM: 
```
# Test to produce an error
import osmnx as ox
import geopandas as gpd
buildings = ox.footprints_from_place("Punavuori, Finland")
buildings = buildings.explode()
landuse = ox.footprints_from_place("Punavuori, Finland", 'landuse')
join = gpd.sjoin(buildings, landuse)
```

The solution for fixing this was to `reset_index()` after using the `.explode()`. I am not sure if this is a bug or expected behavior, but wanted to report my findings anyway. 🙂

**Comment by jorisvandenbossche** [comment]
Thanks for the reproducible example! 
The `explode` method results in a geodataframe with a MultiIndex, and this seems to result in that failure. So resetting the index is indeed a good workaround for now. We should look in general at how MultiIndex is supported (or not) in spatial join.
