### ISSUE TITLE
Pull `mapclassify` from `pysal`

### ISSUE THREAD

**Issue by darribas** [geopandas/geopandas#1081]
Currently, if the user wants to make a choropleth, `geopandas` requires `mapclassify`, part of the `pysal` family. This is convenient because it allows `geopandas` to install only the classifiers and avoid, if the user wants, all the other libraries. However, if a user has installed a full `pysal` version (e.g. 2.1), but not classify, `geopandas.plot(scheme=)` will fail as it will not find an independent version of mapclassify. Would it be possible to make an extra check (maybe [here](https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L557)) to see if `import mapclassify` fails, whether `import pysal.viz.mapclassify` works? That'd avoid duplicating an install on the user's system.

**Comment by jorisvandenbossche** [comment]
So if you install pysal, it does *not* install the separate packages? (I assumed it would, and it then imports that package if you access `pysal.viz.mapclassify`)

**Comment by martinfleis** [comment]
@jorisvandenbossche `pysal` currently duplicates the code base in this case. It has everything within `pysal` package and then parts of it are also released separately, like `mapclassify` or `libpysal`. So with this design, it makes sense for `geopandas` to check for both. However, I agree with you that having it vice versa (load packages to `pysal`) would make much more sense.

**Comment by jorisvandenbossche** [comment]
@darribas so this was added now. I suppose this decision is done ;) but personally I find it a bit confusing to have a copy of the code in two places, I expected pysal to be kind of a "meta-package" that ensures you can install all things in one go and access it from the same place, but by importing the standalone packages.
