### ISSUE TITLE
ENH: choropleth legend formatting

### ISSUE THREAD

**Issue by sjsrey** [geopandas/geopandas#1087]
This is using master of [mapclassify](https://github.com/sjsrey/mapclassify) where some enhancements for legend handling are being considered. The motivation is to be more explicit in the formatting of the legends from these classifiers to have their definition be unambiguous.

I've been exploring their use with geopandas and am opening this to get feedback/ideas.

Below are excerpts from the [example notebook](https://github.com/sjsrey/geopandas/blob/mcm/examples/choro_legends.ipynb):

![2019-08-11-1034-1565544885-sel](https://user-images.githubusercontent.com/118042/62837388-b058d600-bc23-11e9-8879-20a30e87bbe4.png)

![2019-08-11-1043-1565545387-sel](https://user-images.githubusercontent.com/118042/62837484-d763d780-bc24-11e9-871d-091f4fe72a46.png)

![2019-08-11-1047-1565545623-sel](https://user-images.githubusercontent.com/118042/62837533-683ab300-bc25-11e9-8e91-56b06e12da68.png)

Related changes to geopandas to incorporate these enhancements are [here](https://github.com/geopandas/geopandas/compare/master...sjsrey:mcm?expand=1).  

## Release timing note
In terms of release cadence, the pysal meta package is back on a six month release cycle (end of january and july). mapclassify can be done more frequently. When the meta package is released, it includes the stable version of mapclassify at that point in time.

**Comment by martinfleis** [comment]
I like this a lot. Both clarification of intervals and formatting of numbers.

Regarding your changes to make this possible, if I am looking correctly, there are only a couple of lines, right? Can you, before making a PR, disable your automatic linter which is changing much more than this? 

If I understand correctly your timing note, time to implement this change will come after the end of January (to have it supported by both stable mapclassify and pysal)?

Thanks for this!

**Comment by sjsrey** [comment]
> I like this a lot. Both clarification of intervals and formatting of numbers.
> 

Cool.

> Regarding your changes to make this possible, if I am looking correctly, there are only a couple of lines, right? Can you, before making a PR, disable your automatic linter which is changing much more than this?

Yes, of course. Sorry about the noise induced in the diff.

Key changes: 
- plotting.py [Line 399](https://github.com/geopandas/geopandas/compare/master...sjsrey:mcm?expand=1#diff-9f920647ae0bb977ab8d642b436d8eacR399)
- plotting.py [Line 478](https://github.com/geopandas/geopandas/compare/master...sjsrey:mcm?expand=1#diff-9f920647ae0bb977ab8d642b436d8eacR478)
- test_plotting.py [Line 422](https://github.com/geopandas/geopandas/compare/master...sjsrey:mcm?expand=1#diff-04033cfa31e6e588e765d43278b20949R422)
- test_plotting.py [Line 430](https://github.com/geopandas/geopandas/compare/master...sjsrey:mcm?expand=1#diff-04033cfa31e6e588e765d43278b20949R430)
- test_plotting.py [Line 443](https://github.com/geopandas/geopandas/compare/master...sjsrey:mcm?expand=1#diff-04033cfa31e6e588e765d43278b20949R443)
> 
> If I understand correctly your timing note, time to implement this change will come after the end of January (to have it supported by both stable mapclassify and pysal)?

That would be the easiest path. If mapclassify gets bumped before then, the meta package and mapclassify would be out of sync so that could cause problems. Handling that might add more complexity than is desired. So waiting until the next meta release might be the way to go. Also gives time to add any enhancements others might want.
> 
> Thanks for this!

**Comment by sjsrey** [comment]
New branch diffs with [linting off](https://github.com/geopandas/geopandas/compare/master...sjsrey:legend?expand=1).

Demo [notebook](https://github.com/sjsrey/geopandas/blob/c4be55d08235428712dde0b0c6447a76eec6048f/examples/choro_legends.ipynb).

**Comment by sjsrey** [comment]
[New branch with linting off](https://github.com/geopandas/geopandas/compare/master...sjsrey:legend?expand=1).

Demo [notebook](https://github.com/sjsrey/geopandas/blob/c4be55d08235428712dde0b0c6447a76eec6048f/examples/choro_legends.ipynb).

**Comment by jorisvandenbossche** [comment]
Cool! Better formatting of the legend is certainly a welcome change. 

I am only wondering if we want to include the `fmt` in one of the other kwargs already (`classification_kwds`, `legend_kwds`), although it strictly does not fit in both (as it is passed to a different function). Just thinking that in the future, `get_legend_classes` might grow more keywords ..

The `mapclassify` and `pysal` possibly being out of sync is a bit annoying. BTW, we always first check for mapclassify, even if pysal might be more recent. Eg if a user initially installed mapclassify, and later also pysal. But then only updates pysal, geopandas will never see the "latest" mapclassify included in pysal.

**Comment by rbuffat** [comment]
@sjsrey your proposal looks very nice! Do you plan to create a PR?

**Comment by sjsrey** [comment]
@rbuffat Yes, hopefully within the next few weeks.

**Comment by sjsrey** [comment]
A new release of [mapclassify](https://github.com/pysal/mapclassify) is pending that provides this new [functionality](https://github.com/sjsrey/geopandas/blob/legendkwds/examples/choro_legends.ipynb).

@jorisvandenbossche I moved the `fmt` into `legend_kwds`.

I also have a local branch of geopandas using this functionality with everything passing locally.

The plan is to release mapclassify in the coming week, then do a pr into geopandas that incorporates the new mapclassify. In January a new version of pysal will be released that consumes the new mapclassify.
