### ISSUE TITLE
Nearest (spatial) join as a new feature to geopandas?

### ISSUE THREAD

**Issue by HTenkanen** [geopandas/geopandas#1096]
@jorisvandenbossche Sorry took awhile to come back to this. BUT. Would following nearest neighbor kind of spatial join be something that would be useful to be integrated into geopandas? 

I include a working piece of code and a test case to demonstrate the idea.

 - So here is the function:

```python
import geopandas as gpd
import osmnx as ox
from shapely.geometry import LineString

def sjoin_nearest(left_df, right_df, op='intersects', search_dist=0.03, report_dist=False,
                  lsuffix='left', rsuffix='right'):
    """
    Perform a spatial join between two input layers.
    If a geometry in left_df falls outside (all) geometries in right_df, the data from nearest Polygon will be used as a result.
    To make queries faster, "search_dist" -parameter (specified in map units) can be used to limit the search area for geometries around source points.
    If report_dist == True, the distance for closest geometry will be reported in a column called `dist`. If geometries intersect, the distance will be 0.

    """

    # Explode possible MultiGeometries
    right_df = right_df.explode()
    right_df = right_df.reset_index(drop=True)

    if 'index_left' in left_df.columns:
        left_df = left_df.drop('index_left', axis=1)

    if 'index_right' in left_df.columns:
        left_df = left_df.drop('index_right', axis=1)

    if report_dist:
        if 'dist' in left_df.columns:
            raise ValueError("'dist' column exists in the left DataFrame. Remove it, or set 'report_dist' to False.")

    # Get geometries that intersect or do not intersect polygons
    mask = left_df.intersects(right_df.unary_union)
    geoms_intersecting_polygons = left_df.loc[mask]
    geoms_outside_polygons = left_df.loc[~mask]

    # Make spatial join between points that fall inside the Polygons
    if geoms_intersecting_polygons.shape[0] > 0:
        pip_join = gpd.sjoin(left_df=geoms_intersecting_polygons, right_df=right_df, op=op)

        if report_dist:
            pip_join['dist'] = 0

    else:
        pip_join = gpd.GeoDataFrame()

    # Get nearest geometries
    closest_geometries = gpd.GeoDataFrame()

    # A tiny snap distance buffer is needed in some cases
    snap_dist = 0.00000005

    # Closest points from source-points to polygons
    for idx, geom in geoms_outside_polygons.iterrows():
        # Get geometries within search distance
        candidates = right_df.loc[right_df.intersects(geom[left_df.geometry.name].buffer(search_dist))]

        if len(candidates) == 0:
            continue
        unary = candidates.unary_union

        if unary.geom_type == 'Polygon':

            # Get exterior of the Polygon
            exterior = unary.exterior

            # Find a point from Polygons that is closest to the source point
            closest_geom = exterior.interpolate(exterior.project(geom[left_df.geometry.name]))

            if report_dist:
                distance = closest_geom.distance(geom[left_df.geometry.name])

            # Select the Polygon
            closest_poly = right_df.loc[right_df.intersects(closest_geom.buffer(snap_dist))]

        elif unary.geom_type == 'MultiPolygon':
            # Keep track of distance for closest polygon
            distance = 9999999999
            closest_geom = None

            for idx, poly in enumerate(unary):
                # Get exterior of the Polygon
                exterior = poly.exterior

                # Find a point from Polygons that is closest to the source point
                closest_candidate = exterior.interpolate(exterior.project(geom[left_df.geometry.name]))

                # Calculate distance between origin point and the closest point in Polygon
                dist = geom[left_df.geometry.name].distance(closest_candidate)

                # If the point is closer to given polygon update the info
                if dist < distance:
                    distance = dist
                    closest_geom = closest_candidate

            # Select the Polygon that was closest
            closest_poly = right_df.loc[right_df.intersects(closest_geom.buffer(snap_dist))]
        else:
            print("Incorrect input geometry type. Skipping ..")

        # Reset index
        geom = geom.to_frame().T.reset_index(drop=True)

        # Drop geometry from closest polygon
        closest_poly = closest_poly.drop(right_df.geometry.name, axis=1)
        closest_poly = closest_poly.reset_index(drop=True)

        # Join values
        join = geom.join(closest_poly, lsuffix='_%s' % lsuffix, rsuffix='_%s' % rsuffix)

        # Add information about distance to closest geometry if requested
        if report_dist:
            if 'dist' in join.columns:
                raise ValueError("'dist' column exists in the DataFrame. Remove it, or set 'report_dist' to False.")
            join['dist'] = distance

        closest_geometries = closest_geometries.append(join, ignore_index=True, sort=False)

    # Merge everything together
    result = pip_join.append(closest_geometries, ignore_index=True, sort=False)
    return result
```

- And this is how it works:

```python
# Get some data and prepare the data for demonstration
# -------------------------------------------------------------
place = "Kamppi, Helsinki"
polys = ox.footprints_from_place(place, footprint_type='building')
pois = ox.pois_from_place(place, amenities=['school'])

# Take a good sample for demonstration purposes (use mixture of points and polygons)
polys = polys.head(10).copy()
geom_mix = pois.head().copy()
geom_mix = geom_mix.append(pois.tail().copy())

# Add ids for the data for easier visual examination
polys['polyid'] = polys.reset_index().index
geom_mix['pointid'] = [a for a in 'abcdefghij']

# Plot the data and annotate ids
ax = polys.plot()
ax = geom_mix.plot(ax=ax, color='red', alpha=0.5)
polys.apply(lambda x: ax.annotate(s=x.polyid, xy=x.geometry.centroid.coords[0], ha='center'),axis=1);
geom_mix.apply(lambda x: ax.annotate(s=x.pointid, xy=x.geometry.centroid.coords[0], ha='center'),axis=1);
```
![before_join](https://user-images.githubusercontent.com/6659534/62884703-11b99b80-bd2f-11e9-95ae-8361b9cb9e1d.png)

So in this example above, the point `'e'` should get information from closest Polygon number 2, 
and point `'d'` should get information from Polygon 1, whereas red polygon `'j'` should get information from blue polygon 3 (most likely) and so on.

- We can conduct the spatial join in a similar manner as the `sjoin` but in this case the left_df will get information from the closest geometry in right_df in case it does not intersect with any geometries. By using parameter `report_dist` it is also possible to get information about the distance to the closest geometry (in map units). If the geometries intersect directly, the distance is 0. 

```python
# Let's test the nearest join and confirm if it works, let's also report the distance
nearest_join = sjoin_nearest(left_df=geom_mix, right_df=polys, report_dist=True)

# Let's confirm the join visually
lines = gpd.GeoDataFrame()
for idx, row in nearest_join.iterrows():
    a = polys.loc[polys['polyid']==row['polyid'], 'geometry'].centroid.values[0]
    b = geom_mix.loc[geom_mix['pointid']==row['pointid'], 'geometry'].centroid.values[0]
    line = LineString([a, b])
    lines = lines.append({'geometry': line}, ignore_index=True)
    
# Plot the data and annotate ids
ax = polys.plot()
ax = geom_mix.plot(ax=ax, color='red', alpha=0.5)
ax = lines.plot(ax=ax, color='orange', alpha=0.5)
polys.apply(lambda x: ax.annotate(s=x.polyid, xy=x.geometry.centroid.coords[0], ha='center'),axis=1);
geom_mix.apply(lambda x: ax.annotate(s=x.pointid, xy=x.geometry.centroid.coords[0], ha='center'),axis=1);

```
![correct_join](https://user-images.githubusercontent.com/6659534/62885069-d7043300-bd2f-11e9-803d-ccb54824952b.png)

```python
# Check values - Everything from point df should be present (with distance as well in this case)
[0] nearest_join[['polyid', 'pointid', 'dist']].head(10)
   polyid pointid      dist
0       0       a  0.008897
1       0       b  0.009375
2       0       c  0.002689
3       1       d  0.000610
4       2       e  0.000117
5       0       f  0.003870
6       0       g  0.010740
7       0       h  0.010204
8       0       i  0.009624
9       3       j  0.003662
```

So as we can see, the join works correctly at least when joining information between Points and Polygons (haven't tested yet extensively so there might be issues though). 

Any thoughts about this? The code is now a first iteration so all comments, concerns, ideas would be highly useful. 🙂 If you think this could be useful, I would be happy to work on it. 

Cheers,
Henrikki

**Comment by ljwolf** [comment]
This is rad! If this is something we want to support, we have a [performant example with points to points](http://pysal.org/scipy2019-intermediate-gds/deterministic/gds1-relations.html#how-about-nearest-neighbor-joins) that can be used if the inputs are of the right type?

**Comment by HTenkanen** [comment]
@ljwolf Yep using a KDTree is a great solution between points. 👍

**Comment by HTenkanen** [comment]
Just thinking out loud here, but if going forward with this, the functionality could perhaps be called as `nearest` which would work with all kind of geometry types. If inputs are points, the function could use `KDTree`, if something else, it could utilize something like drafted above.

**Comment by martinfleis** [comment]
This is cool! I would definitely be up for implementing it. I have done similar thing before ([find closest LineString to point](https://github.com/martinfleis/momepy/blob/be76722abc46b61b8a7d282cfb5754aa301424f5/momepy/elements.py#L583)), using `rtree`. We will definitely need some spatial index if we want a reasonable performance.

**Comment by jorisvandenbossche** [comment]
@HTenkanen Thanks for opening the issues! I think this is certainly something worth adding in geopandas: it's a rather typical analysis to do, and not that straightforward to quickly implemented it (performantly) yourself.

So certainly welcome to explore different implementation options.

**Comment by HTenkanen** [comment]
@jorisvandenbossche Okay cool, I can make a first version of it, and take into account the good suggestions made by @ljwolf and @martinfleis. Below are some additional thoughts about this functionality and ideas how the function could work. 

I think the easiest way to implement this would be as a separate function (e.g. `nearest`) so that it does not affect the usability of the current `sjoin` (although otherwise having somewhat similar logic). 

There are at least the following reasons why I think this function should perhaps be implemented as a separate function instead of being part of current `sjoin`:

- I think there should be a way to control the threshold for search distance when finding the nearest geometries. For example, I have often use-cases in which I need to find the nearest neighbors (e.g. some services) but only within some specific threshold distance (e.g. 1 km). This requires an additional parameter which is not part of current `sjoin`
- There should be a way to store information about the distance to closest geometry. This would also require a new parameter to tell whether to store the information or not. 
- In terms of finding the nearest neighbor, it does not really make sense to include an `op` parameter (as in `sjoin`) because I think in most cases you would anyway like to obtain information from the nearest geometry, and then the spatial relationship between geometries that goes under the hood would always be `intersects` (not `within` nor `contains`). Anyway this logic is something that the user should not need to worry about. Hence, I think we should exclude the parameter `op` from here. This is maybe the biggest difference compared to the logic of `sjoin` which is why I think it should be separated.

Does these thoughts seem rational to you @jorisvandenbossche @ljwolf @martinfleis? 

With the current ideas on the table, the implementation could do following things / have following features:

- Have a CRS check in the beginning
-  Check the geometry types of input GeoDataFrames
- If the inputs are both Points, the nearest neighbors would be searched by using KDtree (I've used [sklearn-KDtree](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KDTree.html) implementation which is highly performant and memory efficient)
- If there are other geometry types, the nearest neighbors would be searched by using the logic from the code example above but integrating `rtree` spatial index for faster lookups and using vectorized predicate operations as in current `sjoin`. 
- If there are overlapping geometries, those would be joined similarly as with the current `sjoin`
- There would be a way to keep track of the distances to closest geometry (e.g. `save_distance=False`), this would save the distance into a column `nn_dist` (alternatively the name could also be set with a parameter). If there are overlapping geometries, the distance will be 0.
- There would be a way to control the search distance (e.g. `search_distance=None`), if `None`, would search the closest neighbor in all cases. 
- The function should maintain the original index similarly as current `sjoin`
- As a result the function would return a GeoDataFrame where all attributes (except `geometry') from `right_df` will be joined to the `left_df`, plus possibly the nearest neighbor distance if requested. 

Hence, the API could look like: 

```
def nearest(left_df, right_df, search_distance=None, save_distance=False):
```

I think this could be written into a separate file called `nearest.py` under the `tools`. 

Any comments, concerns or ideas? :)

**Comment by martinfleis** [comment]
I was thinking about this in the meantime as well. And I have some comments.

I think the better solution is to expand `sjoin`. I would add three attributes: `nearest=False`, `tolerance=None` and `keep_dist=True`, all relevant only if `op` is set to `intersection`.

`nearest`, if set to True would do your nearest search for features unlinked in normal sjoin. `tolerance` is equal to your search_distance, it should define how far should one look for a neighbour and helps in rtree. `keep_dist` is the same as yours save_distance. 

The reason for keeping it in sjoin is that it is effectively spatial join, just with an additional option. Moreover, you do normal sjoin as a part of `nearest`, so it makes more sense to keep it all together.

Regarding the design of the function, as much as I like KDtree, I prefer not to use it within geopandas as it is an additional dependency we do not have at the moment. Also, having two versions (KDtree for points, rtree for else) sounds quite complicated for further maintenance. There will be one tricky part with rtree, and that is the extent of the box. You can use `tolerance`, but if it is not set or set too large (performance issues), you will have to define the distance based on something else (5% of gdf bounds?) and then iteratively extend this distance if you don't find any match (that would be the first thing I'd try).

**Comment by HTenkanen** [comment]
@martinfleis Good points 👍 I was also first thinking that it could be integrated with `sjoin` but then came thinking that the logic would have been unintuitive if the `op` parameter would work differently in some cases. But your suggestion of including the `nearest` -parameter actually could be a nice way to avoid the possibility for getting misleading results as the logic should be fairly straightforward to explain as well. 

And yep, KDtree would add a new dependency, but I was thinking this a bit as a similar thing as geocoding functionality which requires geopy. But if this would be part of `sjoin`, then it indeed might be a good idea to avoid any new dependencies.

**Comment by jwilson8767** [comment]
@martinfleis You actually have very nearly described a function I have written (`sjoin_nearest`) for one of my projects which also goes so far as to resolve multiple overlapping geometries by finding the most-overlapping by area. This is very expensive and I do not recommend it for implementation in geopandas. Here's the signature and an example usage of my `sjoin_nearest` to maybe give you some inspiration:
```
def sjoin_nearest(left_df: gpd.GeoDataFrame, right_df: gpd.GeoDataFrame, tolerance_meters, how='inner_left', lsuffix='left', rsuffix='right', epsg=None) -> gpd.GeoDataFrame:
    """
    Spatial join within a given tolerance, eliminating all but the nearest match by nearest distance, then greatest area of overlap, then first.


    :param left_df: GeoDataFrame
    :param right_df: GeoDataFrame
    :param how: string, default 'inner_left'
        The type of join:

        * 'left': use keys from left_df; retain only left_df geometry column; eliminate all but the nearest match for the left_df.
        * 'right': use keys from right_df; retain only right_df geometry column; eliminate all but the nearest match for the right_df.
        * 'inner_left': use intersection of keys from both dfs; retain left geometries; eliminate all but the nearest match for the left_df.
        * 'inner_right: use intersection of keys from both dfs; retain right geometries; eliminate all but the nearest match for the right_df.
    :param tolerance_meters: Max distance in meters (required).
    :param lsuffix:
    :param rsuffix:
    :param epsg: string The EPSG to perform the sjoin in (should be in units meters). Automatically reprojects if needed, without affecting the projection of the final result.
    :return:
    """
pass

#Example of getting the 'id' column of the nearest aggregation area and assigning it to 'aggregation_groups' on gdf.
gdf['aggregation_area_id'] = sjoin_nearest(gdf[['geometry']], aggregation_areas[['geometry', 'id']], how='inner_left', tolerance_meters=500, epsg=epsg)['id']
```
There are a couple interesting things here:
1. I chose to require a projected CRS (passed as an EPSG code) with units in meters to reduce cases were units are passed in the wrong units and to force the user (usually myself) to think about the CRS that is being used.
2. I have implemented 'how' parameter options of 'left', 'right', 'left_inner', and 'right_inner'. Mostly I end up using 'left', but as with a normal `sjoin`, this gives a few options.
3. In the future, I would recommend adding support for setting 'tolerance' using a Series which aligns to the left_df as sometimes a single tolerance for all geometries doesn't make sense.

In regards to choosing a sensible tolerance, it really does vary heavily. The largest factors are the units of the CRS (meters vs ft vs degrees) and the size of the geometries concerned. Very large geometries mixed with many very small geometries create for cases where I'm performing thousands of `intersects` to check candidates that are ultimately thrown away. I've actually been looking at Uber's H3 spatial index as a possible improvement as it could at least reduce the number of possible candidates compared to rtree, but I don't have time right now to explore this idea further.

Finally, when it comes to performing successive `sjoin_nearest` operations with progressively larger tolerances, I had one of my coworkers run some performance experiments and he concluded that it was faster to just run once with a single best-guess tolerance than to step toward that tolerance in 2-3 attempts due to the cost of the `intersects` operation. That said, I do think that implementing the usage of rtree to ramp up the tolerance/buffer until all items have a match *may* offer a nice balance of reducing bad candidates and making sure that every item in left_df finds a match (within the final tolerance). 

I suggest the geopandas implementation `sjoin_nearest` extend `sjoin`, but should be a separate function / file.

**Comment by bluetyson** [comment]
Sounds like an excellent idea, having been working on problems like this recently.

**Comment by adriangb** [comment]
I recently had to implement something similar, except I was just calculating distances, not joining.

No one seemed to mention the shapely [`nearest_points`](https://shapely.readthedocs.io/en/stable/manual.html#shapely.ops.nearest_points) method, which I think would be quite useful.

I ran a comparison using cKDTree, KDTree and an iterative approach using `shapely.ops.nearest_points`.

```python
import geopandas
import pandas as pd
from itertools import permutations
from shapely.ops import nearest_points
from scipy.spatial import cKDTree, KDTree


class GeoDataFrameWithDistances(geopandas.GeoDataFrame):
    
    def k_d_distance_cython(self, other, max_distance):
        # create trees for self and other
        this_tree = cKDTree(data=tuple(zip(self.geometry.x, self.geometry.y)))
        other_tree = cKDTree(data=tuple(zip(other.geometry.x, other.geometry.y)))
        # compute distances
        data = this_tree.sparse_distance_matrix(other=other_tree, max_distance=max_distance)
        # format data for return
        d = ((data[(ind1, ind2)] if (ind1, ind2) else np.nan for ind2 in range(other.shape[0])) for ind1 in range(self.shape[0]))
        return pd.DataFrame.from_records(index=self.index.array, columns=other.index.array, data=d)
    
    def k_d_distance_python(self, other, max_distance):
        # create trees for self and other
        this_tree = KDTree(data=tuple(zip(self.geometry.x, self.geometry.y)))
        other_tree = KDTree(data=tuple(zip(other.geometry.x, other.geometry.y)))
        # compute distances
        data = this_tree.sparse_distance_matrix(other=other_tree, max_distance=max_distance)
        # format data for return
        d = ((data[(ind1, ind2)] if (ind1, ind2) else np.nan for ind2 in range(other.shape[0])) for ind1 in range(self.shape[0]))
        return pd.DataFrame.from_records(index=self.index.array, columns=other.index.array, data=d)
    
    def shapely_distances(self, other, poly_distance="min"):
        if poly_distance == "min":
            nearest = ((nearest_points(in_o, in_s) for _, in_o in other.geometry.items()) for _, in_s in self.geometry.items())
            d = ((p1.distance(p2) for p1, p2 in sub) for sub in nearest)
        elif poly_distance == "centroid":
            d = ((in_o.centroid.distance(in_s.centroid) for _, in_o in other.geometry.items()) for _, in_s in self.geometry.items())
        else:
            raise ValueError('poly_distance must be one of "min" or "centroid"')
        return pd.DataFrame.from_records(index=self.index.array, columns=other.index.array, data=d)
            


        
# test
from timeit import timeit

world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres')).set_index("name")
world['centroid'] = world.centroid

w1 = GeoDataFrameWithDistances(world[["geometry"]], geometry="geometry")
w2 = GeoDataFrameWithDistances(world[["centroid"]], geometry="centroid")


max_d = 1e4
runs = 10
time_kd_c = timeit(lambda: w2.k_d_distance_cython(other=w2, max_distance = max_d), number=runs)
print(f"Time for point-to-point using k-d-tree cython: {time_kd_c:.2f} s")
time_kd_p = timeit(lambda: w2.k_d_distance_python(other=w2, max_distance = max_d), number=runs)
print(f"Time for point-to-point using k-d-tree python: {time_kd_p:.2f} s")
time_shap_point = timeit(lambda: w2.shapely_distances(other=w2), number=runs)
print(f"Time for point-to-point using shapely.ops.nearest_points: {time_shap_point:.2f} s")
time_shap_poly = timeit(lambda: w2.shapely_distances(other=w1, poly_distance="min"), number=runs)
print(f"Time for point-to-poly using shapely.ops.nearest_points: {time_shap_poly:.2f} s")
time_shap_poly = timeit(lambda: w2.shapely_distances(other=w1, poly_distance="centroid"), number=runs)
print(f"Time for point-to-poly using shapely centroids: {time_shap_poly:.2f} s")
```
```
Time for point-to-point using k-d-tree cython: 3.74 s
Time for point-to-point using k-d-tree python: 9.68 s
Time for point-to-point using shapely.ops.nearest_points: 8.63 s
Time for point-to-poly using shapely.ops.nearest_points: 8.87 s
Time for point-to-poly using shapely centroids: 6.73 s
```

From this, it seems that:

- k-d-tree _is_ faster even at large max_distance
- any algorithmic advantage k-d-tree has goes away if comparing Python (KDTree) to C++ (shapely)
- using `shapely.ops.nearest_points` in conjunction with shapely's `distance` method could be a versatile way to expand functionality for `GeoDataFrame.distance` and create a new method `GeoDataFrame.distances` that returns and mxn DataFrame.

**Comment by adriangb** [comment]
Here's what I came up with:

```python
import geopandas as gpd
from shapely.ops import nearest_points
from shapely.geometry import Point
from geopandas import sjoin as sjoin_old


class GeoDataFrame2(gpd.GeoDataFrame):
    
    def distances(self, other, poly_distance="min"):
        """
        Compute distance from geometry in self to all geometries in other.
        """
        if poly_distance == "min":
            # find nearest points in polygons
            nearest = [[nearest_points(in_o, in_s) for _, in_o in other.geometry.items()] for _, in_s in self.geometry.items()]
            # compute distances
            d = [[p1.distance(p2) for p1, p2 in sub] for sub in nearest]
        elif poly_distance == "centroid":
            # compute distances directly from centroids
            d = [[in_o.centroid.distance(in_s.centroid) for _, in_o in other.geometry.items()] for _, in_s in self.geometry.items()]
        else:
            raise ValueError('poly_distance must be one of "min" or "centroid"')
        return self.__class__(data=d, index=self.index.array, columns=other.index.array)
    
    
    def distance(self, other_geometry, poly_distance="min"):
        """
        Compute distance from geometry in self to single point.
        """
        other_is_point = type(other_geometry) == Point
        all_in_self_points = all((type(el) == Point for el in self.geometry))
        if all_in_self_points and (other_is_point or all((type(el) == Point for el in other_geometry.geometry))):
            # all points, use existing distance method
            return super().distance(other_geometry)
        else:
            d = [other_geometry] * self.shape[0]
            other = self.__class__(d, columns=["geometry"], geometry="geometry")
            return self.distances(other=other, poly_distance=poly_distance)


def sjoin(left_df, right_df, how='inner', op='intersects', lsuffix='left', rsuffix='right', report_dist=False):

    # rederict to existing sjoin when possible
    if op != "near":
        return sjoin_old(left_df, right_df, how='inner', op='intersects', lsuffix='left', rsuffix='right')
    
    # manipulate DataFrames to accomodate 'how' parameter
    if how=="inner":
        # this isn't working, using .loc makes the GeoDataFrame a regular DataFrame (?)
        intersection = left_df.index.intersection(right_df.index)
        left_df = left_df.loc[intersection]
        right_df = right_df.loc[intersection]
    elif how=="right":
        left_df, right_df = right_df, left_df

    # find all distances
    d = left_df.distances(other=right_df)
    
    # find index in right dataframe corresponding to the min distance
    nearest_ind_in_right = d.idxmin(axis=1).to_list()
    
    # create a DF indexed as left_df that has info one the closest geometry in right_df
    right_items = right_df.drop(right_df.geometry.name, axis=1).loc[nearest_ind_in_right]
    right_items["index_right"] = nearest_ind_in_right
    right_items.index = left_df.index
    
    # add distances if requested
    if report_dist:
        right_items["dist"] = d.min(axis=1)

    return left_df.join(right_items, lsuffix=f'_{lsuffix}', rsuffix=f'_{rsuffix}')
```

The main idea is:
- Create a `distances` method that allows distance computation between polygons, multi-polygons, etc. between two GeoDataFrames. This is done using `shapely.ops.nearest_points`.
- Use this `distances` method to give `sjoin` a `op=near` option. For other values of `op`, the existing method is used (obviously this would be worked into the existing method, not calling it in this janky way).
- Since we're at it might as well allow the `distances` method to operate on polygons (I don't think it does currently) by redirecting to `distances`.

For testing, I compared it to the method in OP, except I changed the call to `sjoin_nearest` to:
```python
nearest_join = sjoin(left_df=geom_mix, right_df=polys, report_dist=True, op="near", how="left")
```
The resulting DataFrames seem the same, as least as far as I can tell with a quick look. The plots match up as well.
<img width="265" alt="OP_results" src="https://user-images.githubusercontent.com/1755071/72872572-8c092700-3ca2-11ea-9026-c89da66b8db9.png">
<img width="260" alt="proposed_results" src="https://user-images.githubusercontent.com/1755071/72872586-90cddb00-3ca2-11ea-886a-ed2e28609701.png">

Finally, I did some benchmarking:
```python
from timeit import timeit


n = 100
t_1 = timeit(lambda: sjoin_nearest(left_df=geom_mix, right_df=polys, report_dist=True, op="intersects"), number=n)
t_2 = timeit(lambda: sjoin(left_df=geom_mix, right_df=polys, report_dist=True, op="near", how="left"), number=n)
print(f"Time for sjoin_nearest in OP: {t_1:.2f}")
print(f"Time for proposed sjoin changes: {t_2:.2f}")
```
Results:
```
Time for sjoin_nearest in OP: 16.30
Time for proposed sjoin changes: 0.89
```

Maybe these benchmarks are unfair? As it is, this seems orders of magnitude faster.

**Comment by carlosg-m** [comment]
I tried solving this problem using a rtree but discovered that it doesn't guarantee 100% recall.

Using the geometries' vertices with a kd-tree can also yield incorrect results.

https://github.com/Toblerity/Shapely/issues/967
https://github.com/Toblerity/rtree/issues/164

My solution was to get the exterior of all geometries as a LineString, split the LineString into segments using the original points, and using scikit-learn's BallTree with a custom metric.

For Line ABCD we get get:
- Seg 1: A-B
- Seg 2: B-C
- Seg 3 :C-D
```
keys = np.array([[Ax, Ay, Bx, By]
                 [Bx, By, Cx, Cy]
                 [Cx, Cy, Dx, Dy]])
```

The custom metric will be shapely's distance between two lines:

```
def line_distance(a1, b1): 
    a1 = LineString([Point(a1[0],a1[1]),Point(a1[2],a1[3])])
    b1 = LineString([Point(b1[0],b1[1]),Point(b1[2],b1[3])])
    return a1.distance(b1)
```

Then create the BallTree with the custom distance and apply it:
```
tree = BallTree(keys, leaf_size=5, metric=line_distance)
tree.query(...)
```

Code example:
```
def line_to_segment(line):
  line = split(line, MultiPoint(line.coords))
  line = list(map(lambda x: list(x.coords), line))
  return np.array(line).reshape(-1,4)

keys = LineString([Point(1,2),Point(3,4),Point(5,5),Point(9,11)])
keys = line_to_segment(keys)

print(keys)

# array([[ 1.,  2.,  3.,  4.],
#        [ 3.,  4.,  5.,  5.],
#        [ 5.,  5.,  9., 11.]])

def line_distance(a1, b1): 
    a1 = LineString([Point(a1[0],a1[1]),Point(a1[2],a1[3])])
    b1 = LineString([Point(b1[0],b1[1]),Point(b1[2],b1[3])])
    return a1.distance(b1)

tree = BallTree(keys, leaf_size=5, metric=line_distance)

# Query for nearest neighbor of LINESTRING (-1 -2, -3 -4)
tree.query([[-1,-2,-3,-4]])

# (array([[4.47213595]]), array([[0]]))
```

I think this works for every possible case, but it's quite slow.

**Comment by shandou** [comment]
Hello! I am curious about the current status of this feature and if it could be included in future releases. Thank you very much!

**Comment by martinfleis** [comment]
@shandou we are waiting for the support of `nearest` in `pygeos.STRtree` which is on the way - https://github.com/pygeos/pygeos/pull/272 . My assumption is that GeoPandas 0.10 will have this feature, next 0.9 will not.

**Comment by rowanwins** [comment]
FWIW it had to do something along these lines recently. In my case I wanted to find the distance to the nearest feature on some data which had previously been tiled, so I didn't actually do a full spatial join, but what I did could be easily modified.

This is what I came up with utilising the [existing spatial index](https://geopandas.org/docs/reference/api/geopandas.GeoSeries.sindex.html#geopandas.GeoSeries.sindex) stored by geopandas GeoSeries, which has a [nearest method](https://rtree.readthedocs.io/en/latest/class.html#rtree.index.Index.nearest) provided by rtree.
````
def find_nearest_pair(row, gdf):
    row_geom = row['geometry']
    gdf_to_search = gdf.loc[gdf['Tilename'] != row['Tilename']]
    closest_index = gdf_to_search.sindex.nearest(row_geom.bounds, 1)
    f = gdf_to_search.iloc[list(closest_index)[0]]
    return f['geometry'].distance(row_geom)

get_distance_to_pair = gdf.apply(
      lambda row: find_nearest_pair(row, gdf),
      axis=1)
gdf['distance_to_nearest_pair'] = get_distance_to_pair
````

Hope this helpful somebody

**Comment by nirklaiman** [comment]
Hi,
I try to use the "Nearest" function with two geodataframes, a point layer and a linestring layer. the function fail to run with the following error:  
"ValueError: 'left_df' should be GeoDataFrame, got <class 'geopandas.geodataframe.GeoDataFrame'>"
Although both of the objects are geodataframes. what am I missing? I would greatly appreciate an assistance here. 

Thank you!
Nir
