### ISSUE TITLE
Problems installing geopandas in conda env on Mac Mojave

### ISSUE THREAD

**Issue by mauermbq** [geopandas/geopandas#1109]
Hi,

tried to install GeoPandas on Mac Mojave in conda env.

Made a clean env with gdal

conda create -n geo python=3.7 gdal

conda install geopandas leads to:
The following packages will be SUPERSEDED by a higher-priority channel:

  gdal               conda-forge::gdal-3.0.1-py37h4b80d33_7 --> pkgs/main::gdal-2.3.3-py37hbe65578_0
  libdap4            conda-forge::libdap4-3.20.2-hae55d67_~ --> pkgs/main::libdap4-3.19.1-h3d3e54a_0
  libgdal             conda-forge::libgdal-3.0.1-he77f7c2_7 --> pkgs/main::libgdal-2.3.3-h0950a36_0

Then on python console import does not work:
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import geopandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/dev/miniconda3/envs/geo/lib/python3.7/site-packages/geopandas/__init__.py", line 5, in <module>
    from geopandas.io.file import read_file
  File "/opt/dev/miniconda3/envs/geo/lib/python3.7/site-packages/geopandas/io/file.py", line 4, in <module>
    import fiona
  File "/opt/dev/miniconda3/envs/geo/lib/python3.7/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/opt/dev/miniconda3/envs/geo/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/opt/dev/miniconda3/envs/geo/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libpoppler.76.dylib
  Referenced from: /opt/dev/miniconda3/envs/geo/lib/libgdal.20.dylib
  Reason: image not found

**Comment by jorisvandenbossche** [comment]
@mauermbq can you try to do the environment creation in a single step? (`conda create -n geo python=3.7 geopandas` ? 

Also it is advisable to set the "channel_priority" setting to strict: `conda config --set channel_priority strict`

**Comment by mauermbq** [comment]
o.k. thank you,
conda config --set channel_priority strict solved it
however I did not understand why channels of depended packages are mixed up even when I install only one package in one empty environment

**Comment by jorisvandenbossche** [comment]
OK, good to hear it is solved.

> however I did not understand why channels of depended packages are mixed up even when I install only one package in one empty environment

The environment was not empty: you already installed gdal in the first step. Anyway, I don't know the exact details for this specific case, but that is in general why the "strict" config was added: to avoid this mixing of channels (which causes the errors you saw).

**Comment by mauermbq** [comment]
@jorisvandenbossche , the gdal try was the second try, at first I tried to install geopandas in a clean env without any other packages (I use miniconda), but that without the "strict" config. That's why I'm still a little bit confused. If it is clear that the channels are not 100% compatible why will some packages of geopandas are mixed up automatically between available channels, this should not be the default behavior.
