### ISSUE TITLE
Adopt black for code formatting

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1112]
In pandas we recently started using `black` (https://github.com/psf/black) for automatic code formatting. I don't like all the style choices that it makes, but I *do* like that fact that you don't have to worry any more about code style yourself when writing, or need to comment (or argue) on PRs about code style.

So what are your thoughts on using it for geopandas as well?

If we do it, I think we should add a CI check to enforce it (and add a pre-commit hook that people can use, which will run black when committing). Which *does* mean that this can make it a bit harder to do a PR as a pass-by contributor (as you might get failures for style).

Anyway, we also did not yet check for PEP8 (flake8) on CI currently, which is something which we should start doing otherwise I think. But since that also introduces possible failing CI due to style, I would personally directly go for black.

**Comment by martinfleis** [comment]
I tried it to see the changes in the readability of a code and I must say that it is quite nice. Yes, it is one more hurdle for pass-by contributors, but it is easy to reformat code using `black` and as number of contributors of GeoPandas is quite high, it is nice to have a tool ensuring the code is coherent across PRs. Like it!

**Comment by ljwolf** [comment]
I'm in favor. I dig black. 

I also think if folks don't know how to run the formatter on their contribution, a maintainer can always run it before merging. That's kind of @jdmcbr's suggestion, but it ensures the formatting happens at the point of the contribution.

**Comment by jdmcbr** [comment]
> I also think if folks don't know how to run the formatter on their contribution, a maintainer can always run it before merging.

That is reasonable.

**Comment by jorisvandenbossche** [comment]
Additionally, while it is certainly an extra hurdle to understand black and use it, afterwards it also decreases some contribution friction, as you don't need to do nitpicky reviews on style (there is no choice in style anymore, just black). That's something I find a big advantage (certainly in pandas, in geopandas we always have been not that strict, but which also resulted in more inconsistency in the code base)

**Comment by jorisvandenbossche** [comment]
But indeed, we certainly need to be welcoming on newcomers on that aspect, and if we notice that some PRs fails because of this we should properly explain it or offer to do it if needed.

**Comment by jorisvandenbossche** [comment]
OK, so black and flake8 are enabled on travis now. Let's see how it goes for a while, we can always revisit that if it turns out a hurdle or annoyance on PRs.
