### ISSUE TITLE
Working with matplotlib's zoomed_inset_axes and geopandas' plot

### ISSUE THREAD

**Issue by jeremysze** [geopandas/geopandas#1114]
I am trying to use matplotlib's zoomed_inset_axes with geopanda's plot. However, most [examples ](https://pythonmatplotlibtips.blogspot.com/2017/12/draw-axes-in-axes-using-zoomed-inset-axes.html) I've found uses other matplotlib's functions to draw the "zoomed" sections of interest. 

E.g. 
`# plot in the inset axes`
`axins.scatter(x, y, s=1)`

But I typically use geopandas's plotting to plot, so I am not sure about how I should go about doing it with the zoomed_inset_axes function.

I've created a working example in this [notebook](https://nbviewer.jupyter.org/github/jeremysze/GIS_exploration/blob/master/code/zoomed_inset_axes.ipynb), where I've plotted out the map layer and created the zoom boxes. But as you can see I could/did not figure out how to actually plot the "zoomed" section of New Hampshire and West Virginia in those boxes.

How should I go about this? or is there another way to do this with geopandas plot? Thank you!

**Comment by ljwolf** [comment]
This is a great insight, mapping with insets is really important! We should probably add a viginette on how to do this. 
Using something that's like your data:
```python
from pysal.lib import examples
states = geopandas.read_file(examples.get_path('NAT.shp'))
``` 
we could do something nearly identical to what's in [your notebook](https://nbviewer.jupyter.org/github/jeremysze/GIS_exploration/blob/master/code/zoomed_inset_axes.ipynb), using `states.plot(..., ax=axins)` where appropriate:
```python
f, ax = plt.subplots(figsize=(15, 20))

# State layer
states.loc[(states['STATE_FIPS'] != "60") &
           (states['STATE_FIPS'] != "66") &
           (states['STATE_FIPS'] != "69") &
           (states['STATE_FIPS'] != "72") &
           (states['STATE_FIPS'] != "78") &
           (states['STATE_FIPS'] != "15") &
           (states['STATE_FIPS'] != "02")      
          ].plot(ax=ax, edgecolor='black', color = 'white')

axins = zoomed_inset_axes(ax, 2, loc=1)
axins2 = zoomed_inset_axes(ax, 2, loc=4)

minx,miny,maxx,maxy =  states.query('STATE_NAME == "New Hampshire"').total_bounds
axins.set_xlim(minx, maxx)
axins.set_ylim(miny, maxy)
states.query('STATE_NAME == "New Hampshire"').plot(ax=axins, edgecolor='black', color='none')

minx,miny,maxx,maxy =  states.query('STATE_NAME == "West Virginia"').total_bounds
axins2.set_xlim(minx, maxx)
axins2.set_ylim(miny, maxy)
states.query('STATE_NAME == "West Virginia"').plot(ax=axins2, edgecolor='black', color='none')


mark_inset(ax, axins, loc1=2, loc2=4, fc="none", ec="0.5")
mark_inset(ax, axins2, loc1=2, loc2=3, fc="none", ec="0.5")

# Plot zoom window
#axins.plot()
#axins2.plot()

plt.setp(axins.get_xticklabels(), visible=False)
plt.setp(axins.get_yticklabels(), visible=False)
plt.setp(axins2.get_xticklabels(), visible=False)
plt.setp(axins2.get_yticklabels(), visible=False)

#ax.set_axis_off()
plt.show()
```
![demo_insets](https://user-images.githubusercontent.com/2250995/63852189-a5c26e80-c98f-11e9-9752-959f300cfb37.png)
Is that what you want?

**Comment by samuelbasilio** [comment]
Nice! Any idea how to switch the full map with the zoomed map? I would like to leave the full map small in a corner and the zoomed map occupying the entire plot.
