### ISSUE TITLE
New sjoin 'how' value to return intersection geometry

### ISSUE THREAD

**Issue by johnflavin** [geopandas/geopandas#1115]
I have a use case where I need to intersect the geometries of two GeoDataFrames. `sjoin` seems like the natural way to do this. But despite `sjoin` determining whether the left and right geometries intersect, the results I can get from `sjoin` using the various `how` arguments contain only the left geometry or the right geometry and not the geometry of the intersections.

I could always merge back in the missing geometry (as `sjoin` only gives me one) and calculate all the intersections. But that feels like I am intersecting everything twice: once within `sjoin` and again after `sjoin` has given me all the indices that intersect.

Would it make sense to add an additional case to `sjoin`'s `how` parameter which would cause it to return a GeoDataFrame with the intersection between left and right as the geometry?

**Comment by jorisvandenbossche** [comment]
You might be looking for the `overlay` operation? (https://geopandas.readthedocs.io/en/latest/set_operations.html)
