### ISSUE TITLE
Overlay Union applied to single layer

### ISSUE THREAD

**Issue by aborruso** [geopandas/geopandas#1117]
Hi,
is it possible to apply something like `geopandas.overlay(df1, df2, how='union')` to the elements of a single dataframe?

I have read about unary_union, but I'm not able to have in output something like the below image.

Thank you

![image](https://user-images.githubusercontent.com/30607/64115454-fd961680-cd8f-11e9-8650-2232d1ec8a1f.png)

**Comment by jorisvandenbossche** [comment]
Ah, I see now this issue, so what I interpreted in https://github.com/geopandas/geopandas/issues/1116 is probably correct. 

As I said there, there is no direct solution as far as I know, but can you loop though the geometries and each time the intersection of the result with the next.

**Comment by jorisvandenbossche** [comment]
Did a quick try (based on this SO answer: https://gis.stackexchange.com/a/326583/9828), see https://nbviewer.jupyter.org/gist/jorisvandenbossche/3a55a16fda9b3c37e0fb48b1d4019e65

This uses the trick to union the boudaries of all pairwise intersections, and then this MultiLineString can be polygonized. 

To then know from which original polygon they came, you might be able to do a spatial join of the result with the original.

**Comment by aborruso** [comment]
What a great notebook!!

Thank you
