### ISSUE TITLE
Writing to file doesn't respect fiona vsi schemes

### ISSUE THREAD

**Issue by ian-r-rose** [geopandas/geopandas#1118]
Fiona supports writing to different OGR virtual filesystem schemes via the file path, e.g., `zip://`, `s3://`, etc. However, these schemes get overwritten in `gpd.to_file()`, which attempts to take the path and construct an absolute path:
https://github.com/geopandas/geopandas/blob/29add0a735b00dc20c79e0fccc8e6a775c4997b0/geopandas/io/file.py#L127
so you get bad paths like `/home/username/s3:/bucket/object`.

Is this absolute file path important? Is there a reason to not allow VSI-based paths in `gpd.to_file()`? Can we check for a url-like scheme before trying to abs-path it? If so, I'd be happy to submit a PR.

(N.b., the corresponding `gpd.read_file()` handles these URLs correctly).

**Comment by martinfleis** [comment]
That is a good point. I don't think there is any reason not to allow VSI-based paths, it just wasn't implemented yet. 

> Can we check for a url-like scheme before trying to abs-path it? If so, I'd be happy to submit a PR.

PRs are always welcome. Feel free to do so. Thanks!
