### ISSUE TITLE
installation notes about pyproj - update?

### ISSUE THREAD

**Issue by darrenleeweber** [geopandas/geopandas#1125]
```
$ curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
$ mkdir tmp_project
$ poetry init  # follow the prompts
$ poetry add pyproj
$ ls -l ~/.cache/pypoetry/virtualenvs/tmp-project-py3.6/lib/python3.6/site-packages/pyproj/.libs/
libproj-e5ef822e.so.15.1.1
libsqlite3-fdd57a2d.so.0.8.6
libz-a147dcb0.so.1.2.3

$ cat ~/.cache/pypoetry/virtualenvs/tmp-project-py3.6/lib/python3.6/site-packages/pyproj-2.3.1.dist-info/WHEEL 
Wheel-Version: 1.0
Generator: bdist_wheel (0.33.6)
Root-Is-Purelib: false
Tag: cp36-cp36m-manylinux1_x86_64
```

This looks like `pyproj` is providing wheels with the required binary libs available.  Yet, the geopandas docs indicate that it does not.
- http://geopandas.org/install.html#installing-with-pip

The point may be true of `rtree`? e.g.
```
$ poetry add rtree
$ ls -1 ~/.cache/pypoetry/virtualenvs/tmp-project-py3.6/lib/python3.6/site-packages/rtree/
core.py
index.py
__init__.py
__pycache__

$ cat ~/.cache/pypoetry/virtualenvs/tmp-project-py3.6/lib/python3.6/site-packages/Rtree-0.8.3.dist-info/WHEEL 
Wheel-Version: 1.0
Generator: bdist_wheel (0.29.0)
Root-Is-Purelib: true
Tag: py3-none-any
```

But, `rtree` asserts that it _is_ a pure-python library.  So, what's the story on that one?

**Comment by darrenleeweber** [comment]
Via pip, geopandas did not install `rtree` at all

```
$ poetry add geopandas
Creating virtualenv tmp-project-py3.6 in /home/dlweber/.cache/pypoetry/virtualenvs
Using version ^0.5.1 for geopandas

Updating dependencies
Resolving dependencies... (0.7s)

Writing lock file


Package operations: 14 installs, 0 updates, 0 removals

  - Installing click (7.0)
  - Installing six (1.12.0)
  - Installing attrs (19.1.0)
  - Installing click-plugins (1.1.1)
  - Installing cligj (0.5.0)
  - Installing munch (2.3.2)
  - Installing numpy (1.17.2)
  - Installing python-dateutil (2.8.0)
  - Installing pytz (2019.2)
  - Installing fiona (1.8.6)
  - Installing pandas (0.25.1)
  - Installing pyproj (2.3.1)
  - Installing shapely (1.6.4.post2)
  - Installing geopandas (0.5.1)

$ poetry show --tree
geopandas 0.5.1 Geographic pandas extensions
├── fiona *
│   ├── attrs >=17 
│   ├── click >=4.0,<8 
│   ├── click-plugins >=1.0 
│   │   └── click >=4.0 (circular dependency aborted here)
│   ├── cligj >=0.5 
│   │   └── click >=4.0,<8 (circular dependency aborted here)
│   ├── munch * 
│   │   └── six * 
│   └── six >=1.7 (circular dependency aborted here)
├── pandas *
│   ├── numpy >=1.13.3 
│   ├── python-dateutil >=2.6.1 
│   │   └── six >=1.5 
│   └── pytz >=2017.2 
├── pyproj *
└── shapely *
```

**Comment by jorisvandenbossche** [comment]
> This looks like pyproj is providing wheels with the required binary libs available. Yet, the geopandas docs indicate that it does not.

The information is indeed outdated. The wheels are a relatively recent addition for pyproj, and they are also only for mac and linux (like it is the case for fiona and shapely). 
Do you want to do a PR to correct that?

> But, rtree asserts that it is a pure-python library. So, what's the story on that one?

The story is that rtree itself is indeed a pure-python library, so technically they can provide universal wheels. But you still need libspatialindex C library installed, which is not included in the wheels.

> Via pip, geopandas did not install rtree at all

rtree is not an actual hard dependency of geopandas. Partly because it is not that easy to install. But since it is very useful in practice (it's needed for spatial join, overlay functionality), the conda packages list it as a dependency.
