### ISSUE TITLE
Error using geopandas.tools.sjoin after serializing and deserializing GeoDataFrame

### ISSUE THREAD

**Issue by julianocruz** [geopandas/geopandas#1129]
I need to serialize and deserialize a geopandas object, but it seems to be loosing some data.

It works
```
roi = geopandas.GeoDataFrame.from_file("file1.kml")
landsat = eopandas.GeoDataFrame.from_file("file2.shp")

result = geopandas.tools.sjoin(roi, landsat, how="inner")
```

It doesn't work
```
#serializing
roi_json = geopandas.GeoDataFrame.from_file("file1.kml").to_json()
landsat_json = geopandas.GeoDataFrame.from_file("file2.shp").to_json()

#deserializing
roi = geopandas.GeoDataFrame.from_dict(json.loads(roi_json)) 
landsat = geopandas.GeoDataFrame.from_dict(json.loads(landsat_json))

result = geopandas.tools.sjoin(roi, landsat, how="inner")
```
and throws the following error

> Traceback (most recent call last):
>   File "file.py", line 185, in <module>
>     main()
>   File "file.py", line 174, in main
>     scene = func1(roi, landsat)
>   File "file.py", line 37, in scene_discovery
>     result = geopandas.tools.sjoin(polygon, landsat_scenes_shp,how="inner")  ['Name', 'Description', 'geometry', 'index_right', 'AREA', 'PERIMETER','PR_', 'PR_ID', 'RINGS_OK', 'RINGS_NOK', 'WRSPR', 'PR', 'PATH', 'ROW','MODE', 'DAYCLASS', 'SEQUENCE']
>   File "C:\Anaconda3\lib\site-packages\geopandas\tools\sjoin.py", line 84, in sjoin
>     right_df_bounds = right_df.geometry.apply(lambda x: x.bounds)
>   File "C:\Anaconda3\lib\site-packages\pandas\core\generic.py", line 5179, in __getattr__
>     return object.__getattribute__(self, name)
>   File "C:\Anaconda3\lib\site-packages\geopandas\geodataframe.py", line 70, in _get_geometry
>     " column '%s'." % self._geometry_column_name)
> AttributeError: No geometry data set yet (expected in column 'geometry'.

**Comment by jorisvandenbossche** [comment]
Thanks for the report!

`GeoDataFrame.from_dict` is not specialized for geopandas (we are inheriting pandas' one), so I am not sure it is working as you would expect (also the geojson-like dict is not a flat dict as would fit in `from_dict`).

If you want to do what you are doing above (converting to a geojson dict and back to GeoDataFrame), I think you can use `GeoDataFrame.from_features` instead of `from_dict`. 

Is there a reason you are serializing the dataframe like this in memory to a geojson string? (I assume the above is a simplified example)

**Comment by julianocruz** [comment]
Thank you Joris!
The main problem was me using .from_dict instead of .from_features .
Now it's working.

I'm working with web services, so the parameters and the return variables must be serialized.

**Comment by jwilson8767** [comment]
@julianocruz In case it helps, I've had awesome success using python's `pickle` module to temporarily serialize / deserialize GeoDataFrames. It's super fast and actually not awful on disk usage.
