### ISSUE TITLE
Errors in reprojecting data with to_crs

### ISSUE THREAD

**Issue by dzanaga** [geopandas/geopandas#1142]
Hello everybody,

thanks in advance for the great library provided and the effort you put into it.

I am encountering issues in projecting geometries to different projections. This occurs when a polygon seems to touch the the sides of espg zones 32601, 32659, 32660, or the left and right sides in latlon projection.

I first noticed this while reprojecting the Sentinel-2 MGRS grid to latlon...
Then I had it again with other shapefiles.
Example of the problem using the [natural earth land layer](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/physical/ne_110m_land.zip):
```
aoi = gpd.read_file("ne_110m_land.shp")
aoi.plot()
```
![Figure 1](https://user-images.githubusercontent.com/8113766/66061584-0a995780-e540-11e9-8644-b83162e64e6b.png)

if then I reproject it to an EPSG zone I get:
```
aoi.to_crs(epsg=32628).plot()
```
![Figure 4](https://user-images.githubusercontent.com/8113766/66061702-40d6d700-e540-11e9-9f25-89ecefeefd7b.png)

and if I project it back:
```
aoi.to_crs(epsg=32628).to_crs(epsg=4326).plot()
```
![Figure 5](https://user-images.githubusercontent.com/8113766/66061755-5d730f00-e540-11e9-8e05-efa33bac30c3.png)

Env info:
```
geopandas             0.5.1                      py_0    conda-forge
pyproj                    1.9.6           py37h516909a_1002    conda-forge
gdal                       2.4.1           py37h5f563d9_10    conda-forge
libgdal                   2.4.1               hc4f5fd6_10    conda-forge
```

**Comment by martinfleis** [comment]
Thanks for the report. Can confirm on pyproj 2.2.1 and Geopandas master. CC-ing  @snowman2 as he might know more about it, as it is probably linked to some pyproj issue.

**Comment by jorisvandenbossche** [comment]
This is a known issue, because geopandas "naively" reprojects all coordinates of a geometry separately. From the to_crs docs:

> This method will transform all points in all objects. It has no notion or projecting entire geometries. All segments joining points are assumed to be lines in the current projection, not geodesics. Objects crossing the dateline (or other projection boundary) will have undesirable behavior.

See https://github.com/geopandas/geopandas/issues/448 for some discussion about this (I thought there was another issue, but can't find it). I think we can close this in favor of the other issue (maybe post the example there as well)

Cartopy actually handles this (and it could be a reason to use cartopy instead of pyproj for repojections, it would actually be interesting to have a conversation about if PROJ would be interested in such functionality)

**Comment by jorisvandenbossche** [comment]
At least we should document the issue better (with some examples), and maybe give some workarounds if there are any (in the other issue there are some ideas). 
That issue mentions some options in PROJ (like `+over`), but not sure how that fits in the new (non-proj string) CRS interface.

**Comment by snowman2** [comment]
Another option could be to allow the `to_crs` method to have a transformer kwarg and provide a default transformer for the kwarg and possible provide a set of transformers for users to select from.

This way, they could use whatever transformer best fits their dataset. For example., it could be expanded to use methods such as `transform_geom` in shapely:
https://github.com/Toblerity/Fiona/blob/d6ec15f1c2e7a860bc57d35a51e36aeb48377a1a/fiona/transform.py#L44-L86

**Comment by snowman2** [comment]
This would be similar to what we do in geocube to allow users to rasterize their points:
https://corteva.github.io/geocube/html/examples/rasterize_point_data.html

**Comment by snowman2** [comment]
> it would actually be interesting to have a conversation about if PROJ would be interested in such functionality

That sounds like a reasonable path forward as well.

**Comment by jorisvandenbossche** [comment]
Ah, that's interesting, I didn't know that fiona / gdal also had functionality for this. 
This was added in https://github.com/OSGeo/gdal/commit/cc92ccb7a01321efed8cfc820fc7215aba12b1f1

**Comment by dzanaga** [comment]
Thanks for the quick answer. I will crop to the global bbox as suggested in #448 . I added the example there as advised. I am closing this since it's the same issue.
