### ISSUE TITLE
plot_bokeh became extremely slow with 0.6.0

### ISSUE THREAD

**Issue by lamourj** [geopandas/geopandas#1146]

**Comment by jorisvandenbossche** [comment]
@lamourj can you show a code example ?

**Comment by lamourj** [comment]
Sorry, my issue description stayed idling there and I forgot to post it. I've done further investigation, and to the best of my knowledge, the huge increase in runtime are obtained when the geometry contains `MultiPolygons`.

### Steps to reproduce:

**1. Get the data (from Swiss publicly available government datasets):**
- https://shop.swisstopo.admin.ch/en/products/landscape/names3D (download button at the bottom of the page)
- https://data.geo.admin.ch/ch.swisstopo-vd.ortschaftenverzeichnis_plz/PLZO_SHP_LV95.zip

**2. Extract the data**
Unzip both archives and place into `./data` such that the following code snippet runs smoothly).
```sh
unzip PLZO_SHP_LV95.zip -d data
unzip data.zip -d data
unzip data/swissNAMES3D_LV95.zip -d data/lakes
```

**3. Load the data**
```python
import geopandas as gpd
import pandas_bokeh
pandas_bokeh.output_notebook()

postal_codes=gpd.read_file('data/PLZO_SHP_LV95/PLZO_PLZ.shp')
postal_codes.crs = {'init': 'epsg:2056'}
postal_codes = postal_codes.to_crs(epsg=4326) # contains polygons only

lakes = gpd.read_file("data/lakes/swissNAMES3D_LV95/shp_LV95_LN02/")
lakes.crs = {'init': 'epsg:2056'}
lakes = lakes.to_crs(epsg=4326)
lakes = lakes[(lakes.STATUS != 'fremd') & (lakes.STATUS != 'k_WOBJEKTART')]
lakes = lakes[lakes.OBJEKTART == 'See']
lakes = lakes.loc[lakes.geometry.apply(lambda x: x.wkb).drop_duplicates().index]
lakes = lakes[lakes.to_crs(epsg=32633).area / 10**6 > 0.5]

# Modify the geometries to exclude the lakes:
without_lakes = gpd.overlay(postal_codes, lakes[['geometry']], how='difference') 
# Hence, `without_lakes`contains polygons and multipolygons
```

**4. Now, call `plot_bokeh` on each gpd:**
On `postal_codes`, which does not contain multipolygons, time is relatively similar between `geopandas==0.6.0` and `geopandas==0.5.1` (note that 0.6.0 is already a bit slower here):
```python
postal_codes.plot_bokeh()
```

Using `%time` inside an iPython notebook, I observe:
_0.5.1_: CPU times: user 41.8 s, sys: 2.08 s, total: 43.9 s Wall time: 44 s
_0.6.0_: CPU times: user 51.3 s, sys: 1.58 s, total: 52.9 s Wall time: 53 s

On `without_lakes`, which does contain multipolygons, the difference is huge:
```python
without_lakes.plot_bokeh()
```

_0.5.1_: CPU times: user 47.6 s, sys: 4.1 s, total: 51.7 s Wall time: 51.8 s
_0.6.0_: CPU times: user 5min 11s, sys: 5.21 s, total: 5min 16s Wall time: 5min 17s

**Comment by jorisvandenbossche** [comment]
@lamourj thanks for the detailed description!

I took a look in the pandas-bokeh code for geopandas (https://github.com/PatrikHlobil/Pandas-Bokeh/blob/master/pandas_bokeh/geoplot.py), and noticed they have the following function:

```
def convert_geoDataFrame_to_patches(gdf, geometry_column_name="geometry"):
    """Creates from a geoDataFrame with Polygons and Multipolygons a Pandas DataFrame with x any y columns specifying the geometry of the Polygons"""

    import geopandas as gpd

    gdf_new = gpd.GeoDataFrame(columns=gdf.columns)

    def extract(row, geometry):
        x, y = geometry.exterior.xy
        # Convert to int for web mercador projection to save space:
        row["__x__"] = [[[int(_) for _ in x]]]
        row["__y__"] = [[[int(_) for _ in y]]]

        for interior in geometry.interiors:
            x, y, *z = zip(*interior.coords)
            row["__x__"][0].append([int(_) for _ in x])
            row["__y__"][0].append([int(_) for _ in y])

        return row

    for i, row in gdf.iterrows():
        geometry = row[geometry_column_name]
        if geometry.type == "Polygon":
            gdf_new = gdf_new.append(extract(row, geometry), ignore_index=True)

        if geometry.type == "MultiPolygon":
            for polygon in geometry:
                gdf_new = gdf_new.append(extract(row, polygon), ignore_index=True)

    gdf_new = gdf_new.drop(columns=["geometry"])
    return gdf_new
```

Running that on 

```
import random
import numpy as np
import geopandas
import shapely.geometry

N = 100
df = geopandas.GeoDataFrame({
    'a': np.random.randn(N), 'b': np.random.randint(100, size=N),
    'geometry': [shapely.geometry.MultiPolygon([
                    shapely.geometry.Polygon([(random.random()*10, random.random()*10) for i in range(3)])
                    for _ in range(5)])
                 for _ in range(N)]
})
```

shows a slowdown compared to previous versions:

```
In [24]: %timeit convert_geoDataFrame_to_patches(df) 
1.34 s ± 216 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [25]: geopandas.__version__ 
Out[25]: '0.5.1'
```

```
In [28]: %timeit convert_geoDataFrame_to_patches(df) 
5.78 s ± 1.08 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [31]: geopandas.__version__
Out[31]: '0.6.0+1.gcf98586'
```

Not in the same order of magnitude as you observe, but certainly already a significant slowdown.

The reason for this slowdown / slow function is two-fold:

- GeoPandas got slower in appending data to a GeoDataFrame, becuase we now validate the input to check that is are actual geometries
- The function in pandas-bokeh is written somewhat inefficiently, by appending in a for loop (which each times copies and recreates the full geodataframe with one row appended)

If I rewrite the function slightly to append to a list, and only create the GeoDataFrame once in the end from the built-up list:

```
def convert_geoDataFrame_to_patches2(gdf, geometry_column_name="geometry"):
    """Creates from a geoDataFrame with Polygons and Multipolygons a Pandas DataFrame with x any y columns specifying the geometry of the Polygons"""

    import geopandas as gpd

    gdf_new = []

    def extract(row, geometry):
        x, y = geometry.exterior.xy
        # Convert to int for web mercador projection to save space:
        row["__x__"] = [[[int(_) for _ in x]]]
        row["__y__"] = [[[int(_) for _ in y]]]

        for interior in geometry.interiors:
            x, y, *z = zip(*interior.coords)
            row["__x__"][0].append([int(_) for _ in x])
            row["__y__"][0].append([int(_) for _ in y])

        return row

    for i, row in gdf.iterrows():
        geometry = row[geometry_column_name]
        if geometry.type == "Polygon":
            gdf_new.append(extract(row, geometry))

        if geometry.type == "MultiPolygon":
            for polygon in geometry:
                gdf_new.append(extract(row, polygon))

    gdf_new = gpd.GeoDataFrame(gdf_new)

    gdf_new = gdf_new.drop(columns=["geometry"])
    return gdf_new
```

then this is much faster, also on geopandas 0.5.1 and with hardly any slowdown in geopandas 0.6.0 (within the uncertainty):

```
# geopandas 0.5.1
In [32]: %timeit convert_geoDataFrame_to_patches2(df)
162 ms ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

```
# geopandas 0.6.0
In [34]: %timeit convert_geoDataFrame_to_patches2(df)                                                                                                                                                              
178 ms ± 27.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

That said, we might be able to improve the `append` performance, as in principle it should not be needed to re-validate the geometries of the existing geodataframe, only of the new one that is being appended. However, I am not sure that is easy to fix (as this is mainly done in pandas).

**Comment by jorisvandenbossche** [comment]
I reported this at pandas-bokeh: https://github.com/PatrikHlobil/Pandas-Bokeh/issues/48. I suppose they will be happy take a PR to improve this! 

@lamourj you could also test that this actually solves fully the issue for you by doing:

```
import pandas_bokeh.geoplot
pandas_bokeh.geoplot.convert_geoDataFrame_to_patches = convert_geoDataFrame_to_patches2
```

with the second version above

**Comment by lamourj** [comment]
Thanks @jorisvandenbossche ! Your fix solved the issue (actually even improved the runtime between 0.5.1 and 0.6.0). I'll take care of submitting a PR to follow-up to PatrikHlobil/Pandas-Bokeh#48

**Comment by jorisvandenbossche** [comment]
Great!
