### ISSUE TITLE
projected bounds vs WGS84 bounds

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1148]
I came across a [question](https://stackoverflow.com/questions/58289362/geopandas-reprojection-from-4326-to-3857-not-working-properly) on StackOverflow. 

I have very limited knowledge on this matter but wonder if there should be an option to return WGS 84 instead?

**Comment by jorisvandenbossche** [comment]
@StevenLi-DS what do you mean exactly? Converting WGS84 coordinates to WebMercator (EPSG:3857) should return coordinates in this projection, and not WGS84?

**Comment by StevenLi-DS** [comment]
might be a stupid question indeed...
