### ISSUE TITLE
Lazy Loading Dataframes

### ISSUE THREAD

**Issue by snowman2** [geopandas/geopandas#1157]
There have been times when I wanted to use geopandas to get an idea of what was in a large file. But, it took a long time to load it in. So, I used `fiona` instead. Are there any plans (or desires) to do lazy loading of the geopandas data?

This is library I recently saw is related:
https://vaex.readthedocs.io/en/latest/index.html
https://github.com/vaexio/vaex

**Comment by martinfleis** [comment]
What would be the ideal workflow for that?

**Comment by jorisvandenbossche** [comment]
I suppose you used fiona to then only look at the first few elements? Or to look at the metadata? Or can you clarify what you want out of the "lazy" aspect?

In case of the first, we could maybe add a keyword to control how many records to fetch.

I am not fully sure geopandas would be a good fit for vaex. They eg use a lot of memory mapping, which is something that doesn't work with geometries. 
There were recently some talks again (and an old prototype) about combining geopandas with dask (see https://github.com/geopandas/geopandas/issues/461, https://github.com/dask/dask/issues/5438, https://github.com/geopandas/geopandas/pull/1143)

**Comment by snowman2** [comment]
> I suppose you used fiona to then only look at the first few elements? Or to look at the metadata? Or can you clarify what you want out of the "lazy" aspect?

Something where I could look at the CRS and do a `head()` or `tail()` of a large dataset without having to load in the whole dataset. There are also times when I am only interested in a small subset of the file. 

I haven't worked out the details of how it would work under the hood yet, just at the initial idea stage at the moment.


Also, using vaex isn't necessary what I was thinking, just something that has implented some of these things that might be a good reference.

**Comment by snowman2** [comment]
So, looking into this a bit more, I am thinking adding more options to `filter()` on open would be a good start.

Currently supports `bbox`:
https://github.com/geopandas/geopandas/blob/e0b720580880464e4ed93cc269ac4d23b159feff/geopandas/io/file.py#L90

However, `filter()` also supports slices and geometries:
https://github.com/Toblerity/Fiona/blob/d6ec15f1c2e7a860bc57d35a51e36aeb48377a1a/fiona/collection.py#L231-L237

```
        """Returns an iterator over records, but filtered by a test for
        spatial intersection with the provided ``bbox``, a (minx, miny,
        maxx, maxy) tuple or a geometry ``mask``.

        Positional arguments ``stop`` or ``start, stop[, step]`` allows
        iteration to skip over items or stop at a specific item.
        """
```

So, maybe on open, we could add the kwargs:
1. data_slice (start, stop[, step])
2. geometry_mask

This way, the user can specify what chunks they are interested in.

Thoughts?

**Comment by snowman2** [comment]
I tested it out on a smaller dataset and it works nicely:
![image](https://user-images.githubusercontent.com/8699967/66725666-e53b0200-edf9-11e9-8eae-4438acdac471.png)

**Comment by snowman2** [comment]
![image](https://user-images.githubusercontent.com/8699967/66725707-57134b80-edfa-11e9-99b0-8b20449d2387.png)

**Comment by snowman2** [comment]
Draft PR #1160
