### ISSUE TITLE
Topological colouring

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1165]
Hi,

I have ported topological colouring QGIS tool for geopandas yesterday. There is still some work to be done, but the main question is - do we want to include it directly in geopandas? It can be done without additional dependencies. 

Other option would be to release it as a separate package with a richer options: speedup using PySAL's contiguity weights, another effective options using networkX. At the moment it basically mimic the behaviour of QGIS tool (options to balance based on count, area and distance).

The original code is licensed under GNU General Public License v2. I have no clue how compatible it is with ours. However, @nyalldawson mentioned he is [willing to relicense](https://twitter.com/nyalldawson/status/1184375622748889088) (the part I used is solely his work).
![Unknown-3](https://user-images.githubusercontent.com/36797143/66899979-d881fe00-eff3-11e9-83e0-32d903e98de5.png)

cc @jorisvandenbossche @snowman2

**Comment by snowman2** [comment]
I think if he relicenses it to MIT or BSD, then it should be fine to include. How performant is it without the speedups?

This made me think of a way to organize geopandas such that you could install part of it without requiring all of it.

For example:
geopandas-core (shapely, pygeos, pyproj)
geopandas-plot (Descartes, matplotlib, etc..)

And then have the main geopandas package install all of those and also install fiona and manage file io. That way if a user doesn't need all of it, they don't have to install all of it. Anyway, just a random thought based on this thread.

**Comment by snowman2** [comment]
Also, with the plugin like architecture, you could make this into a package like `geopandas-plot-topo` or something.

**Comment by martinfleis** [comment]
> How performant is it without the speedups?

Not sure yet. PySAL is using shared nodes/edges in fast list/set/dict filtering while the other one is based on rtree intersections, so I assume that the difference will be significant, but the latter option is more robust. I'll try to finalise all the options over the weekend and compare performance and results. 

Some the networkx algorithms gives you 4 colours only, while here we need 5. That is the reason why I am not super sure if we want it to be part of geopandas, we definitely do not want add new dependencies (especially for a minor thing like this). Separate package might give us more flexibility.

> This made me think of a way to organize geopandas such that you could install part of it without requiring all of it.

Do you know about any other package doing it successfully? I know that PySAL does something like that, but the way it is done is more confusing than helpful.

**Comment by snowman2** [comment]
> the latter option is more robust

I lean towards the more robust option. But, it all depends on the use case. I think timing the different solutions will be helpful with the decision.

> Do you know about any other package doing it successfully?

I saw the vaex package do it. I like the idea of having the main package `geopandas` remain the same and install everything. That way, if you have been using geopandas, it still behaves how it always has. But, if you only want a piece of it, you only need that piece. For example, if you want to use the `parquet` driver for reading and writing, you can install `pyarrow` with `geopandas-core` and you won't need to install `Fiona`.

That being said, there are other strategies for achieving this. This was just the first thought that went through my head after reading this. And, dividing things up can add to the complexity of everything and may not be worth the trouble.

**Comment by martinfleis** [comment]
**Timings**

There are 3 options 
- robust one from QGIS with options to balance colours (count, area, distance), done purely in geopandas, no need for another dependency
- fast one using libpysal contiguity weights (you need to share at least one vertex, so gdf needs to be topologically clean) with the same options. needs `libpysal`.
- fast one using libpysal and networkx algorithms for colouring. Allows [multiple strategies](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.coloring.greedy_color.html#networkx.algorithms.coloring.greedy_color) and can sometimes give smaller number of colors than previous two.

Tested on randomised voronoi polygons. Code here: https://nbviewer.jupyter.org/gist/martinfleis/d88ea3d50ccdb6b71ac6f757fecf61dd

```
100
robust_count:  0.49878664016723634 s;  14 colors
pysal_count:  0.008840847015380859 s;  14 colors
pysal_lf:  0.014633893966674805 s;  14 colors
1000
robust_count:  5.006178474426269 s;  17 colors
pysal_count:  0.09947896003723145 s;  17 colors
pysal_lf:  0.6779930114746093 s;  17 colors
10000
robust_count:  45.33429980278015 s;  20 colors
pysal_count:  0.9851454257965088 s;  20 colors
pysal_lf:  1.6736697673797607 s;  20 colors
```
![Unknown-7](https://user-images.githubusercontent.com/36797143/66957970-254eee80-f05f-11e9-9e17-b03aec3c12e3.png)

The difference is huge. That is the reason why I am not so sure about implementing it in geopandas as it would mean either adding a dependency or keeping only the slowest option. I have big datasets where I know that my topology is correct, so I would definitely prefer the one based on pysal.

After seeing all this I incline towards having it as a small independent package with all the options included.

**Comment by snowman2** [comment]
> After seeing all this I incline towards having it as a small independent package with all the options included.

Sounds like a good plan to me. Definitely something to include in the plotting docs in geopandas.

**Comment by martinfleis** [comment]
> Definitely something to include in the plotting docs in geopandas.

Will do. 

Closing here for now. Thank you for your comments @snowman2!

**Comment by nyalldawson** [comment]
Just for reference: the original algorithms were designed purely for aesthetics (I E. Balancing overall area by color, or maximizing distances between adjacent features of the same colour). That's why they often result in larger counts vs routines designed to minimise the overall number of colours. That said, it's likely there's many ways they could be improved!

**Comment by jorisvandenbossche** [comment]
@martinfleis cool stuff, thanks for exploring this!

Some thoughts:

- optional dependencies are not necessarily a problem. Eg for the scheme-based plotting we already use libpysal/mapclassify
- it might be that there is room for performance improvements in the geopandas-based one. With a few small adaptations (will try to list later what I did) I got a 2x speed-up. However, after that, it might be that we bump into the bottomline of the time that the GEOS operations take

**Comment by martinfleis** [comment]
@jorisvandenbossche 

>optional dependencies are not necessarily a problem

So you prefer to include it in geopandas?

> it might be that there is room for performance improvements in the geopandas-based one

That is likely. I just dumbly ported the original code, but it will always be significantly slower than PySAL implementation (reason to keep both).

**Comment by snowman2** [comment]
> So you prefer to include it in geopandas?

Sounds like it would be worth looking into. I think the insight from @jorisvandenbossche makes it sound like it could be a good fit.

**Comment by martinfleis** [comment]
I have refreshed this idea over the holiday and decided to turn it into the independent package, rather than having it built-in in geopandas. Few reasons why I decided that:

- this is a small cartographic tool, nothing crucial for geographic analysis and geometric operations in pythons. I feel that geopandas should provide the core for geospatial analysis in python, but we should be careful which _nice additional_ tools should be part of it to keep the maintenance demands as low as possible. 
- even though it is one function in the end, it offers a variety of options so the documentation is larger than I thought it would be.
- it requires networkx and libpysal, which are currently not dependencies of geopandas. I know it might be fine as Joris suggested, but it again gives us unnecessary maintenance tasks to check if these two are not causing issues.

The resulting package, called `greedy` is here https://github.com/martinfleis/greedy + [docs](https://martinfleis.github.io/greedy/).

I will add an example of topological colouring to geopandas docs later.

One thing we might consider is some way of _geopandas affiliated projects_ listing packages like this one, geoplot, splot, movingpandas etc.

**Comment by snowman2** [comment]
Sounds good 👍. I like the idea of having an affiliated packages page as well.

**Comment by nyalldawson** [comment]
@martinfleis looks great! Would love to hear if you implemented any fixes or enhancements during the port which could be upstreamed back to qgis?

**Comment by martinfleis** [comment]
@nyalldawson I did some enhancements, but not sure how applicable they'll be in qgis.

There are two changes in `balanced` function.

1) distance-based balance can be done based on distance between centroids (as in qgis) and also based on distance between features (it is slower, but might be better for multi polygons like USA).

2) Distance to `other_features` is computed for all at once and the loop goes through values without computing distances within the loop. Not sure if it can be done in qgis, but it was a significant change.
https://github.com/martinfleis/greedy/blob/fc19f6ea3e97d949d1f1e6c29b7091e255b9a6e3/greedy/greedy.py#L123-L130 
vs https://github.com/qgis/QGIS/blob/8a3c7b14c367771d096b4a6d006aa3c4b1017dd5/python/plugins/processing/algs/qgis/TopoColors.py#L267-L276

The other enhancements which are not derived from the original - libpysal for adjacency matrix (based on shared points, so there is no spatial operation which gives us performance boost) and inclusion of other algorithms from networkx (aiming to have the smallest number of colors, not a nice balance). Plus a few minor changes here and there.

**Comment by ljwolf** [comment]
Happy to integrate it into pysal (the `splot` package probably would be the best place) if that's an appropriate home!

**Comment by martinfleis** [comment]
@ljwolf I thought splot is focused on spatial statistics more. But happy to discuss this. I'll open an issue on splot.

**Comment by martinfleis** [comment]
Moved to pysal/mapclassify#61.
