### ISSUE TITLE
[DOC] separator missing between function args and dtypes

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1167]
It seems like there is a problem in the doc http://geopandas.org/reference.html

![image](https://user-images.githubusercontent.com/33796896/66942991-43ddc700-f018-11e9-839b-274db98e1771.png)

**Comment by jdmcbr** [comment]
This seems to be resolved:

![image](https://user-images.githubusercontent.com/666108/96329141-f915d700-0ffe-11eb-9f71-b232a53c1729.png)
