### ISSUE TITLE
Window directory go as unknown and can't open multiple shapefiles

### ISSUE THREAD

**Issue by ildoildi** [geopandas/geopandas#1172]
Geopandas.GeoDataFrame can not open multiple shapefiles because of different directories of windows and library
`
   
    import geopandas as gpd
    import matplotlib.pyplot as amarildo 
    from tkinter import filedialog
   
    def test1():

          filetype = [('All files', ' .*'), ('Shapefile .shp', ' .shp')]

          new_file = filedialog.askopenfilename(initialdir = "C:/",title='Select Input File', filetypes = 
          filetype, multiple=True)
          #('C:\\1_AutoCord\\Shp\\Lakes.shp') -- this works
          #('C:/1_AutoCord/Shp/Lakes.shp') -- Windows directory don't work for multiple shapefiles

          bdry_line = gpd.GeoDataFrame.from_file(str(new_file)) 
   
          myploygons = gpd.GeoDataFrame.from_file(str(new_file))

         ax = bdry_line.plot()
         myploygons.plot(axes=ax)

         amarildo.show()
    
         return test1
`
and I get this error: fiona.errors.DriverError: '('C:/1_AutoCord/Shp/Lakes.shp',)' does not exist in the file system, and is not recognized as a supported dataset name.
But if I put it internally as ('C:\\1_AutoCord\\Shp\\Lakes.shp') it works
So how to connect shapefiles on my computer with gpd, because is impossible to import more then one

**Comment by jorisvandenbossche** [comment]
I am not sure this is related to trying to open multiple files. It seems that the file path that fails uses forward slashes and the file path that works uses backslashes as separator, and Windows can be sensitive to this.

**Comment by ildoildi** [comment]
This is the problem, when I upload one shapefile it works doesn't metter the side of slash, but when I upload multiple shapefiles it doesn't work, it require that the shapes should be "internal" at the code.

**Comment by martinfleis** [comment]
@ildoildi have you found a solution/cause? Is it related to some behaviour of GeoPandas, something we can fix on our side?

**Comment by ildoildi** [comment]
No, I have not found a solution. Yes its related with Geopandas, because when I upload one shapefile to the script it works normally, but when I upload multiple shapefiles I get an error that shows me that the path is not correct, meanwhile the path is the same as before. If I put this "\\" internally on the code, code will work. But if I upload from Windows on this format"/", it will not work
