### ISSUE TITLE
Creation of geodataframe shouldn't modify the original dataframe

### ISSUE THREAD

**Issue by xyzjayne** [geopandas/geopandas#1179]
I'm using geopandas 0.5.1 for the example. Creating a geodataframe from a Pandas dataframe modifies the input dataframe, even when the `geometry` is not a column of the input dataframe. This creates an issue especially when the same dataframe is used to create multiple geodataframes, in which case the first geometry definition would always prevail in subsequent operations.

````
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
df = pd.DataFrame({'Name':['Adam','Barbara','Cat','Doug','Ezra','Fiona','Greg'],
                  'lat':[35.5,35.2,34.89,36.1,35.78,35.76,34.99],
                  'lon':[-112.02,-111.09,-115.3,-114.01,-113.02,-112.9,-112.02]})
gdf = gpd.GeoDataFrame(df, geometry = [Point(x,y) for x, y in zip(df.lon,df.lat)])
print(gdf.columns)
>>> Index(['Name', 'lat', 'lon', 'geometry'], dtype='object')
print(df.columns)
>>> Index(['Name', 'lat', 'lon', 'geometry'], dtype='object')
````

**Comment by jdmcbr** [comment]
Thanks for the report and the nice example, @xyzjayne. Confirmed this is still present in master.

**Comment by raphaelquast** [comment]
here's another interesting thing about this:

while the obtained GeoDataFrame does not maintain additional metadata, 
the initial dataframe that has been altered does!

...I know that pandas currently does not support propagation of metadata attributes,
but it would be a very nice feature if geopandas could do so  :-)
(or maybe an 'inplace' option to modify the existing dataframe instead of creating a new one?)


```python
df = pd.DataFrame(dict(lon=[10,20,30], lat=[20,30,40]))
df.meta = 'metadata'

gdf = gpd.GeoDataFrame(df, geometry=[Point(i,j) for i,j in zip(df.lon, df.lat)])

# -------------------------
gdf.meta
>>> AttributeError: 'GeoDataFrame' object has no attribute 'meta'
# -------------------------
df.columns
>>> Index(['lon', 'lat', 'geometry'], dtype='object')
df.meta
>>>'metadata'
```

**Comment by Sangarshanan** [comment]
Would solving this be as easy as adding a `self._data.copy()` in the GeoDataFrame class and creating a copy every time or maybe something like inplace (which pandas might deprecate) or is there anything else I am missing?

**Comment by martinfleis** [comment]
@Sangarshanan can you try that solution?

**Comment by Sangarshanan** [comment]
Sure...will open a PR for this

**Comment by mvonpohle** [comment]
I'm still running into this issue using python 3.10.4, GeoPandas 0.10.2, and Pandas 1.4.2.

**Comment by MordorianGuy** [comment]
Could this behavior be noted at least in the documentation on the official site up until then it is fixed?

**Comment by raybellwaves** [comment]
> Would solving this be as easy as adding a `self._data.copy()` in the GeoDataFrame class and creating a copy every time or maybe something like inplace (which pandas might deprecate) or is there anything else I am missing?

Can confirm in user code adding a `.copy()` works.

```
import geopandas as gpd
import pandas as pd

df = pd.DataFrame(data={"lon": [1, 2, 3], "lat": [1, 2, 3]})
print(df.columns)
# Index(['lon', 'lat'], dtype='object')

gdf = gpd.GeoDataFrame(df,
    geometry=gpd.points_from_xy(df["lon"], df["lat"]),
    crs="epsg:4326",
) 
print(df.columns)
# Index(['lon', 'lat', 'geometry'], dtype='object')

df = pd.DataFrame(data={"lon": [1, 2, 3], "lat": [1, 2, 3]})
gdf = gpd.GeoDataFrame(df.copy(),
    geometry=gpd.points_from_xy(df["lon"], df["lat"]),
    crs="epsg:4326",
) 
print(df.columns)
# Index(['lon', 'lat'], dtype='object')
```
