### ISSUE TITLE
Require pandas 0.23

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1182]
For some reason we do not have pandas in requirements.txt and one on conda-forge is not tied to version. In some cases it conda allows installing geopandas with older pandas (0.22) causing incompatibility (https://stackoverflow.com/questions/58555286/pandas-import-modulenotfounderror-no-module-named-pandas-api-extensions?noredirect=1#comment103439434_58555286).

**Comment by jorisvandenbossche** [comment]
We do have it in setup.py though: https://github.com/geopandas/geopandas/blob/master/setup.py#L32 (so pip install should honour that). But indeed should add it to conda-forge recipe. 

We could also do a runtime check to provide a nicer error message?

**Comment by jorisvandenbossche** [comment]
See https://github.com/conda-forge/geopandas-feedstock/pull/67 for conda-forge !

**Comment by martinfleis** [comment]
@jorisvandenbossche that was quick!

**Comment by martinfleis** [comment]
Fixed by https://github.com/conda-forge/geopandas-feedstock/pull/67.
