### ISSUE TITLE
Can geopandas read and pass the file_schema automatically?

### ISSUE THREAD

**Issue by Mike-Honey** [geopandas/geopandas#1185]
I've stumbled across the issue discussed in #177 , while trying to do a really simple and I'm sure quite common task - simplifying a geojson file. Essentially I used the methods:
read_file
simplify
to_file

I was surprised to find the schema of the properties was changed in my to_file output, e.g. the classic: 
"properties": { "OBJECT_ID" : 1,
became 
"properties": { "OBJECT_ID" : 1.0,

It seemed every numeric field was converted to one decimal place?

Some research turned up #177 and I was able to use the example code to re-open the input file with fiona, catch the schema and pass it to to_file. But this feels quite cludgy and surely the default behavior of geopandas would not be expected by anyone?

Can geopandas be enhanced so: read_file ... simplify ... to_file  will pass the file_schema automatically?

PS: thanks so much for geopandas - it is saving me so much time!

**Comment by DanRunfola** [comment]
+1 from me on this as well! Just ran into this trying to pass schema's around between Fiona and geopandas.

**Comment by martinfleis** [comment]
Hi,
this does not seem to be complicated. Can you provide some sample data we can use to test is? That one in #177 does not work anymore.

I have made a **very** rough attempt to carry schema in https://github.com/martinfleis/geopandas/tree/carry_schema, so you can even try that.

**Comment by martinfleis** [comment]
The complication here is that GeoDataFrame could change significantly between `read_file` and `to_file` and original scheme might not apply anymore. While we should keep it for `simplify`, we should invalidate/change it for `centroid`, for example. In fact, for the majority of cases we would have to change original schema anyway.

**Comment by martinfleis** [comment]
Check #1200. I would still welcome some sample data though.

**Comment by Mike-Honey** [comment]
This turned out to be a bit subtle to repro - needed a None value for an OBJECTID property to trigger the schema change (to decimal number).  

Attached is some input data & output and a script to reproduce the issue.  Note in the schemaTest_out.geojson file, "OBJECT_ID" : 1 becomes "OBJECT_ID" : 1.0.


[schemaTest.zip](https://github.com/geopandas/geopandas/files/3839528/schemaTest.zip)

**Comment by martinfleis** [comment]
Okay, this seems to be a bit more complicated. This is, in fact, behaviour of pandas. If you have missing value in your column of integers it automatically assigns float dtype to the whole column. We then infer schema based on dtypes, that is where the issue comes from. #1200 does not fix that at the moment.

```py
df = pd.DataFrame()
df['col'] = [1, 1]
df['col2'] = [1, np.nan]
df['col3'] = [1, None]

df.dtypes

col       int64
col2    float64
col3    float64
dtype: object
```

**Comment by martinfleis** [comment]
To give you a bit more context: nan in pandas is a float, so it automatically convert the whole column to float dtype. However, there is [nullable integer dtype](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html) (which we should use in this case). In fact, if you have pandas Int64 in your gdf now, to_file will fail, so we need to support that anyway (added to #1200). 

Then we have to check during read_file, once gdf is created whether there is a discrepancy between original schema and used dtypes and convert float to Int64 where applicable.

**Comment by Mike-Honey** [comment]
Thanks for looking into this @martinfleis and for your explanation. Now I understand the root cause I'm happy to close this as it seems beyond the control of geopandas.

**Comment by DanRunfola** [comment]
Thanks all for the update and digging in here.
