### ISSUE TITLE
DOC: add example of simple joining two GeoSeries together (append)

### ISSUE THREAD

**Issue by matkoniecz** [geopandas/geopandas#1186]
I am writing (extremely basic) script using Geopandas and I am stuck a bit due to missing documentation.

I was happy to fing "merging data"  at http://geopandas.org/mergingdata.html because I run into `TypeError: unsupported operand type(s) for +: 'GeometryArray' and 'GeometryArray'` on attempting to merge data split into two such objects.

Sadly, "Merging Data" docs page is not covering simplest possible way of merging data.

For reference my code:
```
data = gpd.read_file(in_file)

if "waterway" in data:
    rivers = []
    streams = []
    rivers = data[data["waterway"] == "river"]
    rivers.geometry = rivers['geometry'].buffer(0.000250)
    streams = data[data["waterway"] == "stream"]
    streams.geometry = rivers['geometry'].buffer(0.000025)
    (rivers + streams).to_file(out_file, driver = 'GeoJSON')
```

EDIT: I asked https://gis.stackexchange.com/questions/340463/merge-two-geometryarray-into-one-one-geometryarray-in-geopandas

**Comment by matkoniecz** [comment]
I found https://jorisvandenbossche.github.io/blog/2017/09/19/geopandas-cython/

> To summarize, we created a numpy array-like object, which we call the GeometryArray, to hold geometry objects:

it appears to not be described at https://geopandas.readthedocs.io/en/latest/data_structures.html

https://geopandas.readthedocs.io/en/latest/search.html?q=GeometryArray&check_keywords=yes&area=default gives "Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories."

**Comment by martinfleis** [comment]
You are looking for simple `append`. Reproducible example:

```py
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
cities = gpd.read_file(gpd.datasets.get_path('naturalearth_cities'))
merged = world.geometry.append(cities.geometry)
```

Your example:
```py
data = gpd.read_file(in_file)

if "waterway" in data:
    rivers = []
    streams = []
    rivers = data[data["waterway"] == "river"]
    rivers.geometry = rivers['geometry'].buffer(0.000250)
    streams = data[data["waterway"] == "stream"]
    streams.geometry = rivers['geometry'].buffer(0.000025)
    rivers.append(streams).to_file(out_file, driver = 'GeoJSON')
```

But yeah, we might add it to docs.

**Comment by awa5114** [comment]
Does this still need to be addressed? If so I would really like to take a look? Thanks.

**Comment by martinfleis** [comment]
@awa5114 it is being fixed in #1215.

**Comment by awa5114** [comment]
Any open documentation issues I can take a look at which have not been addressed yet?

**Comment by martinfleis** [comment]
You can check #524 and #529. But first check what is already included on geopandas.readthedocs.io and in examples folder.
