### ISSUE TITLE
ENH: move CRS metadata to array level (allow columns with different CRS)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1193]
Currently, the CRS (`.crs` attribute) is kept track of at the GeoDataFrame (or GeoSeries if selecting the column) level. This means it is implicitly the CRS for the "active" geometry column. 

We could also look into moving the metadata to the GeometryArray. This feels more correct anyhow, and would allow to have multiple columns with different CRS (which would be especially relevant if returning a GeoSeries for other geometry columns as well -> https://github.com/geopandas/geopandas/issues/1192). 
The GeoDataFrame.crs would keep pointing to the crs of the active geometry column, to ensure to preserve the current behaviour.

**Comment by rwijtvliet** [comment]
Would definitely be an improvement, also regarding reprojecting of the GeoDataFrame; see [here](https://gis.stackexchange.com/q/351325/158505) for a use case that would then work.

**Comment by diptosarkar** [comment]
This is absolutely necessary as one of the most attractive features of Geopandas is the ability to support multiple geometry columns.

Currently, as the crs information is stored at the table level, there is no way to project the entire Geodataframe easily too.

**Comment by martinfleis** [comment]
@diptosarkar This has been already implemented. Each GeometryArray/GeoSeries can have its own CRS.

CRS is not stored at the GeoDataFrame level unless there's no active geometry. 

> there is no way to project the entire Geodataframe easily too.

What do you mean by this? Reprojecting multiple columns at the same time?

**Comment by diptosarkar** [comment]
> 
> 
> @diptosarkar This has been already implemented. Each GeometryArray/GeoSeries can have its own CRS.
> 
> CRS is not stored at the GeoDataFrame level unless there's no active geometry.
> 
> > there is no way to project the entire Geodataframe easily too.
> 
> What do you mean by this? Reprojecting multiple columns at the same time?

Yes. That is what I meant. We can't reproject multiple columns. Here is my workaround:
`gdf = gdf.to_crs("EPSG:32618")
gdf.crs="EPSG:4326"
gdf = gdf.set_geometry("end_geometry")
gdf = .to_crs("EPSG:32618")`

Note that, by setting gdf.crs manually, I tricked it into thinking the data was unprojected. So, when I changed the active geometry column and tried projection again, it changed the projection for the second geometry column. Without changing the crs manually, the second projection does not work as geopandas thinks that the dataframe is already in the correct projection.

**Comment by martinfleis** [comment]
You can reproject individual columns.

```py
gdf.geom1 = gdf.geom1.to_crs(32618)
gdf.geom2 = gdf.geom2.to_crs(32618)
gdf.geom3 = gdf.geom3.to_crs(32618)
```
Or automatically loop through all GeoSeries:

```py
gdf = geopandas.read_file(geopandas.datasets.get_path("nybb"))
gdf["centroid"] = gdf.centroid
gdf["representative_point"] = gdf.representative_point()

for col in gdf.columns[gdf.dtypes == "geometry"]:
    gdf[col] = gdf[col].to_crs(4326)
```

No need for these tricks.

**Comment by diptosarkar** [comment]
> 
> 
> You can reproject individual columns.
> 
> ```python
> gdf.geom1 = gdf.geom1.to_crs(32618)
> gdf.geom2 = gdf.geom2.to_crs(32618)
> gdf.geom3 = gdf.geom3.to_crs(32618)
> ```
> 
> Or automatically loop through all GeoSeries:
> 
> ```python
> gdf = geopandas.read_file(geopandas.datasets.get_path("nybb"))
> gdf["centroid"] = gdf.centroid
> gdf["representative_point"] = gdf.representative_point()
> 
> for col in gdf.columns[gdf.dtypes == "geometry"]:
>     gdf[col] = gdf[col].to_crs(4326)
> ```
> 
> No need for these tricks.

This is great. Thanks. In my case, the geometries came from table joins. The dataframe was converted to a geodataframe after the join using:
`gdf = gpd.GeoDataFrame(df, crs="EPSG:4326")`
 For some reason, the second geometry did not have a default crs associated with it. So, I had to run the following:
gdf.geometry2 = gpd.GeoSeries(trips_gdf.geometry2, crs = "EPSG:4326").to_crs(32618)

**Comment by diptosarkar** [comment]
> 
> 
> > You can reproject individual columns.
> > ```python
> > gdf.geom1 = gdf.geom1.to_crs(32618)
> > gdf.geom2 = gdf.geom2.to_crs(32618)
> > gdf.geom3 = gdf.geom3.to_crs(32618)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or automatically loop through all GeoSeries:
> > ```python
> > gdf = geopandas.read_file(geopandas.datasets.get_path("nybb"))
> > gdf["centroid"] = gdf.centroid
> > gdf["representative_point"] = gdf.representative_point()
> > 
> > for col in gdf.columns[gdf.dtypes == "geometry"]:
> >     gdf[col] = gdf[col].to_crs(4326)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No need for these tricks.
> 
> This is great. Thanks. In my case, the geometries came from table joins. The dataframe was converted to a geodataframe after the join using:
> `gdf = gpd.GeoDataFrame(df, crs="EPSG:4326")`
> For some reason, the second geometry did not have a default crs associated with it. So, I had to run the following:
> `gdf.geometry2 = gpd.GeoSeries(trips_gdf.geometry2, crs = "EPSG:4326").to_crs(32618)`

I also noticed that when using this method, the crs associated with the GeoDataFrame is not updated automatically.

**Comment by martinfleis** [comment]
> I also noticed that when using this method, the crs associated with the GeoDataFrame is not updated automatically.

That is a proper bug. -> #1960
