### ISSUE TITLE
Add tests for pathlib support in read_file / to_file

### ISSUE THREAD

**Issue by soxofaan** [geopandas/geopandas#1199]
`to_file` fails when given a `pathlib.Path` object with this exception:

```
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

Current workaround is converting the path object to a string before passing it to `to_file`, but it would be nice if geopandas supported pathlib path objects by default.

somewhat related to #388

**Comment by martinfleis** [comment]
Hi, can you provide easy reproducible example we can play with? Fiona should already support this so there should not be any block to implement it.

> somewhat related to #388

It seems to be exactly the same issue. Can we move the discussion (example) there to keep everything at one place?

**Comment by jdmcbr** [comment]
I think these are actually distinct issues. #388 is about handling open file objects; `pathlib` provides a path object that acts kind of like a str that represents a path to a file, but has additional capabilities.

That said, I'm not sure where the issue is coming in, so a reproducible example would be useful, @soxofaan. I can do the following:
```
In [1]: gdf = gpd.read_file(gpd.datasets.get_path("nybb"))

In [2]: import pathlib

In [3]: outpath = pathlib.Path("/home/james/nybb.shp")

In [4]: outpath
Out[4]: PosixPath('/home/james/nybb.shp')

In [5]: gdf.to_file(outpath)

In [6]: assert os.path.exists(outpath)
```

**Comment by jorisvandenbossche** [comment]
Also reading seems to work for me:

```
In [12]: path = geopandas.datasets.get_path("nybb")

In [13]: import pathlib   

In [15]: path = pathlib.Path(path) 

In [16]: geopandas.read_file(path)
Out[16]: 
   BoroCode       BoroName     Shape_Leng    Shape_Area                                           geometry
0         5  Staten Island  330470.010332  1.623820e+09  MULTIPOLYGON (((970217.022 145643.332, 970227....
1         4         Queens  896344.047763  3.045213e+09  MULTIPOLYGON (((1029606.077 156073.814, 102957...
2         3       Brooklyn  741080.523166  1.937479e+09  MULTIPOLYGON (((1021176.479 151374.797, 102100...
3         1      Manhattan  359299.096471  6.364715e+08  MULTIPOLYGON (((981219.056 188655.316, 980940....
4         2          Bronx  464392.991824  1.186925e+09  MULTIPOLYGON (((1012821.806 229228.265, 101278...
```

In any case, it would be good to add tests for this, to ensure it keeps working.

**Comment by soxofaan** [comment]
Never mind, apparently I'm working in an environment with geopandas pinned down to version 0.3.0
In another environment with version 0.6.1, things work smoothly indeed.

Example code:

```python
import geopandas as gpd
import pathlib

df = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))

work_dir = pathlib.Path.cwd()
print(work_dir)

df.to_file(work_dir / "tmp")
```

**Comment by jorisvandenbossche** [comment]
OK, good to hear! 
Let's leave this open to add some tests
