### ISSUE TITLE
Legend ranges are not mutually exclusive

### ISSUE THREAD

**Issue by rbuffat** [geopandas/geopandas#1203]
Currently, the legend is produced in the following form:

```
0 - 5
5 - 10
10 - 15
```
https://github.com/geopandas/geopandas/blob/00d9fd281ee4891215e96bd4cb15e82c87ab232b/geopandas/plotting.py#L560

However, in this example, it is not clear to which category the value 5 should belong. 

I would suggest changing the legend entries to something in the following form:

```
x <= 5
5 < x <= 10
10 < x
```

**Comment by martinfleis** [comment]
Hi @rbuffat,

thanks for the suggestion. It has already been discussed in #1087, but I don't think @sjsrey actually did a PR (which might be related to the release schedule of mapclassify & pysal?). Would that solution make sense to you?

**Comment by rbuffat** [comment]
@martinfleis  Oops, didn't found this issue. The label formatting looks very nice!
