### ISSUE TITLE
Adding a "warning" during Spatial Joins

### ISSUE THREAD

**Issue by albertkun** [geopandas/geopandas#1204]
I am wondering if it is possible to print out a warning statement when conducting a spatial join? I think I am aware that geopandas uses "shapely" to handle the joins, but was wondering if a simple "Warning: CRS does not match" message would be possible to add. Since geopandas has Coordinate Reference System metadata available, I would think a try-statement might suffice?

**Comment by jorisvandenbossche** [comment]
There should be such warning right now:

https://github.com/geopandas/geopandas/blob/00d9fd281ee4891215e96bd4cb15e82c87ab232b/geopandas/tools/sjoin.py#L57-L63

Is that what you mean? In what case would you want to see a warning?

**Comment by albertkun** [comment]
Hello! Yes! That is exactly what I was requesting! Thank you very much! Which version of geopandas can I test this out in?

**Comment by jorisvandenbossche** [comment]
What version are you using? (you can check `geopandas.__version__`) 
This should be included in already the last couple of releases
