### ISSUE TITLE
Color scheme options reduced?

### ISSUE THREAD

**Issue by NHameleers** [geopandas/geopandas#1207]
Early September I made some plots with the 'natural_breaks' colorscheme and with a 'user-defined' colorscheme. Both of these options now result in a ValueError:

Invalid scheme. Scheme must be in the set: dict_keys(['equal_interval', 'quantiles', 'fisher_jenks', 'fisher_jenks_sampled'])

Looking at plotting.py it seems the number of scheme options has been reduced. Is there a way I can still use the extended set of color schemes as described in the [geopandas documentation](http://geopandas.org/mapping.html#choropleth-maps), or a user-defined one? Or perhaps pass a mapclassify object (which now also results in an error if passed as scheme argument, because it is not a string with lower() method).

**Comment by martinfleis** [comment]
@NHameleers Which version of geopandas are you using? It has not been reduced, it still support all mapclassify methods. What happened is the change of naming convention on mapclassify side, but you should not face that issue with geopandas.

**Comment by NHameleers** [comment]
version 0.4.1

**Comment by NHameleers** [comment]
I'll try to update. Thanks for your quick reply!

**Comment by martinfleis** [comment]
The current version is 0.6.1. You were using 0.5 or 0.6 in September.
