### ISSUE TITLE
Deprecation warning when using with the latest pyproj version

### ISSUE THREAD

**Issue by AjayThorve** [geopandas/geopandas#1213]
Basically when I try to load a file, and execute .to_crs, pytests give deprecation warnings:

Simple repro:
-----------------

test.py
```python
import geopandas as gpd
data = open('../tests/test.geojson').read()
t = gpd.read_file(data)
t = t.to_crs(epsg=3857) #even tried t.to_crs(3857)
```

```bash
pytest test.py
```

Output:
```bash
collected 0 items                                                                                                                                                                 

================================================================================ warnings summary =================================================================================
/***/lib/python3.6/site-packages/pyproj/crs.py:122
/***/lib/python3.6/site-packages/pyproj/crs.py:122
/***/lib/python3.6/site-packages/pyproj/crs.py:122
/***/lib/python3.6/site-packages/pyproj/crs.py:122
  /***/lib/python3.6/site-packages/pyproj/crs.py:122: DeprecationWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
    DeprecationWarning,

```

Environment: **python 3.6.7, geopandas 0.6.2, pyproj 2.4.1**

PS: This does not happen with **pyproj 1.9.6**

**Comment by jorisvandenbossche** [comment]
@AjayThorve Yes, this is expected at the moment. Pyproj started deprecating the {'init': ..} syntax, but geopandas is still using it. We are working to get geopandas updated to only use the latest pyproj: https://github.com/geopandas/geopandas/pull/1101 (which will also solve those warnings). This will be included in the next geopandas release.

However, I would personally recommend to actually already start using the newer pyproj versions (and thus live with the deprecation warning for now; a user should not yet see the DeprecationWarning in an interactive environment such as the console). The reason for this is that pyproj > 2 changed a lot (for good), and it's probably already good to start testing it now (despite the deprecation warning you see, geopandas *is* already using the new pyproj version).

**Comment by AjayThorve** [comment]
Thanks @jorisvandenbossche for the response, that helps.

**Comment by maxblee** [comment]
The [documentation for managing projections](https://geopandas.org/projections.html) currently uses this deprecated syntax. For instance: `my_geoseries.crs = {'init' :'epsg:4326'}`. Can this be updated? (Also, am I correct in thinking that the example above should just be rewritten to `my_geoseries.crs = "epsg:4326"`?)

**Comment by jorisvandenbossche** [comment]
@maxblee thanks for noticing! The docs for 0.7.0 were updated with the new syntax, but geopandas.org was not yet updated with those latest docs. I did that now, so https://geopandas.org/projections.html should now show the correct syntax. 
And that is indeed to do `my_geoseries.crs = "EPSG:4326"`
