### ISSUE TITLE
BUG: GeoSeries.reset_index() gives DataFrame not GeoDataFrame

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1216]
Having GeoSeries with MultiIndex, GeoSeries.reset_index() returns pandas DataFrame not GeoDataFrame as I would expect in such a case. 

```python
import geopandas as gpd
gpd.__version__
```

    '0.6.1+17.g1132cc8'

```python
nybb = gpd.read_file(gpd.datasets.get_path('nybb'))
geoms = nybb.geometry
geoms = geoms.explode()  # nybb has multipolygons, so we get multiindex
type(geoms)
```

    geopandas.geoseries.GeoSeries

```python
geoms = geoms.reset_index()
type(geoms)
```

    pandas.core.frame.DataFrame

**Comment by jorisvandenbossche** [comment]
We might be able to fix this by defining `GeoSeries._constructor_expanddim` to be GeoDataFrame (that's at least being used in `Series.to_frame`, which is being used in `Series.reset_index`; but should need to check in what other cases this `_constructor_expanddim` is being used).
