### ISSUE TITLE
DOC/RTD: readthedocs failing due to excessive memory consumption

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1219]
RTD currently fails. https://readthedocs.org/projects/geopandas/builds/10001022/

`Command killed due to excessive memory consumption`

The only change which could affect this part was pinning geoplot to 0.4.0 in #1218. @ResidentMario any idea if there are additional memory demands compared to 0.3.0? Any new dependencies?

**Comment by ResidentMario** [comment]
Hmm, that is concerning. Here are the `setup.py` files [for 0.4.0](https://github.com/ResidentMario/geoplot/blob/5a67ad9e692cfd31f5e7eddcee9a4e5494fb647f/setup.py) and [for 0.3.0](https://github.com/ResidentMario/geoplot/blob/9466bc0bd154e290d9b39302e88d1a79de15c603/setup.py). Two dependencies have been added in the meantime: `mapclassify`, and `
contextily>=1.0rc2`.

**Comment by martinfleis** [comment]
That should not make the difference, both were already in environment.yml. 🤔

**Comment by jorisvandenbossche** [comment]
I don't think it is related to geoplot as such. The main problem with conda on readthedocs is that conda can use a lot of memory to "solve" the environment (giving that error). That's the main reason that the current environment.yml file for the docs in a "fully pinned" one, to make it easier for conda to solve it and thus use less memory. 
But, that means that whenever you change something in the pinning in that file, you should actually check if the new pinning works as is (create the env locally), and if you don't have to edit something else.

**Comment by martinfleis** [comment]
@jorisvandenbossche It works locally, I checked that before merging.

**Comment by jorisvandenbossche** [comment]
Although that doesn't seem to be the problem .. ;) Tried it locally, and solving is very fast, no conflicts are mentioned (so all pins match I suppose). I also see that on readthedocs, it actually failed in the last step

**Comment by jorisvandenbossche** [comment]
It's clearly not a problem of the changed environment.yml file, since the build is also failing on stable and v0.6.2 (not sure who triggered those though): https://readthedocs.org/projects/geopandas/builds/

So something must have changed on the readthedocs side I suppose ..

**Comment by jorisvandenbossche** [comment]
I asked at the old issue about this: https://github.com/readthedocs/readthedocs.org/issues/5598. If I don't get a response the coming days there, will open a new issue.

**Comment by martinfleis** [comment]
Closing as it seems to be fixed after the increase of the limit https://github.com/readthedocs/readthedocs.org/issues/5598#issuecomment-558293126. I assume it is temporary only due to the transition to py38 anyway.
