### ISSUE TITLE
Rtree 0.9 changes behaviour

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1221]
As shown [here](https://travis-ci.org/geopandas/geopandas/jobs/616885697), new rtree changed its behaviour which broke our tests. I assume that it no longer raises `RTreeError`, but I haven't tested it yet. It is not critical to anything, but we should fix it to make Travis green again.

https://github.com/geopandas/geopandas/blob/6ac19052c811b39fea88b40625c69246f733709d/geopandas/base.py#L114-L120

**Comment by jorisvandenbossche** [comment]
It seems it indeed doesn't raise an error any more when constructing from an empty stream (eg in case of an empty GeoSeries). But the created index object from such empty stream also doesn't seem to work properly. Opened https://github.com/Toblerity/rtree/issues/122 for this
