### ISSUE TITLE
DOC: add explanation of using zorder to control which layers are on top

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1224]
See eg https://stackoverflow.com/questions/59052898/why-are-line-plots-in-geopandas-ignoring-plot-order-when-it-comes-to-display-lay (@martinfleis was faster in answering ;))

We should add some explanation to the mapping docs on this.

**Comment by jorisvandenbossche** [comment]
Also wondering if we could actually "fix" this, so the expectation that the order of plotting defines this is respected. 
In principle you could (if no manual zorder is specified) [check the max zorder of the collections already plotted, and then specify that +1

**Comment by Sangarshanan** [comment]
I faced the same issue a while back and @martinfleis answer was golden.. I would love to help out and contribute to the docs. I was also wondering how exactly you wanted to make the order of plotting more clearer ?

**Comment by martinfleis** [comment]
> Also wondering if we could actually "fix" this, so the expectation that the order of plotting defines this is respected.

@jorisvandenbossche Matplotlib has its defaults as patch 1, line 2 and text 3. If we checked the max zorder, we would be inconsistent with it. I would rather not do it, you can end up with super complicated mess of default/set/derived zorders.

@Sangarshanan my pleasure :). If you want to make an example on `zorder`, mapping is the best place for that. https://github.com/geopandas/geopandas/blob/master/doc/source/mapping.rst . I would give couple of examples in a similar manner matplotlib has: https://matplotlib.org/3.1.1/gallery/misc/zorder_demo.html.
