### ISSUE TITLE
is v0.6.2 the latest version, why I still get error "Unknown property missing_kwds"

### ISSUE THREAD

**Issue by shuai-zhou** [geopandas/geopandas#1247]
The latest release is v0.6.2, and I installed it. But when I was trying to plot missing using the "missing_kwds" from [here](https://geopandas.readthedocs.io/en/latest/mapping.html), I got an error saying that "Unknown property missing_kwds". Is the version [here](https://geopandas.readthedocs.io/en/latest/mapping.html) still under development and the feature has not been published in v0.6.2?

**Comment by martinfleis** [comment]
Hi, 0.6.2 is indeed the latest version. However, `missing_kwds` will be released as a part of v.0.7.0. The documentation on readthedocs refers to the development version of geopandas (master branch), the documentation of releases is on geopandas.org. If you want to use master, you already can. You just have to install geopandas directly from git.

`pip install git+git://github.com/geopandas/geopandas.git`

**Comment by HalukaMB** [comment]
Hey there. I just followed this thread and also did 
`pip install git+git://github.com/geopandas/geopandas.git`

However, when I run

```
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
gdf.loc[np.random.choice(gdf.index, 40), 'pop_est'] = np.nan
gdf.plot(column='pop_est', figsize=(15, 10), legend=True,
         missing_kwds={'color': 'lightgrey'})

```

I get the error "AttributeError: 'PatchCollection' object has no property 'missing_kwds'"

**Comment by martinfleis** [comment]
@HalukaMB can you show your `geopandas.show_versions()`?

**Comment by HalukaMB** [comment]
Ok, this is confusing. When I do` pip freeze`, I get:
`geopandas @ git+git://github.com/geopandas/geopandas.git@9fdeb1474185c8d2edaede428f57d258810d87b7
`
However, on `gpd.show_versions()`

I end up with 
`geopandas  : 0.6.2`

**Comment by martinfleis** [comment]
That is the culprit. You have some mess in your environment causing an import of an old version.
