### ISSUE TITLE
BUG: Indexing GeometryArray with boolean array mask

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1257]
Pandas added tests (pandas-dev/pandas#30308) for indexing ExtensionArray with boolean array mask, which are failing with our GeometryArray (https://travis-ci.org/geopandas/geopandas/jobs/633241442). I did not dig deep into the issue, but it seems that something is not supported by GeometryArray and it should be.

This is causing our dev CI fail at the moment (the second (shapely) issue is being fixed in #1244 .

**Comment by jorisvandenbossche** [comment]
Yes, this was expected to give failures here. That same PR (https://github.com/pandas-dev/pandas/pull/30308) also added some utility functions to deal with this change. Will do a PR to fix this.
