### ISSUE TITLE
rtree included in Conda distribution

### ISSUE THREAD

**Issue by DanRunfola** [geopandas/geopandas#1261]
Hey guys -

Ok, so it's possible I'm doing something wrong here, but when I run this command:

conda install -c conda-forge/label/gcc7 geopandas python=3.6.8 -n python3.6

I get rtree as a dependency from conda:
```
The following NEW packages will be INSTALLED:

    cycler:           0.10.0-py_1              conda-forge/label/gcc7
    dbus:             1.13.12-h746ee38_0                             
    descartes:        1.1.0-py_2               conda-forge/label/gcc7
    geopandas:        0.4.0-py_1               conda-forge/label/gcc7
    gst-plugins-base: 1.14.0-hbbd80ab_1                              
    gstreamer:        1.14.0-hb453b48_1                              
    kiwisolver:       1.0.1-py36h6bb024c_1002  conda-forge/label/gcc7
    matplotlib:       3.0.2-py36h8a2030e_1001  conda-forge/label/gcc7
    matplotlib-base:  3.0.2-py36h167e16e_1001  conda-forge/label/gcc7
    palettable:       3.1.1-py_0               conda-forge/label/gcc7
    patsy:            0.5.0-py_1               conda-forge/label/gcc7
    psycopg2:         2.8.4-py36h1ba5d50_0                           
    pyparsing:        2.2.1-py_0               conda-forge/label/gcc7
    pyqt:             5.6.0-py36h13b7fb3_1008  conda-forge/label/gcc7
    pysal:            2.0.0-py_0                                     
    qt:               5.6.3-h8bf5577_3                               
    rtree:            0.8.3-py36_0                                   
    scipy:            1.3.2-py36h7c811a0_0                           
    seaborn:          0.9.0-py_0               conda-forge/label/gcc7
    sip:              4.18.1-py36hf484d3e_1000 conda-forge/label/gcc7
    sqlalchemy:       1.2.16-py36h14c3975_1000 conda-forge/label/gcc7
    statsmodels:      0.9.0-py36h3010b51_1000  conda-forge/label/gcc7
    tornado:          5.1.1-py36h14c3975_1000  conda-forge/label/gcc7
```

I can definitely see value in including rtree, but would it be possible to include a branch without rtree included?

Thanks for any thoughts and feedback on this!
Dan

**Comment by ocefpaf** [comment]
> I can definitely see value in including rtree, but would it be possible to include a branch without rtree included?

That request should be in the geopandas feedstock and not here at the source code for it. However, the decision to include `rtree` was made by the original authors of the library and, if I recall correctly, the PyPI version does not have it as a mandatory dependency b/c there are no `rtree` wheels to do so.

**Comment by jorisvandenbossche** [comment]
I think it is fine to discuss general packaging / distribution stuff here, as it has more visibility for potentially interested people.

I have been thinking lately about having a "geopandas-base" package on conda-forge that has less dependencies (similarly to how dask and matplotlib also do something like this I think?)

Also `fiona` would be a possible target for leaving out in a "slim" package+deps.

**Comment by ocefpaf** [comment]
> I think it is fine to discuss general packaging / distribution stuff here, as it has more visibility for potentially interested people.

I'm +1 to that but most maintainers are weary of conda-forge package questions downstream, so I try to be proactive and mentioned that upstream may be better.

**Comment by DanRunfola** [comment]
I'll leave the philosophy of where this should leave to ya'll, but a geopandas-base would be a beautiful thing to see.  I'm personally dealing with a multiple-architecture spark / hadoop cluster, which is what prompted me to raise this.  

I'll go ahead and close this out and re-create with a link on the feedstock.

**Comment by jorisvandenbossche** [comment]
Another idea could be to add *back* matplotlib in `geopandas`, if `geopandas-base` can then provide one without it (although I would need to look back at the discussion that prompted to remove matplotlib as dep on conda-forge)

**Comment by jorisvandenbossche** [comment]
Note, fiona is not possible right now to remove, as it is a required dependency (it's imported on geopandas import). But it would only be a small code restructure to make it an optional dependency.

**Comment by martinfleis** [comment]
I like the idea of having the very minimal `geopandas-base` and then normal `geopandas` with all dependencies you would expect to use normally (e.g. matplotlib, descartes, maybe even mapclassify). Then you provide comfort for normal users and options for others.

**Comment by DanRunfola** [comment]
I'll try to hammer out a pull request over the next few weeks for this (tm).

**Comment by asmaier** [comment]
From a users point of view what I really don't like is that if I construct a geodataframe and then call a function on that object it can fail because of a missing dependency:

```
import geopandas as gpd

world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
world.plot(...)  # fails with missing matplotlib dependency
```
It basically means the object constructed is incomplete and invalid.
Even worse is when that happens if I just add a new parameter to the function
```
import geopandas as gpd
import matplotlib.pyplot as plt

world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
world.plot(..., scheme='quantiles)  # fails with missing mapclassify dependency
```
Both cases violate the "Principle of least surprise". 

However my suggestion would be to handle this issue not by creating a geopandas and a geopandas-base package. Instead I suggest to move functions dependent on optional dependencies into sub-packages like this:
```
import geopandas as gpd
import geopandas.plotting as plt  # fails at import time, when matplotlib is missing
import geopandas.classify as cls # fails at import time, when mapclassify is missing

world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
plt.plot(world, ..., scheme=cls.quantiles)  
```
The advantage would be that an error caused by missing dependencies could already be thrown at import time. This is much more transparent to the user and in accordance with the "fail early" philosophy.

**Comment by jorisvandenbossche** [comment]
I am attempting creating a `geopandas-base` for conda-forge at https://github.com/conda-forge/geopandas-feedstock/pull/90, and then adding matplotlib as a dependency for `geopandas`. (note, conda-forge only, not for pip)

**Comment by martinfleis** [comment]
`geopandas-base` flavour is now available.
