### ISSUE TITLE
Error to_crs : ellipsoid do not belong to the same celestial body

### ISSUE THREAD

**Issue by Skealz** [geopandas/geopandas#1264]
Versions :
geopandas : 0.6.2
pyproj : 2.3.1
(I am using conda)

When doing 
```
tracks.crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
#Or
tracks.crs = {'init': 'epsg:4326'}
tracks_data = tracks.to_crs(crs=ccrs.PlateCarree(central_longitude=lonOffset).proj4_init)
```

I have : 
```
pyproj.exceptions.ProjError: Error creating CRS to CRS.: (Internal Proj Error: proj_create_operations: Source and target ellipsoid do not belong to the same celestial body)
```
When searching for this issue I found some [links](http://osgeo-org.1560.x6.nabble.com/PROJ-Source-and-target-ellipsoid-do-not-belong-to-the-same-celestial-body-td5399777.html) saying that a verification has recently been added to pyproj to avoid mapping CRS to wrong planets (project Earth CRS to the Moon for example).

But this is not what I'm doing (maybe I'm misusing geopandas).

I tried downgrading to pyproj 1.9.6 and it perfectly works.

**Comment by martinfleis** [comment]
It looks okay from the Geopandas perspective. Seems to be caused by changes in `pyproj`. 
cc @snowman2

**Comment by snowman2** [comment]
It is due to the plate caree implementation in cartopy. See:
- https://github.com/SciTools/cartopy/pull/1252#issuecomment-502328242
- https://github.com/SciTools/cartopy/pull/1252#issuecomment-504680237
- https://github.com/SciTools/cartopy/pull/1252#issuecomment-505057870
