### ISSUE TITLE
Read crs from geojson in from_features

### ISSUE THREAD

**Issue by ktollas** [geopandas/geopandas#1266]
If geojson has 'crs' as a key, set that as crs in from_features (https://github.com/geopandas/geopandas/blob/943186e7d4a14f5fa496ee60b2ffbc570c26c08b/geopandas/geodataframe.py#L250)

**Comment by sgillies** [comment]
The GeoJSON format does not allow coordinate reference systems other than CRS84. I'm not saying that such files don't exist, but they are broken and should be dealt with by setting the crs after reading.
