### ISSUE TITLE
Again: libkea.so.1.4.7: cannot open shared object file

### ISSUE THREAD

**Issue by Sieboldianus** [geopandas/geopandas#1273]
I've seen reports of `libkea.so.1.4.7: cannot open shared object file` from 2017 onwards.

I tried to follow all the suggestions, but I still get the error on a new conda env based on the following setup:

```bash
conda config --remove channels defaults
conda create -n jupyter_env python=3.7 -c conda-forge
conda activate jupyter_env
conda install -c conda-forge geopandas fiona jupyterlab geoviews holoviews nbconvert libgdal geoplot
```

In a jupyter notebook:
```python
import geoviews as gv
import geoviews.feature as gf
from pathlib import Path
from shapely.geometry import shape
from shapely.geometry import Point
import geopandas as gp
import pandas as pd
import numpy as np
import holoviews as hv
hv.notebook_extension('bokeh')
```

Error at:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-3fde873047b6> in <module>
      5 from shapely.geometry import Point
      6 # from fiona.crs import from_epsg
----> 7 import geopandas as gp
      8 import pandas as pd
      9 import numpy as np

~/miniconda3/envs/jupyter_env/lib/python3.7/site-packages/geopandas/__init__.py in <module>
      3 from geopandas.array import _points_from_xy as points_from_xy  # noqa
      4 
----> 5 from geopandas.io.file import read_file  # noqa
      6 from geopandas.io.sql import read_postgis  # noqa
      7 from geopandas.tools import sjoin  # noqa

~/miniconda3/envs/jupyter_env/lib/python3.7/site-packages/geopandas/io/file.py in <module>
      4 import six
      5 
----> 6 import fiona
      7 
      8 from geopandas import GeoDataFrame, GeoSeries

~/miniconda3/envs/jupyter_env/lib/python3.7/site-packages/fiona/__init__.py in <module>
     82     os.environ["PATH"] = os.environ["PATH"] + ";" + libdir
     83 
---> 84 from fiona.collection import BytesCollection, Collection
     85 from fiona.drvsupport import supported_drivers
     86 from fiona.env import ensure_env_with_credentials, Env

~/miniconda3/envs/jupyter_env/lib/python3.7/site-packages/fiona/collection.py in <module>
      7 
      8 from fiona import compat, vfs
----> 9 from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
     10 from fiona.ogrext import Session, WritingSession
     11 from fiona.ogrext import buffer_to_virtual_file, remove_virtual_file, GEOMETRY_TYPES

ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory
```

I post it here because the error gets raised during geopandas support, but I can also create an issue for fiona. Any recommendations for workarounds?

Note: there's also [this](https://github.com/conda-forge/fiona-feedstock/issues/138) issue for the fiona conda-forge feedstock, but is is open since September 2019..

**Comment by jorisvandenbossche** [comment]
Can you try adding `conda config --set channel_priority strict` before creating the env? 

If that doesn't work, can you open an issue on the fiona or [gdal](https://github.com/conda-forge/gdal-feedstock) feedstock? (it's not a geopandas issue as such, meaning nothing we can do about it in *this* repo) 
And when doing that, ensure to show the output of `conda list` as well.

**Comment by ocefpaf** [comment]
@Sieboldianus as @jorisvandenbossche this is not a `geopandas` issue. Not that even though you removed `defaults`, `conda` does not behave as you expect there and will still pull packages from the `main` channel (`defaults`). The only "right" way to avoid such conflicts is activating the `strict` channel option that @jorisvandenbossche mentioned. That worked for me locally.

PS: I was also able to reproduce your problem when I removed `defaults` instead of using `strict`.

**Comment by Sieboldianus** [comment]
Tested. Works with `channel_priority strict` (not ideal, because some combination of packages cannot be installed this way, but ok as a workaround atm).

Thanks so much!

**Comment by ocefpaf** [comment]
> not ideal, because some combination of packages cannot be installed this way

When that happens we have a real bug and/or missing dependencies in conda-forge, please open an issue there. When working with multiple channels strict is the only way to ensure a stable env.
