### ISSUE TITLE
New feature: leveraging the STRtree in shapely

### ISSUE THREAD

**Issue by alessioarena** [geopandas/geopandas#1278]
Hi all,

I just discovered the STRtree in shapely and I was wondering why this is not used in geopandas.
The performance improvement compared to the 'intersects' operation is definitely worth considering.

This returns intersecting geometries, but there is a discussion [here](https://github.com/Toblerity/Shapely/issues/618) about an additional workaround to return the index of intersecting geometries instead. For my application I made a simple code snippet that could be improved and added to geopandas.

```
from shapely.strtree import STRtree
def _build_STRtree(geometries):

    def store_index(row):
        geom = row.geometry
        geom.name = row.name
        return geom

    geometries = geometries.apply(store_index, axis=1)
    return STRtree(geometries.values)
```

This can then be used to query in this way
```
import geopandas as gpd
import pandas as pd
from itertools import compress

#load data
test_data = gpd.read_file(gpd.datasets.get_path('naturalearth_cities'))
#artificially increase the size of data
test_data = gpd.GeoDataFrame( pd.concat( [test_data]*20, ignore_index=True) )
test_data.shape
# (4040, 2)

# return the index of intersecting geometries
#using STRtree
geometry_tree = _build_STRtree(test_data)
results_STRtree_index = test_data.apply(lambda row: [o.name for o in geometry_tree.query(row.geometry.buffer(1))], axis=1)
# on my system, 858ms walltime

#using classic intersects
results_intersects_index = test_data.apply(lambda row: list(compress(test_data.index.values, test_data.intersects(row.geometry.buffer(1)))), axis=1)
# on my system 1m 17s walltime
```

In my case I'm using it to cluster polygons based on a minimum separation distance, based on something similar to this:
```
results_STRtree_index.apply(lambda row: min(row))
```

However I can already imagine several other applications for this.

I didn't perform extensive tests, but the STRtree seems holding very well even with very large datasets

**Comment by brendan-ward** [comment]
@alessioarena provided I read your example above correctly, there is a key difference between querying the `STRtree` and performing geometric intersections:
* `tree.query()` finds geometries from the tree that have envelopes that overlap the envelope of your input geometry (in your case a buffer).  Not all geometries returned will geometrically intersect your buffer.
* `intersects()` evaluates the actual geometric intersection between your buffers and the target geometries.

Typically, you would do this in 2 passes: query a spatial index (via `tree.query()` or via existing `sjoin`) to find potentially overlapping geometries, then perform intersection against just those.

My suggestion for your use case is to buffer your input geometries, then do a `sjoin` against your original geometries.


Related:
`STRtree` is implemented in `pygeos` (https://pygeos.readthedocs.io/en/latest/strtree.html) and I believe that will be integrated into `shapely` and `geopandas` - so this particular tree implementation may be available at some point.  See #1155 and https://github.com/Toblerity/Shapely/issues/782

**Comment by alessioarena** [comment]
Yes, after further testing I did notice that. I'm now using the approach you described.
For my application I want to cluster polygons without modifying the actual polygons or the GeoDataFrame structure.

This is to then perform a `data.groupy('cluster').apply(func)` operation.

**Comment by jorisvandenbossche** [comment]
Some additional thoughts on what @brendan-ward already mentioned:

- For geopandas, one of the problems with shapely's STRtree is indeed that it returns objects and not indices. That could be solved they way you solved, but that is also one of the reasons that right now we use `rtree` for spatial indexing (it also has some different performance characteristics, I think). But with the pygeos STRtree mentioned, this also returns indices, making it easier to integerate in geopandas.
- Note that we already use spatial indexing in geopandas, eg in spatial join, overlay, and the upcoming clip function. But there is a *lot* of room for improvement here, as there are many places where we also could use spatial indexing where we don't do it yet, such as in basic `intersects(..)` functions.

**Comment by brendan-ward** [comment]
@alessioarena in case it is useful for you, [here](https://github.com/astutespruce/sarp-connectivity/blob/master/analysis/prep/barriers/lib/points.py#L203) is a crude "neighborhood" analysis function that I think does roughly what you are trying to do here.

It creates a tree based on points, creates windows of defined size around my points (faster than buffers for purpose of querying tree), drops self-intersections, then uses `networkx` to build a network graph of the adjacent points that are within a certain distance of each other.  E.g., A is near B, B is near C, so A,B,C are in a "neighborhood".   (Note: A and C might be 2x tolerance distance from each other, in this example)

Note: I'm using `pygeos` for this implementation because I needed it to be faster.  You'd need to adapt it to `geopandas` but hopefully the functions seem similar enough in intent.  Feel free to DM me if not.

Certainly open to generalizing it further if it seems like a good fit for `geopandas`; just didn't have time on that project to pursue it at the time.

**Comment by alessioarena** [comment]
Thanks for that, it seems that is doing what I am after and I'll give it a try.
At the moment I wrote a code that does that operation using `STRtree` + `intersects` working its way through a `Queue` of indexes to test.
I basically need a solution that can be parallelized as I am dealing with very large datasets with 1+ million polygons with very complex shapes and heterogeneous size distribution.
This is why I'm trying to do it through a queue.

I still haven't look at the `sjoin` approach. I will also test that and see which one scales better with dataset size.

I agree with @jorisvandenbossche regarding a more extensive use of spatial indexing, but this is more of a generic comment rather than specific issue or suggestion (therefore I'll close this issue).
