### ISSUE TITLE
control on custom rounding for decimal values in plot_dataframe

### ISSUE THREAD

**Issue by mattijn** [geopandas/geopandas#1281]
In a choropleth map based on a geodataframe we are adding a legend as was raised in this SO [question](https://stackoverflow.com/questions/31755886/choropleth-map-from-geopandas-geodatafame). Result looks like this:
![image](https://user-images.githubusercontent.com/5186265/73940335-9145b300-48eb-11ea-9272-522740e065c0.png)

Since we are using custom user defined bins it would be logical to also have the binedges in the legend correspond to the number of decimals in the custom bins.

I cannot find any method to control this legend settings. I found the following hardcoded line ([source](https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L585:587)) in the geopandas github page:
```
categories = [
    "{0:.2f} - {1:.2f}".format(binedges[i], binedges[i + 1])
    for i in range(len(binedges) - 1)
]
```
Which seems to confirm that this is currently not controllable?

**Comment by martinfleis** [comment]
Formatting is being allowed in #1253 using `fmt` in `legend_kwds`. You'll be able to do that in the next release (0.7.0). Now, if you want more decimals, you'll have to make a legend manually I am afraid.
