### ISSUE TITLE
DOC: explain ValueError on tuple when invoking to_file()

### ISSUE THREAD

**Issue by vovchykbratyk** [geopandas/geopandas#1286]
Using geopandas 0.6.3, fiona 1.8.13

I have a simple geodataframe containing point data with 3 columns:

'City Name' (str)
'Coordinates' (tuple)
'geometry' (tuple)

When I try to write it out to a geopackage:

```
op = os.path.join(output_dir, output_file)
geo_df.to_file(op, layer='newlayer', driver='GPKG', encoding='utf8')
```
fiona throws a ValueError:
```
Traceback (most recent call last):
  File "C:\anaconda3\envs\newenv\lib\site-packages\geopandas\io\file.py", line 130, in to_file
    colxn.writerecords(df.iterfeatures())
  File "C:\anaconda3\envs\newenv\lib\site-packages\fiona\collection.py", line 342, in writerecords
    self.session.writerecs(records, self)
  File "fiona/ogrext.pyx", line 1195, in fiona.ogrext.WritingSession.writerecs
  File "fiona/ogrext.pyx", line 412, in fiona.ogrext.OGRFeatureBuilder.build
ValueError: Invalid field type <class 'tuple'>
```
This is confusing because the [geopandas documentation](http://geopandas.org/io.html#writing-spatial-data) states:

Writing to GeoPackage:
```
countries_gdf.to_file("package.gpkg", layer='countries', driver="GPKG")
cities_gdf.to_file("package.gpkg", layer='cities', driver="GPKG")
```

**Comment by martinfleis** [comment]
As ValueError states, tuple is not supported by GPKG. You have to convert tuple objects to something else, like strings or split it to multiple columns and save it as floats/integers.

**Comment by vovchykbratyk** [comment]
In that case, the documentation is incorrect and should be changed to show the correct way to output a gdf to a gpkg layer.

**Comment by martinfleis** [comment]
I disagree. Documentation shows the correct way how to save gdf to GKPK. Your data are not standard and are not supported by GPKG driver. It would not work for lists or plenty other objects either. We cannot cover every option in the documentation. 

I agree that we might add a sentence mentioning that different drivers support different field types and that user needs to manually convert unsupported objects to supported, but that does not make the existing documentation incorrect. This is a limitation of GPKG driver (and many other) not of GeoPandas.

**Comment by vovchykbratyk** [comment]
Understand, that makes sense.  I’ll examine the various standard gdfs (point/line/poly) and see if I can recast the dataframe earlier in the process.
