### ISSUE TITLE
HTTPS website

### ISSUE THREAD

**Issue by jayvdb** [geopandas/geopandas#1287]
Hi, I noticed that https://geopandas.org/ shows "Warning: Potential Security Risk Ahead" in Firefox because it has a wrong certificate for that domain.

https://help.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https may be of help to resolve this.

**Comment by jorisvandenbossche** [comment]
@jayvdb Thanks for letting us know!

Apparently it is not as simple as checking the box in the settings, as it is the custom domain that needs fixing. Will look into that.

**Comment by jorisvandenbossche** [comment]
This should be solved now: https://geopandas.org/
