### ISSUE TITLE
Spatial join throwing exception when GeoDataFrame has tuple column names

### ISSUE THREAD

**Issue by borao** [geopandas/geopandas#1291]
The data frame has its column names in tuple form. Doing a spatial join with another data frame not of this same form returns `ValueError: Length of names must match number of levels in MultiIndex`.

<class 'geopandas.geodataframe.GeoDataFrame'>
Int64Index: 3552 entries, 0 to 9991
Data columns (total 12 columns):
(start_polygon_id, )     3552 non-null int64
(end_polygon_id, )       3552 non-null int64
(start_x, )              3552 non-null float64
(start_y, )              3552 non-null float64
(end_x, )                3552 non-null float64
(end_y, )                3552 non-null float64
(metric_value, mean)     3552 non-null float64
(metric_value, sum)      3552 non-null float64
(metric_value, count)    3552 non-null int64

**Comment by martinfleis** [comment]
Hi, can you provide some minimal reproducible example?

**Comment by borao** [comment]
Hello, if you try to intersect a GeoDataFrame with a MultiIndex and one without a MultiIndex using `sjoin`, the error will be reproduced.

**Comment by martinfleis** [comment]
Issue with MultiIndex has been fixed in #1159 and will be part of the next release in a couple of days. But you were initially writing about column names, not rows. Is there an issue with columns as well or not?

**Comment by borao** [comment]
Sorry, I was unclear. The column names are tuples and this is causing a problem when merging with another `gdf` which has string column names. See the output of `gdf.info()` above. Merging this with a 'normal' `gdf` with typical string names caused problems.

The term MultiIndex is irrelevant here. My bad.

**Comment by martinfleis** [comment]
I am not able to reproduce the issue, everything works if I set a tuple as a column name. If you could provide reproducible example which fails, that would be helpful.

**Comment by borao** [comment]
The issue resolved itself when I updated GeoPandas. Thank you for your support.
