### ISSUE TITLE
make rectangular bar for legend in geopandas

### ISSUE THREAD

**Issue by shuai-zhou** [geopandas/geopandas#1293]
I am not sure if this is a request for geopandas or matplotlib, and I am sorry for posting it again here, but my previous post [here](https://stackoverflow.com/questions/60023670/how-to-make-rectangular-bar-for-legend-in-geopandas) did not get any response.

By default, the legends in Geopandas are small circles. Sometimes the legend is small and the circles in the legend are even smaller. For some color schemes, it is hard to see the small circles of the first quantile. I was wondering how to replace the small circles with customizable rectangular bars to make them more visible. Thanks.

How to replace the round dots in the legend with rectangular bars in the example:

`%matplotlib inline`
`import geopandas as gpd`
`world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))`
`world.plot(column='pop_est', scheme='quantiles', legend=True, legend_kwds={'loc': 'center left'}, figsize=(15,12))`

![image](https://user-images.githubusercontent.com/22311821/74401899-ab522a80-4df0-11ea-9bbf-c73036c6445b.png)

**Comment by martinfleis** [comment]
Hi, 
at this moment GeoPandas itself does not support anything else than circle. It is hard-coded. To have a custom-looking legend, you have to generate it manually. We know about it. See #735 for a discussion and one of the solutions.

I'll close this as a duplicate. We can have a further discussion about it in #735.
