### ISSUE TITLE
GeoDataFrame as generator

### ISSUE THREAD

**Issue by butlnor** [geopandas/geopandas#1294]
As far as I am using GeoDataFrame, it loads and returns the whole data in memory. I have debugged it, and I don't see it using a generator principle (with "yield" keyword). This means this is unusable for really large datasets. 
Can GeoDataFrame be rewritten to behave as a generator, to optimize the loading performance?

**Comment by jorisvandenbossche** [comment]
Pandas (and thus GeoPandas) dataframes are fully in memory data objects, that's a limitation of this project. For large datasets / out-of-core / lazy dataframes, there are several options. Dask is probably the most known one (and there is currently some work on getting geopandas to run with dask, see https://github.com/dask/dask/issues/5438. 
Another option could be ibis (https://docs.ibis-project.org/), with your data in a database (eg postgis).

**Comment by ian-r-rose** [comment]
A bit of info on the `ibis` approach here: #1164
