### ISSUE TITLE
legend's labels for binned plots

### ISSUE THREAD

**Issue by SylvainLan** [geopandas/geopandas#1301]
Hello, 

I'm trying to plot a geodataframe and change the label assigned to the different binned colors in the legend. Here's an example : 

```
import geopandas as gpd
import matplotlib.pyplot as plt

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

fig, ax = plt.subplots(figsize=(12, 10))
world.plot(column='pop_est', scheme='quantiles', legend=True, ax=ax)
```

We get the same map as in the documentation but I want to change the labels of the legend to be, e.g., `['very low', 'low', 'average', 'high', 'very high']`. 

I guess it's not directly possible for the legend categories are created automatically ([see here](https://github.com/geopandas/geopandas/blob/0a1799d986861e55c26e38b6273bfb70012c7d1e/geopandas/plotting.py#L585)) but would'nt it be possible for the user to set it manually ?

 I guess it would have to check that there is a match of length between the number of bins and the number of labels and other checks... 

If this sounds doable / interesting I could try to work on it

**Comment by martinfleis** [comment]
Hi, that is indeed to possible at the moment. You can make mapclassify bins manually beforehand and then use them as categorical values, but that is not ideal (for many reasons).

It should not be complicated to add `labels` as a supported keyword to `legend_kwds`. Then you would either place mapping dict or just a simple list in order. If you want to try a PR, feel free to do so.

**Comment by gcaria** [comment]
I was looking for an easy issue to work on, but it looks like this one is already fixed and needs to be closed.

**Comment by martinfleis** [comment]
Thanks @gcaria!
