### ISSUE TITLE
DOC: missing changelog in documentation

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1305]
Our changelog is available only as a .md file in the root folder. It should be part of the documentation online as well as @StevenLi-DS correctly pointed out in https://github.com/geopandas/geopandas/issues/1076#issuecomment-590126250.

**Comment by Sangarshanan** [comment]
Can I pick this up?

**Comment by martinfleis** [comment]
Feel free to do so. If you find a way hot to get it automatically from CHANGELOG.md that would be ideal.
