### ISSUE TITLE
to_crs gives error 'CRS' object has no attribute 'is_exact_same'

### ISSUE THREAD

**Issue by harmbuisman** [geopandas/geopandas#1311]
Ignore below, for some reason my environment uses the pyproj version not in my conda environment, but the one in a different location. If anyone reads this and knows how to tackle this I would be interested to hear. For now this issue is not with geopandas.

_________________________
I get an error when trying to run to_crs on a geopandas dataframe.

Repro file provided here:
[provinces.zip](https://github.com/geopandas/geopandas/files/4256510/provinces.zip)

Repro:
---------------------------------------------------------------------------

import geopandas as gpd
gdf = gpd.read_file('provinces.geojson')
gdf.to_crs(epsg='3857')

Error message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-34c2bf268cf5> in <module>
      1 import geopandas as gpd
      2 gdf = gpd.read_file('provinces.geojson')
----> 3 gdf.to_crs(epsg='3857')

~\.conda\envs\cs\lib\site-packages\geopandas\geodataframe.py in to_crs(self, crs, epsg, inplace)
    562         else:
    563             df = self.copy()
--> 564         geom = df.geometry.to_crs(crs=crs, epsg=epsg)
    565         df.geometry = geom
    566         df.crs = geom.crs

~\.conda\envs\cs\lib\site-packages\geopandas\geoseries.py in to_crs(self, crs, epsg)
    431 
    432         # skip if the input CRS and output CRS are the exact same
--> 433         if self.crs.is_exact_same(crs):
    434             return self
    435 

AttributeError: 'CRS' object has no attribute 'is_exact_same'

SYSTEM INFO
-----------
python     : 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 21:48:41) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\XXX\.conda\envs\cs\python.exe
machine    : Windows-10-10.0.18362-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.0.4
GDAL data dir: None
PROJ       : 6.0.0
PROJ data dir: C:\Users\XXX\AppData\Roaming\Python\Python37\site-packages\pyproj\proj_dir\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.7.0
pandas     : 1.0.1
fiona      : 1.8.13
numpy      : 1.18.1
shapely    : 1.7.0
rtree      : 0.9.4
pyproj     : 2.1.0
matplotlib : 3.1.3
mapclassify: None
pysal      : None
geopy      : None
psycopg2   : None

However, strange enough pyproj reports a different version in my conda environment:
![image](https://user-images.githubusercontent.com/7702207/75359661-fcfcb980-58b4-11ea-9788-6360994f4731.png)

**Comment by martinfleis** [comment]
This seems like an issue with your environment and especially pyproj as you mention. GeoPandas require pyproj 2.2.0 or newer, the one which is used is 2.1.0. I would not say that this is the issue GeoPandas caused or we can fix on our side. Have tried setting up a new environment?

**Comment by harmbuisman** [comment]
> This seems like an issue with your environment and especially pyproj as you mention. GeoPandas require pyproj 2.2.0 or newer, the one which is used is 2.1.0. I would not say that this is the issue GeoPandas caused or we can fix on our side. Have tried setting up a new environment?
> 
> Edit: How did you install geopandas?
> 
> Edit2: See related issue [conda-forge/geopandas-feedstock#75](https://github.com/conda-forge/geopandas-feedstock/pull/75) .

@martinfleis , thanks for your reply. Indeed it is the pyproj version. I installed it in the right way and in the conda environment it shows that I have 2.5.0 installed, but somehow that version is not used. Python decides to use another version:
![image](https://user-images.githubusercontent.com/7702207/75363232-1c4a1580-58ba-11ea-9293-c2df93eb1f22.png)
so I need to find out how that works. If you have an idea, I would be happy to hear
