### ISSUE TITLE
Geopandas "within" problems - Question

### ISSUE THREAD

**Issue by zedpatterson** [geopandas/geopandas#1316]
I'm teaching a course on programming with geospatial technologies. (GEOG 464 Concordia University). I'm looking closely at geopandas. I'm having some trouble with the spatial relationship operations. In particular, I'm having trouble getting the "within" method to work for creating subsets of geographical data, as I understand it to be able to work based on  geopandas-tutorial/03-spatial-relationships-operations.ipynb. 

 I'll illustrate the problem with the natural earth data. I'm working in colab.

`countries = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))`
`na = countries[countries['continent']=='North America']`
`cities = geopandas.read_file(geopandas.datasets.get_path('naturalearth_cities'))`
`na_cities = cities[cities.within(na)]`
`na_cities.head()`

![emptyWithinResult](https://user-images.githubusercontent.com/14890938/76086667-8b8ecc00-5f82-11ea-8550-96336eeba551.png)

I get an empty result. I've tried with different data sets including the velib and quartier datasets described in  geopandas-tutorial/04-spatial-joins.ipynb

I just can't seem to get it to work. I wonder whether I'm doing something wrong or whether this is a (known) bug?

**Comment by martinfleis** [comment]
Within, similarly to intersects and similar operations (xref #972), when done as `gdf.within(gdf2)` works in pair-wise manner. We aim to change it in the future (probably) as it is not very friendly behaviour. Now you need to either loop through the other df or check agains single geometry, fo example using `unary_union`. 

In your example, you would get the intended result using `cities[cities.within(na.unary_union)]` or using apply: `cities.apply(lambda x: na.intersects(x.geometry).any(), axis="columns") `. If you have large gdf, you can use loop with spatial indexing.

I'll close the issue as it is essentially the same one as #972.

**Comment by zedpatterson** [comment]
Good stuff. Thanks.
