### ISSUE TITLE
Make `GeoDataFrame._to_geo` "public"

### ISSUE THREAD

**Issue by kuraga** [geopandas/geopandas#1320]
Currently `GeoDataFrame.to_json` uses `GeoDataFrame._to_geo` to get JSON (string) representation of GeoDataFrame.

But `GeoDataFrame._to_geo` is 'private" (prefixed). So we can get string representation of GeoDataFrame but not dictionary.

Proposition: make `GeoDataFrame._to_geo` "public".

**Comment by martinfleis** [comment]
What would be the use case of that? I am just curious, I have nothing against it. Feel free to make a PR.

**Comment by kuraga** [comment]
@martinfleis ,

Well [Plotly's Choropleth Mapbox](https://plotly.github.io/plotly.py-docs/generated/plotly.express.choropleth_mapbox.html) gives result of `GeoDataFrame._to_geo()` not unJSONed result of `GeoDataFrame.to_file(..., driver='GeoJSON')` (that's strange, I know, but it wants to have `id` one level up).

I'm also curious why we publish string representation and hide original dictionary :)

BTW, what' original of `GeoDataFrame.to_file(..., driver='GeoJSON')`?

And am I correct that JSON != GeoJSON?

Thanks.

**Comment by martinfleis** [comment]
> I'm also curious why we publish string representation and hide original dictionary :)

No one probably thought about it before :).

> what' original of GeoDataFrame.to_file(..., driver='GeoJSON')?

GeoJSON in this case is generated by Fiona based on `df.iterfeatures()`.

> And am I correct that JSON != GeoJSON?

Yes. If you compare result of `to_file` and `to_json`, you can notice that JSON does not include CRS definition - `"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },`. Not sure if there are any other differences between these two, but you certainly want to preserve CRS.

**Comment by kuraga** [comment]
> Not sure if there are any other differences between these two, but you certainly want to preserve CRS.

They are, one of them I pointed above: GeoJSON puts `id` property inside `properties` dictionary but `to_json` puts it beside `properties`.

**Comment by martinfleis** [comment]
`GeoDataFrame.__geo_interface__` is a public API for `_to_geo` that returns the original dictionary.

**Comment by aspyk** [comment]
I was testing some performance capabilities of different export methods of `GeoDataFrame` and I've just seen that `_to_geo` was in my test case 20% faster than `__geo_interface__`. The difference seems to come from the arg `show_bbox` set to `True` in `__geo_interface__`. Could it be a reason to reopen this issue ? Thanks !

(my use case was to try to export geoson using the [geobuf](https://github.com/pygeobuf/pygeobuf) lib that needs geoson as dict format)

**Comment by aspyk** [comment]
Thanks a lot! Indeed, I also tried the workaround you indicate and ended up creating a new function in my own code :) 

Do you want me to have a look at this and open a PR ?

**Comment by jorisvandenbossche** [comment]
Another option could be to partially re-use pandas' `to_dict()` method? (to avoid adding a new method, although that's of course also less discoverable). `to_dict` has an `orient` keyword that determines the layout of the resulting dict, we could add a "geojson" option for that.

**Comment by martinfleis** [comment]
@jorisvandenbossche I was thinking about that but would personally prefer a separate method since GeoJSON serialisation of geometries is not compatible with other `orient` options and it feels weird that you get shapely objects in all but one case.

**Comment by aspyk** [comment]
> That would be great! I think you can just rename `_to_geo`, change its name in other places and add it to API documentation. I _think_ it should be tested but we should double check that.

Ok I'm going for it!

The `orient` option does indeed sound interesting but I don't know enough about it to contribute to the discussion. I'll start with the first option by default but let me know if there are any changes :)

**Comment by aspyk** [comment]
The PR is open here: https://github.com/geopandas/geopandas/pull/3132
Feel free to give me any feedback or modify it, it's my first contribution here :)

Concerning the tests, `_to_geo` already has some so I didn't change anything for now (apart from the name).
