### ISSUE TITLE
`GeoDataFrame.simplify` returns `GeoDataSeries`

### ISSUE THREAD

**Issue by kuraga** [geopandas/geopandas#1321]
`GeoDataFrame.simplify` returns `GeoDataSeries` but `GeoDataFrame` is expected.

**Comment by martinfleis** [comment]
Geometric methods like `simplify` or `buffer` in GeoPandas work on GeoSeries and return GeoSeries. If you want to update GeoDataFrame geometry with changed one, you have to do `gdf.geometry = gdf.simplify(tolerance)`.

Changing this behaviour to automatically update geometry column would be a huge breaking change. Moreover, I believe that it is designed like this for a safety reason. If you want to alter your geometry, you have to reassign them manually, knowing what are you doing.

**Comment by kuraga** [comment]
Well `gdf = gdf.simplify(tolerance)` allowed but not safety.

Ok, thanks! Closing.
