### ISSUE TITLE
Making a bivariate choropleth map using `gdf.show`

### ISSUE THREAD

**Issue by osheanlee** [geopandas/geopandas#1322]
Would it be possible for geopandas to have a feature of making a **bivariate choropleth map** quicker using few lines of code, similar to making a univariate choropleth map?

**Comment by martinfleis** [comment]
I would say that bivariate plots might be out of scope of core geopandas package. `splot` can do Value-by-Alpha bivariate plot (https://nbviewer.jupyter.org/github/pysal/splot/blob/master/notebooks/mapping_vba.ipynb) and I would like to see further development to happen there.

**Comment by osheanlee** [comment]
Oh cool! Thanks @martinfleis!
