### ISSUE TITLE
Saved IntegerArray is not read as IntegerArray

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1325]
Pandas added one check (https://github.com/pandas-dev/pandas/pull/32570)  to `assert_series_equal` which made our CI red. It catches the fact that if we save IntegerArray to file and then read it back, it comes as array of floats. Not sure if that is something we can or should try to fix, so maybe better to change tests in this particular case.

```py
df = pd.DataFrame({'Name':['Adam','Barbara','Cat','Doug','Ezra','Fiona','Greg'],
                  'lat':[35.5,35.2,34.89,36.1,35.78,35.76,34.99],
                  'lon':[-112.02,-111.09,-115.3,-114.01,-113.02,-112.9,-112.02]})
gdf = gpd.GeoDataFrame(df, geometry = [Point(x,y) for x, y in zip(df.lon,df.lat)])

gdf["data"] = pd.array([1, np.nan, 1, np.nan, 1, np.nan, 1], dtype=pd.Int64Dtype())
gdf.data.values
```

```
<IntegerArray>
[1, NaN, 1, NaN, 1, NaN, 1]
Length: 7, dtype: Int64
```

```py
gdf.to_file('testint.shp')
gdf_read = gpd.read_file('testint.shp')

gdf_read.data.values
```

```
array([ 1., nan,  1., nan,  1., nan,  1.])
```

**Comment by Sangarshanan** [comment]
It's the same with pandas read too, should the tests be changed ? 
```
>>> df = pd.DataFrame({'Name':['Adam','Barbara','Cat','Doug','Ezra','Fiona','Greg'],
                  'lat':[35.5,35.2,34.89,36.1,35.78,35.76,34.99],
                  'lon':[-112.02,-111.09,-115.3,-114.01,-113.02,-112.9,-112.02]})
>>> df['data'] =  pd.array([1, np.nan, 1, np.nan, 1, np.nan, 1], dtype=pd.Int64Dtype())
>>> df.to_csv('testint.csv', index=False)
>>> data_test = pd.read_csv('testint.csv')
>>> data_test.data.values
array([ 1., nan,  1., nan,  1., nan,  1.])
```

**Comment by martinfleis** [comment]
Sure it is, csv, shp and other filetypes do not support IntegerArray, so pandas does not know how to load them and fall back to array of floats. 

> should the tests be changed ?

Yes.

**Comment by jorisvandenbossche** [comment]
Personally, I think this is a regression in pandas that should be fixed. We specified `check_dtypes=False`, in which case it should not check that it is an extension dtype or not

**Comment by jorisvandenbossche** [comment]
I opened an issue about it here: https://github.com/pandas-dev/pandas/issues/32747

**Comment by jorisvandenbossche** [comment]
The pandas issue is fixed, so I think this can be closed
