### ISSUE TITLE
Geopandas raises UserWarning after loading osm shapes

### ISSUE THREAD

**Issue by TiRoX** [geopandas/geopandas#1331]
Hello dear GeoPandas-devs,

When loading the OpenStreetMap shapes (eg: https://download.geofabrik.de/europe/germany.html - I used the shape for Berlin: https://download.geofabrik.de/europe/germany/berlin-latest-free.shp.zip) with read_file it raises the following:

```
venv/lib/python3.6/site-packages/geopandas/array.py:575: UserWarning: Only Polygon objects have interior rings. For other geometry types, None is returned.
  "Only Polygon objects have interior rings. For other "

venv/lib/python3.6/site-packages/geopandas/base.py:104: UserWarning: Cannot generate spatial index: Missing package `rtree`.
  warn("Cannot generate spatial index: Missing package `rtree`.")
```

When my IDE looks for code completion suggestions, my python goes for 100% CPU and starts to raise this Warnings again and repeatedly - simultaniously the IDE also tries to read all variables inside the read_file-variable.

IDE:
PyCharm CE newest version

System-Info:
'3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'
Mac OS X 10.14.6

Package-Info:
Name: geopandas
Version: 0.7.0
Summary: Geographic pandas extensions
Home-page: http://geopandas.org
Author: GeoPandas contributors
Author-email: kjordahl@alum.mit.edu
License: BSD
Location: /venv/lib/python3.6/site-packages
Requires: pyproj, shapely, fiona, pandas

venv packages: https://pastebin.com/3FfK1Nrs
code: https://pastebin.com/L0BxMdAr

I am missing gdal & rtree dependencies.

Best regards

**Comment by martinfleis** [comment]
Thank you for the report.

> I am missing gdal

That is likely the cause as Fiona which is used to read Shapefiles is dependent on GDAL to read it.

I am not able to reproduce the issue. I don't know what actually happens under the hood from the error message. Can you share full traceback?

It is likely issue with your installation, so I would recommend making sure that all dependencies are [correctly installed](https://geopandas.readthedocs.io/en/latest/install.html).

**Comment by TiRoX** [comment]
Sorry, can you please share how to get the full traceback for warnings in this example?

**Comment by martinfleis** [comment]
Oh, sorry. It is a warning, not error. There's no traceback :).

**Comment by TiRoX** [comment]
I added the second error message, as well as the current packages installed in venv and the short code snippets in pastebin. I hope this will help to reproduce the error. Obviously not all packages in venv should be installed - but you will certainly understand what is missing.

I think the goal should be to try to suppress the reloading process such that the warning is not raised multiple times.

As of installing further dependencies - some devs (like me) don't have the luxury to be able to install frameworks like gdal or psycopg2 on their own due to privilege. :P

**Comment by jorisvandenbossche** [comment]
I don't see any warning if I read that file. 

Can you show the output of running `geopandas.show_versions()` ? 
Can you also show the full input + output of the code you ran and the output you got?

**Comment by TiRoX** [comment]
Sure. Here are the logs: 

https://pastebin.com/ETg1mE0B

**Comment by jorisvandenbossche** [comment]
Thanks. So from your log, it seems that the warning is raised by `df.head()`, not by reading the file? But it's strange that getting the first few rows of the dataframe actually checks the `interiors` property, I can't think directly of a reason where in geopandas that would happen.

**Comment by TiRoX** [comment]
> Thanks. So from your log, it seems that the warning is raised by `df.head()`, not by reading the file? But it's strange that getting the first few rows of the dataframe actually checks the `interiors` property, I can't think directly of a reason where in geopandas that would happen.

You are right. It doesn't. My IDE must have checked the interiors for some reason. I tried it with a factory new installation without any plugins or additional settings, which stops the repeatedly raised warnings. However, if I want to check the interiors, they are raised again.

**Comment by jorisvandenbossche** [comment]
Ah, yes, I suppose there is some inspection of the properties (eg for tab-completion) from your IDE that triggers the properties to be executed. 
(it's a similar problem that occurred before in IPython as well witht the jedi library that provides the tab completion. It's not ideal that GeoDataFrame has properties that are expensive to compute, but that's hard to change right now)

**Comment by TiRoX** [comment]
> Ah, yes, I suppose there is some inspection of the properties (eg for tab-completion) from your IDE that triggers the properties to be executed.
> (it's a similar problem that occurred before in IPython as well witht the jedi library that provides the tab completion. It's not ideal that GeoDataFrame has properties that are expensive to compute, but that's hard to change right now)

For some variables I already see tracebacks like _constructor_expanddim or is_ring - wouldn't it be optimal to convert these variables to string as well with the occurred warning messages in order to stop the reevaluation by IDE after a command?
