### ISSUE TITLE
Pysal has no explore attribute

### ISSUE THREAD

**Issue by giandrickdabian** [geopandas/geopandas#1333]
I keep getting this error when trying to enter this code:

AttributeError                            Traceback (most recent call last)
<ipython-input-189-6b7dac0e38a0> in <module>
      1 #Global autocorrelation
      2 
----> 3 I_neigh_virus= pysal.explore.esda.moran.Moran(spatial['Normalized'].values, qw)
      4 print('Global Autocorrelation of Virus X:', I_neigh_virus.I, I_neigh_virus.p_sim)

AttributeError: module 'pysal' has no attribute 'explore'

**Comment by ljwolf** [comment]
hi, this is an issue with PySAL, not Geopandas. You need to upgrade your pysal version to something above 2.0.
