### ISSUE TITLE
How to generate contourline?

### ISSUE THREAD

**Issue by ziliangok** [geopandas/geopandas#1346]
In gdal, we can use ContourGenerate function to generate it. But hot can I do this in geopandas?

**Comment by martinfleis** [comment]
@ziliangok I believe you are referring to extraction of contour lines from a raster data. GeoPandas does not support rasters, for that you need [rasterio](https://rasterio.readthedocs.io) or other packages. Also, I would recommend asking questions like this one on https://stackoverflow.com, https://gis.stackexchange.com or Gitter (https://gitter.im/geopandas/geopandas). GitHub issues should be used for bug reports and development-focused discussion.
