### ISSUE TITLE
ENH: implement set_crs()

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1352]
Implement explicit `set_crs()` method to overwrite CRS of GeometryArrays once we have #1339. Should be consistent with `to_crs()`. It should work as `GeoSeries.crs = 4326`, but having it explicit will help consistency. Also, because we now transform passed CRS value into pyproj.CRS, setting it directly to attribute might be confusing (I set a number, but I do not get a number back).

`set_crs()` should be preferred way of assigning CRS to GeometryArray without one. Note that warnings in `GeoSeries.__new__` and `GeoDataFrame.__init__` should reflect the change.

xref #747

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/geopandas/geopandas/pull/747
