### ISSUE TITLE
ValueError: Unknown geometry type: featurecollection upon upgrade to 0.7

### ISSUE THREAD

**Issue by tarmangue** [geopandas/geopandas#1353]
I was using geopandas 0.5.1 and upgraded to 0.7 to be able to use missing_kwds, but upon doing that, a part of the code that was working fine stopped working:

```python
mrgd = pd.concat([mrgd,df_missing])
```

This is the line giving me an error, which is:

```
ValueError: Unknown geometry type: featurecollection
```

**Comment by martinfleis** [comment]
Thanks for the report! Can you provide a bit more information so we can debug the issue? Ideal would be minimal reproducible example, full traceback and copy&paste of `geopandas.show_versions()`.

**Comment by BradyHu** [comment]
![image](https://user-images.githubusercontent.com/19490397/82003066-03b7f300-9692-11ea-8e6d-4bdd49b195ff.png)
![image](https://user-images.githubusercontent.com/19490397/82003093-10d4e200-9692-11ea-84ef-88b0f4d71776.png)
emm, will this can help you? I met the same problem....

**Comment by martinfleis** [comment]
@BradyHu not much. It seems that there is `featurecollection` somewhere in your geometry column. GeoPandas now requires all values in `geometry` to be either shapely.geometry or missing. How did you generated `tmp`?

**Comment by JoyMonteiro** [comment]
I faced the same problem. What I was doing wrong was assigning geometry from another geodataframe incorrectly. I was
doing something like this

```
def get_geometry(location):
     return a[a['Location'] == location].geometry

b.geometry = b['Locations'].map(get_geometry)
```
what worked for me was

```
def get_geometry(location):
     return a[a['Location'] == location].geometry.values[0]

b.geometry = b['Locations'].map(get_geometry)
```

**Comment by MohammadForouhesh** [comment]
That's right, most of the time the error is caused by GeoPandas strict rules for data types.

**Comment by MikePia** [comment]
Had the same issue. 

```
poly = gpd.GeoSeries(MultiPolygon([Polygon(x[0]) for x in coords]))
self.gdf = gpd.GeoDataFrame(index=[0], crs='epsg:4326', geometry=[poly])
```
That generated the error. And it can be avoided by using instead:
`self.gdf = gpd.GeoDataFrame(index=[0], crs='epsg:4326', geometry=[poly.geometry.values[0]])`
It seems if geopandas generates the geometry, it ought to be able to use it to create an object
