### ISSUE TITLE
clip: return warning or error if inputs have different projections

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1354]
`0.7.0`

The `.clip()` function returns an empty GeoDataFrame if the input GeoDataFrames have different projections. I would say it might be better to raise a warning or exception to warn users.

```python
import geopandas as gpd

gdf_nyc = gpd.read_file(gpd.datasets.get_path('nybb'))
gdf_world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

gdf = gpd.clip(gdf_world, gdf_nyc)
print(len(gdf)) # returns 0

gdf_nyc = gdf_nyc.to_crs(gdf_world.crs)

gdf = gpd.clip(gdf_world, gdf_nyc)
print(len(gdf)) # returns 1
```

I believe this is worth mentioning in the doc as well

**Comment by jorisvandenbossche** [comment]
Yes, now we have a more robust CRS system, a warning would be good to add.
