### ISSUE TITLE
DOC: Missing geopandas.Series overlaps method in documentation

### ISSUE THREAD

**Issue by alephcero** [geopandas/geopandas#1358]
[Documentation]( https://geopandas.org/reference.html) for `geopandas.Series.overlaps()` is missing in `v0.7.0`

**Comment by martinfleis** [comment]
Thanks for the notice. Feel free to open a PR adding it.

**Comment by raphacosta27** [comment]
Hi there, is this still open? May I go for it?

**Comment by martinfleis** [comment]
@raphacosta27 Yes, it is still missing in Reference guide. Thanks!

**Comment by martinfleis** [comment]
Closed by #1423
