### ISSUE TITLE
Tests failing with PROJ 7

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1360]
Tests are failing on conda-forge builds with PROJ7 (https://travis-ci.org/github/geopandas/geopandas/builds/672966994). 

Something has changed in usage of proj4 string and proj4 dict (deprecation?).

**Comment by jorisvandenbossche** [comment]
So an example that fails is the roundtrip of "+proj=utm +zone=18 +ellps=GRS80 +datum=NAD83 +units=m +no_defs " of EPSG:4326 and back (there is a difference in decimal points).

I didn't test, but I think the following example would fail with PROJ 7 (based on the logs):

```
import pyproj 

crs1 = pyproj.CRS("+proj=utm +zone=18 +ellps=GRS80 +datum=NAD83 +units=m +no_defs ") 
crs2 = pyproj.CRS("EPSG:4326")
trans = pyproj.Transformer.from_crs(crs1, crs2, always_xy=True) 
trans_inv = pyproj.Transformer.from_crs(crs2, crs1, always_xy=True)   

# this is for PROJ 6, according to the travis logs this gives now -1683723.248 6689138.821
>>> trans_inv.transform(*trans.transform(-1683723.000, 6689139.000))                                                                                                                                             
(-1683723.0000000005, 6689139.0)
```


cc @snowman2 are you aware of something that changed in PROJ that could be related to this?

**Comment by snowman2** [comment]
The difference i think is due to PROJ RFC 4 (https://proj.org/community/rfc/rfc-4.html).

conda has the environment variable `PROJ_NETWORK=ON` which will download the datumgrids for you automatically. It is likely in the tests that you didn't have the proper datumgrids installed previously to ensure the best transformation and now it is doing it for you.

Related:
- https://github.com/pyproj4/pyproj/pull/594
- https://github.com/pyproj4/pyproj/issues/530

**Comment by jorisvandenbossche** [comment]
Naive question: shouldn't the "best transformation" still give a faithfull roundtrip?

**Comment by snowman2** [comment]
> Naive question: shouldn't the "best transformation" still give a faithfull roundtrip?

Ahh, I see. I am not entirely sure. I would ask one of the PROJ devs to see what they have to say.

**Comment by snowman2** [comment]
I tested it out with PROJ 7 with all of the datum grids and with PROJ_NETWORK=ON and it seems to provide the correct results:
```
>>> import pyproj 
>>> 
>>> crs1 = pyproj.CRS("+proj=utm +zone=18 +ellps=GRS80 +datum=NAD83 +units=m +no_defs ") 
>>> crs2 = pyproj.CRS("EPSG:4326")
>>> trans = pyproj.Transformer.from_crs(crs1, crs2, always_xy=True) 
>>> trans_inv = pyproj.Transformer.from_crs(crs2, crs1, always_xy=True)   
>>> trans_inv.transform(*trans.transform(-1683723.000, 6689139.000)) 
(-1683723.0000000005, 6689139.0)
>>> pyproj.show_versions()
pyproj info:
    pyproj: 2.6.0
      PROJ: 7.0.0
  data dir: /home/snowal/miniconda/envs/proj700/share/proj

System:
    python: 3.8.2 | packaged by conda-forge | (default, Mar  5 2020, 17:11:00)  [GCC 7.3.0]
executable: /home/snowal/miniconda/envs/proj700/bin/python
   machine: Linux-4.15.0-96-generic-x86_64-with-glibc2.10

Python deps:
       pip: 20.0.2
setuptools: 46.0.0.post20200310
    Cython: 0.29.15

```

**Comment by snowman2** [comment]
This looks suspect: `epsg4326 = {'epsg': 4326}`

**Comment by snowman2** [comment]
Nope that was fine.

**Comment by snowman2** [comment]
I did `unset PROJ_NETWORK` and it passed:
```
============================ test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/snowal/scripts/geopandas, inifile: setup.cfg
plugins: cov-2.8.1
collected 1039 items / 1014 deselected / 25 selected

geopandas/tests/test_crs.py .........................                    [100%]

=============================== warnings summary ===============================
geopandas/geoseries.py:118
  /home/snowal/scripts/geopandas/geopandas/geoseries.py:118: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
    s = pd.Series(data, index=index, name=name, **kwargs)

geopandas/tests/test_crs.py::test_transform2[epsg_number-epsg_dict]
geopandas/tests/test_crs.py::test_transform2[epsg_string-epsg_dict]
geopandas/tests/test_crs.py::test_transform2[epsg_dict-epsg_number]
geopandas/tests/test_crs.py::test_transform2[epsg_dict-epsg_string]
geopandas/tests/test_crs.py::test_transform2[epsg_dict-epsg_dict]
geopandas/tests/test_crs.py::test_transform2[epsg_dict-proj4_string]
geopandas/tests/test_crs.py::test_transform2[epsg_dict-proj4_dict]
geopandas/tests/test_crs.py::test_transform2[proj4_string-epsg_dict]
geopandas/tests/test_crs.py::test_transform2[proj4_dict-epsg_dict]
  /home/snowal/miniconda/envs/test/lib/python3.8/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
    return _prepare_from_string(" ".join(pjargs))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============== 25 passed, 1014 deselected, 10 warnings in 5.49s ===============
```

Strange ....

**Comment by snowman2** [comment]
If i do `conda install proj-data` and I `unset PROJ_NETWORK` it fails again.

**Comment by snowman2** [comment]
Possibly related: https://github.com/OSGeo/PROJ/issues/2143

**Comment by jorisvandenbossche** [comment]
So indeed, with just a plain `conda create -n test-proj7 pyproj ipython` fresh environment, this seems to work correctly for me:

```
In [1]: import pyproj  
   ...:  
   ...: crs1 = pyproj.CRS("+proj=utm +zone=18 +ellps=GRS80 +datum=NAD83 +units=m +no_defs ")  
   ...: crs2 = pyproj.CRS("EPSG:4326") 
   ...: trans = pyproj.Transformer.from_crs(crs1, crs2, always_xy=True)  
   ...: trans_inv = pyproj.Transformer.from_crs(crs2, crs1, always_xy=True)    
  
In [2]: trans_inv.transform(*trans.transform(-1683723.000, 6689139.000)) 
Out[2]: (-1683723.0000000005, 6689139.0)
```

and the first time it took a long time, so I suppose it was downloading something? 
I indeed found that there is a now a new file in .local/share/proj (cache.db), and if I remove that, it again takes a longer time on the first call. 

If I do `unset PROJ_NETWORK`, it also works fine.

When I turn off my internet connection, then I get `inf`:

```
In [2]: trans_inv.transform(*trans.transform(-1683723.000, 6689139.000))  
Out[2]: (inf, inf)
```

Which is similarly as what is being described at https://github.com/OSGeo/PROJ/issues/2143

But so I actually don't get what we see on Travis (coordinates off with 20 cm)

**Comment by jorisvandenbossche** [comment]
Now, for travis it might be fine to turn off `PROJ_NETWORK`? So we don't need to bother testing the multiple options of network on/off, proj-data available or not, .. (that kind of testing we can leave to pyproj?)

Now, I still find it strange that Travis is actually showing a different error ..

**Comment by jorisvandenbossche** [comment]
OK, I could reproduce the Travis issue (the thing is that we were using a different description of the CRS in the forward and inverse transform):

```
import pyproj

crs1a = pyproj.CRS("epsg:26918")
crs1b = pyproj.CRS("+proj=utm +zone=18 +ellps=GRS80 +datum=NAD83 +units=m +no_defs ") 
crs2 = pyproj.CRS("EPSG:4326")

trans = pyproj.Transformer.from_crs(crs1a, crs2, always_xy=True) 
trans_inv = pyproj.Transformer.from_crs(crs2, crs1b, always_xy=True)   

trans_inv.transform(*trans.transform(-1683723.000, 6689139.000))
```

So with PROJ 6.3 this gives:

```
In [2]: trans_inv.transform(*trans.transform(-1683723.000, 6689139.000))    
Out[2]: (-1683723.0000000005, 6689139.0)

In [3]: pyproj.proj_version_str      
Out[3]: '6.3.0'
```

With PROJ 7:

```
In [2]: trans_inv.transform(*trans.transform(-1683723.000, 6689139.000))  
Out[2]: (-1683723.2477671406, 6689138.821430741)

In [3]: pyproj.proj_version_str   
Out[3]: '7.0.0'
```

Now, with the following combinations:

- unset PROJ_NETWORK, but proj-data is installed: the "wrong" result
- unset PROJ_NETWORK, but also removed proj-data again: "correct" result
- with PROJ_NETWORK on: "wrong" result

so it clearly depends on whether the grid file is used or not.

**Comment by jorisvandenbossche** [comment]
So it seems that in PROJ 6 the "epsg:26918" and "+proj=utm +zone=18 +ellps=GRS80 +datum=NAD83 +units=m +no_defs " descriptions could roundtrip, while in PROJ 7 (when using grids) not anymore. 
Now that goes beyond my geodesic knowledge to known whether that is a regression or not ;)

I suppose it is quite possible that when using grids, the EPSG:26918 -> EPSG:4326 is now more correct, while the conversion of EPSG:4326 back using the proj4 string still uses the ballpark transformation. Hence it doesn't fully roundtrip. 
When not using grids, the first EPSG:26918 -> EPSG:4326 conversion might also use the less correct transformation, so roundtrip works since back and forth is both with the ballpark transformation. Does that make sense?

So for geopandas, we should probably either not use grids for this test, or update the test to use a different CRS for which the EPSG vs proj4 string based transformations used is the same, or make the test less precise.
