### ISSUE TITLE
Spatial index not deterministic?

### ISSUE THREAD

**Issue by bretttully** [geopandas/geopandas#1361]
Hi all,

I am working with the `sindex` but am surprised to find that the results returned are not deterministic (or more likely, I'm doing it wrong...)

I have a geopandas dataframe and then run the following:

```python
assert gpd.__version__ == "0.7.0"

def intersects(si, geom):
    i = si.intersection(geom.bounds)
    try:
        _ = next(i)
        return True
    except StopIteration:
        return False

# create the spatial index
sindex = df.sindex

# create geom
geom = shapely.wkt.loads(
    'POLYGON ((-122.34375 47.98992166741417, -122.34375 48.1074311884804,'
    ' -122.51953125 48.1074311884804, -122.51953125 47.98992166741417,'
    ' -122.34375 47.98992166741417))'
)

# intersect many times
for i in range(5):
    cnt = {True: 0, False: 0}
    for _ in range(1000):
        cnt[intersects(sindex, geom)] += 1
    print(cnt)
```

Is there some probabilistic algorithm in the sindex?

which gives:

```python
{True: 966, False: 34}
{True: 960, False: 40}
{True: 957, False: 43}
{True: 969, False: 31}
{True: 976, False: 24}
```

**Comment by martinfleis** [comment]
Can you prove reproducible example? I am getting either all True or all False. It should return the same result all the time. This may come from floating point precision issue.

**Comment by adriangb** [comment]
@martinfleis should we close this due to lack of response?

**Comment by bretttully** [comment]
Oof, dropped the ball. Sorry guys, that example was useless coming back 2 years later.
