### ISSUE TITLE
BUG: GeoDataFrame.astype() returns GeoDataFrame without crs

### ISSUE THREAD

**Issue by onietosi** [geopandas/geopandas#1366]
The crs is lost when using the `astype` method on a GeoDataFrame:

    >>> import geopandas

    >>> df = geopandas.read_file(geopandas.datasets.get_path('nybb'))
 
    >>> df2 = df.astype({'BoroCode': str})
 
    >>> type(df.crs)
    pyproj.crs.crs.CRS
    
    >>> type(df2.crs)
    NoneType

Would it suffice to add `crs = self._crs` when reconstructing the GeoDataFrame in line 775? I am not that familiar with the inner workings of geopandas.

https://github.com/geopandas/geopandas/blob/8932b3c59f2eecc925bbea565de03ce59a8cb52d/geopandas/geodataframe.py#L772-L775

**Comment by martinfleis** [comment]
Thank you for the report. This will be fixed by #1339.

**Comment by jorisvandenbossche** [comment]
@martinfleis did you add a test for this case in the PR?

**Comment by martinfleis** [comment]
@jorisvandenbossche will do.

**Comment by joooeey** [comment]
This bug is still present on the current version v0.12.2:

```
gpd.GeoDataFrame(
    [42],
    geometry=[shapely.geometry.Point([1, 2])],
    crs="epsg:4326",
).astype(str).crs

---------->
AttributeError: 'DataFrame' object has no attribute 'crs'
```
