### ISSUE TITLE
BUG: GeoDataFrame CRS loss during __setitem__ on pandas master

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1372]
Due to some recent changes on pandas master, GeometryArray loses its CRS during `__setitem__`. In the following example from our tests, resulting CRS should be the one of passed array (4326).

```py
from geopandas.array import from_shapely

geoms = [Point(0, 0), Point(1, 1)]
df = GeoDataFrame({"col1": [0, 1]}, geometry=geoms, crs=27700)
df["geometry"] = from_shapely(geoms, crs=4326)

df.crs
<Projected CRS: EPSG:27700>
...
```

Related issues on pandas side pandas-dev/pandas#33457, pandas-dev/pandas#32960

**Comment by m-richards** [comment]
I might take a look at this one too if that's okay

**Comment by martinfleis** [comment]
Yes, thanks!
