### ISSUE TITLE
BUG: Incorrect colours when plotting multiple geometry types with list of colours

### ISSUE THREAD

**Issue by robbibt** [geopandas/geopandas#1379]
**Expected result**

I have a `geopandas.GeoDataFrame` that contains multiple geometry types (e.g. `Polygon`, `LineString` and `Point`). I want to plot this data by supplying a list of colours (one per feature) to the `color=` parameter:

 ```
from shapely.geometry import LineString, Point, Polygon
import geopandas as gpd

gdf = gpd.GeoDataFrame(geometry=[Polygon([(1, 1), (1, 2), (2, 2), (2, 1)]),
                                 LineString([(2, 0), (4, 2)]),
                                 Point(3, 2),
                                 Point(1, 0)])

gdf.plot(color=['red', 'green', 'blue', 'blue'])
```

For this example, I would expect that:

1. My `Polygon` feature will be plotted in "red"
2. My `LineString` feature will be plotted in "green"
3. Both of my `Point` features will be plotted in "blue"

**Actual result**

However, I receive this result:

![image](https://user-images.githubusercontent.com/17680388/79415718-65346580-7ff1-11ea-88c6-0473ebaeaf1a.png)

It appears to me like the list of colours is being applied separately to each geometry type, with the first item of each type being plotted in "red", and the second item of each type being plotted in "green" (e.g. see the `Point` features).

This appears related to the PR and linked issues here (#1119), but those look like they refer specifically to multi-geometries, and **not multiple geometry types.**

**Environment**
`geopandas '0.7.0'`
`Python 3.6.9 (default, Nov  7 2019, 10:44:02) `
`IPython 7.12.0 `

**Comment by martinfleis** [comment]
Thank you for the report!

Your assumption is correct. Each geometry type is now plotted as an independent Collection, to which we pass `color` as it is (assuming it is a single value). For list-like `color` values of the correct length, we should do the same we do with `value`, i.e. decomposing the list based on the geom type.

**Comment by martinfleis** [comment]
ref #1385

**Comment by jorisvandenbossche** [comment]
Another example that I just saw on SO (https://stackoverflow.com/questions/67552817/geopandas-not-plotting-correct-colors):

```python
import geopandas
from shapely.geometry import Point, box

gdf = geopandas.GeoDataFrame({
    "geometry": [box(0,0,1,1), box(1,1,2,2), box(2,2,3,3), Point(0, 0), Point(1,1), Point(2,2), Point(3,3)],
    "color_rgba": [(0.0, 0.0, 0.0, 0.5), (0.0, 0.0, 0.0, 0.2), (0.0, 0.0, 0.0, 0.1), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0)],
})

gdf.plot(figsize=(20, 20), markersize=1000, edgecolor='k', color=gdf['color_rgba'])
```


![Figure_ge](https://user-images.githubusercontent.com/1020496/118391890-e0be7700-b636-11eb-95ef-7e1db891aef0.png)

(all points should be white)

**Comment by cmcconomyfwig** [comment]
I just got bitten by this issue; how do you recommend specifying color in a GeoDataFrame with mixed geometry types?

**Comment by jorisvandenbossche** [comment]
I mentioned it on the StackOverflow question as well: I think the easiest workaround for now is to plot the different geometry types separately (you can subset the single dataframe, once for the polygons, once for the linestrings, once for the points, and plot each of them separately)

**Comment by rraymondgh** [comment]
Using both examples in this issue:

```
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point, box
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

# fmt: off
gdf = gpd.GeoDataFrame({
    "geometry": [box(0,0,1,1), box(1,1,2,2), box(2,2,3,3), Point(0, 0), Point(1,1), Point(2,2), Point(3,3)],
    "color_rgba": [(0.0, 0.0, 0.0, 0.5), (0.0, 0.0, 0.0, 0.2), (0.0, 0.0, 0.0, 0.1), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0), (1.0, 1.0, 1.0, 1.0)],
})
# fmt: on

fig, axs = plt.subplots(nrows=1, ncols=3, figsize=(10, 6.4))
cmap = LinearSegmentedColormap.from_list(
    "seg", gdf["color_rgba"].unique(), N=len(gdf["color_rgba"].unique())

)

gdf.plot(ax=axs[0], markersize=1000, edgecolor="k", color=gdf["color_rgba"])
gdf.plot(ax=axs[1], markersize=1000, edgecolor="k", column="color_rgba", cmap="Blues")
gdf.plot(ax=axs[2], markersize=1000, edgecolor="k", column="color_rgba", cmap=cmap)
```
<img width="610" alt="image" src="https://user-images.githubusercontent.com/42769112/164683971-4b2dc052-d4d5-4fd6-901b-8031d3015007.png">

```
rom shapely.geometry import LineString, Point, Polygon
import geopandas as gpd
import numpy as np

gdf = gpd.GeoDataFrame(geometry=[Polygon([(1, 1), (1, 2), (2, 2), (2, 1)]),
                                LineString([(2, 0), (4, 2)]),
                                Point(3, 2),
                                Point(1, 0)])

fig, axs = plt.subplots(nrows=1, ncols=2, figsize=(10, 6.4))
colors = ['red', 'green', 'blue', 'blue']

cmap = LinearSegmentedColormap.from_list(
    "seg", np.unique(colors), N=len(np.unique(colors))

)
gdf.plot(ax=axs[0], color=colors)
gdf.assign(_color=colors).plot(ax=axs[1], column="_color", cmap=cmap)
```

<img width="609" alt="image" src="https://user-images.githubusercontent.com/42769112/164684152-92cccce6-1b7d-4c51-94c2-b2ba6f5b6949.png">

In both cases the situation is the **color** series / list is same length as dataframe.   
- could be considered an misunderstanding of **color** parameter. It's the sequence in which colors are used based on **column** parameter.  This is quite somewhat subtle as **geometry** is processed internally drives this
- could be considered an enhancement...  if length of **color** parameter is same as dataframe, create an internal column and a `LinearSegmentedColormap()` as per examples above

Happy to create a PR for second bullet if that's considered right approach

**Comment by cmcconomyfwig** [comment]
Great idea.. i can't speak for everyone but the GDF to me is the collection abstraction i am plotting, and i expected the color to distribute across all items irrespective of geometry type. I wonder what other side effects would occur with this patch?

**Comment by martinfleis** [comment]
> could be considered an misunderstanding of color parameter. It's the sequence in which colors are used based on column parameter.

Not necessarily. You can plot geometries without using a `column` and then the idea is that you are able to pass a list of colours that is mapped to individual geometries. It is just broken when you have mixed geom types.

> if length of color parameter is same as dataframe, create an internal column and a LinearSegmentedColormap() as per examples above

That may work, yes. You don't even need a column as `column` can take an array.

But the solution I outlined above would also work:

> For list-like color values of the correct length, we should do the same we do with value, i.e. decomposing the list based on the geom type.
