### ISSUE TITLE
Handle empty geometry

### ISSUE THREAD

**Issue by fscottfoti** [geopandas/geopandas#138]
When I called geopandas.GeoDataFrame.from_file() I was getting an exception.  I followed the error and realized I had geometry that was being returned by fiona as 'None'.  The following code, for instance, solves the issue by checking for 'None' and continuing.

https://github.com/fscottfoti/geopandas/commit/a4cbbde5467043338ee2404df0ad7af3e82a490e

I'm not sure how you want to handle this issue, but I figured you should be aware of it - it seems like geopandas should gracefully handle empty geometry.  When I added code to allow adding records with empty geometry to the dataframe, I got another exception when I called 'to_file'.  I'm happy to fix this if you want to advise me on how you want it done.

Thanks -
Fletcher

**Comment by martinfleis** [comment]
Fixed by #138
