### ISSUE TITLE
Multi-part Lines getting same color but dissimilar width

### ISSUE THREAD

**Issue by rwijtvliet** [geopandas/geopandas#1384]
Probably related to [1141](https://github.com/geopandas/geopandas/issues/1141), but this issue is still present in 0.7. I'll let the example speak for itself:

```
import geopandas as gpd
import shapely.geometry as sg

gdf = gpd.GeoDataFrame([{'geometry':sg.MultiLineString([[[0,0],[0,1]],[[0,1],[1,1]]]),
                         'linewidth':8, 'color':'red'},
                        {'geometry':sg.LineString([[0,0],[2,1]]),
                         'linewidth':2, 'color':'blue'}])
gdf.plot(linewidth=gdf['linewidth'], color=gdf['color'])
```

output: 
![image](https://user-images.githubusercontent.com/4106013/79636312-0567c700-8177-11ea-8b47-a8871d982945.png)

As you can see, the `MultiLine`, which is correctly colored red in the image, is drawn with an incorrect linewidth for one of its two lines. The `Line`, which is correctly colored blue, also has an incorrect linewidth. That is, unless I'm using it wrong of course.

**Comment by martinfleis** [comment]
Thank you! We should make sure that all style kwds are properly replicated for all parts. We do that now for `color` only. This should be generalised for all applicable kwds:

https://github.com/geopandas/geopandas/blob/f70a66918df086bd0fca37f03e160224f400fe14/geopandas/plotting.py#L101-L102

**Comment by rwijtvliet** [comment]
Ah, great. I was looking through the trace to see where this happens. If I have time later I'll see if I can fix it and make a PR
