### ISSUE TITLE
TST: from_postgis is skipped in all envs

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1389]
There is an issue with testing `from_postgis` somewhere. We have a condition to skip the test if `psycopg2` is missing, but it is currently skipped even for envs where it actually is installed. It is skipped even in my local env.

**Comment by jorisvandenbossche** [comment]
We did have it in travis at some point, it seems, but a long time ago .. https://github.com/geopandas/geopandas/commit/f9ee0be092c5fac00be6c65c5f73a96a8016f785

Nowadays, you can install postgresql and postgis with conda-forge, so that might be an option to install it in one of the builds.

**Comment by jorisvandenbossche** [comment]
OK, after quite some trial an error .., the tests should be running -> https://github.com/geopandas/geopandas/pull/1391. So we can actually test the other PRs then ;)

**Comment by martinfleis** [comment]
Closed by #1391
