### ISSUE TITLE
Importing contextily before geopandas breaks geopandas crs conversion

### ISSUE THREAD

**Issue by richardmcnamara** [geopandas/geopandas#1392]
When importing contextily before geopandas (for example, if you wanted to import alphabetically) converting crs from 'epsg:4326' to 'epsg:3857' on a GeoDataFrame is broken.

With contextily imported before geopandas:
```
import contextily as ctx
import geopandas
import pandas as pd

print(geopandas.__version__)
print(pd.__version__)
print(ctx.__version__)

df = pd.DataFrame([(1, 40, 5)], columns=['id', 'latitude', 'longitude'])

gdf = geopandas.GeoDataFrame(
    df,
    geometry=geopandas.points_from_xy(df.longitude, df.latitude),
    crs='epsg:4326'
)

print(gdf)

df_converted = gdf.to_crs(crs='epsg:3857')

print(df_converted)
```
results in
```
0.7.0
0.25.1
1.0.0
   id  latitude  longitude                  geometry
0   1        40          5  POINT (5.00000 40.00000)
   id  latitude  longitude                 geometry
0   1        40          5  POINT (0.00000 0.00000)
```
I don't expect to see `POINT (0.00000 0.00000)` here.

With contextily imported after geopandas:
```
import geopandas
import pandas as pd
import contextily as ctx

print(geopandas.__version__)
print(pd.__version__)
print(ctx.__version__)

df = pd.DataFrame([(1, 40, 5)], columns=['id', 'latitude', 'longitude'])

gdf = geopandas.GeoDataFrame(
    df,
    geometry=geopandas.points_from_xy(df.longitude, df.latitude),
    crs='epsg:4326'
)

print(gdf)

df_converted = gdf.to_crs(crs='epsg:3857')

print(df_converted)
```
results in
```
0.7.0
0.25.1
1.0.0
   id  latitude  longitude                  geometry
0   1        40          5  POINT (5.00000 40.00000)
   id  latitude  longitude                        geometry
0   1        40          5  POINT (556597.454 4865942.280)
```
as expected.

As a side note, calling `geopandas.GeoDataFrame` on `df` results in the `df` having a `geometry` column added. I wouldn't expect the `df` to be modified in place with this function, only the new `gdf` to be created.

**Comment by martinfleis** [comment]
Thank you for the report. How did you install geopandas and contextily? In my environment it works as expected.

> As a side note, calling geopandas.GeoDataFrame on df results in the df having a geometry column added. I wouldn't expect the df to be modified in place with this function, only the new gdf to be created.

Yeah, it has been already reported (#1179).

**Comment by richardmcnamara** [comment]
Sorry, I should have checked the other issues before mentioning that side note.

I've installed geopandas and contextily using pip, however had trouble building fiona, GDAL and rasterio on my machine, so used the wheels at:

https://www.lfd.uci.edu/~gohlke/pythonlibs/

Fiona-1.8.13-cp37-cp37m-win_amd64.whl
GDAL-3.0.4-cp37-cp37m-win_amd64.whl
rasterio-1.1.3-cp37-cp37m-win_amd64.whl

Other dependencies (Shapely, pyproj etc) were installed with pip

**Comment by jorisvandenbossche** [comment]
@richardmcnamara can you check if importing `rasterio` instead of `contextily` gives the same problem? (it might be that the PROJ lib included in the rasterio wheel is giving conflicts)

**Comment by richardmcnamara** [comment]
Yip, rasterio gives the issue. Running:

```
import rasterio
import geopandas
import pandas as pd

print(geopandas.__version__)
print(pd.__version__)
print(rasterio.__version__)

df = pd.DataFrame([(1, 40, 5)], columns=['id', 'latitude', 'longitude'])

gdf = geopandas.GeoDataFrame(
    df,
    geometry=geopandas.points_from_xy(df.longitude, df.latitude),
    crs='epsg:4326'
)

print(gdf)

df_converted = gdf.to_crs(crs='epsg:3857')

print(df_converted)
```

gives:
```
0.7.0
0.25.1
1.1.3
   id  latitude  longitude                  geometry
0   1        40          5  POINT (5.00000 40.00000)
   id  latitude  longitude                 geometry
0   1        40          5  POINT (0.00000 0.00000)
```

I had another go at reinstalling rasterio without using the wheel but didn't succeed.

**Comment by jorisvandenbossche** [comment]
@richardmcnamara can you show the result of `import pyproj; pyproj.show_versions()` ?

Also, to reduce the scope further of a reproducuble example, I suppose that just rasterio and pyproj should suffice:

```
# import rasterio
import pyproj
# import rasterio
crs1 = pyproj.CRS("EPSG:4326")  
crs2 = pyproj.CRS("EPSG:3857") 
transformer = pyproj.Transformer.from_crs(crs1, crs2, always_xy=True)
print(transformer.transform(5, 40))
```

Can you try those (with either of rasterio imports uncommented)

In the end, I suppose it has to do with incompatible binary packages installed from different sources (I suppose pyproj is finding the PROJ included in rasterio, instead of the one it is build against), so solutions to get this solved for you:

- Use conda instead of pip (there are binary conda packages for rasterio on Windows, while there are no rasterio wheels for windows on PyPI)
- If using the wheels from https://www.lfd.uci.edu/~gohlke/pythonlibs/, also install pyproj from there

But it would be nice to still solve it generally (cc @snowman2). Maybe there is some PROJ detection mechanism in pyproj that is going wrong or could detect this case.

**Comment by snowman2** [comment]
> If using the wheels from https://www.lfd.uci.edu/~gohlke/pythonlibs/, also install pyproj from there

Actually, that is where the wheels for `pyproj` come from on pypi.

**Comment by snowman2** [comment]
This is what should be happening:
https://pyproj4.github.io/pyproj/stable/api/datadir.html#pyproj-datadir-get-data-dir
```
The order of preference for the data directory is:
1.    The one set by pyproj.datadir.set_data_dir (if exists & valid)
2.    The internal proj directory (if exists & valid)
3.    The directory in PROJ_LIB (if exists & valid)
4.    The directory on sys.prefix (if exists & valid)
5.    The directory on the PATH (if exists & valid)
```

@richardmcnamara 

For debugging purposes, would you mind running this and sharing the output:
```python
import rasterio
import geopandas
import pyproj

print(pyproj.get_data_dir())
```
And then running this and sharing the output:
```python
import geopandas
import pyproj
import rasterio

print(pyproj.get_data_dir())
```

**Comment by richardmcnamara** [comment]
For the record, importing the packages in the 'wrong' order is fine for me. But I'm happy to help debug the issue.

@jorisvandenbossche I've run your example and both options (rasterio before or after), give the same result
```
(556597.4539663679, 4865942.279503176)
```

@snowman2 When running either of your examples `pyproj.datadir.get_data_dir()` gives the same result:
```
c:\users\richard.mcnamara\appdata\local\programs\python\python37\lib\site-packages\pyproj\proj_dir\share\proj
```

I've just found the time to keep digging through and have found that the projection was a red herring. It turns out the Point is created incorrectly in `points_from_xy` (though not the fault of geopandas).

Here's a new minimal example:
```
#import rasterio
import shapely
import shapely.geometry

#print(rasterio.__version__)
print(shapely.__version__)

result = shapely.geometry.Point(5, 40)

print(result)

for x, y in result.coords:
   print("x={}, y={}".format(x, y))
```
gives
```
1.7.0
POINT (5 40)
x=5.0, y=40.0
```
as expected, whereas:
```
import rasterio
import shapely
import shapely.geometry

print(rasterio.__version__)
print(shapely.__version__)

result = shapely.geometry.Point(5, 40)

print(result)

for x, y in result.coords:
   print("x={}, y={}".format(x, y))
```
gives
```
1.1.3
1.7.0
POINT (5 40)
x=0.0, y=0.0
```
so importing rasterio is causing the shapely point not to be created correctly (although it's still labelled correctly). Shapely was installed from pip, rasterio from the wheel (as above).

So it's not a problem with either geopandas or contextily, sorry for wasting your time!

**Comment by jorisvandenbossche** [comment]
> So it's not a problem with either geopandas or contextily, sorry for wasting your time!

No, no, thanks for testing it further! 

So then the problem will be with GEOS instead of PROJ (rasterio / GDAL also builds against GEOS in addition to PROJ, so indeed that was also a possibility)

How did you install Shapely? With pip, or also from Gohlke's site? If not, can you try if installing shapely from there solves the problem?

**Comment by jorisvandenbossche** [comment]
Also, can you show the output of `geopands.show_versions()` (before you reinstall shapely)

**Comment by richardmcnamara** [comment]
My `geopandas.show_versions()` gives (with Shapely installed from pip):

```
SYSTEM INFO
-----------
python     : 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\richard.mcnamara\AppData\Local\Programs\Python\Python37\python.exe
machine    : Windows-10-10.0.18362-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.0.4
GDAL data dir: None
PROJ       : 6.3.1
PROJ data dir: C:\Users\richard.mcnamara\AppData\Local\Programs\Python\Python37\lib\site-packages\pyproj\proj_dir\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.7.0
pandas     : 0.25.1
fiona      : 1.8.13
numpy      : 1.18.3
shapely    : 1.7.0
rtree      : None
pyproj     : 2.6.0
matplotlib : 3.1.1
mapclassify: None
pysal      : None
geopy      : 1.21.0
psycopg2   : None
```

Shapely was installed from pip. Installing the wheel from Gohlke's site indeed solves the issue:
```
import rasterio
import shapely
import shapely.geometry

print(rasterio.__version__)
print(shapely.__version__)

result = shapely.geometry.Point(5, 40)

print(result)

for x, y in result.coords:
   print("x={}, y={}".format(x, y))
```
gives
```
1.1.3
1.7.0
POINT (5 40)
x=5.0, y=40.0
```
as expected.
