### ISSUE TITLE
Spatial indexes for geo data frames and series

### ISSUE THREAD

**Issue by sgillies** [geopandas/geopandas#140]
A new issue and branch because we're starting over from f42d049.

When a GeoDataFrame or GeoSeries is created, it will get an R-tree attached as `_sindex`. This R-tree can be used to speed up queries. Usage example:

```python
from geopandas import read_file

boros = read_file("/nybb_14a_av/nybb.shp", vfs="zip://examples/nybb_14aav.zip")
tree = self.boros._sindex
hits = list(tree.intersection((1012821.80, 229228.26)))
print(boros.ix[hits]['BoroName'])
# Output:
#
# 4     Bronx
# 2    Queens
# Name: BoroName, dtype: object
```

R-tree intersection considers bounding boxes only, so it generates false positives: `boros.intersects(Point(1012821.80, 229228.26))` needs to run over those 2 candidates and reduce the selection to those that precisely intersect.

After reading http://pandas.pydata.org/pandas-docs/stable/indexing.html again I think we need to put some thought into whether this supports integer or label indexing. Example above is for integer/iloc type indexing.

**Comment by kjordahl** [comment]
closed by #141
