### ISSUE TITLE
DOC: Add section for fastest method to transform points in CSV file

### ISSUE THREAD

**Issue by snowman2** [geopandas/geopandas#1400]
Ref: https://gis.stackexchange.com/questions/334271/converting-large-data-with-lat-and-long-into-x-and-y

There is overhead with GEOS geometry creation that isn't necessary when you only have a CSV file with points.

I was thinking it might be worthwhile to add a recommendation to use the `Transformer` directly in that case with a pandas dataframe.

Essentially:
```python
from pyproj import Transformer

trans = Transformer.from_crs(
    "epsg:4326",
    "+proj=utm +zone=10 +ellps=WGS84",
    always_xy=True,
)
xx, yy = trans.transform(My_data["LON"].values, My_data["LAT"].values)
My_data["X"] = xx
My_data["Y"] = yy
```

**Comment by martinfleis** [comment]
In this case, geopandas is not used in any step. Should not this go rather to documentation of pyproj?

**Comment by snowman2** [comment]
I actually think of this more of a targeted & advanced use case for geopandas. For most people, `to_crs()` will do what they want. However, there are a subset of geopandas users who do use a CSV file (or equivalent) with point data stored in the columns (https://geopandas.org/gallery/create_geopandas_from_pandas.html)

For that user base, it would be more of a tip for them if they want to transform points that there is a faster way if they need it. However, this is definitely not something that must be added. Just something I thought might be helpful.

**Comment by snowman2** [comment]
Another one popped up recently: https://stackoverflow.com/questions/61440619/how-to-speed-up-projection-conversion/61459700

**Comment by snowman2** [comment]
I think with the examples in stackoverflow, this is probably not necessary.
