### ISSUE TITLE
geopandas.read_file fails for gzip content-encoded URLs

### ISSUE THREAD

**Issue by ian-r-rose** [geopandas/geopandas#1403]
A bit of context here: yesterday (4/28) ArcGIS Hub (which hosts a lot of open data portals) turned on gzip content encoding for their data download URLs (geojson, shapefile, etc). GeoPandas doesn't identify this encoding and tries to read in the gzipped data directly, then fails.

A MWE:
```python
import geopandas
geopandas.read_file("https://opendata.arcgis.com/datasets/898c91b2d8f046608a4df64de8d36649_3.geojson")
```
which succeeded a few days ago, and fails now.

Two possible fixes:

1. Use the higher-level `requests` library, which automatically decompresses transport-encoded data, at the cost of another dependency.
1. Use the stdlib gzip in `geopandas.read_file` to decompress when necessary, which doesn't add a non-stdlib dependency, but may not catch some corner cases that `requests` would.

I'd be happy to make a PR fixing this if there is consensus on the best way forward.

**Comment by thomas-hervey** [comment]
@ian-r-rose I apologize for this inconvenience. This is a bug that we haven't seen before. The Hub team is looking into this right now. Yesterday we released an update to our download system and so we are monitoring issues as they come in. I've elevated this problem and will be checking with developers about it this evening.

**Comment by thomas-hervey** [comment]
@ian-r-rose the fix is out. I've tested a `geopandas.read_file` request with the above dataset without a problem.

**Comment by ian-r-rose** [comment]
This has indeed been fixed on the ArcGIS side, thanks for the update @thomas-hervey.

I'm going to close this as resolved. However, for posterity, in case other cases of gzip-encoded remote content arise in the future, I found this to be a relatively minimal fix on the geopandas side:

```diff
diff --git a/geopandas/io/file.py b/geopandas/io/file.py
index 26f4243..4f46701 100644
--- a/geopandas/io/file.py
+++ b/geopandas/io/file.py
@@ -83,7 +83,11 @@ def read_file(filename, bbox=None, mask=None, rows=None, **kwargs):
     """
     if _is_url(filename):
         req = _urlopen(filename)
-        path_or_bytes = req.read()
+        if req.info().get("Content-Encoding") == "gzip":
+            import gzip
+            path_or_bytes = gzip.decompress(req.read())
+        else:
+            path_or_bytes = req.read()
         reader = fiona.BytesCollection
     elif isinstance(filename, io.TextIOBase):
         path_or_bytes = filename.read()
```
This is something that `requests` should also handle automatically.
