### ISSUE TITLE
GeoPandas logo proposal

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1405]
GeoPandas is a widely known package, but even after all the years of development it does not have a logo. At some places we use this https://avatars0.githubusercontent.com/u/8130715?s=200&v=4 and now I've noticed that on [NumFOCUS](https://numfocus.org/sponsored-projects/affiliated-projects) we have [another one](https://numfocus.org/wp-content/uploads/2020/04/GeoPandas.png) serving as a placeholder more than anything. There was one attempt to get a logo (#786) before, but that was not adopted.

I am proposing to use following one, based on pandas logo adding a simple circle representing pandas data within a world. I feel that adapting pandas logo in this way reflects relationship between pandas and GeoPandas.

![Artboard 8](https://user-images.githubusercontent.com/36797143/80921920-6f848c80-8d71-11ea-9512-bc0a4858c2d4.png)
![Artboard 9](https://user-images.githubusercontent.com/36797143/80921918-6eebf600-8d71-11ea-838f-6e2193cf55f8.png)
![Artboard 9 copy](https://user-images.githubusercontent.com/36797143/80921916-6d223280-8d71-11ea-884b-eb523ba0fbb0.png)

Unlike for pandas, I feel that `GeoPandas` works better than `geopandas`.

If we want to be a bit less similar to pandas than this, we may try using different colors.

Logo is using the same font, for which I have a license.

Another option is to use non-pandas-like logo, but that will be a more complicated journey.

All versions of pandas logo for a reference: https://pandas.pydata.org/about/citing.html

What do you think?

**Comment by story645** [comment]
The rif on the pandas log in geo colors (green, blue, brown) could be cool, would even look a little like a globe.  This is probably a given but,  do you have permission from pandas to riff on their logo/how is their logo licensed?

**Comment by jorisvandenbossche** [comment]
Thanks @martinfleis for starting this discussion again, and for the proposal ;)

I was also wondering whether we could use (partly) different colors, to have a more distinct look while still maintaining the link with pandas (but not sure if that will be easy / the pandas logo resemblance is then still strong enough to recognize the link).

>  This is probably a given but, do you have permission from pandas to riff on their logo/how is their logo licensed?

That's certainly something we best check with the pandas team. I am not sure we (speaking as pandas dev now) really thought about this already.

**Comment by martinfleis** [comment]
I'll try different colors, to see what happens.

I tried to check the licensing of pandas logo before I did that, but there is no mention that it should be licensed differently than the rest of the package. @jorisvandenbossche can you check that with the rest of the pandas team? I am happy to drop this idea if pandas is not comfortable with that.

**Comment by ljwolf** [comment]
I dig. But, terms of the logo usage say we can't 
> distort the logo by changing its properties

Hopefully this isn't too much of a distortion...

**Comment by martinfleis** [comment]
I am not sure if the Logo usage rules apply to this case. It seems to cover the placement of the actual logo than derivations.

If they do apply, we certainly violate following point

> Do not place text or other elements on top of the logo

**Comment by jdmcbr** [comment]
I would personally vote to have a logo for geopandas that is a little more visually distinctive from the pandas logo. Even if colors were altered a bit on top of adding the circle around the core part of the pandas logo, it feels like it would be easy for more casual users to mistake it for the pandas logo.

**Comment by snowman2** [comment]
Ref: #938

**Comment by adriangb** [comment]
Maybe the colored bits (I guess they are called rifs?) could be reshaped into continent-like shapes, so that it looks like a globe?

**Comment by martinfleis** [comment]
Since we've got some updates from pandas team recently, let's move this forward. The optimal plan would be to pick a different colour scheme. I've played with some, and here are three options which are distinct enough from the original pandas logo, but still play nicely with original yellow and pink dots I'd like to keep in original colours.

**Option A**
![Artboard 7 kopie 2](https://user-images.githubusercontent.com/36797143/87470122-3a6ba480-c614-11ea-9d16-cee94787410a.png)
![Artboard 7 kopie](https://user-images.githubusercontent.com/36797143/87470129-3ccdfe80-c614-11ea-9c21-d222e98b29b2.png)
![Artboard 7](https://user-images.githubusercontent.com/36797143/87470133-3dff2b80-c614-11ea-85b1-40e8331f4041.png)

**Option B**

![Artboard 7 kopie 5](https://user-images.githubusercontent.com/36797143/87470217-5e2eea80-c614-11ea-90c6-05ffd73353ad.png)
![Artboard 7 kopie 4](https://user-images.githubusercontent.com/36797143/87470223-5ff8ae00-c614-11ea-9c70-528ae3fc885f.png)
![Artboard 7 kopie 3](https://user-images.githubusercontent.com/36797143/87470228-625b0800-c614-11ea-81a3-010460ba2fad.png)

**Option C**

![Artboard 7 kopie 8](https://user-images.githubusercontent.com/36797143/87470314-7ef74000-c614-11ea-9c5c-be0dcf63b9e1.png)
![Artboard 7 kopie 7](https://user-images.githubusercontent.com/36797143/87470320-80c10380-c614-11ea-8ba8-087c0fc05a35.png)
![Artboard 7 kopie 6](https://user-images.githubusercontent.com/36797143/87470328-83235d80-c614-11ea-93b3-9f90e185e366.png)

twitter:

<img width="542" alt="Screenshot 2020-07-14 21 04 30" src="https://user-images.githubusercontent.com/36797143/87471086-aac6f580-c615-11ea-83ad-00a45b42ea80.png">


My personal preference is option A, but I'd be happy with any of these. What are your thoughts?

**Comment by ljwolf** [comment]
A looks rad!

**Comment by adriangb** [comment]
A looks great, but tbh they all look really cool, great job @martinfleis!

**Comment by jbednar** [comment]
Looks good! @BoBednar has also offered another option for GeoPandas at https://github.com/holoviz/spatialpandas/issues/39 : 

![image](https://user-images.githubusercontent.com/1695496/87478036-bbb04080-c5ee-11ea-8353-b2e9768c6158.png)

This one resembles the Pandas logo less (not sure if that's good or bad), but does sort of spell GeoPandas (or Gpd, at least), even though she proposed it for [SpatialPandas](https://github.com/holoviz/spatialpandas). I assume it would go with the same font as in the above.

**Comment by martinfleis** [comment]
@jbednar Looks good either if I put the text along and use the same colours as above. Although the circular one feels a bit more balanced in terms of stroke width vs text. This one might also need a less circular font.

<img width="571" alt="Screenshot 2020-07-14 23 15 01" src="https://user-images.githubusercontent.com/36797143/87481777-eec2f600-c627-11ea-9077-2619d9af8d43.png">

**Comment by jbednar** [comment]
Cool! I like either set of colors. I agree, this font looks a bit too curvy for this blocky logo, particularly where the stroke width gets narrow. Do you have anything where the stroke stays constant width, unlike this one's "a" and "d" that have those narrow bits?  The logo is so brutally rectangular that having graceful curves in the letters looks less appropriate somehow.

**Comment by jbednar** [comment]
Here are examples with tightly kerned Ubuntu bold (with source in [possiblegeopandaswordmark.zip](https://github.com/geopandas/geopandas/files/4927677/possiblegeopandaswordmark.zip)):

Option D
![image](https://user-images.githubusercontent.com/1695496/87587654-02ae3c80-c6a8-11ea-8f8b-411849b36a8a.png)

Option E

![image](https://user-images.githubusercontent.com/1695496/87587695-0e016800-c6a8-11ea-8b2a-f5bbd5607758.png)

@jorisvandenbossche , ready to vote?

**Comment by jorisvandenbossche** [comment]
I am leaving (as I type) on holidays and will be offline for the rest of the month, so I won't be able to help with driving this to a decision on the short term (but other core devs: feel free to do so!)

My quick opinion:

* From options A-C, I also like the A color the most. For options D-E, I like D the most. 
* I think I generally feel that A-C might be conveying the "spatial" aspect a bit more, but my feeling says that D-E are better as a "logo" (so I think a slight preference for this).
* For the D-E, I was wondering if a version with just the G (the left part, but then a bit wider) could also make sense (but since I am not a good designer, I can only see it vaguely in my head and not put it on screen ;))

**Comment by jbednar** [comment]
Sure, here's just the G either original size or a bit wider:

Option F
![possiblegeopandaswordmarkF](https://user-images.githubusercontent.com/1695496/87595315-f62fe100-c6b3-11ea-8aa7-59886c5aa245.png)

Option G
![possiblegeopandaswordmarkG](https://user-images.githubusercontent.com/1695496/87595480-3c854000-c6b4-11ea-8755-8eda251f2a65.png)

**Comment by martinfleis** [comment]
Let's see what people think. **It is a vote time.** Use reactions to this post to indicate your preference. Feel free to pick one or more options.

**Option A** - 👍 
![image](https://user-images.githubusercontent.com/36797143/88634393-39c01d00-d0ae-11ea-90ad-eb30e75080f2.png)

**Option B** - 😄 
![image](https://user-images.githubusercontent.com/36797143/88634462-4c3a5680-d0ae-11ea-81a6-8505f3c04731.png)

**Option C** - 🎉 
![image](https://user-images.githubusercontent.com/36797143/88634509-5d836300-d0ae-11ea-9fba-088ad8f7d94d.png)

**Option D** - 😕
![image](https://user-images.githubusercontent.com/36797143/88634615-83a90300-d0ae-11ea-87b2-178cbe1eae79.png)

**Option E** - ❤️ 
![image](https://user-images.githubusercontent.com/36797143/88634644-8efc2e80-d0ae-11ea-8815-eb43152985f4.png)

**Option F** - 🚀 
![image](https://user-images.githubusercontent.com/36797143/88634690-a0453b00-d0ae-11ea-9dbe-259d0ee1b1b1.png)

**Option G** - 👀 
![image](https://user-images.githubusercontent.com/36797143/88634733-acc99380-d0ae-11ea-9526-31ca605de97a.png)

cc @geopandas/collaborators

**Comment by snowman2** [comment]
A,B,D,E:  :+1:

**Comment by martinfleis** [comment]
Ehm, one point regarding options D and E (raised in the spatialpandas repo - https://github.com/holoviz/spatialpandas/issues/39#issuecomment-659527789)

> Bo pointed out that the version above might evoke a swastika, which I now can't unsee.

**Comment by ljwolf** [comment]
I'm all for A.

**Comment by BoBednar** [comment]
> Ehm, one point regarding options D and E (raised in the spatialpandas repo - [holoviz/spatialpandas#39 (comment)](https://github.com/holoviz/spatialpandas/issues/39#issuecomment-659527789))
> 
> > Bo pointed out that the version above might evoke a swastika, which I now can't unsee.


This was regarding a different logo option, I don’t really see a resemblance between the options above and a swastika.

**Comment by martinfleis** [comment]
@BoBednar oh, I thought it was a reference to the negative space in between.

**Comment by jbednar** [comment]
I don't think there's any concern about swastikas for any of options listed here.

**Comment by gusbruschi13** [comment]
Option A !

**Comment by martinfleis** [comment]
Current score is 7 (Option A) - 5 (Option D), counting @ljwolf who expressed his preference only vocally.

@jorisvandenbossche shall we close the poll? You still have time to cast your vote :wink:.

**Comment by TomAugspurger** [comment]
FYI, the pandas core team doesn't have any objections to geopandas using one of these proposed logos.

**Comment by jorisvandenbossche** [comment]
OK, so we have a (slight) majority for option A, and an approval from pandas to use it. So I think that's decided then! Thanks all!

@martinfleis you do a PR to add the logo (and variants) to the repo?

@BoBednar @jbednar thanks a lot for the alternative proposal! (and it was very close .. but yeah, in the end we need to pick one)

**Comment by martinfleis** [comment]
@jorisvandenbossche I'll merge #1564 and make a PR with a page dedicated to logo and colors.

Thanks everyone for participating!
