### ISSUE TITLE
Error (GDAL) while importing GeoPandas in Python3 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by swiss-knight** [geopandas/geopandas#1408]
I met the following error while importing GeoPandas in Python3 on Ubuntu 18.04 after having freshly upgraded GDAL to its version [3.1.0](https://github.com/OSGeo/gdal/releases/tag/v3.1.0):

```
>>> import geopandas as gpd
ERROR 4: Unable to open EPSG support file gcs.csv. 
         Try setting the GDAL_DATA environment variable to point 
         to the directory containing EPSG csv files.
```

Further details here:    
https://github.com/OSGeo/gdal/issues/2500

Is there something I can do?

### EDIT

it seems that both [`fiona`](https://github.com/Toblerity/fiona) and [`rasterio`](https://github.com/mapbox/rasterio) keep installing this file in `/usr/local/lib/python3.6/dist-packages/___/gdal_data/` (where "___" = {"fiona" or "rasterio"}.

I would better go ask there I guess... Because when I do;

```
>>> import rasterio
>>> import geopandas
>>> 
```

or

```
>>> import fiona
ERROR 4: Unable to open EPSG support file gcs.csv.  
         Try setting the GDAL_DATA environment variable to point 
         to the directory containing EPSG csv files.
>>> import geopandas
>>> 
```

GeoPandas is not complaining anymore; in the first case `fiona` does, while in the second case, nobody does.

**Comment by martinfleis** [comment]
Moved to https://github.com/Toblerity/Fiona/issues/897.

**Comment by matthiasdemuzere** [comment]
I am currently facing a similar issue on my ubuntu 18.04 installation.

Geopandas was working fine for me, until I tried to execute [this OSM example](https://colab.research.google.com/drive/1Rpg0uFFMRB8Im3c32lO6J5-821vIt5p5#scrollTo=LWS-aNUJdZT9) on my local machine (including these new installs).

When I import geopandas now, I get the following:
> ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

Even though the GDAL_DATA environmental variable is defined:
> /usr/share/gdal:/home/demuzmp4/.local/lib/python3.6/site-packages/fiona/gdal_data/:/home/demuzmp4/.local/lib/python3.6/site-packages/rasterio/gdal_data/:

If I define GDAL_DATA explicitly again in my code, I do not get the error:
> import os
> os.environ['GDAL_DATA'] = '/usr/share/gdal/'
> import geopandas

Yet when trying to read a shapefile (example the one mentioned in issue [#1276](https://github.com/geopandas/geopandas/issues/1276), or my own data), I get a segmentation fault and my session is killed.

Below the output of geopandas.show_versions().

Any ideas?

> SYSTEM INFO
> -----------
> python     : 3.6.10 (default, Dec 19 2019, 09:29:29)  [GCC 8.3.0]
> executable : /usr/bin/python3
> machine    : Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
> 
> GEOS, GDAL, PROJ INFO
> ---------------------
> GEOS       : 3.7.0
> GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
> GDAL       : 2.4.4
> GDAL data dir: /home/demuzmp4/.local/lib/python3.6/site-packages/fiona/gdal_data
> PROJ       : 7.0.1
> PROJ data dir: /home/demuzmp4/.local/lib/python3.6/site-packages/pyproj/proj_dir/share/proj
> 
> PYTHON DEPENDENCIES
> -------------------
> geopandas  : 0.7.0
> pandas     : 1.0.3
> fiona      : 1.8.13.post1
> numpy      : 1.18.4
> shapely    : 1.7.0
> rtree      : 0.9.4
> pyproj     : 2.6.1.post1
> matplotlib : 3.2.1
> mapclassify: 2.2.0
> pysal      : None
> geopy      : 1.22.0
> psycopg2   : 2.8.5 (dt dec pq3 ext lo64)

**Comment by martinfleis** [comment]
Doing that new installation from pip broke your C dependencies. One thing is to have correctly linked GDAL_DATA, other is to have compatible versions. In your case that is likely the issue. I would recommend sticking to a single-source installation, ideally using conda from conda-forge channel.

**Comment by matthiasdemuzere** [comment]
As far as I know, all of this is based on a single source installation (pip). 

I do not use conda (and want to avoid that), as often this messes with other software installs on my linux systems ....

This morning all was working fine. So i am a bit confused why this is no longer the case?

**Comment by jorisvandenbossche** [comment]
Do you still have the output of the upgrade that you did? (to see which libraries actually got upgraded?)

**Comment by martinfleis** [comment]
In that linked notebook, GDAL is apt install while geopandas, which comes with fiona, is pip. So you have GDAL from different source than fiona. Fiona is our link with GDAL.

**Comment by matthiasdemuzere** [comment]
As far as I can see, only one package got upgraded: python3-rtree (see below).
All others where already present on my system?

I do need gdal-bin (from apt), as it is used by example QGIS. 

I just removed all these libraries(including rtree), and installed them again.
`sudo apt-get install qgis python-qgis qgis-plugin-grass (installs gdal-bin as well)`
`pip3 install geopandas fiona rasterio`

Yet I still get the same problem.

> Python 3.6.10 (default, Dec 19 2019, 09:29:29) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: import geopandas                                                                                                                                                                                                                 
> **ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.**
> 
> In [3]: **geopandas.show_versions()**                                                                                                                                                                                                        
> 
> SYSTEM INFO
> -----------
> python     : 3.6.10 (default, Dec 19 2019, 09:29:29)  [GCC 8.3.0]
> executable : /usr/bin/python3
> machine    : Linux-4.15.0-99-generic-x86_64-with-Ubuntu-18.04-bionic
> 
> GEOS, GDAL, PROJ INFO
> ---------------------
> GEOS       : 3.7.0
> GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
> GDAL       : 2.4.4
> GDAL data dir: /home/demuzmp4/.local/lib/python3.6/site-packages/fiona/gdal_data
> PROJ       : 7.0.1
> PROJ data dir: /home/demuzmp4/.local/lib/python3.6/site-packages/pyproj/proj_dir/share/proj
> 
> PYTHON DEPENDENCIES
> -------------------
> geopandas  : 0.7.0
> pandas     : 1.0.3
> fiona      : 1.8.13.post1
> numpy      : 1.18.4
> shapely    : 1.7.0
> rtree      : 0.9.4
> pyproj     : 2.6.1.post1
> matplotlib : 3.2.1
> mapclassify: 2.2.0
> pysal      : None
> geopy      : 1.22.0
> psycopg2   : 2.8.5 (dt dec pq3 ext lo64)
> 
> 2020-05-13 11:20:47 startup archives unpack
> 2020-05-13 11:20:47 install python3-rtree:all <none> 0.8.3+ds-1
> 2020-05-13 11:20:47 status half-installed python3-rtree:all 0.8.3+ds-1
> 2020-05-13 11:20:47 status unpacked python3-rtree:all 0.8.3+ds-1
> 2020-05-13 11:20:47 status unpacked python3-rtree:all 0.8.3+ds-1
> 2020-05-13 11:20:47 startup packages configure
> 2020-05-13 11:20:47 configure python3-rtree:all 0.8.3+ds-1 <none>
> 2020-05-13 11:20:47 status unpacked python3-rtree:all 0.8.3+ds-1
> 2020-05-13 11:20:47 status half-configured python3-rtree:all 0.8.3+ds-1
> 2020-05-13 11:20:48 status installed python3-rtree:all 0.8.3+ds-1

I do see a difference in gdal versions though:
- _gdalinfo --version_: **GDAL 2.4.0, released 2018/12/14**
- _geopandas.show_versions()_: ** GDAL 2.4.4**

Could this be causing these issues?

**Comment by jorisvandenbossche** [comment]
Yes, that can certainly cause issues: if fiona finds/uses a GDAL library with a different version than the GDAL_DATA it finds, that can give problems. 
But that sounds exactly like the orignial issue here, which they are trying to solve in fiona: https://github.com/Toblerity/Fiona/issues/897

> I do not use conda (and want to avoid that), as often this messes with other software installs on my linux systems ....

From my experience, it is actually the other way around. Conda allows me to have completely isolated environments that don't depend on system libraries. 
This way, it actually prevents the exact issue you are having here (a conflict between the GDAL included in the wheel and the system GDAL installed with apt for qgis).

**Comment by matthiasdemuzere** [comment]
Thanks @jorisvandenbossche. Indeed very similar, apart from the fact that I do not get the same behaviour when loading eg. rasterio first resolving the issue.

I also tried the suggested solution in that post, yet it does not work for me.

About anaconda: I've been working with anaconda several times, yet at some point I always run into problems (with other software packages). I can't recall with what exactly, but I just keep making a mental note I should not try this again. So ... not sure if I should do so again this time ....

**Comment by jorisvandenbossche** [comment]
In case you would give conda another try, know that there is "miniconda", which is only a small initial download (not heavy to try out like the full Anaconda)
