### ISSUE TITLE
Geoseries.contains() showing weird behavior on vectorized operation

### ISSUE THREAD

**Issue by pmdbt** [geopandas/geopandas#1422]
Hey guys, not sure if this is a bug or if I'm just using the method incorrectly, but I've encountered a weird error when passing in a Geoseries of Points to see any of those points land within a custom Polygon that's also a Geoseries.

I'm running this on ubuntu linux with python3.7 installed through linuxbrew and geopandas 0.7.0 installed through pip.

```python
# imports
import geopandas as gpd
from shapely.geometry import Point, Polygon
```

I have the following polygon, which is just a custom polygon around the greater Los Angeles area.

```python
BOUNDARY_MAPPING = {
    'los angeles': [
        (-118.8886048, 34.0572105),
        (-117.8663776, 33.5917433),
        (-117.6602834, 33.7974088),
        (-118.3555078, 34.3910458),
        (-118.8886048, 34.0572105)
        ]
    }
```
I then convert this to a geopandas DataFrame within my class's __init__ function.

```python
def __init__(self):
    self.geo_boundary = gpd.GeoDataFrame(
        index=[0],
        geometry=[Polygon(geo_config.BOUNDARY_MAPPING['los angeles'])]
    )
```

which looks like this

```
                                             geometry
0  POLYGON ((-118.88860 34.05721, -117.86638 33.5...
```

I also have a series of points like this (roughly 245k coordinates) called coord_df.

```
                      geometry
0  POINT (-105.25790 40.00899)
1  POINT (-105.24551 39.99726)
2  POINT (-105.22149 40.00450)
3  POINT (-105.24934 40.01547)
4  POINT (-105.25790 40.00899)
...
```

Now, I know factually that some of those 245k points falls within the custom boundary I've defined. I want to use the Geoseries.contains() method for this. Here is my wrapper function:
```python
def filter_coordinates(self, point_series):
    """
    Vectorized method to filter out coordinates that don't fall within a specified polygon boundary.

    Params:
    point_series (Geopandas Geoseries)

    Returns:
    in_bound (Geopandas Geoseries)
    """
    in_bound = self.geo_boundary['geometry'].contains(point_series)
    return in_bound
```

When I call the above function in my execution file, I make sure to pass the Geoseries in:
```python
data['in_bound'] = self.filter_coordinates(coord_df['geometry'])
```
The result is that no errors are thrown and the operation returns a Series object with Boolean values, True if the polygon contains the point or False if it does not. This leads me to think that the .contains() method supports vectorized calculations. But, every time I run this code, the Series object returned has False for all elements, even though I know factually that many of those points are within the boundary.

I test to make sure by using
```python
data['in_bound'].any()
```
and it does return False when I try a vectorized approach. But weirdly, when I use the pd.apply() method, it works as expected. For example:

```python
data['in_bound'] = coord_df['geometry'].apply(self.filter_coordinates)
```

returns the expected result and checking again with the .any() method returns True.

So, I'm pretty confused if I'm just doing something wrong, or if this is not the intended behavior? The reason why I would like to use the vectorized approach is that this is just a test set, when in production, we would need to run this with millions of points at various times and the vectorized approach gives a significant speed advantage over the .apply() method.

**Comment by martinfleis** [comment]
At the moment, this is not a bug but a behaviour of all spatial predicates like `contains` or `intersects`. Contains now does pair-wise check. Rows are matched and only geometries within the same rows are checked against each other.

We are discussing changing this behaviour, because most of the people actually expect the same as you do. See #972 for a bit more context.

To do this check efficiently across millions of points, I would recommend using spatial index in some way.

**Comment by pmdbt** [comment]
@martinfleis thanks for getting back to me so quickly! I'm looking forward to the potential change in the future. In the meantime, I'll take a look at using spatial index for this problem.
