### ISSUE TITLE
Tests fail intermittently due to GeocoderTimedOut error

### ISSUE THREAD

**Issue by perrygeo** [geopandas/geopandas#143]
Occasionally I experience a `geopy.exc.GeocoderTimedOut: Service timed out` exception from the various geocoding services when running tests, both locally and on Travis.

I'm not sure what the options are but we should ensure that a broken third-party web service doesn't break the unit tests. I'm not a big fan of mocking but it might be appropriate here? Or maybe just raise a ` unittest.SkipTest` if we get a `GeocoderTimedOut`?

**Comment by kjordahl** [comment]
Closed by #159.

**Comment by scottstanie** [comment]
Note that this appears to still be happening on the current docs:
https://geopandas.org/geocoding.html
<img width="753" alt="image" src="https://user-images.githubusercontent.com/8291800/78040787-86c8f800-7335-11ea-860d-1c5a08f01c0e.png">

<img width="735" alt="image" src="https://user-images.githubusercontent.com/8291800/78040816-921c2380-7335-11ea-99c5-7835b244f8e7.png">

**Comment by martinfleis** [comment]
Thanks @scottstanie. That sometimes happens, usually it is enough to try it again. So it probably happened when @jorisvandenbossche generated the latest version. Stable docs needs to be regenerated. Docs for master are fine https://geopandas.readthedocs.io/en/latest/geocoding.html.
