### ISSUE TITLE
MAINT: unify spatial index error handling

### ISSUE THREAD

**Issue by adriangb** [geopandas/geopandas#1436]
Currently, there is no unified approach to error handling for empty spatial indexes or lack of a spatail index backend:
- sjoin does it's own check for rtree, this means you need rtree even if you have pygeos!
- overlay and clip do not do any checks, they would fail with something like `None does not have any attribute query_bulk`, which is not very helpful.

Further, when you create a spatial index, if:
- The spatial index is empty, `GeoDataFrame.sindex` gets set to None
- There is not spatial index backend, `GeoDataFrame.sindex` gets set to None and a _warning_ is raised.

I don't particularly like that handling. There is no way to tell what happened, aside from a warning.

I would like to propose the following:
- No modules outside of `sindex` shall check for a spatial index backend. They should just blindly try to access the `sindex` property.
- The `sindex` backends should be instantiated even with no geometries, and should have a `__len__` property that reports 0 when empty (this preserves the `if gdf.sindex:` syntax used in some modules).
- In the case of no spatial index backend, a clear error should be raised by `sindex.*

\* Currently, the error is raised only when a property of the spatial index is accessed (`sindex.intersection`). There are two options with this:
1. Preserve the current behavior, but make the error more useful. This would require setting `GeoDataFrame.sindex` to some non-None value, perhaps a dummy class that raises a user friendly error if any of its methods (`query`, `query_bulk`, etc.) are accessed and always reports a `len` of 0. The big con of this approach is complexity. We'd have to make a dummy class, etc.
2. Raise an error when `GeoDataFrame.sindex` is accessed. This is the lower complexity approach, we just replace what is currently a warning with an error. It would however require either a `try/except` block or an import of `geopandas.sindex.has_sindex` by other modules to handle this error if they want to operate without a spatial index. Currently, all modules that use a spatial index _cannot_ operate without a spatial index, so they would actually not need to do anything.

**Comment by martinfleis** [comment]
Yeah, this does not seem to be very consistent :).

> No modules outside of sindex shall check for a spatial index backend. They should just blindly try to access the sindex property.

This makes sense and allows us to write cleaner code elswhere.

> The sindex backends should be instantiated even with no geometries, and should have a __len__ property that reports 0 when empty (this preserves the if gdf.sindex: syntax used in some modules).

This would be a hard breaking change, which I am not in favour. Even though we do not do that, users might do `gdf.sindex is None` check which would be broken.

I'd do the simple way of providing better error/warning if `sindex` is accessed but is does not exist. We just have to make sure it won't break anything if we raise an error.

**Comment by adriangb** [comment]
I realize that having the `len() == 0` change would be breaking, but I think it would be more consistent with general handling of empty iterables? Like in python if I do `list([])` I get back a `list` object with `len==0`, not `None`. The same applies to `DataFrames`, etc. It's also more explicit as to what happened: you created an empty spatial index.

We might break things for some users, but it would be a simple fix for them: delete 8 characters.

**Comment by martinfleis** [comment]
I agree that empty vs None logic here is not optimal. But this change can be done with deprecation period. First raise warning that None will change to zero length sindex and then change it. No need for a hard breaking change.

**Comment by brendan-ward** [comment]
👍 
> In the case of no spatial index backend, a clear error should be raised by `sindex.*`

Conflating `None` as an indicator of an empty spatial index with a missing backend is not at all ideal here.  Unmet dependencies should raise errors.

A deprecation period seems fine for this, in which case it would be good to get the deprecation warning into 0.8.0.

**Comment by adriangb** [comment]
A deprecation warning seems fine to me. So:

- No backend raises an error (currently a warning, which is followed by some downstream error).
- Empty spatial index raises a deprecation warning and gets set to `None`, in the future will be set to a spatial index instance with `len == 0`.
