### ISSUE TITLE
Can´t make install version 0.7.0 on python 3.7+ it install 0.6.1

### ISSUE THREAD

**Issue by hectorpatino** [geopandas/geopandas#1442]
### System
Windows 10 Home Edition

### Conda Environment
conda version : 4.8.2

### Step 1

I created new environment using conda navigator setting python = 3.8, 
follow the steps described on [installation](https://geopandas.org/install.html), but unfortunaly i get geopandas in version 0.6.1,

### Step 2
Download a 3.8 python interpreter and using pip i try to install geopandas using
`pip install geopandas==0.7.0` but got this

![2020-05-22_16h43_42](https://user-images.githubusercontent.com/64384750/82711580-6c334100-9c4b-11ea-9b24-060d43f27d2b.png)

### Step 3
Try the same but in pycharm, cause i was going crazy, but didn´t work.

#### Why i need 0.7.0?
Because overlay in 0.6.1 doesn´t support clip operation and overlay doesn't support points or linestrings.

**Comment by martinfleis** [comment]
Since you are using `conda`, why are you installing GeoPandas from pip and not using conda (`conda install -c conda-forge geopandas`)? This is an issue with Fiona pip installation, not so much geopandas. One potential workaround might be (I did not test it) using python 3.7 or 3.6 instead of 3.8.

**Comment by hectorpatino** [comment]
I tried `pip` cause `conda` was installing 0.6.1 in my project env, anyway i tried yesterday your suggestion on new python 3.6, 3.7, 3.8 envs and it worked, but i uninstalled GeoPandas in my project env and re-install it but again got 0.6.1. Gonna use one of the new envs, thank you @martinfleis !
