### ISSUE TITLE
Error creating a dataframe with EPSG:32650

### ISSUE THREAD

**Issue by Meresmata** [geopandas/geopandas#1454]
Hi, 

 I tried to create a geodataframe with own data, in the coordinate system EPSG:32650. My data coordinates are based on Sentinel-2 data. I am using the coordinates that are given by the system for the current tile. I wanted to insert my data into the dataframe and than convert into EPSG:4326.

The SRS is: **'+init=epsg:32650 +type=crs'** Which I than concert into a crs with **pyproj.crs.CRS(....)** without an error. Only when I call:

`geopandas.GeoDataFrame(df, geometry=geometry, crs={pyproj.crs.CRS(sys)})`

I get the following error:

> pyproj.exceptions.CRSError: Invalid CRS input: {<Projected CRS: EPSG:32650>
> Name: WGS 84 / UTM zone 50N
> Axis Info [cartesian]:
> - E[east]: Easting (metre)
> - N[north]: Northing (metre)
> Area of Use:
> - name: World - N hemisphere - 114°E to 120°E - by country
> - bounds: (114.0, 0.0, 120.0, 84.0)
> Coordinate Operation:
> - name: UTM zone 50N
> - method: Transverse Mercator
> Datum: World Geodetic System 1984
> - Ellipsoid: WGS 84
> - Prime Meridian: Greenwich
> }

I am using geopandas in version 0.7.0 on windows 64 with an ryzen2400G.

The code is:

```
        for srs in exportable.keys():
            df = pd.DataFrame(data=export_data[srs])

            geometry = geopandas.points_from_xy(df.longitude, df.latitude)
            gdfs.append(geopandas.GeoDataFrame(df, geometry=geometry, crs={pyproj.crs.CRS(sys)}))
```

**Comment by martinfleis** [comment]
Do not pass the CRS as a dict.

`geopandas.GeoDataFrame(df, geometry=geometry, crs=pyproj.crs.CRS(sys))`

**Comment by Meresmata** [comment]
thanks!
