### ISSUE TITLE
CRS is lost when save in BytesIO

### ISSUE THREAD

**Issue by habibutsu** [geopandas/geopandas#1458]
```python
import io
import geopandas as gpd

df = gpd.GeoDataFrame([
    {
        'k': 'v',
        'geometry': None
    }
], crs='epsg:32611')

file_obj = io.BytesIO()
df.to_file(file_obj, driver='GPKG')
file_obj.seek(0)

upd_df = gpd.read_file(file_obj, driver='GPKG')
assert df.crs == upd_df.crs, (str(df.crs), str(upd_df.crs))
```

**Expected behavior**: everything ok
**Actual behavior**: assertion error

```
Traceback (most recent call last):
  File "test_crs.py", line 16, in <module>
    assert df.crs == upd_df.crs, (str(df.crs), str(upd_df.crs))
AssertionError: ('epsg:32611', 'None')
```

**Comment by habibutsu** [comment]
Looks like that `crs` was lost here
https://github.com/geopandas/geopandas/blob/master/geopandas/io/file.py#L255

In corresponding with fiona docs it is required for `w` mode
https://github.com/Toblerity/Fiona/blob/master/fiona/__init__.py#L178

**Comment by jorisvandenbossche** [comment]
Thanks for the report. So this seem to have changed between geopandas 0.6 and 0.7.

cc @snowman2 can you think of a reason why the changes to `crs` handling could cause this? 
We started passing `crs_wkt` keyword instead of `crs` to fiona in `to_file` (to the `fiona.open(..)` function), but so if that is the reason, that sounds more as a fiona bug?

**Comment by snowman2** [comment]
Not sure what is going on here. Sounds like some investigation will be needed. 🤔

**Comment by habibutsu** [comment]
@jorisvandenbossche yes it can be fixed in `fiona`, by some reason when fiona is used memory buffer, it no passing crs_wkt to function `open`, only `crs` ([details](https://github.com/Toblerity/Fiona/blob/master/fiona/__init__.py#L229)).

**Comment by jorisvandenbossche** [comment]
@habibutsu Thanks for the investigation. Can you open an issue at https://github.com/Toblerity/Fiona/issues for this?

**Comment by habibutsu** [comment]
@jorisvandenbossche I created similar bug in fiona [Fiona/issues/907](https://github.com/Toblerity/Fiona/issues/907), but I am not sure that is fiona bug, because in corresponding with [documentation](https://github.com/Toblerity/Fiona/blob/master/fiona/__init__.py#L177) `crs` is required parameter.

**Comment by jorisvandenbossche** [comment]
@habibutsu thanks!

>  am not sure that is fiona bug, because in corresponding with documentation crs is required parameter.

Yes, but it seems that `crs_wkt` should be passed through to `memfile.open` as well, as it acually has this keyword:

https://github.com/Toblerity/Fiona/blob/7f6f9dc3e466036ca196138efc49fc3c281c59b1/fiona/io.py#L31-L33

**Comment by jorisvandenbossche** [comment]
This is fixed on fiona's side (https://github.com/Toblerity/Fiona/pull/908), so closing here
