### ISSUE TITLE
Support for osm.pbf files

### ISSUE THREAD

**Issue by Robinlovelace** [geopandas/geopandas#1459]
I have been testing this package and am wondering if it can read-in `osm.pbf` files using GDAL's [OSM driver](https://gdal.org/drivers/vector/osm.html). I've had a look at the [pydriosm](https://pypi.org/project/pydriosm/) package which looks great but wondering if there's a way to read-in .pbf files directly with `read_file()` having tried successfully with .gpkg files but having got the following message with the `andora.osm.pbf` file from Geofabric (sorry I lack a reproducible example):

```
# Error in py_call_impl(callable, dots$args, dots$keywords) : 
#   DriverError: unsupported driver: 'OSM'
```

**Comment by martinfleis** [comment]
We are using `fiona` to read files and it does not support `OSM` driver. And [according to author](https://gis.stackexchange.com/questions/110943/open-a-osm-pbf-file-with-fiona-in-python#comment156603_110950) it will not support it in the future.

> OGR reads PBF into a temporary SQLite database. This violates my sense of what's appropriate for a library to do and so Fiona is going to keep the OSM driver turned off.

For `pbf` files I would recommend using `[pyrosm](https://pyrosm.readthedocs.io/en/latest/)` package to read them into GeoDataFrame. It is on the to-do list of documentation expansion, so we'll point to it directly in the future.

**Comment by Robinlovelace** [comment]
Great, thanks for the quick-fire reply. I'll check-out `pyrosm`, that looks great.
