### ISSUE TITLE
DOC: sindex documentation missing

### ISSUE THREAD

**Issue by srenoes** [geopandas/geopandas#1479]
sindex apparently can be used separately as well. In general it would be good to have some documentation of it. https://geoffboeing.com/2016/10/r-tree-spatial-index-python/

**Comment by adriangb** [comment]
I was literally about to make an issue for this, thank you @srenoes! @martinfleis feel free to assign this to me, I'll take care of it in the next couple of weeks.

**Comment by martinfleis** [comment]
@adriangb We’re in the middle of documentation restructuring now, so do not start working on it yet. I’ll keep you in mind once new structure is in place.

**Comment by adriangb** [comment]
Just tag me when/if you want me to work on this.
