### ISSUE TITLE
geopandas.to_file drops rows (.geojson files). Fiona or geopandas issue?

### ISSUE THREAD

**Issue by srenoes** [geopandas/geopandas#1480]
Hi,

I am working on OSM data and realised that sometimes for no reason some of the datasets or rows are dropped when saving the geodataframe file as . Even for small amount of datasets

Geometry was ok on those. Master branch. i dont know where to start or how to work around it.

I guess first the problems source has to be located. But it is behind a bunch of code to be able to reproduce. Also I dont know if it is a new issue or if it is old.

Usually saving the files is relatively slow (as they contain a lot of None values--> is that the reason)

How does the writing of geojson files work, or how could you search for obvious spots in the source code that give a clue what actually happens. Is is maybe the __geo__interface method

Any ideas? It is only very few that it drops but I have no idea why... which is a bit annoying

**Comment by martinfleis** [comment]
Can you try to provide a [reproducible example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)? A bit of code loading OSM data and saving them which always fails, so we can debug it?

**Comment by srenoes** [comment]
Ok I'll provide some code that you can run and that drops some of the rows. It just might take a while.
Anyway it only seems to appear with OSM data, though I am not really sure,
First I thought it could be due to some of the OSM geometries being invalid but apparently this is not really related

**Comment by srenoes** [comment]
OK now it works... strange... I guess it somehow relates to some dataframe object that I use in the construction of the geopandas geodataframe. Because in the actual code it is inside a function and thus deleted. Now here in this code it isnt and it works fine:
"import requests
import osm2geojson
import pandas as pd
import geopandas as gpd

server_url='http://overpass-api.de/api/interpreter'
data='[out:json];\n(\nrel(area:3600054224)["admin_level"="6"]["boundary"="administrative"];\n<;\n>;\n);\nout geom;\n'
response = requests.get(server_url,params={'data':data})

shapes=osm2geojson.json2shapes(response.text)#, log_level='INFO')

df=pd.DataFrame(shapes)

dfp=pd.DataFrame([prop for prop in df.properties])
columns=dfp.columns
dfp.columns=['osm_'+column for column in columns]
tags=pd.DataFrame([tag for tag in dfp.osm_tags])        
dfp=dfp.drop('osm_tags',axis=1)
dfp=dfp.join(tags)

gdf=gpd.GeoDataFrame(df,geometry='shape')
gdf=gdf.drop('properties',axis=1).join(dfp)
columns=gdf.columns.to_list()
new_columns=columns[1:]
new_columns.append(columns[0])
gdf=gdf[new_columns]# moves shape column to the end
gdf.crs='EPSG:4326'

print(f'{len(gdf)} datasets before saving.')
gdf.to_file('Adminlevel6_Finland.geojson',driver='GeoJSON')

gdf2=gpd.read_file('Adminlevel6_Finland.geojson')
print(f'{len(gdf2)} datasets after saving and reloading.\n geojson file is missing entries--> Text editor, search for "FI-02"')
for idx,rows in gdf.iterrows():
    isostr=rows['ISO3166-2']
    bool=any(gdf2['ISO3166-2']==isostr)
    if not bool:
        print('Before:')
        print(gdf.loc[gdf['ISO3166-2']==isostr,:])
        print('After:')
        print(gdf2.loc[gdf2['ISO3166-2']==isostr,:])

"

Luckily I read a little here and there in the bug report and somewhere there was something similar.
I'll still cross check what happens if I delete df in the above, and does that make any difference.
Otherwise quite weird that it now doesnt appear where I just copied the code from within functions or actually methods and now it doesnt drop anything

**Comment by srenoes** [comment]
Or actually... it stays in memory as it never vanished from the gdf but it just wasnt there in the geojson file ... I dont really get it what happens... Strange thing. Anyway lets test what happens when I delete df, dfp or tags dataframe before saving

**Comment by srenoes** [comment]
Ok even deleting didnt do anything. And neither when i used functions to reproduce methos and the classes that I normally use. It still is ok and shows 19 before and after...
I have to study a bit further and see if there is some not so obvious problem with my osm related class

**Comment by srenoes** [comment]
Seems like I cannot reproduce it right now. Reason is maybe that the overpass server puts out different data right now. Because sometimes it thinks some counties are inside some level 3 admin boundaries and sometimes not. I have no clue but now it answers correctly and gives the right counties. But sometimes I have to remove some counties that are not inside the adminlevel_3 regions.

Overpass is somehow behaving often quite strangely. Maybe it has something to do with that?
I have not idea.

Is there some tags that would be not allowed (--> column names) for example in form xxx:yyy with a ":" in the middle?  I will look if I can find an example... I noticed it also elsewhere. It threw away buildings when saving them to disk. 

If it is an overpass issue now it should not leading to drops because now overpass works like it should

**Comment by srenoes** [comment]
I could not reproduce the error. I dont know why but with everything I did it did not anymore drop rows. Though I also came accross something where somehow I managed to get a write error with to _file because of numpy.float64 type. Is that interesting enough to study the cricumstances when that happened?
