### ISSUE TITLE
.to_crs no longer working 

### ISSUE THREAD

**Issue by annehulsey** [geopandas/geopandas#1484]
The following code has been working consistently but suddenly stopped working. It may be related to a conda install for orca:

2020-06-22 15:23:31  (rev 10)
     ca-certificates  {2019.8.28 -> 2020.1.1}
     certifi  {2019.9.11 -> 2020.6.20}
     conda  {4.7.12 -> 4.8.3}
     geopandas  {0.4.1 -> 0.6.1}
     matplotlib  {3.1.1 -> 3.2.2}
     openssl  {1.1.1d -> 1.1.1g}
    +matplotlib-base-3.2.2
    +plotly-orca-1.3.1 (plotly)

I reverted to the previous conda revision, including:
    geopandas  {0.6.1 -> 0.4.1 (defaults/noarch)}

I am still unable to use the .to_crs feature due to the following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-24-6084bb4793cf> in <module>
      6 ruptures.crs = original_crs
      7 ruptures.crs
----> 8 ruptures.to_crs(epsg=new_crs)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\geopandas\geodataframe.py in to_crs(self, crs, epsg, inplace)
    441         else:
    442             df = self.copy()
--> 443         geom = df.geometry.to_crs(crs=crs, epsg=epsg)
    444         df.geometry = geom
    445         df.crs = geom.crs

~\AppData\Local\Continuum\anaconda3\lib\site-packages\geopandas\geoseries.py in to_crs(self, crs, epsg)
    302             except TypeError:
    303                 raise TypeError('Must set either crs or epsg for output.')
--> 304         proj_in = pyproj.Proj(self.crs, preserve_units=True)
    305         proj_out = pyproj.Proj(crs, preserve_units=True)
    306         project = partial(pyproj.transform, proj_in, proj_out)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyproj\__init__.py in __new__(self, projparams, preserve_units, **kwargs)
    344             projstring = projparams
    345         else: # projparams a dict
--> 346             projstring = _dict2string(projparams)
    347         # make sure units are meters if preserve_units is False.
    348         if not projstring.count('+units=') and not preserve_units:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pyproj\__init__.py in _dict2string(projparams)
    684     # convert a dict to a proj4 string.
    685     pjargs = []
--> 686     for key,value in projparams.items():
    687         pjargs.append('+'+key+"="+str(value)+' ')
    688     return ''.join(pjargs)

AttributeError: 'int' object has no attribute 'items'

![image](https://user-images.githubusercontent.com/28743653/85343554-00d6cc00-b4a2-11ea-8d4f-91452ccc2323.png)

**Comment by jorisvandenbossche** [comment]
What is the pyproj version that you are using? It might be due to some interaction of the geopandas + pyproj version that this was not supported at some point anymore.

But in any case, I would recommend you to upgrade to geopandas 0.7. Starting in that release, geopandas uses pyproj's CRS objects to manage projections, and I *think* the code you show should work: https://geopandas.readthedocs.io/en/latest/projections.html#upgrading-to-geopandas-0-7-with-pyproj-2-2-and-proj-6

**Comment by martinfleis** [comment]
You probably have an older version of pyproj, which expects that `crs` is passed as a dictionary, not just an EPSG number (current version supports that). 

You have to specify both CRS like this:

```python
original_crs = {'init' :'epsg:4326'}
new_crs = {'init' :'epsg:26910'}
```

But generally, try to update to recent versions if you can.

**Comment by annehulsey** [comment]
Thank you, Joris and Martin, for your responses.

I discovered that part of the issue is my mishmash of pip versus conda installations. I have been using geopandas 0.7.0 all along. The conda version of geopandas was older but the pip install had overwritten it. I think that when I tried to update something else using conda, things got messed up. (I realize that this is a bad way to handle the environments but I don’t currently have the capacity to set up everything again since my PhD dissertation defense is in one month…)

With pip, I have been using geopandas 0.7.0 and pyproj 2.2 (I think). So when I did the conda install, it may have reverted to an old version of pyproj, along with the old version of geopandas.
I have since reverted to the earlier conda environment and then did a full system restore back to June 16th, when everything was working (I am using Windows 10).

In any case, here is my current status:


  1.  I made sure pip had geopandas 0.7.0 and an updated pyproj. It updated to pyproj 2.6.1.post1 and I still got errors, though they were new errors.
  2.  I uninstalled pyproj and reinstalled it as 2.2.0
  3.  I got the same error as with 2.6.1.post1. See the image below
  4.  I see that the conda environment still says geopandas 0.4.1 and pyproj 1.9.6

Do you have any suggestions?
Thanks,
Anne

[cid:image001.png@01D64960.11ABAD00]

**Comment by annehulsey** [comment]
Update, I solved the issue by digging further into how to override the conda install with a pip.

Thanks for helping me figure out that the issue was the geopandas version, allowing me to track down this crude solution.

Anne

From: Anne McLeod Hulsey<mailto:ahulsey@stanford.edu>
Sent: Tuesday, June 23, 2020 1:13 PM
To: geopandas/geopandas<mailto:reply@reply.github.com>; geopandas/geopandas<mailto:geopandas@noreply.github.com>
Cc: Author<mailto:author@noreply.github.com>
Subject: RE: [geopandas/geopandas] .to_crs no longer working (#1484)

Thank you, Joris and Martin, for your responses.

I discovered that part of the issue is my mishmash of pip versus conda installations. I have been using geopandas 0.7.0 all along. The conda version of geopandas was older but the pip install had overwritten it. I think that when I tried to update something else using conda, things got messed up. (I realize that this is a bad way to handle the environments but I don’t currently have the capacity to set up everything again since my PhD dissertation defense is in one month…)

With pip, I have been using geopandas 0.7.0 and pyproj 2.2 (I think). So when I did the conda install, it may have reverted to an old version of pyproj, along with the old version of geopandas.
I have since reverted to the earlier conda environment and then did a full system restore back to June 16th, when everything was working (I am using Windows 10).

In any case, here is my current status:


  1.  I made sure pip had geopandas 0.7.0 and an updated pyproj. It updated to pyproj 2.6.1.post1 and I still got errors, though they were new errors.
  2.  I uninstalled pyproj and reinstalled it as 2.2.0
  3.  I got the same error as with 2.6.1.post1. See the image below
  4.  I see that the conda environment still says geopandas 0.4.1 and pyproj 1.9.6

Do you have any suggestions?
Thanks,
Anne

[cid:image001.png@01D64960.11ABAD00]
