### ISSUE TITLE
Feature request  GeoSeries.plot(self, *args, **kwargs)  add ax keyword and alike?

### ISSUE THREAD

**Issue by srenoes** [geopandas/geopandas#1488]
It would be nice to for example have an 'ax' keyword input for the geoseries plot function.

That would be  similar to geodataframe. plot() function
And similarly some of the other keywords could be added as well, where that makes sense

Consistency

**Comment by srenoes** [comment]
It seems like it already exists. I made some mistake with plotting and thought it doesnt exist, because it is not mentioned in  the docs. GeoSeries.plot(ax=ax) worked.

**Comment by martinfleis** [comment]
It is :) https://geopandas.readthedocs.io/en/latest/reference.html#geopandas.GeoSeries.plot. I'll make sure it is clear from User Guide as well in the future.
