### ISSUE TITLE
DOC: Contributing guides contain links to travis.org that cannot be opened 

### ISSUE THREAD

**Issue by srenoes** [geopandas/geopandas#1491]
Getting started docs  link http://about.travis-ci.org/docs/user/getting-started/   leads to a (probably old) version whose ssl certificate is not ok. Cannot open it. But the other Travis link worked fine

**Comment by srenoes** [comment]
Same problem on travis.org btw. They also put a link to the same address which doesnt work at the moment

**Comment by martinfleis** [comment]
Thanks! `CONTRIBUTING.md` should be generally updated based on https://github.com/geopandas/geopandas/blob/master/doc/source/contributing.rst (or at least linked to it). The link to Travis user guide should in both lead to https://docs.travis-ci.com/user/tutorial/ I guess. It seems that Travis CI changed their documentation recently.

Would you like to fix the link in both files?

**Comment by srenoes** [comment]
> 
> 
> Thanks! `CONTRIBUTING.md` should be generally updated based on https://github.com/geopandas/geopandas/blob/master/doc/source/contributing.rst (or at least linked to it). The link to Travis user guide should in both lead to https://docs.travis-ci.com/user/tutorial/ I guess. It seems that Travis CI changed their documentation recently.
> 
> Would you like to fix the link in both files?

Yeah I can do that.  Are you interested still in the write method for two geometries, or are you rather opting for something more sound? 
At the moment I have it on my master but i guess i will now first reset my master and change only those two files and send a pull only from that...
