### ISSUE TITLE
wrong default projection 

### ISSUE THREAD

**Issue by MAGALLANESJoseManuel** [geopandas/geopandas#1495]
Using QGIS I read a geojson file, and it has a epsg: 3857
When I read in geopandas:
`
import geopandas as gpd

link="https://www.dropbox.com/s/glvfockpk442qpw/WA_County_Boundaries.json?dl=1"

counties= gpd.read_file(link)

counties.plot()
`
![image](https://user-images.githubusercontent.com/7110381/85957925-2575ec80-b957-11ea-81a1-b7cab3f11ce5.png)

I get the epsg: 4326 instean of epsg=3857
I have tried to change the projection but it is not working (to_crs(epsg=3857))
What am I doing wrong?

In R I read:
`
counties=read_sf(link, crs=3857)
counties=st_transform(counties, crs=4326)

`
and I was successful (notice coordinates):
![image](https://user-images.githubusercontent.com/7110381/85957962-6ec63c00-b957-11ea-9e9d-3c2396c84025.png)

**Comment by martinfleis** [comment]
Because you JSON does not have specified CRS, GeoPandas expects that it follows GeoJSON specification which means EPSG:4326. You have to manually assign correct CRS, in this case, and then you can reproject it to lat/long.

```python
counties= gpd.read_file(link)
counties.crs = 3857 # this will override the existing CRS
counties = counties.to_crs(4326)  # this will reproject geometries 
```

Even though I am happy to help here, considering asking "how to" and debugging questions on [StackOverflow.com](https://stackoverflow.com/questions/tagged/geopandas) or [gis.stackexchange.com](https://gis.stackexchange.com) with `geopandas` tag.  Those are better places for that than issue tracker. 😉

**Comment by longavailable** [comment]
I met a related problem, so I post it here although this is closed. Look at my screenshot. My GeoJSON file has an explicit crs, while geopandas minassign it to `EPSG:4326`.
![Image 1](https://user-images.githubusercontent.com/24582280/88201728-1decef00-cc48-11ea-8c39-a6e3e12d0269.png)

- python 3.8.2
- geopandas 0.8.1

**Comment by longavailable** [comment]
GeoJSON file was exported by using QGIS.

**Comment by martinfleis** [comment]
@longavailable I cannot reproduce the issue with GeoPandas 0.8.1, even if I manually reproduce your GeoJSON. Can you show the output of `geopandas.show_versions()`?

**Comment by longavailable** [comment]
Bruce / Xiaolong Liu
刘小龙
 
From: Martin Fleischmann
Date: 2020-07-27 20:05
To: geopandas/geopandas
CC: longavailable; Mention
Subject: Re: [geopandas/geopandas] wrong default projection (#1495)
@longavailable I cannot reproduce the issue with GeoPandas 0.8.1, even if I manually reproduce your GeoJSON. Can you show the output of geopandas.show_versions()?

**Comment by longavailable** [comment]
Actually, all my geojson files by using `read_file()` missed `crs` these days.

![image](https://user-images.githubusercontent.com/24582280/88578523-fd0e0a80-d048-11ea-934a-af17eb6a6e67.png)

I don't know why the GDAL showing above is `2.4.4`. I am sure that the output of `gdalinfo --version` is `3.0.4`.

**Comment by martinfleis** [comment]
@longavailable That will be the cause of the issue most likely. Because the version above is the one GeoPandas sees and uses, so I sense some issue with installation.

**Comment by longavailable** [comment]
@martinfleis You inspired me to check my recent operations. I met the following error about ten days ago:

> ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

And I added `export GDAL_DATA="/usr/local/share/gdal"` to `.zshrc` by following [How to set GDAL_DATA variable?](https://trac.osgeo.org/gdal/wiki/FAQInstallationAndBuilding#HowtosetGDAL_DATAvariable).

It seems this caused a conflict in version identification of GDAL. I reset `GDAL_DATA` variable and pointed it to `/home/bruce/.local/lib/python3.8/site-packages/fiona/gdal_data` just now. 

`crs` property comes back now.

Thanks a lot.
