### ISSUE TITLE
There might be some questions with function "check_geographic_crs"

### ISSUE THREAD

**Issue by Ricco1010** [geopandas/geopandas#1502]
There is a usering warning when I get the centroid. I wanna konw how to aviod this warning message.

Is "if self.crs and self.crs.is_geographic:" correct?

Looking forward to your reply and thanks very much!

**Comment by martinfleis** [comment]
Generating centroid is a distance-based function. As such, it works correctly in a projected plane with units in meters, feet etc. If your geometry is in degrees in geographic projection (i.e. EPSG:4326), your units denote a place on a sphere, not plane. However, GeoPandas treats them as they would be planar, which means that any distance-related operation does not reflect reality and is more or less distorted.

In the latest release, we have added a warning if a user applies a distance-based function to unprojected geometry. In your case, the warning tries to tell you, that the centroid you have generated is likely not precise _spherical_ centroid and you should project your geometries (`.to_crs()`) first to make sure that there is no unwanted distortion of results.

If you want to suppress the warning no matter what, you can do so also, but it is not recommended.

```py
import warnings

warnings.filterwarnings('ignore', 'Geometry is in a geographic CRS', UserWarning)
```

**Comment by Ricco1010** [comment]
Got it, thanks again!
