### ISSUE TITLE
sjoin renames the right index, is this intentional or a result of the requirements?

### ISSUE THREAD

**Issue by srenoes** [geopandas/geopandas#1504]

**Comment by srenoes** [comment]
returned joined geodataframe shows a column with right_index yet one could use the original left index name for that, similar to how the right index name has been kept. 

It does some checking I reckon wether column names can be kept or not, wouldnt that be also a good place to check also the names of the indeces, if they can be kept

In the sjoin.py code it looks like _frame_join tries to rename whenever possible the left and right indexes to "left/right_index" respectively.... and in the end the name of the index is restored from the saved index name from left/right_index_name.

The other index is moved into a column but I think the intention first was first also to rename it. Yet the column name remains as it seems "index_left/right".

Wouldnt it be a good idea to also restore the name for the column?

**Comment by martinfleis** [comment]
Thanks for the notice and ideas. Yes, there is an issue for that already - #846. Feel free to leave your ideas there. I'll close this to avoid duplication.

**Comment by srenoes** [comment]
ah ok didnt notice that
