### ISSUE TITLE
DOC: New structure of GeoPandas.org

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1505]
GeoPandas documentation is getting a new version. Part of it is this proposal for a new structure of geopandas.org. I would like to use this issue for a discussion about the new structure. Once we have an agreement, the new structure will be part of the PR with the new layout.

The key changes proposed here:

1. **New top-level structure** - geopandas.org should be divided into _About_, _Getting Started_, _Documentation_, and _Community_, where Documentation includes both User Guide and API.
2. **API reference** gets pandas-like structure, where each function, class, method and attribute has its own page, instead of a single long page.
3. **New sections** - Apart from making clear how to cite GeoPandas and who is in the core team, we will add _Roadmap_ and _Ecosystem_ pages plus _Advanced guide_ explaining features requiring a bit of prior knowledge.

**Ecosystem**
A new section of documentation should explain the whole Python GeoSpatial upstream and downstream ecosystem, having section talking about shapely, `pyproj` and `fiona`, briefly about raster packages (like `rasterio`) and section talking about packages built on top of geopandas (`movingpandas`, `splot`, `geoplot` etc.)

**Roadmap**
The new section of documentation as a development roadmap (like http://xarray.pydata.org/en/stable/roadmap.html). That should initially talk about a plan towards GeoPandas 1.0 release.

4. **Deprecation of examples** - Examples section will be removed and examples embedded in the User Guide, where most actually belong already. I am still not sure about this change, but it feels more natural to have all how-to information at one place, especially considering the contents of existing examples. I am open to discussion about this, but the difference between an example and user guide page seems to be a bit blurred.

The structure will also be further expanded with additional new pages later this year.

The whole proposed structure is below.

cc @geopandas/collaborators 

<details>

<summary>Proposed structure of geopandas.org</summary>
<br>

_Note: Some parts go into the detail of page sections for clarity, some not (where it is clear)._

- **About**
  - About GeoPandas
  - Roadmap
  - Team
  - Citing
- **Getting Started**
  - Installation
  - Getting started tutorial
- **Documentation**
  - User Guide
    - Data Structures
      - *includes GDF from DF*
    - Reading and Writing Files
    - Indexing and Selecting Data
    - Making Maps
      - Static plotting
        - Basic maps
          - *includes choropleths and contextily*
        - GeoPlot
        - Cartopy
      - Interactive plotting
        - Folium
        - Kepler.gl
        - hvplot
    - Managing Projections
    - Geometric Manipulations
    - Set Operations
      - overlay
      - clip
    - Aggregation with dissolve
    - Merging data
    - Geocoding
  - Advanced Guide
    - Missing and empty geometries
    - Spatial indexing
    - Vectorized operations
  - API Reference
    - GeoSeries
      - General methods and attributes
      - Unary predicates
      - Binary predicates
      - Set-theoretic methods
      - Constructive methods
      - Affine transformations
      - Aggregating methods
      - I/O
        - from_file
        - to_file
        - to_json
      - Projections
        - crs
        - to_crs
        - set_crs
      - Missing values
        - isna
        - notna
        - fillna
      - Plotting
        - plot
      - Spatial index
      - Interface
        - `__geo_interface__`
    - GeoDataFrame
      - I/O
      - Projections
      - Active geometry
        - rename_geometry
        - set_geometry
      - Aggregating and exploding
        - explode
        - dissolve
      - Plotting
      - Spatial index
      - Interface
    - I/O
      - read_file
      - read_parquet
      - read_feather
      - read_postgis
    - Tools
      - sjoin
      - overlay
      - clip
      - Geocoding
        - geocode
        - reverse_geocode
      - points_from_xy
      - collect
      - datasets.get_path
    - Testing
  - Changelog
- **Community**
  - Contributing
  - Ecosystem
  - Code of Conduct

</details>

**Comment by jorisvandenbossche** [comment]
A big +1 for this proposal!

> Deprecation of examples - Examples section will be removed and examples embedded in the User Guide, where most actually belong already. I am still not sure about this change, but it feels more natural to have all how-to information at one place ... the difference between an example and user guide page seems to be a bit blurred.

Yes, the line is indeed not always clear. I am wondering if we can have something "hybrid"? I think that, also in light of avoiding too long pages, it could be useful to keep some examples / how-to's on specific topics (eg "How to plot a GeoDataFrame with ipyleaflet"). Those can be included/referenced as pages in the appropriate sections of the user guide, and in addition we could also still have a single "gallery" page listing all those examples, if we want. 

The question might then be how to organize this in the sphinx site, technically speaking (keep an examples directory with all centralized and reference them from the user guide, or actually putting the relevant examples in the directory close to their related user guide pages).

**Comment by martinfleis** [comment]
> I am wondering if we can have something "hybrid"?

I am not sure about this. 

Where would you draw a line what is an example and what is not? If it uses an external library (ipyleaflet)?

**Comment by jorisvandenbossche** [comment]
(to be clear, I also don't have a clear-cut opinion, I was more brainstorming ;-))

> Where would you draw a line what is an example and what is not?

Examples would typically be more targeted "how-to"s, showing how to achieve some specific goal, and not necessarily try to explain everything in detail or be comprehensive (which would be done by the user guide and/or docstring). (see also https://documentation.divio.com/how-to-guides/) 
Maybe such kind of pages most easily work for visualization stuff, though, and less so for other topics (it's for projects like matplotlib where having an example gallery is really useful IMO).

It for sure is a sometimes blurry line. But also when we put everything as a "user guide page", we will need to decide on how to structure the content, what to split to a separate page, etc

Related to this: in one of the previous discussions regarding examples, the idea was to turn all examples to notebooks and use nbsphinx to include it in the docs (xref https://github.com/geopandas/geopandas/pull/1254). Is your current idea to still keep them as notebooks (and have a mixture of rst files and notebooks in the user guide), or with the deprecation of examples to also have them all in rst files?

**Comment by jorisvandenbossche** [comment]
There are other storage formats for notebooks that could be used (eg one the formats supported by jupytext), although that also gives a barrier to contribution of course, since you need to install an extension to edit them in a jupyter interface. 

Completely converting to notebooks would lose some sphinx features, I think (like easily linking to the reference docs for methods). Unless we would go with something like myst, but that's also again something new to learn for contributors.

**Comment by martinfleis** [comment]
I was thinking about using MyST to keep sphinx features. But I am biased against reStructuredText, so in my eyes, anything else is better :). The optimal from my perspective would be to use MyST Markdown  + MyST Jupyter notebooks, but that might unnecessarily big change (which also requires people to familiarise with MyST to make any changes). Jupytext feels a bit convoluted for docs.

**Comment by martinfleis** [comment]
You can see the documentation following the proposed structure (with examples kept) on https://martinfleis.github.io/geopandas_docs/. It is based on this branch - https://github.com/martinfleis/geopandas/tree/pydata_theme. I have also adapted the original colour scheme to use green proposed in #1405 (both logos with most votes use the same colour, the logo itself is a placeholder until we'll make a decision).

There are some empty pages, which needs to be done, but I needed them now to have a structure in place.

**Comment by jorisvandenbossche** [comment]
> I was thinking about using MyST to keep sphinx features.

I would be fine with trying out MyST ;)

> You can see the documentation following the proposed structure (with examples kept)

Looking good! Open a PR for it? 
(and empty/stub pages can be filled iteratively I think)

I would maybe make the `/documentation` subdir into `/docs`, to keep the url a bit shorter?
