### ISSUE TITLE
Wrong map used for India

### ISSUE THREAD

**Issue by Subhadeep9** [geopandas/geopandas#1510]
The map for India used in Geopandas is wrong. I am adding two pictures. Notice the top left region. The one used in the Google map is the correct one. 
![brave_TWpwxiWe0s](https://user-images.githubusercontent.com/44867453/87065396-9d34f880-c22e-11ea-9e5b-d0962c79eb59.png)
![brave_DqHaTdOGva](https://user-images.githubusercontent.com/44867453/87065415-a02fe900-c22e-11ea-8fd1-dffd36096700.png)

**Comment by martinfleis** [comment]
Thank you for the report. We are using Natural Earth [dataset](https://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/). Kashmir is a disputed area, so the [following disclaimer](https://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/) applies:

> Natural Earth Vector draws boundaries of countries according to defacto status. We show who actually controls the situation on the ground. Please feel free to mashup our disputed areas ([link](https://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-breakaway-disputed-areas/)) theme to match your particular political outlook.

Interesting is that while google.co.in shows the map as above, google.com (in Czech lang) marks the boundary as disputed:

<img width="830" alt="Screenshot 2020-07-09 at 19 00 38" src="https://user-images.githubusercontent.com/36797143/87074251-7e2a6c80-c216-11ea-9eb0-73b19bf84605.png">

Anyway, there is nothing to do regarding this situation in GeoPandas.
