### ISSUE TITLE
ENH: method to estimate UTM zone of a gdf

### ISSUE THREAD

**Issue by knaaptime** [geopandas/geopandas#1528]
following up on [this conversation](https://github.com/UDST/osmnet/issues/19) from awhile ago, I'm curious whether others would find it useful to have something like `estimated_utm` as a property on a GeoDataFrame? (though i'm not picky about property/method/function/nomenclature)

For context, `osmnx` has [this](https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.projection.project_gdf) nifty little function that guesses a gdf's UTM zone using its geographic coordinates. Although it's not perfect, it's super handy when, say, iterating over several gdfs representing different parts of a large country (e.g. metro areas in the USA) and calculating something like the population density in each. It's especially handy given that #1376 isnt available quite yet

i know a handful of packages that implement this function on their own, so seems like there would be a benefit to providing it in a central place like geopandas

**Comment by martinfleis** [comment]
Sounds like a nice idea. It'll soon get complicated with GeoDataFrames spanning across UTM zones, but for a lot of cases, it could work well. Not sure if the estimation itself should be in GeoPandas or in pyproj. They have[ something like that](https://pyproj4.github.io/pyproj/stable/api/crs/crs.html?highlight=utm#pyproj.crs.CRS.utm_zone), but not exactly afaik.

cc @snowman2

**Comment by snowman2** [comment]
This line from osmnx looks particularly useful, but not entirely accurate: https://github.com/gboeing/osmnx/blob/e1bfad35d8591f8b0e71110476b456c2c62d6e08/osmnx/projection.py#L95. I think it would be useful to get the UTM zone from latlon. The UTM package does this as well.

**Comment by snowman2** [comment]
https://github.com/Turbo87/utm

**Comment by snowman2** [comment]
With: https://github.com/pyproj4/pyproj/pull/712

```python
from pyproj import CRS
from pyproj.aoi import AreaOfInterest
from pyproj.database import query_utm_crs_info

centroid = gdf["geometry"].unary_union.centroid
utm_crs_list = query_utm_crs_info(
    datum_name="WGS 84",
    area_of_interest=AreaOfInterest(
        west_lon_degree=centroid.x,
        south_lat_degree=centroid.y,
        east_lon_degree=centroid.x,
        north_lat_degree=centroid.y,
    )
)

utm_crs = CRS.from_epsg(utm_crs_list[0].code)
```

Then. geopandas could add a `to_utm_crs` method or something. Thoughts?

**Comment by martinfleis** [comment]
@snowman2 Great! Any idea when the next release of pyproj with this PR will be out?

We can add a function estimating UTM zone CRS. So in the end you would do `df.to_crs(df.estimate_utm())`.

One note implementation-wise - we should use `total_bounds` to get coordinates, that is way faster than unary_union.

**Comment by snowman2** [comment]
> We can add a function estimating UTM zone CRS. So in the end you would do df.to_crs(df.estimate_utm())

:+1:

> Any idea when the next release of pyproj with this PR will be out?

The next pyproj release depends on PROJ 7.2 https://github.com/pyproj4/pyproj/issues/689 which is due Nov 1 [7.2 milestone](https://github.com/OSGeo/PROJ/milestone/25). So, sometime after that.
