### ISSUE TITLE
Improving reading from remotes and file-like objects

### ISSUE THREAD

**Issue by ian-r-rose** [geopandas/geopandas#1531]
I'm happy to see progress in the ability to load from file-like objects in #1329. I've been interested in improving the ability for geopandas to load from file-like objects, especially those produced by [`fsspec` ](https://filesystem-spec.readthedocs.io), which should increase the universe of storage backends that we can use here. Since `fsspec` and OGR/Fiona have mutually incompatible virtual filesystems and URL compounding schemes, I think that proceeding with file-like objects is probably the best way to have these two libraries talk to each other.

When I looked into this, I found that the code paths for file loading in GeoPandas are a bit muddled, and could probably use some clarification. Here is a brief survey of the different scenarios I've found. The relevant code block is 
https://github.com/geopandas/geopandas/blob/d3228ddb6814515506921ad5c2e6d6f8bd99c9ae/geopandas/io/file.py#L85-L97
I'll be referring to the three branches of this if-elif-else block below.

### Loading a local text file
```python
geopandas.read_file("test.geojson")
```
This is likely the most common usage. It takes the third branch, and fiona opens the file by path.

### Loading a local binary file
```python
geopandas.read_file("gdal_sample.gpkg", driver="GPKG")
```
This also takes the third branch, and fiona opens the file by path.

### Loading a local zip file:
```python
geopandas.read_file("zip://shapefile.zip")
```
This takes the third branch. Note, however, that I need to include the fiona `zip://` scheme to tell fiona to open it as a zipped file. This is unsurprising, except see below.

### Loading a remote text file
```python
geopandas.read_file("https://opendata.arcgis.com/datasets/76104f230e384f38871eb3c4782f903d_13.geojson")
```
This takes the first branch, loading the GeoJSON into a `fiona.BytesCollection`.

### Loading a remote zipped file
```python
geopandas.read_file("https://opendata.arcgis.com/datasets/76104f230e384f38871eb3c4782f903d_13.zip")
```
This takes the first branch. Note the surprising behavior that *this zipped file doesn't need the `zip://` scheme*. As far as I can tell, this is because fiona's `BytesCollection` does some [automagic detection](https://github.com/Toblerity/Fiona/blob/4750ae99119c7bd2bc38d7842fd57c1c2db2cd2e/fiona/collection.py#L533-L536) of a zipped collection of bytes. The difference between URI schemes for remote and local zipped  files is pretty confusing, and not really documented anywhere, I think. Indeed, if I include `zip://` in the URL above, it fails.

### Loading a `StringIO` file-like object
```python
with open("test.geojson", "r") as f:
    gdf = geopandas.read_file(f, driver="GeoJSON")
```
This takes the second branch, as intended by #1329.

### Loading a `BytesIO` file-like object
```python
with open("gdal_sample.gpkg", "rb") as f:
    gdf = geopandas.read_file(f, driver="GPKG")
```
This *does not* take the second branch, as the `instanceof` check only looks for text objects. Instead it takes the third branch, which I think is not intended. However, fiona has some understanding of file-like objects as well, and it works anyways.

### Loading a zipped `BytesIO` file-like object
This may or may not be an important case, but I was unable to get this to work. In the future, I would hope to be able to get this working using `fsspec`.

Okay, so that is a whole lot of different behaviors, including a couple that I think are probably not intended. Additionally, it seems that @sgillies intends to deprecate `BytesCollection` in favor of `MemoryFile` at some point in the future, though I'm not sure when.  I don't know what the best way forward is right now, but I think there are a couple of behaviors that would be good to get right:
1. I think that having a more duck-typed check for file-like objects (e.g., `pandas.api.types.is_file_like()`) is probably worthwhile. Then it might work better for things like `BytesIO` or `fsspec`. Alternatively, maybe fiona's file-like logic is sufficient?
1. Ideally the differences in how zipped shapefiles are handled could be smoothed out, though I'm not sure how right now.

**Comment by martinfleis** [comment]
This is a great analysis! You are right, it is a bit messy, especially the zip inconsistency.

>  think that having a more duck-typed check for file-like objects (e.g., pandas.api.types.is_file_like()) is probably worthwhile. Then it might work better for things like BytesIO or fsspec. Alternatively, maybe fiona's file-like logic is sufficient?

Agree and what you've done so far in #1535 looks good.

> Ideally the differences in how zipped shapefiles are handled could be smoothed out, though I'm not sure how right now.

From the user's perspective, it would be ideal to remove the need of `zip://` prefix (with some compatibility layer to stay consistent with fiona).
