### ISSUE TITLE
Running geopandas on python 2.7-32bits

### ISSUE THREAD

**Issue by awa5114** [geopandas/geopandas#1534]
I need to use geopandas along with `arcpy` for a project as there are a number of difficulties writing to ESRI geodatabases using `fiona`. I use `archook` to import `arcpy`outside of Arcmap.  `arcpy` is only compatible with 32 bit python so I have to do something like this:

```
set CONDA_FORCE_32BIT=1
conda create --name test
conda activate test
conda install python=2
pip install archook
conda install numpy
conda install geopandas
```

This seems to work and I the installation seems to run OK. However as soon as I try to import `geopandas` in this environmentI get an error:

```
Traceback (most recent call last):
....
  File "C:\Users\aboufira\AppData\Local\Continuum\miniconda3\envs\test\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

I understand this is a `fiona` error, but surely there must be a way to install a 32-bit compatible version of geopandas? Could anyone please help? Thanks...

**Comment by martinfleis** [comment]
GeoPandas does not support Python 2.7 anymore. The last version which might run correctly is 0.6.3, so you should try that one.

**Comment by awa5114** [comment]
Never mind... it seems to work if I first install geopandas immediately after I create the fresh environment, then install archook.

numpy, fiona and pandas are geopandas dependencies. It is no use installing them separately if the plan is to use geopandas.
