### ISSUE TITLE
ENH: geopandas.GeoDataFrame.from_dict() could accept crs as parameter

### ISSUE THREAD

**Issue by iboates** [geopandas/geopandas#1540]
Tested on version 0.8.1, the following command:

```
gpd.GeoDataFrame.from_dict(nodes, columns=["geometry"], orient="index", crs=32637)
```

Returns:

```
TypeError: from_dict() got an unexpected keyword argument 'crs'
```

Is this normal? It seems to me it should be able to accept it because `crs` is a typical GeoDataFrame parameter

**Comment by martinfleis** [comment]
`from_dict` is a method inherited from `pandas.DataFrame.from_dict` and as such it does not support `crs` directly. But you are right, that it is a bit unexpected, so we may override it to add crs support.

For now, you will have to specify CRS manually after the creation of GeoDataFrame:

```py
df = df.set_crs(32637)
```

**Comment by Sangarshanan** [comment]
This also means that `from_dict` should be overloaded with a `geometry` argument along with `crs` right? since we don't wanna be assigning crs to geodataframes without a geometry column

I'm planning to work on this if noone else is : )

**Comment by martinfleis** [comment]
> This also means that from_dict should be overloaded with a geometry argument along with crs right?

@Sangarshanan Yes.

> I'm planning to work on this if noone else is : )

Thanks! :)
