### ISSUE TITLE
Create zipped shapefile

### ISSUE THREAD

**Issue by onewhaleid** [geopandas/geopandas#1547]
I am trying to create a zip file containing a shapefile with all the sidecar files. Here is my code:

```py
import shutil
import geopandas as gpd

# Create shapefile in folder 'foo'
geometry = gpd.points_from_xy([0], [0])
df = gpd.GeoDataFrame(geometry=geometry)
df.to_file('foo', driver='ESRI Shapefile')

# Compress folder into 'foo.zip'
shutil.make_archive('foo', 'zip', root_dir='foo')

# Clean up
shutil.rmtree('foo')
```

I get this error:

```py
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-26-7a2029e4f256> in <module>
     11 
     12 # Clean up
---> 13 shutil.rmtree('foo')

~\AppData\Local\Continuum\anaconda3\lib\shutil.py in rmtree(path, ignore_errors, onerror)
    514             # can't continue even if onerror hook returns
    515             return
--> 516         return _rmtree_unsafe(path, onerror)
    517 
    518 # Allow introspection of whether or not the hardening against symlink

~\AppData\Local\Continuum\anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    402         os.rmdir(path)
    403     except OSError:
--> 404         onerror(os.rmdir, path, sys.exc_info())
    405 
    406 # Version using fd-based APIs to protect against races

~\AppData\Local\Continuum\anaconda3\lib\shutil.py in _rmtree_unsafe(path, onerror)
    400                 onerror(os.unlink, fullname, sys.exc_info())
    401     try:
--> 402         os.rmdir(path)
    403     except OSError:
    404         onerror(os.rmdir, path, sys.exc_info())

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'foo'
```

I think this is a problem with `fiona` not closing files inside `foo`. Is this a bug, or am I doing something wrong?

**Comment by martinfleis** [comment]
I don't have a windows machine to reproduce the issue, but your code works on mac.  Since we are using `with fiona.open()` statement, the file should be properly closed. You may want to look into permissions.

**Comment by onewhaleid** [comment]
@jdmcbr I don't have access to the original computer any more.

I just tried the same code snippet on a different computer in a fresh environment, and it did not give any errors. It must have been a quirk in the old environment.

Thank you for following up!

**Comment by jorisvandenbossche** [comment]
Is this something we want to provide as convenience option in `to_file`? 
I regularly find myself creating a zip file in the file browser of the written shapefiles, and an option to do this automatically might be nice.

**Comment by martinfleis** [comment]
> Is this something we want to provide as convenience option in `to_file`?

Good idea. We have better zip handling on reading in #1535 and having a clean way to save to zip would be cool. It is helpful not only for shapefiles but GPKG can also be nicely compressed.
