### ISSUE TITLE
BUG: CRS property is not pyproj.CRS object in empty GeoDataFrame

### ISSUE THREAD

**Issue by habibutsu** [geopandas/geopandas#1548]
```python
import geopandas
import pyproj

df = geopandas.geodataframe.GeoDataFrame(crs='epsg:32638')
# this does not work in versions above 0.8.0
assert type(df.crs) is pyproj.crs.crs.CRS 

df.crs = 'epsg:32638'
# this works in both versions  0.8.0 and 0.7.0
assert type(df.crs) is pyproj.crs.crs.CRS 
```
Expected behavior: everything ok
Actual behavior: AssertionError

This is relevant for version above 0.8.0, for previous version 0.7.0 this code did not raise exception. In according with description for `crs` property return value should be  ``pyproj.CRS``object. As I understand was lost string `self.crs = crs` that invoked corresponded setter for parsing input string.

**Comment by martinfleis** [comment]
In 0.8 is CRS stored on GeometryArray level (primarily), so the fact that there is no geometry causes the issue. But your example should work, so this is a bug. Have you figured out a workaround?

**Comment by jorisvandenbossche** [comment]
Note that when doing the above, you get a deprecation warning about it (as @martinfleis mentioned, the crs is now stored on the array, so if there are no geometries, we can't properly store it, hence that is deprecated):

```
In [3]: df = geopandas.geodataframe.GeoDataFrame(crs='epsg:32638') 
<ipython-input-3-036a6818513a>:1: FutureWarning: Assigning CRS to a GeoDataFrame without a geometry column is now deprecated and will not be supported in the future.
```

---

I assume we should already convert the input to a pyproj.CRS even for the dummy one we keep on the GeoDataFrame as workaround.

**Comment by jorisvandenbossche** [comment]
> so if there are no geometries, we can't properly store it

In principle we could also create an empty GeometryArray, to overcome this limitation?

So if you do `GeoDataFrame`, we could still add an empty "geometry" column (instead of no columns). Although that would probably break other things.
