### ISSUE TITLE
Iso_a3 codes of naturalearth_lowres

### ISSUE THREAD

**Issue by sanojb99** [geopandas/geopandas#1550]
I tried to match an external data set to the `naturalearth_lowres` data set that ships with GeoPandas. I noticed that there is no `iso_a3` code for e.g. France. The `isoa3` code for France is `-99`. To me, using `iso_a3` codes seems to be the most straightforward approach to match country-referenced data sets. Having false or missing entries in a antive GeoPandas data set is quite inconvenient and should be fixed :)

```Python
import geopandas as gpd
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
france = world[world['name'] == 'France']
```

**Comment by brendan-ward** [comment]
See #1041 - this comes from the Natural Earth dataset.

Closing as duplicate.
