### ISSUE TITLE
BUG: legend misplaced in subplots

### ISSUE THREAD

**Issue by gboeing** [geopandas/geopandas#1555]
I'm using v0.8.0. When I plot on multiple subplots and pass `legend_kwds` to `gdf.plot`, it draws all the subplot legends on the same subplot.

This works as expected:

```python
import geopandas as gpd
import matplotlib.pyplot as plt
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
fig, axes = plt.subplots(3, 2, figsize=(8,8))
for ax in axes.flat:
    gdf.plot(ax=ax, column='gdp_md_est', legend=True)
```
![1](https://user-images.githubusercontent.com/4977197/89090446-cccfb000-d357-11ea-8c9f-1505629b4f80.png)

But this draws the legends all on the same subplot:
```python
legend_kwds = {'orientation': 'horizontal'}
fig, axes = plt.subplots(3, 2, figsize=(8,8))
for ax in axes.flat:
    gdf.plot(ax=ax, column='gdp_md_est', legend=True, legend_kwds=legend_kwds)
```
![2](https://user-images.githubusercontent.com/4977197/89090447-ce997380-d357-11ea-9d86-7e5c6fb4edbf.png)

Is this user error or a bug?

**Comment by martinfleis** [comment]
It looks like a bug to me. I am just not sure if it is not a `matplotlib` bug, because we just pass `legend_kwds` to `colorbar`.
