### ISSUE TITLE
Concat two geodataframes = dead kernel

### ISSUE THREAD

**Issue by Instatarama** [geopandas/geopandas#1556]
When calling concat with two geodataframes with a geometry column each the kernel will crash, no error in Jupyter. 

Can avoid this issue by dropping one of the geometry columns. 

gdA and gdB are geodataframes with geometry columns

` # This will crash: 
`    gdf = pd.concat(
`        [gdA.reset_index(drop=True), gdB.loc[idx, :].reset_index(drop=True)], axis=1)`

`   # this will work
`    gdf = pd.concat(
`        [gdA.reset_index(drop=True), gdB.loc[idx, :].reset_index(drop=True).drop('geometry', axis=1)], axis=1)`

Thanks for looking into this, and for building and maintaining a very useful library!

**Comment by martinfleis** [comment]
Thanks for the report. This was already reported in #1230. I assume that the recursion kills the kernel for some reason.
