### ISSUE TITLE
geojsonio in geopandas

### ISSUE THREAD

**Issue by pjsudharshan** [geopandas/geopandas#1558]
It would be great to see the geojsonio features directly in geopandas.
Embedding inside the Jupyter is problematic with geojsonio. Hope it will be dealt with!

**Comment by martinfleis** [comment]
@pjsudharshan Which features exactly would you like to see? To me, it looks that there's an [easy way](https://github.com/jwass/geojsonio.py#goes-great-with-geopandas) to make these two work together. Do you mean just interactive plotting capabilities?

```py
import geopandas as gpd
import geojsonio

states = gpd.read_file('states.geojson')
m_states = states[states['Name'].str.startswith('M')]
geojsonio.display(m_states.to_json())
```

**Comment by pjsudharshan** [comment]
`Geojsonio` doesn't work properly if the file is slightly big (approx. >=15MB). It creates a gist on Github just like [this](https://gist.github.com/pjsudharshan/7234b4c3f92508a502a98c182028c234), but it fails to embed inside Jupyter Notebook and also doesn't display when it automatically gets redirected to [geojson.io](geojson.io) with the command `geojsonio.display` (An [issue ](https://github.com/jwass/geojsonio.py/issues/13) has also been opened regarding this on June 18, 2018).

It would be great to see this display feature directly in geopandas without all these messy creation of Gist on Github. Just a suggestion :)

**Comment by martinfleis** [comment]
I would assume this is now resolved by `explore()`.
