### ISSUE TITLE
BUG: the clip function don't take dynamically the geometry column name  

### ISSUE THREAD

**Issue by wallystart** [geopandas/geopandas#1563]
Hi, today i noticed that the clip function didn't work for me but then i found which was the problem.

Import geodataframes with geometry called "WKT":
```
field_map = pd.read_csv('./field_map.csv')
field_map['WKT'] = field_map['WKT'].apply(wkt.loads)
field_map = gpd.GeoDataFrame(field_map, geometry = 'WKT', crs = {'init': 'epsg:4326'})

print(field_map.columns)

boundary_map = pd.read_csv('./boundary_map.csv')
boundary_map['WKT'] = boundary_map['WKT'].apply(wkt.loads)
boundary_map = gpd.GeoDataFrame(boundary_map, geometry = 'WKT', crs = {'init': 'epsg:4326'})

print(boundary_map.columns)

> Index(['Unnamed: 0', 'IDX', 'Value', 'WKT', 'WKTTypeID', 'IDXmaster'], dtype='object')
> Index(['Unnamed: 0', 'WKT'], dtype='object')

```
Clip the map and plot to validate:
```
clip_map = gpd.clip(field_map, boundary_map)

fig, ax = plt.subplots(figsize=(10,10))
clip_map.plot(ax=ax)
boundary_map.geometry.boundary.plot(ax=ax, color='red')
```
![image](https://user-images.githubusercontent.com/25191329/89591504-baa2b580-d820-11ea-84b0-3f5b41577ef2.png)

it seems that the clip has not worked but if we look at the of clip_map columns we see "WKT" and "geometry"

![image](https://user-images.githubusercontent.com/25191329/89591734-52080880-d821-11ea-8d30-ccb5f95e5f33.png)

**SOLUTION:**
This worked for me, renaming the geometry column as "geometry"

```
field_map = field_map.rename_geometry('geometry')
boundary_map = boundary_map.rename_geometry('geometry')

clip_map = gpd.clip(field_map, boundary_map)

fig, ax = plt.subplots(figsize=(10,10))
clip_map.plot(ax=ax)
boundary_map.geometry.boundary.plot(ax=ax, color='red')
```

![image](https://user-images.githubusercontent.com/25191329/89591886-ba56ea00-d821-11ea-8961-e39db3c8a4c1.png)

The clip function now work correctly
Regards

**Comment by jorisvandenbossche** [comment]
@wallystart Thanks for the report! Yes, `clip` should also work with differently named geometry columns. We probably missed a hard-coded "geometry" somewhere in the implementation.

**Comment by martinfleis** [comment]
> We probably missed a hard-coded "geometry" somewhere in the implementation.

Here
https://github.com/geopandas/geopandas/blob/0b804ea8afc9cf743643016048c65c8b07818af8/geopandas/tools/clip.py#L69
