### ISSUE TITLE
Warning when missing_kwds provided but no areas missing data

### ISSUE THREAD

**Issue by cjw296** [geopandas/geopandas#1565]
If `df` is a GeoDataFrame which has no missing data in `column`, then if I do:

```
df.plot(column=column, 
        missing_kwds={'color': 'lightgrey'},
    )
```
...I get:

```
geopandas/plotting.py:332: UserWarning: The GeoSeries you are attempting to plot is empty. Nothing has been displayed.
```

`plot()` should, instead, just not attempt to plot the empty series when there's no missing data.

Workaround is to omit `missing_kwds` if you know there will be no missing data, but if you're unsure then you have to live with the warning as best I can tell?

**Comment by martinfleis** [comment]
Thanks! You are right, we should check if there are actually any geometries and do not try plot empty series in here:

https://github.com/geopandas/geopandas/blob/0b804ea8afc9cf743643016048c65c8b07818af8/geopandas/plotting.py#L752-L760

The one workaround could be to silence the warning.

```python
import warnings
warnings.filterwarnings("ignore", "The GeoSeries you are attempting", UserWarning)
```

**Comment by cjw296** [comment]
Where would I look for existing test cases to add to for this?

**Comment by martinfleis** [comment]
Missing geometry tests are scattered around in `test_plotting.py`. I think we added them for each geometry types.
