### ISSUE TITLE
geos_c.dll not found  error when import geopandas in python

### ISSUE THREAD

**Issue by garretvo19** [geopandas/geopandas#1567]
Hi,

 I got the following error: 

OSError: Could not find lib geos_c.dll or load any of its variants ['C:\\Users\\garre\\Anaconda3\\Library\\lib\\geos_c.dll'].

when importing geopandas into python. I installed OsGeo4W and copied geos_c.dll into the Anaconda3 library\lib directory. However, the issue still persists. Can anyone help?

**Comment by jorisvandenbossche** [comment]
You will need to give more details on how you installed geopandas. Also, since you are using conda, can you show the output of `conda list` ?

**Comment by garretvo19** [comment]
I use conda list and geopandas is shown in there. I installed using conda install (i.e. conda install geopandas).

**Comment by jorisvandenbossche** [comment]
Can you show the output of conda list?
