### ISSUE TITLE
gpd.read_file(%) kills jupyter kernel

### ISSUE THREAD

**Issue by saguerraty** [geopandas/geopandas#1569]
I´m trying to load a .geojson file that I saved from qgis, and I'm working inside a jupyter notebook with a Anaconda installed version of python, every time I try and run:
`import geopandas as gpd`
`df = gpd.read_file( "file_path")` 
the kernel restarts. 
I've read the fllowing issue but it seems to be unrelated:

- #1113 

Please help :) I clueless to what might be causing this issue
I'm using vscode 1.48.0 as my text editor/ IDE with MacOS catalina 10.15.5 
My anaconda env is set up as follows:

Name                    Version                   Build  Channel
- appnope                   0.1.0                 py38_1001  
- astroid                   2.4.2                    py38_0  
- attrs                     19.3.0                     py_0  
- backcall                  0.2.0                      py_0  
- blas                      1.0                         mkl  
- branca                    0.4.1                      py_0    conda-forge
- brotlipy                  0.7.0           py38haf1e3a3_1000  
- bzip2                     1.0.8                h1de35cc_0  
- ca-certificates           2020.6.24                     0  
- cairo                     1.14.12              hc4e6be7_4  
- certifi                   2020.6.20                py38_0  
- cffi                      1.14.0           py38hb5b8e2f_0  
- chardet                   3.0.4           py38h32f6830_1006    conda-forge
- click                     7.1.2                      py_0  
- click-plugins             1.1.1                      py_0  
- cligj                     0.5.0                    py38_0  
- cryptography              3.0              py38h52adbb4_0    conda-forge
- curl                      7.67.0               ha441bb4_0  
- decorator                 4.4.2                      py_0  
- expat                     2.2.9                hb1e8313_2  
- fiona                     1.8.4            py38h9a122fd_0  
- folium                    0.11.0                     py_0    conda-forge
- fontconfig                2.13.0               h5d5b041_1  
- freetype                  2.10.2               ha233b18_0  
- freexl                    1.0.5                h1de35cc_0  
- gdal                      2.3.3            py38hbe65578_0  
- geojson                   2.5.0                    pypi_0    pypi
- geopandas                 0.6.1                      py_0  
- geos                      3.7.1                h0a44026_0  
- gettext                   0.19.8.1             h15daf44_3  
- giflib                    5.1.4                h1de35cc_1  
- glib                      2.63.1               hd977a24_0  
- h3-py                     3.6.4            py38h11c0d25_0    conda-forge
- hdf4                      4.2.13               h39711bb_2  
- hdf5                      1.10.4               hfa1e0ec_0  
- icu                       58.2                 h0a44026_3  
- idna                      2.10                       py_0  
- intel-openmp              2019.4                      233  
- ipykernel                 5.3.4            py38h5ca1d4c_0  
- ipython                   7.17.0           py38h39e3cac_0  
- ipython_genutils          0.2.0                    py38_0  
- isort                     4.3.21                   py38_0  
- jedi                      0.17.2                   py38_0  
- jinja2                    2.11.2                     py_0  
- jpeg                      9b                   he5867d9_2  
- json-c                    0.13.1               h3efe00b_0  
- jupyter_client            6.1.6                      py_0  
- jupyter_core              4.6.3                    py38_0  
- kealib                    1.4.7                hf5ed860_6  
- krb5                      1.16.4               hddcf347_0  
- lazy-object-proxy         1.4.3            py38h1de35cc_0  
- libboost                  1.67.0               hebc422b_4  
- libcurl                   7.67.0               h051b688_0  
- libcxx                    10.0.0                        1  
- libdap4                   3.19.1               h3d3e54a_0  
- libedit                   3.1.20191231         h1de35cc_1  
- libffi                    3.2.1                h0a44026_6  
- libgdal                   2.3.3                h0950a36_0  
- libgfortran               3.0.1                h93005f0_2  
- libiconv                  1.16                 h1de35cc_0  
- libkml                    1.3.0                hbe12b63_4  
- libnetcdf                 4.6.1                hd5207e6_2  
- libpng                    1.6.37               ha441bb4_0  
- libpq                     11.2                 h051b688_0  
- libsodium                 1.0.18               h1de35cc_0  
- libspatialindex           1.9.3                h0a44026_0  
- libspatialite             4.3.0a              h644ec7d_19  
- libssh2                   1.9.0                ha12b0ac_1  
- libtiff                   4.1.0                hcb84e12_1  
- libxml2                   2.9.10               h3b9e6c8_1  
- lz4-c                     1.9.2                hb1e8313_1  
- markupsafe                1.1.1            py38h1de35cc_1  
- mccabe                    0.6.1                    py38_1  
- mkl                       2019.4                      233  
- mkl-service               2.3.0            py38hfbe908c_0  
- mkl_fft                   1.1.0            py38hc64f4ea_0  
- mkl_random                1.1.1            py38h959d312_0  
- munch                     2.5.0                      py_0  
- ncurses                   6.2                  h0a44026_1  
- numpy                     1.19.1           py38h3b9f5b6_0  
- numpy-base                1.19.1           py38hcfb5961_0  
- openjpeg                  2.3.0                hb95cd4c_1  
- openssl                   1.1.1g               haf1e3a3_1    conda-forge
- overpass                  0.7                      pypi_0    pypi
- pandas                    1.1.0            py38hb1e8313_0  
- parso                     0.7.0                      py_0  
- pcre                      8.44                 hb1e8313_0  
- pexpect                   4.8.0                    py38_1  
- pickleshare               0.7.5                 py38_1001  
- pip                       20.2.2                   py38_0  
- pixman                    0.40.0               haf1e3a3_0  
- poppler                   0.65.0               ha097c24_1  
- poppler-data              0.4.9                         0  
- proj4                     5.2.0                h0a44026_1  
- prompt-toolkit            3.0.5                      py_0  
- psycopg2                  2.8.4            py38ha12b0ac_0  
- ptyprocess                0.6.0                    py38_0  
- pycparser                 2.20                       py_2  
- pygments                  2.6.1                      py_0  
- pylint                    2.5.3                    py38_0  
- pyopenssl                 19.1.0                     py_1  
- pyproj                    1.9.6            py38h9c430a6_0  
- pysocks                   1.7.1                    py38_1  
- python                    3.8.2                hfe9666f_0  
- python-dateutil           2.8.1                      py_0  
- python_abi                3.8                      1_cp38    conda-forge
- pytz                      2020.1                     py_0  
- pyzmq                     19.0.1           py38hb1e8313_1  
- readline                  7.0                  h1de35cc_5  
- requests                  2.24.0                     py_0  
- rtree                     0.9.4                    py38_1  
- setuptools                49.6.0                   py38_0  
- shapely                   1.7.0                    pypi_0    pypi
- six                       1.15.0                     py_0  
- sqlite                    3.32.3               hffcf06c_0  
- tk                        8.6.10               hb0a8c7a_0  
- toml                      0.10.1                     py_0  
- tornado                   6.0.4            py38h1de35cc_1  
- traitlets                 4.3.3                    py38_0  
- urllib3                   1.25.10                    py_0  
- wcwidth                   0.2.5                      py_0  
- wheel                     0.34.2                   py38_0  
- wrapt                     1.11.2           py38h1de35cc_0  
- xerces-c                  3.2.2                h44e365a_0  
- xz                        5.2.5                h1de35cc_0  
- zeromq                    4.3.2                hb1e8313_2  
- zlib                      1.2.11               h1de35cc_3  
- zstd                      1.4.5                h41d2c2f_0

**Comment by martinfleis** [comment]
Before we'll try to debug your issue, can you update GeoPandas to the latest version (0.8.1) and try it again? If you can do it from `conda-forge` (`conda update geopandas -c conda-forge`) channel, that would be ideal.

**Comment by saguerraty** [comment]
I really sorry not to have tried that.
I'm now running geopangas 0.8.1 and the issue I was experiencing is no longer present.
It seems the version of geopandas that the regular anaconda channel is distributing might have an issue, since the version I had before was not from conda-forge
Thanks a lot! :D
