### ISSUE TITLE
BUG: TypeError exception shows the type of the wrong variable

### ISSUE THREAD

**Issue by ocielliottc** [geopandas/geopandas#1570]
https://github.com/geopandas/geopandas/blob/b366d890c35d68a52f7f608e47f00b89eaa85850/geopandas/tools/clip.py#L130

This should reference 'mask' instead of 'gdf'.

**Comment by jorisvandenbossche** [comment]
That's correct, thanks for the notice! 
(and a pull request to fix it is always welcome)

**Comment by gcaria** [comment]
I've created #1598 but I'm guessing it doesn't show up here because I forgot to link the issue in the commit message
