### ISSUE TITLE
DOC: append to a shapefile stored on disk (not in-memory)?

### ISSUE THREAD

**Issue by zeluspudding** [geopandas/geopandas#1571]
Or any other geofile format that is purely a file system object?.. I originally asked this question [here on Stackoverflow](https://stackoverflow.com/q/63459301/3491991) but guidance has been sparse. Hoping coming to the source repo can help. Thanks in advance!

**Comment by martinfleis** [comment]
Yes, any file format which supports appending (and is supported by fiona) can be appended. You just have to specify `mode="a"`.

```python
df.to_file(filename, mode="a")
```

You can check if `a` mode is supported using

```py
import fiona

fiona.supported_drivers
```


This is the current result r-read, a-append, w-write. 
```
{'AeronavFAA': 'r',
 'ARCGEN': 'r',
 'BNA': 'raw',
 'DXF': 'raw',
 'CSV': 'raw',
 'OpenFileGDB': 'r',
 'ESRIJSON': 'r',
 'ESRI Shapefile': 'raw',
 'GeoJSON': 'rw',
 'GeoJSONSeq': 'rw',
 'GPKG': 'rw',
 'GML': 'raw',
 'GPX': 'raw',
 'GPSTrackMaker': 'raw',
 'Idrisi': 'r',
 'MapInfo File': 'raw',
 'DGN': 'raw',
 'PCIDSK': 'r',
 'S57': 'r',
 'SEGY': 'r',
 'SUA': 'r',
 'TopoJSON': 'r'}
```

We should make sure to add this to docs.

**Comment by zeluspudding** [comment]
You are awesome! Thank you so much for your answer @martinfleis! This is closed as far as I'm concerned but I'm leaving it open since I see you're tracking it with the "Documentation" label / may be wanting to close it once this bit has been added to the documentation.
