### ISSUE TITLE
BUG: overlays can create geometry collections dropped with keep_geom_type=True

### ISSUE THREAD

**Issue by jdmcbr** [geopandas/geopandas#1581]
See #1554 for some more discussion. Running `overlay` can result in single `GeometryCollection` objects that consist of a mix of geometry types. When applying the `keep_geom_type=True` argument, _all_ the geometries within the `GeometryCollection` are dropped, rather than just those that don't conform to the original geometry type. As @jorisvandenbossche notes:

> If the overlay of polygon layers results in a GeometryCollection consisting of a polygon and linestring, I would expect it to keep the polygon of it and not only drop the linestring, and not drop the full GeometryCollection?

**Comment by jorisvandenbossche** [comment]
This was closed by https://github.com/geopandas/geopandas/pull/1582 ?

**Comment by jdmcbr** [comment]
Thanks, that's right, I forgot to tag #1582 as closing this.
