### ISSUE TITLE
Error in reading shape file using geopandas through jupyter

### ISSUE THREAD

**Issue by Shado101-afk** [geopandas/geopandas#1585]
hello guys im new to jupyter notebbook and recently when i tried importing geopandas through jupyter i got the following error:

```
OSError                                   Traceback (most recent call last)
<ipython-input-1-a62d01c1d62e> in <module>
----> 1 import geopandas as gpd

~\miniconda3\envs\env_env\lib\site-packages\geopandas\__init__.py in <module>
----> 1 from geopandas._config import options  # noqa
      2 
      3 from geopandas.geoseries import GeoSeries  # noqa
      4 from geopandas.geodataframe import GeoDataFrame  # noqa
      5 from geopandas.array import points_from_xy  # noqa

~\miniconda3\envs\env_env\lib\site-packages\geopandas\_config.py in <module>
    124 use_pygeos = Option(
    125     key="use_pygeos",
--> 126     default_value=_default_use_pygeos(),
    127     doc=(
    128         "Whether to use PyGEOS to speed up spatial operations. The default is True "

~\miniconda3\envs\env_env\lib\site-packages\geopandas\_config.py in _default_use_pygeos()
    110 
    111 def _default_use_pygeos():
--> 112     import geopandas._compat as compat
    113 
    114     return compat.USE_PYGEOS

~\miniconda3\envs\env_env\lib\site-packages\geopandas\_compat.py in <module>
    147 RTREE_GE_094 = False
    148 try:
--> 149     import rtree  # noqa
    150 
    151     HAS_RTREE = True

~\miniconda3\envs\env_env\lib\site-packages\rtree\__init__.py in <module>
----> 1 from .index import Rtree
      2 
      3 from .core import rt
      4 
      5 __version__ = '0.9.3'

~\miniconda3\envs\env_env\lib\site-packages\rtree\index.py in <module>
      4 import pprint
      5 
----> 6 from . import core
      7 
      8 try:

~\miniconda3\envs\env_env\lib\site-packages\rtree\core.py in <module>
    126         rt = _load_library(lib_name, ctypes.cdll.LoadLibrary)
    127     if not rt:
--> 128         raise OSError("could not find or load %s" % lib_name)
    129 
    130 elif os.name == 'posix':

OSError: could not find or load spatialindex_c-64.dll
```

and here is my conda info:

```
(base) C:\Users\DELL>conda info

     active environment : base
    active env location : C:\Users\DELL\miniconda3
            shell level : 1
       user config file : C:\Users\DELL\.condarc
 populated config files : C:\Users\DELL\.condarc
          conda version : 4.8.4
    conda-build version : not installed
         python version : 3.6.10.final.0
       virtual packages :
       base environment : C:\Users\DELL\miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\DELL\miniconda3\pkgs
                          C:\Users\DELL\.conda\pkgs
                          C:\Users\DELL\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\DELL\miniconda3\envs
                          C:\Users\DELL\.conda\envs
                          C:\Users\DELL\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.6.10 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

I would appreciate any help guys

**Comment by jdmcbr** [comment]
@Shado101-afk It looks like you have a mix of packages from different channels, which tends to produce the sort of "dll not found" error that you encountered. Can you try following the instructions in the documentation for [installing geopandas in a clean environment](https://geopandas.org/install.html#creating-a-new-environment)?

**Comment by Shado101-afk** [comment]
> @Shado101-afk It looks like you have a mix of packages from different channels, which tends to produce the sort of "dll not found" error that you encountered. Can you try following the instructions in the documentation for [installing geopandas in a clean environment](https://geopandas.org/install.html#creating-a-new-environment)?

i have tried it but still the same error
 and i have even tried installing anaconda 3 with python3.6 and it worked to import the geopandas but another new error has come:
CPLE_OpenFailedError            Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: '/Documents/Data/DAMSELFISH_distributions.shp' does not exist in the file system, and is not recognized as a supported dataset name.

During handling of the above exception, another exception occurred:

DriverError                     Traceback (most recent call last)
<ipython-input-16-1ed97abf5c2e> in <module>
----> 1 data = gpd.read_file(fp)

~\anaconda3\envs\geopython\lib\site-packages\geopandas\io\file.py in _read_file(filename, bbox, mask, rows, **kwargs)
     94 
     95     with fiona_env():
---> 96         with reader(path_or_bytes, **kwargs) as features:
     97 
     98             # In a future Fiona release the crs attribute of features will

~\anaconda3\envs\geopython\lib\site-packages\fiona\env.py in wrapper(*args, **kwargs)
    396     def wrapper(*args, **kwargs):
    397         if local._env:
--> 398             return f(*args, **kwargs)
    399         else:
    400             if isinstance(args[0], str):

~\anaconda3\envs\geopython\lib\site-packages\fiona\__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    251 
    252         if mode in ('a', 'r'):
--> 253             c = Collection(path, mode, driver=driver, encoding=encoding,
    254                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    255         elif mode == 'w':

~\anaconda3\envs\geopython\lib\site-packages\fiona\collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    152             if self.mode == 'r':
    153                 self.session = Session()
--> 154                 self.session.start(self, **kwargs)
    155             elif self.mode in ('a', 'w'):
    156                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: '/Documents/Data/DAMSELFISH_distributions.shp' does not exist in the file system, and is not recognized as a supported dataset name.
even if the file is present in that locations its hsowing this error some one please help!

**Comment by Shado101-afk** [comment]
this my conda list:
(geopython) C:\Users\DELL>conda list
# packages in environment at C:\Users\DELL\anaconda3\envs\geopython:
#
# Name                    Version                   Build  Channel
argon2-cffi               20.1.0           py38h1e8a9f7_1    conda-forge
attrs                     20.1.0             pyh9f0ad1d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
blas                      1.0                         mkl    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
boost-cpp                 1.72.0               h89d28cc_2    conda-forge
brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
bzip2                     1.0.8                he774522_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cartopy                   0.18.0           py38hb748def_2    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.1           py38hba49e27_0    conda-forge
cfitsio                   3.470                hbbe6aef_6    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              3.0              py38hba49e27_0    conda-forge
curl                      7.71.1               h4b64cdc_5    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
expat                     2.2.9                h33f27b4_2    conda-forge
fiona                     1.8.13           py38hcb65fe8_2    conda-forge
freetype                  2.10.2               hd328e21_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      3.1.2            py38h5f218aa_2    conda-forge
geopandas                 0.8.1                      py_0    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.6.0                h09e6dc1_1    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.65.0               he4de6d7_0    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        1.7.0            py38h32f6830_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
intel-openmp              2019.4                      245
ipykernel                 5.3.4            py38h5ca1d4c_0    conda-forge
ipython                   7.17.0           py38h1cdfbd6_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.17.2           py38h32f6830_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   he774522_0    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
kealib                    1.4.13               h3b59ab9_1    conda-forge
kiwisolver                1.2.0            py38heaebd3c_0    conda-forge
krb5                      1.17.1               hc04afaa_2    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
libcurl                   7.71.1               h4b64cdc_5    conda-forge
libffi                    3.2.1             ha925a31_1007    conda-forge
libgdal                   3.1.2                h132428b_2    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h7e985d0_1011    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_105    conda-forge
libpng                    1.6.37               ha81a0f5_2    conda-forge
libpq                     12.3                 hd9aa61d_0    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            h9ed2f40_1039    conda-forge
libssh2                   1.9.0                hb06d900_5    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h1006b36_2    conda-forge
lz4-c                     1.9.2                h62dcd97_2    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py38h9de7a3e_1    conda-forge
matplotlib                3.3.1                         1    conda-forge
matplotlib-base           3.3.1            py38hfb9ee82_1    conda-forge
mistune                   0.8.4           py38h9de7a3e_1001    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py38hfa6e2cd_0    conda-forge
mkl_fft                   1.1.0            py38hc8d92b1_1    conda-forge
mkl_random                1.1.0            py38he350917_0    conda-forge
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0    conda-forge
nbconvert                 5.6.1            py38h32f6830_1    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
notebook                  6.1.3            py38h32f6830_0    conda-forge
numpy                     1.19.1           py38h72c728b_0    conda-forge
numpy-base                1.18.5           py38hc3f5095_0
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1g               he774522_1    conda-forge
owslib                    0.20.0                     py_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.0            py38h7ae7562_0    conda-forge
pandoc                    2.10.1               he774522_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 h6538335_0    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pillow                    7.2.0            py38h7011068_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
poppler                   0.89.0               h0cd1227_0    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.3                 he14cc48_0    conda-forge
proj                      7.1.0                h7d85306_1    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.6                      py_0    conda-forge
prompt_toolkit            3.0.6                         0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38h5a885fd_1    conda-forge
pyqt                      5.12.3           py38h6538335_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py38h9de7a3e_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.5           h60c2a47_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pywin32                   227              py38hfa6e2cd_0    conda-forge
pywinpty                  0.5.7                    py38_0    conda-forge
pyyaml                    5.3.1            py38h9de7a3e_0    conda-forge
pyzmq                     19.0.2           py38h77b9d75_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
qtconsole                 4.7.6              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.4            py38h7ad75cc_1    conda-forge
scikit-learn              0.23.2           py38hf00eced_0    conda-forge
scipy                     1.5.0            py38h9439919_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h32f6830_0    conda-forge
shapely                   1.7.1            py38hc96c142_0    conda-forge
sip                       4.19.20          py38h6538335_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               he774522_0    conda-forge
statsmodels               0.11.1           py38h1e8a9f7_2    conda-forge
tbb                       2020.1               he980bc4_0    conda-forge
terminado                 0.8.3            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tiledb                    2.0.8                h71c485d_0    conda-forge
tk                        8.6.10               he774522_0    conda-forge
tornado                   6.0.4            py38hfa6e2cd_0    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1            py38h32f6830_1    conda-forge
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
winpty                    0.4.3                         4    conda-forge
xerces-c                  3.2.3                ha925a31_1    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zeromq                    4.3.2                ha925a31_3    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h62dcd97_1007    conda-forge
zstd                      1.4.5                h1f3a1b7_2    conda-forge

(geopython) C:\Users\DELL>

**Comment by jorisvandenbossche** [comment]
The error message indicates that it doesn't find  '/Documents/Data/DAMSELFISH_distributions.shp'. You might need to specify it with an absolute path (starting with C:\)

**Comment by Shado101-afk** [comment]
> The error message indicates that it doesn't find '/Documents/Data/DAMSELFISH_distributions.shp'. You might need to specify it with an absolute path (starting with C:)

oh ok thanks will try it and let u know@jorisvandenbossche

**Comment by Shado101-afk** [comment]
> > The error message indicates that it doesn't find '/Documents/Data/DAMSELFISH_distributions.shp'. You might need to specify it with an absolute path (starting with C:)

CPLE_OpenFailedError            Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: C:/Documents/Data/DAMSELFISH_distributions.shp: No such file or directory

During handling of the above exception, another exception occurred:

DriverError                     Traceback (most recent call last)
<ipython-input-27-1ed97abf5c2e> in <module>
----> 1 data = gpd.read_file(fp)

~\anaconda3\envs\geopython\lib\site-packages\geopandas\io\file.py in _read_file(filename, bbox, mask, rows, **kwargs)
     94 
     95     with fiona_env():
---> 96         with reader(path_or_bytes, **kwargs) as features:
     97 
     98             # In a future Fiona release the crs attribute of features will

~\anaconda3\envs\geopython\lib\site-packages\fiona\env.py in wrapper(*args, **kwargs)
    396     def wrapper(*args, **kwargs):
    397         if local._env:
--> 398             return f(*args, **kwargs)
    399         else:
    400             if isinstance(args[0], str):

~\anaconda3\envs\geopython\lib\site-packages\fiona\__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    251 
    252         if mode in ('a', 'r'):
--> 253             c = Collection(path, mode, driver=driver, encoding=encoding,
    254                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    255         elif mode == 'w':

~\anaconda3\envs\geopython\lib\site-packages\fiona\collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    152             if self.mode == 'r':
    153                 self.session = Session()
--> 154                 self.session.start(self, **kwargs)
    155             elif self.mode in ('a', 'w'):
    156                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: C:/Documents/Data/DAMSELFISH_distributions.shp: No such file or directory
 
I have tried as u told but im still getting this same error@jorisvandenbossche

**Comment by Shado101-afk** [comment]
> @Shado101-afk I had the same issue. What worked for me was manually downloading the Rtree wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/ ; in your case download the Rtree‑0.9.4‑cp36‑cp36m‑win_amd64.whl (python 3.6 64 bit) and then pip install this .whl file. I was able to then import geopandas

ok thanks will try and let u know

**Comment by Shado101-afk** [comment]
> > @Shado101-afk I had the same issue. What worked for me was manually downloading the Rtree wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/ ; in your case download the Rtree‑0.9.4‑cp36‑cp36m‑win_amd64.whl (python 3.6 64 bit) and then pip install this .whl file. I was able to then import geopandas


when i did pip install of that file it said it had already installed :

(py_env) C:\Users\DELL>pip install Rtree-0.9.4-cp36-cp36m-win_amd64.whl
WARNING: Requirement 'Rtree-0.9.4-cp36-cp36m-win_amd64.whl' looks like a filename, but the file does not exist
Requirement already satisfied: Rtree==0.9.4 from file:///C:/Users/DELL/Rtree-0.9.4-cp36-cp36m-win_amd64.whl in c:\users\dell\anaconda3\envs\py_env\lib\site-packages (0.9.4)
Requirement already satisfied: setuptools in c:\users\dell\anaconda3\envs\py_env\lib\site-packages (from Rtree==0.9.4) (49.6.0.post20200814)

**Comment by Shado101-afk** [comment]
and now my issue is that jupyter notebook is showing this error when im trying to read shapefile from the geopandas:
---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: C:/Documents/Data/DAMSELFISH_distributions.shp: No such file or directory

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
<ipython-input-3-1ed97abf5c2e> in <module>
----> 1 data = gpd.read_file(fp)

~\anaconda3\envs\py_env\lib\site-packages\geopandas\io\file.py in _read_file(filename, bbox, mask, rows, **kwargs)
     94 
     95     with fiona_env():
---> 96         with reader(path_or_bytes, **kwargs) as features:
     97 
     98             # In a future Fiona release the crs attribute of features will

~\anaconda3\envs\py_env\lib\site-packages\fiona\env.py in wrapper(*args, **kwargs)
    396     def wrapper(*args, **kwargs):
    397         if local._env:
--> 398             return f(*args, **kwargs)
    399         else:
    400             if isinstance(args[0], str):

~\anaconda3\envs\py_env\lib\site-packages\fiona\__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    252         if mode in ('a', 'r'):
    253             c = Collection(path, mode, driver=driver, encoding=encoding,
--> 254                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    255         elif mode == 'w':
    256             if schema:

~\anaconda3\envs\py_env\lib\site-packages\fiona\collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    152             if self.mode == 'r':
    153                 self.session = Session()
--> 154                 self.session.start(self, **kwargs)
    155             elif self.mode in ('a', 'w'):
    156                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: C:/Documents/Data/DAMSELFISH_distributions.shp: No such file or directory

**Comment by martinfleis** [comment]
> DriverError: C:/Documents/Data/DAMSELFISH_distributions.shp: No such file or directory

Your file does not exist in the path you specified. The same applies to the wheel above. Make sure that you are passing a correct path to your file.

**Comment by Kshitijpawar** [comment]
> > > @Shado101-afk I had the same issue. What worked for me was manually downloading the Rtree wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/ ; in your case download the Rtree‑0.9.4‑cp36‑cp36m‑win_amd64.whl (python 3.6 64 bit) and then pip install this .whl file. I was able to then import geopandas
> 
> when i did pip install of that file it said it had already installed :
> 
> (py_env) C:\Users\DELL>pip install Rtree-0.9.4-cp36-cp36m-win_amd64.whl
> WARNING: Requirement 'Rtree-0.9.4-cp36-cp36m-win_amd64.whl' looks like a filename, but the file does not exist
> Requirement already satisfied: Rtree==0.9.4 from file:///C:/Users/DELL/Rtree-0.9.4-cp36-cp36m-win_amd64.whl in c:\users\dell\anaconda3\envs\py_env\lib\site-packages (0.9.4)
> Requirement already satisfied: setuptools in c:\users\dell\anaconda3\envs\py_env\lib\site-packages (from Rtree==0.9.4) (49.6.0.post20200814)

Make sure the wheel file(.whl) is in the same directory where you are running the pip install command i.e., C:\Users\DELL in this case

**Comment by Shado101-afk** [comment]
> > DriverError: C:/Documents/Data/DAMSELFISH_distributions.shp: No such file or directory
> 
> Your file does not exist in the path you specified. The same applies to the wheel above. Make sure that you are passing a correct path to your file.

yeah i have entered the correct path but still showing same error

**Comment by Shado101-afk** [comment]
> > > > @Shado101-afk I had the same issue. What worked for me was manually downloading the Rtree wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/ ; in your case download the Rtree‑0.9.4‑cp36‑cp36m‑win_amd64.whl (python 3.6 64 bit) and then pip install this .whl file. I was able to then import geopandas
> > 
> > 
> > when i did pip install of that file it said it had already installed :
> > (py_env) C:\Users\DELL>pip install Rtree-0.9.4-cp36-cp36m-win_amd64.whl
> > WARNING: Requirement 'Rtree-0.9.4-cp36-cp36m-win_amd64.whl' looks like a filename, but the file does not exist
> > Requirement already satisfied: Rtree==0.9.4 from file:///C:/Users/DELL/Rtree-0.9.4-cp36-cp36m-win_amd64.whl in c:\users\dell\anaconda3\envs\py_env\lib\site-packages (0.9.4)
> > Requirement already satisfied: setuptools in c:\users\dell\anaconda3\envs\py_env\lib\site-packages (from Rtree==0.9.4) (49.6.0.post20200814)
> 
> Make sure the wheel file(.whl) is in the same directory where you are running the pip install command i.e., C:\Users\DELL in this case

yeah i have done it and it is still saying its already installed it.

**Comment by Kshitijpawar** [comment]
the 'could not find spatialindex dll file' error because of the missing dll files in 'C:\Users\<your username>\miniconda3\envs\<your env name>\Lib\site-packages\rtree' folder. Could you check if any dll files exist there and revert?

**Comment by Shado101-afk** [comment]
> the 'could not find spatialindex dll file' error is because of the missing dll files in 'C:\Users<your username>\miniconda3\envs<your env name>\Lib\site-packages\rtree' folder. Could you check if any dll files exist there and revert?

hello , the issue is not the missing ddll file cause i didnt get that error anymore and could import geopandas but the new error ocuured.

The command i used in jupyter was:

In [1]: import geopandas as gpd
In[2]: fp = "Home/Documents/DAMSELFISH_distributions.shp"
In[3]: data = gpd.read_file(fp)

and the Error i got after I entered this command was:

CPLE_OpenFailedError                      Traceback (most recent call last)
fiona/_shim.pyx in fiona._shim.gdal_open_vector()

fiona/_err.pyx in fiona._err.exc_wrap_pointer()

CPLE_OpenFailedError: Home/Documents/DAMSELFISH_distributions.shp: No such file or directory

During handling of the above exception, another exception occurred:

DriverError                               Traceback (most recent call last)
<ipython-input-12-1ed97abf5c2e> in <module>
----> 1 data = gpd.read_file(fp)

~\anaconda3\envs\py_env\lib\site-packages\geopandas\io\file.py in _read_file(filename, bbox, mask, rows, **kwargs)
     94 
     95     with fiona_env():
---> 96         with reader(path_or_bytes, **kwargs) as features:
     97 
     98             # In a future Fiona release the crs attribute of features will

~\anaconda3\envs\py_env\lib\site-packages\fiona\env.py in wrapper(*args, **kwargs)
    396     def wrapper(*args, **kwargs):
    397         if local._env:
--> 398             return f(*args, **kwargs)
    399         else:
    400             if isinstance(args[0], str):

~\anaconda3\envs\py_env\lib\site-packages\fiona\__init__.py in open(fp, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt, **kwargs)
    252         if mode in ('a', 'r'):
    253             c = Collection(path, mode, driver=driver, encoding=encoding,
--> 254                            layer=layer, enabled_drivers=enabled_drivers, **kwargs)
    255         elif mode == 'w':
    256             if schema:

~\anaconda3\envs\py_env\lib\site-packages\fiona\collection.py in __init__(self, path, mode, driver, schema, crs, encoding, layer, vsi, archive, enabled_drivers, crs_wkt, ignore_fields, ignore_geometry, **kwargs)
    152             if self.mode == 'r':
    153                 self.session = Session()
--> 154                 self.session.start(self, **kwargs)
    155             elif self.mode in ('a', 'w'):
    156                 self.session = WritingSession()

fiona/ogrext.pyx in fiona.ogrext.Session.start()

fiona/_shim.pyx in fiona._shim.gdal_open_vector()

DriverError: Home/Documents/DAMSELFISH_distributions.shp: No such file or directory

**Comment by Kshitijpawar** [comment]
i tried to reproduce this error, so I downloaded the .shp file from https://automating-gis-processes.github.io/2016/Lesson2-download-data.html ( correct me if I'm wrong). However doing `data = gpd.read_file('DAMSELFISH_distributions.shp')` didn't throw any errors. Also then I tried reading a file.shp that didn't exist, I got the same error stack as above. So my guess is your file input path is wrong and geopandas is unable to even find the file. Try to run the command from where all the contents of Data.zip are present (.shp, .dbf, .shx etc); if you do change `fp = 'DAMSELFISH_distributions.shp'`.

**Comment by Shado101-afk** [comment]
> i tried to reproduce this error, so I downloaded the .shp file from https://automating-gis-processes.github.io/2016/Lesson2-download-data.html ( correct me if I'm wrong). However doing `data = gpd.read_file('DAMSELFISH_distributions.shp')` didn't throw any errors. Also then I tried reading a file.shp that didn't exist, I got the same error stack as above. So my guess is your file input path is wrong and geopandas is unable to even find the file. Try to run the command from where all the contents of Data.zip are present (.shp, .dbf, .shx etc); if you do change `fp = 'DAMSELFISH_distributions.shp'`.

sorry but im still getting the same error even if i change the file path name like u told me to as fp= 'DAMSELFISH_distributions.shp'. and i had previously extracted the zip file to the folder data using winRAR.anyway thanks for helping me this far and if u could suggest any further solution i would be grateful.

**Comment by martinfleis** [comment]
@Shado101-afk You have to specify the correct path to your file. It is mentioned few times above. We do not know where the file is on your computer, but we do know that it is not here: `"Home/Documents/DAMSELFISH_distributions.shp"` You have to either specify the correct relative path (from your current working directory) or the absolute path (starting with `C:`, like `C:\full\path\to\your\file\DAMSELFISH_distributions.shp`. The error message is clear.

**Comment by Kshitijpawar** [comment]
> DriverError: C:/Documents/Data/DAMSELFISH_distributions.shp: No such file or directory

> and now my issue is that jupyter notebook is showing above error when im trying to read shapefile from the geopandas:

Usually Documents folder is not present in C:/ but in C:/Users/<you username>/Documents.

**Comment by Shado101-afk** [comment]
> > DriverError: C:/Documents/Data/DAMSELFISH_distributions.shp: No such file or directory
> 
> > and now my issue is that jupyter notebook is showing above error when im trying to read shapefile from the geopandas:
> 
> Usually Documents folder is not present in C:/ but in `C:/Users/<your username>/Documents`.

thanks bro i tried changing directory to double // and it worked
