### ISSUE TITLE
Introduce an OpenStreetMap module

### ISSUE THREAD

**Issue by jwass** [geopandas/geopandas#160]
Introduce a GeoPandas OpenStreetMap (OSM) module that can read/query OSM data. The real powerful piece is that it provides a Python interface to the [Overpass API](http://wiki.openstreetmap.org/wiki/Overpass_API) allowing easy, dynamic queries of OSM data, returning output as a `GeoDataFrame`, without having to manage your own OSM database. 

It lives on the `osm` branch now. There is still plenty of work to do which I'll try to capture in the issue.

[Example IPython notebook](http://nbviewer.ipython.org/github/geopandas/geopandas/blob/osm/examples/osm.ipynb) that uses OSM to find how many traffic lights are along an arbitrary running route.

I'd love any feedback here.

Here's the doc to the `query_osm` function.

```
def query_osm(typ, bbox=None, recurse=None, tags='', raw=False, **kwargs):
    """
    Query the Overpass API to obtain OpenStreetMap data.

    See also:
    http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide

    The OSM XML data is parsed into an intermediate set of DataFrames.
    By passing in 'render=False', this will return these DataFrames stored
    as the OSMData namedtuple. If render is True, then the DataFrames
    are built into their corresponding geometries.

    Parameters
    ----------
    typ : {'node', 'way', 'relation'}
        The type of OSM data to query
    bbox : (min lon, min lat, max lon, max lat) bounding box
        Optional bounding box to restrict the query. Unless the query
        is extremely restricted, you usually want to specify this.
        It can be retrieved from GeoPandas objects as 'df.total_bounds' or
        from Shapely objects as 'geom.bounds'
    recurse : {'up, 'down', 'uprel', 'downrel'}
        This is used to get more data than the original query. If 'typ' is
        'way', you'll usually want this set to 'down' which grabs all nodes
        of the matching ways
    tags : string or list of query strings
        See also the OverpassQL (referenced above) for more tag options
        Examples:
            tags='highway'
                Matches objects with a 'highway' tag
            tags='highway=motorway' <-- Matches ob
                Matches objects where the 'highway' tag is 'motorway'
            tags='name~[Mm]agazine'
                Match if the 'name' tag matches the regular expression

            Specify a list of tag requests to match all of them
            tags=['highway', 'name~"^Magazine"']
                Match tags that have 'highway' and where 'name' starts
                with 'Magazine'

    raw : boolean, default False
        Return the raw XML data returned by the request
    render : boolean, default True
        Parse the output and return a final GeoDataFrame

    Returns
    -------
    df - GeoDataFrame
    Note that there's probably a bit more filtering required to get the
    exact desired data. For example if you only want ways, you may want
    to grab only the linestrings like:
        >>> df = df[df.type == 'LineString']

    """
```

**Comment by yeesian** [comment]
Hi, just dropping by to mention that I'm a huge fan of geopandas, and it's great to see things moving along. The ecosystem for geospatial operations in [julia](http://julialang.org/) is primitive, but we do have a basic [OpenStreetMap](https://github.com/tedsteiner/OpenStreetMap.jl) package going, which parses the nodes from osm files, before constructing the road network. From my limited experience, it's worth

- creating a network that is compatible with [networkx](https://networkx.github.io/) and/or [igraph](http://igraph.org/python/).
- being able to parse osm files into GeoDataFrames (maybe through [imposm-parser](https://github.com/omniscale/imposm-parser)?)

Also, the developers of [OpenStreetMap.jl](https://github.com/tedsteiner/OpenStreetMap.jl) (including myself) aren't GIS specialists, and will love to get your input on how we might be able to move things forward, to form a cross-language community for working with geospatial data

cc @tedsteiner @garborg

**Comment by yeesian** [comment]
I should mention: @fscottfoti I've never heard of pandana (and urbansim) before -- the [example notebook](http://nbviewer.ipython.org/github/fscottfoti/pandana_presentation/blob/master/FullExample.ipynb) is *amazing*. It is really exciting to see greater interoperability between both tabular and network representations of geo-data (outside of a RDBMS)!

The one-to-one association of geometry to ids (buildings/zones/regions) breaks down in the presence of relations, which might explain why that aspect of it seems so tricky. It might be a better workflow for the nodes/network/routing to be dealt with by pandana (which in turn outputs (Geo)DataFrames, and possibly other objects, depending on the query?), and for the tabular/relational aspects to be dealt with by geopandas.

**Comment by fscottfoti** [comment]
Cool - yes we're still working on processing OSM into a routable network. In fact @jiffyclub has made some recent improvements: https://github.com/synthicity/pandana/pull/33.  I think your separation of concerns makes a lot of sense.  For now, we've been trying to use points only within Pandana and so depend on Pandas directly rather than GeoPandas.  Someday I expect we'll integrate GeoPandas directly.

**Comment by jwass** [comment]
Hi @yeesian - thanks for dropping by.

The osm module is still on my priority list - but just haven't had the time to continue to work on it (would love for anyone else to help out!). Right now it has the ability to parse OSM XML files directly into GeoDataFrames but could/should probably switch to something like imposm's parser.

Agreed that it should integrate with some routing frameworks... although I'm not sold all of that needs to live within GeoPandas.

One of the things I'm placing a high priority on is the ability to directly call OSM's [Overpass API](http://wiki.openstreetmap.org/wiki/Overpass_API). It removes the annoying workflow of finding/downloading OSM data from somewhere... so you can just dynamically query any parts of OSM you want at any point. And it's updated every few minutes or so I believe.

So you can just do something like:
`roads = osm.query_osm('way', bbox=df.total_bounds, tags='highway')`
to get the roads inside a bounding box.

I've been using that function privately for a while now and find it extremely useful in my own workflows.

**Comment by yeesian** [comment]
Agreed about the Overpass API; it seems to be alot more convenient for GeoPandas to integrate the Overpass API as a first priority. The suggestion to use imposm's parser was from observing [the osm.py file](https://github.com/geopandas/geopandas/blob/7cad7d2dc080859e6eab893e07f759ba805aed12/geopandas/io/osm.py) mirroring our experience of [rolling out our own parser](https://github.com/tedsteiner/OpenStreetMap.jl/pull/55) in julia, and isn't a priority I'm waiting on.

And yup, I didn't notice pandana until today -- it changed [my stance](https://github.com/geopandas/geopandas/issues/160#issuecomment-70764473) regarding the [TODO](https://github.com/geopandas/geopandas/issues/160#issuecomment-53176587): I think the routing/network might be better left to pandana (see previous comment), and for geopandas only deal with those aspects of osm data that are informationally dense (buildings, features, individual nodes, etc).

**Comment by gmorain** [comment]
Hi, this issue is rather old, but I just stumbled upon OSMnx through [Geoff Boeing's blog](http://geoffboeing.com/2016/11/osmnx-python-street-networks/) and it looks awesome !

**Comment by martinfleis** [comment]
At this point, I would argue that all the functionality mentioned above is implemented in `OSMnx`. That returns GeoPandas GeoDataFrames, so introducing OSM module on geopanas would be duplication. Closing the issue as resolved in downstream.

**Comment by LorenzoBottaccioli** [comment]
Hi,

OSMnx is for network analysis and it is not possible to enter a simple query. I believe that it will be very useful to have the module `geopandas_osm` integrated inside `geopandas.io`
For example, we can retrieve information on restaurants, pubs, post office, parks.... this thing can not be queried from `OSMnx`

**Comment by martinfleis** [comment]
@LorenzoBottaccioli You can query POIs through OSMnx - https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.pois.

**Comment by LorenzoBottaccioli** [comment]
@martinfleis I still believe that the possibility to perform a query to overpass directly in geopandas is very helpful and gives more possibilities. What about if in OSMnx I try to get data from power lines?

**Comment by knaaptime** [comment]
you might want to check out the brand new [pyrosm](https://pyrosm.readthedocs.io/en/latest/)

**Comment by LorenzoBottaccioli** [comment]
@knaaptime it is interesting but still, I believe that geopandas_osm with query_osm was the best option for flexibility.
