### ISSUE TITLE
How to plot multiple lists as points in geopandas??

### ISSUE THREAD

**Issue by gmehta1996** [geopandas/geopandas#1601]
I plotted some latitudes and longitudes on a map and below is my code.I had a list with longitudes(long1) and a list with latitudes(lat1)  which I zipped and then plotted in the code. Now I have a set of more latitudes and longitudes (lat2 and long2) which I want to plot on this same map but with different color.How do I plot the lat2,long2 lists in the same code .

```py
long1= [values ]
lat1 = [values ]
file1 = r'C:\Users\wards delimited.shp'
delhi = gpd.read_file(file1)
geometry = [Point(xy) for xy in zip(long1,lat1)]
geo_df = gpd.GeoDataFrame(geometry = geometry)
delhi.crs = {'init':"epsg:4326"}
geo_df.crs = {'init':"epsg:4326"}

ax = delhi.to_crs(epsg=3857).plot(alpha=0.2, color='#e8dfcf', zorder=1)

ax = gpd.GeoSeries(delhi.to_crs(epsg=3857)['geometry'].unary_union).boundary.plot(ax=ax, alpha=0.35, color="#262424",zorder=2)

ax = geo_df.to_crs(epsg=3857).plot(ax = ax, markersize = 10, color = 'red',marker = 'o',label = 'Hero', zorder=3)
ctx.add_basemap(ax,source=ctx.providers.OpenStreetMap.Mapnik)
plt.show()
```

Here is my output:
I want another set of plot points for lat2 and long2  just like these red plot points I plotted using lat1 and long1 list:

![map](https://user-images.githubusercontent.com/63504137/91852327-4c65dd00-ec7e-11ea-8f01-ff2592959d30.png)

**Comment by martinfleis** [comment]
The same way as you did the first one. Note that you should specify `ax` only once and pass it to other plots.

```py
geometry2 = [Point(xy) for xy in zip(long2,lat2)]

geo_df2 = gpd.GeoDataFrame(geometry=geometry2)
geo_df2 = 4326

ax = delhi.to_crs(epsg=3857).plot(alpha=0.2, color='#e8dfcf', zorder=1)

gpd.GeoSeries(delhi.to_crs(epsg=3857)['geometry'].unary_union).boundary.plot(ax=ax, alpha=0.35, color="#262424",zorder=2)

geo_df.to_crs(epsg=3857).plot(ax = ax, markersize = 10, color = 'red',marker = 'o',label = 'Hero', zorder=3)

geo_df2.to_crs(epsg=3857).plot(ax = ax, color = 'blue')
```

Next time, please ask usage questions like this on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).
