### ISSUE TITLE
TST: appending to GeoJSON fails with Fiona 1.8.16

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1606]
Our CI is currently red as the latest release of fiona (1.8.16) broke GeoJSON appending. See Travis - https://travis-ci.org/github/geopandas/geopandas/jobs/724462128#L1980

Not sure if it is something to be fixed here or regression in fiona.

**Comment by snowman2** [comment]
Recent fiona GeoJSON change [here](https://github.com/Toblerity/Fiona/commit/290cdd30601aac773d4eb370c77b864aeeda6541). May or may not be related.

**Comment by snowman2** [comment]
Last working version was `1.8.13.post1`.

Git bisect says this is the commit where the issue started: https://github.com/Toblerity/Fiona/commit/79e1b5a2caf8cdcf525b6ee255215e0ab12dc8fc
