### ISSUE TITLE
BUG: load_file() GeoJSON containing "": .* fails

### ISSUE THREAD

**Issue by omzoqasd** [geopandas/geopandas#1611]
Hi,
using geoJSON with an entry "": "" does not work:
`    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          8.694291999999999,
          49.409639999999996
        ]
      },
      "properties": {
        "": "",
        "@osmId": "node/568461834",
        "@validFrom": "2009-11-22T15:47:35Z",
        "@validTo": "2009-11-22T15:49:21Z",
        "amenity": "cafe",
        "created_by": "iLOE 1.6",
        "name": "St. Anna Chocolaterie"
      }
    }` 

[samplecafe_halfhalfhalfhalfhalfEmpty2.txt](https://github.com/geopandas/geopandas/files/5195853/samplecafe_halfhalfhalfhalfhalfEmpty2.txt)

https://tools.ietf.org/html/rfc7946 
It is valid GeoJSON to have an empty property key

**Comment by tyrasd** [comment]
adding to that, the error message produced in such cases is broken, as the error message references an unrelated field name:

https://github.com/Toblerity/Fiona/blob/779d2c1/fiona/ogrext.pyx#L598-L599

```python
            if not bool(key_b):
                raise ValueError("Invalid field name ref: %s" % key)

            key = key_b.decode(encoding)
```

note that `key` in only set in the line _after_ it was already used in the error message. :see_no_evil: 
this causes either an unrelated (and correct) field to be "blamed" for the error, or causes an `UnboundLocalError: local variable 'key' referenced before assignment` if the data contains only one of these "empty string property keys".

**Comment by martinfleis** [comment]
What would you expect to happen in such a case? Isn't it invalid GeoJSON in fact?

**Comment by tyrasd** [comment]
> What would you expect to happen in such a case?

not sure what you mean, but I'd say that valid input should not cause the library to crash :shrug: – at the very least it should result in a meaningful error message.

oh, I just realize that this might better fit in Fiona's issue tracker, actually: https://github.com/Toblerity/Fiona/issues

**Comment by martinfleis** [comment]
I meant what would be the expected output of this. Could be a meaningful error, but if the input is valid, we should be able to read it. I just don't know how would you like to handle it since it does not have a name nor value, which could be quite problematic in pandas (esp. name).

**Comment by tyrasd** [comment]
I'd say that the output should be the same as what one gets when doing the following:

```python
geopandas.GeoDataFrame({'': [''], 'geometry': [Point(0,0)]})
```

**Comment by snowman2** [comment]
With the fix here: https://github.com/Toblerity/Fiona/pull/955
```python
>>> import geopandas
>>> gdf = geopandas.read_file("samplecafe_halfhalfhalfhalfhalfEmpty2.geojson")
>>> gdf
           @osmId  ...                  geometry
0  node/558798864  ...  POINT (8.69079 49.41474)
1  node/568461834  ...  POINT (8.69429 49.40964)

[2 rows x 24 columns]
>>> gdf.columns
Index(['@osmId', '@validFrom', '@validTo', 'addr:city', 'addr:housenumber',
       'addr:postcode', 'addr:street', 'addr:suburb', 'amenity', 'cuisine',
       'diet:vegan', 'diet:vegetarian', 'name', 'opening_hours',
       'outdoor_seating', 'phone', 'smoking', 'source', 'toilets:wheelchair',
       'website', 'wheelchair', '', 'created_by', 'geometry'],
      dtype='object')
```

**Comment by snowman2** [comment]
The fix has been merged in upstream, so this issue can be closed.
