### ISSUE TITLE
SettingwithCopyWarning for geometry column

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1612]
`0.8.1`

I encountered a situation like this:

```python
import geopandas as gpd
gdf = gpd.read_file(gpd.datasets.get_path('nybb'))

trans_geo = gdf[gdf.BoroName == 'Bronx'].translate(yoff=-10**5)
gdf[gdf.BoroName == 'Bronx'].geometry = trans_geo
```
The above code didn't change the geometry for Bronx and I have to use `.loc` to do so.
```python
gdf.loc[gdf.BoroName == 'Bronx', 'geometry'] = trans_geo
```
However, I didn't get any warning for it. Should there be a SettingwithCopyWarning  or something?

**Comment by martinfleis** [comment]
There is SettingwithCopyWarning, I see it when I run your code. Are you sure your warnings are not filtered? (VS Code does that by default for a reason I never understood).

**Comment by StevenLi-DS** [comment]
@martinfleis Sorry about that. Just ran it in Jupyter Lab and indeed there was a warning...
