### ISSUE TITLE
wrong plot crs (4326 been projected by default?)

### ISSUE THREAD

**Issue by Mingyi1995** [geopandas/geopandas#1622]
I upgraded from 0.4.1 to 0.8.0 and received different results when plotting a data frame in CRS 4326.
`import geopandas as gpd`

`import matplotlib.pyplot as plt`

`gpd.read_file('https://data.cityofnewyork.us/api/geospatial/cwiz-gcty?method=export&format=GeoJSON').plot()`

![image](https://user-images.githubusercontent.com/27841137/93047600-df155d00-f62a-11ea-87ad-c9b3e16cabb6.png)

![image](https://user-images.githubusercontent.com/27841137/93047639-f05e6980-f62a-11ea-80aa-ccb4eb535c61.png)
The second plot seems like been projected to 2263 while the CRS is still 4326.

**Comment by jorisvandenbossche** [comment]
This is expected. It's a new feature to adjust the axis scaling when the GeoDataFrame has a geographic CRS to give a better plot by default, see https://github.com/geopandas/geopandas/pull/1290

If you want to preserve the original, you can specify `aspect="equal"` in the `plot(..)` call.

**Comment by Mingyi1995** [comment]
> This is expected. It's a new feature to adjust the axis scaling when the GeoDataFrame has a geographic CRS to give a better plot by default, see #1290
> 
> If you want to preserve the original, you can specify `aspect="equal"` in the `plot(..)` call.


> This is expected. It's a new feature to adjust the axis scaling when the GeoDataFrame has a geographic CRS to give a better plot by default, see #1290
> 
> If you want to preserve the original, you can specify `aspect="equal"` in the `plot(..)` call.

Thanks! This method works alone. But when it comes together with missing_kwds, still cannot plot in epsg: 4236.

**Comment by martinfleis** [comment]
>  But when it comes together with missing_kwds, still cannot plot in epsg: 4236.

Can you elaborate on what do you mean by that and show a reproducible example?
