### ISSUE TITLE
The 'to_crs' reprojection function raises the known deprecation warning immediately after reading shapefile

### ISSUE THREAD

**Issue by phildias** [geopandas/geopandas#1624]
Hi there,

When I use geopandas to read a specific shapefile and reproject it using the `to_crs` function, I get the known deprecation warning from pyproj regarding the old 'init'-style CRS (see [this issue ](https://github.com/geopandas/geopandas/issues/1213) and [this page](https://geopandas.org/projections.html?) under the *Manually specifying the CRS* heading).

I looked into it and I think I found a clue. Immediately after reading in the shapefile, the `.crs` attribute on the geodataframe returns `{'init': 'epsg:4326'}`. The odd thing here is that I am not manually setting the CRS to be in the old 'init' format. This is being read automatically from the shapefile. The shapefile's original projection data (as found in its `.PRJ` file) is replicated below:

    GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]

Why is this happening? Is the CRS supposed to be read as the old 'init' format?

Thank you!!!

**Comment by martinfleis** [comment]
Hi, which version of GeoPandas do you have? 0.8.1 should never return dictionary as `.crs`.

**Comment by phildias** [comment]
You're right, I'm running version 0.6.1 of geopandas.

I was sure I was using the latest version! Sorry about that.
