### ISSUE TITLE
CI: codecov compatibility with GHA

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1628]
After #1576, `codecov` does not work. See https://github.com/geopandas/geopandas/pull/1576#issuecomment-695351870 for details.

**Comment by jorisvandenbossche** [comment]
It's certainly still running and uploading, see https://codecov.io/gh/geopandas/geopandas

@adriangb the issue is that it no longer puts a comment on PRs?

**Comment by jorisvandenbossche** [comment]
> the issue is that it no longer puts a comment on PRs?

Did it actually do that recently? 

But, it seems it is no longer included in the "Checks status" at the bottom of a PR.

**Comment by adriangb** [comment]
Right, if should do one or the other and seems to be doing neither.
