### ISSUE TITLE
"Best Intersection" Spatial Join

### ISSUE THREAD

**Issue by amichuda** [geopandas/geopandas#1630]
Thank you for this really awesome package. It's been critical for my research! 

I'm currently trying to spatially join two dataframes, but I always have geometries being intersected by more than one geometry in `other`. I don't think this is is an issue with the package but rather with the shapefiles, but I wanted to ask: is there a method that allows for something like a "best intersection?" Something like an intersection where if geometries in one geodataframe intersect with more than one geometry of the other, then the join goes to the geometry of `other` that intersects with the most area?

**Comment by martinfleis** [comment]
> Thank you for this really awesome package. It's been critical for my research!

Thanks!

The function you are describing is currently not implemented as we do not check how big the intersection is at any point. Just whether there is one or not. You would have to implement it yourself. See #1265 for related discussion.

I'll close this in favour of #1265 to avoid duplication. Feel free to post some additional details (or workarounds) there.
