### ISSUE TITLE
QST: ImportWarning

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1635]
For some reason, I keep getting a ImportWarning whenever I import geopandas ('0.8.1')

```
C:\Users\liqia\Anaconda3\lib\importlib\_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
```

**Comment by martinfleis** [comment]
Cany you give us a bit more context? Does in happen in Jupyter, in command line, everywhere? Have you imported something else before that? 

If you use VS Code, PyCharm and similar, is it possible that it is caused by the software or its plugin?

**Comment by StevenLi-DS** [comment]
@martinfleis Just tried. Indeed this only happens in VS code and importing it in jupyter lab has no warning. 

This happens whenever I import geopandas (itself or along with other pkgs)
![image](https://user-images.githubusercontent.com/33796896/94320655-895e8000-ff5b-11ea-83a9-8ce4c14cb6e8.png)

but I do have the following settings for the python extension:
```
    "python.dataScience.runStartupCommands":  [
        "%config Completer.use_jedi = False",
        "import warnings",
        "warnings.simplefilter(action='default')"]
```

**Comment by martinfleis** [comment]
I can't reproduce it in stable nor insiders build. Do you have any plugins which may cause it?

Truth is, that we do not use `__spec__` or `__package__` (refs https://www.python.org/dev/peps/pep-0451/, https://www.python.org/dev/peps/pep-0366/), but it normally does not raise a warning, so it has to be something in your specific environment which triggers that.

**Comment by StevenLi-DS** [comment]
@martinfleis thanks I will take a look and see if the python extension folks have a better idea about this.

**Comment by StevenLi-DS** [comment]
@martinfleis After I changed warnings to default and I also got ImportWarning in Jupyter.

![image](https://user-images.githubusercontent.com/33796896/94324751-4c998580-ff69-11ea-9fc6-9cb1b40d4728.png)

**Comment by martinfleis** [comment]
Can you show `conda list`?

**Comment by StevenLi-DS** [comment]
@martinfleis sorry it is really messy
[conda-list.txt](https://github.com/geopandas/geopandas/files/5295192/conda-list.txt)

**Comment by martinfleis** [comment]
I don't see anything obvious. But I would not be surprised if it was caused by something in your environment, since as you say it is really messy. Have you tried creating a new environment to see if it happens there as well? See our docs: https://geopandas.readthedocs.io/en/latest/getting_started/install.html#creating-a-new-environment

Regarding environments, it is a good practice to work in separate environments, i.e. creating new one for a new project etc. Also, it is highly recommended to stick to a one source of packages as much as you can, optimally `conda-forge`. Mixing packages from pip and conda can cause a lot of disruptions (I am actually surprised that this environment on windows works :)).

**Comment by StevenLi-DS** [comment]
@martinfleis Indeed. I'm aware of those things you mentioned above and I installed python via Anaconda at a time when I don't know much about python. Now it becomes a problem for me. But I have so many things that are already set up and it would take too many efforts to reset everything and I pretty much need it for my work every day. I will definitely find a time to do so.

Thank you for taking a look at it for me and I think it is reasonable to close this issue as you can't repro it on your end. Thanks again.
