### ISSUE TITLE
BUG: geom_type with pygeos master

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1640]
Recent changes in pygeos master caused our tests to fail on `geom_type` checks for None.

https://github.com/geopandas/geopandas/runs/1171292789?check_suite_focus=true

For `None`, pygeos now returns Point instead of None as geometry type. I guess this needs to be fixed in pygeos but worth having an issue here to keep an eye on it. The reason is probably https://github.com/pygeos/pygeos/pull/199

**Comment by jorisvandenbossche** [comment]
Ah, good we catched this. So it's not actually a change in `get_type_id` (that returned -1 before as well), but that the `GeometryType` enum no longer includes that value.

cc @caspervdw Do we want to add back a "missing" enum value for -1 to `GeometryType`, or do we let this as responsibility for the user to deal with the -1 in the output of `get_type_id` ?
