### ISSUE TITLE
BUG: CRS lost after GeoSeries.shift()

### ISSUE THREAD

**Issue by PeterFogh** [geopandas/geopandas#1648]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import geopandas as gpd
print(gpd.__version__)
df = pd.DataFrame(
    {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
     'Country': ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Venezuela'],
     'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
     'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})
gdf = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.Longitude, df.Latitude),
    crs='epsg:4326')
gdf.geometry.distance(gdf.geometry.shift())
```

#### Problem description

The pandas `shift()` method should be supported by geopandas to also copy the CRS - thus, avoiding the missing CRS warning when computing distance.

#### Expected Output

Not missing CRS warning.

#### Output of ``geopandas.show_versions()``

<details>
SYSTEM INFO
-----------
python     : 3.8.2 (default, Mar 26 2020, 15:53:00)  [GCC 7.3.0]
executable : /home/fogh/miniconda3/envs/py38_v3/bin/python
machine    : Linux-5.4.0-48-generic-x86_64-with-glibc2.10

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.0
GEOS lib   : /home/fogh/miniconda3/envs/py38_v3/lib/libgeos_c.so
GDAL       : 3.0.2
GDAL data dir: /home/fogh/miniconda3/envs/py38_v3/share/gdal
PROJ       : 6.2.1
PROJ data dir: /home/fogh/miniconda3/envs/py38_v3/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.1
fiona      : 1.8.13.post1
numpy      : 1.19.1
shapely    : 1.7.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.1
mapclassify: 2.3.0
geopy      : 2.0.0
psycopg2   : None
geoalchemy2: None
pyarrow    : 1.0.1
</details>

**Comment by martinfleis** [comment]
Thanks for the report. I can confirm that after doing `gdf.geometry.shift()`, the resulting geoseries does not have CRS, even on master. This is something we should fix.

**Comment by jorisvandenbossche** [comment]
Thanks for the catch! 

Pandas provides a base implementation for the `shift` method of the array:

https://github.com/pandas-dev/pandas/blob/653f6944eba664d19e8d93e850340ac039ec452e/pandas/core/arrays/base.py#L677-L692

And you can see this creates an "empty" array from scalars, which will not actually preserve the CRS. 

And together with our implementation of `_concat_same_type`:

https://github.com/geopandas/geopandas/blob/aa9f9c1ed8637bf38ea8f8d1a01b4668326e3f01/geopandas/array.py#L992-L1006

which takes the CRS from the first object passed to it, this means we loose the CRS for `shift` with a positive number ..

**Comment by JonnoB** [comment]
I am still getting a warning when using shift.

`
df = pd.DataFrame({'time': ['2022-05-02 01:50:00+0000', '2022-05-02 06:30:00+0000', 
                            '2022-05-02 07:00:00+0000', '2022-05-02 07:30:00+0000', '2022-05-02 08:00:00+0000'], 
 'latitude': [39.65, 39.64, 39.61, 39.49, 39.37], 
 'longitude': [106.04, 106.05, 106.13, 106.20, 106.20]})


gdf = gpd.GeoDataFrame(
   df , geometry=gpd.points_from_xy(df.longitude, df.latitude, crs="EPSG:4326"))

gdf.to_crs(epsg=3310,inplace=True)


gdf.geometry.distance(gdf.geometry.shift())
`

The warning is 
```
/usr/local/lib/python3.11/site-packages/geopandas/array.py:1406: UserWarning: CRS not set for some of the concatenation inputs. Setting output's CRS as NAD83 / California Albers (the single non-null crs provided).
  warnings.warn(
```
The warning disappears if loc is used instead of shift

`gdf.iloc[:-1,:].distance(gdf.loc[1:,:], align = False)`

**Comment by JonnoB** [comment]
I should note the above work around causes issues later in the process and so cannot be used. These issues do not occur when shift is used.

**Comment by martinfleis** [comment]
@JonnoB I can reproduce the issue on the 0.12.2 but the warning no longer appears on main due to changes probably in #2680. So once the 0.13 will come out, it will be solved.

In your case, you can temporarily suppress the warning, the result seems to be correct anyway.
