### ISSUE TITLE
BUG: .attrs not preserved

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1654]
Pandas `DataFrame.attrs` dictionary is lost after slicing (and likely some other operations).

Copying @jorisvandenbossche comments from gitter

> Those attrs are passed through using the `__finalize__` mechanism (so the same as for `_metadata` actually)
but we override `__finalize__`
>
> The pandas implementation is here: https://github.com/pandas-dev/pandas/blob/9cb372376fc78aa66e2559de919592007b74cfaa/pandas/core/generic.py#L5324-L5359
> and pandas added several types of functionality to that recently (to preserve `attrs` but also `flags`)
>
> In the GeoPandas implementation, we have some custom logic for merge and concat (to use the metadata of the first object)
but would need to think that through if this is still needed with the "crs on the array level" change

This works (pandas.DataFrame)

```python
>>> df = pd.DataFrame({'a': range(10)})                                                                                                                                                                       
>>> df.attrs['name'] = "my_name"
>>> df.iloc[:5].attrs
{'name': 'my_name'}
```

This does not (geopandas.GeoDataFrame)

```python
>>>df = gpd.GeoDataFrame({'a': range(10)})                                                                                                                                                                       
>>> df.attrs['name'] = "my_name"
>>> df.iloc[:5].attrs
{}
```

See https://gitter.im/geopandas/geopandas?at=5f85673f02e81701b01b6126 for a relevant discussion.

**Comment by jorisvandenbossche** [comment]
So for reference, the current geopandas implementation of `GeoDataFrame.__finalize__` is here:

https://github.com/geopandas/geopandas/blob/7044aa479dbae72c14dfb647a5a782a01cff81d1/geopandas/geodataframe.py#L1148-L1162
