### ISSUE TITLE
QST: descartes dependency

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1660]
I have a question about the descartes dependency and I wonder if this has something to do with geopandas pypi metadata. 

Whenever I use an online jupyter env like colab or something. I have to pip install descartes after pip install geopandas. 
Does this mean descartes is not included in the geopandas dependency metadata? If so, should it be added it to lile fiona, shapely, etc?

**Comment by martinfleis** [comment]
Descartes and matplotlib are optional dependencies. There are folks who do not use geopandas for plotting and we do now want to force them to install it. However, there was a discussion that this may change in future. We may have `geopandas-base` with the very minimum and `geopandas` which should then come with some optional dependencies as well.

**Comment by StevenLi-DS** [comment]
@martinfleis I wish you guys add it to the requirement in the further since geopandas is a high-level package.

**Comment by jorisvandenbossche** [comment]
I don't think we will add matplotlib as a required dependency any time soon (note that also pandas does not have that as a required dependency), but the actual annoying thing is not having to install matplotlib separately (which many people will have installed anyway), but having to install descartes. And for that we are actually thinking to simply include the code of descartes into geopandas itself, see https://github.com/geopandas/geopandas/issues/1039

**Comment by jorisvandenbossche** [comment]
The mentioned removal of descartes as an optional dependency has been done now (https://github.com/geopandas/geopandas/pull/1677), so closing this issue.
