### ISSUE TITLE
QST: sjoin doesnt work on known intersecting polygons

### ISSUE THREAD

**Issue by ludwighagelstein** [geopandas/geopandas#1663]
I have two polygons and want to do a spatially join the attributes from the landuse_rel to lod2_1 polygon.

`lod2_landuse_a = gpd.sjoin(lod2_1,landuse_rel,how='left',op='intersects',rsuffix='luse')`

It works fine with these two polygons (lod1_1,landuse_rel):
[https://i.stack.imgur.com/0bVRB.png](url)

But when I do the exact same thing with another lod2 polygon (lod2_2,landuse_rel), it doesnt join any attributes, even though `lod2_2.intersects(landuse_rel)` returns `True`:
[https://i.stack.imgur.com/gtAc7.png](url)

How can I solve this?

In this link I put the relevant shapefiles: https://drive.google.com/drive/folders/1C55ewvDi6AAFCGLX8Lbfnyv2jhzPkWbG?usp=sharing

Here are the Polygon coordinates:

landuse_rel.geometry:` 0    POLYGON ((4476190.885 5294958.985, 4476197.645 5294981.272, 4476241.312 5295070.633, 4476241.223 5295070.866, 4476289.669 5295136.702, 4476305.462 5295151.025, 4476325.216 5295168.501, 4476326.360 5295164.393, 4476330.617 5295159.250, 4476335.813 5295154.692, 4476343.146 5295150.604, 4476351.084 5295147.836, 4476359.507 5295148.135, 4476364.660 5295149.582, 4476365.437 5295149.023, 4476369.688 5295146.003, 4476391.786 5295132.204, 4476387.870 5295090.657, 4476404.478 5295090.000, 4476403.034 5295059.374, 4476350.684 5295061.089, 4476314.562 5295062.638, 4476297.859 5295073.036, 4476214.263 5294944.568, 4476190.885 5294958.985)) Name: geometry, dtype: geometry`

lod2_1.geometry: `0    POLYGON Z ((4476390.380 5295101.660 757.840, 4476390.373 5295100.170 757.840, 4476386.170 5295100.173 757.840, 4476381.977 5295100.165 757.840, 4476381.975 5295101.656 757.840, 4476372.119 5295101.669 757.840, 4476372.122 5295107.692 757.840, 4476372.136 5295113.716 757.840, 4476386.374 5295113.694 757.840, 4476391.828 5295113.682 757.840, 4476397.381 5295113.667 757.840, 4476397.388 5295107.662 757.840, 4476397.395 5295101.648 757.840, 4476391.882 5295101.682 757.840, 4476390.380 5295101.660 757.840)) Name: geometry, dtype: geometry`

lod2_2.geometry: ` 0    POLYGON Z ((4476407.045 5295067.191 754.640, 4476406.564 5295061.496 754.640, 4476370.230 5295064.617 754.640, 4476370.054 5295063.163 754.640, 4476360.773 5295064.064 754.640, 4476360.907 5295065.459 754.640, 4476342.745 5295067.005 754.640, 4476342.667 5295065.767 754.640, 4476339.327 5295066.097 754.640, 4476339.404 5295067.315 754.640, 4476321.871 5295068.826 754.640, 4476321.914 5295069.415 754.640, 4476322.911 5295080.413 754.640, 4476345.583 5295078.513 754.640, 4476346.107 5295084.276 754.640, 4476354.975 5295083.552 754.640, 4476355.359 5295088.310 754.640, 4476382.252 5295085.865 754.640, 4476381.837 5295080.828 754.640, 4476408.044 5295078.510 754.640, 4476407.509 5295072.707 754.640, 4476410.341 5295072.447 754.640, 4476409.857 5295066.952 754.640, 4476407.045 5295067.191 754.640)) Name: geometry, dtype: geometry`

**Comment by martinfleis** [comment]
Can you try to provide a minimal reproducible example as in this guide: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports? It is fine to use linked shapefiles, but the complete code you used would help a lot.

**Comment by ludwighagelstein** [comment]
Thanks for the quick reply!

So I traced down the problem:
```
from osgeo import gdal
import geopandas as gpd

lod2 = gpd.read_file('.../problemPoly.shp')

landuse_rel = gpd.read_file('.../landuse_rel.shp') #OSM landuse_a layer

sjoin_out = gpd.sjoin(lod2,landuse_rel,how='left',op='intersects',rsuffix='luse')
print(sjoin_out)
```
doesn't join the attributes of one polygon correctly.
If I remove the `from osgeo import gdal`, it works fine.
.shp files are here: [https://drive.google.com/drive/folders/1C55ewvDi6AAFCGLX8Lbfnyv2jhzPkWbG?usp=sharing](url)

I also tried to reproduce the code without external shapefiles, but then it also works with gdal imported:
```
import geopandas as gpd
import pandas as pd
from shapely import wkt
from osgeo import gdal

df=pd.DataFrame({'fclass':['industrial'],'coords':['POLYGON ((4476190.885 5294958.985, 4476197.645 5294981.272, 4476241.312 5295070.633, 4476241.223 5295070.866, 4476289.669 5295136.702, 4476305.462 5295151.025, 4476325.216 5295168.501, 4476326.360 5295164.393, 4476330.617 5295159.250, 4476335.813 5295154.692, 4476343.146 5295150.604, 4476351.084 5295147.836, 4476359.507 5295148.135, 4476364.660 5295149.582, 4476365.437 5295149.023, 4476369.688 5295146.003, 4476391.786 5295132.204, 4476387.870 5295090.657, 4476404.478 5295090.000, 4476403.034 5295059.374, 4476350.684 5295061.089, 4476314.562 5295062.638, 4476297.859 5295073.036, 4476214.263 5294944.568, 4476190.885 5294958.985))']})
df['coords'] = df['coords'].apply(wkt.loads)

df2=pd.DataFrame({'id':['1','2'],'coords':['POLYGON Z ((4476390.380 5295101.660 757.840, 4476390.373 5295100.170 757.840, 4476386.170 5295100.173 757.840, 4476381.977 5295100.165 757.840, 4476381.975 5295101.656 757.840, 4476372.119 5295101.669 757.840, 4476372.122 5295107.692 757.840, 4476372.136 5295113.716 757.840, 4476386.374 5295113.694 757.840, 4476391.828 5295113.682 757.840, 4476397.381 5295113.667 757.840, 4476397.388 5295107.662 757.840, 4476397.395 5295101.648 757.840, 4476391.882 5295101.682 757.840, 4476390.380 5295101.660 757.840))','POLYGON Z ((4476407.045 5295067.191 754.640, 4476406.564 5295061.496 754.640, 4476370.230 5295064.617 754.640, 4476370.054 5295063.163 754.640, 4476360.773 5295064.064 754.640, 4476360.907 5295065.459 754.640, 4476342.745 5295067.005 754.640, 4476342.667 5295065.767 754.640, 4476339.327 5295066.097 754.640, 4476339.404 5295067.315 754.640, 4476321.871 5295068.826 754.640, 4476321.914 5295069.415 754.640, 4476322.911 5295080.413 754.640, 4476345.583 5295078.513 754.640, 4476346.107 5295084.276 754.640, 4476354.975 5295083.552 754.640, 4476355.359 5295088.310 754.640, 4476382.252 5295085.865 754.640, 4476381.837 5295080.828 754.640, 4476408.044 5295078.510 754.640, 4476407.509 5295072.707 754.640, 4476410.341 5295072.447 754.640, 4476409.857 5295066.952 754.640, 4476407.045 5295067.191 754.640))']})
df2['coords']= df2['coords'].apply(wkt.loads)

poly_tojoin = gpd.GeoDataFrame(df,geometry='coords')
poly_base = gpd.GeoDataFrame(df2,geometry='coords')

base=poly_tojoin.plot()
poly_base.plot(ax=base,color='green')

sjoin_out=gpd.sjoin(poly_tojoin,poly_base,how='left',op='intersects',rsuffix='joined')
print(sjoin_out)
```

Kinda happy I got it to work but I am still quite curious what the issue is. Any idea?

**Comment by martinfleis** [comment]
Does the order of import make a difference? 

```
from osgeo import gdal
import geopandas as gpd
```

compared to 

```
import geopandas as gpd
from osgeo import gdal
```

? This looks like some dependency conflict in your environment, but I can't tell why is this happening from top of my head. We are using `gdal` within `fiona` to read the file, not to do the spatial operation, which is a bit puzzling. Can you also show the output of `geopandas.show_version()`?

Last question - how did you install geopandas, fiona and gdal?

**Comment by ludwighagelstein** [comment]
Yes changing the order it also works.

```
SYSTEM INFO
-----------
python     : 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
executable : /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6
machine    : Darwin-17.7.0-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.7.1
GEOS lib   : /Users/ludwighagelstein/opt/anaconda2/lib/libgeos_c.dylib
GDAL       : 2.4.4
GDAL data dir: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/fiona/gdal_data
PROJ       : 7.0.1
PROJ data dir: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.0+50.gaa9f9c1
pandas     : 0.25.3
fiona      : 1.8.13.post1
numpy      : 1.15.4
shapely    : 1.6.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.1.3
mapclassify: None
geopy      : 2.0.0
psycopg2   : 2.7.5 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : None
```

I think I installed them with the pip3 command from my terminal if that's what you mean.

**Comment by martinfleis** [comment]
Thanks! Installing using `pip` can sometimes cause dependency issues when it comes to the C packages. You most likely have multiple installations of GDAL in your system and Python uses the one you import first. If you import `osgeo` first, it uses its GDAL which cause a conflict somewhere in geopandas dependencies because they expect another version. If you import geopandas first, it loads the version it needs.

If importing geopandas first resolves the issue, I think we can close the case as it should resolve your need to use `gdal` later in the script. However, I would generally recommend using `conda` for package management as it takes care of these issues on your behalf.

**Comment by ludwighagelstein** [comment]
Okay thanks for your fast help!
