### ISSUE TITLE
ENH: support ~ (home dir) expansion in file paths?

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1664]
From https://stackoverflow.com/questions/64423707/python-geopandas-unable-to-locate-shapefile, pandas supports passing a file path with a `~`, which gives the expectation that geopandas also supports this. 

So we could consider supporting this as well. 
But, we also need to be careful about not fully replicating pandas complex file handling code (but it's also not officially public to reuse ..). Although in this case it might be a straightforward `if isinstance(path, str): os.path.expanduser(path)`

**Comment by martinfleis** [comment]
Ah, I did not know pandas supports that. Yeah, would be nice to have a consistency here, but if there is a wide range of cases like this we would have to cover, it may be better to have such code in fiona.

**Comment by snowman2** [comment]
Is this also an issue with the parquet format?

**Comment by Imanflow** [comment]
Do we want to add this in the end?

**Comment by martinfleis** [comment]
I think we do. For the sake of consistency and convenience. 

> Is this also an issue with the parquet format?

Yes, for both parquet and feather and both read and write. If we want to implement `~` support, it should cover all these cases.

**Comment by Imanflow** [comment]
Before I'm too brave, would this be to add
```
        if isinstance(path, str):
            path = os.path.expanduser(path)
        elif isinstance(path, Path):
            path = path.expanduser()
```

before of this line for each of the `to_xxx` functions of geodataframe? 
https://github.com/geopandas/geopandas/blob/b6174f4855693e08f3ee987e2a966b3c5ee01c35/geopandas/geodataframe.py#L974

**Comment by martinfleis** [comment]
I think so. In `to_file`, `to_parquet` and `to_feather` as well as their `read_*` counterparts. This should ideally happen in `geopandas/io/file.py` and `geopandas/io/arrow.py`, not in `geogataframe.py`.

**Comment by snowman2** [comment]
Do you think it would be worthwhile to add a utility function for this and use it everywhere?

**Comment by martinfleis** [comment]
Good suggestion. Something like `_expand_path(path)` in `file.py` (and import it from `arrow.py`) would be a good solution.

**Comment by Imanflow** [comment]
Here the PR: https://github.com/geopandas/geopandas/pull/1876
