### ISSUE TITLE
QST: replace a GEOMETRYCOLLECTION wtih a MultiPolygon

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#1665]
I'm trying to subset a GEOMETRYCOLLECTION and then replace it to a MultiPolygon in my GeoDataFrame. But the problem is that the len of MultiPolygon equals the number of geomtry inside. I really couldn't find any answer elsewhere.

```python
import geopandas as gpd  # 0.8.1
from shapely.geometry import MultiPolygon

gdf = gpd.read_file('./data.geojson')

geo_array = gdf[gdf.geoid == '06075'].geometry.explode()[1:].values
gdf.loc[gdf.geoid == '06075', 'geometry'] = MultiPolygon(geo_array)
```

```
ValueError: Must have equal len keys and value when setting with an iterable
```

[data.zip](https://github.com/geopandas/geopandas/files/5405545/data.zip)

**Comment by martinfleis** [comment]
This is known bug. See #992 for details and workaround options.

**Comment by StevenLi-DS** [comment]
@martinfleis Could you take a look at my data. I don't think the workaround is the same since I just wanna replace a GEOMETRYCOLLECTION with a  MultiPolygon not saving a dataframe.

**Comment by martinfleis** [comment]
@StevenLi-DS the workaround for your case is in the last comment in that issue I linked.

```python
import geopandas as gpd  # 0.8.1
from shapely.geometry import MultiPolygon

gdf = gpd.read_file('data.geojson')

geo_array = gdf[gdf.geoid == '06075'].geometry.explode()[1:].values
gdf.loc[gdf.geoid == '06075', 'geometry'] = gpd.GeoSeries([MultiPolygon(geo_array)])
```

**Comment by StevenLi-DS** [comment]
@martinfleis  Thanks. it seems like I have to use `gpd.GeoSeries([MultiPolygon(geo_array)]).values` if I have a geodataframe more than one row.

**Comment by StevenLi-DS** [comment]
@martinfleis This has happened to me a few time. When I `clip` a polygon geodataframe, I end up with some points or geometrycollection in the output. Do you think this could be a good FR idea to only return certain types of geometry?

**Comment by martinfleis** [comment]
@StevenLi-DS There is already `keep_geom_type` option controlling this. https://geopandas.readthedocs.io/en/latest/reference/geopandas.clip.html#geopandas.clip

**Comment by StevenLi-DS** [comment]
@martinfleis 
Do this handle cases like a polygon that is clipped into a many polygons so that it needs to be returned as a MultiPolygon? 
I get  `ValueError: Shape of passed values is (3414, 19), indices imply (3220, 19)` once I use that param.

**Comment by martinfleis** [comment]
Can you report that as a separate issue? That should not happen.
