### ISSUE TITLE
REF: replace _mapclasssify_choro with mapclassify.classify()

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1669]
Next release of mapclassify will have new high-level API allowing to call all classifiers from a single function. It replaces our custom `_mapclasssify_choro`.

See https://github.com/pysal/mapclassify/pull/90

Once it is released, we should remove our custom function and rely on this.

https://github.com/geopandas/geopandas/blob/924cdf65c7c15b01749d1cdd036c5c291e87b0f4/geopandas/plotting.py#L833

**Comment by vidushityagi8** [comment]
can i work on this? I'm a beginner so please guide me..

**Comment by martinfleis** [comment]
This is already being implemented in #1737.
