### ISSUE TITLE
ENH: Faster .explode() implementation

### ISSUE THREAD

**Issue by HTenkanen** [geopandas/geopandas#1672]
Hi guys!

Currently the `gdf.explode()` is quite slow as it relies on a [Python loop](https://github.com/geopandas/geopandas/blob/master/geopandas/base.py#L1212). 

@brendan-ward has been working on the [`get_parts()` function](https://github.com/pygeos/pygeos/pull/197) for pygeos which should give quite a nice boost for this functionality.
I was wondering that is the idea to integrate that into `gdf.explode()` function? I'd assume so, but did not find an issue for it here, so doing that now. 🙂

**Comment by jorisvandenbossche** [comment]
Yes, once it is merged (released) on the pygeos side, I am certainly planning to use it for `explode()`! (that was one of the main drivers for implementing it-> https://github.com/pygeos/pygeos/issues/127)
