### ISSUE TITLE
Geopandas geom_almost_equals method gives wrong output

### ISSUE THREAD

**Issue by dksivagis** [geopandas/geopandas#1678]
I have 2 geodata frames.

geoframe1

    MULTILINESTRING((-0.87131 52.25771, -0.87144 52.25763, -0.87126 52.25756, -0.87146 52.25747, -0.87159 52.25756))
    MULTILINESTRING((-0.87180 52.25758, -0.87167 52.25760, -0.87160 52.25767, -0.87148 52.25769, -0.87141 52.25774))
    MULTILINESTRING((-0.87190 52.25757, -0.87185 52.25767, -0.87171 52.25775, -0.87151 52.25777, -0.87151 52.25777))

geoframe2

    MULTILINESTRING((-0.87131 52.25771, -0.87144 52.25763, -0.87126 52.25756, -0.87146 52.25747, -0.87159 52.25756))
    MULTILINESTRING((-0.87190 52.25757, -0.87185 52.25767, -0.87171 52.25775, -0.87151 52.25777, -0.87151 52.25777))

before taking up, geometry wise, both the sets are exactly equal. to check "geom_almost_equals" method, i removed one linestring from geoframe2 and executed the method.

    features_equal = geoframe1.loc[geoframe1.geom_almost_equals(geoframe2, decimal=5)]

The result should give me only 2 geometries that are actually equal.
But the result i got is only 1 geometry

    **MULTILINESTRING((-0.87190 52.25757, -0.87185 52.25767, -0.87171 52.25775, -0.87151 52.25777, -0.87151 52.25777))**

How could this happen ? 
is there any internal processing that doing wrong operation?
please help in this.

**Comment by martinfleis** [comment]
`geoframe1.geom_almost_equals(geoframe2, decimal=5` works row-wise. It aligns both GeoSeries and checks if geometries almost equal for each row. 

In your case, the first checks with the first which is `True` since both are equal. Second checks with second, which is `False`, because they are different. Third checks with `None`.

Therefore you have `[True, False, False]` which naturally returns a single row.

What are you trying to do?

**Comment by dksivagis** [comment]
Thank you martinfleis. till now , i am of the openion that each line of geoframe1 compare itself with all lines of geoframe2 (Like a nested for-loop) 

**Is there such function in geopandas that checks for actual geometric equality rather than row-wise?**

**Comment by martinfleis** [comment]
Not at the moment, there is a WIP PR which should implement it in the next release (#1674). You want to know which feature of the left geodataframe is also present in the right geodataframe, correct?

**Comment by dksivagis** [comment]
Exactly Martinfleis.
I am working on road feature data verification. new roads get added every month. we have to ensure that already existing roads are not disturbed. 
So Geometry wise, I want a method to know which feature on the left geodataframe is also present in right geodataframe.
this way i could identify those features that are not changed.

**Comment by martinfleis** [comment]
@dksivagis This function does what you need until we'll have it in GeoPandas directly.

```python
import numpy as np
import pandas as pd

def geom_almost_equals_matrix(df1, df2, decimal=5):
    inp, res = df2.sindex.query_bulk(df1.geometry)
    check = df2.geometry.values[res].geom_almost_equals(df1.geometry.values[inp], decimal=decimal)
    unique, counts = np.unique(inp, return_counts=True)
    values = np.split(check, np.cumsum(counts)[:-1])
    return pd.Series([np.any(a) for a in values], index=df1.index)
```
```
>>> geom_almost_equals_matrix(df1, df2)
0     True
1    False
2     True
dtype: bool
```

**Comment by dksivagis** [comment]
Thank you so much Martinfleis.
I will try using this.
It helps a lot.

**Comment by dksivagis** [comment]
Hi Martinfleis,
while using the above function, i am getting this error

 "Length of passed values is 3, index implies 4."

This error is occurring when the below line is executed
return pd.Series([np.any(a) for a in values], index=df1.index)

Any idea why its popping up.

**Comment by martinfleis** [comment]
Ah, sure. Sorry, it was just a quick untested function.  Try this one (no guarantee :) without reproducible example.). 

```python
import numpy as np
import pandas as pd

def geom_almost_equals_matrix(df1, df2, decimal=5):
    inp, res = df2.sindex.query_bulk(df1.geometry)
    check = df2.geometry.values[res].geom_almost_equals(df1.geometry.values[inp], decimal=decimal)
    unique, counts = np.unique(inp, return_counts=True)
    values = np.split(check, np.cumsum(counts)[:-1])
    bools = [np.any(a) for a in values]
    out = np.zeros(shape=df1.geometry.values.shape, dtype=np.bool_)
    out[unique] = bools
    return pd.Series(out, index=df1.index)
```

**Comment by dksivagis** [comment]
Awesome.
Worked like a charm.
Testing on more number of features. will open the issue if i come across any unknown error.
Thanks a lot martinfleis 👍
