### ISSUE TITLE
Tests not distributed in the pypi source

### ISSUE THREAD

**Issue by shoyer** [geopandas/geopandas#168]
This makes it trickier to test a geopandas install -- I encountered this issue because I am trying to build a conda package for geopandas.

I believe the best practice would be to make "geopandas.tests" a Python module (this is basically want pandas does). That would ensure tests get distributed with the source, and also let you run tests with something like `nosetests geopandas`.

**Comment by jorisvandenbossche** [comment]
Closed by #309
