### ISSUE TITLE
ENH: publicise `wkt` and `wkb` io functions as GeoSeries methods

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1680]
We have currently `to_wkb`, `to_wkt` and `from_wkb`, `from_wkt` on array level, but those are not part of a public API as a method on GeoSeries.

Optimally, all should be directly accessible as `GeoSeries.to_wkt()` etc.

It should be really simple to implement.

**Comment by Ervin66** [comment]
hey, can I work on this?

**Comment by martinfleis** [comment]
@Ervin66 yes, that would be welcome :).

The functions are here https://github.com/geopandas/geopandas/blob/ca101aae93e7bfdf11068a2297bd8e503c3e8156/geopandas/array.py#L180

Thanks!

**Comment by johnflavin** [comment]
@martinfleis Questions:

1. Should `GeoSeries.to_wkt()` / `.to_wkb()` return a pandas `Series`?
2. How should `from_wkt` and `from_wkb` be integrated into the API? I could see them being useful as class methods on `GeoSeries` that would create a `GeoSeries` from a list or array of WKTs/WKBs. Or I could see them being useful as additional kwargs on the `GeoDataFrame` constructor; they could work similarly to the `geometry` kwarg, where a user could specify a `wkt` or `wkb` column name or pass in a list of WKTs/WKBs which would be set as the `geometry`. Or maybe both?
