### ISSUE TITLE
Kernel getting hanged while performing overlay Operation

### ISSUE THREAD

**Issue by dksivagis** [geopandas/geopandas#1681]
Hi,
I tried finding difference operation using the overlay method on 2 very small geojson files. 
**I installed python 3.8 (32 bit) and set up a virtual environment to use geopandas (0.8.1).**
i also added jupyter notebook to my environment and tried running the following code.
<img width="539" alt="proa" src="https://user-images.githubusercontent.com/6330294/98438569-1414cc00-2111-11eb-8f5a-2179dd1345b2.PNG">
**Both the linestring geodataframes are valid with same CRS.** 
But when i run the overlay method, the kernel is dying. 
<img width="508" alt="prob" src="https://user-images.githubusercontent.com/6330294/98438612-8be2f680-2111-11eb-80a6-c716fc21e640.PNG">
When i used QGIS software tool over the same features, there is no error and i am getting the result immediately.
Not able to understand what would be the root cause here. 

please let me know where the mistake is happening.

**Comment by martinfleis** [comment]
How did you install geopandas? Can you show `geopandas.show_versions()`?

**Comment by dksivagis** [comment]
Hi martinfleis , Here is the snapshot after running geopandas.show_versions()
<img width="544" alt="version" src="https://user-images.githubusercontent.com/6330294/98441260-357eb380-2123-11eb-898f-9b415a2ee0d7.PNG">

**Comment by martinfleis** [comment]
It looks like an issue in the environment (i.e. with the installation). Notice that `shapely` does not see GEOS.

I assume you installed geopandas using `pip install geopandas` right?

I have no experience with `venv`, but it is known that pip install on windows can be tricky, that is why we recommend using `conda` and `conda-forge` channel. If that is not possible, you may have to try reinstalling from different sources (like wheels). See https://geopandas.readthedocs.io/en/latest/getting_started/install.html#installing-with-pip and https://geoffboeing.com/2014/09/using-geopandas-windows/ for some details on the issue.

**Comment by dksivagis** [comment]
thank you Martinfleis.

Yes i installed geopandas using pip. 

I shall check the links and update my setup once. your suggestions are very helpful.

**Comment by dksivagis** [comment]
Thanks once again Martinfleis.
I updated Fiona, pyproj, Rtree and gdal to their latest versions that are available in 
https://www.lfd.uci.edu/~gohlke/pythonlibs/
**Now its working perfect with out any problem**. Below is the snapshot of "geopandas.show_versions()"
<img width="573" alt="version2" src="https://user-images.githubusercontent.com/6330294/98446683-2577cb80-2145-11eb-84d5-94a0348dd1a9.PNG">
