### ISSUE TITLE
fix install env

### ISSUE THREAD

**Issue by khaitranhuynh** [geopandas/geopandas#1683]
Try installing your geo_env kernel to Jupyter:

```
conda activate geo_env
python -m ipykernel install --user --name geo_env
```

Then you should be able to switch to it in jypyter notebook. I will close this issue as it is not issue of geopandas apparently. We can continue discussion even in closed issue.

_Originally posted by @martinfleis in https://github.com/geopandas/geopandas/issues/1166#issuecomment-542726879_

**Comment by martinfleis** [comment]
Hi @khaitranhuynh,

do you have any question regarding that comment?

I'll close the issue now as it is unclear what is it about. We can reopen it if there is any specific question/suggestion regarding this.
