### ISSUE TITLE
QST: MultiLineString is converted to LineString when creating new GeoDataFrame from pandas Dataframe

### ISSUE THREAD

**Issue by ludwighagelstein** [geopandas/geopandas#1684]
Hi, 

when I'm creating a new GeoDataFrame from a pandas DataFrame including a MultiLineString, they are converted to two LineStrings within the GeoDataframe.
Is it like that on purpose and is there a way to keep the MultiLineString as a single feature in the new GeoDataFrame without dissolving it (e.g. by 'name' in the below example)

```
import geopandas as gpd
import pandas as pd
from shapely.geometry import LineString,MultiLineString
line1 = LineString([(0, 0), (1, 1)])
line2 = LineString([(0, 1), (1, 2)])

muLine=MultiLineString([line1,line2])

df=pd.DataFrame({'name':'Testline','geometry':muLine})
gdf=gpd.GeoDataFrame(df,geometry='geometry')

```
returns
```
       name                                       geometry
0  Testline  LINESTRING (0.00000 0.00000, 1.00000 1.00000)
1  Testline  LINESTRING (1.00000 1.00000, 1.00000 2.00000)
```

**Comment by martinfleis** [comment]
GeoPandas automatically checks if the variable passed as `geometry` is an array-like. MultiLineString has an array interface and is hence _exploded_ in this specific case.

Pass it as a list to get a single line with the original MultiLineString.

```py
df = pd.DataFrame({'name': ['Testline'], 'geometry': [muLine]})
```

**Comment by ludwighagelstein** [comment]
Awesome thank you!
