### ISSUE TITLE
QST: geodf.to_postgis force geometry type

### ISSUE THREAD

**Issue by fbmfbm** [geopandas/geopandas#1692]
Hi,

I have some error to import shapes file to potsgis with geodf.to_postgis . Some file  use simple geometry type and other multy.
How can force import in postgis as multy polygone ?

Don't find any way to set geometry type in this function.

Tank's for your help.

**Comment by martinfleis** [comment]
There is a trick using a quite abandoned function `collect`.

```py
mutli = gdf.geometry.apply(gpd.tools.collect, multi=True)
```

**Comment by fbmfbm** [comment]
Tan'ks for your help Martin !

**Comment by jorisvandenbossche** [comment]
Not fully sure we should recommend using `collect` too much (or, we should update it to be a more officially supported function).

We could also consider adding some way to specify this in `to_postgis` ?

**Comment by martinfleis** [comment]
> we should update it to be a more officially supported function

We could update it and then hook it into `to_postgis` via keyword?
