### ISSUE TITLE
BUG: geopandas.read_file fails for large polygon geoJSON 

### ISSUE THREAD

**Issue by bbuzz31** [geopandas/geopandas#1695]
geopandas.read_file incorrectly reads large geoJSON polygon file.
This isn't directly related to the version of geopandas, but rather to underlying drivers (i.e. gdal, fiona). 
Code to reproduce (which takes some minutes, especially the first time when downloading data) is below, as well as the output figures from the correct and incorrect install.

Any help sorting it out / gettting it to the right people is appreciated.

---

####  MWE

```python
import os
from osgeo import gdal
import geopandas as gpd
import matplotlib.pyplot as plt

def get_OSM():
    """ Download/crop water/land OSM polys if desired crop isn't on disk """
    path_dst = os.path.join(os.getcwd(), 'water_polygons_SW.json')
    path_osm = f'/vsizip/vsicurl/https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip/water-polygons-split-4326/water_polygons.shp'
    W,E,S,N  = [-180, 0, -180, 0]
    # vector translate = 'ogr2ogr', f"-spat {W} {S} {E} {N}", '-f GeoJSON', path_dst, path_osm
    if not os.path.exists(path_dst):
        print(f'Downloading and cropping OSM water polygons to SE')
        gdal.VectorTranslate(path_dst, path_osm, spatFilter=[W,S,E,N], format='GeoJSON')

    print(f'Loading OSM water polygons from: {path_dst}')
    gdf_osm  = gpd.read_file(path_dst)
    return gdf_osm

if __name__ == '__main__':
    gdf_OSM  = get_OSM() # get a large df of polys
    axes     = gdf_OSM.plot(color='blue', edgecolor='black', alpha=0.25)
    plt.show()


```
#### Correct Output
![res_good](https://user-images.githubusercontent.com/15522503/98754599-e7b0b800-237b-11eb-8fcd-69c680b1644e.png)

#### Incorrect Output
![gdf_wrong](https://user-images.githubusercontent.com/15522503/98754760-32cacb00-237c-11eb-8c35-181fd101856d.png)

SYSTEM INFO - (Correct Output)
-----------
python     : 3.8.5 | packaged by conda-forge | (default, Jul 22 2020, 17:24:51)  [Clang 10.0.0 ]
executable : /Users/bb/Miniconda3/envs/SL/bin/python
machine    : macOS-10.15.7-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO - (Correct Output)
---------------------
GEOS       : 3.8.1
GEOS lib   : /Users/bb/Miniconda3/envs/SL/lib/libgeos_c.dylib
GDAL       : 3.0.4
GDAL data dir: /Users/bb/Miniconda3/envs/SL/share/gdal
PROJ       : 7.0.0
PROJ data dir: /Users/bb/Miniconda3/envs/SL/share/proj

PYTHON DEPENDENCIES - (Correct Output)
-------------------
geopandas  : 0.7.0
pandas     : 1.1.0
fiona      : 1.8.13
numpy      : 1.18.5
shapely    : 1.7.0
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.2.1
mapclassify: 2.3.0
pysal      : None
geopy      : 2.0.0
psycopg2   : None

SYSTEM INFO - (Incorrect Output)
-----------
python     : 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 18:42:56)  [Clang 10.0.1 ]
executable : /Users/bb/Miniconda3/envs/test/bin/python
machine    : macOS-10.15.7-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO - (Incorrect Output)
---------------------
GEOS       : 3.8.1
GEOS lib   : /Users/bb/Miniconda3/envs/test/lib/libgeos_c.dylib
GDAL       : 3.1.4
GDAL data dir: /Users/bb/Miniconda3/envs/test/share/gdal
PROJ       : 7.1.1
PROJ data dir: /Users/bb/Miniconda3/envs/test/share/proj

PYTHON DEPENDENCIES - (Incorrect Output)
-------------------
geopandas  : 0.7.0
pandas     : 1.1.4
fiona      : 1.8.17
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.2
mapclassify: None
pysal      : None
geopy      : None
psycopg2   : None

</details>

**Comment by martinfleis** [comment]
Thanks for the report. I can confirm that it is the same on master. No idea what is going on, to be honest, but it'll most likely be an issue in `fiona` reading JSON. Reading that shp directly works.

**Comment by bbuzz31** [comment]
thanks @martinfleis, I've gotten to the bottom of it with the fiona people (https://github.com/Toblerity/Fiona/issues/990)
