### ISSUE TITLE
ENH: Add an option to not load geometries

### ISSUE THREAD

**Issue by adehecq** [geopandas/geopandas#1700]
I could not find this feature, but please point me to the right direction if it exists.

I wish I could load all the metadata of a vector file, without loading the geometries (which takes the longest). This is useful for large vector files when one is only interested in looking at the metadata before e.g. loading only a subset.
I imagine it could be a simple boolean option to read_file, then a condition in the method would just skip the part where geometries are read.

**Comment by martinfleis** [comment]
We use `fiona` to read files and `fiona` itself can do this exploration. 

If you only want to know metadata, you can use fiona for that.

```py
with fiona.open(geopandas.datasets.get_path('naturalearth_lowres')) as f:
    print(f.schema)
    print(f.crs)
    print(f.driver)
```
```
{'properties': OrderedDict([('pop_est', 'int:10'), ('continent', 'str:80'), ('name', 'str:80'), ('iso_a3', 'str:80'), ('gdp_md_est', 'float:24.15')]), 'geometry': 'Polygon'}
{'init': 'epsg:4326'}
ESRI Shapefile
```

Alternatively, you can read the first row only (which is fast).

```py
geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'), rows=1)
```

As a function of geopandas, it does not exist and I am not sure I understand your proposal, to be honest.

**Comment by adehecq** [comment]
Thanks for the suggestion! I just found out that fiona was doing this indeed. But then it does not seem to load for example the attributes (at least that's how they're called in QGIS) of each shape.

I used to work with GDAL/OGR, and I had a wrapper class around it that would load **all** the metadata, without actually loading the geometry, which is really fast. The data set could then later be cropped to a given extent, filtered by attribute etc to only load a subset. You can see some _light_ examples of it here: https://geoutils.readthedocs.io/en/latest/get-started.html

**Comment by martinfleis** [comment]
I believe that fiona can do all that. `schema` shows you attributes. 
```
 |  bounds
 |      Returns (minx, miny, maxx, maxy).
 |  
 |  closed
 |      ``False`` if data can be accessed, otherwise ``True``.
 |  
 |  crs
 |      Returns a Proj4 string.
 |  
 |  crs_wkt
 |      Returns a WKT string.
 |  
 |  driver
 |      Returns the name of the proper OGR driver.
 |  
 |  meta
 |      Returns a mapping with the driver, schema, crs, and additional
 |      properties.
 |  
 |  profile
 |      Returns a mapping with the driver, schema, crs, and additional
 |      properties.
 |  
 |  schema
 |      Returns a mapping describing the data schema.
 |      
 |      The mapping has 'geometry' and 'properties' items. The former is a
 |      string such as 'Point' and the latter is an ordered mapping that
 |      follows the order of fields in the data file.
```

Then `read_file` can filter based on `bbox` or `mask` or you can pass a slice of rows. Filtering by attributes would have to be done afterwards I guess.

If you just want to get a full DataFrame, just without geometry, or a subset of columns, here are some ways: https://gis.stackexchange.com/questions/129414/only-read-specific-attribute-columns-of-a-shapefile-with-geopandas-fiona

**Comment by adehecq** [comment]
Ok thanks, I will look into this!
I still believe it would be a useful feature to geopandas.read_file to have an option to skip loading the geometries in memory, but if you think it's not relevant, feel free to close the issue.

**Comment by martinfleis** [comment]
Sorry for mystification, going through old issues I just realised that we already have the functionality you want.

https://geopandas.readthedocs.io/en/latest/docs/user_guide/io.html#field-column-filters

**Comment by adehecq** [comment]
Fantastic!
