### ISSUE TITLE
ENH: check for non-overlapping bounding boxes in overlay and sjoin

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1708]
In `clip` we have a quick check which immediately returns empty GeoDataFrame if left and right dfs are non-overlapping (their total bounds). We should do the same in `overlay` and `sjoin` to avoid building an expensive spatial index. 

This is the check in `clip`:

https://github.com/geopandas/geopandas/blob/cdb42821ababcf29b6f7f94dd66fa9cb5a8f6071/geopandas/tools/clip.py#L136-L145

See for use case https://github.com/geopandas/geopandas/issues/400#issuecomment-729899659 cc @zedrdave

**Comment by Imanflow** [comment]
There is a PR for this https://github.com/geopandas/geopandas/pull/1851
