### ISSUE TITLE
QST: Why no geometry/crs kwargs in GeoDataFrame.__init__?

### ISSUE THREAD

**Issue by johnflavin** [geopandas/geopandas#1712]
- [X] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

---

#### Question about geopandas

The [`GeoDataFrame.__init__` method](https://github.com/geopandas/geopandas/blob/master/geopandas/geodataframe.py#L87) has no special keyword arguments in its signature. But the `geometry` and `crs` keywords are clearly important, and are `pop`ed out of `kwargs` right away.

```python
    def __init__(self, *args, **kwargs):
        crs = kwargs.pop("crs", None)
        geometry = kwargs.pop("geometry", None)
        ...
```

Is there a reason those special keyword args are not in the signature? i.e. why not this:
```python
    def __init__(self, *args, geometry=None, crs=None, **kwargs):
        ...
```

**Comment by martinfleis** [comment]
It looks that it evolved like this historically. There was a support of `crs` attribute before `crs` keyword - https://github.com/geopandas/geopandas/commit/64327aab8309deff00e384e242d0f6082d499632. I don't think this is a specific design decision, therefore there's no real reason why it looks as it looks. It is strange though that we document them separately but do not list them in the signature.

Feel free to push a PR changing that, I don't think it can cause any damage.
