### ISSUE TITLE
REF: remove heuristics in __repr__ guessing if CRS if projected

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1713]
In `GeometryArray.__repr__` we have a heuristic which tries to guess if a geometry is projected or not based on coords of first ten geometries. The reason is that we set rounding of geographic CRS to 5 while for projected to 3.

https://github.com/geopandas/geopandas/blob/59d3b2b7260b485e95e06a38f1c3e218b0a40a46/geopandas/array.py#L1005-L1023

We can remove this and use `crs.is_projected` or `crs.is_geographic` instead. Something along

```py
if precision is None:
    if self.crs and self.crs.is_projected:
        precision = 3
    else:
        precision = 5
```

**Comment by jorisvandenbossche** [comment]
We should certainly start using the `crs.is_projected` logic when a CRS is set, but could also still keep the current code as fall back?

**Comment by kenkirito** [comment]
can i work on this

**Comment by martinfleis** [comment]
@kenkirito Yes! If you can keep the fall back to existing logic as @jorisvandenbossche suggested above, that'd be ideal. Thanks a lot!
