### ISSUE TITLE
DOC: document spatial join not working in 3d

### ISSUE THREAD

**Issue by chrisroat** [geopandas/geopandas#1716]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gp
from shapely.geometry import MultiPoint, Point

df_pnts = gp.GeoSeries([Point(0, 0, 0), Point(0, 0, 10)]).to_frame('pnts').set_geometry('pnts')

data_poly = [
    [-1, -1, -1],
    [-1, -1, +1],
    [-1, +1, -1],
    [-1, +1, +1],
    [+1, -1, -1],
    [+1, -1, +1],
    [+1, +1, -1],
    [+1, +1, +1],
]
df_poly = gp.GeoSeries([MultiPoint(data_poly)]).convex_hull.to_frame('poly').set_geometry('poly')
df_join = gp.sjoin(df_pnts, df_poly)
print(df_join)
```

Output:
```
                                 pnts  index_right
0   POINT Z (0.00000 0.00000 0.00000)            0
1  POINT Z (0.00000 0.00000 10.00000)            0
```

#### Problem description

The point (0, 0, 10) is not contained with the polygon, yet is returned as spatially joined to the polygon.

#### Expected Output

I expect only the first point in the output to be returned.

Or, if 3d spatial joins are not implemented, an exception should be raised.

#### Output of ``geopandas.show_versions()``

<details>

Failed `CDLL(libgeos_c.so.1)`
Failed `CDLL(libgeos_c.so)`

SYSTEM INFO
-----------
python     : 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05)  [GCC 7.5.0]
executable : /opt/conda/bin/python
machine    : Linux-4.19.112+-x86_64-with-glibc2.10

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 2.4.4
GDAL data dir: /opt/conda/lib/python3.8/site-packages/fiona/gdal_data
PROJ       : 7.2.0
PROJ data dir: /opt/conda/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.4
fiona      : 1.8.17
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : None
pyproj     : 3.0.0.post1
matplotlib : 3.3.2
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : 2.0.0

</details>

**Comment by martinfleis** [comment]
Thank you for the report @chrisroat!

Every operation in GeoPandas and shapely is planar, i.e. the third dimension is not taken into account. There is a wide range of applications where you want to spatially join xyz geometry in planar terms, i.e. rivers (LinesStringZ) and administrative boundaries etc, so raising an exception is not an optimal solution.

We should make it clear in the documentation (as shapely does) but this is expected behaviour. There are no plans to support three-dimensional operations of this kind. You may want to look into [scikit-geometry](https://github.com/scikit-geometry/scikit-geometry) if you need more complex three-dimensional operations.

**Comment by jorisvandenbossche** [comment]
I was writing a similar answer, but Martin phrased it much better ;) 
This is indeed something that should be documented better. 

Sidenote: it seems that PostGIS has a small set of specific functions that *do* support 3D geometries, so in general this functionality might not be fully out of scope (but certainly not directly for geopandas, I mean for the general GEOS-based Python ecosystem)
