### ISSUE TITLE
How do I know if pygeos is working?

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#1722]
I thought I'd setup `pygeos` right, but in my tracebacks I'm seeing `shapely`, and my geometric objects are of type `shapely.geometry.polygon.Polygon`. Is there a way to check if `pygeos` integration is working correctly?

**Comment by martinfleis** [comment]
Pygeos is now implemented as a backend, so unless you intentionally want to get pygeos geometries, you should not notice it. It is used if geopandas can import it.

You can check that with `print(geopandas.options.use_pygeos)` which should return `True`.

If you want to get the underlying array of pygeos geometries, you can as `gdf.geometry.values.data`.

**Comment by nickeubank** [comment]
Thanks!
