### ISSUE TITLE
BUG: geopandas installed with pygeos doesn't read geometries

### ISSUE THREAD

**Issue by MRossol** [geopandas/geopandas#1730]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
gdf = gpd.read_file('RhodeIsland.geojson')
gdf.head()
```
```
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/test/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/miniconda3/envs/test/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/miniconda3/envs/test/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/core/frame.py in __repr__(self)
    742         else:
    743             width = None
--> 744         self.to_string(
    745             buf=buf,
    746             max_rows=max_rows,

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/core/frame.py in to_string(self, buf, columns, col_space, header, index, na_rep, formatters, float_format, sparsify, index_names, justify, max_rows, min_rows, max_cols, show_dimensions, decimal, line_width, max_colwidth, encoding)
    881                 line_width=line_width,
    882             )
--> 883             return formatter.to_string(buf=buf, encoding=encoding)
    884 
    885     # ----------------------------------------------------------------------

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/format.py in to_string(self, buf, encoding)
    919         encoding: Optional[str] = None,
    920     ) -> Optional[str]:
--> 921         return self.get_result(buf=buf, encoding=encoding)
    922 
    923     def to_latex(

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/format.py in get_result(self, buf, encoding)
    518         """
    519         with self.get_buffer(buf, encoding=encoding) as f:
--> 520             self.write_result(buf=f)
    521             if buf is None:
    522                 return f.getvalue()

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/format.py in write_result(self, buf)
    832         else:
    833 
--> 834             strcols = self._to_str_columns()
    835             if self.line_width is None:  # no need to wrap around just print
    836                 # the whole frame

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/format.py in _to_str_columns(self)
    768                     col_space.get(c, 0), *(self.adj.len(x) for x in cheader)
    769                 )
--> 770                 fmt_values = self._format_col(i)
    771                 fmt_values = _make_fixed_width(
    772                     fmt_values, self.justify, minimum=header_colwidth, adj=self.adj

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/format.py in _format_col(self, i)
    952         frame = self.tr_frame
    953         formatter = self._get_formatter(i)
--> 954         return format_array(
    955             frame.iloc[:, i]._values,
    956             formatter,

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/format.py in format_array(values, formatter, float_format, na_rep, digits, space, justify, decimal, leading_space, quoting)
   1177     )
   1178 
-> 1179     return fmt_obj.get_result()
   1180 
   1181 

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/format.py in get_result(self)
   1208 
   1209     def get_result(self) -> List[str]:
-> 1210         fmt_values = self._format_strings()
   1211         return _make_fixed_width(fmt_values, self.justify)
   1212 

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/format.py in _format_strings(self)
   1275                 else:
   1276                     tpl = " {v}"
-> 1277                 fmt_values.append(tpl.format(v=_format(v)))
   1278 
   1279         return fmt_values

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/format.py in _format(x)
   1249             else:
   1250                 # object dtype
-> 1251                 return str(formatter(x))
   1252 
   1253         vals = extract_array(self.values, extract_numpy=True)

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/printing.py in pprint_thing(thing, _nest_lvl, escape_chars, default_escapes, quote_strings, max_seq_items)
    232         result = f"'{as_escaped_string(thing)}'"
    233     else:
--> 234         result = as_escaped_string(thing)
    235 
    236     return result

~/miniconda3/envs/test/lib/python3.8/site-packages/pandas/io/formats/printing.py in as_escaped_string(thing, escape_chars)
    208             escape_chars = escape_chars or tuple()
    209 
--> 210         result = str(thing)
    211         for c in escape_chars:
    212             result = result.replace(c, translate[c])

~/miniconda3/envs/test/lib/python3.8/site-packages/shapely/geometry/base.py in __str__(self)
    244 
    245     def __str__(self):
--> 246         return self.wkt
    247 
    248     # To support pickling

~/miniconda3/envs/test/lib/python3.8/site-packages/shapely/geometry/base.py in wkt(self)
    373     def wkt(self):
    374         """WKT representation of the geometry"""
--> 375         return WKTWriter(lgeos).write(self)
    376 
    377     @property

~/miniconda3/envs/test/lib/python3.8/site-packages/shapely/geos.py in write(self, geom)
    396         """Returns WKT string for geometry"""
    397         if geom is None or geom._geom is None:
--> 398             raise ValueError("Null geometry supports no operations")
    399         result = self._lgeos.GEOSWKTWriter_write(self._writer, geom._geom)
    400         text = string_at(result)

ValueError: Null geometry supports no operations
```

geojson is attached:
[RhodeIsland.geojson.zip](https://github.com/geopandas/geopandas/files/5669062/RhodeIsland.geojson.zip)

#### Problem description
I have installed geopandas using pip in a python 3.8 conda environment

`conda create -n test python=3.8`
`pip install geopandas`

To use spatial indexing I have also installed pygeos since rtree cannot be pip installed
`pip install pygeos`

After installing pygeos it appears that geopands.read_file() does not work properly. geopandas does not properly identify the geometries in the geojson and an empty dataframe is returned.

This came up while running tests for NREL's Renewable Energy Potential Exchange tool: github.com/nrel/reVX

Tests before adding pygeos as a dependency:
https://github.com/NREL/reVX/runs/1525022793?check_suite_focus=true
Error:
```
ImportError: Spatial indexes require either `rtree` or `pygeos`. See installation instructions at https://geopandas.org/install.html
```
Tests after adding pygeos as a dependency:
https://github.com/NREL/reVX/runs/1526296854?check_suite_focus=true
NOTE: tests only fail on MAC OSx
Error:
```
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/runner/work/reVX/reVX/reVX/wind_setbacks/wind_setbacks.py", line 339, in _compute_generic_setbacks
    features = cls._parse_features(features_fpath, crs)
  File "/Users/runner/work/reVX/reVX/reVX/wind_setbacks/wind_setbacks.py", line 786, in _parse_features
    return structures.to_crs(crs)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/geopandas/geodataframe.py", line 816, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'to_crs'
```

#### Expected Output
                                            geometry
0  POLYGON ((-71.83120 41.37143, -71.83118 41.371...
1  POLYGON ((-71.83389 41.36475, -71.83389 41.364...
2  POLYGON ((-71.82240 41.36891, -71.82227 41.368...
3  POLYGON ((-71.82079 41.36944, -71.82075 41.369...
4  POLYGON ((-71.81835 41.36942, -71.81838 41.369...

#### Output of ``geopandas.show_versions()``

<details>

Failed `CDLL(/Library/Frameworks/GEOS.framework/Versions/Current/GEOS)`
Failed `CDLL(/opt/local/lib/libgeos_c.dylib)`
Failed `CDLL(/usr/local/lib/libgeos_c.dylib)`

SYSTEM INFO
-----------
python     : 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ]
executable : /Users/mrossol/miniconda3/envs/test/bin/python
machine    : macOS-10.15.7-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 2.4.4
GDAL data dir: /Users/mrossol/miniconda3/envs/test/lib/python3.8/site-packages/fiona/gdal_data
PROJ       : 7.2.0
PROJ data dir: /Users/mrossol/miniconda3/envs/test/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.0+72.ge506de5
pandas     : 1.1.5
fiona      : 1.8.18
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : None
pyproj     : 3.0.0.post1
matplotlib : 3.3.3
mapclassify: None
geopy      : None
psycopg2   : 2.8.6 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : None

</details>

**Comment by jdmcbr** [comment]
@MRossol Is there a particular reason that you're installing with pip rather than conda? I can create a working environment with:

    conda create -n test python=3.8 geopandas pygeos

**Comment by jorisvandenbossche** [comment]
Although we typically recommend conda (certainly if you are already using conda to create an environment), it should still work with pip installed packages as well .. 
Now, I also created a conda environment and pip installed geopandas and pygeos (on ubuntu), and I can read the linked file without problem. 

Although, I see now you are using Windows? Shapely is known to have problems in that case to find the correct GEOS version in a conda environment when installed with pip .. And that is potentially the issue, as the output of `geopandas.show_versions()` is showing an error related to GEOS lib.

> To use spatial indexing I have also installed pygeos since rtree cannot be pip installed

It's true that the error message for spatial indexing says you need to install rtree or pygeos. But, what is actually not clear from this message is that installing pygeos also does a lot more than just enabling spatial indexing... (see https://geopandas.readthedocs.io/en/latest/getting_started/install.html#using-the-optional-pygeos-dependency).

**Comment by jorisvandenbossche** [comment]
Hmm, looking at the CI output, there it is also failing for MacOSX. From the output, it seems that by installing pygeos, it messed up the shapely installation, because it is complaining about "null" geometries (probably because it is not correctly finding the GEOS library anymore). 

I don't really know how to solve this on the short term (I think it is something that needs to be fixed in the Shapely wheels), so I would advice you to either not install pygeos (but eg rtree instead, if only needing the spatial index), or otherwise install it with conda.

**Comment by MRossol** [comment]
@jorisvandenbossche and @jdmcbr,  for backstory, as you can see from the CI we have an open-source package that uses geopandas. I just implemented a new feature that requires spatial indexing. Historically we released the package both on conda and on pypi. For CI we were using pure python and pip to install the dependencies and run our tests. As you probably know rtree doesn't provide a pre-build wheel on pip which is why I went down the pygeos rabbit hole. @jorisvandenbossche  you seem to be spot on the pygeos seems to break shapely only on MacOSX.

My current workaround is to switch our CI workflow to use a conda env and install rtree from conda. I'll add a note to our installation instructions that for this new feature you'll need to install rtree separately if you pip install our package.

Should I duplicate this issue on the pygeos repo?

**Comment by jdmcbr** [comment]
@jorisvandenbossche Of course, you're correct, geopandas does aim to support this installation route. I've personally experienced enough challenges in pip installations of libraries that depend on C libraries within conda envs that my default approach in conda envs is to use conda for all packages that can be installed with conda.

**Comment by jorisvandenbossche** [comment]
Yeah, fully agreed that it should be your default approach touse conda to install shapely in a conda environment. I am only of the opinion that we should not actively make it *not* working (which is basically what shapely does right now), since some people will always do it (eg because online tutorials say them to do `pip install ..`).

> Should I duplicate this issue on the pygeos repo?

Not in pygeos, since it's a shapely issue. But it's a known issue, see eg https://github.com/Toblerity/Shapely/issues/1032

**Comment by jorisvandenbossche** [comment]
Closing the issue here then
