### ISSUE TITLE
BUG: error in reading GeoJSON text sequence file

### ISSUE THREAD

**Issue by dazza-codes** [geopandas/geopandas#1732]
- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of geopandas.

A GeoJSON text sequence file contains lines of geojson features and they have a field called "s2_cell_id" that contains various values, e.g.

```
$ jq '.' file.geojsons | grep '"s2_cell_id'
    "s2_cell_id": 9824657365274853000,
    "s2_cell_id": 9868811851946736000,
    "s2_cell_id": 9826983181680402000,
    "s2_cell_id": 9868914762299110000,
    "s2_cell_id": 9870151630277210000,
    "s2_cell_id": 9866365850911373000,
    "s2_cell_id": 9869844377563986000,
    "s2_cell_id": 9868791200154489000,
```

But when they are read by geopandas, it replicates the same values for that field:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

$ python
Python 3.7.8 | packaged by conda-forge | (default, Nov 27 2020, 19:24:58) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> gpd.__version__
'0.8.1'
>>> import geopandas as gpd
>>> gpd.__version__
'0.8.1'
>>> gdf = gpd.read_file("filename.geojsons", driver="GeoJSONSeq")
/opt/conda/envs/jupiter-gis/lib/python3.7/site-packages/geopandas/geodataframe.py:422: RuntimeWarning: Sequential read of iterator was interrupted. Resetting iterator. This can negatively impact the performance.
  for feature in features_lst:
>>> gdf[["geometry","s2_cell_id"]]
                     geometry           s2_cell_id
0  POINT (-82.39925 34.85019)  9223372036854775807
1  POINT (-84.44996 33.87042)  9223372036854775807
2  POINT (-84.97259 34.77607)  9223372036854775807
3  POINT (-84.47147 34.08686)  9223372036854775807
4  POINT (-82.04219 33.50975)  9223372036854775807
5  POINT (-84.25836 30.44980)  9223372036854775807
6  POINT (-81.03490 34.00312)  9223372036854775807
7  POINT (-84.42884 33.65523)  9223372036854775807

```

Clearly something is not right with that GeoJSONSeq loading.  If the json-query (jq) program can read the data OK but geopandas does not, that suggests the file itself is OK but there is a bug in geopandas (or fiona or something).

An example feature (line) in the geojsons file is like the following line, only there are many of them:

```json
{"type": "Feature", "id": "790", "geometry": {"type": "Point", "coordinates": [-84.428837, 33.655232]}, "properties": {"state": "GA", "cityName": "Atlanta", "countryName": "United States", "uuid": "431de354-1411-4dc9-b6ad-d7eddafa5376", "s2_cell_id": 9868791200154488613}}
```

The bug could be related to the assumed size of the int value.  When the same feature data is output using a string to represent the s2_cell_id, then geopandas loads it OK.  (It issues the same warning about the sequential read interruption, that is not likely directly related to the issue, not sure.)

**Comment by martinfleis** [comment]
Thanks for the report!

`9223372036854775807` is a maximum value for 64-bit integer (it is `2^63 - 1`). You will not be able to read higher value as `Int64` due to how `fiona` handles integers (every integer is read as `Int64`):

https://github.com/Toblerity/Fiona/blob/7be39538f7317efec3e60b8dc722af7e8fea6d52/fiona/schema.pyx#L72-L77

There's nothing geopandas can do about it, so I would recommend moving the issue over to `fiona` repo.

**Comment by dazza-codes** [comment]
The backgound on these values is that they are google s2 CellID values, from a pure python implementation of [google s2 geometry](https://s2geometry.io/)
- https://github.com/sidewalklabs/s2sphere/blob/master/s2sphere/sphere.py#L893
- https://github.com/sidewalklabs/s2sphere/blob/master/s2sphere/sphere.py#L1046

It's described as:
```
    """S2 cell id
    The 64-bit ID has:
    - 3 bits to encode the face
    - 0-60 bits to encode the position
    - a 1
    The final 1 is the least significant bit (lsb) in the underlying integer
    representation and is returned with :func:`s2sphere.CellId.lsb`.
    see :cpp:class:`S2CellId`
    """
```

It _seems_ like it should be a 64-bit integer value.

WRT to geopandas vs. fiona issue - agreed that it belongs on fiona.  It's possible that issue is already logged in
- https://github.com/Toblerity/Fiona/issues/989
- sorry, didn't immediately see that connection

**Comment by martinfleis** [comment]
In Python 3, `int` is not bounded, but `int64` is. `s2` is using `int`, that is why they do not have an issue with it. `fiona` forces `int64` causing this erroneous reading.

I will close this here as it has been reported to fiona and should be resolved there. Thanks again for the report!
