### ISSUE TITLE
TST: pandas TestInterface.test_contains fails on `fixture 'nulls_fixture' not found`

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1735]
Pandas added a test using `nulls_fixture` in https://github.com/pandas-dev/pandas/pull/37867 . That test is failing in our CI with `fixture 'nulls_fixture' not found` - https://github.com/geopandas/geopandas/runs/1550967375?check_suite_focus=true#step:6:2802

Not sure if it is something to be fixed on our side or in pandas (I guess pandas).

**Comment by jorisvandenbossche** [comment]
That needs to be fixed on the pandas side (we (pandas) need to remember we can only use fixtures that are defined in the local conftest.py for those extension tests that are also used by external packages). 
Will do a PR in pandas. Thanks for the note!

**Comment by jorisvandenbossche** [comment]
Was fixed on the pandas side, this is no longer failing the tests, so closing.
