### ISSUE TITLE
BUG: 'GeometryArray' object has no attribute 'value_counts'

### ISSUE THREAD

**Issue by jamesmyatt** [geopandas/geopandas#1738]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
gdf["geometry"].value_counts()
```
<details>

```raw
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-fb6329993e01> in <module>
----> 1 gdf["geometry"].value_counts()

C:\tools\miniconda3\envs\project-dev\lib\site-packages\pandas\core\base.py in value_counts(self, normalize, sort, ascending, bins, dropna)
   1243         dtype: int64
   1244         """
-> 1245         result = value_counts(
   1246             self,
   1247             sort=sort,

C:\tools\miniconda3\envs\project-dev\lib\site-packages\pandas\core\algorithms.py in value_counts(values, sort, ascending, normalize, bins, dropna)
    790 
    791             # handle Categorical and sparse,
--> 792             result = Series(values)._values.value_counts(dropna=dropna)
    793             result.name = name
    794             counts = result._values

AttributeError: 'GeometryArray' object has no attribute 'value_counts'
```

</details>

#### Problem description

The "geometry" columns of a geopandas data frame should act like a regular pandas Series. This includes supporting "value_counts". 

I can't even monkey-patch it with something that uses `collections.Counter` since the geometry types are unhashable, i.e. the following also fails:

```
import collections
pd.Series(collections.Counter(gdf["geometry"]), name="geometry")
```

#### Expected Output

Same as `pd.Series.value_counts(*args, **kwargs)`

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:58:29) [MSC v.1916 64 bit (AMD64)]
executable : C:\tools\miniconda3\envs\project-dev\python.exe
machine    : Windows-10-10.0.18362-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.1.4
GDAL data dir: None
PROJ       : 7.1.1
PROJ data dir: C:\tools\miniconda3\envs\project-dev\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.5
fiona      : 1.8.18
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.3
mapclassify: 2.3.0
geopy      : 2.0.0
psycopg2   : None
geoalchemy2: None
pyarrow    : 2.0.0

</details>

**Comment by jorisvandenbossche** [comment]
@jamesmyatt Thanks for the report! Yes, `value_counts` is currently not implemented. In the past several of those functionalities were not working (eg like groupby, giving the "not hashable" error). But nowadays we actually use the WKB representation for those, so we should also do that for `value_counts`.

**Comment by jamesmyatt** [comment]
Thanks. It doesn't need to be clever. Just needs to work 😁 .

It would also be OK for me if it depended on the PyGEOS backend.

**Comment by jamesmyatt** [comment]
Would it be simple to do something like convert the geometry series to into a regular pandas binary series using WKB, then use regular value_counts and then convert the index back to a geometry type?

Alternatively, would it be OK to convert it to a text series using WKT, then use regular value_counts and just return that directly?

These are just ideas.

**Comment by jorisvandenbossche** [comment]
> Would it be simple to do something like convert the geometry series to into a regular pandas binary series using WKB, then use regular value_counts and then convert the index back to a geometry type?

Yes, that would be the idea. Something like this (untested code), method on GeometryArray:

```
def value_counts(self, ...):
    values = to_wkb(self)
    from pandas import Series, Index
    result = Series(values).value_counts(...)
    result.index = Index(from_wkb(result.index))
```

**Comment by m-richards** [comment]
I think I'll work on this as well, seems pretty straightforward and nice to have.

**Comment by martinfleis** [comment]
@m-richards Thanks!

**Comment by m-richards** [comment]
I've made a PR for this. It's probably worth noting this won't fix `gdf.value_counts("geometry")` because in pandas the method starts with this (https://github.com/pandas-dev/pandas/blob/3fe8e24a17170ad2296ecd81ba60e23cee763173/pandas/core/frame.py#L6379):
```python
 def value_counts(
        self,
        subset: Optional[Sequence[Label]] = None,
        normalize: bool = False,
        sort: bool = True,
        ascending: bool = False,
    ):
    if subset is None:
        subset = self.columns.tolist()
    counts = self.groupby(subset).grouper.size()
```
and `self.groupby(subset).grouper.size())` fails as `sort=True` is default in `groupby` and we can't sort geometry. It's not clear to me why that needs sort=True, when counts is sorted immediately below this if sort=True is passed to value_counts - but I haven't looked too hard on this point.

The other thing is that the index in the result of value counts is an index of objects, not geometry. I think that's tied to https://github.com/pandas-dev/pandas/issues/39133.

**Comment by jamesmyatt** [comment]
@m-richards , That's the code for DataFrame.value_counts. Better to look at Series.value_counts.

**Comment by jamesmyatt** [comment]
@m-richards , I think that's just the default groupby behaviour. Might be worth asking in the pandas repo whether that can be changed to sort=False.

**Comment by jorisvandenbossche** [comment]
Indeed, `sort=True` is the default in groupby. Pandas still needs it if `sort=False` is passed to `value_counts`. It's probably a welcome fix to pandas to avoid sorting in the groupby if the result is sorted.
