### ISSUE TITLE
QST: read_feather is very slow

### ISSUE THREAD

**Issue by JohanMollevik** [geopandas/geopandas#1740]
#### Code Sample, a copy-pastable example

```python
import pandas as pd
import geopandas as gpd
from datetime import datetime

print(datetime.now().replace(microsecond=0).time(),'read pandas')
df=pd.read_feather('cache/nmd-classes-33VWE-0_0.ftr')
print(df)
print(datetime.now().replace(microsecond=0).time(),'read geopandas')
gdf=gpd.read_feather('cache/nmd-classes-33VWE-0_0.ftr')
print(gdf)
print(datetime.now().replace(microsecond=0).time(),'done')
```

#### Problem description

I think that compared to pandas geopandas is extremely slow when reading feather files.

I think this is related to things discussed in this issue but maybe not the exact same problem
https://github.com/geopandas/geopandas/issues/460#issuecomment-334163897

Link to the feather file used to reproduce http://mollevik.se/~johan/nmd-classes-33VWE-0_0.ftr (185 MB)

Time to run with geopandas 5 min 29 seconds => 329 seconds
Time to run with pandas 0 min 17 seconds => 17 seconds

This shows that geopandas is 20 times slower than just pandas.
My expectation would be that the overhead for geosupport should not be that steep and that geopandas would not have a 20 times slowdown just from saving and restoring a geo column that is not used for any geographical operation.

My usecase needs to preserve the geodata but not process it in pandas in this stage, in the later stages where I do process the geodata I will have filtered it to much fewer rows so there performance is much less of an issue.

####  Output

14:38:19 read pandas
         ClassNumber                                           geometry   tile subtile       Id     x     y
0                114  b'\x01\x01\x00\x00\x00\xfc\xff\xff\xffC\x84\x1...  33VWE     0_0        0     0     0
1                114  b'\x01\x01\x00\x00\x00\xfe\xff\xff\xffk\x84\x1...  33VWE     0_0        1     0     1
2                114  b'\x01\x01\x00\x00\x00\x02\x00\x00\x00\x94\x84...  33VWE     0_0        2     0     2
3                 42  b'\x01\x01\x00\x00\x00\x04\x00\x00\x00\xbc\x84...  33VWE     0_0        3     0     3
4                 52  b'\x01\x01\x00\x00\x00\x06\x00\x00\x00\xe4\x84...  33VWE     0_0        4     0     4
...              ...                                                ...    ...     ...      ...   ...   ...
7535020          112  b'\x01\x01\x00\x00\x00\xf8\n\x00\x002\x18 Ap\x...  33VWE     0_0  7535020  2744  2740
7535021          115  b'\x01\x01\x00\x00\x00\xfa\n\x00\x00F\x18 Ap\x...  33VWE     0_0  7535021  2744  2741
7535022          115  b'\x01\x01\x00\x00\x00\xfb\n\x00\x00Z\x18 Ap\x...  33VWE     0_0  7535022  2744  2742
7535023          115  b'\x01\x01\x00\x00\x00\xfb\n\x00\x00n\x18 Ap\x...  33VWE     0_0  7535023  2744  2743
7535024          115  b'\x01\x01\x00\x00\x00\xfd\n\x00\x00\x82\x18 A...  33VWE     0_0  7535024  2744  2744

[7535025 rows x 7 columns]
14:38:36 read geopandas
         ClassNumber                        geometry   tile subtile       Id     x     y
0                114  POINT (499985.000 6500035.000)  33VWE     0_0        0     0     0
1                114  POINT (499995.000 6500035.000)  33VWE     0_0        1     0     1
2                114  POINT (500005.000 6500035.000)  33VWE     0_0        2     0     2
3                 42  POINT (500015.000 6500035.000)  33VWE     0_0        3     0     3
4                 52  POINT (500025.000 6500035.000)  33VWE     0_0        4     0     4
...              ...                             ...    ...     ...      ...   ...   ...
7535020          112  POINT (527385.000 6472595.000)  33VWE     0_0  7535020  2744  2740
7535021          115  POINT (527395.000 6472595.000)  33VWE     0_0  7535021  2744  2741
7535022          115  POINT (527405.000 6472595.000)  33VWE     0_0  7535022  2744  2742
7535023          115  POINT (527415.000 6472595.000)  33VWE     0_0  7535023  2744  2743
7535024          115  POINT (527425.000 6472595.000)  33VWE     0_0  7535024  2744  2744

[7535025 rows x 7 columns]
14:44:05 done

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.7.3 (default, Jul 25 2020, 13:03:44)  [GCC 8.3.0]
executable : /usr/bin/python3
machine    : Linux-4.4.0-18362-Microsoft-x86_64-with-debian-10.6

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.7.1
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 2.4.4
GDAL data dir: /home/jmollevi/.local/lib/python3.7/site-packages/fiona/gdal_data
PROJ       : 7.0.1
PROJ data dir: /home/jmollevi/.local/lib/python3.7/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.0
pandas     : 1.1.4
fiona      : 1.8.13.post1
numpy      : 1.18.5
shapely    : 1.7.0
rtree      : None
pyproj     : 2.6.1.post1
matplotlib : 3.1.1
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : 1.0.1

</details>

**Comment by brendan-ward** [comment]
The key difference between feather in pandas and feather in geopandas is that the geometry column is deserialized from WKB format in the feather file into geometry objects; reading this in pandas skips the deserialization.

The performance of that step is a function of the libraries available in your environment.  It looks like you do not have `pygeos` installed.  `pygeos` performs this step much faster than `shapely` (the geometry backend when `pygeos` is not available).

With `pygeos` installed, I observe that pandas takes 6.1s, whereas geopandas takes 7.3s.

See the [docs](https://geopandas.readthedocs.io/en/latest/getting_started/install.html#using-the-optional-pygeos-dependency) for using `pygeos` on GeoPandas.  Conda is recommended for installing these to ensure compatible dependencies; there are performance issues when using the pip-installed version of `shapely` alongside `pygeos`.

If you are unable to install `pygeos` _and_ you know the CRS, geometry column, etc (this is all stored in metadata in the feather file and used when geopandas reads from feather), you could read this in pandas to avoid the deserialization step, filter records, then convert the column containing WKB into a GeoSeries.  Right now the methods used are part of the internal API, but work is underway in #1710 to expose those.

However, the metadata and encoding used within feather files is still experimental, so I would advise against building up much code around handling deserialization from feather outside of the methods provided by geopandas.  I recommend installing `pygeos` (many things will be faster, not just this).

**Comment by JohanMollevik** [comment]
Thanks, installing pygeos made my current test run take 10 and 11 seconds respectivly, effectivly removing the performance penalty.
