### ISSUE TITLE
BUG: Colorbar issue if series has zero variance?

### ISSUE THREAD

**Issue by JamesSample** [geopandas/geopandas#1743]
#### Code Sample, a copy-pastable example

```python
import geopandas as gpd

cities = gpd.read_file(gpd.datasets.get_path('naturalearth_cities'))
cities['data'] = 10
cities.plot(column='data', cmap='plasma', legend=True)

```

![image](https://user-images.githubusercontent.com/12967176/102612211-9fca4100-4130-11eb-8d1f-d84c4e871767.png)

#### Problem description

When colouring features using a column in a dataframe, `gdf.plot()` assigns incorrect colours if the variance of the series is zero (i.e. if all values are constant). Perhaps `gdf.plot()` should not be used in such cases, but I was using a script to auto-generate lots of maps, and a few of the series had constant values. It would be great if geopandas assigned correct colours in these cases, rather than having my script explicitly check and use a different plotting method for constant values.

#### Expected Output

The points on the plot above should be coloured pink-ish (for value = 10) and not deep blue/purple (for value = 9).

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05)  [GCC 7.5.0]
executable : /opt/conda/bin/python
machine    : Linux-4.14.127+-x86_64-with-glibc2.10

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.1
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.1.3
GDAL data dir: None
PROJ       : 7.0.1
PROJ data dir: /opt/conda/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.5
fiona      : 1.8.13.post1
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.3
mapclassify: 2.3.0
geopy      : 2.0.0
psycopg2   : 2.8.6 (dt dec pq3 ext lo64)
geoalchemy2: 0.8.4
pyarrow    : 2.0.0

</details>

**Comment by martinfleis** [comment]
Hi, thanks for the report.

This is a known issue already reported as #1162. It is a bug in `matplotlib` which should be fixed there https://github.com/matplotlib/matplotlib/issues/15566.

The current workaround is to specify the minimum and maximum for colorbar manually.

```py
import geopandas as gpd

cities = gpd.read_file(gpd.datasets.get_path('naturalearth_cities'))
cities['data'] = 10
cities.plot(column='data', cmap='plasma', legend=True, vmin=9, vmax=11)
```
