### ISSUE TITLE
QST: to_crs gives very slightly different results on 0.8.1 compared to an older version of geopandas (0.6.2)

### ISSUE THREAD

**Issue by lieuzhenghong** [geopandas/geopandas#1748]
- [X] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com) <-- not a usage related question

---

#### Question about geopandas

I am trying to replicate some research I did a year ago. 
However, it looks like the new version of geopandas (or one of its dependencies)
gives _very_ slightly different results when calling `to_crs`.

This is the minimum viable reproduction:

I have read the 
[Craft Minimal Bug Reports](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) link
but unfortunately I can't have the data in the file because after loading the csv string in with `gpd.GeoDataFrame(pd.read_csv())`
I get the error `AttributeError: 'Series' object has no attribute 'to_crs'`.
But I have put the csv string if you can get it working.

```python
import geopandas as gpd

# I can't use this: I get 'Series' object has no attribute 'to_crs' error
# csv_string = """,CID,geometry,party,pd
# 0,1,POINT (-5201070.724318862 6770052.606328751),D,0"""

gdf = gpd.read_file("all_rvps_before_conversion_old.shp")
# This assert passes on both machines
assert str(gdf["geometry"][0]) == "POINT (-5201070.724318862 6770052.606328751)"

# Now convert to crs
gdf = gdf.to_crs({"init": "epsg:4326"})
print(str(gdf["geometry"][0])) # on old machine: POINT (-73.59250979083568 41.01678126113871)
# This assert passes on my new machine but fails on my old one
assert str(gdf["geometry"][0]) == "POINT (-73.59250974534255 41.01678109722333)"

print("All asserts passed!")
```

The full traceback is as follows:

```bash
lieu@lieu-ubuntu ~/d/geographically_sensitive_dislocation (master)> 
python minimum_reproducible_to_crs_bug.py
POINT (-73.59250979083568 41.01678126113871)
Traceback (most recent call last):
  File "minimum_reproducible_to_crs_bug.py", line 16, in <module>
    assert str(gdf["geometry"][0]) == "POINT (-73.59250974534255 41.01678109722333)"
AssertionError
```

I have done a `conda list -e > requirements.txt` for both machines and put them in a GitHub Gist
[here](https://gist.github.com/lieuzhenghong/f8569a6b17c155757c863719af6c5914) so the issue can be easily reproduced by doing 
```
conda create --name human-compactness --file requirements.txt
conda create --name old-human-compactness --file requirements_old.txt
```

Reproduced on my new machine:

```bash
(human-compactness) lieu@DESKTOP-NV19JNO:~/dev/geographically_sensitive_dislocation$ python minimum_reproducible_to_crs_bug.py
/home/lieu/miniconda3/envs/human-compactness/lib/python3.8/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
POINT (-73.59250974534255 41.01678109722333)
All asserts passed!

(human-compactness) lieu@DESKTOP-NV19JNO:~/dev/geographically_sensitive_dislocation$ conda activate old-human-compactness
(old-human-compactness) lieu@DESKTOP-NV19JNO:~/dev/geographically_sensitive_dislocation$ python minimum_reproducible_to_crs_bug.py
POINT (-73.59250979083568 41.01678126113871)
Traceback (most recent call last):
  File "minimum_reproducible_to_crs_bug.py", line 15, in <module>
    assert str(gdf["geometry"][0]) == "POINT (-73.59250974534255 41.01678109722333)"
AssertionError
```

**Comment by martinfleis** [comment]
cc @snowman2

**Comment by snowman2** [comment]
@lieuzhenghong, what is the original CRS?

**Comment by snowman2** [comment]
Also, I noticed that you had pyproj 1.9.6 in one environment and 2.6.1 in another. My guess is that it has something to do with that.

**Comment by lieuzhenghong** [comment]
> 
> 
> @lieuzhenghong, what is the original CRS?

PROJCS["Equidistant_Conic",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0],UNIT["Degree",0.0174532925199433],AUTHORITY["EPSG","4269"]],PROJECTION["Equidistant_Conic"],PARAMETER["latitude_of_center",0],PARAMETER["longitude_of_center",0],PARAMETER["standard_parallel_1",20],PARAMETER["standard_parallel_2",60],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]

**Comment by snowman2** [comment]
I created this test script:
```python
from pyproj import Transformer
wkt = 'PROJCS["Equidistant_Conic",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0],UNIT["Degree",0.0174532925199433],AUTHORITY["EPSG","4269"]],PROJECTION["Equidistant_Conic"],PARAMETER["latitude_of_center",0],PARAMETER["longitude_of_center",0],PARAMETER["standard_parallel_1",20],PARAMETER["standard_parallel_2",60],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]'
tr = Transformer.from_crs(wkt, "EPSG:4326", always_xy=True)
print(tr.transform(-5201070.724318862, 6770052.606328751))
```
And tested it with pyproj 3 (PROJ 7.2):
```
$ python testprj.py 
(-73.59250979083568, 41.01678126113871)
$ PROJ_NETWORK=ON python testprj.py 
(-73.59250974534255, 41.01678109722333)
```

The first result matches the old version. The second result with `PROJ_NETWORK=ON` matches the new version. This indicates to me that your old machine is missing the proper transform grids and the new version is not. As such, I am pretty sure this is not an issue with geopandas, pyproj, or PROJ.

For reference: https://pyproj4.github.io/pyproj/stable/transformation_grids.html

Hopefully this helps.

**Comment by martinfleis** [comment]
Thank you @snowman2 for the explanation!
