### ISSUE TITLE
Pandas version compatibility

### ISSUE THREAD

**Issue by jwass** [geopandas/geopandas#175]
Which Pandas versions should we explicitly support and test against?

Now that 0.15 is out, we should add it to the travis config, but keep going back to 0.13? The tests are already huge so I'm hesitant to add even more.

Any reason not to drop 0.13?

**Comment by kjordahl** [comment]
I agree, we don't want the matrix any bigger than it is already. I say we keep the latest 2 major revisions, and master. Now 0.16.0 is out as well, so we'll drop both 0.13 and 0.14. PR #192.
