### ISSUE TITLE
rtree wheels

### ISSUE THREAD

**Issue by snowman2** [geopandas/geopandas#1758]
Looks like rtree has wheels now:
- https://github.com/Toblerity/rtree/pull/163
- https://pypi.org/project/Rtree/#files

With this change, should it be added as a main dependency instead of optional?

**Comment by martinfleis** [comment]
Not sure. With `pygeos` you don't need `rtree` for spatial indexing. The user now has a choice which package to use so there's no need to force installing of `rtree`. I know we do that in `conda` recipe but my assumption is that with shapely 2.0 `STRtree` (from pygeos) will be used primarily anyway and `rtree` will become an optional alternative. Which means to add it as a main dependency now and then remove it relatively soon.

**Comment by snowman2** [comment]
Makes sense to me. Probably just an update to the installation instructions would be needed then.
