### ISSUE TITLE
BUG: Reprojecting Geojson from WGS84 to EPSG:32749 is erronous

### ISSUE THREAD

**Issue by sid-ks** [geopandas/geopandas#1761]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

---

#### Code Sample, a copy-pastable example

```python

import geopandas as gpd
import rasterio
from rasterio.mask import mask
import json

def reproj(gjsonpath,epsgcode):
    data = gpd.read_file(gjsonpath)

    # Reproject the geojson
    # tried data.to_crs(epsgcode)
    # and the one below
    data = data.to_crs(f'EPSG:{epsgcode}')

    # printing UTM zone shows no errors in UTM zone
    crs = data.crs.utm_zone
    print(f'\n UTM zone... - {crs}')
    
    # extracting new geojson for further processing with rasterio, which is for clipping a raster
    poly = data.geometry
    return [json.loads(poly.to_json())['features'][0]['geometry']]

with rasterio.open('path/to/tif') as src:

            out_meta = src.meta.copy()
            epsg_code = int(src.crs.data['init'][5:])

            print(out_meta,'\n')

            print(epsg_code, '\n')

            coords = reproj('/path/to/WGS84geojson/abc.geojson',epsg_code)

            out_img, out_transform = mask(src, coords, crop=True)

```

#### Problem description

I frequently use Geopandas to convert Geojsons to almost any EPSG code, and it works well, but I stumbled upon this error as a surprise.

Using rasterio I simply take the CRS of the GeoTIFF file im working with, then send the EPSG code to Geopandas' to_crs() function, to convert my WGS84 geojson to whatever CRS the GeoTIFF file is, so that I can clip the GeoTIFF and continue the workflow.

I used this on GeoTIFF files with EPSG:32748 projection and that worked well, but EPSG:32749 ends in error.

Looking at the Geojson output after conversion by Geopandas, it seems the "Longitudes" are not being converted properly.

##### My Input Geojson -

{"type": "FeatureCollection", "features": [ {"type": "Feature","properties": { },"geometry": { "type": "Polygon", "coordinates": [ [ [106.48395538330078, -6.155403427850139 ], [106.48283958435059, -6.155787439040594], [106.48309707641602, -6.164960957140216 ], [106.49438381195068, -6.166752974718632 ],[ 106.49558544158936, -6.165302294288643 ], [106.49605751037598, -6.159286194876414 ], [106.49489879608153, -6.156086114219029 ], [106.48824691772461, -6.154251392613409], [ 106.48395538330078, -6.155403427850139 ] ] ] } } ] }

##### Output Geojson after conversion with my reproj function -

[{'type': 'Polygon', 'coordinates': [[[-154.36913294129772, 9317499.90843731], [-277.8360450650216, 9317456.279798925], [-240.63701934635174, 9316439.348094093], [1013.5772078567534, 9316251.262744963], [1145.5639648492797, 9316413.242389383], [1192.310020961042, 9317080.748276107], [1060.7238905857666, 9317434.4855076], [320.80853154388024, 9317631.678669509], [-154.36913294129772, 9317499.90843731]]]}]

#### Expected Output

Not sure

#### Output of ``geopandas.show_versions()``

SYSTEM INFO
-----------
python     : 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
executable : /usr/bin/python3
machine    : Linux-5.4.0-58-generic-x86_64-with-glibc2.29

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.1
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 2.4.4
GDAL data dir: /home/username/.local/lib/python3.8/site-packages/fiona/gdal_data
PROJ       : 7.0.1
PROJ data dir: /home/username/.local/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.4
fiona      : 1.8.17
numpy      : 1.19.4
shapely    : 1.7.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.3
mapclassify: None
geopy      : None
psycopg2   : 2.8.4 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : None
None

 ---------------------------------------------

Thanks in advance.

**Comment by martinfleis** [comment]
Thanks for the report. Based on the results from [epsg.io](https://epsg.io/transform#s_srs=4326&t_srs=32749&x=106.0666667&y=-6.0000000) I think that you're right that the result is not correct. 

It seems to be an issue in `pyproj` (cc @snowman2). Consider the following snippet:

```python
>>> import pyproj

>>> transformer = pyproj.Transformer.from_crs(4326, 32749)
>>> transformer.transform(-6.155403427850139, 106.48395538330078,)
(-154.36913294129772, 9317499.90843731)
```

The epsg.io returns the same `y` coordinate, but `x` is `~46618`.

Since we use `pyproj` to do coordinate transformation, it seems that this should be fixed there.

**Comment by snowman2** [comment]
@sid-ks, as a side note, you may be interested in `rioxarray`: https://corteva.github.io/rioxarray/stable/examples/clip_geom.html
```
import geopandas
import rioxarray

xds = rioxarray.open_rasterio("path/to/tif")
gdf = geopandas.read_file("/path/to/WGS84geojson/abc.geojson")
clipped = xds.rio.clip(geodf.geometry.apply(mapping), gdf.crs)
clipped.rio.to_raster("clipped.tif")
```

**Comment by snowman2** [comment]
Forwarded: https://github.com/OSGeo/PROJ/issues/2497

**Comment by snowman2** [comment]
Also, there is a [to_epsg()](https://rasterio.readthedocs.io/en/latest/api/rasterio.crs.html#rasterio.crs.CRS.to_epsg) method on the rasterio CRS class:
```python
epsg_code = src.crs.to_epsg()
```

**Comment by sid-ks** [comment]
> Also, there is a [to_epsg()](https://rasterio.readthedocs.io/en/latest/api/rasterio.crs.html#rasterio.crs.CRS.to_epsg) method on the rasterio CRS class:
> 
> ```python
> epsg_code = src.crs.to_epsg()
> ```

Thanks for these tips. Will try them out :+1:

**Comment by snowman2** [comment]
Based on the upstream response, the results are expected.

**Comment by martinfleis** [comment]
Thank you @snowman2 for the enquiry! Closing as not-a-bug.

@sid-ks Can you check that the result is, in fact, correct in your case and works as expected? Let us know if you still think it should produce a different result.

**Comment by sid-ks** [comment]
> Thank you @snowman2 for the enquiry! Closing as not-a-bug.
> 
> @sid-ks Can you check that the result is, in fact, correct in your case and works as expected? Let us know if you still think it should produce a different result.

Hi, thanks for your support. 

This below tip was useful.

```epsg_code = src.crs.to_epsg()```

The error stemmed from the fact that my AOI was actually inside 32748 UTM 48S and not in 32749 UTM 49S, hence converting WGS84 AOI to 32749 will obviously yield wrong coordinates.

Thanks again @martinfleis and @snowman2 , and this can be closed, as it is not-a-bug. 

On the other hand, @snowman2 is there a way to first check if an AOI is within the extent of an image, before proceeding to clipping via rasterio? I understand this question is outside of Geopandas domain, can you link me to some material on this? Thanks

**Comment by martinfleis** [comment]
> On the other hand, is there a way to first check if the WGS 84 is being converted to an erroneous UTM and maybe warn the user?

I don't think that is something we would want to do. After all, the transformation is still correct, although it may be less precise. I can imagine cases where this is the desired output.

**Comment by snowman2** [comment]
> is there a way to first check if the WGS 84 is being converted to an erroneous UTM 

This method might be helpful for you to do yourself: https://github.com/geopandas/geopandas/pull/1646

**Comment by sid-ks** [comment]
> > is there a way to first check if the WGS 84 is being converted to an erroneous UTM
> 
> This method might be helpful for you to do yourself: #1646

the [https://github.com/geopandas/geopandas/blob/36521787c3e6484c00c2ffb8cdde60798d6d1616/geopandas/geoseries.py#L873]estimate_utm() function looks handy! Thanks! :smile:
