### ISSUE TITLE
Distance function returning 0 for some values contained in a polygon

### ISSUE THREAD

**Issue by emilianosantin** [geopandas/geopandas#1769]
- [ ] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

---

#### 
Hi
It is me again. I am trying to find the minimum distance between points and the coastline. I am using a shapefile from NOAA nos80k.shp <http://pubs.usgs.gov/of/2012/1005/data/basemaps/nos80k/nos80k.zip> to measure between points and the shape file. Most of the points are inside the shapefile, some even in the mid plains far enough from the coast and I get 0 values. I tried to different ways to iterate through the rows (answers in stackoverflow). Again I am not sure why I get is zero values even if they far away from the coastline,  both files have been reprojected to the same crs. Some points return values that are clearly wrong from their distance to the coast. Thanks 

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python


```

**Comment by martinfleis** [comment]
Moving to #1768
