### ISSUE TITLE
ENH: add argument to dissolve() to keep the column after dissolving

### ISSUE THREAD

**Issue by Imanflow** [geopandas/geopandas#1771]
Is your feature request related to a problem?

No 

Describe the solution you'd like

When applying dissolve(by=column), that column is passed as the index in the new GeoDataFrame. In my opinion, that might make more sense in Pandas, but in a GIS context, you usually want to keep that column, specially if your next step is saving that GDF to file. 

API breaking implications

None

Describe alternatives you've considered

None
Additional context

**Comment by martinfleis** [comment]
Thanks for the suggestion. `dissolve` mirrors pandas `groupby`, that is why it uses the column as an index.

We can certainly add a keyword controlling it but all it would do would be to call `reset_index()` before returning.

So in practice, you would either have to manually specify keyword or manually reset index.

```py
gdf.dissolve("col", reset_index=True)

gdf.dissolve("col").reset_index()
```

Not sure if the keyword actually helps anything :). Resetting index by default would be a breaking change deviating from pandas which is something we would probably not do.

> specially if your next step is saving that GDF to file.

That should not be a problem even now, is it? We have relatively clever heuristic deciding when the index should be saved. Alternatively you can specify `df.to_file(path, index=True)` and always save index. See https://geopandas.readthedocs.io/en/latest/docs/reference/api/geopandas.GeoDataFrame.to_file.html#geopandas.GeoDataFrame.to_file

**Comment by Imanflow** [comment]
To be honest, I did not know about the option index=True, which solves exactly the extra line that i wanted to save. So, I guess this can be closed?

**Comment by martinfleis** [comment]
Great. Marking it resolved then ;).
