### ISSUE TITLE
ENH: include CRS in "to_json"

### ISSUE THREAD

**Issue by xuqinghan** [geopandas/geopandas#1774]
_Note (by @martinfleis): see the discussion below for details on the enhancement proposal._

#### Question about geopandas

gdf.to_json() 

> {"type": "FeatureCollection", 
> "features": [{**"id": "0500"**, "type": "Feature", **"properties": {}**, "geometry": ...}]
> }
> 

gdf.to_file('temp.geojson', driver='GeoJSON')

> {
> "type": "FeatureCollection",
> **"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::32246" } },**
> "features": [
> { "type": "Feature", **"properties": { "id": "0500" }**, "geometry": ...}]
> }

the   "id" is in "properties" for .to_file(driver='GeoJSON')  
and to_json miss the "crs"

Why they have different behavior?

and

How to:

1  let to_json()  output "crs" ?

2 let to_file()  output   each feature  with "id" as  to_json()?

Thanks.

**Comment by martinfleis** [comment]
Each of the methods is managed differently. `to_json` is internal GeoPandas method, so the creation of JSON is managed by GeoPandas.

https://github.com/geopandas/geopandas/blob/eabe4049dd8596526b39f2a4beca470f4b84943e/geopandas/geodataframe.py#L645

`to_file()` uses `fiona` package to write files, hence the structure of the JSON depends on `fiona` and there's not much we can do about it.

One thing we may is to report CRS in `to_json`, but I am not sure what the specification is and how to get it from `pyproj`.

> let to_json() output "crs" ?

The method does not return CRS currently. You'll have to edit JSON manually.

> let to_file() output each feature with "id" as to_json()?

I don't think it is possible, but there may a way to control that in fiona.

**Comment by swiss-knight** [comment]
I also miss the CRS when dumping `.to_json()`, even it's a proper `pyproj.crs.crs.CRS` type containing, e.g. 
```
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich```

**Comment by JoakimJoensuu** [comment]
Any update on this?

**Comment by martinfleis** [comment]
@JoakimJoensuu not that I am aware of. I'll put a milestone to it so it is part of the next release. It is in line with our tentative roadmap anyway.

@snowman2 Is there a way to get the CRS in the required format (i.e. `urn:ogc:def:crs:EPSG::32246`) from the `pyproj.CRS`?

**Comment by snowman2** [comment]
> Is there a way to get the CRS in the required format (i.e. urn:ogc:def:crs:EPSG::32246) from the pyproj.CRS?

The closest thing is `to_authority`|`to_epsg`.

**Comment by martinfleis** [comment]
Linking the OGC CRS URN specification here: https://www.ogc.org/ogcUrnPolicy and GeoJSON specs https://gist.github.com/sgillies/1233327 as a reference. 

We should be able to get the string as

```python
authority, code = df.crs.to_authority()
ogc_crs = f"urn:ogc:def:crs:{authority}::{code}"
```

If someone wants to turn this into a PR, feel free to pick it up.

**Comment by JoakimJoensuu** [comment]
Should `crs` actually be removed from `gdf.to_file('temp.geojson', driver='GeoJSON')` instead of adding it to `gdf.to_json()`?

https://datatracker.ietf.org/doc/html/rfc7946#section-4

```
Note: the use of alternative coordinate reference systems was specified in [GJ2008], but it has been removed from this version of the specification because the use of different coordinate reference systems
```

To respect RFC7946 `crs` key could be removed and instead ability to add `properties` could be added.

**Comment by martinfleis** [comment]
@JoakimJoensuu I wouldn't remove it as per the following bit from the linked spec:

> However, where all
   involved parties have a prior arrangement, alternative coordinate
   reference systems can be used without risk of data being
   misinterpreted.

The change in the spec assuming wgs84 CRS is being dealt with in #416 by the addition of `to_wgs84` keyword. The creation of GeoJSON using `gdf.to_file` is managed by fiona and any change should be implemented there.

**Comment by simberaj** [comment]
I'm linking a PR to resolve this. IMHO the case where CRS is WGS84 (EPSG 4326) could also be converted back to no CRS being reported since that is the GeoJSON default, but I'm not sure about the implications of either design.
