### ISSUE TITLE
BUG: Empty Point given to construct a GeoDataFrame leads to a "GEOMETRYCOLLECTION EMPTY" instead of a "POINT EMPTY"

### ISSUE THREAD

**Issue by swiss-knight** [geopandas/geopandas#1779]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

Hello,

I met some issues while playing around with a GeoDataFrame, especially when this one contains empty geometries.

Here are some results of my early exploration:

```
import shapely
from shapely.geometry import Point
import geopandas as gpd

print(shapely.__version__) # 1.7.1
print(gpd.__version__) # 0.8.1

point = Point(1,1)
empty_point_1 = Point()
gdf = gpd.GeoDataFrame(geometry=[point, empty_point_1])

gdf # check the output

# gdf.plot() # TypeError output
```
```
>>> gdf
                   geometry
0   POINT (1.00000 1.00000)
1  GEOMETRYCOLLECTION EMPTY
```

#### Expected Output

```
>>> gdf
                   geometry
0   POINT (1.00000 1.00000)
1               POINT EMPTY
```

#### Additional issue    

In addition, if I construct a GeoDataFrame using empty points I got some `RuntimeWarning`:
```
>>> gpd.GeoDataFrame(geometry=[empty_point_1, empty_point_1])
/usr/local/lib/python3.8/dist-packages/geopandas/array.py:689: RuntimeWarning: All-NaN slice encountered
  np.nanmin(b[:, 0]),  # minx
/usr/local/lib/python3.8/dist-packages/geopandas/array.py:690: RuntimeWarning: All-NaN slice encountered
  np.nanmin(b[:, 1]),  # miny
/usr/local/lib/python3.8/dist-packages/geopandas/array.py:691: RuntimeWarning: All-NaN slice encountered
  np.nanmax(b[:, 2]),  # maxx
/usr/local/lib/python3.8/dist-packages/geopandas/array.py:692: RuntimeWarning: All-NaN slice encountered
  np.nanmax(b[:, 3]),  # maxy
                   geometry
0  GEOMETRYCOLLECTION EMPTY
0  GEOMETRYCOLLECTION EMPTY
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
executable : /usr/bin/python3
machine    : Linux-5.4.0-60-generic-x86_64-with-glibc2.29

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.0
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 2.4.4
GDAL data dir: /usr/local/lib/python3.8/dist-packages/fiona/gdal_data
PROJ       : 7.2.0
PROJ data dir: /usr/local/lib/python3.8/dist-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.2.0
fiona      : 1.8.18
numpy      : 1.19.5
shapely    : 1.7.1
rtree      : None
pyproj     : 3.0.0.post1
matplotlib : 3.3.3
mapclassify: None
geopy      : None
psycopg2   : 2.8.6 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : None

</details>

**Comment by jorisvandenbossche** [comment]
@swiss-knight This is a known issue with Shapely, the library that is being used here by GeoPandas: https://github.com/Toblerity/Shapely/issues/742

A workaround, for now, is to create the empty geometry from WKT with `from shapely import wkt; wkt.loads("POINT EMPTY")`. 

Since it's something that needs to be fixed in Shapely (and it will also be fixed in Shapely 2.0), I am closing the issue here.

For the warnings shown when printing the values in the console, this was recently fixed in geopandas (https://github.com/geopandas/geopandas/pull/1673), and that will be fixed in the next geopandas release.
