### ISSUE TITLE
BUG: Malta is missing from naturalearth_lowres

### ISSUE THREAD

**Issue by MeliBall** [geopandas/geopandas#1780]
BUG: Malta is missing from naturalearth_lowres

**Comment by martinfleis** [comment]
Thanks for the notice!

We are directly using data from NaturalEarthData in the lowest resolution for the purpose of illustration more than anything else. Malta is probably too tiny for the resolution. Anyway, issues of this kind need to be raised there. There is one related already open https://github.com/nvkelso/natural-earth-vector/issues/345.

If you need higher resolution, I recommend downloading it from https://www.naturalearthdata.com directly. Note that you can pass the link to zip file directly to `geopandas.read_file`.
