### ISSUE TITLE
BUG: Stop gdal from getting the projection of a raster when the projection is incorrect.

### ISSUE THREAD

**Issue by Housyou** [geopandas/geopandas#1783]
The file 'windfield.tif' could be downloaded [here](https://github.com/Housyou/MyFiles).
If I don't import geopandas, the code
`from osgeo import gdal`
`res = gdal.Open(r'windfield.tif',0)`
`print(res.GetProjection())`
will run successfully, and the result is
`GEOGCS["Greenwich",DATUM["unnamed",SPHEROID["unnamed",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST]]`
although there are several warnings:
`proj_create_from_database: datum not found`
`proj_create_from_database: ellipsoid not found`
`proj_create_from_database: prime meridian not found`
because the datum is "unnamed". But when I import geopandas, it becomes
`Fatal Python error: PyThreadState_Get: no current thread`
`Python runtime state: initialized`

`Current thread 0x00001004 (most recent call first):`
`  File "C:\software\miniconda3\envs\py\lib\site-packages\osgeo\gdal.py", line 2074 in GetProjection`
`  File "D:/\u5730\u7406\u4fe1\u606f\u7cfb\u7edf\u5de5\u7a0b/bigwork/main/with_postgis.py", line 4 in <module>`

**Comment by martinfleis** [comment]
Hi, I think you wanted to report this to GDAL. GeoPandas is not involved in this at all.

**Comment by Housyou** [comment]
> 
> 
> Hi, I think you wanted to report this to GDAL. GeoPandas is not involved in this at all.

Sorry, I'm not familiar with geopandas... It's because I meet this problem when I import geopandas that I report it here. I am very sorry for making this mistake...

**Comment by jorisvandenbossche** [comment]
And for the reason that importing geopandas changes something, that's probably due to a bad interaction between the python gdal bindings, and the fiona package with alternative gdal bindings.

**Comment by Housyou** [comment]
> 
> 
> And for the reason that importing geopandas changes something, that's probably due to a bad interaction between the python gdal bindings, and the fiona package with alternative gdal bindings.

Thank you. It's necessary for me to learn more about gdal, fiona and so on.🙂
