### ISSUE TITLE
ENH: implement to_crs on GeometryArray level

### ISSUE THREAD

**Issue by johnflavin** [geopandas/geopandas#1784]
In a `GeoSeries`, both the geometries and their CRS is stored in the underlying `GeometryArray`. However, the operation of projecting those geometries to a different CRS is only available in the `GeoSeries.to_crs` method. There is no corresponding `GeometryArray.to_crs`.

I wondered why that is. Is there some reason? Was it just missed when the `GeometryArray` was created? 

If the latter, do you think it would be useful to migrate the `to_crs` implementation over to `GeometryArray`, and modify `GeoSeries.to_crs` to use that?

Example: I had a set of latitudes and longitudes in one CRS, and wanted to create points and immediately project them to another CRS. I wanted to do something like this:
```python
gdf['col_name'] = (geopandas.points_from_xy(gdf['longitude'], gdf['latitude'], crs=input_crs)
                   .to_crs(output_crs))
```
However, this did not work. `points_from_xy` returns a `GeometryArray`, which does not have `to_crs`.

Now, I could always wrap this `GeometryArray` in a `GeoSeries` and then it would work. But I would rather not have to, when the `GeometryArray` has all the information it needs to do the transformation other than the actual code.

**Comment by martinfleis** [comment]
`GeometryArray` initially did not support CRS by itself, that is a relatively recent change. So it was not possible to have the method on an array level. Since GeometryArray is more inward-facing class, not really a part of public API now, I am not concerned much about where `to_crs` sits. However, your use case makes sense, so we may consider moving it.

**Comment by johnflavin** [comment]
> GeometryArray is more inward-facing class, not really a part of public API now

Given this, maybe the better change would be to have `points_from_xy` return a `GeoSeries`?

**Comment by martinfleis** [comment]
I was thinking about that but it is tricky. `GeoSeries` comes with an index which tries to get aligned with the DataFrame index. So having an index which is not a simple range in gdf, the following would cause a lot of trouble.

```
gdf['points'] = geopandas.points_from_xy([0, 0, 1], [1, 1, 2], crs=4326)
```

`GeometryArray` does not have this issue. 

> GeometryArray is more inward-facing class, not really a part of public API now

It is a bit grey zone at the moment.
