### ISSUE TITLE
BUG: Invalid Projection EPSG:9822

### ISSUE THREAD

**Issue by leilaher** [geopandas/geopandas#1788]
- [yes ] I have checked that this issue has not already been reported.

- [ yes] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
# I tried to import specific function 'from_epsg' from fiona module
from fiona.crs import from_epsg
# And then set the GeoDataFrame's coordinate system to OGC-WKT Name:Albers_Conic_Equal_Area (i.e. epsg code 9822)
newdata.crs = from_epsg(9822)
# But I obtained: 
CRSError: Invalid projection: +init=epsg:9822 +no_defs +type=crs: (Internal Proj Error: proj_create: crs not found)

Then I tried setting GDAL_DATA:
import os
os.environ['GDAL_DATA'] = 'C:\\Users\\lch2\\.conda\\envs\\FFP\\Library\\share\\gdal'
print('GDAL_DATA' in os.environ)
from osgeo import osr
srs = osr.SpatialReference() # Declare a new SpatialReference 
srs.ImportFromEPSG(9822) # Import the EPSG code into the new object srs
print(srs.ExportToWkt()) # Print the result before transformation to ESRI WKT (prints the EPSG converted to a WKT string)

# The output is: 
True
ERROR 1: PROJ: proj_create_from_database: crs not found


```

#### Problem description

I cannot project my shapefile to Albers_Conic_Equal_Area (i.e. epsg code 9822)

#### Expected Output
# I expect the following working
newdata.crs = from_epsg(9822)   

#### Output of ``geopandas.show_versions()``

<details>

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by martinfleis** [comment]
That is likely some issue with PROJ library. However, I can confirm that EPSG:9822 is not found even in the most recent version.

One workaround is to use proj string instead (from https://proj.org/operations/projections/aea.html).

Also note that geopandas is not involved in your code above. CRS handling in geopandas is done using `pyproj` not `fiona`. But the issue is in `pyproj` as well since it is caused by PROJ.

```py
from pyproj.crs import CRS

aea = CRS('+proj=aea +lat_1=29.5 +lat_2=42.5')
```

**Comment by leilaher** [comment]
Thank you, Martin. Is there a way to match the EPSG:9822 projection with the following?

I tried: 
from pyproj.crs import CRS
aea = CRS('+proj=aea +lat_1=29.5 +lat_2=45.5')

But I am not sure how to include the rest of the properties to match my other shapefiles, which properties are:
Projected Coordinate System:	NAD_1983_Albers
Projection:	Albers
False_Easting:	0.00000000
False_Northing:	0.00000000
Central_Meridian:	-96.00000000
Standard_Parallel_1:	29.50000000
Standard_Parallel_2:	45.50000000
Latitude_Of_Origin:	23.00000000
Linear Unit: 	Meter

Geographic Coordinate System:	GCS_North_American_1983
Datum: 	D_North_American_1983
Prime Meridian: 	Greenwich
Angular Unit: 	Degree

**Comment by martinfleis** [comment]
If you have it in shapefile, you can load it from that and use it directly.

```py
shp_with_crs = geopandas.read_file("path/file.shp")

df_without_crs = df_without_crs.set_crs(shp_with_crs.crs)
```

Docs https://geopandas.readthedocs.io/en/latest/docs/reference/api/geopandas.GeoDataFrame.set_crs.html#geopandas.GeoDataFrame.set_crs

**Comment by leilaher** [comment]
It works perfectly! Thanks, Martin.
