### ISSUE TITLE
ENH: Make output of assert_geoseries_equal more informative

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#1795]
Currently we get this:

```
In [2]: from shapely.geometry import Polygon

In [3]: s1 = geopandas.GeoSeries([Polygon([(0, 0), (1, 1), (0, 1), (0, 0)])])

In [4]: s2 = geopandas.GeoSeries([Polygon([(0, 0), (1, 1), (1, 0), (0, 0)])])

In [6]: import geopandas.testing

In [7]: geopandas.testing.assert_geoseries_equal(s1, s2)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-3318b7c760e2> in <module>
----> 1 geopandas.testing.assert_geoseries_equal(s1, s2)

~/scipy/geopandas/geopandas/testing.py in assert_geoseries_equal(left, right, check_dtype, check_index_type, check_series_type, check_less_precise, check_geom_type, check_crs)
    132             assert geom_almost_equals(left, right)
    133         else:
--> 134             assert geom_equals(left, right)
    135 
    136 

AssertionError: 
```

with a bare AssertionError. We could at least print the geometries that are failing, and maybe also where in the Series (or how many in the Series are not equal), etc

**Comment by Imanflow** [comment]
Hello, 

I'd like to take this issue. So the idea would be something like this?:

    ` if check_less_precise:
         if not geom_almost_equals(left, right):
             unequal_geoms = [(geom_1.wkt, geom_2.wkt) for geom_1, geom_2
                         in zip(left, right) if not geom_1.almost_equals(geom_2)]
            raise AssertionError(f"These geometries are not almost equal: {unequal_geoms}")
    `
    I guess there must be a most efficient, elegant way of doing this, I'm looking for alternatives.

**Comment by jorisvandenbossche** [comment]
@Imanflow thanks for taking a look at this!

Yes, I think that is a good start. We probably want to reuse the same definition as `geom_almost_equals`, which also checks for empties and missing values. 
But feel free to make a PR, then it will be easier to give concrete feedback.

**Comment by Imanflow** [comment]
Here is the PR https://github.com/geopandas/geopandas/pull/1808
