### ISSUE TITLE
BUG: gpd.read_file() returns multipart geometries instead of singlepart

### ISSUE THREAD

**Issue by matthewjohnborish** [geopandas/geopandas#1807]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

Sample data for this example were obtained from the USGS  on this page:
https://pubs.er.usgs.gov/publication/ofr20151175
Direct link to geodatabase download:
https://pubs.usgs.gov/of/2015/1175/ofr20151175_geodatabase.zip

#### Code
```python
import geopandas as gpd
import fiona
import shapely

contacts_gdf = gpd.read_file('JOTR_OFR_v10-2.gdb', layer='Contacts')
contacts_gdf.head(3)

```
![image](https://user-images.githubusercontent.com/28167838/106231214-03bb3d00-61a6-11eb-9abb-890e3a6d0103.png)

```python
contacts_gdf['geometry'].type.value_counts()

```

![image](https://user-images.githubusercontent.com/28167838/106232780-b50fa200-61a9-11eb-9fc2-68431aa18526.png)

```python
import pprint
datasrc_path = 'JOTR_OFR_v10-2.gdb'

with fiona.open(datasrc_path, layer='Contacts') as c:
    pprint.pprint(c.schema)

```

![image](https://user-images.githubusercontent.com/28167838/106231355-5dbc0280-61a6-11eb-89c4-cf96646a87f2.png)

Using the the GGIS field calculator to populate a virtual field shows singlepart features.

![image](https://user-images.githubusercontent.com/28167838/106232847-de303280-61a9-11eb-8573-ce7720976285.png)

![image](https://user-images.githubusercontent.com/28167838/106232638-58ac8280-61a9-11eb-9291-f5185a43e5a0.png)

#### Problem description

Using gpd.read_file() on an ESRI geodatabase gives multipart geometry types when they should be singlepart. Further investigation suggests this results from Fiona dependency.

SYSTEM INFO
-----------
python     : 3.8.5 | packaged by conda-forge | (default, Aug 19 2020, 11:50:57) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\mborish\AppData\Local\Continuum\anaconda3\envs\py38_gpd_081\python.exe
machine    : Windows-10-10.0.16299-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.1.2
GDAL data dir: None
PROJ       : 7.1.0
PROJ data dir: C:\Users\mborish\AppData\Local\Continuum\anaconda3\envs\py38_gpd_081\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.1.0
fiona      : 1.8.13
numpy      : 1.19.1
shapely    : 1.7.0
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None

<details>

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by jorisvandenbossche** [comment]
> Using the the GGIS field calculator to populate a virtual field shows singlepart features.

What you show it that the features have 1 geometry, not necessarily that they are singlepart. They can also be multi-part with a single sub-geometry. 

If you do a similar calculation with geopandas, you will see that it also says they only have a single geometry:

```
In [5]: contacts_gdf.geometry.map(lambda geom: len(geom.geoms))
Out[5]: 
0        1
1        1
2        1
3        1
4        1
        ..
46243    1
46244    1
46245    1
46246    1
46247    1
Name: geometry, Length: 46248, dtype: int64
```

If you want to actually get the singlepart geometries, you can use the `explode` method:

```
In [7]: contacts_gdf.explode().head(3)
Out[7]: 
                   GeologicFeature  ...                                           geometry
0 0                           None  ...  LINESTRING (618301.396 3725361.397, 617994.581...
1 0  limit of artificial landscape  ...  LINESTRING (620149.275 3725795.292, 620082.279...
2 0  limit of artificial landscape  ...  LINESTRING (618301.396 3725361.397, 618308.718...

[3 rows x 12 columns]
```

I am not familiar enough with this specific file format to know if this is expected or not to get multipart geometries (but I suppose it is), but if you think the file is read incorrectly, that's indeed to bring up with fiona.

**Comment by brendan-ward** [comment]
ESRI File Geodatabase Feature Classes (i.e., point, line, or polygon dataset with the database) can contain multipart features; this is not uncommon for that format.  Some data processing steps (e.g., a dissolve) will produce multipart features even if they only contain a single part; this may have been the case for this specific dataset prior to serving it up.

OGR, used by Fiona under the hood to read this dataset, considers this a MultiLineString dataset:
```
> ogrinfo -so JOTR_OFR_v10-2.gdb/                                                                                      
INFO: Open of `JOTR_OFR_v10-2.gdb/'
      using driver `OpenFileGDB' successful.
1: Contacts (Multi Line String)
```

QGIS also reports this as MultiLineString:
![image](https://user-images.githubusercontent.com/3375604/106280201-73571980-61f2-11eb-8ff3-77631aec9f38.png)

There is neither a geopandas nor a Fiona issue with this dataset.  Explode is the easiest solution to extract single part LineStrings.

**Comment by matthewjohnborish** [comment]
Thanks for the responses. I opened this issue because exporting a geodatabase feature class to a shapefile without any changes, and then using gpd.read_file() gives LineString geometry type. 

```python 
contacts_shp_gdf = gpd.read_file('Contacts.shp')
contacts_shp_gdf.head(3)


```
![image](https://user-images.githubusercontent.com/28167838/106293672-20399280-6203-11eb-9165-07c6be4ac9ac.png)


The gdf created from the geodatabase is able to be used ok and .explode() does indeed work to change geometries to singlepart. However, this results in a MultiIndex, which may not be desirable for users. This inconsistent behavior between geodatabase feature classes and shapefiles isn't a blocker, but it seemed peculiar enough for me to bring up as a possible issue. Of course, this may be due to lower level dependencies such as Fiona and OGR.

**Comment by martinfleis** [comment]
The geometries in this geodatabase are all stores as MultiLineStrings. See what QGIS says about the type:

![Screenshot 2021-01-29 at 16 42 39](https://user-images.githubusercontent.com/36797143/106302536-02931a00-6251-11eb-99eb-18e5c413b235.png)

Therefore, it is a choice of the author of the data to upscale single part geometry to MultiLineStrings with a single geometry. GeoPandas/fiona, therefore, open the data correctly. Exactly as it was saved.

**Comment by matthewjohnborish** [comment]
> The geometries in this geodatabase are all stores as MultiLineStrings. See what QGIS says about the type:
> 
> ![Screenshot 2021-01-29 at 16 42 39](https://user-images.githubusercontent.com/36797143/106302536-02931a00-6251-11eb-99eb-18e5c413b235.png)
> 
> Therefore, it is a choice of the author of the data to upscale single part geometry to MultiLineStrings with a single geometry. GeoPandas/fiona, therefore, open the data correctly. Exactly as it was saved.

Thanks for looking into this. Additional examination of the Contacts geodatabase feature class in QGIS shows that its features are stored as MultiLineStrings, even though each feature only has one part. When exporting with QGIS to a shapefile and checking the force multipart option, followed by gpd.read_file() gives LineString features. So it seems this is just a difference in geodatabase and shapefile capabilities, that I was unaware of, rather than a bug.
