### ISSUE TITLE
No CRS after merge

### ISSUE THREAD

**Issue by JamesG87** [geopandas/geopandas#181]
Hi, when merging a ```GeoDataFrame``` with a panda ```DataFrame``` the original crs is lost.

For example, the following code produce a ```GeoDataFrame``` that has no crs, even though the original did.

```python
shp = gp.read_file('file.shp')
df = pd.read_csv('otherFile.csv')
merged = pd.merge(shp, df, on='LSOA11CD')
```

Apologies if this is something you are aware of, or something I have overlooked.

**Comment by jwass** [comment]
@JamesG87 You can use the `merge` method on the `GeoDataFrame` to get around this. Try this instead:
```
merged = shp.merge(df, on='LSOA11CD')
```
Should maintain the CRS and geometry column, etc.

This issue is also discussed over on #127 which we can now merge since pydata/pandas#7737 was closed.
