### ISSUE TITLE
QST: to_file returns Invalid field type <class 'bytes'>

### ISSUE THREAD

**Issue by projectsUW** [geopandas/geopandas#1813]
I HAVE TRIED THIS:
![image](https://user-images.githubusercontent.com/16848598/106549586-4733e500-64df-11eb-9396-4eb2f0cfa84b.png)

BUT IT IS NOT WORKING:
![image](https://user-images.githubusercontent.com/16848598/106549626-603c9600-64df-11eb-9d95-125af99774a6.png)

**Comment by martinfleis** [comment]
Can you copy&paste the code so we don't have to type your code to reproduce the issue?

My sense is that dtype of one of the columns is not correct.

**Comment by projectsUW** [comment]
Here it is:

import geopandas as gpd
mapl='https://github.com/UW-eScience-WinterSchool/Python_Session/raw/main/TM_WORLD_BORDERS_SIMPL-0.3.zip'
mymap=gpd.read_file(mapl)
mymap.to_file("mymap.geojson", driver='GeoJSON')

Thanks...

**Comment by martinfleis** [comment]
There's a dtpye issue in `NAME` column. Coerce it to string before saving. That resolved the issue.

```py
mapl='https://github.com/UW-eScience-WinterSchool/Python_Session/raw/main/TM_WORLD_BORDERS_SIMPL-0.3.zip'
mymap=gpd.read_file(mapl)

mymap.NAME = mymap.NAME.astype(str)

mymap.to_file("mymap.geojson", driver='GeoJSON')
```
