### ISSUE TITLE
TST: failures with shapely and GEOS 3.9

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1818]
CI started coming with GEOS 3.9 today which caused a lot of errors if we use shapely backend. Most of them are related to overlay, so I guess it is caused by the new `OverlayNG`, which returns slightly different geometries.

https://github.com/geopandas/geopandas/runs/1854075806

**Comment by martinfleis** [comment]
The overlay failures are caused by a different order of coordinates, everything else looks the same to me. Since we use `geom_almost_equals` in the check, we need equality of order, so it is a matter of fixing the tests.

**Comment by martinfleis** [comment]
Hmm, it seems that we'll need a test which checks that geometry is purely almost equal in a way where order of vertices and precision of coordinates does not matter (now we can do one or the other).

**Comment by jorisvandenbossche** [comment]
> Hmm, it seems that we'll need a test which checks that geometry is purely almost equal in a way where order of vertices and precision of coordinates does not matter (now we can do one or the other).

In principle, the easiest way to do this is to "normalize" the geometries before comparing. Problem is that this is only available for pygeos and not shapely ..

**Comment by jorisvandenbossche** [comment]
It should actually be relatively easy to use shapely's geos internals to expose normalize, will do a PR tomorrow.
