### ISSUE TITLE
BUG: access violation  using unary_union on a single group of 8 polygon with use_pygeos

### ISSUE THREAD

**Issue by bardout** [geopandas/geopandas#1820]
- [ X] I have checked that this issue has not already been reported.

- [X ] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely.ops import unary_union

gpd.options.use_pygeos =  True
df = gpd.read_feather("inbox.ftr")
ex2 = df.iloc[[0,6,7,8,9,10,11,13]].loc[:,['type','geometry','area']]
gr2 = ex2.groupby('type', dropna=False)
df2 = gr2.aggregate({'area': ['sum', 'median', 'count']})
print( len(gr2), ' groups; agg shape: ', df2.shape)
df2.columns = ['total-area', 'median-area', 'count']
geoms = gr2.geometry.apply(unary_union)  # <--- raise an OSError: access violation
```

#### Problem description
repeated many times, before pinpointing the minimal rows and column required for the error. 
**reproduced with a 24kb extract of my data saved as feather** (attached as comment), using unary_union on a group with 8 geometries, but not when inlining a json fragment (may differ in rounding). Always only when` gpd.options.use_pygeos =  True`
 I came to use the unary_union on geometries instead of `geopanda.dissolve`, because of many limitations (eg #1814 on dropna) and undocumented arguments (e.g. by=list of attributes for grouping, aggfunc=list of aggregation function), Now I am working around this crash by using dissolve, which It seems does raise it. I hope to pull through with some tweaking.

Traceback (most recent call last):
  File "test\bug_unary_union.py", line 40, in <module>
    geoms = gr2.geometry.apply(unary_union)  # invoked by dissolve
  File "C:\Portable\anaconda3\envs\gis\lib\site-packages\pandas\core\groupby\generic.py", line 221, in apply
    return super().apply(func, *args, **kwargs)
  File "C:\Portable\anaconda3\envs\gis\lib\site-packages\pandas\core\groupby\groupby.py", line 894, in apply
    result = self._python_apply_general(f, self._selected_obj)
  File "C:\Portable\anaconda3\envs\gis\lib\site-packages\pandas\core\groupby\groupby.py", line 928, in _python_apply_general
    keys, values, mutated = self.grouper.apply(f, data, self.axis)
  File "C:\Portable\anaconda3\envs\gis\lib\site-packages\pandas\core\groupby\ops.py", line 238, in apply
    res = f(group)
  File "C:\Portable\anaconda3\envs\gis\lib\site-packages\shapely\ops.py", line 153, in unary_union
    collection = lgeos.GEOSGeom_createCollection(6, subs, L)
**OSError: exception: access violation** writing 0x00007FF997562160

#### Expected Output
as with `gpd.options.use_pygeos = False`
the union is completed and usable. Unfortunately, I need to do this grouping on 200k rows, so It is not efficient. 

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.7.8 | packaged by conda-forge | (default, Nov 27 2020, 18:48:03) [MSC v.1916 64 bit (AMD64)]
executable : C:\Portable\anaconda3\envs\gis\python.exe
machine    : Windows-10-10.0.17763-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.1.4
GDAL data dir: None
PROJ       : 7.1.1
PROJ data dir: C:\Portable\anaconda3\envs\gis\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.2.1
fiona      : 1.8.18
numpy      : 1.19.5
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 2.6.1.post1
matplotlib : 3.3.3
mapclassify: 2.4.2
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : 0.17.1

</details>

**Comment by bardout** [comment]
this is the original data loaded in the code sample (8 rows selected ou of 35)
[inbox.zip](https://github.com/geopandas/geopandas/files/5952660/inbox.zip)

**Comment by martinfleis** [comment]
Thanks for the report. I am not sure what causes is but I'd say it may be resolved by shapely 2.0. The current issue is likely linked to different geometry backends in conflict here.

You can use this workaround now.

```py
def _union_block(block):
    return block.unary_union

geoms = gr2.geometry.apply(_union_block)
```

> Unfortunately, I need to do this grouping on 200k rows, so It is not efficient.

Make sure you have pygeos 0.9 and GEOS 3.9 to get massive speedups in `unary_union` it brings.

**Comment by bardout** [comment]
Thank you for this quick answer, I verified this workaround that I will apply as needed. For now, I had better results with dissolve, with some tricks, these 2 lines instead of 4 lines above:
```
ex2.fillna('null', inplace=True)  # replacing missing values with `'null'` which is a string
df2 = ex2.dissolve( by= ['type', 'NATURE'],  aggfunc=['sum', 'median', 'count'], as_index=False)
```
 

About releases,  I welcome your suggestion, although I am not sure how to **upgrade them on PC Win10 with anaconda 3 ?**
with the latest from december in env Python 3.7.8:
```
Shapely==1.7.1 (stable)
pygeos==0.8
geopandas==0.8.1
```
It seems tricky to me. I had GEOS 3.8.0 binaries present, as part of shapely install (not the latest 3.9.0 from 2020/12/10, not available via conda).
looking up this in web page from pygeos install:  modifying the binaries require geos-config in pygeos-devel, and rebuild of shapely. I  
I suspect upgrading just GEOS won't apply to the packages pygeos and shapely, used by geopanda resp for scalar and vectorial operations. 

it appears the compatibility  matters for GEOS binary between them. I noticed the same via pip on linux CentOS host this month gets  this _UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.8.1-CAPI-1.13.3). Conversions between both will be slow._
Also, uninstall and reinstall shapely didnt help.bg
on this host, I built a container with pygeos==0.9, and 
```
    import geopandas as gpd ...
/usr/local/lib/python3.7/site-packages/geopandas/_vectorized.py:39: in <dictcomp>
    type_mapping = {p.value: _names[p.name] for p in pygeos.GeometryType}
E   KeyError: 'MISSING'
```
Specifying GEOS via pip:
`ERROR: Could not find a version that satisfies the requirement GEOS==3.9 (from -r /app/requirements-mini.txt (line 5)) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2)`

Any suggestions is appreciated. Maybe I should direct this question elsewhere, I have not found any explanation so far.

**Comment by jorisvandenbossche** [comment]
I think currently the only option to have Shapely/PyGEOS with GEOS 3.9 is to use conda-forge or to build manually from source.

**Comment by jorisvandenbossche** [comment]
Given that pygeos is no longer maintained and shapely 2.0 is now well established, and that the main dev branch of geopandas (for 1.0) only supports shapely > 2 (so no longer any issues with mixing pygeos and shapely are possible), I think we can close this issue.

(if you think that assessment is wrong, feel free to comment!)
