### ISSUE TITLE
Geopandas / Shapely Binary distrubituon for MacOS is broken

### ISSUE THREAD

**Issue by eddjharrison** [geopandas/geopandas#1822]
- [x] I have read the [documentation on installation](https://geopandas.org/install.html) and followed the instructions provided.

- [x] I have looked through [issues labeled "installation"](https://github.com/geopandas/geopandas/labels/installation) in the geopandas repo.

- If your issue is related to installation using the `conda-forge` channel, please open an issue in [geopandas-feedstock repository](https://github.com/conda-forge/geopandas-feedstock) instead.

---

#### System information

MacOS BigSur 11.2
Darwin Edwards-Air-2.nextgentel.net 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

pip 21.0.1 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)

#### ISSUE 
After pip3 install geopandas, the following errors occur:

```
>>> import geopandas as gpd
>>> t = gpd.read_file('/Users/edwardharrison/Downloads/small_polygon/small_polygon.shp')
IllegalArgumentException: Shell is not a LinearRing
/Users/edwardharrison/PycharmProjects/EmeraldInterpret/meow1/lib/python3.8/site-packages/geopandas/geodataframe.py:432: FutureWarning: Assigning CRS to a GeoDataFrame without a geometry column is now deprecated and will not be supported in the future.
  return GeoDataFrame(rows, columns=columns, crs=crs)
```

```
>>> import shapely.geometry
>>> shape = shapely.geometry.Polygon([[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]])
IllegalArgumentException: Shell is not a LinearRing
```
The version of Shapely that the above installs is: `Shapely-1.7.1-cp38-cp38-macosx_10_9_x86_64.whl `

This problem is solved by by doing:

`pip3 install --no-binary shapely shapely`

This seems to be related to issue https://github.com/geopandas/geopandas/issues/1730

**Comment by martinfleis** [comment]
Thanks for the report and sorry for the slow follow-up.

The issue you describe is related to shapely being compiled against a different version of GEOS than you have in your environment. This is a known situation, loosely covered by shapely docs - https://shapely.readthedocs.io/en/stable/project.html#source-distributions. 

I'll close the issue as related to pip install of shapely. Since you have found a solution, others coming later can use it as well.
