### ISSUE TITLE
BUG: to_crs() ends script without error

### ISSUE THREAD

**Issue by joebullardPA** [geopandas/geopandas#1823]
- [x] I have checked that this issue has not already been reported. - I have seen the issue on OSX but not windows 10 as is being used here

- [x] I have confirmed this bug exists on the latest version of geopandas. - Yes, this is using version 0.8.1

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

```
gdf = gpd.read_file(file_in)
gdf = gdf.to_crs('EPSG:27700')
```

#### Problem description

When attempting to reproject data in EPSG:3857 to another crs, the script will just shut down with no error message.

#### Output of ``geopandas.to_crs()`` to reproject as expected and not shut script down

<details>

```
SYSTEM INFO
-----------
python     : 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\CLJB3\Anaconda3\envs\test_env\python.exe
machine    : Windows-10-10.0.17763-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.0.2
GDAL data dir: None
PROJ       : 6.2.1
PROJ data dir: C:\Users\CLJB3\Anaconda3\envs\test_env\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.1
pandas     : 1.2.1
fiona      : 1.8.13.post1
numpy      : 1.19.2
shapely    : 1.7.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.2
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
```

</details>

**Comment by jorisvandenbossche** [comment]
@joebullardPA Can you show the output of `conda list`? I suspect you might have a mixture of packages from different sources (conda, pip, ..)

**Comment by joebullardPA** [comment]
Yes, you're right, I created a new env using:

```
conda create -n geo_env
conda activate geo_env
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda install python=3 geopandas 
```

And it worked perfectly. Thanks!
