### ISSUE TITLE
BUG: geopandas.org should redirect to geopandas.readthedocs.io

### ISSUE THREAD

**Issue by discdiver** [geopandas/geopandas#1827]
- [ x] I have checked that this issue has not already been reported.
I think https://geopandas.org/ should redirect to https://geopandas.readthedocs.io/en/latest/index.html . It appears https://geopandas.org/ is outdated.

**Comment by martinfleis** [comment]
Thanks for the notice. We are aware of this (#290) and actively trying to resolve this. It is just slightly out of hands of the current maintainers. Considering that the original issue will soon celebrate 5 years, it would be certainly good to finally close it :D.

_(closing this one as a duplicate)_

**Comment by discdiver** [comment]
Apologies. I didn't see the issue when searching - perhaps I didn't make it back that far. 🙂
