### ISSUE TITLE
API: default behaviour of alignment in binary ops

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1832]
#1668 introduces `align` keyword to control whether two GeoSeries gets aligned in binary, row by row operations or not. However, the default behaviour may require a bit more discussion.

Moving from the original PR here (from https://github.com/geopandas/geopandas/pull/1668#discussion_r578692627).

> @jorisvandenbossche:  Idea: make the default None, which is treated as True but gives a warning when alignment is actually done. This gives a way for the user to indicate they are OK with alignment without getting warnings about it.
(small disadvantage is that the signature in the function is less explicit than with align=True)

> @martinfleis: I do understand your point, but considering how troublesome this behaviour is (I responded to countless questions on this), I would prefer having an explicit align=True in the signature. Having None/True/False is a nice trick for advanced users to silence warnings, but in this specific case, I would prefer understanding for basic users (I really don't want to answer the same question again :D).

> @jorisvandenbossche: Then we should maybe rather make it an error by default? To make it really clear for users they are doing something wrong (with a good explanation then)

> @martinfleis: That'd be a breaking change.

**Comment by jorisvandenbossche** [comment]
Looking at the original issue again, I think this is actually covered by that: https://github.com/geopandas/geopandas/issues/750 (but fine to close that one as well, doesn't matter ;))

That would indeed be a breaking change, but if we want to do this, we can first raise a more elaborate FutureWarning (compared to the UserWarning we have now)

**Comment by martinfleis** [comment]
We should make the warning more explicit and explain what happens apart from just saying that the indices are different.

**Comment by jorisvandenbossche** [comment]
First attempt:

> The index of the left and right GeoSeries in the 'left.contains(right)' operation is not equal, and therefore they will be aligned (introducing missing values) before executing the operation. 
If this alignment is the expected (or desired?) behaviour, you can silence this warning by passing 'align=True'. If you don't want alignment and protect yourself of accidentally aligning, you can pass 'align=False'.

**Comment by m-richards** [comment]
> First attempt:
> 
> > The index of the left and right GeoSeries in the 'left.contains(right)' operation is not equal, and therefore they will be aligned (reordering and/or introducing missing values) before executing the operation.
> > If this alignment is the expected (or desired?) behaviour, you can silence this warning by passing 'align=True'. If you don't want alignment and protect yourself of accidentally aligning, you can pass 'align=False'.

I was going to look at this again as it seems nice to try and get an improved error message in - but the suggested message doesn't correspond to the behaviour in the code. Currently there's no way to silence the warning, it was chosen not to implement that as an option. The suggestion in #2582 the same as originally suggested https://github.com/geopandas/geopandas/pull/1668#discussion_r578692627, so that's already been considered. 

A less elegant version of this with True as an explicit default would be to add `"align_no_warn"` as a value for align.

Otherwise, we could just include the updated warning with a snippet for silencing the warning using warnings.filterwarnings?

**Comment by martinfleis** [comment]
The agreement during the last dev meeting was to use `None` as a defaulting value defaulting to True. Warning is shown when `align=None` and can be silenced by explicitly stating `align=True`. I will make a PR for that.
