### ISSUE TITLE
DOC: ReadTheDocs failure due to timeout

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1835]
RTD does not seem to be happy about the switch to `nbsphinx` examples - https://readthedocs.org/projects/geopandas/builds/13052287/. 

Not sure why exactly, I can think of two reasons (it may actually be a combination of both).

1) I have removed pins from versions to get the recent version, that may take more time to resolve. I'll pin again to current versions tested locally.
2) We have more examples now, some may actually cause trouble/take time. Will explore.

**Comment by jorisvandenbossche** [comment]
Yes, the time to create the environment from the yml file went up from 324s (last passed build) to 534s in the failed build you linked. 
So that's 200s less available for actually building the docs. 
So I would start with pinning the versions again, that might be enough to get it passing.

**Comment by martinfleis** [comment]
We're now on 260s to create env but still timing out.
