### ISSUE TITLE
Install Rtree for phyton on Windows 7

### ISSUE THREAD

**Issue by ernapiantari** [geopandas/geopandas#184]
Help. I have problem when instal Rtree on my windows.
I used cmd for install it.
But it's seem cannot found spatialindex_c.dll
Actually, i have spatialindex_c-64.dll
what sholud i do with it? 

this is what i have done:
C:\Python27\Scripts\easy_install.exe Rtree
Best match: Rtree 0.8.2
Downloading https://pypi.python.org/packages/source/R/Rtree/Rtree-0.8.2.tar.gz#md5=4ba7276cbd4c51b373068004ae864d3
Processing Rtree-0.8.2.tar.gz
Writing c:\users\.....\Rtree-0.8.02\setup.cfg
Running Rtree-0.8.2\setup.py -q dbist_egg --dist-dir ......
error: could not find or load spatialindex_c.dll

And I tried to download Rtree-0.8.2 and install it offline too, but stiil could not find or load spatialindex_c.dll.

**Comment by scw** [comment]
I hopefully answered this over at https://github.com/Toblerity/rtree/issues/43, closing here as this isn't a geopandas issue.
