### ISSUE TITLE
QST: pyproj 6 future warning crs init

### ISSUE THREAD

**Issue by geoHeil** [geopandas/geopandas#1840]
As far as I know the pyproj6 future warning:

``` 
FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
```

should be already fixed in the current releases of geopandas (>= 0.7 https://gis.stackexchange.com/questions/348997/constant-future-warnings-with-new-pyproj). However, for me on 0.8.2 it is not fixed.

**Comment by jorisvandenbossche** [comment]
@geoHeil can you give some example code that gives a warning? (and can you also show the output of `geopandas.show_versions()`

**Comment by geoHeil** [comment]
Sure:

```
Python 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 22:54:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import geopandas
>>> geopandas.show_versions()

SYSTEM INFO
-----------
python     : 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 22:54:47) [MSC v.1916 64 bit (AMD64)]
executable : C:\ProgramData\Anaconda3\envs\my_conda_envl\python.exe
machine    : Windows-10-10.0.16299-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.1.4
GDAL data dir: None
PROJ       : 7.2.0
PROJ data dir: C:\ProgramData\Anaconda3\envs\my_conda_env\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.8.2
pandas     : 1.2.2
fiona      : 1.8.18
numpy      : 1.20.1
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.0.0.post1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : 3.0.0
```

Regarding the exact line - this is hard as I do not get a stacktrace of where the warning is thrown exactly. But I guess it is related to:

````
# https://gis.stackexchange.com/questions/348997/constant-future-warnings-with-new-pyproj
df = df.to_crs({'init': dst_epsg})
````

**Comment by martinfleis** [comment]
Hi,
this is not an issue in GeoPandas. As the warning states, the `init` syntax specifying CRS is now deprecated. Therefore, you should not use `{'init': dst_epsg}` but `dst_epsg` only. You can now specify CRS in many ways, e.g. as an EPSG code, `4326`, string `EPSG:4326` and many other formats supported by pyproj - see the [documentation](https://geopandas.readthedocs.io/en/latest/docs/user_guide/projections.html).

This is the correct form of that line:

```py
df = df.to_crs(dst_epsg)
```
