### ISSUE TITLE
Dissolve geometries by columns/attributes

### ISSUE THREAD

**Issue by ozak** [geopandas/geopandas#185]
Hi,

I was wondering if this is somehow already implemented. I'd like to be able to generate a new GeoPandas Dataframe from another one by dissolving geometries based on attributes. E.g. say you have countries in dataframe ``df`` with each geometry representing a country. There is a column ``continent``, so the idea would be something like 

    continents = df.dissolve('continent')

where continents now would have for each continent a geometry generated by the union of all the geometries in ``df`` that are from that continent. 

If it is not implemented I can write some code to do it and if there is interest add it as a pull request.

**Comment by jwass** [comment]
Hi @ozak,
You can do this by applying normal Pandas patterns and using Shapely functions to aggregate. Something like this should work:

```
df.groupby('continent')['geometry'].agg(shapely.ops.unary_union)
```

**Comment by ozak** [comment]
Will try...thanks @jwass!

**Comment by ozak** [comment]
It generates a ``pandas.core.series.Series'' not a geopandas one. Tried 

    df.groupby('continent').geometry.agg(shapely.ops.unary_union)

just in case with the same result.

**Comment by ozak** [comment]
Ok...here's the solution in case someone else needs this

    df2=df.groupby('continent')
    df.set_index('continent', inplace=True)
    df['geometry']=df2.geometry.apply(shapely.ops.unary_union)
    df.reset_index(inplace=True)
    df=df.drop_duplicates('continent')

Of course this assumes you are interested in the other attributes.

**Comment by nickwg03** [comment]
@ozak I think you can achieve the same result by just doing:
`result = gpd.GeoDataFrame(gdf.groupby("val").geometry.agg(unary_union).reset_index(), geometry="geometry", crs=gdf.crs)`

Like you said, the groupby will create a Series, but resetting the index and passing that into a geopandas.GeoDataFrame will create a new GeoDataFrame for you with the continent values and new geometries.
