### ISSUE TITLE
ENH: Include reset_index in explode()

### ISSUE THREAD

**Issue by Imanflow** [geopandas/geopandas#1859]
#### Is your feature request related to a problem?

One of my most repeated code is 
`gdf = gdf.explode()`
`gdf.reset_index(inplace=True, drop=True)`

And i think i'm not the only one, it's even in geopandas codebase. 

#### Describe the solution you'd like

I'd add the kwarg `reset_index` and reset it if True
#### API breaking implications

If default is False, no breaking changes

#### Describe alternatives you've considered

I understand this would force drop=True and it might not be desirable. (I always drop it but other people might not), so an alternative would be to also add kwarg `drop`.

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
    def explode(self, column=None, reset_index=False, **kwargs):
    ....
      if reset_index:
          geo_df.reset_index(inplace=True, drop=True)
```

**Comment by martinfleis** [comment]
Thanks for the suggestion! You're absolutely right, I am also using that all the time. Should be ideally done together (or at least in sync) with #1751 bringing additional consistency with pandas `explode`.

**Comment by jorisvandenbossche** [comment]
Let's close this in favor of #1751

**Comment by jorisvandenbossche** [comment]
Actually, it's still slightly different .. (not adding the "counts" vs resetting altogether). But will expand on the other issue.

**Comment by jorisvandenbossche** [comment]
@Imanflow as noted in https://github.com/geopandas/geopandas/issues/1751#issuecomment-789515925, in pandas this is a keyword called `ignore_index=False/True`. I think we can certainly add this in geopandas as well to follow the addition in pandas.
