### ISSUE TITLE
BUG: `convert_dtypes()` converts GeoDataFrame to DataFrame

### ISSUE THREAD

**Issue by adriantre** [geopandas/geopandas#1870]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import fiona # AttributeError if not importing fiona before gpd
import geopandas as gpd
from geopandas.testing import assert_geodataframe_equal

def df():
    return pd.DataFrame(
        {
            "City": ["Buenos Aires", "Brasilia", "Santiago", "Bogota", "Caracas"],
            "Country": ["Argentina", "Brazil", "Chile", "Colombia", "Venezuela"],
            "Latitude": [-34.58, -15.78, -33.45, 4.60, 10.48],
            "Longitude": [-58.66, -47.91, -70.66, -74.08, -66.86],
        }
    )

def gdf_points_from_xy(df):
    return gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.Longitude, df.Latitude))

def test_convert_dtypes_before_gdf():
    result = df().convert_dtypes().pipe(gdf_points_from_xy)
    assert isinstance(result, gpd.GeoDataFrame)
    # --> no error

def test_convert_dtypes_after_gdf():
    result = df().pipe(gdf_points_from_xy).convert_dtypes()
    assert isinstance(result, gpd.GeoDataFrame)
    # --> AssertionError

def test_convert_dtypes_expectation():
    expected = df().convert_dtypes().pipe(gdf_points_from_xy)

    result = df().pipe(gdf_points_from_xy).convert_dtypes()

    assert_geodataframe_equal(result, expected)
    #--> AssertionError
```

#### Problem description

Calling `.convert_dtypes()` on a GeoDataFrame turns it into a regular DataFrame.

```python
AssertionError: assert isinstance(result, GeoDataFrame)
```

#### Expected Output
I expect `convert_dtypes` to not change frame type.

The problem may be with the [original method](https://github.com/pandas-dev/pandas/blob/c5d0d138cf1162cea985741cbbbaea3eef6ca8c3/pandas/core/generic.py#L6138). I suspect it is because of `return concat(results, axis=1, copy=False)`. As the pandas repo does not know about other frame types, I suspect the fix should lie in this repo.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.4 (default, Jan 11 2021, 16:58:12)  [Clang 12.0.0 (clang-1200.0.32.28)]
executable : /Users/adriantofting/Library/Caches/pypoetry/virtualenvs/gpd-test-qc5veAeh-py3.8/bin/python
machine    : macOS-11.1-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /usr/local/Cellar/geos/3.9.1/lib/libgeos_c.dylib
GDAL       : 3.2.1
GDAL data dir: None
PROJ       : 7.2.1
PROJ data dir: /usr/local/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.3
fiona      : 1.8.18
numpy      : 1.20.1
shapely    : 1.7.1
rtree      : None
pyproj     : 3.0.0.post1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

#### Environment (poetry)

<details>

```toml
#pyproject.toml
[tool.poetry]
name = "gpd_test"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.8"
geopandas = "0.9.0"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.0.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

</details

**Comment by martinfleis** [comment]
Thanks for the report! This is indeed something we need to fix in GeoPandas as pandas internally split the DataFrame into a list of (Geo)Series and concatenate them together, which essentially creates a brand new object.

We need to override the method and ensure that we preserve GeoDataFrame as well as our metadata (active geometry, CRS), which are currently also lost.

**Comment by damanad** [comment]
convert_dtypes is declared as final, at least in the last versions of pandas, so it should not be overridden (I don't know if python actually prevents it or it is just a recommendation). In any case, I think this does the trick:
```python
def convert_dtypes_geopandas(gdf):
    return pd.concat((gdf[['geometry']],
                      gdf.drop(columns=['geometry']).convert_dtypes()),
                      axis=1)
```

**Comment by m-richards** [comment]
Just a note on reproducing this (because I couldn't in my mock up at first), order matters to the result of convert dtypes - because order matters in concat:
```python
In [8]: type(df().pipe(gdf_points_from_xy)[['geometry', 'Country']].convert_dtypes())
Out[8]: geopandas.geodataframe.GeoDataFrame

In [9]: type(df().pipe(gdf_points_from_xy)[['Country', 'geometry']].convert_dtypes())
Out[9]: pandas.core.frame.DataFrame
```

**Comment by adriantre** [comment]
@jorisvandenbossche it looks like pandas is using the _constructor, but before that they cast it to DataFrame ([source code](https://github.com/pandas-dev/pandas/blob/f482bb751f6e230bc74fefa385a68bc4998d6842/pandas/core/reshape/concat.py#L513))
. What do you think is the reason for that?

**Comment by adriantre** [comment]
convert_dtypes [actually calls concat internally](https://github.com/pandas-dev/pandas/blob/95d2667dd88ba71593bcaa7dd2ad51f7e290325d/pandas/core/generic.py#L6264), so maybe concat is the root to problem.

**Comment by jorisvandenbossche** [comment]
That `cast` doesn't actually "cast" anything in runtime, but only does that to help the type checker.

But yes, it's the facto that it _only_ calls concat that is the problem here. Ideally pandas should still pass the result of concat to `_constructor` or call `__finalize__` on it (this second option might actually be sufficient).

**Comment by adriantre** [comment]
Thanks for the clarification. Is this issue indeed what we need?
https://github.com/pandas-dev/pandas/issues/28283

**Comment by adriantre** [comment]
Seems like this is [fixed for append](https://github.com/pandas-dev/pandas/blob/1b6cb0f45c36b79ef4df27b86f3785684e147504/pandas/core/frame.py#L8947), so is the fix as simple as this?
```python
8947    return concat(results, axis=1, copy=False).__finalize__(self, method="concat")
```

**Comment by m-richards** [comment]
I'm pretty sure finalize on it's own won't be enough, because the return type of concat depends on the return type of the first argument in the list of frames - which is why order matters in what I posted above. So if concat returns a DataFrame,
`DataFrame.__finalize` will be called  (as opposed to `GeoDataFrame.__finalize__` and we won't have any mechanism to turn that into a `GeoDataFrame`.

**Comment by jorisvandenbossche** [comment]
> So if concat returns a DataFrame,
> `DataFrame.__finalize` will be called (as opposed to `GeoDataFrame.__finalize__` and we won't have any mechanism to turn that into a `GeoDataFrame`.

Indeed, only a `__finalize__` won't be enough. But if we could somehow have pandas call the finalize of the class of `self`, that could solve it (to avoid that the return type of `convert_dtypes` depends on the return type of `concat`, since the use of `concat` should be an implementation detail).

Although maybe just passing it to the constructor `return self._constructor(result).__finalize__(self, method="convert_dtypes")` might be easier (where `result` is the output of concat).

I opened an issue for this on the pandas side: https://github.com/pandas-dev/pandas/issues/43668
