### ISSUE TITLE
BUG: overlay(intersection) when keep_geom_type=True  GeometryCollection contains (Multi)Polygon

### ISSUE THREAD

**Issue by boeleman** [geopandas/geopandas#1874]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

When using geopandas.overlay with the options how="intersection" and keep_geom_type=True for two intersecting Polygons, not all (Multi)Polygons are returned. On further exploration it turnes out that sometimes (Multi)Polygons are put in a GeometryCollection together with other elements.

#### Expected Output

I would expect that for two intersecting Polygons all (Multi)Polygons are returned when keep_geom_type=True, even when they reside in a GeometryCollection.

#### Output of ``geopandas.show_versions()``

<details>

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by jorisvandenbossche** [comment]
@boeleman which version of geopandas are you using? 

Based on your description, that sounds like something that was fixed in geopandas 0.9.0 (released beginning of this week) 
(https://github.com/geopandas/geopandas/pull/1554 for the original discussion, fixed by https://github.com/geopandas/geopandas/pull/1582)

**Comment by boeleman** [comment]
I am using geopandas  : 0.8.2

Looks like it is fixed then. Sorry I missed it when I looked through the existing bug reports.

**Comment by jorisvandenbossche** [comment]
No problem!
