### ISSUE TITLE
BUG: __finalize__ does not copies .attrs

### ISSUE THREAD

**Issue by chourmo** [geopandas/geopandas#1875]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Problem description

Dataframe .attrs attributes are lost after explode().
It seems that geopandas and geoseries __finalize__ is not copying .attrs while pandas version is.

This bug exists in version 0.9

**Comment by martinfleis** [comment]
Thanks, I can confirm the issue. We should look into that. We've added the support of `attrs` in #1658 but this case slipped.

MRE:
```py
>>> import geopandas as gpd
>>> df = gpd.read_file(gpd.datasets.get_path('nybb'))
>>> df.attrs = {'test': "value"}
>>> df.explode().attrs
{}
```
