### ISSUE TITLE
CRSError: Invalid projection: EPSG:4326

### ISSUE THREAD

**Issue by ghost** [geopandas/geopandas#1887]
Hi, I'm working in a jupyter notebook and trying to specify the CRS of a geopandas dataframe, like so:

```
import geopandas as gpd
import pyproj
coords = df[['latitude','longitude']]
raw_gpspoints_gdf = gpd.GeoDataFrame(
    coords, geometry=gpd.points_from_xy(coords['longitude'], coords['latitude']), crs="EPSG:4326")
```

However, every time I get the error:

```
CRSError: Invalid projection: EPSG:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name)
```

My versions are:
```
import sys
import pyproj
import geopandas
print(sys.version)
print(pyproj.__version__)
print(geopandas.__version__)
```
```
3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0]
2.6.1.post1
0.8.1
```

and my pyproj directory is
```
pyproj.datadir.get_data_dir()
```

```
'/opt/conda/lib/python3.8/site-packages/pyproj/proj_dir/share/proj'
```

How do I resolve this issue?

**Comment by martinfleis** [comment]
This is an issue with `pyproj` package. They even cover this exact error in their documentation: https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select. Your `pyproj` points to a database created for a different version. You need to specify the path to a correct data directory (see the docs). Proper reinstallation also often helps.

**Comment by jorisvandenbossche** [comment]
Specifically in your case, it seems that you installed pyproj using pip (as a wheel, because it looks for PROJ data inside the pyproj package), and not with conda (although you are using a conda environment). It's best to install all those packages with conda (especially for non-pure python packages such as pyproj)

**Comment by basillatif** [comment]
Hi,
I have been stuck with the exact same error message. I have tried all of the fixes suggested in the PyProj4 documentation page for this.

I created new conda environment and installed a fresh version of geopandas - this[way ](https://geopandas.org/getting_started/install.html). 

The docs on this [page ](https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select) suggest setting a project directory using `pyproj.datadir.set_data_dir(proj_data_dir: Union[str, pathlib.Path]) → None` which takes as a parameter `The path to the PROJ data directory.`

What does PROJ data directory refer to???

**Comment by ftheeten** [comment]
Hi. On Windows 10, I had `crs=CRS("epsg:3857)` recongnized by installing geopandas version 0.9.0 instead of the version (0.6.X both on Anaconda and pip from the OS).
I had also to assigne a crs on shapefile this way 
```
prov_shp=geopandas.read_file(fichier_dist )
prov_shp.set_crs(epsg=4326, inplace=True)
```
...to be able to reproject

**Comment by wsauthoff** [comment]
> Hi, I have been stuck with the exact same error message. I have tried many of the fixes suggested in the PyProj4 documentation page for this.
> 
> I created new conda environment and installed a fresh version of geopandas - this [way ](https://geopandas.org/getting_started/install.html). I still gave me the same error.
> 
> The docs on this [page ](https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select) suggest setting a project directory using `pyproj.datadir.set_data_dir(proj_data_dir: Union[str, pathlib.Path]) → None` which takes as a parameter `The path to the PROJ data directory.`
> 
> What does PROJ data directory refer to???

@basillatif this Stackoverflow thread may help you. https://gis.stackexchange.com/questions/383883/pyproj-invalid-projection-init-epsg25832/431688#431688

**Comment by jeanbaptisteb** [comment]
> Specifically in your case, it seems that you installed pyproj using pip (as a wheel, because it looks for PROJ data inside the pyproj package), and not with conda (although you are using a conda environment). It's best to install all those packages with conda (especially for non-pure python packages such as pyproj)

From this answer, I assume there is no other solution than using conda. The problem is that it's apparently impossible to have conda without Anaconda (https://stackoverflow.com/questions/67312469/how-to-install-conda-without-anaconda-or-miniconda-installer), and Anaconda is no longer free for many users, per their new terms of service. It would be great to have another solution that does not rely on conda!

**Comment by martinfleis** [comment]
@jeanbaptisteb You can use `conda` without `Anaconda` with `miniconda` or its alternatives like `miniforge` or `mambaforge`. You can also use `micromamba` and use mamba instead of conda.

> The problem is that it's apparently impossible to have conda without Anaconda

This is false.

**Comment by jeanbaptisteb** [comment]
> @jeanbaptisteb You can use `conda` without `Anaconda` with `miniconda` or its alternatives like `miniforge` or `mambaforge`. You can also use `micromamba` and use mamba instead of conda.
> 
> > The problem is that it's apparently impossible to have conda without Anaconda
> 
> This is false.

Oh ok, my bad. Thanks for the explanation.

**Comment by jorisvandenbossche** [comment]
> From this answer, I assume there is no other solution than using conda. 

And to be clear, you don't have to use conda, you _can_ use pip. In this specific issue however it's mixing of conda and pip that gave problems.

**Comment by WaelJRD** [comment]
Hello, I don't understand why I still have the same problem. last year it worked and not now : 

import geopandas as gpd
pyproj.datadir.get_data_dir()_ 
=> 'C:\\Users\\Users\\Anaconda3\\lib\\site-packages\\pyproj\\proj_dir\\share\\proj'

gpd.read_file('file.shp')

=> Invalid projection: epsg:4326: (Internal Proj Error: proj_create: SQLite error on SELECT name, type, coordinate_system_auth_name, coordinate_system_code, datum_auth_name, datum_code, area_of_use_auth_name, area_of_use_code, text_definition, deprecated FROM geodetic_crs WHERE auth_name = ? AND code = ?: no such column: area_of_use_auth_name)

**Comment by jorisvandenbossche** [comment]
Can you show the output of `geopandas.show_versions()` and `pyproj.show_versions()`?

**Comment by WaelJRD** [comment]
@jorisvandenbossche  : 
pyproj version :  2.6.1.post1
geopandas version : 0.9.0

**Comment by jorisvandenbossche** [comment]
Please show the full output of those functions, not just the versions

**Comment by WaelJRD** [comment]
gpd.show_versions() : 

SYSTEM INFO
-----------
python     : 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\wael\Anaconda3\python.exe
machine    : Windows-10-10.0.19041-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.0.2
GDAL data dir: None
PROJ       : 6.2.1
PROJ data dir: C://Users/wael/Anaconda3/Lib/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.3.3
fiona      : 1.8.13.post1
numpy      : 1.21.2
shapely    : 1.7.1
rtree      : 0.9.3
pyproj     : 2.6.1.post1
matplotlib : 3.4.3
mapclassify: 2.4.3
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None


pyproj info:
    pyproj: 2.6.1.post1
      PROJ: 6.2.1
  data dir: C://Users/wael/Anaconda3/Lib/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\wael\Anaconda3\python.exe
   machine: Windows-10-10.0.19041-SP0

#######################################

pyproj.show_versions()

Python deps:
       pip: 21.0.1
setuptools: 58.0.4
    Cython: 0.29.24

**Comment by jorisvandenbossche** [comment]
@WaelJRD it seems you have a mixture of pip and conda packages. If you are using Anaconda, we strongly recommend installing geopandas and all its dependencies (pyproj, fiona, shapely) using conda from conda-forge (see https://geopandas.org/en/stable/getting_started/install.html#using-the-conda-forge-channel). 
In your case, I can see that pyproj is installed as a wheel, but based on the GDAL version, that is installed using conda (and thus also PROJ is installed using conda).

**Comment by WaelJRD** [comment]
Thank you @jorisvandenbossche :-)

**Comment by MAfarrag** [comment]
just uninstall pyproj from conda 
`conda remove --force pyproj`
then install it using pip
`pip install pyproj`

**Comment by mikaelagordon** [comment]
I have been having the same issues as everyone here and have tried to fix it but can't seem to. Can someone please help me? Also, I am new so if you are as direct as possible with a solution I would be grateful haha. See my versions and info below:

SYSTEM INFO
-----------
python     : 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
executable : C:\Users\mikae\Anaconda3\python.exe
machine    : Windows-10-10.0.22000-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 2.3.3
GDAL data dir: None
PROJ       : 8.1.1
PROJ data dir: C:\Users\mikae\Anaconda3\lib\site-packages\pyproj\proj_dir\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 0.25.1
fiona      : 1.8.4
numpy      : 1.16.5
shapely    : 1.6.4.post1
rtree      : 0.9.7
pyproj     : 3.2.1
matplotlib : 3.3.2
mapclassify: None
geopy      : 2.3.0
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None
pyproj info:
    pyproj: 3.2.1
      PROJ: 8.1.1
  data dir: C:\Users\mikae\Anaconda3\lib\site-packages\pyproj\proj_dir\share\proj
user_data_dir: C:\Users\mikae\AppData\Local/proj

System:
    python: 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
executable: C:\Users\mikae\Anaconda3\python.exe
   machine: Windows-10-10.0.22000-SP0

Python deps:
   certifi: 2020.06.20
       pip: 19.2.3
setuptools: 41.4.0
    Cython: 0.29.13

**Comment by jorisvandenbossche** [comment]
See my comment just above (https://github.com/geopandas/geopandas/issues/1887#issuecomment-1287694730). You have installed pyproj using pip in a conda environment, and depending on what else is installed in that environment using conda, that can give conflicts.

**Comment by lucijaprodan** [comment]
Hi everyone! I've been getting this error and I don't know how to fix it, can someone please help me?
CRSError: Invalid projection: EPSG:4326: (Internal Proj Error: proj_create: no database context specified)

These are my system informations:

**gpd.show_versions()**  : 

SYSTEM INFO
-----------
python     : 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)]
executable : C:\Users\asdfg\Anaconda3\envs\geo_env\python.exe
machine    : Windows-10-10.0.19044-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.6.2
GDAL data dir: None
PROJ       : 9.1.1
PROJ data dir: C:\Users\asdfg\Anaconda3\envs\geo_env\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.24.2
pandas     : 1.5.3
pyproj     : 3.4.1
shapely    : 2.0.1
fiona      : 1.9.1
geoalchemy2: None
geopy      : 2.3.0
matplotlib : 3.7.1
mapclassify: 2.5.0
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : 1.0.1

**pyproj.show_versions() :** 

pyproj info:
    pyproj: 3.4.1
      PROJ: 9.1.1
  data dir: C:\Users\asdfg\Anaconda3\envs\geo_env\Library\share\proj
user_data_dir: C:\Users\asdfg\AppData\Local/proj
PROJ DATA (recommended version): None
PROJ Database: None.None
EPSG Database: None [None]
ESRI Database: None [None]
IGNF Database: None [None]

System:
    python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)]
executable: C:\Users\asdfg\Anaconda3\envs\geo_env\python.exe
   machine: Windows-10-10.0.19044-SP0

Python deps:
   certifi: 2022.12.7
    Cython: None
setuptools: 67.6.0
       pip: 23.0.1
       
       
**pyproj.datadir.get_data_dir()** : 

'C:\\Users\\asdfg\\Anaconda3\\envs\\geo_env\\Library\\share\\proj'

**Comment by WaelJRD** [comment]
look to the comment of Mr jorisvandenbossche on Oct 22, 2022 (https://github.com/geopandas/geopandas/issues/1887#issuecomment-1287694730)

**Comment by lucijaprodan** [comment]
I did read it but how can I know what was installed via pip? And should I delete those and install them via conda?
I installed geopandas via conda forge.

**Comment by m-richards** [comment]
Running `conda list` in the environment will show you which packages come from conda and which come from pypi. My suggestion would be to create a new conda environment and install geopandas from conda-forge and ensure that works correctly.

**Comment by lucijaprodan** [comment]
I checked and all of the packages are from conda-forge but I will try and create a new conda environment. Thanks for the suggestion
