### ISSUE TITLE
BUG: Geopandas with pygeos removes z-coordinate if the first z-coordinate is NaN

### ISSUE THREAD

**Issue by woest** [geopandas/geopandas#1888]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
import pandas as pd
import numpy as np
import shapely.geometry

coords1 = np.array([
    [1, 2, 3],
    [1, 1, np.NaN],
])

coords2 = np.array([
    [1, 1, np.NaN],
    [1, 2, 3],
])

for coords in [coords1, coords2]:
    geom = shapely.geometry.LineString(coords)
    print(np.array(geom.coords))
    df = gpd.GeoDataFrame(pd.DataFrame({'geometry': [geom]}))
    print(np.array(df.geometry.iat[0].coords))
    print('\n')

```

#### Problem description

In Geopandas 0.9.0, if the first z-value of a linestring is NaN, the z-dimension is removed. This seems to be a new bug, as geopandas <0.9 did not have this problem.

#### Expected Output (on 0.8)

```python
[[ 1.  2.  3.]
 [ 1.  1. nan]]
[[ 1.  2.  3.]
 [ 1.  1. nan]]


[[ 1.  1. nan]
 [ 1.  2.  3.]]
[[ 1.  1. nan]
 [ 1.  2.  3.]]
```

#### Output on 0.9.0

```python
[[ 1.  2.  3.]
 [ 1.  1. nan]]
[[ 1.  2.  3.]
 [ 1.  1. nan]]


[[ 1.  1. nan]
 [ 1.  2.  3.]]
[[1. 1.]
 [1. 2.]]
```

#### Output of ``geopandas.show_versions()``

<details>

-----------
python     : 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\USERNAME\Miniconda3\python.exe
machine    : Windows-10-10.0.18362-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.2.1
GDAL data dir: None
PROJ       : 7.2.0
PROJ data dir: C:\Users\USERNAME\Miniconda3\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.3
fiona      : 1.8.18
numpy      : 1.20.1
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.0.1
matplotlib : 3.3.4
mapclassify: None
geopy      : 2.1.0
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : 0.9

</details>

**Comment by woest** [comment]
after further debugging, this seems to be due to pygeos/shapely. After uninstalling pygeos, the problem goes away.

I cannot really pinpoint where the error is, but it seems that pygeos incorrectly reports that the second set of coordinates 'has_z' is false.

As this does affect geopandas, I won't close this issue, unless you decide otherwise.

```python
import numpy as np
import pygeos
import shapely.wkb

coords1 = [
    (1, 2, 3),
    (1, 1, np.NaN),
]

coords2 = [
    (1, 1, np.NaN),
    (1, 2, 3),
]

for coords in [coords1, coords2]:
    geom1 = pygeos.creation.linestrings(coords)
    print(pygeos.geometry.get_coordinate_dimension(geom1))
    print(pygeos.predicates.has_z(geom1))
    print(pygeos.coordinates.get_coordinates(geom1, include_z=True))
    geom2 = shapely.wkb.loads(pygeos.to_wkb(geom1))
    print(np.array(geom2.coords))
    print('\n')
```


#### Output

```python
3
True
[[ 1.  2.  3.]
 [ 1.  1. nan]]
[[ 1.  2.  3.]
 [ 1.  1. nan]]


3
False
[[ 1.  1. nan]
 [ 1.  2.  3.]]
[[1. 1.]
 [1. 2.]]
```

**Comment by jorisvandenbossche** [comment]
@woest thanks a lot for the report and the debugging!

I don't think there is an easy way to workaround this in geopandas, and so will need to be solved on the pygeos/shapely side. And since there is already active discussion about it on the pygeos/pygeos#323 issue you opened, let's close this one.

**Comment by jorisvandenbossche** [comment]
There is actually one more thing at play here. So the first issue is that depending on whether the first z-coordinate is NaN or not, `has_z` can return a wrong value. This is what's being discussed in pygeos/pygeos#323, but this *also* applies to Shapely (since the behaviour comes from the underlying GEOS library).

However, with Shapely, there is another issue as well (and which is the reason that you see a change in behaviour when un-installing pygeos). Depending on how the geometry is created, it has a different "dimension" stored internally. Using your `coords2` from above:

```
In [48]: LineString(coords2)._ndim
Out[48]: 3

In [49]: LineString(coords2).has_z
Out[49]: False

In [50]: shapely.wkb.loads(LineString(coords2).wkb)._ndim
Out[50]: 2

In [51]: shapely.wkb.loads(LineString(coords2).wkb).has_z
Out[51]: False
```

So while `has_z` returns (incorrectly) False for both cases, the `_ndim` is inconsistent (thus depends on how the geometry is created, from coordinates or from WKB). And it is depending on this `_ndim` attribute that the `.coords` will return a `(n, 2)` array or a `(n, 3)` array.
