### ISSUE TITLE
DOC: `from_wkt()`, `from_wkb()`, `to_wkt()`, `to_wkb()` not in API reference

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1889]
New methods added in #1710 are not in the API reference in the documentation. We should add them here to `doc/source/docs/reference/geoseries.rst`.

**Comment by mesejo** [comment]
Hey, can I work on this?

**Comment by martinfleis** [comment]
@mesejo yes, that'd be great! Thanks!

**Comment by mesejo** [comment]
@martinfleis Great! Just a question, should I put them under the "Constructor" section or the "Reading and writing files"?
