### ISSUE TITLE
Implement to_sql()

### ISSUE THREAD

**Issue by kjordahl** [geopandas/geopandas#189]
The pandas [`to_sql()`](http://pandas.pydata.org/pandas-docs/dev/generated/pandas.DataFrame.to_sql.html) method should be overridden to implement writing to spatial databases (e.g. postGIS and spatialite).

**Comment by jdmcbr** [comment]
Let's close this. We can open more specific issues around implementations of different spatial databases, but we do have a `to_sql` method that can write to postgis databases via #1248

**Comment by jorisvandenbossche** [comment]
The method is called `to_postgis` to be correct, but indeed, this can be closed. Thanks!
