### ISSUE TITLE
BUG: Tests failing on matplotlib import

### ISSUE THREAD

**Issue by johnflavin** [geopandas/geopandas#1897]
Some of the tests appear to be failing (more precisely, causing an error on collection) in the 3.8-dev environment when importing matplotlib. This was discovered in #1891 (see [test run](https://github.com/geopandas/geopandas/pull/1891/checks?check_run_id=2256509714)).

### pytest error output
<details>
<pre>
___________ ERROR collecting geopandas/tests/test_extension_array.py ___________
1969
geopandas/tests/test_extension_array.py:21: in <module>
1970
    from pandas.tests.extension import base as extension_tests
1971
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/tests/extension/base/__init__.py:66: in <module>
1972
    from pandas.tests.extension.base.reshaping import BaseReshapingTests  # noqa
1973
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/tests/extension/base/reshaping.py:6: in <module>
1974
    import pandas.util._test_decorators as td
1975
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/util/_test_decorators.py:186: in <module>
1976
    _skip_if_no_mpl(), reason="Missing matplotlib dependency"
1977
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/util/_test_decorators.py:101: in _skip_if_no_mpl
1978
    mod = safe_import("matplotlib")
1979
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/util/_test_decorators.py:77: in safe_import
1980
    mod = __import__(mod_name)
1981
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:839: in <module>
1982
    rcParamsDefault = _rc_params_in_file(
1983
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:773: in _rc_params_in_file
1984
    config[key] = val  # try to convert to proper type or raise
1985
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:607: in __setitem__
1986
    raise ValueError(f"Key {key}: {ve}") from None
1987
E   ValueError: Key backend: '' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
1988
___________ ERROR collecting geopandas/tests/test_extension_array.py ___________
1989
geopandas/tests/test_extension_array.py:21: in <module>
1990
    from pandas.tests.extension import base as extension_tests
1991
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/tests/extension/base/__init__.py:66: in <module>
1992
    from pandas.tests.extension.base.reshaping import BaseReshapingTests  # noqa
1993
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/tests/extension/base/reshaping.py:6: in <module>
1994
    import pandas.util._test_decorators as td
1995
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/util/_test_decorators.py:186: in <module>
1996
    _skip_if_no_mpl(), reason="Missing matplotlib dependency"
1997
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/util/_test_decorators.py:101: in _skip_if_no_mpl
1998
    mod = safe_import("matplotlib")
1999
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pandas/util/_test_decorators.py:77: in safe_import
2000
    mod = __import__(mod_name)
2001
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:839: in <module>
2002
    rcParamsDefault = _rc_params_in_file(
2003
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:773: in _rc_params_in_file
2004
    config[key] = val  # try to convert to proper type or raise
2005
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:607: in __setitem__
2006
    raise ValueError(f"Key {key}: {ve}") from None
2007
E   ValueError: Key backend: '' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
2008
______________ ERROR collecting geopandas/tests/test_plotting.py _______________
2009
geopandas/tests/test_plotting.py:28: in <module>
2010
    matplotlib = pytest.importorskip("matplotlib")
2011
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:839: in <module>
2012
    rcParamsDefault = _rc_params_in_file(
2013
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:773: in _rc_params_in_file
2014
    config[key] = val  # try to convert to proper type or raise
2015
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:607: in __setitem__
2016
    raise ValueError(f"Key {key}: {ve}") from None
2017
E   ValueError: Key backend: '' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
______________ ERROR collecting geopandas/tests/test_plotting.py _______________
geopandas/tests/test_plotting.py:28: in <module>
2020
    matplotlib = pytest.importorskip("matplotlib")
2021
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:839: in <module>
2022
    rcParamsDefault = _rc_params_in_file(
2023
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:773: in _rc_params_in_file
2024
    config[key] = val  # try to convert to proper type or raise
2025
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/matplotlib/__init__.py:607: in __setitem__
2026
    raise ValueError(f"Key {key}: {ve}") from None
2027
E   ValueError: Key backend: '' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'MacOSX', 'nbAgg', 'Qt4Agg', 'Qt4Cairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
</pre>
</details>

**Comment by johnflavin** [comment]
Probably the same issue as https://github.com/matplotlib/matplotlib/issues/19848, for which a fix was already merged to matplotlib master in https://github.com/matplotlib/matplotlib/pull/19855. I bet if the tests on #1891 were reran this would be fixed already.

**Comment by martinfleis** [comment]
Thanks for looking into this. It is indeed fixed. I have merged #1878 which should make CI green again.

**Comment by johnflavin** [comment]
Yes, rerunning the tests confirmed that this has been fixed upstream.
