### ISSUE TITLE
QST: Can we plot/print the digits(values) of the variable considered on the respective states/cities/countries while plotting a choropleth map? If yes, how?

### ISSUE THREAD

**Issue by AjinkyaP1998** [geopandas/geopandas#1898]
I have a GeoDataFrame with one column having the geometry and the other column having values of a certain variable.
The following picture shows the data.

![Screenshot (44)](https://user-images.githubusercontent.com/66870664/113550115-2d626b80-9610-11eb-82c1-0eb83450a1f4.png)

I am trying to plot a choropleth map using Geopandas but I also want the variable value plotted on the map at respective states.
Is this possible in Geopandas? How can I do it?

**Comment by martinfleis** [comment]
GeoPandas plot is a `matplotlib` figure, which means that you can use `matplotlib`'s machinery to do annotations. See the example below to plot names of boroughs on top of their polygons.

To use `plt.annotate` you need to know the text you want to plot and coordinates where to place it. We can use centroid (or representative point...) to get such coordinates. I am also passing ` horizontalalignment='center'` to align the text to the center.

```py
import geopandas as gpd
import matplotlib.pyplot as plt

nybb = gpd.read_file(gpd.datasets.get_path('nybb'))
centroids = nybb.centroid
x_coords = centroids.x
y_coords = centroids.y

nybb.plot(figsize=(12, 12))

for name, x, y in zip(nybb['BoroName'], x_coords, y_coords):
    plt.annotate(name, (x, y),  horizontalalignment='center')
```

<img width="633" alt="Screenshot 2021-04-05 at 10 55 10" src="https://user-images.githubusercontent.com/36797143/113562063-65ac7e80-95fd-11eb-9856-22690ca225f7.png">

You may also find solutions using `apply` but that is less performant as it does not use vectorization to get coordinates (while the code above does).

**Comment by AjinkyaP1998** [comment]
Hey @martinfleis!
Got it. Thanks.
