### ISSUE TITLE
Distance and area still in degrees even reprojected to EPSG:3857 whose unit is in meter

### ISSUE THREAD

**Issue by nuistzhou** [geopandas/geopandas#1901]
I convert the dataframe to a geodataframe using command below: 

`gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.lon, df.lat, crs="epsg:3857"))`
 
and I did double checked that the crs of this gdf is indeed "epsg:3857" using:

`gdf.crs`

The other geodataframe is also created this way.

Then when I use `distance` and `area` to calcualte, the result is still in degrees, which does not make sense at all.

**Comment by martinfleis** [comment]
I assume that `df.lon`, `df.lat` are coordinates in degrees. Therefore you need to reproject them to 3857. You have only assigned 3857.

```py
gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.lon, df.lat, crs="epsg:4326")
gdf_projected = gdf.to_crs(3857)
```

Then all metric methods (distance, area) called on `gdf_projected` will be in meters. 

Note that 3857 is in meters but can be extremely unprecise when measuring areas and distances, esp. towards poles.

**Comment by nuistzhou** [comment]
> I assume that `df.lon`, `df.lat` are coordinates in degrees. Therefore you need to reproject them to 3857. You have only assigned 3857.
> 
> ```python
> gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.lon, df.lat, crs="epsg:4326")
> gdf_projected = gdf.to_crs(3857)
> ```
> 
> Then all metric methods (distance, area) called on `gdf_projected` will be in meters.
> 
> Note that 3857 is in meters but can be extremely unprecise when measuring areas and distances, esp. towards poles.

This did help me ! Sorry that I mix up the assignee and the real projecting.
