### ISSUE TITLE
ENH: Interactive plotting API

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1904]
We (@Sangarshanan and myself) are finishing the work on interactive plotting based on `folium` - see https://github.com/martinfleis/geopandas-view for details on that and a notebook with examples - https://nbviewer.jupyter.org/github/martinfleis/geopandas-view/blob/main/examples.ipynb. 

One of the major things now is to resolve the API. We can think of a few options:

1. use it as a backend for  - `gdf.plot(backend="folium")` or via global switch
2. add it as a plotting kind - `gdf.plot(kind="interactive/folium")` or `gdf.plot.interactive()`
3. add it is an independent method - `gdf.interactive()` (or some other keyword).

The first and the second option can cause a bit of trouble since they may conflict with the existing pandas plotting backends but we would have to look into that.

I currently prefer the last option + mirroring the backend management pandas has for its plots. We would always get an interactive map from the `gdf.interactive()` method. By default, the implementation based on folium but we can open the API to other options like `ipyleaflet` or `hvplot` to allow something like this:

```py
gdf.interactive(column='foo', cmap='viridis', legend=True, backend='folium')
gdf.interactive(column='foo', cmap='viridis', legend=True, backend='ipyleaflet')
gdf.interactive(column='foo', cmap='viridis', legend=True, backend='hvplot')

# or ideally with some global switch

gpd.options.interactive.backend = "backend.module"
```

Links to ipyleaflet and hvplot should not be complicated given their current support of geodataframes and can be done in downstream.

Another argument for an independent method is the potential to expand it with other plotting kinds as `MarkerCluster` or `Heatmap` -> `gdf.interactive.markercluster()`. Having it separated from the `plot` API feels like the cleanest solution.

cc-ing @jbednar and @philippjfr for `hvplot` and @martinRenou for `ipyleaflet` to get your views on the idea of interactive backends (whether it is worth doing from your perspective).

---
To give you a bit of a context why we decided to go with folium instead of other options: we wanted to go with leaflet.js as it is widely used across the ecosystem (in both Python and R) and has the _Google maps-like_ feeling people are used to. Between `folium` and `ipyleaflet`, the former is much lighter and does not depend on Jupyter lab (GeoPandas has a lot of users not working with JL so it would be suboptimal to support interactive plotting only under JL).

**Comment by philippjfr** [comment]
This is great! As you say the mechanism for swapping backends should be modeled on what pandas has done but I do see the potential on confusion here. Does `GeoDataFrame` currently just override the pandas plot accessor? If so I think the best solution in the long run is to coordinate with pandas to allow extending the plotting interface in a clean way rather than overriding it wholesale. In the short term that doesn't leave many good options though.

Personally I'd hope a better name than `.interactive` could be found though since it doesn't suggest anything about plotting to me. Secondly though it also clashes with a feature I implemented for hvPlot which also uses an `interactive` accessor to dynamically build interactive pipelines. The hvPlot docs focus on xarray but the accessor works equally well for pandas, dask and geopandas DataFrame objects: https://hvplot.holoviz.org/user_guide/Interactive.html. I realize that may not be a particularly strong reason for you though.

So overall I'd suggest we work towards making pandas plotting extensible and in the short term the best suggestion I have is adding it via `iplot` or similar.

**Comment by martinRenou** [comment]
@SylvainCorlay @davidbrochart for awareness

**Comment by martinfleis** [comment]
>  Does GeoDataFrame currently just override the pandas plot accessor?

@philippjfr Yes but the full pandas functionality including backends still works as you know it. We just change the default to use `kind="geo"` which uses our internal mapping module no matter the backend.

If I read your suggestion correctly, you'd keep the API as `gdf.plot()` and change backends between matplotlib, folium, holoviews etc.? The tricky aspect of that is that with `folium` backend you'll be able to create a map but not e.g. bar plot. We may try to control `kind="geo"` backend independently / fallback to pandas default or something along that.

> Personally I'd hope a better name than `.interactive` could be found though since it doesn't suggest anything about plotting 

Agree.

---

I now realised that I forgot to add plotly to the mix (cc @nicolaskruchten).

**Comment by nicolaskruchten** [comment]
👋 Thanks for thinking of us! We'd be glad to work on a pluggable backend here, indeed. I found the way the Pandas pluggable backend works to be pretty easy to integrate with. I especially liked that it didn't impose a lot in terms of which kwargs we *had* to implement i.e. the `.bar()` implementation for the Plotly backend doesn't accept the same kwargs as the Matplotlib one and I found this really nice, even if it means that the Plotly backend isn't a drop-in replacement.

**Comment by martinfleis** [comment]
I think that https://github.com/martinfleis/geopandas-view is ready to be merged in geopandas so the remaining part to figure out is the API.

ping @geopandas/collaborators & @Sangarshanan - what are your thoughts on this?

**Comment by TLouf** [comment]
Having some experience in using GeoPandas and plotly to plot interactive maps, I'd be glad to work on the plotly backend!

To give my unsolicited opinion on the API, I really like the way it's done in pandas too, I think converging to the same API would be best in the long run for GeoPandas. Extending `GeoplotAccessor` in the same way as `PlotAccessor` with a call to an equivalent of  `_get_plot_backend` for geographic kinds seems rather straightforward to me. Also, other map kinds could be added on top of the generic 'geo'. Although not so many come to mind, a 'heatmap' ([implemented in plotly](https://plotly.com/python/mapbox-density-heatmaps/)) or 'contourf' (in hvPlot) kind could be nice for instance. All backends won't be able to make every kind of plots, but I think it's fine to raise a `NotImplementedError` from the backend when this comes up, suggesting alternatives when available, [as is done in plotly for pandas at the moment](https://github.com/plotly/plotly.py/blob/5e327e76e11c5e8a82d74d9d2ea0a44519a4b43e/packages/python/plotly/plotly/__init__.py#L128).

**Comment by martinfleis** [comment]
The current proposal discussed during the last dev call is to create a new method `GeoDataFrame.explore()` dedicated to interactive plotting/exploration. By default, `explore` will use folium-based implementation which is being developed in https://github.com/martinfleis/geopandas-view but it will allow specification of `backend` in a similar way you can specify pandas plotting backend (either via keyword or a global config).

There a few reasons for this. Mainly, the use case of static and interactive maps is different and we want to keep both methods easily available. Also, implementing interactive maps as a backend for `plot` could result in various conflicts with pandas plotting backends and it is better to be explicit here, that we're setting backend for `explore` only to get interactive maps.

Unless anyone has a strong opinion against this proposal, we'll move forward with it to have it ready for the next release.

**Comment by martinfleis** [comment]
See https://github.com/geopandas/geopandas/pull/1953
