### ISSUE TITLE
DOC: Clarify the meaning of tolerance in GeoSeries.simplify

### ISSUE THREAD

**Issue by serghiou** [geopandas/geopandas#1905]
Hi there,

GeoPandas is such a powerful tool! I wanted to point out that novice users may benefit from noting that tolerance is tied to the coordinate system of their geometry. This is not immediately clear from the current definition:

https://github.com/geopandas/geopandas/blob/08cb5909b88837a2a963f22a81874287ea2ef5ae/geopandas/base.py#L2729-L2731

As such, applying the simplification before or after a projection (without changing the tolerance) can lead to unexpected results. I feel that future users may find it useful to emphasize that tolerance has units. In addition to the current definition, something along the lines of the following may be helpful: 

**"Tolerance is  assumed to be in the units of the coordinate system being used; for example, if using a Mercator projection,`tolerance=300` would suggest a tolerance distance of 300 meters."**

I hope this is helpful!

**Comment by martinfleis** [comment]
Agree that it would deserve clarification. It may be also useful to use something from https://martinfleischmann.net/line-simplification-algorithms/ which explains what the tolerance actually refers to in Douglas-Peucker algorithm used by geopandas.

**Comment by serghiou** [comment]
That's a fantastic post - I wish I had seen it earlier. This would definitely help users!

**Comment by simberaj** [comment]
This is probably closed by #1942

**Comment by jorisvandenbossche** [comment]
Indeed, thanks!
