### ISSUE TITLE
BUG: Losing the geometry column should convert to a DataFrame

### ISSUE THREAD

**Issue by arredond** [geopandas/geopandas#1911]
Branched out from the discussion in #1653 

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

From @jorisvandenbossche 's comment in #1653 

```python
df = geopandas.read_file(geopandas.datasets.get_path("naturalearth_cities"))

type(df.drop("geometry", axis=1)) # geopandas.geodataframe.GeoDataFrame
type(df.reindex(columns=["name"])) # geopandas.geodataframe.GeoDataFrame
```

#### Problem description

When a GeoDataFrame loses its geometry column (via `.drop()` or `.reindex()`, for instance), the result should be a regular pandas DataFrame. This makes intuitive sense and would allow easier compatibility with the pandas API, as well as preventing issues such as the one found in #1653.

Right now, these methods are simply inherited from the DataFrame class but we can overwrite them in the GeoDataFrame to automate this downcasting when possible.

#### Expected Output

```python
type(df.drop("geometry", axis=1)) # pandas.core.frame.DataFrame
type(df.reindex(columns=["name"])) # pandas.core.frame.DataFrame
```

**Comment by arredond** [comment]
While playing around I've seen that using the standard `.rename()` method can lead to a discrepancy between the column's new name and the internal properties:

```python
gdf = gpd.read_file(get_path('naturalearth_cities'))

gdf._geometry_column_name # 'geometry'

gdf.rename(columns={'geometry': 'geom'}, inplace=True)
gdf._geometry_column_name # still 'geometry'
gdf.geometry # raises ValueError since column 'geometry' can't be found
```

I suppose this is why `.rename_geometry()` exists but maybe we could also overwrite `.rename()` so that, if the geometry column is included, this is handled internally by `rename_geometry()` as well?

**Comment by arredond** [comment]
Also, regarding selecting columns, this works just fine:

```python
type(gdf[['name']]) # pandas.core.frame.DataFrame
``` 

However, when using `.loc` or `.iloc`, the GeoDataFrame is kept:

```python
type(gdf.loc[:, ['name']]) # geopandas.geodataframe.GeoDataFrame
type(gdf.iloc[:, [0]]) # geopandas.geodataframe.GeoDataFrame
```

**Comment by martinfleis** [comment]
This has been discussed before in #544, #1153 and #1856. It would be great to finally resolve it.

**Comment by arredond** [comment]
I've been looking at similar existent implementations of pandas' method overrides, such as `GeoDataFrame.merge` and it _looks_ straightforward enough. Happy to give this a shot. Should I assign this to myself somehow? Or is providing a PR enough?

**Comment by martinfleis** [comment]
Would be great to have a solution which would return `pandas.DataFrame` in these cases without the need to override all these methods but that may not be possible.

**Comment by arredond** [comment]
Any idea how that could be accomplished? Some sort of internal method that ran every time a GeoDataFrame is modified, checking the geometry column is still there and, if not, downcasting to a regular DataFrame? Not sure if that's even possible or whether it would require using metaclasses or some other magic.

For the implementation, I've thought of simply creating a decorator, then using it to override all of these methods. It isn't that pretty but at least the logic would be encapsulated in the decorator and the overrides would be simple enough (just calling `super` and the method itself).

And regarding `super`... I've seen that, in some places we're using `super()` (Python 3 version) and, in others, we're using `super(GeoDataFrame, self)` (Python 2 version). Is there a reason for this? Should we standardize?

**Comment by martinfleis** [comment]
> Any idea how that could be accomplished?

Not really but I am not as fluent in pandas internals as @jorisvandenbossche is. The decorator sounds fine.

> And regarding `super`

See #1885

**Comment by m-richards** [comment]
Hi @arredond is this still something you are planning on working on? This is something I'd quite like to see in geopandas, and if you're not, I'd like to make a start on it.

**Comment by martinfleis** [comment]
@m-richards I'd say you can go for it.

**Comment by jorisvandenbossche** [comment]
For a possible solution, I think we should also look into the suggestion I wrote down in https://github.com/geopandas/geopandas/issues/1153, having a `GeoDataFrame._constructor` that holds this logic of returning a GeoDataFrame or a DataFrame.
