### ISSUE TITLE
BUG: Writing to GeoPackage doesn't check for SQL-protected words in column names or "forbidden" characters in layer names

### ISSUE THREAD

**Issue by phildias** [geopandas/geopandas#1914]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd

test_gdf = gpd.GeoDataFrame({'my_id':[1,2,3],
                             'select':[1,2,3],
                             'count':[1,2,3]},
                            geometry=gpd.points_from_xy([0,1,2], [0,1,2]),
                            crs='epsg:4326')

test_gdf.to_file('test.gpkg', driver='GPKG',layer='with-hyphen')

```

#### Problem description
The code above **does not throw** any kind of error. The issue here is that **it should!** The newly-generated GeoPackage file is not readable, for example, in ArcGIS Pro. This is because of two problems: 
1) There are column names that use SQL protected words, like `SELECT` and `COUNT`. 
2) The layer name contains a hyphen, which shouldn't be allowed (I think this is also a SQL restriction)

#### Expected Output
I expect the columns to be automatically renamed to avoid clashes with SQL-protected words. Clashing columns can have an underscore added to the end. 

Furthermore, layer names should automatically transform hyphens into underscores.

Note: Since this is likely related to `Fiona`, I've also opened up an [issue on their GitHub](https://github.com/Toblerity/Fiona/issues/1009).

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
executable : C:\ProgramData\Anaconda3\envs\myenv\python.exe
machine    : Windows-10-10.0.17763-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.0.2
GDAL data dir: None
PROJ       : 6.2.1
PROJ data dir: C:\ProgramData\Anaconda3\envs\myenv\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0+10.g37ffc35
pandas     : 1.2.3
fiona      : 1.8.13.post1
numpy      : 1.19.1
shapely    : 1.7.1
rtree      : 0.9.4
pyproj     : 2.6.1.post1
matplotlib : 3.3.1
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : 0.9

</details>

## Important Context

When trying to read this `GPKG` file into ArcGIS Pro, it throws an error. I've been able to pinpoint the cause of that error to the two issues I detailed above. When I generate a `GPKG` file that avoids SQL-protected words and hyphens, ArcGIS Pro is able to read the `GPKG` file just fine. So this might be more ArcGIS Pro's issue than it is GeoPandas'.  

So please feel free to close this issue if you believe this shouldn't really be addressed by GeoPandas.

**Comment by martinfleis** [comment]
Thanks for the report!

I can only reiterate what was said in the fiona bug report. This does not seem to be an issue for geopandas or QGIS or indeed SQL itself. So it is likely an issue with ArcGIS Pro.
