### ISSUE TITLE
CI: arrow IO CI broken on defaults channel

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1918]
Our CI checking arrow (parquet/feather) using defaults channel IO is red after the environment started resolving with numpy 1.20 instead of 1.19, failing on:

```py
pyarrow.lib.ArrowTypeError: ('Did not pass numpy.dtype object', 'Conversion failed for column pop_est with type int64')
```

I guess that the reason is the ancient version of pyarrow which is in the defaults channel (0.15.1). I would skip these tests in there because we cannot control this on our end in any way. Alternatively, we can pin pyarrow to some sensible minimal requirement in the env file. I'll try that and see if it works and remove pyarrow form the env if it does not.

See the log: https://github.com/geopandas/geopandas/runs/2453237435?check_suite_focus=true#step:6:3039

**Comment by jorisvandenbossche** [comment]
Hmm, it's bizarre that it is installing pyarrow 0.15 (that package is indeed not compatible with latest numpy), since pyarrow 3.0 should now be available on the default channel ..
