### ISSUE TITLE
DOC: add links to relevant API to the user guide 

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1929]
We should ensure that when referring documented objects/methods in the user guide, we link to the relevant API pages using for example `:py:class:`GeoSeries` and intersphinx mapping to link pandas, pyproj, matplotlib et al. 

See the first step done in #1926 done by @raybellwaves for an illustration.

**Comment by mcanueste** [comment]
Hi, new here, can I work on this?

**Comment by martinfleis** [comment]
@mcanueste Hi, absolutely! Thanks!

**Comment by mcanueste** [comment]
Thanks, on it.
