### ISSUE TITLE
TypeError on adding a Point geometry

### ISSUE THREAD

**Issue by nheeren** [geopandas/geopandas#195]
Hello. I am pretty new to the world of python and GIS, so please excuse me if I am overlooking something rather important. I am trying to add a point geometry to a GeoDataFrame, but it will raise a `TypeError`. An example:

    test = gpd.GeoDataFrame(pd.DataFrame(['some','data']))
    test.loc[:,'geometry'] = [Point(0,1), Point(3,2)]

    TypeError: float() argument must be a string or a number

However, if I use a `Polygon` instead, it will work. E.g.:

    test.loc[:,'geometry'] = [Polygon([(0,1),(1,2),(0,2)]), Polygon([(1,2),(2,3),(1,3)])]

**Comment by kjordahl** [comment]
Hmm, I guess this way of adding a new column should work (and it does for `Polygon`s or non-geometry columns). It is a bit unusual, though. The preferred ways to add a geometry column would be either:

    test['geometry'] = [Point(0,1), Point(3,2)]
or

    test.set_geometry([Point(0,1), Point(3,2)], inplace=True)

**Comment by nheeren** [comment]
Thanks. I guess I was confused by the warning Pandas sometimes raises when you do this kind of insert. There the[recommended method](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy) is to use `.loc`.
