### ISSUE TITLE
BUG: Missing dependency for matplotlib package

### ISSUE THREAD

**Issue by asmaier** [geopandas/geopandas#1956]
- [ x] I have checked that this issue has not already been reported.

- [ x] I have confirmed this bug exists on the latest version of geopandas.

- [ x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world.plot()
```

#### Problem description

I installed geopandas via `pipenv install geopandas` . But the `matplotlib` dependency is missing from `setup.py`. So the simple example code above from the documentation raises an error

```
ImportError: The matplotlib package is required for plotting in geopandas.
```

I believe `matplotlib` should be included in the list of required dependencies, since plotting is really a very basic feature of the geopandas package. It is just annoying for first time users that one has to manually install a package to make plotting work. 

#### Expected Output

Expected output is a plot of the world map as shown in the documentation at https://geopandas.org/docs/user_guide/mapping.html

#### Output of ``geopandas.show_versions()``

<details>
SYSTEM INFO
-----------
python     : 3.9.0 (default, Oct 27 2020, 14:15:17)  [Clang 12.0.0 (clang-1200.0.32.21)]
executable : /Users/username/.local/share/virtualenvs/covid-UYjDG-ri/bin/python
machine    : macOS-10.15.7-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.3.0
GDAL data dir: /Users/username/.local/share/virtualenvs/covid-UYjDG-ri/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 8.0.1
PROJ data dir: /Users/username/.local/share/virtualenvs/covid-UYjDG-ri/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.4
fiona      : 1.8.20
numpy      : 1.20.3
shapely    : 1.7.1
rtree      : None
pyproj     : 3.1.0
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

**Comment by martinfleis** [comment]
Thanks for the note. There are two discussions on the same topic #1261 and #1313 so I'd move channel further discussion there.
