### ISSUE TITLE
TST: TestSeries.test_proj4strings fails with PROJ 8.0.1

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1957]
We have a new failure likely caused by PROJ 8.0.1. It worked with PROJ 8.0.0.

@snowman2 where should this be reported?

https://github.com/geopandas/geopandas/runs/2723837365?check_suite_focus=true#step:6:2654

```
_________________________ TestSeries.test_proj4strings _________________________
[gw0] linux -- Python 3.8.10 /usr/share/miniconda/envs/test/bin/python

self = <geopandas.tests.test_geoseries.TestSeries object at 0x7f22fc561d90>

    def test_proj4strings(self):
        # As string
>       reprojected = self.g3.to_crs("+proj=utm +zone=30N")

geopandas/tests/test_geoseries.py:265: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
geopandas/geoseries.py:1036: in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
geopandas/array.py:768: in to_crs
    crs = CRS.from_user_input(crs)
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyproj/crs/crs.py:466: in from_user_input
    return CRS(value, **kwargs)
/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyproj/crs/crs.py:313: in __init__
    self._local.crs = _CRS(self.srs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???

E   pyproj.exceptions.CRSError: Invalid projection: +proj=utm +zone=30N +type=crs: (Internal Proj Error: proj_create: Error 1027 (Invalid value for an argument): utm: Invalid value for zone)

pyproj/_crs.pyx:2326: CRSError
```

**Comment by snowman2** [comment]
Can you reproduce the issue with the `proj`\ `projinfo` commands?

**Comment by jorisvandenbossche** [comment]
I see "UTM: error out when value of +zone= is not an integer (#2672)" in the news file of the latest release: https://github.com/OSGeo/PROJ/blob/fdfeae1908e8bf9e199aed3654ff418aaaa4fe26/NEWS#L20. So this was probably on purpose.

-> https://github.com/OSGeo/PROJ/issues/2671

**Comment by martinfleis** [comment]
>> But so this only happened to work "by accident" before? (because the north zone is the default, eg using +zone=30S would still give the north zone)

>yes.

(https://github.com/OSGeo/PROJ/issues/2671#issuecomment-852985459)

This is interesting. We should probably change the test on our side then.
