### ISSUE TITLE
TST: adapt colorbar tests to changes in matplotlib master

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1962]
Matplotlib made a major overhaul of their colorbar machinery in https://github.com/matplotlib/matplotlib/pull/20054. As a consequence, some of our tests are now failing (see https://github.com/geopandas/geopandas/runs/2731536698?check_suite_focus=true#step:6:2974).

From what I understand, we need to fix our tests, not the implementation but I haven't dig deep into that.

**Comment by martinfleis** [comment]
Colorbars are now plotted differently, there is no collection on their axis anymore, causing this line (and same below) to fail on `IndexError: list index out of range` https://github.com/geopandas/geopandas/blob/fc6136480c36b02b0b008cb8c0e2eac08de3e994/geopandas/tests/test_plotting.py#L247

I don't know how to get those colors anymore.

The second failure here https://github.com/geopandas/geopandas/blob/fc6136480c36b02b0b008cb8c0e2eac08de3e994/geopandas/tests/test_plotting.py#L736 is caused by reorganization of axes. So the label is now accessible as `cax.child_axes[0].get_ylabel()` instead of `cax.get_ylabel()`. Similarly, line 746 now needs to be `cax.child_axes[0].get_xlabel()`.

The last failure is caused by the fact that the colorbar axis does not have the label passed in `divider.append_axes`, hence has no name.  Can be rewritten using 

```py
plot_height = fig.axes[0].get_position().height
legend_height =  fig.axes[1].get_position().height
```

https://github.com/geopandas/geopandas/blob/fc6136480c36b02b0b008cb8c0e2eac08de3e994/geopandas/tests/test_plotting.py#L1193-L1194

I can fix the second and third issues now, I'd appreciate help with the first one if there's someone more familiar with matplotlib internals.

**Comment by TLouf** [comment]
> I don't know how to get those colors anymore.

The breaking change from `matplotlib` is that the axis we get from `_get_colorbar_ax`, the one with label "<colorbar>", is no longer the one directly containing the `pcolormesh`. This is now drawn in a inset axis of the latter. To fix the test, `_get_colorbar_ax` should return this inset axis, by looking in the children of the currently returned axis for an axis with label "inset_axes". I made a quick test and it seems to work.

**Comment by martinfleis** [comment]
@TLouf would you like to turn it into a PR?

**Comment by TLouf** [comment]
Yes no problem, I'm on it.

**Comment by Zeroto521** [comment]
Guys.
After https://github.com/matplotlib/matplotlib/pull/20501 was merged, [CI](https://github.com/geopandas/geopandas/actions/runs/1009889442) got fail again.

There were some new changes to the colorbar.
