### ISSUE TITLE
help identifying error message

### ISSUE THREAD

**Issue by nejohnson2** [geopandas/geopandas#197]
I'm trying to use `sjoin` and I keep getting this error which I have no idea what it means.  I'm loosely following the `spatial_joins.ipynb` example.  Is this a bug or does this error something I'm doing wrong?

`RTreeError: Coordinates must not have minimums more than maximums`

**Comment by maxalbert** [comment]
Can you provide a minimal code example which reproduces this error? I'm not a `geopandas` developer so probably won't be able to help, but I'm sure it would save other people with more knowledge of `geopandas` a lot of time to dig into this issue if they had a code snippet that they can copy & paste. Thanks!

**Comment by jdmcbr** [comment]
@nejohnson2 I'm going to close this for now. If you are still seeing this issue, and can post an example that shows what leads to this error, I'm happy to re-open.
