### ISSUE TITLE
BUG: to_crs() returns inf polygon on MacOS (only)

### ISSUE THREAD

**Issue by cipri-tom** [geopandas/geopandas#1972]
- [x] I have checked that this issue has not already been reported. In fact, is has (#798 ), but I have been advised to open a new one.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```
conda create -n test-proj python geopandas
conda activate test-proj
conda env export > /tmp/test-proj-inf.yaml
```
Environment file on MacOS [test-proj-inf.yaml.zip](https://github.com/geopandas/geopandas/files/6661165/test-proj-inf.yaml.zip)

After these installation steps, I am reading and projecting [this minimal file](https://github.com/geopandas/geopandas/files/6638665/inf.geojson.zip) using the `proj` definition from [here](https://spatialreference.org/ref/esri/usa-contiguous-lambert-conformal-conic/)

```python
df = gpd.read_file('inf.geojson')
proj_df = df.to_crs(crs='+proj=lcc +lat_1=33 +lat_2=45 +lat_0=39 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs')
```

#### Problem description

The first row of `proj_df` has a Polygon consisting of only `inf` coordinates.

#### Expected Output

However, on my linux machine, I get a correct polygon:
`POLYGON ((273611.8084311375 -970145.3978538376, 273628.2693416685 -970144.8860112878, 273627.957304829 -970134.8531099072, 273611.4964131049 -970135.3649518734, 273611.8084311375 -970145.3978538376))`

I realise this may be a problem in one of the dependencies, rather than actual geopandas. If you can point me to the right one, I can open an issue there.

It seems that `gdal` version is different between the 2 machines. Could that be the issue ?

Thanks !

#### Output of ``geopandas.show_versions()`` on MacOS

<details>

SYSTEM INFO
-----------
python     : 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:15)  [Clang 11.1.0 ]
executable : /Users/a770pl/miniconda3/envs/test-proj/bin/python
machine    : macOS-10.15.7-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /Users/a770pl/miniconda3/envs/test-proj/lib/libgeos_c.dylib
GDAL       : 3.3.0
GDAL data dir: /Users/a770pl/miniconda3/envs/test-proj/share/gdal
PROJ       : 8.0.1
PROJ data dir: /Users/a770pl/miniconda3/envs/test-proj/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.4
fiona      : 1.8.20
numpy      : 1.20.3
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.1.0
matplotlib : 3.4.2
mapclassify: 2.4.2
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

#### Output of ``geopandas.show_versions()`` on Linux

<details>
SYSTEM INFO
-----------
python     : 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33)  [GCC 9.3.0]
executable : /home/ciprian/miniconda3/envs/test-env/bin/python
machine    : Linux-4.15.0-142-generic-x86_64-with-glibc2.27

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /home/ciprian/miniconda3/envs/test-env/lib/libgeos_c.so
GDAL       : 3.2.2
GDAL data dir: /home/ciprian/miniconda3/envs/test-env/share/gdal
PROJ       : 8.0.1
PROJ data dir: /home/ciprian/miniconda3/envs/test-env/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.2.4
fiona      : 1.8.20
numpy      : 1.20.3
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.1.0
matplotlib : 3.4.2
mapclassify: 2.4.2
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

**Comment by martinfleis** [comment]
I think this is some kind of an installation issue. I have created env based on your yaml (on intel macOS 11.4) and everything seems to work fine.

```py
>>> import geopandas as gpd
>>> df = gpd.read_file('inf.geojson')
>>> df
   release  ...                                           geometry
0        2  ...  POLYGON ((-93.17520 30.20277, -93.17503 30.202...
1        2  ...  POLYGON ((-93.17533 30.20468, -93.17517 30.204...
2        2  ...  POLYGON ((-93.17638 30.22263, -93.17613 30.222...

[3 rows x 3 columns]
>>> proj_df = df.to_crs(crs='+proj=lcc +lat_1=33 +lat_2=45 +lat_0=39 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs')
>>> proj_df
   release  ...                                           geometry
0        2  ...  POLYGON ((273611.808 -970145.398, 273628.269 -...
1        2  ...  POLYGON ((273592.606 -969933.092, 273607.614 -...
2        2  ...  POLYGON ((273428.072 -967935.764, 273452.563 -...

[3 rows x 3 columns]
```

Can you try using the following code, which does not depend on GeoPandas to do the transformation?

```py
from pyproj import CRS, Transformer
from shapely.ops import transform

origin = CRS.from_user_input(df.crs)
target = CRS.from_user_input('+proj=lcc +lat_1=33 +lat_2=45 +lat_0=39 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs')

transformer = Transformer.from_crs(origin, target, always_xy=True)

geom = df.geometry.iloc[0]  # shapely.geometry causing a problem

transform(transformer.transform, geom).wkt
```

If it returns inf, then it is clear that it is out of our hands but may get us closer to the issue. In any case, I believe that all this is caused by an installation issue of some sort, probably related to pyproj/PROJ.

**Comment by cipri-tom** [comment]
Thanks for trying it out !

Indeed, the code you suggest returns `inf`.

It seems it does this regardless of which geom we pass in. Digging deeper, it seems that only the first call to `transformer.transform()` returns `inf`. I will open an issue in pyproj.

**Comment by jonschwenk** [comment]
For others having a similar issue, I found that the old `.buffer(0)` trick seems to clear this up.
