### ISSUE TITLE
QST: how to force column types in PostGIS using GeoDataFrame.to_postgis 'dtype={}' ?

### ISSUE THREAD

**Issue by NMItools** [geopandas/geopandas#1978]
- [x] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

#### How to force column types in PostGIS using 'dtype={...}' with "GeoDataFrame.to_postgis"  ?

```python

    openrd = gpd.read_file(shp_file)
    openrd.to_postgis(table, 
                      conn, 
                      schema=db_schema,
                      if_exists='replace',
                      index=True,
                      index_label='gid',
                      chunksize=1000000,
                      dtype={"class":TEXT,
                             "form_of_way":TEXT,
                             "length":INTEGER,
                             "loop":TEXT,
                             "name1":TEXT,
                             "name2":TEXT,
                             "road_network":BIGINT,
                             "geom":Geometry(geometry_type='LINESTRING', spatial_index=True, srid=27700)
                             })
    print("Shapefile import done.")                             

```
Even if I used a type dictionary with column names and types, after uploading a shapefile in the PostGIS table, the names and types are still like in an original shapefile. 

![Screenshot 2021-06-26 21 21 17](https://user-images.githubusercontent.com/5813553/123523576-ada2e500-d6c4-11eb-9056-bbd6692394d1.png)

for example column names are not changed to lowercase with underscores and type for a column "length" is still DOUBLE PRECISION

**Comment by jorisvandenbossche** [comment]
@NMItools you can't use the `dtype` argument to change column names, only to specify the type to be used for a certain column. And because you used different names in that dictionary, I suppose that's also the reason it didn't change any of the types. 

If you want different names in the PostGIS table, you will first have to rename your dataframe's columns (`openrd = openrd.rename(columns={...})`), and then you can call `to_postgis` with the `dtypes` expressed as you have it above.

**Comment by NMItools** [comment]
@jorisvandenbossche  Thank you!!
