### ISSUE TITLE
Writing GeoDataFrame with NULL attribute creates "1.#QNAN" in shapefile

### ISSUE THREAD

**Issue by philip-riggs** [geopandas/geopandas#198]
When I write a GeoDataFrame to a shapefile using .to_file(filename), if there is a nan value in a text attribute field, the shapefile has "1.#QNAN" written. 

When I write the DataFrame out with Pandas, the nan values are corrected written as NULL. They are type float with other data in the field unicode string.

Is there a way for GeoPandas to write NULL string values to shapefiles?

**Comment by kjordahl** [comment]
@philip-riggs I agree that it should write out `NULL`. If you have a simple example to reproduce the issue, that would be helpful.

**Comment by jdmcbr** [comment]
@philip-riggs I'm going to close this for now. If you are still seeing this issue, and can post an example that shows what leads to this error, I'm happy to re-open.
