### ISSUE TITLE
TST: IO failures with GDAL 3.3.0 and GPKG

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#1980]
`38-no-optional-deps` CI environment is now coming with GDAL 3.3.0 and two failures.

```
test_file.py::test_to_file_bool[GPKG-gpkg] 
test_file.py::test_to_file_datetime
```

Both lose a CRS during a roundtrip through GPKG.

I will explore further to understand where is this coming from but I guess it will be fiona, not us.

**Comment by jorisvandenbossche** [comment]
See also https://github.com/geopandas/geopandas/issues/1975

**Comment by martinfleis** [comment]
Ah, missed that one. Closing as a duplicate then.
