### ISSUE TITLE
BUG: no attribute 'has_sindex' + sindex null

### ISSUE THREAD

**Issue by maifeeulasad** [geopandas/geopandas#1982]
- [x] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
print(type(gdf))
#<class 'geopandas.geodataframe.GeoDataFrame'>
print(gdf.has_sindex)
spatial_index = gdf.sindex
```

#### Problem description
*'GeoDataFrame' object has no attribute 'has_sindex'*
if I skip the `has_sindes` it gives me null on `sindex`

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 2.7.18 (default, Mar  8 2021, 13:02:45)  [GCC 9.3.0]
machine    : Linux-5.8.0-59-generic-x86_64-with-Ubuntu-20.04-focal
executable : /usr/bin/python2

GEOS, GDAL, PROJ INFO
---------------------
PROJ data dir: /usr/local/lib/python2.7/dist-packages/pyproj/proj_dir/share/proj
GEOS       : 3.8.0
PROJ       : 6.1.1
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL data dir: /usr/share/gdal
GDAL       : 3.0.4

PYTHON DEPENDENCIES
-------------------
pysal      : None
mapclassify: None
shapely    : 1.7.1
geopandas  : 0.6.3
rtree      : None
pyproj     : 2.2.2
matplotlib : 2.2.5
psycopg2   : None
fiona      : 1.8.20
geopy      : None
numpy      : 1.16.6
pandas     : 0.24.2
None

</details>

**Comment by martinfleis** [comment]
Thanks for the report. However, I am not sure what do you mean. The snippet above works in my case with and without `gdf.has_sindex`.

Can you try updating GeoPandas to 0.9.0? You are using a really old version in you environment.

**Comment by maifeeulasad** [comment]
My bad, my environment was Python2.x, that's why it was installing geopandas 0.6.3. After using Python 3.x as default, I'm now able to install and use geopandas 0.9.0. So the issue is resolved.

**Comment by maifeeulasad** [comment]
Just one question - Why this awesome library isn't backward compatible?

**Comment by martinfleis** [comment]
Python 2 is [no longer supported by Python developers](https://www.python.org/doc/sunset-python-2/) and its support would block further development of GeoPandas. The whole ecosystem is moving away from Python 2, I would suggest you do the same.
