### ISSUE TITLE
ENH: Define a custom-color-map and visualize

### ISSUE THREAD

**Issue by maifeeulasad** [geopandas/geopandas#2009]
#### Is your feature request related to a problem?

I wish geopandas would let me plot a custom color map directly, and do all the processing behind the hood

#### Describe the solution you'd like

I can use the plot API, from matplotlib actually, like this:
```
shape_file.plot(column='ITEM',cmap='etcetc')
```
This will plot an image with the specified color map, based on the column named 'ITEM', one specific color for the same class.
Now what if I want to define a minimal color mapping just, not a color map, like:
```
{
    'Isolated Structures':'gray',
    'Forests':'green',
    'Abandoned House':'green'
}
```

#### API breaking implications
```
shape_file.plot(...,ccmap={})
```
**`ccmap`** meaning custom cmap, and that will take a dictionary and do all the complex stuff under the hood.

#### Describe alternatives you've considered

The article, right here: https://www.earthdatascience.org/courses/scientists-guide-to-plotting-data-in-python/plot-spatial-data/customize-vector-plots/python-customize-map-legends-geopandas/

#### Additional context
Pasted the code below from above link: 

```python
roadPalette = {'M': 'blue',
               'S': 'green',
               'C': 'purple',
               'Unknown': 'grey'}

fig, ax = plt.subplots(figsize=(10, 10))
ax.set_axis_off()

for ctype, data in sjer_roads.groupby('RTTYP'):
    color = roadPalette[ctype]    
    data.plot(color=color,
              ax=ax,
              label=ctype,
            

ax.legend()
ax.set(title='Madera County \n Line width varies by TYPE Attribute Value')
plt.show()
```

**Comment by martinfleis** [comment]
Thanks for the suggestion! We're well aware of the sub-optimality of plotting options. This one has been actually already listed in #1269 (so I'll close this as a duplicate).

If you'd be willing to try to make a PR implementing this (probably based on the API outlined in #1269), that'd be really cool!
