### ISSUE TITLE
BUG in plotting py, call to cmap.set_array()

### ISSUE THREAD

**Issue by HansAschauer** [geopandas/geopandas#2011]
Recently, a geopandas script stopped working and crashed deep within matplotlib:

```
  File "/usr/lib64/python3.8/site-packages/matplotlib/figure.py", line 1173, in colorbar
    cb = cbar.Colorbar(cax, mappable, **cb_kw)

  File "/usr/lib64/python3.8/site-packages/matplotlib/colorbar.py", line 1172, in __init__
    mappable.autoscale_None()

  File "/usr/lib64/python3.8/site-packages/matplotlib/cm.py", line 476, in autoscale_None
    self.norm.autoscale_None(self._A)

  File "/usr/lib64/python3.8/site-packages/matplotlib/colors.py", line 1542, in autoscale_None
    super().autoscale_None(np.ma.array(A, mask=(A <= 0)))

TypeError: '<=' not supported between instances of 'list' and 'int'

```
I traced the problem back to a call within geopandas/plotting.py, line 906

```python
            else:
                legend_kwds.setdefault("ax", ax)

            n_cmap.set_array([])
            ax.get_figure().colorbar(n_cmap, **legend_kwds)

    plt.draw()
    return ax

```

Replacing the call `n_cmap.set_array([])` with `n_cmap.set_array(np.array([]))` solves the problem.

According to the matplotlib documentation, the argument to the `set_array()` method shall be a ndarray or None.

I run geopandas version 0.9 (installed via pip), matplotlib version 3.4.2 (from my distribution) and python 3.8.10.

**Comment by martinfleis** [comment]
Thanks for the report! Can you provide some reproducible example? I'd like to know when this happens so we can test it.

**Comment by brianckeegan** [comment]
I'm getting this error when using plot that calls the `norm` parameter in GeoPandas 0.9.0.

```
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm, SymLogNorm

# Load shapefile
nybb = gpd.read_file(gpd.datasets.get_path('nybb'))

# Setup figure
f,ax = plt.subplots(figsize=(15,10))

# Plot
nybb.plot(
    column='Shape_Area',
    cmap='bwr',
    edgecolor='k',
    lw=.5,
    legend=True,
    norm=LogNorm(1e6,1e10),
    ax=ax
)
```

Commenting out the `norm=LogNorm(1e6,1e10)` will generate the appropriate plot without error.

**Comment by brianckeegan** [comment]
Appears to be a MPL error, documented [here](https://github.com/matplotlib/matplotlib/issues/20902).
