### ISSUE TITLE
Point creation extremely slow

### ISSUE THREAD

**Issue by Jap8nted** [geopandas/geopandas#2041]
Hi all,

I am currently working on a building a pipeline which basically reads some .csv files containing lat, lon along with other features and discarding some of those based on a spatial join. The process is extremely slow, specifically the part of converting lat lon to points. It takes 10 minutes for 14 million points. 
``gdf = geopandas.GeoDataFrame(
    df, geometry=geopandas.points_from_xy(df.lon, df.lat))
``

My question is, can this be done faster? I used multiprocessing to spawn the process but it was not that better. So is there a Shapely issue or geopandas or is it just normal and I will need to change maybe to a other approach. Any ideas how can this be done faster?

**Comment by martinfleis** [comment]
Hi,

you have two options.

1) install `pygeos`. That will give you vectorized point creation compared to a for loop used with `shapely`. https://geopandas.readthedocs.io/en/latest/getting_started/install.html#using-the-optional-pygeos-dependency

2) If that is not fast enough, you can experiment with `dask-geopandas` which can do `points_from_xy` in parallel. Note that you should have `pygeos` as well as `dask_geopandas` in that case. https://github.com/geopandas/dask-geopandas

Let us know if that helped.

**Comment by Jap8nted** [comment]
Thanks @martinfleis. PyGeos does it already in 17 Seconds for the same dataframe.
