### ISSUE TITLE
BUG: converting crs from 4326  to 4978 and back to 4326 gives 0.0000 latitude

### ISSUE THREAD

**Issue by kerinb** [geopandas/geopandas#2044]
- [ X] I have checked that this issue has not already been reported.

- [ X] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
```
raw = pd.read_csv('testing geo DP .csv')
raw = gpd.GeoDataFrame(raw, geometry=gpd.points_from_xy(raw.longitude, raw.latitude))
raw = raw.set_crs("EPSG:4326")
raw = raw.to_crs("EPSG:4978")
raw = raw.to_crs("EPSG:4326")

raw

```

#### Problem description

I am currently trying to test out different geospatial differential privacy techniques. One approach I am trying to test is to convert the crs from 4326 to 4978, and add in some random Laplacian noise; as meters, then convert back to 4326. 

However, before I even get to add the noise, I checked the functionality of changing between these CRS's for my purposes, and it appears that regardless, the latitude of the output is always set to 0.0000 when I run the above code sample.  

#### Expected Output

This is the current output with the faulty conversion:
latitude | longitude | altitude | geometry
-- | -- | -- | --
1.316468 | 103.898017 | 58.145112 | POINT (103.89802 0.00000)
1.316468 | 103.898017 | 58.145112 | POINT (103.89802 0.00000)
1.316543 | 103.898261 | 57.400518 | POINT (103.89826 0.00000)
1.316784 | 103.898170 | 50.222063 | POINT (103.89817 0.00000)
1.316015 | 103.898366 | 54.092930 | POINT (103.89837 0.00000)

While, the following is the expected output:
latitude | longitude | altitude | geometry
-- | -- | -- | --
1.316468 | 103.898017 | 58.145112 | POINT (103.89802 1.31647)
1.316468 | 103.898017 | 58.145112 | POINT (103.89802 1.31647)
1.316543 | 103.898261 | 57.400518 | POINT (103.89826 1.31654)
1.316784 | 103.898170 | 50.222063 | POINT (103.89817 1.31678)
1.316015 | 103.898366 | 54.092930 | POINT (103.89837 1.31601)

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
executable : 
machine    : Windows-10-10.0.19041-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.2.1
GDAL data dir: None
PROJ       : 7.1.1
PROJ data dir: 

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.1.3
fiona      : 1.8.18
numpy      : 1.20.3
shapely    : 1.7.1
rtree      : 0.9.3
pyproj     : 2.6.1.post1
matplotlib : 3.3.2
mapclassify: None
geopy      : 1.21.0
psycopg2   : 2.8.6 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : None
pygeos     : 0.8
</details>

**Comment by martinfleis** [comment]
Thank you for the report!

I can confirm that this roundtrip fails even on geopandas master, pyproj 3.1.0 and proj 8.0.0. 

It is probably an upstream issue with pyproj/PROJ. cc @snowman2

**Comment by snowman2** [comment]
Works fine with pyproj 3.1.0 with PROJ 8.1:
```python
>>> from pyproj import Transformer
>>> tr = Transformer.from_crs(4326, 4978, always_xy=True)
>>> tr
<Concatenated Operation Transformer: pipeline>
Description: axis order change (2D) + Conversion from WGS 84 (geog2D) to WGS 84 (geocentric)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
>>> tr.transform(103.898017, 1.316468, 58.145112)
(-1531605.377504483, 6189848.855982023, 145556.28089554436)
>>> tr.transform(*tr.transform(103.898017, 1.316468, 58.145112), direction="INVERSE")
(103.898017, 1.3164680000000002, 58.14511200040579)
```
and PROJ 8.1:
```bash
echo 1.316468 103.898017 58.145112 | cs2cs 'EPSG:4326' 'EPSG:4978' | cs2cs -d 8 'EPSG:4978' 'EPSG:4326'
1.31646799	103.89801701 58.14959000
```

**Comment by martinfleis** [comment]
@snowman2 thanks!

@kerinb can you try to update to the latest PROJ 8.1.0 and let us know if the issue persists on your side?

**Comment by kerinb** [comment]
Hey, @snowman2  & @martinfleis that seems to have solved the issue! Thank you :)
