### ISSUE TITLE
BUG: GeoSeries.to_frame when name is not 'geometry' doesn't set geometry column

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#2063]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
In [2]: import geopandas

In [3]:  df = geopandas.read_file(geopandas.datasets.get_path("naturalearth_cities"))

In [4]: srs = df['geometry']

In [5]: type(srs)
Out[5]: geopandas.geoseries.GeoSeries

In [6]: srs.name = 'foo'

In [7]: srs.to_frame().geometry
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-ee808c91f778> in <module>
----> 1 srs.to_frame().geometry

C:\MyPrograms\Miniconda3\envs\gpd_latest_conda_forge\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   5476         ):
   5477             return self[name]
-> 5478         return object.__getattribute__(self, name)
   5479
   5480     def __setattr__(self, name: str, value) -> None:

c:\data\mydocuments\code\geopandas_test\geopandas-m-richards\geopandas\geodataframe.py in _get_geometry(self)
    196     def _get_geometry(self):
    197         if self._geometry_column_name not in self:
--> 198             raise AttributeError(
    199                 "No geometry data set yet (expected in"
    200                 " column '%s'.)" % self._geometry_column_name

AttributeError: No geometry data set yet (expected in column 'geometry'.)

In [8]: srs.name = 'geometry'

In [9]: srs.to_frame().geometry
Out[9]:
0        POINT (12.45339 41.90328)
1        POINT (12.44177 43.93610)
2         POINT (9.51667 47.13372)
3         POINT (6.13000 49.61166)
4        POINT (158.14997 6.91664)
                  ...
197      POINT (31.24802 30.05191)
198     POINT (139.74946 35.68696)
199       POINT (2.33139 48.86864)
200    POINT (-70.66899 -33.44807)
201      POINT (103.85387 1.29498)
Name: geometry, Length: 202, dtype: geometry
```

#### Problem description
`GeoSeries.to_frame()` should produce valid geometry, regardless of whether the series name is geometry.

#### Expected Output
As in [9]. (Edit: also `srs.to_frame().crs` should be preserved and not None)

I also think that if `GeoSeries.name = None` it might make more sense to produce a GeoDataFrame with a single column "geometry" rather than '0' that is default. 

Yet to look into properly, but I think this probably could be fixed by expanding `GeoSeries._constructor_expanddim`, similar to some of the other stuff I've been looking at.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
executable : C:\MyPrograms\Miniconda3\envs\gpd_latest_conda_forge\python.exe
machine    : Windows-10-10.0.19043-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.3.1
GDAL data dir: None
PROJ       : 8.0.1
PROJ data dir: C:\MyPrograms\Miniconda3\envs\gpd_latest_conda_forge\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0+59.g4536b92
pandas     : 1.3.1
fiona      : 1.8.20
numpy      : 1.21.1
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.1.0
matplotlib : 3.4.2
mapclassify: 2.4.3
geopy      : 2.2.0
psycopg2   : 2.9.1 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 5.0.0
pygeos     : 0.10.1

</details>

**Comment by eemilhaa** [comment]
Was able to reproduce this.

**geopandas.show_versions()** output:

```
SYSTEM INFO
-----------
python     : 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48)  [GCC 9.3.0]
executable : /home/eemil/miniconda3/envs/minimal/bin/python
machine    : Linux-5.11.0-7620-generic-x86_64-with-glibc2.33

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /home/eemil/miniconda3/envs/minimal/lib/libgeos_c.so
GDAL       : 3.3.1
GDAL data dir: /home/eemil/miniconda3/envs/minimal/share/gdal
PROJ       : 8.0.1
PROJ data dir: /home/eemil/miniconda3/envs/minimal/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.3.2
fiona      : 1.8.20
numpy      : 1.21.2
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.1.0
matplotlib : 3.4.3
mapclassify: 2.4.3
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None
```
