### ISSUE TITLE
Inconsistency with pandas in plotting kwarg names

### ISSUE THREAD

**Issue by maxalbert** [geopandas/geopandas#208]
Some of the kwargs in plotting functions use a different naming convention than pandas itself. For example, `plot_series()` and `plot_dataframe()` accept the keyword arguments `axes` and `colormap` instead of `ax` and `cmap`. I kind of like the long names because it makes things more explicit, but it also keeps tripping me up because I'm used to the pandas names (and I could imagine that other people feel the same).

It's perfectly ok if that's a design decision, but one could also argue that it would be good to keep things as consistent with pandas as possible. I just wanted to raise this, hence this issue. Feel free to close it if this choice is deliberate (but at least then it's documented somewhere that it's intentional).

If you're ok with changing the names so that they are the same as in pandas I'm happy to submit a PR.

**Comment by jorisvandenbossche** [comment]
+1 for renaming `axes` to `ax` (this is also what seaborn uses)

for `colormap`, I also think `cmap` is the name that matplotlib itself uses, so maybe that is also better (although I have to agree that I find the longer `colormap` clearer as well)

**Comment by kjordahl** [comment]
Agreed, we should change to `ax`.

**Comment by darribas** [comment]
Just issued PR

**Comment by darribas** [comment]
Just issued PR #228 replacing `axes` for `ax` and `colormap` for `cmap`. After accordingly modifying the tests for plotting, everything passes locally.

**Comment by IamJeffG** [comment]
While I am a fan of this change (I had tried 'cmap' first, and it didn't work before your patch), how do you all feel about leaving in backward-compat for the old "colormap" argument name for a version or two?

**Comment by kjordahl** [comment]
@IamJeffG briefly discussed on #228, but not written in stone. If we come up with a backwards-compatible patch that isn't too intrusive, we could use that. As I said there though, I slightly lean towards just breaking this relatively minor part of the API and moving forward.

At some point we should have a release (1.0?) that has stronger forward-compatible guarantees.

**Comment by jorisvandenbossche** [comment]
@kjordahl I put up a PR as an example of how this backwards compatibiltiy could look like:  #240

I personally think this is not very intrusive

**Comment by kjordahl** [comment]
Thanks, now we have consistency with pandas and backward compatibility. Closing this as done.
