### ISSUE TITLE
BUG: Why does a remote polygon with no touching edge get affected by difference?

### ISSUE THREAD

**Issue by andhuang-CLGX** [geopandas/geopandas#2081]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.
---

A polygon's coordinates located on the top right gets affected by a difference operation on the bottom left. I expect that the upper right polygon shouldn't be affected.

```
import pandas as pd
import geopandas as gpd

df = pd.DataFrame({"coords": [
    'POLYGON ((-100.5378104 45.175, -100.54 45.1712889, -100.5439257 45.175, -100.545 45.1776854, -100.5453305 45.18, -100.545 45.1803472, -100.5427045 45.18, -100.54 45.1789127, -100.5378104 45.175))',
    'POLYGON ((-101.9053297 44.3, -101.91 44.2978065, -101.9114672 44.3, -101.91 44.3012996, -101.9053297 44.3))',
    'POLYGON ((-101.9034962 44.295, -101.905 44.2944638, -101.91 44.2940891, -101.9126333 44.295, -101.915 44.2982986, -101.9158031 44.3, -101.915 44.3038377, -101.9132229 44.305, -101.91 44.3052182, -101.9090659 44.305, -101.905 44.3029345, -101.9001957 44.3, -101.9034962 44.295))'
]})
gdf = gpd.GeoSeries.from_wkt(df["coords"], name="geometry").to_frame()
gdf["value"] = ["a", "b", "a"]

gdf.plot()

diff = gdf.loc[gdf["value"] == "a"].difference(gdf.loc[gdf["value"] == "b"].unary_union)

print(gdf.iloc[0]["geometry"])
print(diff.iloc[0])
```

The coordinates change a bit; is this expected?
```
# original
POLYGON ((-100.5378104 45.175, -100.54 45.1712889, -100.5439257 45.175, -100.545 45.1776854, -100.5453305 45.18, -100.545 45.1803472, -100.5427045 45.18, -100.54 45.1789127, -100.5378104 45.175))

# difference
POLYGON ((-100.54 45.1712889, -100.5439257 45.175, -100.545 45.1776854, -100.5453305 45.18, -100.545 45.1803472, -100.5427045 45.18, -100.54 45.1789127, -100.5378104 45.175, -100.54 45.1712889))
```

![image](https://user-images.githubusercontent.com/83971150/130477445-592e828c-52d2-4d5b-960a-219fb1d28a7f.png)

**Comment by andhuang-CLGX** [comment]
I tried with / without pygeos too

**Comment by martinfleis** [comment]
Using `difference` in this way, we actually send both geometries to GEOS to do the `difference` overlay operation. This is what comes back. I am not sure there's much we can do about it but I'd leave this to others closer to GEOS (cc @jorisvandenbossche @brendan-ward).

One workaround would be to use the spatial index to filter geometries that need to be sent to GEOS for `difference` and don't touch those that do not. We could/should maybe do that under the hood anyway once we fully depend on shapely2.0 (with shapely1.7 and rtree, that would be expensive).

**Comment by andhuang-CLGX** [comment]
Can you elaborate on how I can use spatial index to filter geometries? For this test data, it might be easy to separate but I'm afraid with 1000s, it's hard to group them.

**Comment by martinfleis** [comment]
Sure.

Something along these lines. `gdf.sindex.query(geom, predicate="intersects")` returns integer indices of geometries that intersect your target geometry (see the [docs](https://geopandas.readthedocs.io/en/latest/docs/reference/api/geopandas.sindex.SpatialIndex.query.html#geopandas.sindex.SpatialIndex.query)). For larger combinations, you may also want to look at [`sindex.query_bulk`](https://geopandas.readthedocs.io/en/latest/docs/reference/api/geopandas.sindex.SpatialIndex.query_bulk.html).

```py
sel = gdf.loc[gdf["value"] == "a"]
geom = gdf.loc[gdf["value"] == "b"].unary_union

hits = sel.sindex.query(geom, predicate="intersects")
diff = sel.iloc[hits].difference(geom)
```

**Comment by brendan-ward** [comment]
The original and difference geometries are equal but start from a different vertex, and are completely equal once each has been normalized (start from consistent vertex).  It is not unexpected that GEOS returns a geometry starting from a different vertex from an operation like `difference`.

```
>>> import pygeos as pg
>>> original = pg.Geometry('POLYGON ((-100.5378104 45.175, -100.54 45.1712889, -100.5439257 45.175, -100.545 45.1776854, -100.5453305 45.18, -100.545 45.1803472, -100.5427045 45.18, -100.54 45.1789127, -100.5378104 45.175))')
>>> difference = pg.Geometry('POLYGON ((-100.54 45.1712889, -100.5439257 45.175, -100.545 45.1776854, -100.5453305 45.18, -100.545 45.1803472, -100.5427045 45.18, -100.54 45.1789127, -100.5378104 45.175, -100.54 45.1712889))')
>>> pg.equals(original, difference)
True
>>> pg.equals_exact(original, difference)
False
>>> pg.equals_exact(pg.normalize(original), pg.normalize(difference))
True
```

However, the best approach is as @martinfleis suggests - first use a spatial index and only calculate the difference for those geometries that intersect; those that don't intersect can be copied directly from the input (left side of `difference` operation).  This will also be much better for performance, since difference can be an expensive spatial operation for many or complex geometries.

**Comment by andhuang-CLGX** [comment]
Wow, thank you for the explanation! I think this issue can be closed then, or this issue can be redirected to: "We could/should maybe do that under the hood anyway once we fully depend on shapely2.0 (with shapely1.7 and rtree, that would be expensive)."

**Comment by martinfleis** [comment]
Thanks @brendan-ward!
