### ISSUE TITLE
QST: the precision of the coordinates of centroid points is imprecise after a buffer. 

### ISSUE THREAD

**Issue by tikitong** [geopandas/geopandas#2093]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example:

```python
from shapely.ops import transform
import geopandas as gpd
import shapely.wkt
import pyproj
from math import sqrt

def edge_size(area): return sqrt(area)*1e3

point = "POINT (4379065.583907348 2872272.254645019)"
point = shapely.wkt.loads(point)

center = gpd.GeoSeries(point)

project = pyproj.Transformer.from_proj(
    pyproj.Proj('epsg:3395'), 
    pyproj.Proj('epsg:4326'),
    always_xy=True) 

center = center.apply(lambda p: transform(project.transform, p))

print(center.iloc[0])

square = point.buffer(
    edge_size(3), cap_style=3) #distance of 3km2

square = gpd.GeoSeries(square)
square = square.apply(lambda p: transform(project.transform, p))
square = square.apply(lambda p: p.centroid)

print(square.iloc[0])

#POINT (39.33781544185747 25.11929860805248)
#POINT (39.33781544185747 25.11929777802279)
```

#### Problem description

This is a problem I had already observed in other versions of my work. When generating polygons by [buffer](https://shapely.readthedocs.io/en/stable/manual.html#object.buffer) (here squares), the geometry points used for the generation have different coordinates than the one taken by the centroid method on the polygon after their generation. 

This is a **very annoying** problem because the points are then strictly different, which leads to imperfections in the following treatments. 

#### Expected Output

Points with strictly identical coordinates. 

How to overcome this problem?
Thank you very much for your attention.

**Comment by martinfleis** [comment]
This is not a bug but a misunderstanding of coordinate transformation. You have to keep in mind that what is square in one projection is not square in another. 

If you stick to the same CRS, the output of the centroid of a buffer equals the initial point. But the centroid of a reprojected polygon is slightly off, specifically because you did reprojection that skewed the geometry in one direction.

> How to overcome this problem?

Do all your operations in one CRS and reproject once you are done.

**Comment by tikitong** [comment]
Thank you very much @martinfleis for the explanation.
