### ISSUE TITLE
TST: slow hexbin plot comparison with pandas

### ISSUE THREAD

**Issue by TLouf** [geopandas/geopandas#2094]
While working on #2012 I noticed that  `test_plotting.py::TestGeoplotAccessor::test_pandas_kind[pdf-hexbin]` was the slowest of all tests by far (more than 7 seconds on my machine vs less than a second for all others).

This is simply due to the fact that the two populated bins are very far apart from each other relatively to the gridsize, so the plot features a hexgrid with many cells which, in a vector format like pdf, is heavy.

Thus, he duration of this test can be greatly reduced simply by setting something like `gridsize=10`. I can open a PR to do so if that's ok.

**Comment by martinfleis** [comment]
@TLouf Nice catch. 

>I can open a PR to do so if that's ok.

Go for it.
