### ISSUE TITLE
BUG: geopandas.to_crs() seems to misbehave with xarray.rio.crs

### ISSUE THREAD

**Issue by dimzog** [geopandas/geopandas#2104]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---
#### Code Sample, a copy-pastable example

```python
import xarray as xr
import geopandas as gpd

# Open files
data = xr.open_dataset(path/to/file.nc)
gdf = gpd.read_feather(path/to/feather)

# Reproject
gdf.to_crs(crs=data.rio.crs, inplace=True)

```

#### Problem description

Using xarray.rio.crs to reproject a GeoDataFrame throws an Exception, namely 'Warning 1: +init=epsg:XXXX syntax is deprecated. It might return a CRS with a non-EPSG compliant axis order.'.

#### Expected Output
Exception should not be thrown. This might be a underlying Proj issue.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
executable : /usr/bin/python3
machine    : Linux-5.8.0-7642-generic-x86_64-with-glibc2.29

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.0
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 2.4.4
GDAL data dir: /home/dimzog/.local/lib/python3.8/site-packages/fiona/gdal_data
PROJ       : 7.0.1
PROJ data dir: /home/dimzog/.local/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.3.0
fiona      : 1.8.18
numpy      : 1.21.0
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 2.6.1.post1
matplotlib : 3.4.3
mapclassify: None
geopy      : None
psycopg2   : 2.8.4 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 5.0.0
pygeos     : None

</details>

**Comment by martinfleis** [comment]
Hi @dimzog,

thank you for the report! 

I am not able to reproduce the issue. Can you tell me your version of `xarray`, and `rasterio`?  With rasterio '1.2.6', xarray 0.19.0 and pyproj '3.1.0' I see no warning or exception. 

Also, note that your version of pyproj is not up to date. Updating to the latest versions may resolve your issue.

**Comment by dimzog** [comment]
@martinfleis hey,

<details><summary>Output of <tt>xr.show_versions()</tt></summary>

<INSTALLED VERSIONS
------------------
commit: None
python: 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0]
python-bits: 64
OS: Linux
OS-release: 5.8.0-7642-generic
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.12.0
libnetcdf: 4.7.4

xarray: 0.19.0
pandas: 1.3.0
numpy: 1.21.0
scipy: 1.6.1
netCDF4: 1.5.7
pydap: None
h5netcdf: 0.7.1
h5py: 3.1.0
Nio: None
zarr: 2.4.0+ds
cftime: 1.4.1
nc_time_axis: None
PseudoNetCDF: None
rasterio: 1.2.7
cfgrib: None
iris: None
bottleneck: 1.2.1
dask: 2021.03.0
distributed: 2021.03.0
matplotlib: 3.3.4
cartopy: None
seaborn: 0.11.1
numbagg: None
pint: 0.16.1
setuptools: 45.2.0
pip: 21.2.4
conda: None
pytest: 4.6.9
IPython: 7.21.0
sphinx: None
</details>

I installed proj binaries using `sudo apt-get install proj-bin`, there were missing for some reason. Τhen updated both pyproj to 3.2.0 and certifi to certifi-2021.5.30. 

I also updated GDAL version using 
`pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"`

The issue persists.

<details>

SYSTEM INFO
-----------
python     : 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
executable : /usr/bin/python3
machine    : Linux-5.8.0-7642-generic-x86_64-with-glibc2.29

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.0
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.3.0
GDAL data dir: /home/dimzog/.local/lib/python3.8/site-packages/fiona/gdal_data
PROJ       : 8.1.1
PROJ data dir: /home/dimzog/.local/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.3.0
fiona      : 1.8.20
numpy      : 1.21.0
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.2.0
matplotlib : 3.4.3
mapclassify: None
geopy      : 2.2.0
psycopg2   : 2.8.4 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 5.0.0
pygeos     : None

</details>

**Comment by martinfleis** [comment]
Can you try the following snippets and check whether the warning is emitted?

```py
import rasterio
import geopandas

gdf = geopandas.read_file(geopandas.datasets.get_path("naturalearth_lowres"))
gdf.to_crs(rasterio.crs.CRS.from_epsg(32631))
```

and 

```py
import pyproj
import rasterio

pyproj.CRS.from_user_input(rasterio.crs.CRS.from_epsg(32631))
```

**Comment by dimzog** [comment]
@martinfleis no issues in your code, i am also not able to reproduce my own bug in a notebook. This seems to happen only while in terminal. 
Also, i think that the issue might come from  `data.rio.crs` and not `to_crs()`.

**Comment by martinfleis** [comment]
> Also, i think that the issue might come from `data.rio.crs` and not `to_crs()`.

Yeah, it may be coming from that. rioxarray attempts to get CRS from DataArray attrs and if that is stored in the deprecated form it may cause this warning. The issue may in the end be in the data.

Since the snippets above are fine, I don't think this is an issue on our side.

**Comment by dimzog** [comment]
Yes, thanks @martinfleis closing this.
