### ISSUE TITLE
ENH: Allow `hex` kwarg in GeoSeries.from_wkb

### ISSUE THREAD

**Issue by snowman2** [geopandas/geopandas#2105]
#### Is your feature request related to a problem?

With `GeoSeries.from_wkb` in shapely mode I get this error with a hex encoded geometry:
```
~/.../lib/python3.8/site-packages/shapely/geos.py in read(self, data)
    426         """Returns geometry from WKB"""
    427         geom = self._lgeos.GEOSWKBReader_read(
--> 428             self._reader, c_char_p(data), c_size_t(len(data)))
    429         if not geom:
    430             raise WKBReadingError(

TypeError: bytes or integer address expected instead of str instance
```
This is due to the fact that the `hex=True` kwargs is needed. This is not necessary for the `pygeos` engine.

It works with:
```
pdf.geometry.apply(lambda geom: shapely.wkb.loads(geom, hex=True))
```

#### Describe the solution you'd like

```python
GeoSeries.from_wkb(pdf.geometry, hex=True)
```

#### API breaking implications

It will add the `hex` kwarg.

**Comment by snowman2** [comment]
I guess an alternative could be to handle automatically. Something like:
```python
if isinstance(geom, str):
    hex = True
```

**Comment by martinfleis** [comment]
pygeos doesn't mind if it is hex or not? If so I'd try to automatically resolve it under the hood in `from_wkb` here https://github.com/geopandas/geopandas/blob/187287b2fac8216bcc56ba6d5c5074ff6ce6dd3d/geopandas/_vectorized.py#L159

PR is welcome (as always :))!

**Comment by snowman2** [comment]
How about #2106?
