### ISSUE TITLE
REGR: regression in explode's MultiIndex creation when using pygeos

### ISSUE THREAD

**Issue by TLouf** [geopandas/geopandas#2109]
#1945 introduced a slight performance regression in `GeoSeries.explode()` when using `pygeos`, as the new series' MultiIndex is created using `from_tuples` instead of `from_arrays`. The former calling the latter, it's necessarily less performant, particularly here since the needed arrays are computed, then converted to a list of tuples using a list comprehension, only to be passed to `from_tuples` and converted back to arrays.

The list of arrays is simply the output of  `get_level_values` for each level of the original index plus the new `inner_index`, which is computed in `explode`. So the fix to go back to using `from_arrays` is rather straightforward I think.

Shall I open a PR for this?

**Comment by martinfleis** [comment]
> Shall I open a PR for this?

Yes please :)
