### ISSUE TITLE
Feature Request: support saving list properties when driver="Geojson" is used

### ISSUE THREAD

**Issue by rbavery** [geopandas/geopandas#2113]
#### Is your feature request related to a problem?
When saving geojsons it'd be nice if saving properties with lists was supported. I'd like to track lists of bounding box coordinates for each feature in a geojson. The geojson features represent labels for a machine learning model and it would be useful to track the bounding boxes of images next to the features representing labels. This is brought up in https://github.com/Toblerity/Fiona/issues/738, and I recognize it won't work for shapefiles, but it seems like this could work for geojsons.

An example feature with a list property is below:

```
{"geometry": {"coordinates": [[[2.366512, 13.273837], [2.366968, 13.273839], [2.366967, 13.274152], [2.366511, 13.274151], [2.366512, 13.273837]]], "type": "Polygon"}, "properties": {"_type": "rural", "country": "niger","stile": "132794-121318-18-st.png", "tiles_bbox": [2.36480712890625, 13.27202630119995, 2.3675537109375, 13.274699510266418], "tiles_list": ["132794-121318-18", "132794-121319-18", "132795-121318-18", "132795-121319-18"]}, "type": "Feature"}],
```

#### Describe the solution you'd like

"`GeoDataFrame.to_file(driver="Geojson")` could support saving properties with lists

#### Describe alternatives you've considered
I'm using the geojson library to read in the geojsons and create dataframes from scratch so that I can work with existing geodataframes.

**Comment by rbavery** [comment]
It'd also be great if these list properties could be read into geopandas, in addition to being savewd with `to_file`.

**Comment by jorisvandenbossche** [comment]
@rbavery I agree it would be nice to support list-like values for those file formats that support it. However, for `read_file` / `to_file`, geopandas does not do the reading/writing itself, but uses an external library for this. So you still end up with this being a feature request for fiona (you can maybe comment on the issue you linked to with your use case, to see if the Fiona maintainers might want to reconsider the "wontfix"). 

Also the future alternative library for reading/writing with GDAL, pyogrio, doesn't yet seem to support list-like values. It could also be opened as a feature request there (https://github.com/geopandas/pyogrio/)

Now, specifically for GeoJSON, there are actually alternatives for `read_file`/`to_file`, since we also generate / convert GeoJSON-like dicts in `__geointerface__` and `GeoDataFrame.from_features()`:

```python
In [12]: gdf = geopandas.GeoDataFrame({'value': [1, 2], 'bbox': [[1, 2, 3, 4], [5, 6, 7, 8]]}, geometry=geopandas.points_from_xy([1, 2], [1, 2]))

In [13]: gdf.__geo_interface__
Out[13]: 
{'type': 'FeatureCollection',
 'features': [{'id': '0',
   'type': 'Feature',
   'properties': {'bbox': [1, 2, 3, 4], 'value': 1},
   'geometry': {'type': 'Point', 'coordinates': (1.0, 1.0)},
   'bbox': (1.0, 1.0, 1.0, 1.0)},
  {'id': '1',
   'type': 'Feature',
   'properties': {'bbox': [5, 6, 7, 8], 'value': 2},
   'geometry': {'type': 'Point', 'coordinates': (2.0, 2.0)},
   'bbox': (2.0, 2.0, 2.0, 2.0)}],
 'bbox': (1.0, 1.0, 2.0, 2.0)}

In [14]: gdf.to_json()
Out[14]: '{"type": "FeatureCollection", "features": [{"id": "0", "type": "Feature", "properties": {"bbox": [1, 2, 3, 4], "value": 1}, "geometry": {"type": "Point", "coordinates": [1.0, 1.0]}}, {"id": "1", "type": "Feature", "properties": {"bbox": [5, 6, 7, 8], "value": 2}, "geometry": {"type": "Point", "coordinates": [2.0, 2.0]}}]}'

In [19]: import json

In [23]: with open("test_list.geojson", "w") as f:
    ...:     json.dump(gdf.__geo_interface__, f)   # or f.write(gdf.to_json())

In [24]: with open("test_list.geojson", "r") as f:
    ...:     features = json.load(f)
    ...:     gdf2 = geopandas.GeoDataFrame.from_features(features)

In [25]: gdf2
Out[25]: 
                  geometry          bbox  value
0  POINT (1.00000 1.00000)  [1, 2, 3, 4]      1
1  POINT (2.00000 2.00000)  [5, 6, 7, 8]      2
```

(the `GeoDataFrame.to_json()` could be improved to also take a file path, instead of always returning the result as a string)

**Comment by rbavery** [comment]
Thanks for opening that issue in pyogrio @jorisvandenbossche and thanks for pointing out `__geointerface__`, I'd forgotten about it. I'll link this issue in the fiona repo.

**Comment by robertschweizer** [comment]
In geopandas 1.0.1, `GeoDataFrame.to_file()` writes out list and dict properties fine. It uses the "pyogrio" backend by default now.

**Comment by Bea07** [comment]
i still got the error an my geopandas version is 1.1.1. 
when i save the geodataframe it works fine, but opening as gpd.read_file() is not finding the column with list values.
"Skipping field xxxx: unsupported OGR type: 5"

**Comment by theroggy** [comment]
> i still got the error an my geopandas version is 1.1.1. when i save the geodataframe it works fine, but opening as gpd.read_file() is not finding the column with list values. "Skipping field xxxx: unsupported OGR type: 5"

@Bea07 can you try adding `use_arrow=True` as parameter in `read_file` when reading a file with a list column?
