### ISSUE TITLE
PERF: avoid calculating total_bounds in spatial join

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#2116]
Context: one of the issues from https://github.com/geopandas/dask-geopandas/issues/114

In the `sjoin` code, we currently calculate the total bounds to "shortcut" the sjoin in case there is no overlap:

https://github.com/geopandas/geopandas/blob/9e0770b470d02b8db2887e6fd22076be03b934e4/geopandas/tools/sjoin.py#L120-L138

However, calculating the total bounds can be expensive, while when using pygeos, the STRtree query_bulk can actually be very fast, and once the tree is built, querying the tree is a faster way to check that there is no overlap at all, compared to manually checking this by comparing total_bounds.

Using two partitions from the benchmark case of https://github.com/geopandas/dask-geopandas/issues/114 (~90k points, ~900 polygons) where there is no overlap in the bounding boxes, I get the following timings:

![image](https://user-images.githubusercontent.com/1020496/133881614-338966b8-e43e-4a0d-bc37-8ac55ef97cdb.png)

(`l_idx` and `r_idx` are emtpy arrays as result, since there is no overlap)

So when the spatial index was not yet created before, skipping the total bounds but relying on the tree to check for overlap would give a 3x slowdown (for this part of the sjoin algo). But if the spatial index was already created before, removing the total bounds check would actually be much faster.

In this specific case, the complete `geopandas.sjoin` call took ~30ms (so 10ms from the total bounds check, and 20ms for doing the empty merge + general overhead).

Some considerations / things we can do:

- Low hanging fruit: we should certainly first check `has_sindex` before doing the total_bounds check
- More in general, I wondering how important this "short cut" is, given that creating the tree is not that much slower as calculating the total bounds.
- Especially for dask-geopandas with spatial partitioning information (where we might already have checked the total bounds before hand to determine which partitions need to be combined in a `sjoin` call), it would be useful to have the option to disable the total_bounds check (since it only adds compute time, in a case we know it will most of the time not be needed, as there will be overlap in most cases)

<details>
<summary>Code</summary>

```python
left = ...  # points
right = ...  # polygons

%%timeit
geopandas.sjoin(left, right, op="within", how="inner")

%%timeit
right.total_bounds
left.total_bounds

%%timeit 
left.geometry.array._sindex = None
sindex = left.sindex
input_geoms = right.geometry
l_idx, r_idx = sindex.query_bulk(input_geoms, predicate="contains", sort=False)

%%timeit
sindex = left.sindex
input_geoms = right.geometry
l_idx, r_idx = sindex.query_bulk(input_geoms, predicate="contains", sort=False)
```

</details>

**Comment by martinfleis** [comment]
> More in general, I wondering how important this "short cut" is, given that creating the tree is not that much slower as calculating the total bounds.

Remember that at this moment, `pygeos` is still optional in geopandas. Have you tried the same without it, using shapely1.7 and rtree only?

**Comment by jorisvandenbossche** [comment]
Good question, rerunning the above with `geopandas.options.use_pygeos = False`:

![image](https://user-images.githubusercontent.com/1020496/133965899-46730265-ffef-4c77-adda-1456a9111be1.png)

So in absolute terms, the difference is of course bigger since everything is slower, but relatively it's actually a similar slowdown (for this specific case of course). 
But at least the "don't check bounds if sindex is already built" certainly is valid here as well.
