### ISSUE TITLE
Quick doc fix: update to_postgis example with latest syntax

### ISSUE THREAD

**Issue by openSourcerer9000** [geopandas/geopandas#2128]
Hoping to save someone else a google search, the error passed through from sqlalchemy is really cryptic:
[https://stackoverflow.com/a/64698899/13030053](https://stackoverflow.com/a/64698899/13030053)

`To fix this, rename postgres:// in the URL to postgresql://.`

[https://geopandas.org/docs/reference/api/geopandas.GeoDataFrame.to_postgis.html](https://geopandas.org/docs/reference/api/geopandas.GeoDataFrame.to_postgis.html)

Thank you!

**Comment by akrherz** [comment]
see #2079, fixed in the next release.
