### ISSUE TITLE
API: How to handle empty GeoDataFrame()

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#2130]
After https://github.com/geopandas/geopandas/pull/2060, we will start to return a DataFrame from methods if the geometry column gets lost. 
As a consequence (without extra effort to avoid that), this also means that such methods on an empty GeoDataFrame will no longer return a GeoDataFrame:

```
>>> df = geopandas.GeoDataFrame()
>>> type(df)
Out[7]: geopandas.geodataframe.GeoDataFrame
>>> type(df.copy())
pandas.core.frame.DataFrame
```

On master, before https://github.com/geopandas/geopandas/pull/2060 is merged, the last line also gives a GeoDataFrame.

There are some tests that rely on this way of creating an emtpy GeoDataFrame, and fail with this change (eg `df.to_file(..)` because inside `to_file` we first do a `reset_index` which now converts it to a DataFrame). 
In the PR, this was solved by doing `GeoDataFrame(geometry=[])` or `GeoDataFrame(columns=["geometry"]`), which still results in an "emtpy" dataframe (no data), but with 1 column.

One option is to decide that we are fine with this (it makes it consistent: no geometry column, then no GeoDataFrame). 
Another option is to add some special casing for this. It might be nice that eg the `df.copy()` preserves an empty GeoDataFrame.

See also https://github.com/geopandas/geopandas/pull/2060#issuecomment-898858475

cc @m-richards

**Comment by jorisvandenbossche** [comment]
cc @m-richards

**Comment by martinfleis** [comment]
I would be up for a special case here trying to preserve empty GeoDataFrame as a GeoDataFrame.

**Comment by m-richards** [comment]
As I said in 2060 when this was raised, I think that for users - ending up with empty geodataframes like this is unlikely  (as far as I'm aware) as selections based on some filter will retain information about columns, e.g. 
```python
In [10]: cities = geopandas.read_file(geopandas.datasets.get_path("naturalearth_cities"))

In [11]: cities[cities['name']=='foo']
Out[11]:
Empty GeoDataFrame
Columns: [name, geometry]
Index: []

In [12]: cities.geometry.name
Out[12]: 'geometry'
```
The fix in the PR mimics this, by retaining columns.

But at the same time, it does feel off, that you can construct an object "legally", and have its type change with no warning. It's also not the same has GeoSeries is handled, `GeoSeries([1,2,3])` produces a FutureWarning, and eventually will raise.

I'm wondering now if this opinion contradicts any of the changes I made in 2060? In my mind the difference is the intent, slicing, indexing, apply, drop are all potentially destructive operations where information can be lost, whereas `__init__` should be purer? Not sure if that makes sense.

**Comment by jorisvandenbossche** [comment]
A related question that might indirectly answer this issue: assume that long term we change GeoDataFrame to error if there is no geometry input (like we are doing for GeoSeries, which already raises a TypeError; although this is of course simpler as it's a single dtyped container). In such a case, would we still want to allow `GeoDataFrame()` ? 
So if there are *some* columns, there certainly needs to be a column with geometry dtype, but what if there are no columns at all? Do we special case this to still allow creating truly empty GeoDataFrame? Or raise an error for this?

**Comment by jorisvandenbossche** [comment]
_If_ we would like to handle empty GeoDataFrames, thinking about a possible way to do this: currently we set the `_geometry_column_name` to `"geometry"` even if there is no geometry column. We could also set this to `None` to have a more specific indication for "no geometry column is set".

**Comment by joooeey** [comment]
I have no preference how to handle this but I'd like to point out that not only `df.copy()` but also `copy.copy(df)` and `copy.deepcopy(df)` from the [standard library copy module](https://docs.python.org/3/library/copy.html#copy.deepcopy) must preserve the type (whether that's DataFrame or GeoDataFrame). They currently don't, as discussed in #2765. Changing the type on copy is a grave violation of the least-astonishment principle. I guess there could be similar issues with [pickle](https://docs.python.org/3/library/pickle.html?highlight=pickle#module-pickle).

**Comment by jorisvandenbossche** [comment]
I agree we should at least ensure that `copy`/`deepcopy` preserve the type class.

> I guess there could be similar issues with [pickle](https://docs.python.org/3/library/pickle.html?highlight=pickle#module-pickle).

I was assuming so, since deepcopy basically does a pickle/unpickle as its copy strategy. But it seems that pickle correctly preserve the class. 

But it seems that pandas has custom `__copy__` and `__deepcopy__` implementations, and both dispatch to the `copy()` method. So we could start with overriding `copy` on GeoDataFrame to always return a GeoDataFrame.

**Comment by joooeey** [comment]
> But it seems that pandas has custom `__copy__` and `__deepcopy__` implementations, and both dispatch to the `copy()` method. So we could start with overriding `copy` on GeoDataFrame to always return a GeoDataFrame.

I searched through the source code of Pandas and it looks like they DO NOT have custom `__copy__` and `__deepcopy__` for DataFrames right now, only for Index.

**Comment by jorisvandenbossche** [comment]
It lives in pandas/core/generic.py: https://github.com/pandas-dev/pandas/blob/73840ef221050af2588b079bd6ba45c8e291bcba/pandas/core/generic.py#L6447-L6459
