### ISSUE TITLE
Importing order seems to affect working of GeoPandas

### ISSUE THREAD

**Issue by ozak** [geopandas/geopandas#214]
I have noticed that if I import GeoPandas before or after certain modules, it will not work properly. E.g.

    import numpy as np
    import geopandas as gp
    from geopandas.tools import sjoin, overlay
    from osgeo import gdal, gdalnumeric, ogr, osr
    df = gp.read_file('./file.shp')
 
will cause the following error

    FionaValueError: No dataset found at path './file.shp' using drivers: *

but if I change the order, so that GeoPandas is loaded last, then it works perfectly fine.

    import numpy as np
    from geopandas.tools import sjoin, overlay
    from osgeo import gdal, gdalnumeric, ogr, osr
    import geopandas as gp
    df = gp.read_file('./file.shp')

I have also noticed that loading some packages causes crashes for some operation. E.g. loading 
``rasterstats`` and using the ``buffer`` function on a GeoPandas Dataframe causes the program to crash. I have put a file in [this folder](https://www.dropbox.com/sh/2lerjfvg372rk7l/AACSoGEfJZkslI7DXBe4nK-Ua?dl=0) so that it can be replicated. ``buffer_works.py`` executes the basic buffer operation without any issues. ``buffer_fails.py`` changes the importing order and shows that now one cannot import the file. ``buffer_crashes.py`` is a variant of the one that works, but which now loads an additional package. ``buffer_works2.py`` also works, even importing ``rasterstats``, but it imports it after doing the buffer operation. 

I am on a Mac and using Homebrew's Python. The following is a list of packages on m computer:

``['affine==1.2.0', 'apptools==4.3.0', 'astroid==1.2.1', 'backports.ssl-match-hostname==3.4.0.2', 'basemap==1.0.7', 'beautifulsoup4==4.3.2', 'beautifulsoup==3.2.1', 'biopython==1.64', 'bokeh==0.8.2', 'boto==2.34.0', 'bottleneck==0.8.0', 'cartopy==0.13.0', 'certifi==2015.4.28', 'chaco==4.4.1', 'click-plugins==1.0.1', 'click==5.1', 'cligj==0.3.0', 'colorama==0.3.3', 'configobj==5.0.6', 'coverage==3.7.1', 'cython==0.22.1', 'decorator==3.4.2', 'descartes==1.0.1', 'dill==0.2.2', 'django==1.6.5', 'docopt==0.6.2', 'docutils==0.12', 'enable==4.4.1', 'enum34==1.0.4', 'envisage==4.4.0', 'fiona==1.6.1', 'flask==0.10.1', 'flup==1.0.2', 'folium==0.1.5', 'funcsigs==0.4', 'gdal==1.11.2', 'geopandas==0.1.0.dev-8ed45ac', 'geopy==1.3.0', 'georasters==0.3', 'gevent-websocket==0.9.3', 'gevent==1.0.1', 'gnureadline==6.3.3', 'google-api-python-client==1.4.0', 'greenlet==0.4.5', 'h5py==2.3.1', 'hmi==0.1', 'html5lib==0.999', 'httplib2==0.9.1', 'image==1.3.2', 'ipython==3.2.1', 'isounidecode==0.2', 'itsdangerous==0.24', 'jdcal==1.0', 'jinja2==2.7.3', 'jinja==1.2', 'jsonschema==2.4.0', 'logilab-common==0.62.1', 'lxml==3.3.5', 'markdown==2.6.2', 'markupsafe==0.23', 'matplotlib==1.4.3', 'mdp==3.3', 'mistune==0.5.1', 'mock==1.3.0', 'mpi4py==1.3.1', 'mpld3==0.2', 'mplexporter==0.0.1', 'mplleaflet==0.0.1', 'netcdf4==1.1.0', 'networkx==1.9.1', 'nose==1.3.7', 'numba==0.15.1', 'numexpr==2.4', 'numpy==1.9.2', 'oauth2client==1.4.7', 'openpyxl==2.1.3', 'pandas==0.16.2', 'pandasql==0.6.0', 'patsy==0.2.1', 'paver==1.2.4', 'pbr==1.3.0', 'pdfrw==0.1', 'pil==1.1.7', 'pillow==2.8.1', 'pip==7.0.3', 'pkginfo==1.1', 'plotly==1.6.17', 'progressbar==2.2', 'psycopg2==2.6', 'ptyprocess==0.4', 'py==1.4.26', 'pyandoc==0.0.1', 'pyasn1-modules==0.0.5', 'pyasn1==0.1.7', 'pybrain==0.3', 'pycluster==1.52', 'pydrive==1.0.1', 'pyepsg==0.1.0', 'pyface==4.5.0', 'pyflakes==0.8.1', 'pygments==1.6', 'pylint==1.3.1', 'pymc==3.0', 'pyodbc==3.0.7', 'pypandoc==0.8.4', 'pyparsing==2.0.3', 'pyproj==1.9.4', 'pysal==1.9.1', 'pyshp==1.2.3', 'pyspatialite==3.0.1', 'pystache==0.5.4', 'pytest==2.6.4', 'python-dateutil==2.4.2', 'pytz==2015.4', 'pyyaml==3.11', 'pyzmq==14.4.1', 'quandl==2.8.7', 'rasterio==0.25.0', 'rasterstats==0.5', 'redis==2.10.3', 'reportlab==3.1.44', 'requests-cache==0.4.7', 'requests==2.7.0', 'rope==0.10.2', 'rpy2==2.5.2', 'rsa==3.1.4', 'rst2pdf==0.93.dev-r0', 'rtree==0.8.2', 'scikit-image==0.12.dev0', 'scikit-learn==0.16.1', 'scipy==0.15.1', 'seaborn==0.6.0', 'setuptools==18.2', 'shapely==1.5.9', 'simplejson==3.6.5', 'simpy==3.0.5', 'singledispatch==3.4.0.3', 'six==1.9.0', 'smear==0.1.1.dev0', 'snuggs==1.3.1', 'sphinx==1.2.3', 'sqlalchemy==0.9.8', 'statsmodels==0.7.0', 'tables==3.1.1', 'terminado==0.5', 'theano==0.6.0', 'tornado==4.1', 'traits==4.5.0', 'traitsui==4.4.0', 'twine==1.3.1', 'uritemplate==0.6', 'vincent==0.4.4', 'websocket==0.2.1', 'werkzeug==0.10.4', 'wheel==0.24.0', 'wikipedia==1.4.0', 'wxpython-common==2.9.5.0', 'wxpython==2.9.5.0', 'xlrd==0.9.3', 'xlsxwriter==0.6.4', 'xlwt==0.7.5']``

I can give more info if needed.

**Comment by ozak** [comment]
Ok...some more info. It seems the problem with ``rasterstats`` was caused by having issued the command  ``from geopandas.tools import sjoin, overlay``. I guess it is best in this case not to do the import this way (which was copied from the GeoPandas site). See ``buffer_works3.py``. But the importing order is still affected as shown in ``buffer_fails2.py``.

**Comment by sgillies** [comment]
@ozak [long story](https://github.com/Toblerity/Fiona/issues/92) short: osgeo.* and Fiona (therefore geopandas) are incompatible. You can't reliably import them into the same Python program.

**Comment by ozak** [comment]
@sgillies thanks for the answer. Is there a ``Fiona`` way of doing like the following commands?

    cea = osr.SpatialReference()
    cea.SetCEA(0,0,0,0)
    wgs84 = osr.SpatialReference()
    wgs84.ImportFromEPSG(4326)

i.e. to create spatial reference systems without having to import them from some other file? What is the format being used by ``GeoPandas``?

**Comment by sgillies** [comment]
I recommend pairing [pyproj](https://pypi.python.org/pypi/pyproj) with Fiona and GeoPandas.

```python
>>> from pyproj import Proj
>>> cea = Proj(proj='cea', lon_0=0, lat_ts=0, x_0=0, y_0=0)
```
