### ISSUE TITLE
ENH: support how="inner" in sjoin_nearest

### ISSUE THREAD

**Issue by adriangb** [geopandas/geopandas#2140]
Followup to #1865 .

We should also discuss if `"inner"` should be the default.

**Comment by jorisvandenbossche** [comment]
@adriangb did you already start looking at it? (no pressure, just to know if I would start writing some tests myself I would be duplicating work or not)

**Comment by adriangb** [comment]
I started, but haven't spent more than 30 min on it so no worries about duplicate work 😃

**Comment by jorisvandenbossche** [comment]
If you have something, feel free to push a branch to your fork even if it's only minor work (in any case, I won't be able to start looking at before this evening)
