### ISSUE TITLE
getting error on .to_geojson()

### ISSUE THREAD

**Issue by Casyfill** [geopandas/geopandas#215]
my task is to upload geojson, add data from corresponding csv and save it back to geojson.
However, after I add columns by gj.join(df)  I cant save it to geojson getting Keyerror:

---

KeyError                                  Traceback (most recent call last)
<ipython-input-8-dfdaf75ecd09> in <module>()
----> 1 x = newGj.to_json()
      2 x

/usr/local/lib/python2.7/site-packages/geopandas/geodataframe.pyc in to_json(self, na, *_kwargs)
    249         return json.dumps(
    250             {'type': 'FeatureCollection',
--> 251              'features': [feature(i, row) for i, row in self.iterrows()]},
    252             *_kwargs )
    253 

/usr/local/lib/python2.7/site-packages/geopandas/geodataframe.pyc in feature(i, row)
    245                 'properties':
    246                     dict((k, v) for k, v in iteritems(row) if k != self._geometry_column_name),
--> 247                 'geometry': mapping(row[self._geometry_column_name]) }
    248 
    249         return json.dumps(

KeyError: None

**Comment by perrygeo** [comment]
can you provide some more details on how you did the join (exact code and possibly a small dataset to reproduce). I suspect that the join caused it to become a regular dataframe, losing  the geo info.

**Comment by micahcochran** [comment]
Is this related to issue #262?

**Comment by jdmcbr** [comment]
@Casyfill Not sure if this is still an issue, so closing for now, but can re-open if useful.

**Comment by Casyfill** [comment]
oh, my bad, of course!
