### ISSUE TITLE
Make rtree an optional dependency?

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#217]
As `rtree` is not really an easily installable package, it would easify the installation of geopandas if this was an optional dependency.

I am not familiar enough with geopandas to know how much this is needed for a lot of the functionality?

The test cases and code already checks if rtree is available or not, but just because it is in the `install_requires` in setup.py, installing geopandas fails.

**Comment by kjordahl** [comment]
@jorisvandenbossche I agree, I'd like to make `rtree` an optional dependency as well. This is IMO the biggest thing holding up a 0.2 release. It should be possible, some of the machinery to ignore `rtree` errors is already there: https://github.com/geopandas/geopandas/blob/master/geopandas/base.py#L72
