### ISSUE TITLE
ENH: check for minimum version of folium

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2187]
I've found that we require some recent version of folium with `explore`. I haven't yet checked which is needed but 0.8.3 that comes pre-installed in Google Colab is too old and raises an error. We should capture that and raise an informative error, instead of existing coming from folium (something about `missing 1 required positional argument: “location”`).

In case someone stumbles upon this issue trying to resolve Google Colab, just update folium.
```
!pip install folium -U
```

**Comment by martinfleis** [comment]
It is not about a keyword, it doesn't work at all. It happens during the initialization of a default marker type (even though the marker itself is not used).

```py
import geopandas

df = geopandas.read_file(geopandas.datasets.get_path("nybb"))
df.explore()

TypeError                                 Traceback (most recent call last)
<ipython-input-3-087623d14df8> in <module>()
      2 
      3 df = geopandas.read_file(geopandas.datasets.get_path("nybb"))
----> 4 df.explore()

1 frames
/usr/local/lib/python3.7/dist-packages/geopandas/explore.py in _explore(df, column, cmap, color, m, tiles, attr, tooltip, popup, highlight, categorical, legend, scheme, k, vmin, vmax, width, height, categories, classification_kwds, control_scale, marker_type, marker_kwds, style_kwds, highlight_kwds, missing_kwds, tooltip_kwds, popup_kwds, legend_kwds, **kwargs)
    511             marker_kwds["radius"] = marker_kwds.get("radius", 2)
    512             marker_kwds["fill"] = marker_kwds.get("fill", True)
--> 513             marker = folium.CircleMarker(**marker_kwds)
    514         else:
    515             raise ValueError(

TypeError: __init__() missing 1 required positional argument: 'location'
```

https://colab.research.google.com/drive/1aJySwBvJvYDaAinDZwQ0R9riEqbtwqvn?usp=sharing

**Comment by martinfleis** [comment]
The minimum required by GeoPandas now is 0.12 (corresponding to NEP29 now). We can potentially check for that as a minimum version and raise an error if an older is installed but I am not sure how important that is now when 0.14 is the latest version.

**Comment by fisaenko** [comment]
Hi! I'd like to work on this on, as it's still open.

**Comment by fisaenko** [comment]
@martinfleis, I faced a problem covering my few lines of code with tests. It seems like the only way to patch the folium's version (with value '0.8.0' for example) is to move [the imports from _explore function](https://github.com/geopandas/geopandas/blob/54c6c2ac0a6ee93f8340457215506d44b489ccec/geopandas/explore.py#L282) to the top of the module, so that they appear in the `dir(explore)` and, thus, it would be patchable with `mock.patch('geopandas.explore.folium')`.

Is it OK if I move them to the head of the module (given all tests pass), or is there a good reason why these imports are inside the _explore function?
Or maybe you (or anyone reading this) knows a workaround for this kind of problem?

**Comment by martinfleis** [comment]
> Is it OK if I move them to the head of the module (given all tests pass), or is there a good reason why these imports are inside the _explore function?

It is not okay, folium is an optional dependency. This type of code does not have be tested necessarily.

**Comment by fisaenko** [comment]
@martinfleis, got it, then my PR is ready for review.

I've got 2 failed tests in GitHub out of 20. One is Codecov warning about lack of tests for new code, the other is pytest not finished in "[ubuntu-latest, ci/envs/310-latest-conda-forge.yaml](https://github.com/geopandas/geopandas/issues/2187#logs)", with error "Error: The operation was canceled.", I don't have an idea why.
