### ISSUE TITLE
Reading in M values using geopandas 

### ISSUE THREAD

**Issue by AnneEstoppey** [geopandas/geopandas#2188]
This is about geodatabase, feature class, geopandas and geojson.

Our feature class is lines. The geometry parameters are X, Y, Z and also M.
M values can be used to store distance between vertices, or some other attribute.
M values are part of the geometry.
We are interested in preserving M values for our lines.

When exporting (or writing) a line feature class into a geojson file, using geopandas, we noticed that M values were missing.

After further investigation, we noticed that in fact the M values are not _read_ in by geopandas.
Displaying the geometry field from the geodataframe showed that M values were dropped.
Geometry parameters shown in the geodataframe are: X, Y and Z.

We could not see in the geopandas documentation that there is an option to add (or drop) M values.

Are we missing something or is the option to read in M values with geopandas not possible (yet)?

If this option does not exist, will it be a future enhancement?

Cheers
Anne

**Comment by dunha** [comment]
It's a shame this has been left for so long. GEOS claim to support simple features and be a port of JTS, but simple features support M values and JTS also has for 5 or 6 years at v 1.16. I note that it has been moved to a later milestone
The idea of supporting Ms as a separate field could work, considering ESRI appears to support them with an array of doubles in shapefiles and FileGDBs
