### ISSUE TITLE
QST: TypeError: object of type 'Point' has no len()

### ISSUE THREAD

**Issue by amrbakri** [geopandas/geopandas#2196]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
crs = {"init": "epsg:4326"}
df = pd.DataFrame(
    {
        #  Polygon([(4.338074,50.848677), (4.344961,50.833264), (4.366227,50.840809), (4.367945,50.852455), (4.346693,50.858306)])
        "Latitude": [
            51.13237486727857,
           51.132725423664596,
           51.13301489625002,
           51.13291397940796,
           51.1327121450621,
           51.132520932762816,
           51.13237486727857
            
        ],
        "Longitude": [
            6.692790084436616,
            6.6918971115756305,
            6.6922145189906725,
            6.6926758177672,
            6.692650425173997,
            6.692430356032901,
            6.692790084436616,
        ],
    }
)
gdfPoly = gpd.GeoDataFrame(
    df, crs=crs, geometry=gpd.points_from_xy(df.Longitude, df.Latitude)
)
gdfPoly2 = gpd.GeoSeries([shapely.Polygon(gdfPoly.geometry)], crs=crs)

df2 = pd.DataFrame({"Latitude": [51.133242273121596], "Longitude": [6.6922343999668]})
gdfPoint = gpd.GeoDataFrame(
    df2, crs=crs, geometry=gpd.points_from_xy(df2.Longitude, df2.Latitude)
)
# finally distance, taking into account CRS in metres
dist = gdfPoint.to_crs(32632).distance(
    gdfPoly2.to_crs(32632)
)
print(dist)

```

#### Problem description
The code posted above works fine on my pc at home, however, when i tried to run it on another machine it gives me the following error:
File "shapely/speedups/_speedups.pyx", line 319, in shapely.speedups._speedups.geos_linearring_from_py
        n = len(ob[0])
    TypeError: object of type 'Point' has no len()
I confirmed the installation of the most recent version of geopandas,shapely and pandas.Though, i receive the aforementioned error.

#### Expected Output
I expect to get the distance to the nearest edge from or between the point and the points compose a polygon as descriped in code above,
#### Output of ``geopandas.show_versions()``

<details>

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

</details>

**Comment by martinfleis** [comment]
Hi @amrbakri, this looks like an installation issue as the snippet works on my side as expected. How did you install geopandas and shapely?
