### ISSUE TITLE
BUG: Spatial join returns incorrect results with Shapely 1.8

### ISSUE THREAD

**Issue by nicolaslegrand91** [geopandas/geopandas#2198]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely import wkt

# Define 2 geometries
point = wkt.loads('POINT (-3.61104 54.12069)')
polygon = wkt.loads('''
    Polygon ((-3.63156666666667 54.1267166666667,-3.53435 54.0763833333333,-3.5634 54.0383333333333,
    -3.58396666666667 54.0467,-3.60175 54.0521333333333,-3.62465 54.05735,-3.64296666666667
    54.0595333333333,-3.65568333333333 54.0740166666667,-3.6695 54.0932833333333,-3.65568333333333
    54.1054666666667,-3.63156666666667 54.1267166666667))
''')
print('\npoint within polygon?')
print(point.within(polygon))

# Geodataframe with 1 polygon
df = gpd.GeoDataFrame.from_dict({
    'id': [1],
    'geometry': [polygon],
})
# Geodataframe with 1 Point
poi = gpd.GeoDataFrame.from_dict({
    'id': [2],
    'geometry': [point],
})

print('\nSpatial join:')
print(gpd.sjoin(poi, df, predicate="within"))

```

#### Problem description

The spatial join behaviour (with PyGeos) has changed between Shapely 1.7.1 (correct behaviour) and Shapely 1.8 (incorrect behaviour).
Note that the point does not fall into the polygon. These are WGS84 coordinates, and the distance from the point to the polygon is ~400 meters.
![image](https://user-images.githubusercontent.com/20555592/139079313-9a65d086-642c-43b4-b6ae-b3c4655b271a.png)

**With Shapely 1.7.1 (correct behaviour)**
![image](https://user-images.githubusercontent.com/20555592/139079562-759234b4-30f4-4437-9abd-a497bed2a46b.png)

**With Shapely 1.8 (incorrect behaviour)**
Note that the point is still considered out of the polygon, but the spatial joins incorrectly considers the point to be in the polygon.
![image](https://user-images.githubusercontent.com/20555592/139079766-78658b65-8f16-431d-87d0-f2d45269156a.png)

#### Expected Output

The expected output is the one with Shapely 1.7.1. 
A possible lead is the fact that PyGeos & Shapely 1.8 are built on the same GEOS version, hence no conversions apply (the warnings does not appear). Maybe the formats are not exactly compatible.

#### Output of ``geopandas.show_versions()``

This is the output with shapely 1.8.0. Simply run `pip install shapely==1.7.1` to test the working configuration.

<details>

SYSTEM INFO
-----------
python     : 3.9.5 (default, May  4 2021, 03:33:11)  [Clang 12.0.0 (clang-1200.0.32.29)]
executable : /Users/nicolaslegrand/.virtualenvs/py39/bin/python
machine    : macOS-10.16-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /usr/local/Cellar/geos/3.9.1/lib/libgeos_c.dylib
GDAL       : 3.2.2
GDAL data dir: None
PROJ       : 7.2.1
PROJ data dir: /Users/nicolaslegrand/.virtualenvs/py39/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.2.5
fiona      : 1.8.19
numpy      : 1.21.3
shapely    : 1.8.0
rtree      : None
pyproj     : 3.0.1
matplotlib : 3.4.3
mapclassify: None
geopy      : 2.2.0
psycopg2   : 2.9.1 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : None
pygeos     : 0.10.2

</details>

**Comment by nicolaslegrand91** [comment]
Should I open an issue in PyGeos ?

**Comment by jorisvandenbossche** [comment]
Yes, that's certainly welcome!

**Comment by caspervdw** [comment]
Ref also https://github.com/pygeos/pygeos/issues/447

I think this is something that should be solved here in geopandas, as geopandas is not using the `pygeos.to_shapely` but it has its own implementation.

There doesn’t seem to be a way to detect the exact geos library being used by pygeos, the suggestion of @jorisvandenbossche to only use the pointer conversion when both packages are from the conda environment seems to be a good solution until shapely 2 is out.

**Comment by jorisvandenbossche** [comment]
Given that pygeos is no longer maintained and shapely 2.0 is now well established, and that the main dev branch of geopandas (for 1.0) only supports shapely > 2 (so no longer any issues with mixing pygeos and shapely are possible), I think we can close this issue.
