### ISSUE TITLE
BUG: Enabling PyGeos prevents a geometry's attributes to be set in a GeoSeries (behavior diverges with/out PyGeos enabled)

### ISSUE THREAD

**Issue by InnovativeInventor** [geopandas/geopandas#2199]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
```python
import geopandas
from shapely.geometry import Polygon

geometries =  geopandas.GeoSeries(Polygon([(0,0), (1,1), (1,0)]))
geometries[0].id = "test"
print(geometries[0].id)
```

#### Problem description
The behavior of GeoPandas secretly changes when PyGeos is enabled (looks like it's enabled by default whenever PyGeos is installed). When PyGeos is not installed, setting and getting the attribute of a `Polygon` within a GeoPandas object works as expected. That is, arbitrary attributes can be set and get. For example, this works:

```python
geometries[0].id = "test"
print(geometries[0].id)
```

However, when PyGeos is enabled (by default, whenever it is installed), one can no longer set an arbitrary attribute and attempting to run the above code results in an `AttributeError`.

```python
AttributeError: 'Polygon' object has no attribute 'id'
```
or
```python
AttributeError: 'pygeos.lib.Geometry' object has no attribute 'id'
```
(the bottom error only occurs when the PyGeos mode is switched after a GeoSeries is created).

This is extremely confusing for a user to debug because Shapely **allows** for a Polygon attribute to be set when PyGeos is installed. For example, this snippet works even when PyGeos is enabled and the `AttributeError` detailed above is raised.
```python
poly = geometries[0]
poly.id = "test"
print(polly.id)
```

#### Expected Output
This violates user expectations. Installing PyGeos should not secretly change the behavior of GeoPandas without warning. Additionally, the behavior of an object of a geometry within a GeoSeries should not change after being taken out of a GeoSeries (at least, not without adequate warning to the user). This bug causes `AttributeError`s to be raised in downstream packages (e.g. https://github.com/mggg/GerryChain and https://github.com/mggg/maup), without any obvious reason. This bug was difficult to hunt down because it was unexpected that the presence of a separate package on a user's system would affect the behavior of GeoPandas.

At the very least, a detailed warning should be raised when PyGeos is enabled and a user attempts to set an attribute of a geometry object within GeoPandas. E.g.
```python
geometries[0].id = "test"
```
should result in a warning and this behavior should be documented somewhere.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.4 (default, Apr 24 2021, 22:00:31)  [GCC 9.3.0]
executable : /home/max/.pyenv/versions/3.9.4/bin/python
machine    : Linux-5.11.0-7620-generic-x86_64-with-glibc2.31

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.0
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.3.0
GDAL data dir: /home/max/.pyenv/versions/3.9.4/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 8.0.1
PROJ data dir: /home/max/.pyenv/versions/3.9.4/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2+1.g409d8f0
pandas     : 1.2.4
fiona      : 1.8.20
numpy      : 1.20.3
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.1.0
matplotlib : 3.4.2
mapclassify: 2.4.3
geopy      : 2.2.0
psycopg2   : None
geoalchemy2: None
pyarrow    : 4.0.0
pygeos     : 0.10.2

</details>

**Comment by InnovativeInventor** [comment]
> @InnovativeInventor you might be interested in [`tobler`](https://pysal.org/tobler/) (and the broader pysal ecosystem)

Cool stuff -- looks very useful! We do a lot of vote and population dis/aggregation at the [MGGG redistricting lab](https://mggg.org/). One difficult problem we have is that some states only report mail-in ballots at the county-level, which throws off our voting rights act analysis (particularly for 2020 data). We have a few ways of disaggregating county-level vote data to the precinct-level (including using party registration stats), but it looks like `tobler` implements a few more (NLCD is something I always wanted to implement but never got around to).

Thanks for sharing -- your other projects also look interesting!

**Comment by jorisvandenbossche** [comment]
The original issue (setting an attribute on a scalar geometry) is now disallowed by shapely, and is otherwise also something to discuss on the shapely side. So closing this issue.
