### ISSUE TITLE
TST: tests with invalid values fail with pandas master

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2207]
We have some recent failures coming from pandas master - 
https://github.com/geopandas/geopandas/runs/4059704198?check_suite_focus=true

All seem to be related to the handling of invalid values but I guess that the fix should happen in pandas? I've got no bandwidth now, so filing it to keep an eye on it.

**Comment by jorisvandenbossche** [comment]
Will take a look after the weekend
