### ISSUE TITLE
DOC: Include links to matplotlib documentation in GeoDataFrame.plot() documentation

### ISSUE THREAD

**Issue by philipmnelson** [geopandas/geopandas#2209]
In the documentation for [GeoDataFrame.plot()](https://geopandas.org/docs/reference/api/geopandas.GeoDataFrame.plot.htm) would like the [matplotlib.pyplot.legend() and matplotlib.pyplot.colorbar() functions](https://geopandas.org/docs/reference/api/geopandas.GeoDataFrame.plot.html#:~:text=matplotlib.pyplot.legend()%20or%20matplotlib.pyplot.colorbar()) to link to their respective matplotlib documentation. 

Docs for  [matplotlib.pyplot.legend()](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html) and  [matplotlib.pyplot.colorbar()](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.colorbar.html)

I think this is relevant change because it's not immediately clear what keyword args can be used in legend args and inclusion of these links makes this more clear.

**Comment by martinfleis** [comment]
Thanks for the suggestion! This would be nice, we can use intersphinx mapping to ensure the links are correctly preserved long-term. A PR would be welcome!

**Comment by SimWard** [comment]
Hi team - if noone else has put their hand up I'd love this as a first issue for me.

Might ask some questions if I run into problems with that intersphinx mapping.

**Comment by martinfleis** [comment]
@ryanward-io Go for it! Thanks!

Feel free to prepare a draft PR and we can resolve all questions there.
