### ISSUE TITLE
BUG: UnboundLocalError when missing_kwds is used

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2210]
I'm afraid the issue isn't completely solved yet. Still (0.9.0, 0.10.2) getting the following error  

<img width="709" alt="Bildschirmfoto 2021-11-01 um 18 21 00" src="https://user-images.githubusercontent.com/4449821/139724524-68bd0d0d-ad1c-405e-af3a-cb1f46155371.png">  

however, if I apply your fix a second time a little later in the code like this  

<img width="641" alt="Bildschirmfoto 2021-11-01 um 18 21 58" src="https://user-images.githubusercontent.com/4449821/139724615-f0264f23-76d2-4029-bbe7-4740d428f153.png">

it plots as expected – should you need a testcase pls let me know and thanks so far

_Originally posted by @wahlatlas in https://github.com/geopandas/geopandas/issues/1600#issuecomment-956497381_

**Comment by wahlatlas** [comment]
Would this be of any help
https://nbviewer.org/urls/wahlatlas.net/btw/21/geopandas.ipynb
or would you need a more reduced case with english comments?

**Comment by wahlatlas** [comment]
Maybe some complete sentence on the issue:
The `missing_kwds` defines how missing data should be styled on the plotted map and does this just fine. However if such definition is present but there happens to be no missing data, the mentioned `UnboundLocalError` will occur. In the above example this comes up as the plot command is used with various data columns, some of which happen to have missing data, others not (in this case smaller parties that weren't eligible in the whole country).

**Comment by jdmcbr** [comment]
A reproducible example:
```
import geopandas as gpd
world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
world.plot(column="continent", legend=True, missing_kwds={"facecolor": "none"})
```
