### ISSUE TITLE
DOC: add sjoin_nearest example to gallery/spatial_joins

### ISSUE THREAD

**Issue by raybellwaves** [geopandas/geopandas#2211]
https://geopandas.org/gallery/spatial_joins.html doesn't mention `sjoin_nearest` (https://geopandas.org/docs/reference/api/geopandas.GeoDataFrame.sjoin_nearest.html#geopandas.GeoDataFrame.sjoin_nearest).

An example could be added here https://github.com/geopandas/geopandas/blob/master/doc/source/gallery/spatial_joins.ipynb

**Comment by ryanward-io** [comment]
I'm happy to come up with an example here for `sjoin_nearest` and add to that jupyter notebook - feel free to leave with me.
