### ISSUE TITLE
BUG: 'dict' object has no attribute 'to_epsg'

### ISSUE THREAD

**Issue by iamtekson** [geopandas/geopandas#2214]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
df.crs
crs.to_epsg()
```

#### Problem description
I tried to get the epsg code for my geopandas dataframe like above. On the previous version `0.9.x` it was working fine. But with the latest version I am getting this error, ` 'dict' object has no attribute 'to_epsg'`

#### Expected Output
It should provide me the EPSG code like `4326`.

I am using geopandas 0.10.0 version

**Comment by iamtekson** [comment]
Sorry, my bad. My geopandas `v0.6.x` from another venv was loading thats why I faced this issue. I will close this issue for now.

**Comment by jorisvandenbossche** [comment]
Indeed, on older geopandas versions the `.crs` attribute did not yet return a pyproj.CRS object
