### ISSUE TITLE
BUG: overlay with how='difference' and an empty df2 gives empty result

### ISSUE THREAD

**Issue by mainkai** [geopandas/geopandas#2215]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

overlay with how='difference' and an empty df2 gives empty result

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
import shapely.geometry as shg

df1 = gpd.GeoDataFrame(geometry=[shg.Polygon([(8.0, 49.0), (8.5, 49.0), (8.5, 49.5)])], crs="EPSG:4326")
df2 = gpd.GeoDataFrame(geometry=[], crs=df1.crs)
diff = gpd.overlay(df1, df2, how="difference", keep_geom_type=False)
print(f"df1: {df1.area.sum()}, df2: {df2.area.sum()}, diff: {diff.area.sum()}")

```
**Output:**

**geopandas 0.9.0:**
df1: 0.125, df2: 0.0, diff: **0.125**

**geopandas 0.10.0:**
df1: 0.125, df2: 0.0, diff: **0.0**

#### Problem description

geopandas 0.10.0 returns an empty GeoDataFrame

#### Expected Output

geopandas 0.9.0 shows the expected behaviour: return the original df1

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.7.12 (default, Sep 10 2021, 00:20:04)  [GCC 9.3.0]
executable : x
machine    : Linux-5.4.0-89-generic-x86_64-with-Ubuntu-20.04-focal

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 2.4.4
GDAL data dir: x
PROJ       : 6.3.1
PROJ data dir: x

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.0
pandas     : 1.1.2
fiona      : 1.8.17
numpy      : 1.19.1
shapely    : 1.7.1
rtree      : None
pyproj     : 2.6.0
matplotlib : 3.3.1
mapclassify: None
geopy      : 2.0.0
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : 0.8

</details>

**Comment by martinfleis** [comment]
Try updating to geopandas 0.10.2. This regression should be already fixed.

**Comment by mainkai** [comment]
Thanks for the quick reply and yes, updating to 0.10.2 fixed it.
Sorry for not checking the latest version!
