### ISSUE TITLE
ENH: add engine keyword to read_file to support other backends (pyogrio, pyshp, ..)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#2217]
To support using different backend libraries for reading general GIS files (pyogrio, pyshp (https://github.com/geopandas/geopandas/pull/1580/), ..), we could add an `engine` keyword to the `read_file` function and `to_file` method.

For example, we could then have `geopandas.read_file(path, engine="pyogrio")` to opt-in to use pyogrio instead of fiona for reading the file. 

The `engine` naming is consistent with eg pandas/dask `read_parquet` and `read_csv`.

**Comment by martinfleis** [comment]
Do you want to ship it in 0.11? `pyogrio` engine advertised as an experimental implementation should be ready to go and that `pyshp` PR (#1580) should also work (may need some updating). It would be a nice highlight of the release.

**Comment by jorisvandenbossche** [comment]
That sounds as a good idea! (although it would probably be good to then set up pyogrio wheels by then ..)

**Comment by jack89roberts** [comment]
Could there be (or is there already) a way to set the default engine across all calls via an environment variable/similar?

**Comment by brendan-ward** [comment]
Having something like a `GEOPANDAS_DEFAULT_FILEIO_ENGINE` variable might be helpful for this, though it would still depend on what I/O engines are installed.

Right now Geopandas defaults to Fiona if available and then Pyogrio if available and Fiona is not, so (in theory) if you want to default to Pyogrio you can just uninstall Fiona from your environment.  But if you have a use case where you need to have more than one of the engine libraries installed, this won't work well.

**Comment by jack89roberts** [comment]
Thanks. Geopandas itself specifies Fiona as a dependency, but I could do `pip install geopandas pyogrio && pip uninstall fiona` I suppose. I don't have a reason beyond curiosity to be trying pyogrio, though, so having to modify all my `read_file` calls or add extra steps to my environment creation is probably enough for me to just skip it for now.

**Comment by jack89roberts** [comment]
Thanks. Geopandas itself specifies Fiona as a dependency, but I could do `pip install geopandas pyogrio && pip uninstall fiona`, I suppose. I don't have a reason beyond curiosity to be trying pyogrio, though, so having to modify all my `read_file` calls or add extra steps to my environment creation is probably enough for me to just skip it for now.

**Comment by m-richards** [comment]
I've also wondered about this myself, having switched over to using pyogrio on a project myself while collaborators are still using fiona, and wanting to be able to toggle back and forth if necessary. 

Another option may be to add something like `geopandas.options.use_pygeos` to control the global default of `engine` in read_file and to_file. (But I guess the environment variable has the advantage of requiring zero code changes.)

**Comment by martinfleis** [comment]
I'd mirror what we have for pygeos here.

**Comment by jorisvandenbossche** [comment]
An option to set the default file IO engine sounds good indeed (and actually for `use_pygeos`, we also allow you to set the default for that option through an environment variable ..)

**Comment by afernando79** [comment]
To chime in here, (forgive me if I am totally off) I would love to be able to use an engine that supports reading a file in chunks, achieved using pyshp.Reader().shapeRecord() for a list of records. 

My use-case is to be able to split a massive shapefile into smaller chunks and persist each to disk for loading into BigQuery therefore avoiding blowing memory and CPU limits when running in a GCP CloudRun instance. I have a pipeline that works synchronously to chop up the file into smaller chunks never utilising more than a fraction of the total file's size and am working on making it multi-threaded as a first step, with potentially reengineering it to leverage multi-processing at a later stage. But if geopandas (or perhaps geopandas-dask or equivalent) could support reading a shapefile without reading the whole thing into memory (as I believe is the case with Fiona), and provide an iterator or generator that only reads the disk at memory locations defined by the index, then that would be amazing. If anyone has a suggestion on how this could be possible, I would love to know what I can do. As I understand it, fiona would read the shp, dbf (and optionally the idx) to get all the records into RAM. Even if taking a small slice of the dataframe, the entirety of both DBF and SHP will need to be read to get only a subset of the dataset.

Please correct me if I am wrong but ultimately, being able to create a geopandas GeoDataFrame from only a chunk of the records without reading the whole thing into RAM first is key requirement here.

**Comment by afernando79** [comment]
I just had a look at the pyogrio library and notice it does potentially provide the functionality I am after. I am having issues with getting an environment working with the correct versions etc so I think I should look into that further before going any further with pyshp. If anyone has a link to a dockerfile definition that provides a working container and includes all libraries etc necessary, that would be mega. If not, I will attempt to get a Dockerfile created and share it once I am done.

**Comment by m-richards** [comment]
>  If anyone has a link to a dockerfile definition that provides a working container and includes all libraries etc necessary, that would be mega. If not, I will attempt to get a Dockerfile created and share it once I am done.

@afernando79 just in case you haven't already seen it, pyogrio runs tests on top of a gdal docker image, this might help you getting started with a Dockerfile:
https://github.com/geopandas/pyogrio/blob/main/.github/workflows/docker-gdal.yml

**Comment by martinfleis** [comment]
Here's the geo stack Docker we use for teaching and research https://github.com/darribas/gds_env. It includes pyogrio but I'd recommend building it rather than pulling the last tag as it is a bit dated now.

**Comment by afernando79** [comment]
Thanks @martinfleis and @m-richards! a great help

That will save me a whole load of effort 👍🏾

**Comment by brendan-ward** [comment]
@afernando79 your chunked approach should work with pyogrio using the `skip_features` / `max_features`.

Here's a lightweight Dockerfile I've used for local testing of pyogrio; it assumes that you are building it from within that repo:

```
ARG VERSION=latest

FROM osgeo/gdal:ubuntu-small-$VERSION

WORKDIR /code

RUN apt-get update && apt-get -y install sudo python3-pip && \
    apt-get remove -y python3-numpy

RUN pip3 install cython && \
    pip3 install fiona --no-binary fiona && \
    pip3 install numpy pygeos geopandas

# Uncomment to build within container instead of against host
# COPY . /code
# RUN pip3 install -e .[dev,test,geopandas]
```

Then build it for whatever version of GDAL is appropriate for you:

```bash
docker build --build-arg VERSION="<GDAL version>" -f <filename of above> . -t <tag>
```

As you can see from the comments above, it is possible to either copy the code into the container or to mount against the host using the `-v <host directory>:/code` flag.

Note: this was for testing pyogrio which then uses geopandas via its `read_dataframe()` / `write_dataframe()`; I haven't tested this setup yet from the geopandas `read_file(..., engine="pyogrio")` side yet, but it _should_ work.

Also note: builds Fiona using GDAL within the container so it matches what is used by pyogrio, though Fiona isn't necessary for what you are doing (it is used in some of our tests in pyogrio).

**Comment by afernando79** [comment]
@brendan-ward That is awesome and after the comments from earlier today, I had taken a look at the Dockerfiles and was going to attempt what you have kindly done for me! Even less work for me to do - I feel guilty but grateful.

I will feed back once I have tried the approach you all have suggested. Thanks again

**Comment by Robinlovelace** [comment]
Heads-up @jorisvandenbossche and other developers, I've just mentioned `pyogrio` as another backend and linked to this issue. Please take a peak at the commit above and context, grateful for confirmation that the contents are correct (`fiona` is still the default engine) and any other comments. Thanks for great work in this space and +1 to `engine` arg even if it would result in some rewriting when added!

**Comment by martinfleis** [comment]
@Robinlovelace It is correct, as of today. The `engine` keyword is there and is not going anywhere, the default will change to `pyogrio` though. Not sure if we discussed when, but I assume that 1.0 will be the target.

@jorisvandenbossche do we want to warn about the change in 0.14 already?

**Comment by martinfleis** [comment]
The `engine` keyword has been implemented and at this point supports fiona and pyogrio options.
