### ISSUE TITLE
DOC: contributing guide: point users to env file to install deps?

### ISSUE THREAD

**Issue by raybellwaves** [geopandas/geopandas#2220]
#### Is your feature request related to a problem?

No

#### Describe the solution you'd like

Switch https://docs.geopandas.org/en/latest/community/contributing.html#installing-dependencies to point to a "geopandas_dev" environment file and put it in e.g. https://github.com/geopandas/geopandas/blob/master/ci/envs

Rather than have a user do a few manual import steps e.g.

```
conda create -n geopandas_dev python
conda activate geopandas_dev
conda install -c conda-forge pandas fiona shapely pyproj rtree pytest
python -m pip install pre-commit
pre-commit install
```

Create a geopandas_dev file which has https://github.com/geopandas/geopandas/blob/master/ci/envs/39-latest-conda-forge.yaml in it as well as others e.g. pre-commit and have a user do `conda/mambe env update -f 39-latest-conda-forge.yaml`

#### Additional context

https://github.com/geopandas/geopandas/blob/master/ci/envs/39-latest-conda-forge.yaml could be used but it's named "test" and doesn't have pre-commit.

**Comment by jorisvandenbossche** [comment]
Pointing contributors to an environment.yml file to create the conda environment sounds good to me. 

We could maybe also add a top-level `environment.yml`? (instead of reusing one of the ci/ ones, since those are not _exactly_ what we want for this; we could also change the name of names though)

**Comment by martinfleis** [comment]
We have `environment-dev.yml` in the top level, it just need some updating.

**Comment by jorisvandenbossche** [comment]
Ah, good point, forgot about that :) 

And then also update the contributing docs to mention that.

**Comment by raybellwaves** [comment]
> We have `environment-dev.yml` in the top level, it just need some updating.

https://github.com/geopandas/geopandas/blob/master/environment-dev.yml does seem like a good candidate

**Comment by wxman22** [comment]
I can work on this

**Comment by martinfleis** [comment]
@wxman22 That'd be awesome, thanks!
