### ISSUE TITLE
The x, y, z coordinate attributes error with empty points

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#2223]
Hi! Working with GeoPandas `0.10.2` and the method [here ](https://geopandas.readthedocs.io/en/stable/docs/reference/api/geopandas.GeoSeries.z.html#geopandas.GeoSeries.z) fails:

```python
>>> my_geodataframe.geometry.x
...
IndexError: index out of range
```
 
See the full traceback attached: [traceback.log](https://github.com/geopandas/geopandas/files/7503163/traceback.log).

Ideally, however, this should work: with `my_geodataframe.geometry` I get a `GeoSeries`, so the `.[xyx]` attribute should return the longitude/latitude/elevation.

_Originally posted by @baggiponte in https://github.com/geopandas/geopandas/issues/246#issuecomment-963926763_

**Comment by jorisvandenbossche** [comment]
@baggiponte that's because of the presence of empty points, it seems.

Small reproducer:

```python
import geopandas
from shapely import wkt

gs = geopandas.GeoSeries([wkt.loads("POINT (1 1)"), wkt.loads("POINT EMPTY")])
gs.x
```

Both using pygeos or shapely under the hood errors in the case above, and that simply bubbles up the error from shapely/pygeos itself:

```python
# Shapely
>>> from shapely import wkt
>>> empty = wkt.loads("POINT EMPTY")
>>> empty.x
Traceback (most recent call last)
~/miniconda3/envs/geo-dev/lib/python3.9/site-packages/shapely/geometry/point.py in x(self)
~/miniconda3/envs/geo-dev/lib/python3.9/site-packages/shapely/coords.py in __getitem__(self, key)
IndexError: index out of range

# pygeos
>>> import pygeos
>>> empty = pygeos.Geometry("POINT EMPTY")
>>> pygeos.get_x(empty)
Traceback (most recent call last)
...
GEOSException: UnsupportedOperationException: getX called on empty Point
```

**Comment by baggiponte** [comment]
Oh I completely ignored this! Thank you very much for the help. I also tried this, which confirms your suspicions:

```python
>>> my_data[my_data.geometry.isna()]
UserWarning: GeoSeries.isna() previously returned True for both missing (None) and empty geometries. Now, it only returns True for missing values. Since the calling GeoSeries contains empty geometries, the result has changed compared to previous versions of GeoPandas.
Given a GeoSeries 's', you can use 's.is_empty | s.isna()' to get back the old behaviour.
```

Can I perhaps do something, like help with drafting a more informative error message for the traceback or on the official documentation?

**Comment by simberaj** [comment]
Would returning `nan` for empty geometry coordinates be more appropriate?

**Comment by martinfleis** [comment]
> Would returning `nan` for empty geometry coordinates be more appropriate?

Yeah, that is probably the only solution if we don't want to raise an error.
