### ISSUE TITLE
BUG: Unexpected behaviour with explode()

### ISSUE THREAD

**Issue by skizoforme** [geopandas/geopandas#2229]
- [ ] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---
```
import geopandas as gpd
from shapely.geometry import Polygon

index = [0, 0]
ids = ['one', 'two']
geometry = [Polygon([[0, 0], [0, 1], [1, 1]]),
           Polygon([[2, 2], [2, 3], [3, 3]])]

gdf = gpd.GeoDataFrame(ids, columns=['ids'], index=index, geometry=geometry)
gdf.explode(ignore_index=True)
```

Output:

![image](https://user-images.githubusercontent.com/30041765/142169095-ea6f7b61-91f9-4ce8-a163-61543c32134e.png)

#### Problem description

Is this the expected behaviour when indexes are duplicated? Or the expected output should be:

![image](https://user-images.githubusercontent.com/30041765/142170447-78fa1b30-fc5b-45e9-88fb-5ac44d2da74d.png)

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\skizoforme\Miniconda3\envs\geo\python.exe
machine    : Windows-10-10.0.19042-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.2.1
GDAL data dir: None
PROJ       : 7.2.0
PROJ data dir: C:\Users\skizoforme\Miniconda3\envs\geo\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.4
fiona      : 1.8.18
numpy      : 1.21.4
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.1.0
matplotlib : 3.4.3
mapclassify: 2.4.3
geopy      : None
psycopg2   : 2.8.6 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 3.0.0
pygeos     : 0.9

</details>

**Comment by martinfleis** [comment]
Thanks! I can confirm that this behaviour exists on master as well. It is a bug, the index should have no effect on a result of explode.

**Comment by skizoforme** [comment]
Thank you very much!! And sorry for not having responded earlier...
