### ISSUE TITLE
pandas v0.17.0rc1

### ISSUE THREAD

**Issue by shoyer** [geopandas/geopandas#223]
We have a release candidate of pandas 0.17.0 out, which has some fairly significant changes.

It would be great if you could test it and provide any feedback: https://github.com/pydata/pandas/releases/tag/v0.17.0rc1

Thanks!

**Comment by kjordahl** [comment]
Thanks for the heads up. We are running tests against pandas master, so I don't expect any issues, but I'll take a look.

**Comment by jorisvandenbossche** [comment]
@kjordahl 0.17.0 is released in the meantime. So this issue can maybe be closed

**Comment by jorisvandenbossche** [comment]
And you just made https://github.com/geopandas/geopandas/issues/243 for the follow-up

**Comment by kjordahl** [comment]
Yep, covered there.
