### ISSUE TITLE
BUG: Folium map is not added when using geoDataframe.explore()

### ISSUE THREAD

**Issue by MiguelonGonzalez** [geopandas/geopandas#2241]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

#### Code Sample, a copy-pastable example

```
# Creation of the Folium Map
mymap = folium.Map(tiles='openstreetmap', control_scale=True)
geoPath = folium.GeoJson(gdf1).add_to(mymap)
folium.LayerControl().add_to(mymap)

# Adding info with .explore():
gdf2.explore(color='Color',  # Color values to plot the entities
                    legend_kwds=dict(labels=['Asc','Desc']),
                    legend=True,
                   style_kwds=dict(stroke=False,
                   opacity=0.75),
                   m=mymap )
```

#### Problem description:

I'm using geodataframe.explore() method to add a basemap to my plot with folium library. Since I have a previous folium Map to which add this info, I'm passing it through `m `agg.

Nevertheless, this plot is not added to my previous map. Even more, some of the previous folium Map features are erased.

After many hours of seeking what could be wrong, I've decided to report it as a bug.

**Comment by martinfleis** [comment]
Thank you for the report!

I _think_ that the reason behind the unexpected behaviour here is the order in which you call the methods, especially the `LayerControl`. Can you try adding `LayerControl` to the map after you call `explore`? If I remember correctly, folium requires all layers to be defined before you can add `LayerControl`. 

```py
# Creation of the Folium Map
mymap = folium.Map(tiles='openstreetmap', control_scale=True)
geoPath = folium.GeoJson(gdf1).add_to(mymap)

# Adding info with .explore():
gdf2.explore(color='Color',  # Color values to plot the entities
                    legend_kwds=dict(labels=['Asc','Desc']),
                    legend=True,
                   style_kwds=dict(stroke=False,
                   opacity=0.75),
                   m=mymap )

folium.LayerControl().add_to(mymap)
```

**Comment by MiguelonGonzalez** [comment]
Thank you very much for your quick response!
It was exactly what you say...
Sorry for reporting it as a bug then.
