### ISSUE TITLE
DOC: Address GeoPandas op deprecation in docs

### ISSUE THREAD

**Issue by ryanward-io** [geopandas/geopandas#2246]
While working on #2211 I noticed instances of the `op` parameter still being used.

This `op` parameter was deprecated in pull request #1626 in favour of `predicate`.

Locations where op is still present includes:
* [sjoin benchmark](https://github.com/geopandas/geopandas/blob/master/benchmarks/sjoin.py)
* [Spatial Joins notebook](https://github.com/geopandas/geopandas/blob/master/doc/source/gallery/spatial_joins.ipynb)
 
I can address the notebook instance but I don't know what the benchmark instance of `op` does so wouldn't want to change it without a thumbs up from a maintainer.

**Comment by martinfleis** [comment]
Good catch! You can simply replace every instance of `op` with `predicate` and it should work.
