### ISSUE TITLE
QST: master to main?

### ISSUE THREAD

**Issue by bjlittle** [geopandas/geopandas#2252]
Is there appetite to rename the `master` branch to `main` ?

Akin to `numpy`, `matplotlib`, `dask`, `xarray`, `scikit-learn`, `Shapely` et al

**Comment by martinfleis** [comment]
I have a vague sense that we already discussed this at some point and agreed that we want to do that but I am not able to find that anywhere, so it may have been elsewhere.

Anyway, I think that we should do the switch. We just need to track where we have to change the hard-coded `master` to ensure that everything (CI, links) works properly.

**Comment by brendan-ward** [comment]
Crossref: https://github.com/geopandas/community/issues/7

**Comment by jorisvandenbossche** [comment]
Yes, I have been meaning to get to that after opening https://github.com/geopandas/community/issues/7, which has a list of projects to update and some additional steps to take

**Comment by martinfleis** [comment]
The default branch is renamed to `main`. The remaining stuff is in #2277.
