### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by sergiocaccamo** [geopandas/geopandas#2254]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
L = geopandas.GeoDataFrame()
L['name'] = ['Vatican City', 'San Marino']
L['geometry'] = [shapely.geometry.Point(12.45339, 41.90328),
                 shapely.geometry.Point(12.44177, 43.93610)]
L.explore()
```
different from:

```python
cities = geopandas.read_file(geopandas.datasets.get_path('naturalearth_cities'))
cities[:2].explore()
```

same strange behavior obtained using your code example:

```python

df = pandas.DataFrame(
    {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
     'Country': ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Venezuela'],
     'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
     'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})
gdf = geopandas.GeoDataFrame(
    df, geometry=geopandas.points_from_xy(df.Longitude, df.Latitude))

gdf.explore()
```

#### Problem description

The map tiles do not show up correctly with `explore() ` if I create a geopandas dataframe from scratch. The scale seems off as well.
It works if I use the geopandas dataset 'cities' or if I pass a map element, e.g. with:

```python
map_1 = folium.Map(location=[41.90328, 12.45339], zoom_start=7,control_scale = True)
L.explore(m=map_1)
``` 

#### Expected Output

![first](https://user-images.githubusercontent.com/38214982/144763027-182f1b77-3844-417c-8dd5-d086b78cd0b3.png)

#### Output of ``geopandas.show_versions()``

<details>

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

SYSTEM INFO
-----------
python     : 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]
executable : /usr/bin/python3
machine    : Linux-5.10.0-1008-oem-x86_64-with-glibc2.29

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.0
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.3.0
GDAL data dir: /home/sergio/.local/lib/python3.8/site-packages/fiona/gdal_data
PROJ       : 7.2.0
PROJ data dir: /home/sergio/.local/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.4
fiona      : 1.8.20
numpy      : 1.19.5
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.0.0.post1
matplotlib : 3.3.3
mapclassify: 2.4.3
geopy      : 2.2.0
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

**Comment by martinfleis** [comment]
Hi, thanks for the report.

This is not a bug though, this is expected behaviour. When you create your GeoDataFrame from scratch, you need to specify the CRS of your geometry column. Otherwise, geopandas assumes it is a naive geometry and doesn't know where on the Earth it is. Once you correctly specify EPSG:4326 as your CRS, the map loads as it supposed to.

```py
L = geopandas.GeoDataFrame(crs=4326)
L['name'] = ['Vatican City', 'San Marino']
L['geometry'] = [shapely.geometry.Point(12.45339, 41.90328),
                 shapely.geometry.Point(12.44177, 43.93610)]
L.explore()
```

or 

```py
df = pandas.DataFrame(
    {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
     'Country': ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Venezuela'],
     'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
     'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})
gdf = geopandas.GeoDataFrame(
    df, geometry=geopandas.points_from_xy(df.Longitude, df.Latitude, crs=4326))

gdf.explore()
```

The reason it works with `folium.Map` is that it requires 4326, while GeoDataFrame doesn't assume a CRS.

**Comment by sergiocaccamo** [comment]
I see, many thanks. Perhaps add a comment in the interactive plotting documentation? The connection to what is written in "Managing Projections" is not so direct and it would not hurt to remind users (like myself) how to properly use explore()

**Comment by martinfleis** [comment]
> Perhaps add a comment in the interactive plotting documentation?

Coming up in #2255
