### ISSUE TITLE
QST: how to get the matpltolib artist created with `gdf.plot()`

### ISSUE THREAD

**Issue by raphaelquast** [geopandas/geopandas#2261]
- [x] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

#### Question about geopandas

OK... my question is quite simple but I can't seem to find any hints (except for searching around in the source-code of geopandas...) so I thought I'll give it a try in here first:

Is there a general way to obtain the matpltolib `artist` created on a call to `GeoDataFrame.plot()` ?
(I'm asking because I'm in the process of developing a plotting library [EOmaps](https://github.com/raphaelquast/EOmaps) and I'd really like to make the features compatible with geopandas)

here's a quick example of what I mean:
```python
import geopandas as gpd
gdf = gpd.GeoDataFrame(dict(a=[1,2,3]), 
                       geometry=gpd.points_from_xy([1,2,3], [1,2,3]))

ax = gdf.plot()
# in this case I could get the actual artist via... 
# (but that does not seem very reliable)
artist = ax.collections[0]
```

**Comment by martinfleis** [comment]
Well, that is not that easy as it may sound. GeoPandas is able to plot different geometry types and each type is plotted as a collection. So it may return a single collection as it does in your case above but it can also return three collections within the same axis.

```py
import geopandas
from shapely.geometry import Point, LineString, Polygon

df = geopandas.GeoDataFrame(
    geometry=[
        Point(0, 0),
        LineString([(1, 1), (2, 2)]),
        Polygon([(3, 3), (3, 2), (2, 2), (2, 3)])
    ]
)
ax = df.plot()
ax.collections

[<matplotlib.collections.PatchCollection at 0x15e306dc0>,
 <matplotlib.collections.LineCollection at 0x15e260ee0>,
 <matplotlib.collections.PathCollection at 0x107674bb0>]
```

You can't reliably get the whole geopandas plot as a single artist as it is not just one. Does that answer your question?

**Comment by raphaelquast** [comment]
@martinfleis thanks for the quick response!
yes I expected that it's not always a single collection... I could deal with that...
what I am searching for is a method to access all the collections that have been added to a plot using `gdf.plot()`
(with the possibility that there are already several collections present on the axis...)

Basically I was hoping that there might be a simpler way to get the artists than identifying all new objects in `ax.collections`
...and I'm not sure if this would really cover all artists? (e.g. do you always use collections no matter what? )

**Comment by martinfleis** [comment]
Hmm, that is tricky. It would help if `matplotlib` allowed us to add a custom ID to collections but I am not sure that is possible.

We always use collections and it is always between 1 and 3 collections per `plot` call, depending on the geometry types present in the GeoDataFrame. 

Legends are treated separately but their handling will likely change anyway with #2012

**Comment by raphaelquast** [comment]
Danm... it was worth a try...
The good thing is I'm only interested in the collections (I intend to make them a bit more interactive)
so if I can be certain that geopandas always uses collections then I'll just stick to a check of newly added collections
to identify the artists for now...

Thanks a lot for your insights and keep up the awesome work with geopandas!
