### ISSUE TITLE
BUG: explore() ignores 'popup' argument

### ISSUE THREAD

**Issue by MiguelonGonzalez** [geopandas/geopandas#2266]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Code Sample:

```python
import geopandas

world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))

world.explore(popup='name')
```

#### Problem description:

I have been working with explore  method since a few weeks, and I haven't been able of making it work with the 'popup' method. As seen in the output figure, despite popup is set to only show the name of the countries, all the information is shown.
Since I think this is a bug, I report it like that, althoug you can take the freedom for categorizing it as you consider.

Thank you very much.

#### Expected Output:

Only showing countries names.

#### Output:

![example](https://user-images.githubusercontent.com/75794654/146359188-ea807777-53e8-4870-9ebf-e15937e0417f.png)

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\MiguelGonzalez\Anaconda3\envs\DANA\python.exe
machine    : Windows-10-10.0.19042-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.0.2
GDAL data dir: None
PROJ       : 6.2.1
PROJ data dir: C:\Users\MiguelGonzalez\Anaconda3\envs\DANA\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.2
fiona      : 1.8.13.post1
numpy      : 1.20.3
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 2.6.1.post1
matplotlib : 3.4.2
mapclassify: 2.4.3
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

**Comment by martinfleis** [comment]
Hi, what you show on the screenshot is a `tooltip` not a `popup`. `popup` is a bubble that shows up if you click on the geometry. So I guess that you want to do

```py
world.explore(tooltip='name')
```
