### ISSUE TITLE
BUG:CRSError: Invalid projection: epsg:3857: (Internal Proj Error: proj_create: no database context specified)

### ISSUE THREAD

**Issue by kleikemper** [geopandas/geopandas#2270]
#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely.geometry import Point
```
Jupyter Notebook response:
C:\Users\...\anaconda3\envs\geopandas\lib\site-packages\pyproj\__init__.py:89: UserWarning: pyproj unable to set database path.
  _pyproj_global_context_initialize()

```python
gdf = gpd.GeoDataFrame([Point(1,1)])
gdf.set_geometry(0).set_crs(epsg=3857)
```
Jupyter Notebook response:
CRSError: Invalid projection: epsg:3857: (Internal Proj Error: proj_create: no database context specified)

#### Problem description

Since updating geopandas last week, setting a crs produces the posted error. Moreover, when importing the package, the above shown warning is produced.

I tried installing only geopandas from conda - forge in a complete new environment, still the same.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.1 | packaged by conda-forge | (main, Dec 19 2021, 15:33:35) [MSC v.1929 64 bit (AMD64)]
executable : C:\Users\Jan Kleikemper\anaconda3\envs\geopandas\python.exe
machine    : Windows-10-10.0.19042-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.4.0
GDAL data dir: None
PROJ       : 8.2.0
PROJ data dir: C:\Program Files\PostgreSQL\14\share\contrib\postgis-3.1\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.5
fiona      : 1.8.20
numpy      : 1.21.4
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.3.0
matplotlib : 3.5.1
mapclassify: 2.4.3
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None
</details>

**Comment by martinfleis** [comment]
This is an issue with `pyproj` package. They even cover this exact error in their documentation: https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select. Your `pyproj` points to a database created for a different version. You need to specify the path to a correct data directory (see the docs). Proper reinstallation also often helps. 

See also #1887

Your PROJ path is pointing to your PostGIS installation `C:\Program Files\PostgreSQL\...` not the one coming with pyproj.

**Comment by kavyajeetbora** [comment]
Thanks @martinfleis I had the same issue. My application was running in my system but not in remote machine as it had postgis installed in it and PROJ path was redirected to `C:\Program Files\PostgreSQL\...`
I overcame with this simple import in my code:
```
import geopandas as gpd
import pyproj
pyproj.datadir.set_data_dir('C:\\Users\\<USERNAME>\\Anaconda3\\envs\\geospatial_env\\Library\\share\\proj') ## set the pyproj data directory

Application code.....
```
**Reinstallation of the packages was not required.** 

Also as it  is mentioned in the [docs](https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select):
- To get data directory being used: [pyproj.datadir.get_data_dir()](https://pyproj4.github.io/pyproj/stable/api/datadir.html#pyproj.datadir.get_data_dir)
- The order for searching for the data directory can be found in the docstrings of [pyproj.datadir.get_data_dir()](https://pyproj4.github.io/pyproj/stable/api/datadir.html#pyproj.datadir.get_data_dir)
- To change the data directory: [pyproj.datadir.set_data_dir()](https://pyproj4.github.io/pyproj/stable/api/datadir.html#pyproj.datadir.set_data_dir)

**Comment by bchardon** [comment]
If `pyproj.datadir.get_data_dir()` return the correct path but you still get the error then you can temporarily overwrite the PROJ_LIB variable with:

`os.environ['PROJ_LIB'] = pyproj.datadir.get_data_dir()`
