### ISSUE TITLE
BUG: GeoDataFrame.explode() breaks relationship between index and columns

### ISSUE THREAD

**Issue by William-of-Penge** [geopandas/geopandas#2271]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of geopandas.

---

#### Simple example:

```python
from shapely.geometry import GeometryCollection, Point
import geopandas as gpd

geom = gpd.GeoSeries([GeometryCollection([Point((0, i)), 
                                          Point((1, i))]) for i in range(3)])
gdf = gpd.GeoDataFrame(geometry=geom, crs='EPSG:27700') 
gdf['id'] = [2, 9, 7]
gdf['x'] = [1, 2, 3]
gdf = gdf.set_index('id')
print(gdf)
x = gdf.explode(index_parts=True)
print(x)
```

Output:
```
                                             geometry  x
id                                                      
2   GEOMETRYCOLLECTION (POINT (0.000 0.000), POINT...  1
9   GEOMETRYCOLLECTION (POINT (0.000 1.000), POINT...  2
7   GEOMETRYCOLLECTION (POINT (0.000 2.000), POINT...  3

      x             geometry
id                          
2  0  1  POINT (0.000 0.000)
   1  1  POINT (1.000 0.000)
9  0  3  POINT (0.000 2.000)
   1  3  POINT (1.000 2.000)
7  0  2  POINT (0.000 1.000)
   1  2  POINT (1.000 1.000)
```
Note the values in column `x` in the rows where index level `id` is 9 or 7 in the exploded GeoDataFrame as compared to the original.

#### Problem description

In the GeoDataFrame returned by `explode` in the example above, I would expect values in rows produced by exploding a row `r`, to match the values in row `r` for each column apart from the geometry column. So, in the example above, I would expect the output of the second print statement to be:

```
      x             geometry
id                          
2  0  1  POINT (0.000 0.000)
   1  1  POINT (1.000 0.000)
9  0  2  POINT (0.000 2.000)
   1  2  POINT (1.000 2.000)
7  0  3  POINT (0.000 1.000)
   1  3  POINT (1.000 1.000)
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.5 (default, Nov 18 2021, 16:00:48)  [GCC 10.3.0]
executable : /home/william/venvs/std/bin/python3
machine    : Linux-5.15.5-76051505-generic-x86_64-with-glibc2.33

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.3.0
GDAL data dir: /home/william/venvs/std/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 8.2.0
PROJ data dir: /home/william/venvs/std/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.4
fiona      : 1.8.20
numpy      : 1.21.4
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.3.0
matplotlib : 3.5.0
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

**Comment by martinfleis** [comment]
Thanks! I can confirm that this is a bug. Fix is coming up in #2292.
