### ISSUE TITLE
i have successfully solved this error , by running the following commands;

### ISSUE THREAD

**Issue by MosesKitikuKioko** [geopandas/geopandas#2273]
i have successfully solved this error , by running the following commands;
     OSError: could not find or load spatialindex_c-64.dll

		First run these 3 commands; in your environment
		install pygeos --channel conda-forge
		conda update python
		conda install scikit-learn-intelex

then refresh or restart the program, and you will smile.

_Originally posted by @mugumya21 in https://github.com/geopandas/geopandas/issues/1812#issuecomment-997395333_

**Comment by MosesKitikuKioko** [comment]
The problem seems to be far from being solved

**Comment by martinfleis** [comment]
Hi, thanks for reporting an issue. However, we'll need a bit more to be able to help.

If you are referring to the PyInstaller issue, then this still applies:

> None of the current geopandas maintainers has an experience with PyInstaller so we'll need help from someone who does. At the same time, this issue is not directly with GeoPandas but with rtree so you may want to try your luck there. There's not much we can do about it anyway.

If not, please open a new issue following the issue template. That way, we may be able to understand your problem and eventually fix it.
