### ISSUE TITLE
QST: applying to_crs to revert back to the original geometry results in a different output

### ISSUE THREAD

**Issue by ankitkariryaa** [geopandas/geopandas#2285]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python

import geopandas as gpd
from shapely.geometry import box

def convert_to_crs(bb, from_crs, to_crs):
    gdf = gpd.GeoDataFrame({'geometry': [box(*bb)]}).set_crs(from_crs)
    gdf = gdf.to_crs(to_crs)
    return gdf['geometry'].iloc[0].bounds

bb_4326 = (4.92040911273281, 23.918686706996947, 4.9229565352741504, 23.92102923471972)
epsg4326 = 'EPSG:4326'
epsg32631 = 'EPSG:32631'
bb_4326_32631 = convert_to_crs(bb_4326, epsg4326, epsg32631)
bb_4326_32631_4326 = convert_to_crs(bb_4326_32631, epsg32631, epsg4326)
bb_4326_32631_4326_32631 = convert_to_crs(bb_4326_32631_4326, epsg4326, epsg32631)

print(bb_4326)
print(bb_4326_32631)
print(bb_4326_32631_4326)
print(bb_4326_32631_4326_32631)

#(4.92040911273281, 23.918686706996947, 4.9229565352741504, 23.92102923471972)
#(695470.6181154198, 2646552.588910112, 695733.5075191372, 2646815.563595417)
#(4.9203744754349446, 23.918654856670923, 4.922991219160982, 23.92106108744408)
#(695467.0436709167, 2646549.0133930403, 695737.0868316881, 2646819.1395154255)
```

#### Problem description

Please excuse my naiveness, but IMHO converting to_crs should be a reversible operation. I know that GIS is hard, and EPSG:4326 is a geographic coordinate system and EPSG:32631 is a projected coordinate reference system. While I expected such difference when working with orthorectified raster data, I am surprised to see it in case of vector data (maybe due to my lack of knowledge or experience). In any case, the bug is that gpd doesn't warn about this potentially unwanted behavior nor does the documentation for  [to_crs](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.to_crs.html#geopandas.GeoDataFrame.to_crs) mention any thing in this regard. 

#### Expected Output

Same as the original value.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.6 | packaged by conda-forge | (default, Jan 25 2021, 23:21:18)  [GCC 9.3.0]
executable : /home/ankit/miniconda3/envs/tfgdal/bin/python
machine    : Linux-5.4.0-91-generic-x86_64-with-glibc2.10

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.0
GEOS lib   : /home/ankit/miniconda3/envs/tfgdal/lib/libgeos_c.so
GDAL       : 3.1.4
GDAL data dir: /home/ankit/miniconda3/envs/tfgdal/share/gdal
PROJ       : 8.2.0
PROJ data dir: /home/ankit/miniconda3/envs/tfgdal/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.0
fiona      : 1.8.18
numpy      : 1.21.2
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.3.0
matplotlib : 3.3.4
mapclassify: 2.4.3
geopy      : 2.1.0
psycopg2   : 2.9.1 (dt dec pq3 ext lo64)
geoalchemy2: 0.9.4
pyarrow    : None
pygeos     : None

</details>

**Comment by martinfleis** [comment]
Hi,

you are right that the reprojecting coordinates back and forth should return exactly the same value. And it indeed does. However, you are not reprojecting coordinates but the bounding box. When you reproject a rectangle between these two projections, it becomes slightly rotated (see the fig below). What you do in your snippet above is not reprojecting the same rectangle back, but reprojecting its bounding box. Which in this case is, naturally, a different rectangle. That is why you are getting different values. This stuff is complicated, hope it is clearer now.

```py
gdf = gpd.GeoDataFrame({'geometry': [box(*bb_4326)]}).set_crs(4326)
gdf.plot()
```
<img width="298" alt="Screenshot 2022-01-03 at 19 56 18" src="https://user-images.githubusercontent.com/36797143/147974150-d5d7f92f-77a0-4fea-b139-b98491567a43.png">

```py
gdf.to_crs(epsg32631).plot()
```
<img width="273" alt="Screenshot 2022-01-03 at 19 56 37" src="https://user-images.githubusercontent.com/36797143/147974184-a3aa2b44-84ed-4eee-a493-6759bf808c6f.png">

With the bounding box:
```py
gdf = gdf.to_crs(epsg32631)
ax = gdf.plot()
gpd.GeoSeries([box(*gdf['geometry'].iloc[0].bounds)]).plot(ax=ax, facecolor="none", edgecolor="r", linewidth=1)
```
<img width="270" alt="Screenshot 2022-01-03 at 19 58 44" src="https://user-images.githubusercontent.com/36797143/147974371-02752e17-da0e-4b37-b6ae-72f614605686.png">

And reprojected bounding box overlayed over the original geometry:

```py
ax = gpd.GeoDataFrame({'geometry': [box(*bb_4326)]}).set_crs(4326).plot()
gpd.GeoSeries([box(*gdf['geometry'].iloc[0].bounds)], crs=epsg32631).to_crs(4326).plot(ax=ax, facecolor="none", edgecolor="r", linewidth=1)
```
<img width="300" alt="Screenshot 2022-01-03 at 20 00 19" src="https://user-images.githubusercontent.com/36797143/147974500-2de96e91-568f-48f7-bdfc-7cd186f02ddd.png">

**Comment by ankitkariryaa** [comment]
Hey, 

Thanks for the great explanation! I didn't realize that rectangle != bounds.
