### ISSUE TITLE
BUG: GeoDataFrame object has no attribute 'sjoin'

### ISSUE THREAD

**Issue by vovchykbratyk** [geopandas/geopandas#2290]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd

shp_a = 'path/to/shp_a.shp'
shp_b = 'path/to/shp_b.shp'

gdf_a = gpd.read_file(shp_a)
gdf_b = gpd.read_file(shp_b)

joined = gdf_a.sjoin(gdf_b, how="inner", predicate='intersects')

```

#### Problem description

AttributeError: 'GeoDataFrame' object has no attribute 'sjoin'

#### Expected Output

not an AttributeError, according to https://geopandas.org/en/stable/docs/user_guide/mergingdata.html

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
executable : C:\Anaconda3\envs\foss4g\python.exe
machine    : Windows-10-10.0.22000-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.3.2
GDAL data dir: None
PROJ       : 8.0.1
PROJ data dir: C:\Anaconda3\envs\foss4g\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.3.5
fiona      : 1.8.20
numpy      : 1.22.0
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.3.0
matplotlib : 3.5.1
mapclassify: 2.4.3
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : 0.10.2

</details>

**Comment by akrherz** [comment]
You are using GeoPandas=0.9.0 and reading current release documentation.  See this [changelog entry for 0.10.0 release](https://geopandas.org/en/latest/docs/changelog.html#version-0-10-0-october-3-2021)

**Comment by martinfleis** [comment]
Thanks @akrherz! `GeoDataFrame.sjoin` is indeed a new feature in geopandas 0.10.

**Comment by vovchykbratyk** [comment]
My bad! Sorry for wasting your time.
