### ISSUE TITLE
BUG: Unexpected behavior with GeoDataFrame constructor when passing data=DataFrame with pandas >= 1.3.0 

### ISSUE THREAD

**Issue by spolloni** [geopandas/geopandas#2301]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.
---

Since pandas 1.3.0 the `DataFrame` constructor [honors `copy=False`](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.3.0.html#dataframe-constructor-honors-copy-false-with-dict) when a `DataFrame` is passed as an argument for `data`. This makes sense as a default for pandas but it seems odd that the GeoDataFrame inherits this behavior, since it will modify an argument of a different type.

```
>>> import pandas as pd 
>>> import geopandas as gpd 
>>> 
>>> df = pd.DataFrame(((1,2),(3,4)), columns=['x', 'y'])
>>> gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df.x, df.y))
>>> df
   x  y                 geometry
0  1  2  POINT (1.00000 2.00000)
1  3  4  POINT (3.00000 4.00000)
>>> df._mgr is gdf._mgr
True
```

**Comment by martinfleis** [comment]
I believe this is the same issue as #1179.

**Comment by spolloni** [comment]
It is indeed, closing as duplicate. Thanks @martinfleis .
