### ISSUE TITLE
ENH: custom aggregation functions in GeoDataFrame.dissolve() 

### ISSUE THREAD

**Issue by vidlb** [geopandas/geopandas#2308]
Juste something to improve the documentation.

Right now, when reading geopandas doc for `dissolve`, it seems like `aggfunc` can't be anything else than a function or str in ('first', 'sum', 'max', ...).
> Aggregation function for manipulation of data associated with each group. Passed to pandas groupby.agg method.

According to pandas doc, it is possible to pass a dictionary to `DataFrameGroupBy.aggregate()` thus allowing user to apply different functions to each column. I found it quite convenient when using `dissolve`, moreover it will return only specified columns (names in dict.keys()).

So It would be nice to add these informations (from [pandas doc](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html)) : 

> Function to use for aggregating the data. If a function, must either work when passed a DataFrame or when passed to 
 DataFrame.apply.
> Accepted combinations are:
> - function
> - string function name
> - list of functions and/or function names, e.g. [np.sum, 'mean']
> - dict of axis labels -> functions, function names or list of such.

**Comment by martinfleis** [comment]
We have just merged this exact thing yesterday in #2303. You can see the new version here https://geopandas.org/en/latest/docs/user_guide/aggregation_with_dissolve.html#dissolve-arguments
