### ISSUE TITLE
Q: controlling alpha for every element in `plot_polygon`?

### ISSUE THREAD

**Issue by darribas** [geopandas/geopandas#232]
I've noticed that the `alpha` parameter in `plot_polygon` is not applied to every element of the plotted geom. In particular, the boundaries get drawn in [L. 20](https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L20) and [L. 23](https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L23) without modifying their transparency. Is this coded in this way for a particular reason? If transparency was modified in every element, including borders, it'd make possible to plot layers as simple shapes, whithout being able to tell the different polygons that make up the layer which, in some cases, is useful to provide a contextual layer. The only way in which the change would affect the current behaviour is that, with a low enough alpha, borderlines could potentially be hard to tell apart. However this can be solved by plotting on top a boundary layer only. I think this change would add more flexibility to the method.

If this is something that would be postively received, I'm happy to put it into a PR myself.

**Comment by darribas** [comment]
Nevermind, just ran into [this post](http://stackoverflow.com/questions/28398200/matplotlib-plotting-transparent-histogram-with-non-transparent-edge). Since you can pass RGBA tuples to both edge and face color attributes, this already gives you that flexibility. Closing for now.

**Comment by StevenLi-DS** [comment]
@darribas I'm sorry. I didn't find the code in the post you linked. Is there any way to change the alpha of the edge in the `.plot()`?

**Comment by StevenLi-DS** [comment]
seems like just set `facecolor='none'` and then the alpha will only apply to the `edgecolor`
`gdf.plot(facecolor='none', alpha=0.2, edgecolor='k')`
