### ISSUE TITLE
ENH: prefer min_zoom and max_zoom arguments instead of tile metadata in explore()

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2325]
#### Is your feature request related to a problem?

Right now, `xyzservices.TileProvider` metadata overrides `min_zoom` and `max_zoom` arguments and there's essentially no way around it without changing the provider.

#### Describe the solution you'd like

I believe that the preference should be the other way, i.e. if a user specifies `max_zoom`, it should be kept as is and not changed by tiles.

#### API breaking implications

None as far as I can tell

#### Describe alternatives you've considered

You can change tile metadata but that breaks other things in leaflet.

#### Additional context

These two lines need to check if each of the keywords is already present in the `map_kwds` dict and leave it as it is in that case.

https://github.com/geopandas/geopandas/blob/76e886ec23ddd12a032c933ab08b18693a8144a1/geopandas/explore.py#L331-L332

**Comment by soma2000-lang** [comment]
@martinfleis  I would like to work on this.Please assignme this

**Comment by martinfleis** [comment]
@soma2000-lang Consider it done, I can't do that technically on GitHub. Thanks!

**Comment by kapoor1992** [comment]
Saw this one was open for a while and submitted a PR @martinfleis.
