### ISSUE TITLE
TST: assert_geodataframe_equal checks non active geometry columns twice

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#2333]
https://github.com/geopandas/geopandas/blob/a80081e52ed3bd069a75a4caaed44e45e35c647d/geopandas/testing.py#L318-L333

checks non active geometry columns twice. We should be able to drop all columns of geometrydtype for left2 and right2.

**Comment by martinfleis** [comment]
Ah, yes. Because those get passed to the `assert_frame_equal` below and check with pandas. This most likely pre-dates the ability to have multiple geometry columns, we should adapt that. Does that cause any issues apart from checking the column twice?

**Comment by m-richards** [comment]
Not in my use case - I thought it did which is how I found those columns weren't being dropped, but I actually had other extension arrays (datetimes) causing the assertion to fail.
