### ISSUE TITLE
DOC: add a section about supported formats of geopandas.read_file to user_guide/io.html

### ISSUE THREAD

**Issue by RadMagnus** [geopandas/geopandas#2336]
Following the gitter thread of @jorisvandenbossche & @RadMagnus:

* [ ] add a section on the https://geopandas.org/en/stable/docs/user_guide/io.html page that explains in more detail how to check which formats are supported by geopandas.read_file
* [ ] explain how to change fiona/drvsupport.py on runtime to include supported drivers that are commented out

**Comment by soma2000-lang** [comment]
Please assign me this issue.I want to work on this issue

**Comment by RadMagnus** [comment]
Already on it. See the gitter channel: https://gitter.im/geopandas/geopandas
But there's other open DOC issues that need care :)

**Comment by soma2000-lang** [comment]
Ok
