### ISSUE TITLE
BUG: pandas FutureWarning when calling to_file() method 

### ISSUE THREAD

**Issue by leuchtum** [geopandas/geopandas#2337]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely.geometry import Point

dummy_data = {"dummy": "data", "geometry": Point(0, 0)}
gdf = gpd.GeoDataFrame.from_records([dummy_data])

gdf.to_file("./dummy.shp")
```

This code delivers:

```
/.../python3.10/site-packages/geopandas/io/file.py:362: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  pd.Int64Index,

```
#### Problem description
`to_file()` method produces a pandas FutureWarning

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:30:18) [Clang 11.1.0 ]
executable : /opt/homebrew/Caskroom/miniconda/base/envs/ebahnen/bin/python
machine    : macOS-12.1-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.10.2
GEOS lib   : /opt/homebrew/Caskroom/miniconda/base/envs/ebahnen/lib/libgeos_c.dylib
GDAL       : 3.4.1
GDAL data dir: /opt/homebrew/Caskroom/miniconda/base/envs/ebahnen/share/gdal
PROJ       : 8.2.1
PROJ data dir: /opt/homebrew/Caskroom/miniconda/base/envs/ebahnen/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.4.0
fiona      : 1.8.20
numpy      : 1.22.1
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.3.0
matplotlib : 3.5.1
mapclassify: 2.4.3
geopy      : 2.2.0
psycopg2   : None
geoalchemy2: None
pyarrow    : 6.0.1
pygeos     : None

</details>

**Comment by martinfleis** [comment]
Thanks for the report! We have already picked this and it was fixed in #2322. The next release of geopandas will not raise these warnings anymore.
