### ISSUE TITLE
DOC: binder tutorial won't launch

### ISSUE THREAD

**Issue by thomasastanley** [geopandas/geopandas#2338]
- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

I went to https://geopandas.org/en/stable/getting_started/introduction.html. On a whim, I clicked the binder launcher at the top, which goes to https://mybinder.org/v2/gh/geopandas/geopandas/master?urlpath=lab/tree/doc/source/getting_started/introduction.ipynb

#### Problem description

It gave me this error message:
Error loading geopandas/geopandas/master!
See logs below for details.

#### Expected Output

it should take me to: https://mybinder.org/v2/gh/geopandas/geopandas/main?urlpath=lab/tree/doc/source/getting_started/introduction.ipynb

<details>

Could not resolve ref for gh:geopandas/geopandas/master. Double check your URL. GitHub recently changed default branches from "master" to "main". Did you mean the "main" branch?

</details>

**Comment by m-richards** [comment]
Thanks for pointing this out!

This has actually already been fixed as part of #2277, but only when viewing the latest version of the docs (https://geopandas.org/en/latest/getting_started/introduction.html) rather than stable. We should perhaps look at updating this link across versions of the documentation as well.

**Comment by martinfleis** [comment]
> We should perhaps look at updating this link across versions of the documentation as well.

I don't think that can be easily done.

**Comment by martinfleis** [comment]
I'll close this as the link on `stable` will fix itself when we cut a release.
