### ISSUE TITLE
plot_multipolygon() does not support label arguement

### ISSUE THREAD

**Issue by Casyfill** [geopandas/geopandas#234]
which is sad as I wanted to plot grouped polygons with same color and correct representation in legend

**Comment by jorisvandenbossche** [comment]
Can you specify what you mean? 

If you have a column with those labels, you can specify `column='col_name'` to use those values for coloring and for the legend.

**Comment by nejohnson2** [comment]
I understand the title of this issue to be the same as a problem I'm having.  I'd like to be able to apply a title to my legend but the ```geodataframe.plot()``` does not take ```label``` as an argument.  Is this a bug or am I missing the proper way to apply a title to a legend?  Thanks!!

```python
all_data.plot(column='CT2010', categorical=True, legend=True, label='CT')
plt.legend(label='CT', title="Legend Title")
plt.title('Census Tract 2010')
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-468-77900e86f0b9> in <module>()
----> 1 all_data.plot(column='CT2010', categorical=True, legend=True, lab='CT')
      2 plt.legend(label='CT', title="CT")
      3 plt.title('Census Tract 2010')

/usr/local/lib/python2.7/site-packages/geopandas/geodataframe.pyc in plot(self, *args, **kwargs)
    430 
    431     def plot(self, *args, **kwargs):
--> 432         return plot_dataframe(self, *args, **kwargs)
    433 
    434 

/usr/local/lib/python2.7/site-packages/geopandas/plotting.pyc in plot_dataframe(s, column, colormap, linewidth, categorical, legend, axes, scheme, k, vmin, vmax, figsize, **color_kwds)
    242         for geom, value in zip(s.geometry, values):
    243             if geom.type == 'Polygon' or geom.type == 'MultiPolygon':
--> 244                 plot_multipolygon(ax, geom, facecolor=cmap.to_rgba(value), linewidth=linewidth, **color_kwds)
    245             elif geom.type == 'LineString' or geom.type == 'MultiLineString':
    246                 plot_multilinestring(ax, geom, color=cmap.to_rgba(value), linewidth=linewidth)

TypeError: plot_multipolygon() got an unexpected keyword argument 'label'
```

**Comment by jorisvandenbossche** [comment]
@nejohnson2 Generally, `label` in matplotlib plotting methods is not supposed to be a legend 'title', but the label of one of the legend 'elements'. 
If I understand your notion of 'title' correctly, I think you want something like this: http://nbviewer.ipython.org/gist/jorisvandenbossche/2051142d648fc9ca1ca3

**Comment by nejohnson2** [comment]
Thanks.  Exactly what I was looking for.  Thanks for the explanation.

**Comment by martinfleis** [comment]
Multi-part geometry now propagates color to every part correctly, so I assume that the original issue is resolved.

Second question is already answered above. Closing.
