### ISSUE TITLE
BUG: plot_clip example not working

### ISSUE THREAD

**Issue by maxymczech** [geopandas/geopandas#2341]
This code `https://github.com/geopandas/geopandas/blob/main/doc/source/gallery/plot_clip.ipynb` produces  this error

> TypeError: '>=' not supported between instances of 'float' and 'Polygon'

On this line:

> world_clipped = world.clip(polygon)

**Comment by martinfleis** [comment]
Hi, the example works correctly on my side. How do you create an environment with geopandas (how was it installed)? Can you show what `geopandas.show_versions()` outputs?

**Comment by maxymczech** [comment]
@martinfleis Thank you for your quick response. Here is the output:

```
SYSTEM INFO
-----------
python     : 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
executable : /opt/conda/bin/python
machine    : Linux-4.15.0-166-generic-x86_64-with-glibc2.10

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.1
GEOS lib   : /opt/conda/lib/libgeos_c.so
GDAL       : 3.2.1
GDAL data dir: /opt/conda/share/gdal
PROJ       : 7.2.0
PROJ data dir: /opt/conda/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.1.1
fiona      : 1.8.18
numpy      : 1.20.3
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 3.0.1
matplotlib : 3.3.4
mapclassify: 2.4.3
geopy      : 2.0.0
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None
```

**Comment by martinfleis** [comment]
You need geopandas 0.10 or newer to use that example. Version 0.9 tries to use pandas version of the `clip` method that is not supported on GeoSeries. Within this environment, you can use older function-based API. See https://geopandas.org/en/v0.9.0/gallery/plot_clip.html
