### ISSUE TITLE
ENH: more parameters setting in .buffer() (unit, dissolve, shape preserving option)

### ISSUE THREAD

**Issue by luyuliu** [geopandas/geopandas#2342]
#### Is your feature request related to a problem?

I wish to create dissolved buffers (shape preserved) for point features, which have many points (10k+). The solution I have right now is too slow (see below).

#### Describe the solution you'd like

Add a parameter of unit and planar/geodesic in .buffer() and increase performance. I understand the computation-intentive nature of this problem.

#### API breaking implications

I do not know. I guess this will change the code in a very fundamental way.

#### Describe alternatives you've considered

My current solution is: 1) projecting the whole feature to a state plane meter-based projection; 2) do the buffer operation according to a field in the gdf; 3) dissolve.

The performance is not ideal. I benchmarked a little bit with a single batch (there can be 10k + batches to run), see the code below. The projection step is very time-consuming. I am thinking about a compromise solution that I use degree and planar to produce the buffer in WGS84, but the outcome's accuracy would also be compromised.

Please let me know if you have better solution based on the current state of the library. Thank you very much!

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
df = pd.DataFrame(data, columns = columnsHead)  
geometry = [Point(xy) for xy in zip(df.lon, df.lat)]
df = df.drop(['lon', 'lat'], axis=1)   # 0.12s
gdf = gpd.GeoDataFrame(df, crs="EPSG:4326", geometry=geometry) # 0.32s
gdf_p = gdf.to_crs("EPSG:32123") # 0.59 s
buffers = gdf_p.buffer(distance=df[buffer_field]) # 0.31 s
buffer_gdf = gpd.GeoDataFrame(geometry=buffers) # 0.00 s
buffer_gdf_dissolve = buffer_gdf.dissolve() # 0.43 s
```

**Comment by martinfleis** [comment]
Thanks for the suggestion but I don't think this will happen anytime soon.

1) doing buffers as a spherical operation requires a geometry engine than can do that. GeoPandas currently use GEOS that assumes planar geometry. It may become possible in future with the work being discussed in #2098 and https://github.com/geopandas/community/issues/10
2) make sure you have `pygeos` and recent `pyproj` installed for faster reproduction
3) try switching the order of buffer and dissolve. See the following snippet that uses the underlying methods directly.

```py
import geopandas
import numpy

points = geopandas.GeoSeries().from_xy(
    x=numpy.random.randint(0, 1000, 100),
    y=numpy.random.randint(0, 1000, 100)
)

%%timeit
points.unary_union.buffer(50)

1.91 ms ± 17.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%%timeit
points.buffer(50).unary_union

6.45 ms ± 71.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
