### ISSUE TITLE
Include classifiers other than those that require a `k` argument in PySAL

### ISSUE THREAD

**Issue by darribas** [geopandas/geopandas#235]
Currently, the argument "scheme" in `plot_dataframe` provides and extremely easy and useful interface to some of the classifiers in PySAL for choropleths. However, there are some that, because they do not require `k`, are not hooked up and using them is currently not as straightforward as it should (e.g. box maps, std mean, Max-P, etc.). This also means probably that users will have a bias towards those implemented because they are easier to create. It would be great to use a similar approach as @sjsrey took originally to provide access to the remaining classifiers in PySAL.

**Comment by jorisvandenbossche** [comment]
I think that would be a good idea. @darribas Do you have a proposal for how the API could look like?

In principle adding support for more classifiers using the string-argument approach is not difficult, they just have to be added in the mapping here https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L292. 
At least, that is simple for using their default configuration. But the question, how can we easily handle all the potential different keywords to the different classifiers, which is more difficult with the current api.

**Comment by darribas** [comment]
Not sure at this moment. On top of my head, since the parameter names are pretty specific to the map classification (e.g. hinge, multiples...), we could allow for a `**mapclassify_kwds`, mirroring `**color_kwds`?

As an alternative that would be good as a general case, is to have a clear and easy API for a "user defined" binning that works well with that of PySAL in [l.1450](https://github.com/pysal/pysal/blob/master/pysal/esda/mapclassify.py#L1450). This would allow to create all those combinations outside of `plot_geodataframe` and pass them directly, with all the details being taken care by the plotting machinery (legend, etc.).

Does any of these sound reasonable? Happy to iterate and discuss.

**Comment by jdmcbr** [comment]
Closed by #876
