### ISSUE TITLE
DOC: document saving a GeoDataFrame with more GeoSeries to a file

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2357]
GeoDataFrame could have multiple GeoSeries but most of the traditional GIS file formats do not support that. It would be nice to have an example showing how to do that by converting remaining columns to WKT or WKB. See https://github.com/geopandas/geopandas/pull/1500 for a relevant discussion.

**Comment by soma2000-lang** [comment]
@martinfleis  working on this

**Comment by Abdullium** [comment]
> @martinfleis working on this

Hi, Is @martinflei still working on this, 
if not then please assign the issue to me  
I have been doing geo data projects for a while,
I think I can fix it

**Comment by Abdullium** [comment]
> GeoDataFrame could have multiple GeoSeries but most of the traditional GIS file formats do not support that. It would be nice to have an example showing how to do that by converting the remaining columns to WKT or WKB. See #1500 for a relevant discussion.

i think can definitely fix the documentation in hours .
would you assign the issue to me 
while you work on something more important 

I'm actually new to open source 
I'm passionate to serve the community.

**Comment by martinfleis** [comment]
@Abdullium feel free to prepare a pull request with this! Thanks!

**Comment by DamyanBG** [comment]
Hello, if this issue is still open, please, assign it to me !

**Comment by martinfleis** [comment]
@DamyanBG I cannot formally assign it but go on! Thanks!

**Comment by DamyanBG** [comment]
Okay, I will give a try !

**Comment by alex-translation** [comment]
is there any work on this? currently working on some things and would benefit from an implementation. would love to help/test if someone has a good start.

**Comment by martinfleis** [comment]
@alex-translation There's nothing to implement, we just wanted to document existing solutions. If a file format like a Parquet supports multiple geometry columns, it can be used. Otherwise, you can convert additional cols to WKB or WKT and save as text.

**Comment by NoharaMasato** [comment]
Hello, all. I created a PR for this. #2878 If you have time, please take a look. Thank you.

**Comment by mahdin75** [comment]
Is there any work on this issue?

**Comment by martinfleis** [comment]
Yes, this is resolved by #2878.
