### ISSUE TITLE
BUG: `explode` mixes data with multi-indexes

### ISSUE THREAD

**Issue by kai-tub** [geopandas/geopandas#2367]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import geopandas
from shapely.geometry import Polygon, MultiPolygon

geom1 = Polygon([(0, 0), (1, 1), (0, 1)])

geom2 = MultiPolygon(
    [
        Polygon([(0, 0), (1, 1), (1, 0)]),
        Polygon([(2, 2), (3, 3), (3, 2)]),
    ]
)

print(geopandas.__version__)

df = geopandas.GeoDataFrame(
    {"data": ["rostock_data", "bonn_data"]},
    index=pd.Index([("rostock", "2"), ("bonn", "1")], name=("name", "id")),
    geometry=[geom1, geom2],
)
print(df)

print(df.explode(index_parts=True))
```

### Input dataframe
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>data</th>
      <th>geometry</th>
    </tr>
    <tr>
      <th>name</th>
      <th>id</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>rostock</th>
      <th>2</th>
      <td>rostock_data</td>
      <td>POLYGON ((0.00000 0.00000, 1.00000 1.00000, 0.00000 1.00000, 0.00000 0.00000))</td>
    </tr>
    <tr>
      <th>bonn</th>
      <th>1</th>
      <td>bonn_data</td>
      <td>MULTIPOLYGON (((0.00000 0.00000, 1.00000 1.00000, 1.00000 0.00000, 0.00000 0.00000)), ((2.00000 2.00000, 3.00000 3.00000, 3.00000 2.00000, 2.00000 2.00000)))</td>
    </tr>
  </tbody>
</table>

#### Problem description

If the upper code is executed the second row (bonn) should be exploded into two polygons, without changing the contents.
The data column should duplicate the `bonn_data` since that is the _data-column_ that get _exploded_.

The output that I get when executing the above command is:

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th></th>
      <th>data</th>
      <th>geometry</th>
    </tr>
    <tr>
      <th>name</th>
      <th>id</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>rostock</th>
      <th>2</th>
      <th>0</th>
      <td>bonn_data</td>
      <td>POLYGON ((0.00000 0.00000, 1.00000 1.00000, 1.00000 0.00000, 0.00000 0.00000))</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">bonn</th>
      <th rowspan="2" valign="top">1</th>
      <th>0</th>
      <td>bonn_data</td>
      <td>POLYGON ((2.00000 2.00000, 3.00000 3.00000, 3.00000 2.00000, 2.00000 2.00000))</td>
    </tr>
    <tr>
      <th>1</th>
      <td>rostock_data</td>
      <td>POLYGON ((0.00000 0.00000, 1.00000 1.00000, 0.00000 1.00000, 0.00000 0.00000))</td>
    </tr>
  </tbody>
</table>

The `bonn` data gets mixed up with the `rostock` data.

#### Output of ``geopandas.show_versions()``

<details>

[paste the output of ``geopandas.show_versions()`` here leaving a blank line after the details tag]

SYSTEM INFO
-----------
python     : 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11)  [GCC 9.4.0]
executable : /home/kaiclasen/mambaforge/envs/ben-vqa-builder/bin/python
machine    : Linux-5.4.0-100-generic-x86_64-with-glibc2.27

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.10.2
GEOS lib   : XXX/lib/libgeos_c.so
GDAL       : 3.4.1
GDAL data dir: XXX/share/gdal
PROJ       : 8.2.1
PROJ data dir: XXX/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.4.1
fiona      : 1.8.21
numpy      : 1.22.2
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.3.0
matplotlib : 3.5.1
mapclassify: 2.4.3
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : 6.0.1
pygeos     : 0.12.0

</details>

**Comment by martinfleis** [comment]
Thanks for the report. We have already catch this one in the meantime. This is the output you get with the main branch (I changed one coordinate to see the allocation of geoms).

```
0.10.2+57.gcb0c8b5e
                    data                                           geometry
name    id                                                                 
rostock 2   rostock_data  POLYGON ((60.00000 0.00000, 1.00000 1.00000, 0...
bonn    1      bonn_data  MULTIPOLYGON (((0.00000 0.00000, 1.00000 1.000...
                      data                                           geometry
name    id                                                                   
rostock 2  0  rostock_data  POLYGON ((60.00000 0.00000, 1.00000 1.00000, 0...
bonn    1  0     bonn_data  POLYGON ((0.00000 0.00000, 1.00000 1.00000, 1....
           1     bonn_data  POLYGON ((2.00000 2.00000, 3.00000 3.00000, 3....
```

**Comment by kai-tub** [comment]
Ah, I only looked for "open" issues and not for _all_ issues :facepalm:  (#2271)
