### ISSUE TITLE
QST:sjoin_nearest can't be used

### ISSUE THREAD

**Issue by lx12633036** [geopandas/geopandas#2372]
- [x] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

#### Question about geopandas

**Note**: If you'd still like to submit a question, please read [this guide](
https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.

```python
# Your code here, if applicable
[NotImplementedError: Currently, only PyGEOS >= 0.10.0 supports `nearest_all`. To use PyGEOS within GeoPandas, you need to install PyGEOS: 'conda install pygeos' or 'pip install pygeos']
```
But，my geopandas version is 0.10.2. And my pygeos version is 0.12.0

**Comment by martinfleis** [comment]
Hi, are you sure you are running the code in the same environment where you have pygeos? Can you post what `geopandas.show_versions()` returns in that environment?

**Comment by lx12633036** [comment]
> Hi, are you sure you are running the code in the same environment where you have pygeos? Can you post what `geopandas.show_versions()` returns in that environment?

Hello，thank you for your reply!
This is my  environment.In this environment, I can‘t see pygeos，is that right?
SYSTEM INFO
-----------
python     : 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.3.3
GDAL data dir: None
PROJ       : 8.2.0

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.4.1
fiona      : 1.8.20
numpy      : 1.22.2
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.3.0
matplotlib : 3.5.0
mapclassify: 2.4.3
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

**Comment by martinfleis** [comment]
It seems that tou do not have `pygeos` installed in your environment. Can you double check that?

**Comment by lx12633036** [comment]
should i  need to import pygeos separately

**Comment by jorisvandenbossche** [comment]
There is no need to import pygeos separately, but you do need to install in the environment. From the output of `geopandas.show_versions()`, you can see that pygeos is not installed in that environment (`None` means not installed).

**Comment by lx12633036** [comment]
`gpd.options.use_pygeos=True`
I use this in my notebook,but an ERROR is
`[ImportError: To use PyGEOS within GeoPandas, you need to install PyGEOS: 'conda install pygeos' or 'pip install pygeos']()`

**Comment by martinfleis** [comment]
I think that you are running your code in a different environment that your `pip list` shows.

**Comment by lx12633036** [comment]
In this environment pip list show ,I have pygeos 0.12.0

**Comment by martinfleis** [comment]
Yes, in the environment in which you call `pip list`, you do indeed have pygeos. But I believe that your code actually uses a different environment than this one. You can try `import pygeos` directly in that environment. Maybe you'll get some useful error message.

**Comment by StanNieuwmans** [comment]
@lx12633036 @martinfleis Did anyone find a fix? I have exactly the same problem ;(
If I try to `import pygeos` I get this error: `DLL load failed while importing lib`

**Comment by msumon94** [comment]
Hi,  
I am also facing same problem.    **any solution?**     geopandas.sjoin_nearest ( ) 

**error:** 
NotImplementedError: Currently, only PyGEOS >= 0.10.0 supports `nearest_all`. To use PyGEOS within GeoPandas, you need to install PyGEOS: 'conda install pygeos' or 'pip install pygeos'  

**here is the version **details****


SYSTEM INFO
-----------
python     : 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
executable : /usr/bin/python3
machine    : Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.6.2
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.4.1
GDAL data dir: /usr/local/lib/python3.7/dist-packages/fiona/gdal_data
PROJ       : 8.1.1
PROJ data dir: /usr/local/lib/python3.7/dist-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.5
fiona      : 1.8.21
numpy      : 1.21.6
shapely    : 1.8.2
rtree      : None
pyproj     : 3.2.1
matplotlib : 3.2.2
mapclassify: None
geopy      : 1.17.0
psycopg2   : 2.7.6.1 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 6.0.1

**Comment by brendan-ward** [comment]
@msumon94 it looks like you do not have pygeos installed; as in the issues above, you need to have pygeos installed in 
the environment you are using.  It looks like you are not running inside a conda environment, but are on Linux, so `pip install pygeos` should work for you.

**Comment by msumon94** [comment]
@brendan-ward   Hi,
I appreciate your reply.  I used !pip install pygeos.  But still it is not working. 

I am running my code on google colab (jupyter notebook). 


import pandas as pd
!pip install geopandas
import geopandas as gpd
from shapely.geometry import Point, Polygon
%matplotlib inline   


!pip install pygeos 

lighting_with_crashes=gpd.sjoin_nearest(lighting_interchange, crash_interchange, how='left', max_distance=161)
lighting_with_crashes.head() 

then it shows: following error: 


NotImplementedError: Currently, only PyGEOS >= 0.10.0 supports `nearest_all`. To use PyGEOS within GeoPandas, you need to install PyGEOS: 'conda install pygeos' or 'pip install pygeos'




**My version** 

SYSTEM INFO
-----------
python     : 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0]
executable : /usr/bin/python3
machine    : Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.6.2
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.4.1
GDAL data dir: /usr/local/lib/python3.7/dist-packages/fiona/gdal_data
PROJ       : 8.1.1
PROJ data dir: /usr/local/lib/python3.7/dist-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.3.5
fiona      : 1.8.21
numpy      : 1.21.6
shapely    : 1.8.2
rtree      : None
pyproj     : 3.2.1
matplotlib : 3.2.2
mapclassify: None
geopy      : 1.17.0
psycopg2   : 2.7.6.1 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 6.0.1
pygeos     : 0.12.0


**I also tried:**
 !pip install --upgrade pygeos==0.10.0
import pygeos

**Comment by brendan-ward** [comment]
@msumon94 The problem is the installation and execution order on Google collab; installing pygeos after importing geopandas means that geopandas does not detect pygeos when it starts up - even if you install / import pygeos after.  You need to restart your collab runtime first, then import pygeos, then geopandas, then import geopandas.

Here is a demo [notebook](https://gist.github.com/brendan-ward/245727ecaf511f742c0e3be9de8fa030) that shows pygeos now correctly available. (and a [broken one](https://gist.github.com/brendan-ward/6b72c68ef9a1af84565a89e3d8a249f0) demonstrating the error described above)

**Comment by msumon94** [comment]
@brendan-ward  thank you for your reply. 

Can you please tell me which projection (epsg) should be selected for this sjoin_nearest( ) function. I used epsg 3857, but it's not giving the correct result. Please note that  max_distance =161 which is in meter.

**Comment by brendan-ward** [comment]
@msumon94 The correct projection depends on the extent of your data and your goals / tradeoffs with respect to your analysis, and is off-topic for this issue.  I suggest an internet search to help find suggestions for your case, or to ask on the [Geopandas Gitter](https://gitter.im/geopandas/geopandas).  [This article](https://source.opennews.org/articles/choosing-right-map-projection/) might help.

> it's not giving the correct result

Can you please elaborate on what it is returning and how that is incorrect, so that we can identify if there is a bug?

**Comment by msumon94** [comment]
@brendan-ward  thank you very much

**Comment by ozzalel** [comment]
> > 
> 
> nope,i can't import pygeos.So,I can't use this function！

Hi, just ran into thie issue myself, including seeing pygeons on pip list and not seeing it on geopandas.show_versions().
I've installed pygeos using pip install, but I guess I've updated gepadnas using 
`conda install -c conda-forge geopandas=0.10`
The solution was pip uninstall pygeos and then installing pygeos using conda forge
`conda install pygeos --channel conda-forge, from the geopandas docs`
after this process geopandas.show_versions() worked and sjoin worked

**Comment by sjabarnia** [comment]
I'm having the same problem, pygeos is installed but geopandas fails to use it.


> **SYSTEM INFO**
> -----------
> python     : 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:27:18)  [Clang 11.1.0 ]
> executable : ~/bin/python
> machine    : macOS-12.4-arm64-i386-64bit
> 
> GEOS, GDAL, PROJ INFO
> ---------------------
> GEOS       : 3.10.3
> GEOS lib   : ~/lib/libgeos_c.dylib
> GDAL       : 3.3.1
> GDAL data dir: ~/share/gdal
> PROJ       : 8.0.1
> PROJ data dir: ~/share/proj
> 
> PYTHON DEPENDENCIES
> -------------------
> geopandas  : 0.11.1
> numpy      : 1.21.6
> pandas     : 1.4.2
> pyproj     : 3.3.1
> shapely    : 1.8.0
> fiona      : 1.8.20
> geoalchemy2: 0.9.4
> geopy      : 2.1.0
> matplotlib : 3.5.1
> mapclassify: 2.4.3
> pygeos     : 0.10.2
> pyogrio    : None
> psycopg2   : 2.9.3 (dt dec pq3 ext lo64)
> pyarrow    : 5.0.0
> rtree      : 1.0.0

Following the steps in this [notebook](https://gist.github.com/brendan-ward/245727ecaf511f742c0e3be9de8fa030) :

```
import pandas as pd
import geopandas as gpd
import pygeos
print(f"pygeos version: {pygeos.__version__}")
print(f"geos version: {pygeos.geos_version}")
print(f"use pygeos? {gpd.options.use_pygeos}")
```

> pygeos version: 0.10.2
> geos version: (3, 9, 1)
> use pygeos? True

Still when trying to use sjoin_nearest, I get this error:

> NotImplementedError: Currently, only PyGEOS >= 0.10.0 supports `nearest_all`. To use PyGEOS within GeoPandas, you need to install PyGEOS: 'conda install pygeos' or 'pip install pygeos'

**Comment by martinfleis** [comment]
@sjabarnia have you tried the solutions described above?

**Comment by Coulorful** [comment]
> * [x]  I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.
> * [ ]  I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).
> 
> #### Question about geopandas
> **Note**: If you'd still like to submit a question, please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your question.
> 
> ```python
> # Your code here, if applicable
> [NotImplementedError: Currently, only PyGEOS >= 0.10.0 supports `nearest_all`. To use PyGEOS within GeoPandas, you need to install PyGEOS: 'conda install pygeos' or 'pip install pygeos']
> ```
> 
> But，my geopandas version is 0.10.2. And my pygeos version is 0.12.0

请问这个问题解决了吗？have sovled?

**Comment by martinfleis** [comment]
@Coulorful I am sorry, you will have to post your question in English.

**Comment by Coulorful** [comment]
> @Coulorful I am sorry, you will have to post your question in English.

Thanks for your reply. I have solved my problem, maybe due to pip install pyges ,  import pygeos from .lib import GEOSException # NOQA....ImportError: DLL load failed: The specified procedure could not be found.  Then I unintall it and install from [pygeos‑0.12.0‑cp39‑cp39‑win_amd64.whl]  finally it worked to import pygeos and  now I can use gpd.sjoin_nearest.
