### ISSUE TITLE
Update for GeoParquet spec v0.1.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#2376]
The main parquet specification has moved from https://github.com/geopandas/geo-arrow-spec/ to https://github.com/opengeospatial/geoparquet, and that was now officially released as v0.1.0 (https://github.com/opengeospatial/geoparquet/releases/tag/v0.1.0). 
We are still keeping the https://github.com/geopandas/geo-arrow-spec/ repo for Arrow-specific standards (extension types, other ways to store the geometries than WKB, ..), while the main GeoParquet metadata spec is now covered in https://github.com/opengeospatial/geoparquet.

For the most part we are already compatible (we are only not writing some optional fields, and writing the additional "creator" field, but that is allowed and thus also not a violation of the spec). However, unfortunately I missed one aspect: "version" vs "schema_version" field naming, see https://github.com/opengeospatial/geoparquet/issues/42

Other todo's:

- Update our docs to point to https://github.com/opengeospatial/geoparquet as the spec
- We can include the optional "edges" field, but since we would only support the "planar" option (which is the default if the field is missing), this is not super important to include.
- We should update the construction of the bbox in case of antimeridian crossing (it follows the geojson spec, see https://datatracker.ietf.org/doc/html/rfc7946#section-5)

**Comment by jorisvandenbossche** [comment]
> However, unfortunately I missed one aspect: "version" vs "schema_version" field naming

For this, I was thinking we could do a quick 0.10.3 release with just adding a "version" alias for "schema_version" (it seems we don't check this while validating the metadata on read). Since 0.11 will still take some time to get fully done.

**Comment by martinfleis** [comment]
Ah, that is unfortunate. It means that neither GeoPandas or sfarrow actually follow the spec... (cc @wcjochem)

I am fine a point release to fix this, unless there's a chance to issue a point release to the spec :).

**Comment by wcjochem** [comment]
Thanks! Yes, I'll need to update sfarrow for "schema_version", too.

**Comment by Jesus89** [comment]
I've added a branch with the rename, just in case we want to change it for future versions: https://github.com/opengeospatial/geoparquet/commit/9d94152c6d0bba8f181efcb5377dcb741a4b63b7

**Comment by brendan-ward** [comment]
Superseded by #2441
