### ISSUE TITLE
Does geocode keep the order of the input?

### ISSUE THREAD

**Issue by latot** [geopandas/geopandas#2383]
Hi, I'm using geocode to get the data, but then, I thought the next things, when we geocodify something, the server don't necessary will return the results in the same order as the results, and that seems to be the case:

https://stackoverflow.com/questions/46816461/google-maps-geocoding-results-in-different-order

Some times, not always, we need to know what adress/coords belong to the rows, and I can't found an option, or something, that can tell me if the geocode function, keep or not the order.

The point would be assign the result to the specific index who requested the data, instead just collect all the results.

Thx.

**Comment by jdmcbr** [comment]
@latot Yes, when you perform geocoding (or reverse geocoding) in geopandas, the returned dataframe maintains correspondence between the address and the location. We perform the geocode query row by row, and await the result of one call before making another.
