### ISSUE TITLE
Drop Python 3.7

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2391]
We should consider dropping support for Python 3.7. We are roughly following numpy model (#1457) and numpy itself is 3.8+ now. Same applies to pyproj, which requires 3.8 (and causes some macOS CI failures because of some conda issues). 

I forgot about Python versions when doing #2358 and bumped only packages.

@jorisvandenbossche if you're fine with that, I'll update CI matrix and related things.

**Comment by jorisvandenbossche** [comment]
Sounds good to me!
