### ISSUE TITLE
QST: Not able to convert dataframe into a geodataframe

### ISSUE THREAD

**Issue by nuistzhou** [geopandas/geopandas#2392]
- [x] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

#### Question about geopandas

Hi, I was using below line to convert a dataframe with geometry column named 'geom' into a geodataframe.
Not sure why it doesn't work and always saying it is invalid geometry, but I did check and it is valid!
 
```python
gdf = gpd.GeoDataFrame(df_blocks, geometry='geom')
```

Output:

```python
  File "C:\Users\xxx\Anaconda3\envs\xxx\lib\site-packages\geopandas\_vectorized.py", line 136, in from_shapely
    raise TypeError("Input must be valid geometry objects: {0}".format(geom))
TypeError: Input must be valid geometry objects: SRID=4326;POLYGON Z ((116.71752927718 39.908987976165 0, 116.71780899613 39.914918393883 0, 116.70943130635 39.915668121029 0, 116.70603794804 39.916340990836 0, 116.70287036476 39.91721877866 0, 116.70285145252 39.916881822448 0, 116.70297255866 39.913675770402 0, 116.70312233675 39.912551585686 0, 116.70326213181 39.91148941447 0, 116.70358053401 39.910138980311 0, 116.70378612357 39.909475692272 0, 116.7040016895 39.908820389621 0, 116.70463741142 39.906934501706 0, 116.70524719175 39.905164657767 0, 116.70566742675 39.903390106341 0, 116.70601285555 39.901500676029 0, 116.71291452094 39.901627020364 0, 116.71269790932 39.902173279325 
0, 116.71216390474 39.90327193462 0, 116.71204410401 39.903722073674 0, 116.71197818438 39.904206139862 0, 116.71197804008 39.905365088664 
0, 116.71220844046 39.906232744259 0, 116.71270720906 39.907627025384 0, 116.71278101029 39.907971913562 0, 116.71274905622 39.908143947885 0, 116.71260833722 39.908274126848 0, 116.71234886984 39.90841246273 0, 116.71230095791 39.908522521264 0, 116.71232285733 39.9089554734 0, 116.71752927718 39.908987976165 0))
```
Thanks!

**Comment by martinfleis** [comment]
Hi, can you show a bit of your data? I  believe that your column `geom` does not contain geometry in a correct form. Especially the `SRID=4326` bit should not be there, so it is likely not an array of shapely geometries.

**Comment by nuistzhou** [comment]
@martinfleis 
Hi, Thanks for helping.
The geom is directly read from Geo Django model with the field type of `PolygonField` (https://docs.djangoproject.com/en/4.0/ref/contrib/gis/model-api/) 

An example of my geom stored in PostgreSQL is :

`01030000A0E610000001000000A6000000A63888F7ACA85F4033AD3B31A6E3464000000000000000009585F69AAEA85F402910F39FA7E346400000000000000000C3CF643EB0A85F409272AA0EA9E346400000000000000000B21CD3E1B1A85F40FBD4617DAAE346400000000000000000E0664185B3A85F40653719ECABE346400000000000000000CFB3AF28B5A85F40CE99D05AADE346400000000000000000CF7D16BAB6A85F4054C13ACDADE34640000000000000000080A7D858B8A85F40AC875E86AAE346400000000000000000F1D39AF7B9A85F40054E823FA7E346400000000000000000A2FD5C96BBA85F404413A6F8A3E346400000000000000000122A1F35BDA85F409CD9C9B1A0E3464000000000000000009AA20E84BEA85F4022C99B0A9EE3464000000000000000006CC5AE64BFA85F4066A80F469CE3464000000000000000005A121D08C1A85F40E4C3D8FF98E346400000000000000000895C8BABC2A85F404ADEA1B995E34640000000000000000077A9F94EC4A85F403CF96A7392E3464000000000000000009B086DABC6A85F40F30373BB8DE346400000000000000000CA52DB4EC8A85F406D1748308FE346400000000000000000B89F49F2C9A85F40E82A1DA590E3464000000000000000002701B5FFCBA85F4035DC287892E34640000000000000000036234135CDA85F4035994C318FE3464000000000000000008442CD6ACEA85F40345670EA8BE346400000000000000000D36159A0CFA85F40341394A388E346400000000000000000E283E5D5D0A85F40A7CFB75C85E34640000000000000000030A3710BD2A85F40A78CDB1582E3464000000000000000007FC2FD40D3A85F40A749FFCE7EE34640000000000000000039ED19E9D4A85F400343AD517AE3464000000000000000003DA4DBD2D5A85F40DDF8D00A77E34640000000000000000019FFDD61D6A85F40B0DB9C0975E346400000000000000000FBC0E391D7A85F409697C0C271E34640000000000000000044D1B236D8A85F401FC902FC6FE34640000000000000000057477A47D8A85F403CA548156EE346400000000000000000313F4C86D8A85F4091C94AEB6BE3464000000000000000001C284F86D8A85F409C33A55C6BE346400000000000000000D919C379D8A85F404A9EFDF76AE346400000000000000000483B6671D8A85F40BAF2B69B6AE346400000000000000000412C1D54D8A85F40ADCCEF1D6AE34640000000000000000030798BF7D9A85F40DE9E21C968E3464000000000000000005EC3F99ADBA85F40F56F537467E3464000000000000000004D10683EDDA85F409941851F66E3464000000000000000007B5AD6E1DEA85F403D13B7CA64E346400000000000000000AAA44485E0A85F40E1E4E87563E346400000000000000000D9EEB228E2A85F40F8B51A2162E346400000000000000000073921CCE3A85F409C874CCC60E346400000000000000000F6858F6FE5A85F40B3587E775FE34640000000000000000024D0FD12E7A85F40572AB0225EE346400000000000000000531A6CB6E8A85F406FFBE1CD5CE3464000000000000000008264DA59EAA85F4086CC13795BE34640000000000000000070B148FDEBA85F409D9D45245AE3464000000000000000009FFBB6A0EDA85F40B46E77CF58E3464000000000000000008D482544EFA85F40CB3FA97A57E346400000000000000000FC8F93E7F0A85F40E310DB2556E346400000000000000000EADC018BF2A85F40FAE10CD154E3464000000000000000001927702EF4A85F4011B33E7C53E3464000000000000000004771DED1F5A85F409C83702752E34640000000000000000076BB4C75F7A85F40B354A2D250E346400000000000000000A505BB18F9A85F40CA25D47D4FE346400000000000000000935229BCFAA85F4055F605294EE346400000000000000000C29C975FFCA85F406CC737D44CE34640000000000000000053F660B3FDA85F406D7920C04BE346400000000000000000613B36F1FCA85F40366D3CFE49E34640000000000000000061A92B87FBA85F4022F25FB746E346400000000000000000E211211DFAA85F409C77837043E346400000000000000000237D16B3F8A85F4088FCA62940E3464000000000000000000C658C52F7A85F40E06B3E923CE346400000000000000000240E10F2F5A85F40E6F1614B39E346400000000000000000FCB99391F4A85F40ED77850436E34640000000000000000015631731F3A85F4066FDA8BD32E3464000000000000000006FDF447EF1A85F40C8B3C4A12EE346400000000000000000DDF57025F0A85F405B3AE85A2BE3464000000000000000004B0C9DCCEEA85F40EEC00B1428E3464000000000000000007825C973EDA85F4081472FCD24E346400000000000000000A63EF51AECA85F4013CE528621E346400000000000000000145521C2EAA85F401A54763F1EE3464000000000000000009D01224EE8A85F40DCB6FB4320E3464000000000000000006EB7B3AAE6A85F4006EAF59C21E3464000000000000000003F6D4507E5A85F40311DF0F522E3464000000000000000001123D763E3A85F40CF4FEA4E24E346400000000000000000E2D868C0E1A85F406D82E4A725E346400000000000000000F48BFA1CE0A85F407FB4DE0027E346400000000000000000C5418C79DEA85F40AAE7D85928E346400000000000000000D7F41DD6DCA85F40481AD3B229E346400000000000000000A8AAAF32DBA85F40E64CCD0B2BE3464000000000000000007960418FD9A85F40847FC7642CE346400000000000000000DDF54E7DD8A85F40DAF4C7432DE346400000000000000000AFABE0D9D6A85F40B72736992EE34640000000000000000080617236D5A85F40945AA4EE2FE34640000000000000000092140493D3A85F40718D124431E346400000000000000000A3C795EFD1A85F40DBC0809932E346400000000000000000757D274CD0A85F40B9F3EEEE33E3464000000000000000004633B9A8CEA85F4096265D4435E34640000000000000000058E64A05CDA85F407359CB9936E346400000000000000000299CDC61CBA85F40C48B39EF37E3464000000000000000003B4F6EBEC9A85F402EBFA74439E3464000000000000000004D02001BC8A85F407EF1159A3AE346400000000000000000DEBA9177C6A85F405B2484EF3BE346400000000000000000EF6D23D4C4A85F403957F2443DE3464000000000000000006619C7B3C3A85F4031F40B3A3EE34640000000000000000078CC5810C2A85F4059AE8D9E3FE3464000000000000000004982EA6CC0A85F4067670F0341E3464000000000000000005B357CC9BEA85F400221916742E3464000000000000000002CEB0D26BDA85F409DDA12CC43E3464000000000000000003E9E9F82BBA85F403894943045E3464000000000000000000F5431DFB9A85F40D34D169546E3464000000000000000002107C33BB8A85F40E10698F947E346400000000000000000F2BC5498B6A85F407CC0195E49E346400000000000000000446DE6F4B4A85F40177A9BC24AE34640000000000000000015237851B3A85F40B2331D274CE34640000000000000000027D609AEB1A85F40C0EC9E8B4DE346400000000000000000F88B9B0AB0A85F40CEA520F04EE346400000000000000000CA412D67AEA85F40695FA25450E346400000000000000000DBF4BEC3ACA85F40041924B951E346400000000000000000EDA75020ABA85F4012D2A51D53E346400000000000000000BF5DE27CA9A85F40208B278254E346400000000000000000D01074D9A7A85F40BB44A9E655E346400000000000000000A2C60536A6A85F4056FE2A4B57E346400000000000000000B3799792A4A85F40D7B6ACAF58E346400000000000000000C52C29EFA2A85F4072702E145AE346400000000000000000AF7409D5A1A85F40C5F6A1015BE346400000000000000000C1279B31A0A85F40462DA6625CE34640000000000000000092DD2C8E9EA85F40E064AAC35DE346400000000000000000A490BEEA9CA85F40EE9BAE245FE346400000000000000000A16A82B69BA85F409C3E312560E346400000000000000000B31D14139AA85F4094223D8261E34640000000000000000084D3A56F98A85F40180749DF62E346400000000000000000D68337CC96A85F4010EB543C64E346400000000000000000A839C92895A85F4095CF609965E346400000000000000000B9EC5A8593A85F408DB36CF666E346400000000000000000CB9FECE191A85F401298785368E3464000000000000000009C557E3E90A85F40977C84B069E346400000000000000000AE08109B8EA85F408E60900D6BE346400000000000000000C0BBA1F78CA85F4013459C6A6CE346400000000000000000917133548BA85F409829A8C76DE346400000000000000000A324C5B089A85F40900DB4246FE34640000000000000000074DA560D88A85F4088F1BF8170E346400000000000000000BAF3641787A85F400F77348672E3464000000000000000000924EA8785A85F405CB210CD75E346400000000000000000D84E6FF883A85F401DEDEC1379E346400000000000000000A779F46882A85F406B28C95A7CE346400000000000000000E96F760482A85F40E24242CC7DE346400000000000000000D7BCE4A783A85F40464537527FE3464000000000000000000507534B85A85F40AB472CD880E346400000000000000000F453C1EE86A85F400F4A215E82E346400000000000000000E2A02F9288A85F40734C16E483E346400000000000000000D0ED9D358AA85F40D74E0B6A85E346400000000000000000BF3A0CD98BA85F40AE5000F086E346400000000000000000ED847A7C8DA85F401253F57588E3464000000000000000001CCFE81F8FA85F407755EAFB89E3464000000000000000000A1C57C390A85F404E57DF818BE346400000000000000000F968C56692A85F40B259D4078DE346400000000000000000E7B5330A94A85F40165CC98D8EE3464000000000000000001600A2AD95A85F407A5EBE1390E346400000000000000000044D105197A85F405260B39991E346400000000000000000A290BD8398A85F4001B9D3B692E34640000000000000000090DD2B279AA85F40FAAE474694E3464000000000000000007F2A9ACA9BA85F40F3A4BBD595E346400000000000000000AD74086E9DA85F40EC9A2F6597E3464000000000000000009CC176119FA85F40E590A3F498E3464000000000000000008A0EE5B4A0A85F40DE8617849AE346400000000000000000B9585358A2A85F40D77C8B139CE346400000000000000000A7A5C1FBA3A85F40D072FFA29DE346400000000000000000D6EF2F9FA5A85F40C86873329FE346400000000000000000C43C9E42A7A85F40C15EE7C1A0E346400000000000000000B2890CE6A8A85F40BA545B51A2E346400000000000000000E1D37A89AAA85F40274ACFE0A3E346400000000000000000A63888F7ACA85F4033AD3B31A6E346400000000000000000`

Not sure if this helps.
But please let me know if you need more information. 
Appreciate!

**Comment by martinfleis** [comment]
> Not sure if this helps.

Not much.

Can you show` df_blocks.head()`?

**Comment by nuistzhou** [comment]
@martinfleis 

```
>>> df_blocks['geom'].head()
0    [[(118.09214310822, 29.90780444513, 0.0), (118...
1    [[(117.24302727452, 39.375915791426, 0.0), (11...
2    [[(114.48602134532, 37.096989099989, 0.0), (11...
3    [[(114.50912043155, 37.091300698983, 0.0), (11...
4    [[(114.50926738329, 37.097122242067, 0.0), (11...
```

limited view thought...

And when I check the type of the geom object:

```
>>> df_blocks.geom[0] 
<Polygon object at 0x24f49f21808>
```

Appreciate!

**Comment by martinfleis** [comment]
Your geometry is a geodjango polygon but GeoPandas need a shapely polygon. You can covert one to the other via WKT. Try this.

```
wkt = df_blocks.geom.apply(lambda x: x.wkt)
gdf = geopandas.GeoDataFrame(df_blocks, geometry=geopandas.GeoSeries.from_wkt(wkt))
```
