### ISSUE TITLE
BUG:  gdf.iterfeatures() should preserve order of columns

### ISSUE THREAD

**Issue by ameier3** [geopandas/geopandas#2394]
- [ x ] I have checked that this issue has not already been reported.

- [ x ] I have confirmed this bug exists on the latest version of geopandas.

- [ x ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd

# read example data
file = gpd.datasets.get_path("naturalearth_lowres")  
gdf = gpd.read_file(file)

# get column names without `geomerty`
cols_org = [ c for c in gdf.columns if c != 'geometry']

# get a list of column names for the __GeoInterface__
for feat in gdf.head(1).iterfeatures():
    cols_feat = list(feat['properties'].keys())
    

print("Index\tOriginal\t\tFeature ")
for ii, cols in enumerate(zip(cols_org, cols_feat)):
    
    col_org, col_feat = cols
    
    print(f"{ii}\t\t{col_org:15}\t{col_feat}")

```
produces the folloing output:
```
Index	Original		Feature 
0		pop_est        	continent
1		continent      	gdp_md_est
2		name           	iso_a3
3		iso_a3         	name
4		gdp_md_est     	pop_est
```

#### Problem description

For some applications the order of the `properties` matter. E.g. when constucting XML content for a WFS service.
It would be nice if the order of columns could be specified in the GeoDataFrame and and would not change arbitarily when using  `iterfeatures()` .

The problem is caused by the fact, that in  
[      properties_cols = self.columns.difference([self._geometry_column_name])](https://github.com/geopandas/geopandas/blob/0435306e74c71b870c06ea4e26dc4d4ee85ea9d9/geopandas/geodataframe.py#L868)

the `properties_cols` are determined using `set()` difference, which does not preserve order.

Using the list comprehension from the example above would solve the issue with minimal effort.

Let me know if I should provide a PR.

#### Expected Output

Order of the `feature["properties"]` are the same as the order of columns in the GeoDataFrame

#### Output of ``geopandas.show_versions()``

<details>

geopandas.show_versions()

SYSTEM INFO
-----------
python     : 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
executable : C:\miniconda3\envs\py38\python.exe
machine    : Windows-10-10.0.19044-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.3.3
GDAL data dir: None
PROJ       : 8.2.0
PROJ data dir: C:\miniconda3\envs\py38\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.4.1
fiona      : 1.8.20
numpy      : 1.22.2
shapely    : 1.8.0
rtree      : 0.9.7
pyproj     : 3.3.0
matplotlib : 3.5.1
mapclassify: 2.4.3
geopy      : None
psycopg2   : 2.9.3 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : 7.0.0
pygeos     : 0.12.0

</details>

**Comment by martinfleis** [comment]
> Let me know if I should provide a PR.

Please do! Thanks!
