### ISSUE TITLE
ENH: Ability to read a georeferenced PDF

### ISSUE THREAD

**Issue by RadJaz** [geopandas/geopandas#2399]
Sometimes I come across PDF maps that are georeferenced (have metadata describing how the document would be projected) and sometimes they have vector graphics. I wish it were possible to open one of these documents as a GeoDataFrame.

[Here's an example of such a document published by a county government.](https://gisweb.claycountymo.gov/pdf/votingp.pdf)

I would imagine it would just be a matter of adding a new "driver" to `read_file()`, so the user could use the following:
`geopandas.read_file("map.pdf", driver="PDF")`

It would read all of the items in the document and create a row for each one with columns describing the various properties of each one.

This would probably result in a very messy dataset, but I think it'd be worth it.

I've tried using qgis or similar software, but they all seem to rasterize the map and lose all of the geometric data.

**Comment by RadJaz** [comment]
I realize this is probably more relevant to fiona. My apologies.

**Comment by jorisvandenbossche** [comment]
GDAL (used by `read_file` / fiona) supports PDF (https://gdal.org/drivers/vector/pdf.html), so in theory what you mention should be possible. Although I never used this myself, so I don't know what kind of data it reads from a PDF.

It only might be that fiona does not "enable" this driver by default, in which case you first might need to do:

```
import fiona
fiona.supported_drivers["PDF"] = "rw"
```

before the `geopandas.read_file("map.pdf", driver="PDF")` will work.
