### ISSUE TITLE
ENH: Defer to Postgres search path for schemas instead of defaulting to public schema

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/geopandas#2400]
Originally from [comment on #2395 by @iboates ](https://github.com/geopandas/geopandas/issues/2395#issuecomment-1086841118)

If there is going to be a major overhaul of .to_postgis() then I suggest that some consideration be given to better handling of the target schema and how it relates to the PostGIS connection's search_path, which is what controls where data is read from and written to by default. Most people just dump everything in public, but more complex database setups may actually use the search_path to control user's behaviour, especially in large, multi-user setups.

I explored this a bit in https://github.com/geopandas/geopandas/pull/2117, but I ultimately slowly abandoned those efforts because my attempted solution was too tedious and I got the feeling I was on the wrong path. I also had discovered some oddities on the pandas' side, and had reported them, but I guess my issues were simply considered too minimal and contrived to get any interest from them.

Anyway, my issue with .to_postgis() currently is that it [makes the assumption that a lack of user-specified schema should default to public](https://github.com/geopandas/geopandas/blob/13e0abe99d34da42f3e2b79559b26c70d0e02416/geopandas/io/sql.py#L399). At first glance, this seems reasonable, but it misses a small but critical distinction about PostgreSQL in general - public is not the default schema, it is the default-configured default schema. You can even delete the public schema, even though it's not generally recommended. [search_paths in PostgreSQL are notoriously tangly](https://blog.crunchydata.com/blog/demystifying-schemas-search_path-through-examples) and can be specified at various levels, including at ROLE and at session level.

Since PostgreSQL already has its own meticulous rules and systems for dealing with search_paths, I suggest we just leave it alone and let the database engine do its thing based on its own configuration. Because the way it is now, if schema is left as None, geopandas actually incorrectly makes an overriding assumption of "oh, you mean public!", when in reality, what was meant was "use the first matching schema in the search_path", and it is admittedly true in probably 99% of all cases. [pandas handles this more explicitly by omitting the schema when set to None because they have to in order to maintain compatibility across various RDBMS](https://github.com/pandas-dev/pandas/blob/79fb2debb14e77d6d4af9c4db058e6f994507e29/pandas/io/sql.py#L621).

So, to stop the rambling and to get to the point:

Whatever is implemented should only use the schema parameter if it is not None. Otherwise, it should not specify anything at all, and let the database engine behave according to its configuration. Assuming that schema = None is equivalent to schema = "public" is a command and understandable misconception, but ultimately it is wrong and interferes with intended PostgreSQL functionality.

Example:

A user wants to create a table, and their search_path, whether at session or user level, is set to myschema_public.
Executing CREATE TABLE mytable(...); in psql will put this table in myschema
Executing df.to_postgis("mytable", schema="None") in Python will put this table in public
This could be avoided by just making sure that geopandas completely omits the schema name from any generated SQL or calls to a connection or engine object, as all instructions to the engine/connection will reduce to being consistent with the database and/or connection's parameters.

**Comment by martinfleis** [comment]
Isn't this #2090?

**Comment by brendan-ward** [comment]
Whoops - yes - duplicate of #2090
