### ISSUE TITLE
ENH: better detection of categorical columns in plot and explore

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2416]
In general better supporting pandas extension dtypes such as `string` might be nice, as for example also for boolean data you now have `boolean` dtype (and specifically for that, using a helper like `pd.api.types.is_bool_dtype` could be useful, as it will catch both the numpy bool dtype and extension boolean dtype)

_Originally posted by @jorisvandenbossche in https://github.com/geopandas/geopandas/pull/2403#discussion_r853480264_

In `plot` and `explore` we automatically detect categorical columns and switch to a categorical plot but this detection can be improved as discussed in #2403.

**Comment by emayakeerthi** [comment]
I am interested in getting started with my open source contribution to this issue.  Could you explain this issue deeply?

**Comment by martinfleis** [comment]
@emayakeerthi hi, this issue is already being resolved by #2470. There is no need for another pull request. But thanks for the interest! Try to find another issue you'd be happy to resolve ;).
