### ISSUE TITLE
0.2 release

### ISSUE THREAD

**Issue by kjordahl** [geopandas/geopandas#242]
We're past time making an official release. I think we should be in good shape to do so soon.

If anyone sees any blockers, please tag with the [0.2 release milestone](https://github.com/geopandas/geopandas/milestones/0.2%20release).

xref #237

**Comment by micahcochran** [comment]
:+1:

**Comment by kjordahl** [comment]
@micahcochran Is the :+1: to indicate that you don't see any blockers, or that you're rooting for a release?

**Comment by micahcochran** [comment]
I like the idea of a new release.   Sorry for the confusion.

**Comment by nickeubank** [comment]
@micahcochran @jorisvandenbossche @kjordahl @perrygeo 

Aside from dealing with open (but green) PRs then harmonizing them with one another:

- using example data in docs if #312 accepted, 
- adding the 0.2 updates to the changelog if #313 accepted
- adding dissolve to docs if #311 accepted
- update docs if #302 accepted

Do we have any blockers? I'm still rooting for #294, but that seems like only thing we need to decide / new code to write before release, no?

**Comment by jorisvandenbossche** [comment]
@kjordahl What do you think about doing a release now? 
I can also help if needed.

BTW, what do you all think about using `versioneer` (eg also pandas and matplotlib use it now). This deals with all version related things based on git tags (no longer hardcoding versions in different places like setup.py)

**Comment by kjordahl** [comment]
@jorisvandenbossche It's looking very close. I'll take a look at the outstanding PRs this week.

:+1: for`versioneer`, the manual versioning is annoying and fragile.

**Comment by jorisvandenbossche** [comment]
@kjordahl Do you have some time to look at the remaining issues?

IMO, #313 (changelog) and #331 (versioneer) can be merged as is, and then a release can be done. I can volunteer to do this one of the coming days if that would help.

**Comment by kjordahl** [comment]
@jorisvandenbossche Getting close. #331 is merged, #313 is ready when you are.

I'd like to add the `cx` attribute to the docs still, it's been overlooked. I should be able to cut a release in the next couple days, then. Thanks for your patience.

**Comment by kjordahl** [comment]
Release checklist:

- [ ] Tag release
- [ ] Upload to PyPI
- [ ] Update docs on geopandas.org
- [ ] Update on conda-forge (@jorisvandenbossche)

**Comment by jorisvandenbossche** [comment]
and to add to that: push tags to github

**Comment by kjordahl** [comment]
Released! A bit of a glitch for the docs on geopandas.org (see #345).

**Comment by nickeubank** [comment]
Yay!!! Great work everyone!

**Comment by jorisvandenbossche** [comment]
Thanks!!

@kjordahl small comment: maybe make the tag v0.2.0 instead of v0.2 to be consistent with the older ones (and with possible minor bug-fix releases)? (but not sure this is worth the reset and apply again)

**Comment by jorisvandenbossche** [comment]
And the package is now also uploaded to conda-forge! (only the py3.5 builds for windows are not yet available). So easy install now with `conda install -c conda-forge geopandas`

**Comment by jorisvandenbossche** [comment]
@kjordahl Maybe you can also sent a small release announcement to the pydata (or others) list?

**Comment by jorisvandenbossche** [comment]
@kjordahl Do you want to sent a mail to the pydata list? (otherwise I can also do it)

**Comment by nickeubank** [comment]
@jorisvandenbossche I think you should just post if you're up to it. If not let me know and I can take a crack at it. Too much good work here to not share! :)

**Comment by nickeubank** [comment]
@jorisvandenbossche @kjordahl Hey guys -- wanna make sure this doesn't fall through the cracks -- be a shame to not share the 0.2 release given how much work we did. Happy to do it if no one else has time.

**Comment by jorisvandenbossche** [comment]
@nickeubank thanks for the nudge :-)

Sent out an announcement: https://groups.google.com/forum/#!topic/pydata/5KXiU3_zNc8

Sent it to the pydata mailing list, and gispython (http://lists.gispython.org/mailman/listinfo/community) list. If anybody known good other lists/places to announce, feel free to forward it!

**Comment by nickeubank** [comment]
Thanks @jorvisvandenbossche! Though small ouch on the contributor omission!

**Comment by jorisvandenbossche** [comment]
Oh no .. I am very sorry! 
I used git shortlog, but apparantly my git was checkout on an old branch and I didn't check that first, so stupid! 
I also forgot Martin Journois because of that

**Comment by nickeubank** [comment]
No worries. If I had a penny for every time I was working on the wrong branch...  :)
