### ISSUE TITLE
Stable Documentation lists a git tag in the title

### ISSUE THREAD

**Issue by mrocklin** [geopandas/geopandas#2425]
![image](https://user-images.githubusercontent.com/306380/166160776-fa42e519-afc3-405f-a46a-5501e2bac1ba.png)

**Comment by martinfleis** [comment]
Thanks! I believe that this has been resolved on `main` in the meantime in #1831.

However, there is another solution now - https://github.com/readthedocs/readthedocs.org/issues/8201#issuecomment-1088728000
