### ISSUE TITLE
QST: Is there a geopandas function similar to the ArcGIS pro 'Polygon Apportion' method?

### ISSUE THREAD

**Issue by JRogierKirkman** [geopandas/geopandas#2426]
#### Question about geopandas
I am trying to convert my ArcGIS Pro project to python/geopandas. Unfortunately, I cannot find a function that I used in ArcGIS pro :  [https://pro.arcgis.com/en/pro-app/2.8/tool-reference/analysis/apportion-polygon.htm](url).

[INPUT] 
* many overlapping circle polygons (100m range)
* postal code areas with differing sizes, with corresponding population

[OUTPUT]
* per circle polygon the estimated population for that polygon, where the population attribute is transferred based on the area of the various postal code regions within the circle polygon. 

Looking on stackoverflow and GIS stack exchange and googling, I did not find any alternative for this method in Python. Am I looking over an existing function? Or are there any other steps that I could take to recreate this method?

**Comment by martinfleis** [comment]
Hi, you are looking for areal interpolation methods. That is implemented on top of geopandas in the `tobler` package. See https://pysal.org/tobler/generated/tobler.area_weighted.area_interpolate.html#tobler.area_weighted.area_interpolate

**Comment by JRogierKirkman** [comment]
Hi Martin, thank you for your reply! After your suggestion, I tried to implement the area_interpolate from the tobler package. However, I think that the source_polygons can not overlap whereas my source polygons would overlap (i.e., the overlapping circle polygons). I get the following error: 
`TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point`

**Comment by martinfleis** [comment]
I think that they can but it would be better to report the issue with the full traceback to the toilers repository.

**Comment by JRogierKirkman** [comment]
I will do that. Once again, thank you for your help :)

**Comment by brink395** [comment]
@martinfleis Hi I am trying to download the tobler package but am having a dependency issue with numpy. "cannot import name 'asscalar' from 'numpy' " I have tried installing earlier versions of numpy that include 'asscalar' with no luck. Do you have any advise for how to work around this issue? Thanks!

**Comment by martinfleis** [comment]
@brink395 can you open an issue in https://github.com/pysal/tobler with some details regarding versions and installation methods?
