### ISSUE TITLE
Update to pandas 0.17 in CI test matrix

### ISSUE THREAD

**Issue by kjordahl** [geopandas/geopandas#243]
We should continue testing on the last 2 stable versions of pandas, so let's drop 0.15 and add 0.17. There shouldn't be any issues as we have been testing continuously on pandas master.

**Comment by jorisvandenbossche** [comment]
@kjordahl It would also be good to add python 3.5 to the test matrix I think.

About pandas, I would be inclined to keep pandas 0.15 (maybe not for all combinations, because otherwise with adding py3.5 and pandas 0.17 that would explode, but at least for some), as it is a reality that users often have to rely on an older pandas version (and it can sometimes be more problematic to update pandas, as opposed to updating geopandas)

**Comment by kjordahl** [comment]
@jorisvandenbossche Agree on adding Python 3.5. Any objection to dropping 3.3 in that case?

Regarding pandas 0.15, keeping 4 versions of pandas in the matrix is a lot. We could reduce the combinations as you say. How about we test all pandas versions (3 releases + master) on Python 2.7 and 3.5, and only the last 2 releasees on the older 2.x and 3.x versions? The environment would get more complicated to set up, but that seems reasonable to me (and 25% savings in test runs compared with the full matrix if we keep 4 python versions).

**Comment by jorisvandenbossche** [comment]
Another CI related issue: I also think we should start testing against different matplotlib versions for plotting. And for the other dependencies, I am not really familiar with the chances on changes between versions, but maybe there are minimum versions as well?

Just to say that, keeping all combinations of all libraries is impossible in any case, and a more complicated setup will be needed (now it is just a cross product of pandas/python version). And in that scenario, I would keep older pandas version included.

**Comment by jorisvandenbossche** [comment]
Maybe the best way forward here, would be to define a minimum supported version for each dependency.

And from there, we can eg have a test build with these minimum versions for both py2/py3, test build with latest versions for py2/py3, and then some other combinations (but not fully covering all combinations) to at least have on build for each version of pandas ? I will always be a bit random of course, I don't know what the best approach is here.

**Comment by micahcochran** [comment]
It looks like Pandas 0.18.0 may be released on February 26th.  https://github.com/pydata/pandas/issues/12245

**Comment by kjordahl** [comment]
Closed by #272 (and obsoleted by #275).
