### ISSUE TITLE
CI: geopandas/tests/test_array::test_unary_predicates[is_closed] failure

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#2435]
Main branch is failing https://github.com/geopandas/geopandas/runs/6533478856?check_suite_focus=true, presumably something upstream has changed.

I think this is suggesting that the answer from pygeos is different to the answer from shapely (I'm not super familiar with this part of the tests).

**Comment by jorisvandenbossche** [comment]
Yes, Shapely changed the behaviour for `is_closed` in their recent release, I was just looking into fixing our tests for this.
