### ISSUE TITLE
ENH: Support MySQL spatial

### ISSUE THREAD

**Issue by latot** [geopandas/geopandas#2445]
Hi, actually there is ```to_postgis``` and other functions for postgres, I think would be great have this for MySQL too, it have spatial support too.

The actual ```to_postgis``` does not work with that db, is like obvs but I tested it anyway.

Thx.

**Comment by martinfleis** [comment]
Duplicate of #2467

**Comment by latot** [comment]
D: @martinfleis sorry!, I didn't found the issue, and even I forgot I made it! thx for closing it.
