### ISSUE TITLE
QST: How to select individuals columns using GeoPandas

### ISSUE THREAD

**Issue by martina-dev-11** [geopandas/geopandas#2450]
- [x ] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [ x] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

#### Question about geopandas

I'm still new to GeoPandas. But I am trying to output a list of localities that have changes within them, and group them by locality and month . The PostGIS query is included within this function:

```
def testRead():
    sql = """SELECT TO_CHAR(b.dateofchange, 'Month') as month, a.text, count(a.text)
    from localities as a
    join changes as b
    on ST_WITHIN(b.changelocation, a.geom)
    GROUP BY a.text, TO_CHAR(b.dateofchange, 'Month')
    order by month desc;"""
    gdf = gpd.read_postgis(sql, con=engine )
    return gdf
```
Following the docs, I attempted to use this gpd.read_postgis() function, but I keep getting this error:

_ValueError: Query missing geometry column 'geom'_

Does this mean that I have to have the geom in the SELECT? But this would require the geom to also be in the GROUP BY, and that would defeat the purpose of the query. How can I go about doing this please?

**Comment by jdmcbr** [comment]
@martina-dev-11 The main difference between `gpd.read_postgis` and `pd.read_sql` is that the geopandas function returns fully fledged geospatial objects on which you can perform geometric and geographic operations. In this case, where you're doing a geospatial operation within your query, but are ultimately not interested in accessing geometries within a dataframe, there's no reason you can't just use `pd.read_sql` where you currently have `gpd.read_postgis`.

**Comment by martina-dev-11** [comment]
Oh okay, thanks for the explanation, cheers!
