### ISSUE TITLE
Access x and y coordinates of Point geoseries through attributes

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#246]
When having a GeoSeries with Points, currently you have to do an `apply` to get the `x` and `y` attributes of each shapely Point object AFAIK:

```
In [87]: s = geopandas.GeoSeries([Point(4.42, 50.4), Point(4.43, 50.2)])

In [88]: s.apply(lambda p: p.x)
Out[88]:
0    4.42
1    4.43
dtype: float64

In [89]: s.apply(lambda p: p.y)
Out[89]:
0    50.4
1    50.2
dtype: float64
```

I think it would be very nice if there were a `x` and `y` attribute on the GeoSeries object to get this without the custom apply (`s.x` and `s.y`), and to match the attributes of shapely objects. Do others think this would be useful to have in geopandas?

One problem is that the `x` and `y` attributes are not shared among all geometry types (I think only Points have them?), but I think this could be solved with a good error message if you try to access it on other geometry types.

**Comment by darribas** [comment]
+1

**Comment by carsonfarmer** [comment]
+1
You *could* also return the centroid of non-point geometries. This is what `R`'s  `coordinates`  function from the `sp` package does IIRC?

**Comment by jorisvandenbossche** [comment]
@carsonfarmer I would initially not do this to keep it consistent with shapely. But, shapely *does* have the `centroid` attribute, which is already exposed in geopandas (``GeoSeries.centroid``). So if we add the `x`/`y`, you could do `polygons_series.centroid.x`

**Comment by carsonfarmer** [comment]
Good point!

On Wed, Nov 4, 2015 at 3:45 PM Joris Van den Bossche <
notifications@github.com> wrote:

> @carsonfarmer <https://github.com/carsonfarmer> I would initially not do
> this to keep it consistent with shapely. But, shapely *does* have the
> centroid attribute, which is already exposed in geopandas (
> GeoSeries.centroid). So if we add the x/y, you could do
> polygons_series.centroid.x
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geopandas/geopandas/issues/246#issuecomment-153893607>
> .
>
-- 
Dr. Carson Farmer (mobile edition)
Assistant Professor
Department of Geography
University of Colorado at Boulder
303.492.3252
@carsonfarmer

**Comment by jorisvandenbossche** [comment]
@kjordahl What do you think of this one? Of course, the question then maybe rises, why not `z`, or `xy` for lines/polygons as well? But to start, I think `x` and `y` for points would be rather convenient.

**Comment by chmeul** [comment]
+1 !!

**Comment by mullenkamp** [comment]
I also would like such a feature. Thanks!

**Comment by jdmcbr** [comment]
Closed by #383.

**Comment by anastasiaclark** [comment]
Has this been included in the latest geopandas ? I don't have  gdf.geometry.x in my geopandas 0.2.1 yet

**Comment by jorisvandenbossche** [comment]
It has been included in geopandas dev version a week ago, so not in 0.2, but a next 0.3 will be released one of the coming weeks

**Comment by jerem-lab** [comment]
It could be great to add z support 

```
import geopandas as gpd
from shapely.geometry import Point
s = gpd.GeoSeries([Point(4.42, 50.4,30), Point(4.43, 50.2,30)])
s.apply(lambda p: p.z)

0    30.0
1    30.0
dtype: float64
```

**Comment by martinfleis** [comment]
@jerem-lab That has been implemented and released in 0.9.0 https://geopandas.readthedocs.io/en/stable/docs/reference/api/geopandas.GeoSeries.z.html#geopandas.GeoSeries.z.

**Comment by jerem-lab** [comment]
Oh perfect 🙂👍🏼

**Comment by baggiponte** [comment]
Hi! Working with GeoPandas `0.10.2` and the method [here ](https://geopandas.readthedocs.io/en/stable/docs/reference/api/geopandas.GeoSeries.z.html#geopandas.GeoSeries.z) fails:

```python
>>> my_geodataframe.geometry.x
...
IndexError: index out of range
```
 
See the full traceback attached: [traceback.log](https://github.com/geopandas/geopandas/files/7503163/traceback.log).

Ideally, however, this should work: with `my_geodataframe.geometry` I get a `GeoSeries`, so the `.[xyx]` attribute should return the longitude/latitude/elevation.

**Comment by jorisvandenbossche** [comment]
@baggiponte opened this as a new issue: https://github.com/geopandas/geopandas/issues/2223
