### ISSUE TITLE
0.11.0 still can't be installed from conda-forge

### ISSUE THREAD

**Issue by CNFeffery** [geopandas/geopandas#2469]
the latest version `geopandas` is still `0.10.2`:

https://anaconda.org/conda-forge/geopandas
![image](https://user-images.githubusercontent.com/49147660/174818898-361515ae-15a7-4b71-b383-4f8731bca261.png)

**Comment by martinfleis** [comment]
We know. It is in progress, conda-forge has some delays currently.
