### ISSUE TITLE
QST: Enabling KML support in Fiona

### ISSUE THREAD

**Issue by vectorcrumb** [geopandas/geopandas#2481]
- [X] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

I'm trying to load a KML file in Geopandas. The majority of examples use the following code to load the file:

```python
import geopandas as gpd
import fiona

gpd.io.file.fiona.drvsupport.supported_drivers['KML'] = 'rw'
df = gpd.read_file('<filename>.kml', driver='KML')
```
However, when I tried doing that, I get the following error:
```
Traceback (most recent call last):
  File "kml2jpeg.py", line 5, in <module>
    gpd.io.file.fiona.drvsupport.supported_drivers['KML'] = 'rw'
AttributeError: 'NoneType' object has no attribute 'drvsupport'
```
This is because the object `gpd.io.file.fiona` is of NoneType. This is the same regardless if I import fiona before or after geopands. If instead I do the following:
```python
import geopandas as gpd
import fiona

fiona.drvsupport.supported_drivers['KML'] = 'rw'
df = gpd.read_file('<filename>.kml', driver='KML')
```
I can read the KML file. What is the difference between the two methods?

I am using Ubuntu 20.04 on WSL2, with the Fiona 1.8.21 and geopandas 0.11.0. The packages are installed on my local directory without using a virtual environment nor Conda.

**Comment by and-viceversa** [comment]
Here's the GIS StackExchange [answer](https://stackoverflow.com/questions/72960340/attributeerror-nonetype-object-has-no-attribute-drvsupport-when-using-fiona) (which essentialy mirrors your own).

**Comment by jorisvandenbossche** [comment]
The `drvsupport.supported_drivers` dict is an object from the fiona package, so you should edit this through fiona, and not through geopandas. As mentioned on the StackOverflow answer, we changed to import fiona dynamically (on first use of read_file), so `geopandas.io.file.fiona` is None initially.

To repeat the solution here:

```
import fiona
fiona.drvsupport.supported_drivers['KML'] = 'rw'
```

This is also how it is documented in our user guide: https://geopandas.org/en/stable/docs/user_guide/io.html#reading-spatial-data

(small note that in a future release of fiona, you will probably be able to do `geopandas.read_file(..., driver="KML", allow_unsupported_drivers=True)`, but this isn't yet released)
