### ISSUE TITLE
ENH:

### ISSUE THREAD

**Issue by oderofrancis** [geopandas/geopandas#2489]
#### Is your feature request related to a problem?

I wish I could use geopandas to merge data which has geometry and which doesn't have a geometry, for same columnname.  

#### Describe the solution you'd like

[this should provide a description of the feature request, e.g. "`GeoDataFrame.foo` should get a new parameter `bar` that [...]", try to write a docstring for the desired feature]
'''merge_dataframe should merge pandas data and geopandas dataframe data""

**Comment by brendan-ward** [comment]
@oderofrancis Do you mean joining on a non-geometry column?  Than can be done in the same way as [pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html):

```Python
>>> import geopandas, pandas
>>> from shapely.geometry import Point
>>> gdf = geopandas.GeoDataFrame({"foo": [1, 2]}, geometry=[Point(0,0), Point(1,1)], crs="EPSG:4326")
>>> df = pandas.DataFrame({"foo": [1, 2], "bar": ["a", "b"]})
>>> gdf.join(df.set_index("foo"), on="foo")
   foo                 geometry bar
0    1  POINT (0.00000 0.00000)   a
1    2  POINT (1.00000 1.00000)   b
```

If you meant something else, please reopen this issue and add more information here.
