### ISSUE TITLE
BUG: CRS lost after merge

### ISSUE THREAD

**Issue by benoit9126** [geopandas/geopandas#2493]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

# CRS lost
gdf=gpd.GeoDataFrame(data={"toto":[1,2,3], "geometry":[None, None, None]}, crs="EPSG:4326")
res=pd.merge(left=gdf, right=gdf[["toto"]], on=["toto"])
res.crs # <--- KO: None
res.geometry.crs # <--- KO: None

# CRS not lost
gdf=gpd.GeoDataFrame(data={"toto":[1,2,3], "geometry":[Point(2.5,44), None, None]}, crs="EPSG:4326")
res=pd.merge(left=gdf, right=gdf[["toto"]], on=["toto"])
res.crs # <---- OK: EPSG:4326 CRS object
res.geometry.crs # <---- OK: EPSG:4326 CRS object
```

#### Problem description

Here, when using `pandas.merge` with a geodataframe of `NULL` geometries, the CRS is lost. When at least a geometry is not `NULL` the CRS is maintained.

#### Expected Output

I would have expected the CRS not being lost after the merge.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------

python     : 3.9.6 (default, Aug 23 2021, 19:59:27)  [GCC 10.2.1 20210110]
executable : /home/benoit/.pyenv/versions/sirao_cli/bin/python
machine    : Linux-5.10.0-16-amd64-x86_64-with-glibc2.31

GEOS, GDAL, PROJ INFO
---------------------

GEOS       : 3.9.0
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.4.1
GDAL data dir: /home/benoit/.pyenv/versions/sirao_cli/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 8.2.0
PROJ data dir: /home/benoit/.pyenv/versions/sirao_cli/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------

geopandas  : 0.11.0
pandas     : 1.4.3
fiona      : 1.8.21
numpy      : 1.22.4
shapely    : 1.8.2
rtree      : 1.0.0
pyproj     : 3.3.1
matplotlib : 3.5.2
mapclassify: None
geopy      : 2.2.0
psycopg2   : None
geoalchemy2: 0.10.2
pyarrow    : None
pygeos     : 0.12.0

</details>

**Comment by m-richards** [comment]
Hi Benoit, thanks for the report, I can confirm this behaviour. Yet to dig into the details but likely to do with how pandas calls .__finalize__ after a merge. In lieu of a fix for now, a simple workaround is to use the merge method on a GeoDataFrame:
```python
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

# CRS lost
gdf=gpd.GeoDataFrame(data={"toto":[1,2,3], "geometry":[None, None, None]}, crs="EPSG:4326")
res2=gdf.merge(gdf[["toto"]], on=["toto"])
res2.geometry.crs.to_epsg() # 4326
res2.crs.to_epsg() # 4326
```

**Comment by jorisvandenbossche** [comment]
I was going to say: I don't see this behavior locally, both with the latest main (basically 0.11 release) as with geopandas 0.10.2. 
But so it appears I was still using pandas 1.4.1 in my dev environment (and 1.3.5 together with gpd 0.10.2), and after updating to 1.4.3, I can now see the bug.

**Comment by jorisvandenbossche** [comment]
I opened a PR to pandas to fix this: https://github.com/pandas-dev/pandas/pull/47762

**Comment by benoit9126** [comment]
@jorisvandenbossche @m-richards Thanks a lot.
