### ISSUE TITLE
BUG: Can't set parquet version in `GeoDataFrame.to_parquet`

### ISSUE THREAD

**Issue by TomAugspurger** [geopandas/geopandas#2495]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

The `version` argument in `to_parquet` clashes between the geoparquet version and the parquet file format version.

#### Code Sample, a copy-pastable example

```pytb
In [1]: import geopandas

In [2]: df = geopandas.read_file(geopandas.datasets.get_path("naturalearth_lowres"))

In [3]: df.to_parquet("out.parquet", version="2.6")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 df.to_parquet("out.parquet", version="2.6")

File ~/src/stac-utils/staccontainers/.venv/lib/python3.9/site-packages/geopandas/geodataframe.py:1058, in GeoDataFrame.to_parquet(self, path, index, compression, version, **kwargs)
   1051     raise ValueError(
   1052         f"GeoPandas only supports using pyarrow as the engine for "
   1053         f"to_parquet: {engine!r} passed instead."
   1054     )
   1056 from geopandas.io.arrow import _to_parquet
-> 1058 _to_parquet(
   1059     self, path, compression=compression, index=index, version=version, **kwargs
   1060 )

File ~/src/stac-utils/staccontainers/.venv/lib/python3.9/site-packages/geopandas/io/arrow.py:284, in _to_parquet(df, path, index, compression, version, **kwargs)
    279 parquet = import_optional_dependency(
    280     "pyarrow.parquet", extra="pyarrow is required for Parquet support."
    281 )
    283 path = _expand_user(path)
--> 284 table = _geopandas_to_arrow(df, index=index, version=version)
    285 parquet.write_table(table, path, compression=compression, **kwargs)

File ~/src/stac-utils/staccontainers/.venv/lib/python3.9/site-packages/geopandas/io/arrow.py:236, in _geopandas_to_arrow(df, index, version)
    233 _validate_dataframe(df)
    235 # create geo metadata before altering incoming data frame
--> 236 geo_metadata = _create_metadata(df, version=version)
    238 df = df.to_wkb()
    240 table = Table.from_pandas(df, preserve_index=index)

File ~/src/stac-utils/staccontainers/.venv/lib/python3.9/site-packages/geopandas/io/arrow.py:87, in _create_metadata(df, version)
     84 version = version or METADATA_VERSION
     86 if version not in SUPPORTED_VERSIONS:
---> 87     raise ValueError(f"version must be one of: {', '.join(SUPPORTED_VERSIONS)}")
     89 # Construct metadata for each geometry
     90 column_metadata = {}

ValueError: version must be one of: 0.1.0, 0.4.0
```

#### Problem description

User's have no way to set the parquet file format version in `to_parquet`. They would need to convert to a Table (using private geopandas APIs) and write it

```python
In [4]: table = geopandas.io.arrow._geopandas_to_arrow(df)

In [5]: import pyarrow.parquet as pq

In [6]: pq.write_table(table, "out.parquet", version="2.6")
```

One possible solution: change the `version` argument to `geoparquet_version`. Deprecating things might be a tad difficult.... In the short-term, we might have to look at the actual value and guess if it's a valid parquet file format version?

#### Output of ``geopandas.show_versions()``

<details>

Failed `CDLL(libgeos_c.so.1)`
Failed `CDLL(libgeos_c.so)`

SYSTEM INFO
-----------
python     : 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11)  [GCC 9.4.0]
executable : /home/taugspurger/src/stac-utils/staccontainers/.venv/bin/python3
machine    : Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.4.1
GDAL data dir: /home/taugspurger/src/stac-utils/staccontainers/.venv/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 8.2.0
PROJ data dir: /home/taugspurger/src/stac-utils/staccontainers/.venv/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.11.0
pandas     : 1.4.3
fiona      : 1.8.21
numpy      : 1.23.1
shapely    : 1.8.2
rtree      : None
pyproj     : 3.3.1
matplotlib : None
mapclassify: None
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : 8.0.0
pygeos     : 0.12.0

</details>

**Comment by jorisvandenbossche** [comment]
Ah, good catch, that was an oversight when we added that keyword. 

> One possible solution: change the `version` argument to `geoparquet_version`. 

That sounds good.

> Deprecating things might be a tad difficult.... In the short-term, we might have to look at the actual value and guess if it's a valid parquet file format version?

Yeah, indeed, the version numbers shouldn't overlap I think, so that should allow us to infer when a deprecation warning should be raised.

cc @brendan-ward

**Comment by brendan-ward** [comment]
Yeah, that was an oversight, and hopefully not a keyword that has been used heavily.  It seems like in this case geopandas-specific keywords should be additive rather than duplicative to the underlying `write_table` / `write_feather` functions.

Once (if?) the GeoArrow schema diverges from the GeoParquet, it seems like we would not want to use `geoparquet_version` for the `to_feather` method.

What about `schema_version`?  Then we can basically assert that for 0.1.0 and 0.4.0, the arrow and parquet schemas are identical, but that in the future those can diverge, and `schema_version` refers to the schema for the particular format.

**Comment by jorisvandenbossche** [comment]
> Once (if?) the GeoArrow schema diverges from the GeoParquet, it seems like we would not want to use `geoparquet_version` for the `to_feather` method.

I don't know if we have any intention to do so, but even then, it's a bit strange to use "geoparquet_version" for a non-parquet method. So using a different name like `schema_version` is indeed better (or `metadata_version`, `geo_metadata_version`, ...)

**Comment by brendan-ward** [comment]
I'd prefer `schema_version` because it encapsulates both the metadata and the geometry encoding.

**Comment by TomAugspurger** [comment]
`schema_version` sounds good to me too.
