### ISSUE TITLE
Spatial Join - 

### ISSUE THREAD

**Issue by abjer** [geopandas/geopandas#250]
Hi there,

I have an issue with the spatial join. I have applied it successfully to another problem but it faces some issues with joining polygons to points. I have tried with various commands for how/op. It gives me output in this form:

Example

```
import geopandas as gpd, geopandas.tools, urllib2, os

read = {'amenities.geojson': urllib2.urlopen("https://dl.dropboxusercontent.com/u/1680631/Files/amenities.geojson").read(),
        'polygons.geojson' : urllib2.urlopen("https://dl.dropboxusercontent.com/u/1680631/Files/polygons.geojson").read()}

with open('amenities.geojson','w') as f: f.write(read['amenities.geojson'])
with open('polygons.geojson','w')  as f: f.write(read['polygons.geojson'])

polygons  = gpd.read_file('polygons.geojson')
amenities = gpd.read_file('amenities.geojson')

os.remove('amenities.geojson')
os.remove('polygons.geojson')

merged=gpd.tools.sjoin(polygons, amenities, how='left', op='contains')
```

**Comment by perrygeo** [comment]
I'm not able to recreate this problem, using the datasets and code [here](http://nbviewer.ipython.org/github/geopandas/geopandas/blob/master/examples/spatial_joins.ipynb). 

Can you bundle (as shapefiles) the smallest subset of the datasets necessary to reproduce the problem?

**Comment by abjer** [comment]
Hi again, thanks for the quick reply. Here is a code that should be applicable that illustrates the issue. All data is from OpenStreetMaps. The polygons are processed using ogr2ogr. 

import geopandas as gpd, geopandas.tools, urllib2, os

read = {'amenities.geojson': urllib2.urlopen("https://dl.dropboxusercontent.com/u/1680631/Files/amenities.geojson").read(),
        'polygons.geojson' : urllib2.urlopen("https://dl.dropboxusercontent.com/u/1680631/Files/polygons.geojson").read()}

with open('amenities.geojson','w') as f: f.write(read['amenities.geojson'])
with open('polygons.geojson','w')  as f: f.write(read['polygons.geojson'])

polygons  = gpd.read_file('polygons.geojson')
amenities = gpd.read_file('amenities.geojson')

os.remove('amenities.geojson')
os.remove('polygons.geojson')

merged=gpd.tools.sjoin(polygons, amenities, how='left', op='contains')

**Comment by micahcochran** [comment]
@abjer Link?

**Comment by abjer** [comment]
I've updated the original example with a python code.

**Comment by perrygeo** [comment]
Using the code and datasets above, I can reproduce the error message. Looks like your point dataset has the coordinate order reversed:

```
ipdb> polygons
  building                                           geometry
0      yes  (POLYGON ((12.5718049 55.6880737, 12.5717616 5...
1      yes  (POLYGON ((12.541733 55.6892626, 12.5408057 55...
2      yes  (POLYGON ((12.541715 55.6914459, 12.5424583 55...
3      yes  (POLYGON ((12.5427469 55.6898458, 12.542189 55...
4      yes  (POLYGON ((12.5412559 55.679623, 12.541206 55....
ipdb> amenities
           cat                       geometry                   name
0         fuel      POINT (55.67912 12.54731)  Statoil H C Ørstedvej
1  post_office    POINT (55.695642 12.550753)    Nørrebro Postkontor
2          pub  POINT (55.6892934 12.5578332)                Ølbaren
3   restaurant  POINT (55.6902172 12.5639074)       Nørrebro Bryghus
4       cinema    POINT (55.691954 12.555818)             Empire Bio
```
So this is an issue with the source dataset - given those geometries there is no intersection between the points and polygons.

That being said, it would be helpful if geopandas would give a more meaningful error message in this case (or perhaps an empty data frame?)  I will open that as a separate issue.

**Comment by abjer** [comment]
Thanks!
