### ISSUE TITLE
Handle empty spatial join

### ISSUE THREAD

**Issue by perrygeo** [geopandas/geopandas#251]
As noted in #250 , a spatial join between two non-overlapping geodataframes fails with a cryptic message:

```
Traceback (most recent call last):
  File "_test.py", line 21, in <module>
    merged = sjoin(polygons, amenities, how='left', op='contains')
  File "/Users/mperry/projects/geopandas/geopandas/tools/sjoin.py", line 50, in sjoin
    r_idx = np.concatenate(idxmatch.values)
ValueError: need at least one array to concatenate
```

Should we catch this case and raise a more meaningful exception? Or return an empty (geo)dataframe?

**Comment by kjordahl** [comment]
I would expect an empty `GeoDataFrame`, I think. That's what `pandas.merge` does, right?

**Comment by abjer** [comment]
Yes, agree, an empty GeoDataFrame would make sense. This would be awesome to have fixed for the 0.2 version.

**Comment by jdmcbr** [comment]
@jorisvandenbossche I think this can be closed too.

**Comment by jorisvandenbossche** [comment]
@jdmcbr Thanks for noticing!

**Comment by jzf2101** [comment]
I have this issue with nonempty joins

**Comment by jorisvandenbossche** [comment]
@jzf2101 Can you provide some more information? Ideally a small reproducible example which shows the problem.

**Comment by araichev** [comment]
Using GeoPandas 0.2.1 and Pandas 0.20.3, i encounter this issue.
Here is a simple example involving two non-intersecting squares: http://geojson.io/#id=gist:anonymous/c862ca2e017905c20fbb9fc28ddea959&map=12/-36.8487/174.7734.
Saving the file as `test.geojson`, i do the following

```
>> import geopandas as gpd
>> test = gpd.read_file('test.geojson')
>> a = test[:1].copy()
>> b = test[1:2].copy()
>> geopandas.sjoin(a, b)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-39-ee0c0d3451ec> in <module>()
      2 a = test[:1].copy()
      3 b = test[1:2].copy()
----> 4 gpd.sjoin(a, b)

~/.virtualenvs/mbie_urban_rural/lib/python3.5/site-packages/geopandas/tools/sjoin.py in sjoin(left_df, right_df, how, op, lsuffix, rsuffix)
     55     idxmatch = idxmatch[idxmatch.apply(len) > 0]
     56 
---> 57     r_idx = np.concatenate(idxmatch.values)
     58     l_idx = np.concatenate([[i] * len(v) for i, v in idxmatch.iteritems()])
     59 

ValueError: need at least one array to concatenate  
```

**Comment by jdmcbr** [comment]
@araichev I can confirm that I see this with `geopandas=0.2.1` and `pandas=0.20.3`. However, when installing from master, I don't see any issue. Can you install from master and see if the behavior persists for you?

**Comment by araichev** [comment]
OK @jdmcbr, i installed GeoPandas from master and ran the same test, getting an empty GeoDataFrame as desired.

**Comment by jdmcbr** [comment]
@jzf2101 Would you try installing from master as well?
