### ISSUE TITLE
QST:How to get a correct group in my geopandas project?

### ISSUE THREAD

**Issue by forestbat** [geopandas/geopandas#2511]
I'm making a project which find the nearest linestring(simulate a river) to points or a single point,looks like this:
```
linestrings  points
linestring1  point1    
linestring2  point4     
linestring1  point2    
linestring2  point5
linestring1  point3    
linestring2  point6
```

And it looks like this in intellij idea: 

![图片](https://user-images.githubusercontent.com/23413915/181905193-c7813b92-f276-4763-ba20-4703e224a95d.png)

I want to group the dataframe by linestrings to insert points,like this:
```
linestrings  points
linestring1  point1    
linestring1  point2   
linestring1  point3    
linestring2  point4
linestring2  point5   
linestring2  point6
```

So that I can snap linestring1 to point 1,2,3 and so on.

[[Look at this picture,the same linestring should be snapped on 3 points](https://i.stack.imgur.com/ntH9P.png)]

However when I launch my code,I can only see dtypes in form of DataFrame:

![图片](https://user-images.githubusercontent.com/23413915/181905222-82591b25-7b8f-4ba1-aa12-9507365db043.png)

And group look like this：

![图片](https://user-images.githubusercontent.com/23413915/181905238-18481fdb-0a99-4eb4-bff0-f56ddf70e87b.png)

It's obvious that my attempt is failed，and in pandas'document，a correct group should looks like this: https://pandas.pydata.org/docs/user_guide/groupby.html#iterating-through-groups

So what's my problem and how I can solve it? This is a part of my code:

```(python)
list_point_line_tuple = []
    for point in gpd_nodes_df.geometry:
        list_point_line_tuple.append((point.to_wkt(), geopandas_min_dist(point, gpd_network_df, 200).geometry.to_wkt()))
    graph_frame = gpd.GeoDataFrame(list_point_line_tuple, columns=['near_stations', 'nearest_line'])
    grouped_graph_frame = graph_frame.groupby('nearest_line', as_index=False)
```

And all code is here: https://github.com/forestbat/stream-simulate-conda

**Comment by brendan-ward** [comment]
It looks like your viewer is showing the `dtypes` property of the groupby object, not the actual results.

My suggestion is to install `pygeos` and try [sjoin_nearest](https://geopandas.org/en/stable/docs/reference/api/geopandas.sjoin_nearest.html)

This gives the nearest line(s) per point; multiple lines if they are equidistant or intersecting the point:

```Python
results = gpd.sjoin_nearest(points, lines, max_distance=200).join(lines, on='index_right', rsuffix="_line")
```

(the `geometry` field of the lines dataframe will become `geometry_line`)


Or the nearest point(s) per line:

```Python
results = gpd.sjoin_nearest(points, lines, max_distance=200).join(lines, on='index_right', rsuffix="_point")
```

You need to groupby a non-geometry column.  You can group by the index of the left data frame, in this case `points` (first example above), then collect the line geometries into a list, if that's what you want:

```Python
lines_per_point = results.groupby(level=0).geometry_line.apply(list)
```

Or use `index_right` to group by the other data frame:

```Python
points_per_line = results.groupby('index_right').geometry.apply(list) 
```

Which you can then join back to the data frame indexed by the column you grouped by (i.e., `points` for first example, `lines` for second) to get a column of the original geometries:

```Python
lines_per_point = points.join(results.groupby(level=0).geometry_line.apply(list))
```

Or just do it in your group by:

```Python
lines_per_point = results.groupby(level=0).agg({'geometry': 'first', 'geometry_line': list})
```

**Comment by forestbat** [comment]
@brendan-ward Thanks for your reply，now I will close this issue and when I have other problems about GeoDataFrame，I will reopen it.
