### ISSUE TITLE
Error opening Geojson format with geopandas.readfile()

### ISSUE THREAD

**Issue by Enthdrive** [geopandas/geopandas#2521]
Hi, I have trouble opening a geojson file with geopandas.readfile(). The geojson file I checked and it's utf-8 encoded, furthermore every single online visualization tool is able to open it. On the other hand when I am trying to open just a couple of rows it works perfectly fine, but above 800 rows it crashes. 
I have installed geopanda through conda.
Fiona version is 1.8.13
Shapely version is 1.7.1

The error output is the following:
`data_all=geopandas.read_file(data)`

NotImplementedError                       Traceback (most recent call last)
Input In [7], in <cell line: 1>()
----> 1 data_all=geopandas.read_file(data)
      2 data_all.head()

File ~\Anaconda3\envs\mapping_env\lib\site-packages\geopandas\io\file.py:203, in _read_file(filename, bbox, mask, rows, **kwargs)
    198 if kwargs.get("ignore_geometry", False):
    199     return pd.DataFrame(
    200         [record["properties"] for record in f_filt], columns=columns
    201     )
--> 203 return GeoDataFrame.from_features(
    204     f_filt, crs=crs, columns=columns + ["geometry"]
    205 )

File ~\Anaconda3\envs\mapping_env\lib\site-packages\geopandas\geodataframe.py:587, in GeoDataFrame.from_features(cls, features, crs, columns)
    585     row.update(feature["properties"])
    586     rows.append(row)
--> 587 return GeoDataFrame(rows, columns=columns, crs=crs)

File ~\Anaconda3\envs\mapping_env\lib\site-packages\geopandas\geodataframe.py:138, in GeoDataFrame.__init__(self, geometry, crs, *args, **kwargs)
    127         warnings.warn(
    128             "CRS mismatch between CRS of the passed geometries "
    129             "and 'crs'. Use 'GeoDataFrame.set_crs(crs, "
   (...)
    135             stacklevel=2,
    136         )
    137         # TODO: raise error in 0.9 or 0.10.
--> 138     self["geometry"] = _ensure_geometry(self["geometry"].values, crs)
    139 except TypeError:
    140     pass

File ~\Anaconda3\envs\mapping_env\lib\site-packages\geopandas\geodataframe.py:43, in _ensure_geometry(data, crs)
     41     return GeoSeries(out, index=data.index, name=data.name)
     42 else:
---> 43     out = from_shapely(data, crs=crs)
     44     return out

File ~\Anaconda3\envs\mapping_env\lib\site-packages\geopandas\array.py:168, in from_shapely(data, crs)
    152 def from_shapely(data, crs=None):
    153     """
    154     Convert a list or array of shapely objects to a GeometryArray.
    155 
   (...)
    166 
    167     """
--> 168     return GeometryArray(vectorized.from_shapely(data), crs=crs)

File ~\Anaconda3\envs\mapping_env\lib\site-packages\geopandas\_vectorized.py:142, in from_shapely(data)
    140 aout = np.empty(len(data), dtype=object)
    141 with compat.ignore_shapely2_warnings():
--> 142     aout[:] = out
    143 return aout

File ~\Anaconda3\envs\mapping_env\lib\site-packages\shapely\geometry\base.py:854, in BaseMultipartGeometry.__array_interface__(self)
    851 @property
    852 def __array_interface__(self):
    853     """Provide the Numpy array protocol."""
--> 854     raise NotImplementedError("Multi-part geometries do not themselves "
    855                               "provide the array interface")

NotImplementedError: Multi-part geometries do not themselves provide the array interface

The geojson describes a testing track and seems to be a featurecollection as it starts as:
{"features":[{
    "geometry": {
        "coordinates": [
            [
                16.84055342358215,
                46.8848696610576,
                237.92634877734784
            ],
            [
......
I hope I provided enough information.

**Comment by martinfleis** [comment]
Hey, this is an issue with your environment. You most likely have shapely 1.7 (instead of the recent 1.8) and the latest numpy 1.23. These specific versions are incompatible. You either need to update shapely or downgrade numpy.

**Comment by Enthdrive** [comment]
> Hey, this is an issue with your environment. You most likely have shapely 1.7 (instead of the recent 1.8) and the latest numpy 1.23. These specific versions are incompatible. You either need to update shapely or downgrade numpy.

Thank you for the quick response. Is there an easy way to upgrade to the shapely 1.8? since `conda upgrade shapely` doesn't seem to do the trick neither another solution i found on twitter: `conda install -c conda-forge/label/shapely_dev shapely=1.8a1`

**Comment by martinfleis** [comment]
`conda install -c conda-forge shapely=1.8` doesn't work?

**Comment by Enthdrive** [comment]
> `conda install -c conda-forge shapely=1.8` doesn't work?

It gives me proxy error sadly. Does that have someting to do with the .condarc setup? 
ProxyError: Conda cannot proceed due to an error in your proxy configuration.
Check for typos and other configuration errors in any '.netrc' file in your home directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings.

**Comment by martinfleis** [comment]
I don't know, have never seen this error. It may be easiest for you to downgrade numpy in the end.

**Comment by Enthdrive** [comment]
> I don't know, have never seen this error. It may be easiest for you to downgrade numpy in the end.

Which version do you recommend?

**Comment by martinfleis** [comment]
numpy=1.22 should work. We internally pin for numpy=1.21 on our CI.

**Comment by Enthdrive** [comment]
> numpy=1.22 should work. We internally pin for numpy=1.21 on our CI.

Seems to be working just fine now, thank you so much :)
