### ISSUE TITLE
BUG:  Multi-part geometries do not themselves provide the array interface

### ISSUE THREAD

**Issue by liuhyhit** [geopandas/geopandas#2523]
```python
temp_shp = gpd.read_file("path_to_the_shapefile.shp")


```

#### Problem description

Cannot read some shapefile correctly. Error pop up saying: "NotImplementedError: Multi-part geometries do not themselves provide the array interface". This will occur when reading shapefiles from an intersection result by QGIS. I saw people post similar errors elsewhere: https://stackoverflow.com/questions/73059949/geopandas-not-reading-shapefiles. The code used to work well last month.

#### Expected Output

read successfully

#### Output of ``geopandas.show_versions()``

SYSTEM INFO
-----------
python     : 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
executable : C:\Anaconda\envs\spd_cam\python.exe
machine    : Windows-10-10.0.19044-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.0.2
GDAL data dir: None
PROJ       : 6.2.1
PROJ data dir: C:\Anaconda\envs\spd_cam\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.9.0
pandas     : 1.4.3
fiona      : 1.8.13.post1
numpy      : 1.23.1
shapely    : 1.7.1
rtree      : 0.9.7
pyproj     : 2.6.1.post1
matplotlib : 3.5.1
mapclassify: 2.4.3
geopy      : None
psycopg2   : None
geoalchemy2: None
pyarrow    : None
pygeos     : None

</details>

**Comment by martinfleis** [comment]
See #2521
