### ISSUE TITLE
BUG: CRS ValueError with read_file using shapely 1.8.3

### ISSUE THREAD

**Issue by DirkEilander** [geopandas/geopandas#2531]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example
Create test environment
```
mamba create python=3.10 geopandas=0.11.1 pygeos -n test_pygeos -c conda-forge
```
Python code
```
import geopandas as gpd
gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
```

#### Problem description
When both pygeos (0.12.0) and geopandas (0.11.1) and the latest version of shapely (1.8.3) are installed in the same environement the code above returns a value error (see below). This is solved by uninstalling pygeos or downgrading shapely to 1.8.2. For now I'd like to keep pygeos as I understand this is still required for some spatial index methods such as `sindex.nearest`. I don't know enough about the geopandas internals to understand if this is shapely or geopandas issue.

```ValueError: Assigning CRS to a GeoDataFrame without a geometry column is not supported. Supply geometry using the 'geometry=' keyword argument, or by providing a DataFrame with column name 'geometry'``` 

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 06:57:19) [MSC v.1929 64 bit (AMD64)]
executable : C:\Users\eilan_dk\Miniconda3\envs\shapely2\python.exe
machine    : Windows-10-10.0.19042-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.5.1
GDAL data dir: None
PROJ       : 9.0.1
PROJ data dir: C:\Users\eilan_dk\Miniconda3\envs\shapely2\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.11.1
numpy      : 1.23.2
pandas     : 1.4.3
pyproj     : 3.3.1
shapely    : 1.8.3
fiona      : 1.8.21
geoalchemy2: None
geopy      : None
matplotlib : 3.5.3
mapclassify: 2.4.3
pygeos     : 0.12.0
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : 1.0.0

</details>

**Comment by martinfleis** [comment]
Thanks for the report! I think that we see the similar behaviour on our CI here https://github.com/geopandas/geopandas/runs/7879591422?check_suite_focus=true#step:5:4136 It is triggered in a very specific situation though. Have you ran any other code before the snippet shown above?

**Comment by DirkEilander** [comment]
Thanks for the fast response! I have not run any other code before and can locally reproduce the error with just that code snippet.

**Comment by martinfleis** [comment]
@jorisvandenbossche are you aware of any changes in shapely 1.8.3 that could've caused this? From the changelog, I am not sure where to look.

**Comment by theroggy** [comment]
In my case at least it seems to be triggered by upgrading underlying dependencies of geopandas. When creating a pull request on https://github.com/geofileops/geofileops this afternoon I had (many) of these errors but I couldn't reproduce locally till I upgraded shapely... 
But: upgrading shapely triggered a whole lot of other dependencies to be upgraded, so not sure what the initial culprit is/was.

**Comment by martinfleis** [comment]
There are only 4 changes on our CI

```diff
- libopenblas               0.3.21          pthreads_h78a6416_0    conda-forge
+ libopenblas               0.3.21          pthreads_h78a6416_1    conda-forge
- matplotlib-base           3.5.2           py310h5701ce4_1    conda-forge
+ matplotlib-base           3.5.3           py310h5701ce4_1    conda-forge
- setuptools                65.0.1          py310hff52083_0    conda-forge
- shapely                   1.8.2           py310h5e49deb_3    conda-forge
+ setuptools                65.0.2          py310hff52083_0    conda-forge
+ shapely                   1.8.3           py310h5e49deb_0    conda-forge
```

Out of these, only shapely makes sense to cause a trouble here.

**Comment by theroggy** [comment]
pinning shapely to <1.8.3 indeed solves the issue for me...

**Comment by jorisvandenbossche** [comment]
We will do a quick 1.8.4 to fix this

**Comment by bidhya** [comment]
> We will do a quick 1.8.4 to fix this

Update 1.8.4 seems to fix the issue
