### ISSUE TITLE
Deprecate GeoSeries.almost_equals (deprecated in shapely)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#2538]
The `almost_equals` method in Shapely is deprecated (and will be removed in a future version): https://github.com/shapely/shapely/blob/6c896a7fb0348f46630e4045e1fdc3e54212dc42/shapely/geometry/base.py#L666-L669

So we should probably follow suite in geopandas as well and deprecate our almost_equals method in favor of its alias `equals_exact`

**Comment by shraddhafalane** [comment]
Would like to take this up

**Comment by martinfleis** [comment]
@shraddhafalane Go for it ;)

**Comment by shraddhafalane** [comment]
Could you please elaborate more on task. I can see  `geom_almost_equals` instead of `almost_equals`.

**Comment by m-richards** [comment]
Hey @shraddhafalane sorry unless I'm missing something this has already been done as #2267.

There is however one small follow up, https://github.com/geopandas/geopandas/blob/4d29fcfeb065bdcd7fc69968dd647140772cd5cf/geopandas/_vectorized.py#L720-L724

this `almost_equals` in `_vectorized.py` was missed in that pull request and seems to be dead code now.

**Comment by jorisvandenbossche** [comment]
@m-richards I think that was an internal deprecation in geopandas we where we had "geom_almost_equals" on GeoSeries and "almost_equals" on GeometryArray, so we deprecated `GeometryArray.almost_equals` for `GeometryArray.geom_almost_equals` to make that consistent internally.
But so this is another issue, in shapely "almost_equals" was deprecated in favor of "equals_exact", and that change is not yet reflected in geopandas.

@shraddhafalane indeed, in geopandas this is `geom_almost_equals`, so it is that one that I think we want to deprecate.

**Comment by m-richards** [comment]
Right, don't know how I missed that, sorry @shraddhafalane for the confusion.

**Comment by darshanip** [comment]
Seems nobody is working on this, i'll grab it. @m-richards

**Comment by PluT00** [comment]
Could I take this issue?

**Comment by martinfleis** [comment]
@PluT00 It already is being resolved in #2604.

**Comment by darshanip** [comment]
Update: I've restarted working on this.

**Comment by martinfleis** [comment]
Closed by https://github.com/geopandas/geopandas/pull/3017
