### ISSUE TITLE
Update user documentation

### ISSUE THREAD

**Issue by kjordahl** [geopandas/geopandas#254]
The user docs should include everything that's current before releasing 0.2. For example, spatial joins aren't mentioned.

**Comment by micahcochran** [comment]
How can we help update the docs?

**Comment by kjordahl** [comment]
@micahcochran You could build the docs locally (particularly the [user guide](https://raw.githubusercontent.com/geopandas/geopandas/master/doc/source/user.rst)) and see if anything is out of date. It would be great to have better human-readable documentation as well, but at minimum it should be up-to-date with what's currently in master. There are certainly some things missing, and others that have changed since 0.1.1 was released.

I'm also working on getting the readthedocs build working again, it's very out of date.

**Comment by kjordahl** [comment]
Working on a up-to-date live build of the docs as they exist on master: #255

**Comment by kjordahl** [comment]
@micahcochran To be more specific, adding things that are missing, fixing things that are incorrect, or otherwise improving the docs directly would be most useful. If you can't do that, submitting issues for any errors and omissions is useful as well.

**Comment by jorisvandenbossche** [comment]
I think the docs are currenlty in a decent state (and readthedocs works and has always the latest docs), so closing this issue. If there are missing parts, let's open more specific issues.
