### ISSUE TITLE
clip does not work on the case of polygon that crosses more than one clip area

### ISSUE THREAD

**Issue by RicardoGomesIST** [geopandas/geopandas#2547]
Hi,
I have two shapefiles with polygons. One with buildings (zone.shp) and other with municipalities (munic.shp).
I would like to clip the zone.shp using the municipality polygons.
lets assume: 
zone: geodf with all the buildings (from zone.shp)
muni: geodf with all the mun (from munic.shp)
And I would like to have the buildings from the municipality "Lisbon"

buildings_Lisbon=zone.clip(muni.loc[muni['NAME_2'] == 'Lisbon'], True)

clip works 99% fine but when one building cross 2 municipalities it divides the polygon in two (unwanted result). I would rather lost that building at all. 
So:
here I have the buildings and the one that cross the 2 municipalities borders

![image](https://user-images.githubusercontent.com/52715280/189172662-26d158a8-994e-492e-94c3-bfb780761958.png)

here I have the result. The building was divided on 2 polygons. 
![image](https://user-images.githubusercontent.com/52715280/189172974-b13fd833-2393-4ede-903d-d128721c2619.png)

note I tried: buildings_Lisbon=zone.clip(muni.loc[muni['NAME_2'] == 'Lisbon'], False) also. Some result.

**Comment by RicardoGomesIST** [comment]
I found that I can explode and then drop duplicates

**Comment by martinfleis** [comment]
Exploding is one way. The other would be to do the spatial join, not clip. You would want sjoin with the "within" predicate in this case.
