### ISSUE TITLE
BUG: clip messes the order of attributes with pandas 1.5.0

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2558]
There is a bug somewhere that affects `clip` in special cases that may be a regression in pandas but I wasn't able to create a MRE without geopandas and can't dig further so reporting what I know now.

In some cases (not entirely sure which), `clip` breaks the relationship between geometries and their attributes. See the MRE below as an illustration. I was able to track it down all the way to this line https://github.com/geopandas/geopandas/blob/af50debbbbeab62f3601518f814c9cb271b1859c/geopandas/tools/clip.py#L66-L68 and even abstract that a bit into the MRE but can't really tell what is going on here (and have to go to bed now). Also, I wasn't able to get MRE without using my real-world data (but I didn't spend a lot of time on that), so those are linked.

```py
import geopandas
import numpy
import matplotlib.pyplot as plt

gdf = geopandas.read_parquet('s3://martinfleis-public/sample.parquet')
gdf
```
```
      uID                                           geometry
6870    0  POLYGON ((-298.354 -763.018, -298.379 -762.971...
6873    1  POLYGON ((-308.406 -746.396, -308.816 -745.725...
6877    2  POLYGON ((-317.850 -727.697, -318.396 -726.859...
6878    3  POLYGON ((-337.918 -771.098, -338.093 -770.145...
6879    4  POLYGON ((-362.347 -759.197, -365.199 -760.764...
6880    5  POLYGON ((-338.524 -767.073, -338.620 -766.559...
6881    6  POLYGON ((-370.127 -769.426, -371.391 -768.427...
6882    7  POLYGON ((-373.393 -806.792, -373.794 -806.084...
6883    8  POLYGON ((-410.986 -794.666, -410.966 -794.190...
6891    9  POLYGON ((-392.646 -815.823, -393.100 -815.036...
6909   10  POLYGON ((-363.594 -836.341, -364.021 -835.565...
6910   11  POLYGON ((-299.771 -809.769, -300.367 -809.152...
6934   12  POLYGON ((-418.106 -764.244, -427.218 -745.319...
6936   13  POLYGON ((-396.057 -731.722, -396.372 -730.911...
6937   14  POLYGON ((-404.471 -710.729, -404.756 -709.742...
8955   15  POLYGON ((-320.365 -823.671, -320.364 -823.671...
8956   16  POLYGON ((-308.483 -819.283, -309.092 -818.726...
8997   17  POLYGON ((-380.569 -702.722, -381.014 -701.797...
8998   18  POLYGON ((-363.734 -694.758, -363.600 -694.338...
8999   19  POLYGON ((-354.393 -715.943, -354.272 -715.469...
9000   20  POLYGON ((-365.996 -729.252, -367.081 -729.305...
```
```py
clipped = gdf.copy()
clipped.loc[numpy.ones(len(clipped), dtype=bool), 'geometry'] = clipped.geometry.values
 # the line above breaks the relationship between `uID` and index,  and geometry.
```
An easy way to compare the two is to plot `uID`:
```py
fig,axs = plt.subplots(1, 2, figsize=(12, 12))
gdf.plot('uID', ax=axs[0], cmap="Spectral")
clipped.plot('uID', ax=axs[1], cmap="Spectral")
```

![Screenshot 2022-09-21 at 23 38 24](https://user-images.githubusercontent.com/36797143/191615173-9a00a65c-9476-40e5-9f9d-9c85fa0b68e0.png)

While this is what we get with pandas 1.4.4, two equal maps as expected:

![Screenshot 2022-09-21 at 23 38 55](https://user-images.githubusercontent.com/36797143/191615252-8286f3cc-5358-4828-af11-fdb7c81930f9.png)

So the bug happens inside of `clip` but it is not caused in `clip` but I believe somewhere in pandas.

**Comment by jorisvandenbossche** [comment]
@martinfleis I can take a further look. 
But do you have another way to share the data? I get *"OSError: When getting information for key 'sample.parquet' in bucket 'martinfleis-public': AWS Error ACCESS_DENIED during HeadObject operation: No response body."* when trying to read the file.

**Comment by jorisvandenbossche** [comment]
OK, based on your sdss22-workshop, I was able to reproduce it:

```python
import osmnx
place = "St. Gallen, St. Gallen, Schweiz"
local_crs = 2056
buildings = osmnx.geometries.geometries_from_place(place, tags={"building": True})
buildings = buildings[buildings.geom_type == "Polygon"].reset_index(drop=True)
buildings = buildings[["geometry"]].to_crs(local_crs)
buildings["uID"] = range(len(buildings))

gdf = buildings.copy()
gdf_sub = gdf.iloc[np.array([6870, 6873, 6877, 6878, 6879, 6880, 6881, 6882, 6883, 6891, 6909, 6910, 6934, 6936, 6937, 8955, 8956, 8997, 8998, 8999, 9000])].copy()
print(gdf_sub)
gdf_sub.loc[np.ones(len(gdf_sub), dtype=bool), 'geometry'] = gdf_sub.geometry.values
print(gdf_sub)
```

It turns out this is because pandas ends up in a code path that (I assume) expects a non-boolean indexer (it does `np.argsort` on it, which then returns a random order for all-True boolean array): https://github.com/pandas-dev/pandas/blob/71fc89cd515c3c19230fbab64e979118858b808a/pandas/core/indexing.py#L1990 
Based on where this happens in pandas, I was able to create a simple pandas reproducer:

```
In [1]: df = pd.DataFrame({'idx': range(20), 'col': np.arange(20, dtype="float")})

In [2]: df.loc[np.ones(len(df), dtype=bool), 'col'] = df.col.values

In [3]: df
Out[3]: 
    idx   col
0     0   0.0
1     1  17.0
2     2  16.0
3     3  15.0
4     4  14.0
5     5  13.0
6     6  12.0
7     7  11.0
8     8  10.0
9     9   9.0
10   10   8.0
11   11   7.0
12   12   6.0
13   13   5.0
14   14   4.0
15   15   3.0
16   16   2.0
17   17   1.0
18   18  18.0
19   19  19.0
```

(it seems that it needs a somewhat larger dataframe, eg with 10 elements instead of 20, the np.argsort doesn't return scrambled indices)

In practice, for `geopandas.clip`, this will only happen if the mask is all-True values.

**Comment by martinfleis** [comment]
It was in the meantime reported to pandas by someone else as well https://github.com/pandas-dev/pandas/issues/48701

**Comment by rosepearson** [comment]
Glad to see this has been reported this is impacting me as well. I'm just updating to pandas 1.5.1 to see if the pandas related cases that have already closed resolve this behaviour. They do see to resolve the behaviour I was experiencing. Thank-you :)

**Comment by martinfleis** [comment]
Fixed in upstream.
