### ISSUE TITLE
Minor typo in docs

### ISSUE THREAD

**Issue by william-chu-github** [geopandas/geopandas#2563]
https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.boundary.html

"Returns a GeoSeries of lower dimensional objects representing each geometries’s set-theoretic boundary."

"geometries’s" ought to be "geometry's"

**Comment by shogohida** [comment]
Hi @william-chu-github @martinfleis 
Can I work on this? I haven't contributed to any issues so far but this looked easy as my first one.

**Comment by william-chu-github** [comment]
@shogohida, please do. I'm new to github and haven't had time to figure out how to properly do updates.

**Comment by m-richards** [comment]
Fixed in #2586
