### ISSUE TITLE
QST: to_file fails if the geometry column does not have the exact name `geometry`

### ISSUE THREAD

**Issue by mcsoini** [geopandas/geopandas#2565]
I just documented an issue with `to_frame` [on SO](https://stackoverflow.com/questions/73842773/typeerror-when-writing-geopandas-geodataframe/73842774#73842774): Am I correct in my interpretation that `to_file` only works if the geometry column is called `geometry`, hence excluding the possibility to write GeoDataFrames with mulitlevel columns? If so, could this be caught a bit earlier with a more explicit error message when compared to `TypeError: Cannot interpret '<geopandas.array.GeometryDtype object at 0x7f99fdf45070>' as # a data type`?

**Comment by m-richards** [comment]
Hi @mcsoini, to_file can write any single level column name provided it is correctly set with `set_geometry`. We don't however support writing multiindex column names - there's not a great way of serialising that information, and such serialisation would be format dependent. 

I believe however this might be possible with `to_parquet` (not at a computer to check), noting that other tools that can read geoparquet may not necessarily handle multilevel columns. 

You are right though this error message could be more explicit.

**Comment by mcsoini** [comment]
Thanks for the reply!

> to_file can write any single level column name provided it is correctly set with set_geometry

Is that really the case? If I try writing an example from the [docs](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.set_geometry.html) using `set_geometry`, it also fails as soon as the geometry column is not called "geometry":

```
from shapely.geometry import Point

d = {'col1': ['name1', 'name2'], 'geometry': [Point(1, 2), Point(2, 1)]}
gdf = geopandas.GeoDataFrame(d, crs="EPSG:4326")
df1 = gdf.set_geometry([Point(0,0), Point(1,1)])

# `geometry` is column with name `geometry` => works
df1.to_file("test1.shp")

gdf["buffered"] = gdf.buffer(2)
df2 = gdf.set_geometry("buffered")

# `geometry` is column with name `buffered` => fails
df2.to_file("test2.shp")

**Comment by m-richards** [comment]
As you'll see in the docs, `set_geometry` takes a column label or array as it's first parameter - if I take your case from SO:
```python
In [1]: import pandas as pd
   ...: import geopandas
   ...: df = pd.DataFrame([[1, 0], [0, 1]], columns=[['location', 'location'], ['x', 'y']])
   ...: df["geometry"] = geopandas.points_from_xy(df['location','x'], df['location', 'y'])
   ...: gdf = geopandas.GeoDataFrame(df, geometry="geometry", crs="EPSG:4326")
   ...: gdf
Out[1]:
  location                    geometry
         x  y
0        1  0  POINT (1.00000 0.00000)
1        0  1  POINT (0.00000 1.00000)

In [2]: gdf.columns = ["_".join(x) for x in gdf.columns]

In [3]: gdf.geometry
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [3], in <cell line: 1>()
----> 1 gdf.geometry
--> 233     raise AttributeError(msg)
    234 return self[self._geometry_column_name]

AttributeError: You are calling a geospatial method on the GeoDataFrame, but the active geometry column ('geometry') is not present.
There are columns with geometry data type (['geometry_']), and you can either set one as the active geometry with df.set_geometry("name") or access the column as a GeoSeries (df["name"]) and call the method directly on it.

In [4]: gdf.columns
Out[4]: Index(['location_x', 'location_y', 'geometry_'], dtype='object')

In [5]: gdf = gdf.set_geometry("geometry_")

In [6]: gdf.to_file("tmp.gpkg")

```

Hope this helps, a little more on the concept of active geometry column is in the docs at https://geopandas.org/en/stable/docs/user_guide/data_structures.html#geodataframe which you might also find useful.

**Comment by mcsoini** [comment]
Thanks, very helpful, that explains my SO example. Yet I still don't see why my other example above would not work, as the geometry attribute of `df2` is correctly set to `buffered` right before `to_file` fails.

**Comment by m-richards** [comment]
> Thanks, very helpful, that explains my SO example. Yet I still don't see why my other example above would not work, as the geometry attribute of `df2` is correctly set to `buffered` right before `to_file` fails.

Sorry I missed this separate point, the issue in this case is that you're trying to write a geodataframe with multiple geometry columns to file. As far as I'm aware, geoparquet is the only format natively supporting this, writing with `gdf.to_parquet`, any other format involves serialising via wkt, wkb. But your example does point out that the error message doesn't indicate that at all.
