### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by Kevin-Wettaka** [geopandas/geopandas#2567]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

#### Output of ``geopandas.show_versions()``

<details>

[ImportError: DLL load failed: The specified procedure could not be found.]

</details>

**Comment by martinfleis** [comment]
Hello, I will close this issue as it contains no information. Feel free to edit the first issue to fill the "form" and reopen it.
