### ISSUE TITLE
Bug in apply with geometry?

### ISSUE THREAD

**Issue by cdagnino** [geopandas/geopandas#257]
I'm using

Geopandas '0.1.0.dev-b3d07f3'
Python 3.5.0
Shapely '1.5.11'
Pandas '0.17.1'

I'm pretty sure this example used to work and I don't see why it's giving me an error now:

```python
#setup
import shapely.geometry as geom
import numpy as np
import pandas as pd
import geopandas as gpd

lines = gpd.GeoSeries(
    [geom.LineString(((1.4, 3), (0, 0))),
        geom.LineString(((1.1, 2.), (0.1, 0.4))),
        geom.LineString(((-0.1, 3.), (1, 2.)))])

# 10 points
points = gpd.GeoSeries([geom.Point(x, y) for x, y in np.random.uniform(0, 3, (10, 2))])
# Put the points in a dataframe, with some other random column
df_points = gpd.GeoDataFrame(np.array([points, np.random.randn(10)]).T)
df_points.columns = ['geometry', 'Property1']

# Calculate the minimum distance between each point and the lines

def min_distance(point, lines):
    return lines.distance(point).min()

df_points['min_distance'] = df_points.geometry.apply(min_distance, lines)
````

gives the traceback:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-22fcf36c46b7> in <module>()
      7     return lines.distance(point).min()
      8 
----> 9 df_points['min_distance'] = df_points.geometry.apply(min_distance, lines)
     10 

/Users/cd/anaconda3/lib/python3.5/site-packages/pandas/core/series.py in apply(self, func, convert_dtype, args, **kwds)
   2167             values = lib.map_infer(values, lib.Timestamp)
   2168 
-> 2169         mapped = lib.map_infer(values, f, convert=convert_dtype)
   2170         if len(mapped) and isinstance(mapped[0], Series):
   2171             from pandas.core.frame import DataFrame

pandas/src/inference.pyx in pandas.lib.map_infer (pandas/lib.c:62425)()

/Users/cd/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py in __nonzero__(self)
    729         raise ValueError("The truth value of a {0} is ambiguous. "
    730                          "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
--> 731                          .format(self.__class__.__name__))
    732 
    733     __bool__ = __nonzero__

ValueError: The truth value of a GeoSeries is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

On the other hand, applying the function one point at a time works fine:

```python
one_point = df_points.geometry.iloc[0]
lines.distance(one_point).min()

Out[3]: 2.2731225746283781
```

If I understand  `apply` correctly, it should work too.
It may be something that changed on `pandas`side too...

**Comment by micahcochran** [comment]
[pandas.DataFrame.apply](http://pandas.pydata.org/pandas-docs/version/0.17.1/generated/pandas.DataFrame.apply.html) for the initiated (me)

**Comment by cdagnino** [comment]
@micahcochran, I didn't get your comment

**Comment by jorisvandenbossche** [comment]
@cdagnino Thanks for the report

In any case, the following works:

- using the `args` keyword:
  ```
df_points['min_distance'] = df_points.geometry.apply(min_distance, args=(lines, ))
  ```

- using a lambda:
  ```
df_points['min_distance'] = df_points.geometry.apply(lambda x: min_distance(x, lines))
  ```

What version of pandas were you using before? With 0.16.2, this already fails as well. `Series.apply` has as the second argument `convert_dtype`, which this expects a bool and therefore you are seeing that error. But this keyword has been there already a long time

**Comment by cdagnino** [comment]
@jorisvandenbossche I don't recall which version I had. Maybe 0.16.1?
Is this something that should be fixed or is it just a consequence of `pandas` new syntax and hence I should just adapt?

**Comment by jorisvandenbossche** [comment]
I don't think this is something that should be fixed. Given the signature of `Series.apply`, your function call (`df_points.geometry.apply(min_distance, lines)`) seems wrong. 
I would find it surprising that this worked in 0.16.1. This keyword (`convert_dtype`, see http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.apply.html) has been there since pandas 0.8.0. Are you sure you didn't change anything else in your code?

So to answer, I think you should adapt your code.

**Comment by cdagnino** [comment]
@jorisvandenbossche I might have changed something else in the code, but thanks for your answer, now I understand why it fails!
I'll close this issue now.
