### ISSUE TITLE
BUG: _delgate_binary_method warning misleading

### ISSUE THREAD

**Issue by kai-tub** [geopandas/geopandas#2582]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Problem description

Hey,
I personally find that the warning generated by any binary method with `align=True` is a bit unintuitive.
I was wondering why I was getting user warnings when applying to `Geoseries.difference` between two series with differently _ordered_ indexes and `align=True`.
When I explicitly set `align=True` I would expect _no_ warning (if they just have to be re-aligned).

https://github.com/geopandas/geopandas/blob/0915c2fde66059dd8a934288d8597efc55a46107/geopandas/base.py#L26-L44

#### Code
MWE taken from the documentation:
```python
from shapely.geometry import Polygon, LineString, Point
s = geopandas.GeoSeries(
    [
        Polygon([(0, 0), (2, 2), (0, 2)]),
        Polygon([(0, 0), (2, 2), (0, 2)]),
        LineString([(0, 0), (2, 2)]),
        LineString([(2, 0), (0, 2)]),
        Point(0, 1),
    ],
)
s2 = geopandas.GeoSeries(
    [
        Polygon([(0, 0), (1, 1), (0, 1)]),
        LineString([(1, 0), (1, 3)]),
        LineString([(2, 0), (0, 2)]),
        Point(1, 1),
        Point(0, 1),
    ],
    index=range(1, 6),
)
s.difference(s2, align=True)
```
Especially since the documentation 'hides' the user warning I assumed there was an issue with my indexes.
As of now, I will always reorder my indexes to match up and set `align=True` to not trigger the warning due to the failing index-equals.

#### Expected Output

No warning. Or only a warning if something _happens_ that might be unexpected

#### Possible solution:

Extend the check to only trigger the warning if indexes are missing or something _implicitely_ happens.
Or, at least update the warning message that they are 'differently ordered' (though then I would argue what the point of align=True is when it indirectly _just_ informs me what it is doing?)
Maybe the default value could be `None` and assume `align=True` with the current warning, and if set to `align=True` no warning if the data is only re-ordered?

#### Output of ``geopandas.show_versions()``

<details>
Failed `CDLL(libgeos_c.so.1)`
Failed `CDLL(libgeos_c.so)`

SYSTEM INFO
-----------
python     : 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:32:32)  [GCC 9.3.0]
executable : bigearthnet-label-updater/.venv/bin/python
machine    : Linux-5.4.0-126-generic-x86_64-with-glibc2.27

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.4.1
GDAL data dir: .venv/lib/python3.9/site-packages/fiona/gdal_data
PROJ       : 8.2.0
PROJ data dir: .venv/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.11.1
numpy      : 1.23.1
pandas     : 1.4.3
pyproj     : 3.3.1
shapely    : 1.8.2
fiona      : 1.8.21
geoalchemy2: None
geopy      : None
matplotlib : 3.6.0
mapclassify: 2.4.3
pygeos     : 0.12.0
pyogrio    : None
psycopg2   : None
pyarrow    : 6.0.1
rtree      : None

</details>

Thank! :pray:

**Comment by martinfleis** [comment]
Hey, thanks for the suggestion! Some of this has already been discussed. See #1832.
