### ISSUE TITLE
QST: How to plot Lat Lon point with geometry

### ISSUE THREAD

**Issue by timothyslau** [geopandas/geopandas#2584]
- [X] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

*I have geometry data that I want to plot along with the Latitude and Longitude as points on the graph.*

geopandas 0.11.1
python 3.9.0

```python
import geopandas as gpd
request.urlretrieve("https://raw.githubusercontent.com/Nowosad/spData/dd7634092a150e5d77d4d9b5d28fe77b739643ad/inst/shapes/boston_tracts.dbf", "~boston_tracts.dbf")
bstn = gpd.read_file(filename="boston_tracts.dbf")
gpd.GeoDataFrame(data=bstn[["LAT", "LON"]], geometry=bstn["geometry"]).plot(figsize=(15,10), marker="o", markersize=5)

```
![a32a2d08-1182-443f-85e8-09b7effd090b](https://user-images.githubusercontent.com/3031952/194417087-3fed191a-96bf-4734-a670-c4a38b084b03.png)

**Comment by martinfleis** [comment]
You need (ideally) to create a GeoSeries out of coordinates to properly work with it.

```py
gdf = gpd.GeoDataFrame(data=bstn[["LAT", "LON"]], geometry=bstn["geometry"])
ax = gdf.plot(figsize=(15,10))
gpd.GeoSeries.from_xy(gdf.LON, gdf.LAT).plot(ax=ax, marker="o", markersize=5, color="black")
```
![3e4c741d-c99b-43ab-9d33-b43b501c4e73](https://user-images.githubusercontent.com/36797143/194486724-148f0d52-ce5a-4ef0-a09f-cc7aed57baf5.png)
