### ISSUE TITLE
VIS/PERF: implement plotting using matplolib Collections

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#259]
The current plotting methods plot each Point/LineString/Polygon one at a time (see eg [here](https://github.com/geopandas/geopandas/blob/v0.1.1/geopandas/plotting.py#L202)). 
This means that when plotting a series of eg 100 Points, you end up with a plot consisting of 100 Line2D instances each consisting of a single point. 
The consequence is that the plotting methods are currently rather slow once you have a larger number of points/lines/polygons to plot.

A possible solution is using matplotlib `Collections`s. When having a series with uniform geom_type, this can lead to a speed-up of factor 10x. I experimented a little bit with it, of which you can see the results in this notebook (with some timings as well): http://nbviewer.ipython.org/gist/jorisvandenbossche/999d8af2ba69358a2bc8

As a reference, `pysal` uses a similar approach (@darribas noted this), and `cartopy` also uses collections I think, but then also wraps it in an Artist, but not really familiar with that.

Implementation wise, it is not that difficult, see the notebook I provided. To integrate the functions in the notebook in the `.plot()` method, this can be achieved by detecting the cases where there is a uniform geom_type. 

cc @IamJeffG @darribas @maxalbert  (you all did some plotting PRs recently)

**Comment by IamJeffG** [comment]
Are multi-type GeoSeries (mixing points and lines and polys) something we want to commit to maintaining in plotting?  It works now, but you get very silly looking plots if you try to override most kwargs on such a GeoSeries.  Here's an example, using variables defined in your notebook:

    ser = GeoSeries(pd.concat( (s_points[[20]], s_lines[[1]], s_poly[[5]]) ))
    ser.plot(markersize=10, marker="v")

![manytypes](https://cloud.githubusercontent.com/assets/2002703/12214358/c54bdf7c-b645-11e5-99d7-9b147f973d91.png)

This (actually, our current selection of plotting defaults) also creates some challenges with respect to legends.  Polygons get 0.5 alpha transparency but Points have 0, so should we include the transparency in the colorbar?

That said, I'm not aware of any problems with multi-type Series outside of plotting, so I'd be ok if we agree that we do need to maintain support. (But I might lean toward changing those alpha defaults!)

**Comment by IamJeffG** [comment]
Turns out you can use Collections even without uniformly-typed GeoSeries!  See my PR for a first pass at this.

**Comment by jorisvandenbossche** [comment]
Ah, stupid (of *me* I mean!), I had already a rough working branch, but didn't do a PR yet. Hopefully we didn't too much duplicate work. See https://github.com/geopandas/geopandas/compare/master...jorisvandenbossche:plot-collections

**Comment by IamJeffG** [comment]
Whoops!  We definitely take different approaches.  My change is more disruptive but I hope it makes things simpler for long-term maintenance.  Yours looks good too though.

**Comment by IamJeffG** [comment]
#267 implements this feature in full.
