### ISSUE TITLE
ENH: Support Python 3.11

### ISSUE THREAD

**Issue by EwoutH** [geopandas/geopandas#2592]
Python 3.11 is expected to be released as stable around October 24th, with many new features including:

> - [PEP 657](https://www.python.org/dev/peps/pep-0657/) -- Include Fine-Grained Error Locations in Tracebacks
> - [PEP 654](https://www.python.org/dev/peps/pep-0654/) -- Exception Groups and except*
> - [PEP 673](https://www.python.org/dev/peps/pep-0673/) -- Self Type
> - [PEP 646](https://www.python.org/dev/peps/pep-0646/)-- Variadic Generics
> - [PEP 680](https://www.python.org/dev/peps/pep-0680/)-- tomllib: Support for Parsing TOML in the Standard Library
> - [PEP 675](https://www.python.org/dev/peps/pep-0675/)-- Arbitrary Literal String Type
> - [PEP 655](https://www.python.org/dev/peps/pep-0655/)-- Marking individual TypedDict items as required or potentially-missing
> - [bpo-46752](https://bugs.python.org/issue46752)-- Introduce task groups to asyncio
> - The [Faster Cpython Project](https://github.com/faster-cpython) is already yielding some exciting results: this version of CPython 3.11 is ~ 19% faster on the geometric mean of the [PyPerformance benchmarks](https://speed.python.org/), compared to 3.10.0.

The state of the Python 3.11 ecosystem is already great:

- ✅ The regular scientific computing stack is in excellent shape. NumPy and Pandas support Python 3.11 and have wheels available, as do SciPy, Matplotlib and Seaborn. Tools like, Black and pre-commit and pytest also support Python 3.11.
- The geospatial stack is build on top of those, and now also gaining Python 3.11 support very quickly
  - 🚀 fiona the [CI passes](https://github.com/Toblerity/Fiona/pull/1147) for 3.11, wheel building is being worked on. See tracking issue: https://github.com/Toblerity/Fiona/issues/1087
  - ✅ shapely just released version [1.8.5](https://github.com/shapely/shapely/releases/tag/1.8.5), with 3.11 wheels on PyPI!
  - ✅ pyproj supports Python 3.11 and has wheels on PyPI
  - ✅ SQLAlchemy idem dito
  - ✅ rtree just released their [1.0.1](https://github.com/Toblerity/rtree/releases/tag/1.0.1) release which include Python 3.11 support and wheels!
  - ✅ geopy has a version-independent Python wheel available

GeoPandas is the glue that connects the whole geospatial Python stack. I think it would very well be possible to have full Python 3.11 support in GeoPandas before the official release! (currently planned for October 24th). Would that be a target to aim for?

**Comment by martinfleis** [comment]
Given geopandas is pure python, it should be straightforward as soon as all dependencies have 3.11 support. If you'd like to figure out a CI env that may test it right now, go for it!

**Comment by EwoutH** [comment]
Thanks for getting back! I think aside from the GeoPandas dependencies, the CI relying on Conda will be the hold up. Conda is quite slow with adopting new Python versions. I don't think Conda is needed if all dependencies have wheels on PyPI available, right?

I think moving the dependencies and the optional docs/dev dependencies to the [`pyproject.toml`](https://github.com/geopandas/geopandas/blob/main/pyproject.toml) would also help. The number of needed dependencies for each kind of job can be reduced quite a bit probably.

**Comment by martinfleis** [comment]
> I think aside from the GeoPandas dependencies, the CI relying on Conda will be the hold up. Conda is quite slow with adopting new Python versions. I don't think Conda is needed if all dependencies have wheels on PyPI available, right?

Yes, it can be a bit cumbersome initially. You don't need conda to install geopandas so we should also be able to create a CI env without it if we really want. It just adds some complexity to our  CI setup I am not sure I am happy about.

> I think moving the dependencies and the optional docs/dev dependencies to the [pyproject.toml](https://github.com/geopandas/geopandas/blob/main/pyproject.toml) would also help.

See https://github.com/geopandas/geopandas/pull/2512

**Comment by EwoutH** [comment]
shapely just released version [1.8.5](https://github.com/shapely/shapely/releases/tag/1.8.5), with 3.11 wheels on PyPI! Only Fiona is left of the direct dependencies!

Conda is working on it, see tracking issue https://github.com/conda/conda/issues/11170.
