### ISSUE TITLE
DEP: matplotlib 3.5 deprecates `get_cmap()`

### ISSUE THREAD

**Issue by rraymondgh** [geopandas/geopandas#2601]
matplotlib 3.5 generate deprecation warnings. Removing from https://github.com/geopandas/geopandas/pull/2572

This just shows a working approach.  Will generate a PR

```
    try:
        from matplotlib import colormaps as cm_

        cm_["viridis"].resampled(10)

        def _cm(cmap, lut=None):
            cmap = "viridis" if not cmap else cmap
            cm = cm_[cmap]
            return cm.resampled(lut) if lut else cm

    except (ImportError, AttributeError):
        import matplotlib.cm as cm_

        def _cm(cmap, lut=None):
            return cm_.get_cmap(cmap, lut)
```

**Comment by jorisvandenbossche** [comment]
There is already a PR! -> https://github.com/geopandas/geopandas/pull/2596 (didn't check in detail, but assuming it is the same)

**Comment by rraymondgh** [comment]
dealt with in https://github.com/geopandas/geopandas/pull/2596
