### ISSUE TITLE
ENH: Allow autolim keyword argument in plots

### ISSUE THREAD

**Issue by juseg** [geopandas/geopandas#2602]
#### Is your feature request related to a problem?

I use geopandas to reproject global (e.g. Natural Earth) data and plot it for small regions. This causes axes limits to update to encompass the global (and often badly distorted) data

```python
import geopandas

# open Natural Earth data for the world and Greenland
world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
greenland = world[world.name == 'Greenland']

# suppose we make a map of Greenland
ax = greenland.plot()

# check axes limits
print(ax.get_ylim())  # ca. 60 to 85 degrees North

# add other country borders for context
# (I want to add autolim=False)
ax = world.plot(ax=ax, color='0.75', zorder=-1)

# axes limits have been updated though
print(ax.get_ylim())  # ca. -90 to 90 degrees
```

I wish I could prevent geopandas from updating axes limits when plotting a dataframe.

#### Describe the solution you'd like

`GeoDataFrame.plot` should get a new parameter `autolim`. This is forwarded to matplotlib's `ax.add_collection`. Suggested docstring:

```python
    autolim : bool (default True)
        Update axes data limits to contain the new geometries.
```

#### API breaking implications

None. If `autolim` defaults to `True`, I think this will be fully backward-compatible:

https://github.com/geopandas/geopandas/blob/d5541f8817aac769d628a3108d95f7e1295053c7/geopandas/plotting.py#L182-L186

https://github.com/geopandas/geopandas/blob/d5541f8817aac769d628a3108d95f7e1295053c7/geopandas/plotting.py#L240-L244

#### Describe alternatives you've considered

A workaround is to lock axes limits with `ax.set_autoscale_on(False)`. This works if you do things in this order: plot data of interest, lock axes, plot contextual data. I understand that the `autolim` parameter is superior though, because it allows auto-scaling, but tells matplotlib which layers' limits should be ignored.

#### Additional context

This change will benefit a small library I am developing, which combines plots from xarray and geopandas: https://hyoga.readthedocs.io/en/latest/foreword/startup.html

The current code quietly uses `ax.set_autoscale_on(False)`, which is not ideal:

https://github.com/juseg/hyoga/blob/79d91002fb0c8f0f5df3e773492cd7977b7c9a42/hyoga/plot/datasets.py#L378-L382

Happy to open a PR if this makes sense.

**Comment by raphaelquast** [comment]
Hey @juseg, any progress on this yet?

I would very much like to see support for setting `"autolim"` as well... running into the same problem when trying to avoid unwanted autoscaling in [EOmaps](https://github.com/raphaelquast/EOmaps)

**Comment by martinfleis** [comment]
@raphaelquast feel free to prepare a PR yourself, it is already long enough from the original report.

**Comment by juseg** [comment]
@raphaelquast @martinfleis Sorry for leaving this stale. I have local changes and will open a PR. Due to the upstream issue matplotlib/matplotlib#24416 this will work for line and polygons but not for scatter plots.

**Comment by martinfleis** [comment]
> I have local changes and will open a PR. Due to the upstream issue https://github.com/matplotlib/matplotlib/issues/24416 this will work for line and polygons but not for scatter plots.

Thanks! There seems to be some activity on the matplotlib side to fix this in https://github.com/matplotlib/matplotlib/pull/15595 so let's do the work on our side assuming that scatter plot issue will be solved in upstream.

**Comment by raphaelquast** [comment]
here you go: #2830 

The main problem however is that you use `plt.scatter` for points which does not support `autolim`  (see comments in the PR)

**Comment by raphaelquast** [comment]
sorry just saw that there was some updates in the conversation that I missed... 
@juseg   feel free to take over (or merge my PR into yours)!

**Comment by juseg** [comment]
@raphaelquast Sorry for the duplicate work! I should have tagged you in my pull request...

**Comment by raphaelquast** [comment]
@juseg No worries, it was really more my fault not checking whether there was some progress here beforehand...   I'm happy you're still on it!
