### ISSUE TITLE
QST:  Recommended way for appending to a GeoDataFrame? (`df.append` is depreciated in pandas)

### ISSUE THREAD

**Issue by raphaelquast** [geopandas/geopandas#2606]
- [x] I have searched the [geopandas] tag on [StackOverflow](https://stackoverflow.com/questions/tagged/geopandas) and [GIS StackExchange](https://gis.stackexchange.com/questions/tagged/geopandas) for similar questions.

- [ ] I have asked my usage related question on [StackOverflow](https://stackoverflow.com) or [GIS StackExhange](https://gis.stackexchange.com).

---

#### Question about geopandas

Apparently `pandas.DataFrame.append` is now depreciated since `v1.4.0` and the use of `pd.concat` is recommended...
However, since there is no explicit `gpd.concat()` function, what is the preferred (future-prove)  way of appending rows to a GeoDataFrame?

Here's the depreciation note from pandas:
https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.4.0.html#deprecated-dataframe-append-and-series-append

```python
import geopandas as gpd

gdf1 = gpd.GeoDataFrame([1], geometry=gpd.points_from_xy([1], [2]))
gdf2 = gpd.GeoDataFrame([1], geometry=gpd.points_from_xy([1], [2]))

gdf = gdf1.append(gdf2)
```
```
>>> FutureWarning: The frame.append method is depreciated and will be removed from pandas in a future version. Use pandas.concat instead.
```

**Comment by m-richards** [comment]
Hi @raphaelquast, the recommendation would be to just use pd.concat:
```
import pandas as pd
import geopandas as gpd
gdf1 = gpd.GeoDataFrame([1], geometry=gpd.points_from_xy([1], [2]))
gdf2 = gpd.GeoDataFrame([1], geometry=gpd.points_from_xy([1], [2]))
res = pd.concat([gdf1, gdf2])
type(res)
Out[5]: geopandas.geodataframe.GeoDataFrame
```
`concat` will produce an output of the type of the first argument, so as long as gdf1 is already a geodataframe it will work fine (which is the same as the requirements for using append in the past)

**Comment by raphaelquast** [comment]
Hey @m-richards  thanks for the response!

If this is the recommended way now, does it mean that `gpd.append` will be deprecated as well?
If so, how about providing a direct accessor to `pd.concat` in geopandas (e.g. `gpd.concat`) so that 
one can avoid the explicit import for pandas and also to ensure users that the operation actually 
results in a properly concatenated `GeoDataFrame`.

**Comment by m-richards** [comment]
Hi @raphaelquast, 
>does it mean that gpd.append will be deprecated as well?

yes, GeoPandas doesn't actually implement gpd.append, it is inherited from pandas, so it will be deprecated at the same time as the pandas method.

> how about providing a direct accessor to pd.concat in geopandas (e.g. gpd.concat) 

Others may have different views on this, but I personally don't see a reason to expose a `gpd.concat`, we already depend on pandas so I don't see adding an import as a huge issue. Given that we do not have any special implementation of `concat` I'm not sure it makes sense to alias `pd.concat` either, GeoPandas doesn't exactly provide a stronger promise on correctness than pandas itself.

I could see an argument that using `pd.concat` is confusing and that suggests we should expose an alias, indeed you've asked this question. But at the same time, introducing an alias perhaps creates a new confusion for users, given there is a `pd.concat` and a `gpd.concat` what should one use when they both appear to work (and in actual fact are exactly the same)?

**Comment by martinfleis** [comment]
Fully agree with @m-richards here. If anything, we should stress more that geopandas is an extension of pandas and all the pandas methods and functions work on geopandas objects as you would expect with pandas.

**Comment by tfardet** [comment]
@m-richards is the pandas support complete, though?
I've been using ``pd.concat(gdf_list)`` to combine ``GeoDataFrame`` objects but I get a

```
/home/tfardet/.local/lib/python3.11/site-packages/geopandas/array.py:1406: UserWarning: CRS not set for some of the concatenation inputs. Setting output's CRS as WGS 84 (the single non-null crs provided).
```

despite the fact that all the ``GeoDataFrame`` objects in ``gdf_list`` have a valid ``crs`` attribute (epsg:4326)...
That's in gpd 0.12.1

**Comment by tfardet** [comment]
@martinfleis thanks for the quick reply, it took me a while but I think I found the problem, it's not directly related I guess but it comes from my used of ``sjoin_nearest`` with saved geometries.

The shortest MWE I could come up with was:

```python
import osmnx as ox
import pandas as pd

area = ox.geocode_to_gdf("Ivry-sur-Seine, France").iloc[0].geometry

landuse = ox.geometries_from_polygon(area, tags={"landuse": "commercial"})

buildings = ox.geometries_from_polygon(area, tags={"building": "retail"})

buildings["savedgeom"] = buildings.geometry

nearest = landuse.to_crs('+proj=cea').sjoin_nearest(buildings.to_crs('+proj=cea'))

nearest["geometry"] = nearest["savedgeom"]
del nearest["savedgeom"]

nearest = nearest.to_crs(landuse.crs)

print(buildings.crs, nearest.crs)

pd.concat([nearest, buildings])
```

**Comment by martinfleis** [comment]
If you dissect it a bit further, you can see that while this doesn't warn

```py
pd.concat([nearest[["geometry"]], buildings[["geometry"]]])
```

this does

```py
pd.concat([nearest[["geometry"]], buildings[["geometry", "savedgeom"]]])
```
That it is because when concatenating non-active GeoSeries, pandas creates an empty one on the side of `nearest` to have something to concatenate. And that does not have a CRS. So in this particular case, the warning is a bit misleading and we should probably filter the warning when this happens. For now, you can happily ignore it.
