### ISSUE TITLE
BUG: shapely 2.0b1, geopandas 0.12 unary_union fails

### ISSUE THREAD

**Issue by rraymondgh** [geopandas/geopandas#2613]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import os
# os.environ['USE_PYGEOS'] = '0'
import geopandas as gpd

print(gpd.show_versions())
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres')).head(5)
gdf.geometry.unary_union


```

#### Problem description

`unary_union` fails when using **geos** with **shapely** 2.0b1 installed

<details>
<summary>stack trace</summary>

```
---------------------------------------------------------------------------
GEOSException                             Traceback (most recent call last)
Cell In [1], line 7
      5 print(gpd.show_versions())
      6 gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres')).head(5)
----> 7 gdf.geometry.unary_union

File ~/PycharmProjects/oscontrib/venv/lib/python3.10/site-packages/geopandas/base.py:800, in GeoPandasBase.unary_union(self)
    781 @property
    782 def unary_union(self):
    783     """Returns a geometry containing the union of all geometries in the
    784     ``GeoSeries``.
    785 
   (...)
    798     POLYGON ((0 1, 0 2, 2 2, 2 0, 1 0, 0 0, 0 1))
    799     """
--> 800     return self.geometry.values.unary_union()

File ~/PycharmProjects/oscontrib/venv/lib/python3.10/site-packages/geopandas/array.py:650, in GeometryArray.unary_union(self)
    649 def unary_union(self):
--> 650     return vectorized.unary_union(self.data)

File ~/PycharmProjects/oscontrib/venv/lib/python3.10/site-packages/geopandas/_vectorized.py:1030, in unary_union(data)
   1028         return data
   1029 elif compat.USE_PYGEOS:
-> 1030     return _pygeos_to_shapely(pygeos.union_all(data))
   1031 else:
   1032     data = [g for g in data if g is not None]

File ~/PycharmProjects/oscontrib/venv/lib/python3.10/site-packages/pygeos/decorators.py:80, in multithreading_enabled.<locals>.wrapped(*args, **kwargs)
     78     for arr in array_args:
     79         arr.flags.writeable = False
---> 80     return func(*args, **kwargs)
     81 finally:
     82     for arr, old_flag in zip(array_args, old_flags):

File ~/PycharmProjects/oscontrib/venv/lib/python3.10/site-packages/pygeos/set_operations.py:388, in union_all(geometries, grid_size, axis, **kwargs)
    385     result = lib.unary_union_prec(collections, grid_size, **kwargs)
    387 else:
--> 388     result = lib.unary_union(collections, **kwargs)
    389 # for consistency with other _all functions, we replace GEOMETRY COLLECTION EMPTY
    390 # if the original collection had no geometries
    391 only_none = lib.get_num_geometries(collections) == 0

GEOSException: IllegalArgumentException: Argument must be Polygonal or LinearRing
```
</details>

#### Output of ``geopandas.show_versions()``

<details>
<summary>show_versions()</summary>

```
SYSTEM INFO
-----------
python     : 3.10.8 (main, Oct 13 2022, 10:18:28) [Clang 13.0.0 (clang-1300.0.29.30)]
executable : /Users/rraymond/PycharmProjects/python3.10/venv/bin/python3.10
machine    : macOS-11.6.8-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.0
GEOS lib   : None
GDAL       : 3.4.3
GDAL data dir: /Users/rraymond/PycharmProjects/python3.10/venv/lib/python3.10/site-packages/fiona/gdal_data
PROJ       : 8.2.0
PROJ data dir: /Users/rraymond/PycharmProjects/python3.10/venv/lib/python3.10/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.0
numpy      : 1.23.4
pandas     : 1.5.1
pyproj     : 3.3.1
shapely    : 2.0b1
fiona      : 1.8.22
geoalchemy2: None
geopy      : 2.2.0
matplotlib : 3.5.3
mapclassify: 2.4.3
pygeos     : 0.13
pyogrio    : None
psycopg2   : None
pyarrow    : 9.0.0
rtree      : 1.0.0
```

</details>

**Comment by jorisvandenbossche** [comment]
The error traceback shows that pygeos is being used, not shapely. Did you set the env variable? (the line is commented out in the example code snippet)

**Comment by rraymondgh** [comment]
@jorisvandenbossche it works with shapely enabled, fails when pygeos is used.  That line is commented as I was testing both cases

**Comment by jorisvandenbossche** [comment]
Ah, but I was confused because the title indicates shapely 2.0b1, so I was assuming it was happening when using shapely as the engine. 
So it's updating shapely from 1.8 to 2.0b1 that triggers pygeos to fail? If so, that sounds like a compatibility issue with the GEOS versions both use (we've run into mysterious failures before wen using wheels and not conda, where both packages actually use the same GEOS, instead of each their own compiled GEOS library from the wheel)

**Comment by jorisvandenbossche** [comment]
Similar issues: https://github.com/pygeos/pygeos/issues/447, https://github.com/pygeos/pygeos/issues/377, https://github.com/pygeos/pygeos/issues/122, and also https://github.com/geopandas/geopandas/issues/2551 you opened a while ago ..

We should probably have chosen to only use the "fastpath" in pygeos when we could detect that conda is being used, to avoid those failures when using wheels that happen to have the same GEOS version.

**Comment by martinfleis** [comment]
> We should probably have chosen to only use the "fastpath" in pygeos when we could detect that conda is being used, to avoid those failures when using wheels that happen to have the same GEOS version.

Do you want to make a patch with this?

For a record, I am not able to reproduce the reported behaviour on M1 when installing all from PyPI.

**Comment by rraymondgh** [comment]
Based on comment from @martinfleis I created a new **venv** on a new ubuntu vm.  Everything installs fine with `pip` and I did not receive this error.  Went back to my Mac and have removed all **brew** installs of **geos** and **glad**.  Now everything works just warnings about **shapely** and **pygeos** compiled with different versions of **geos**.  This is something obscure and difficult to re-produce.  Happy that this can be closed
