### ISSUE TITLE
Bug in `GeoSeries.to_json()`

### ISSUE THREAD

**Issue by BibMartin** [geopandas/geopandas#262]
I'm tying to export a `GeoSeries` to GeoJSON, using:

    import geopandas
    boros = geopandas.GeoDataFrame.from_file('../Téléchargements/nybb_14a_av/nybb.shp')
    boros.geometry.to_json()

I get a huge amount of warnings of the form:

    ERROR:shapely.geos:IllegalArgumentException: Operation not supported by GeometryCollection

Then many times:

    ERROR:shapely.geos:IllegalArgumentException: Empty Points cannot be represented in WKB

And Finally an Exception:

    OverflowError: Maximum recursion level reached

I guess this is due to the fact that `.to_json` method is inherited from `pandas.Series` and has not been reimplemented to accept *geometry* objects. I'll try a PR as soon as possible.

BTW, GeoPandas is great, thanks.

**Comment by jorisvandenbossche** [comment]
I think you can write to GeoJSON using `to_file` specifying the correct format?

**Comment by BibMartin** [comment]
@jorisvandenbossche 
Yes, thanks.

But I want to transform the GeoSeries to json *on the fly*, so that I can embed it in a folium map.

**Comment by micahcochran** [comment]
Why not just use the `__geo_interface__`?

So `boros.geometry.__geo_interface__` should do it.

**Comment by BibMartin** [comment]
@micahcochran 
You're true, that's much better.

Anyway, I guess it's good to have the method working. But I'll update the PR based on this.

Thnaks.

**Comment by micahcochran** [comment]
Since #263 was merged, can this be closed?

**Comment by jorisvandenbossche** [comment]
Indeed!
