### ISSUE TITLE
QST: geometry as index column?

### ISSUE THREAD

**Issue by snowman2** [geopandas/geopandas#2626]
Priority: Very low. Just wanted to post before I forgot for awareness. Behavior is likely fine as is.

Take any given geodataframe:

```python
import geopandas
from shapely.geometry import Point
gdf = geopandas.GeoDataFrame({"data": [1]}, geometry=[Point(1, 1)], crs="EPSG:4326")
```
Then, set the `geometry` column as the index and attempt to access the `crs` attribute. Previously, the `crs` attribute worked as the `_crs` as an attribute of the dataframe, With that removed, accessing the `crs` attribute now checks for the `geometry` and it fails.

```python
>>> gdfi = gdf.set_index("geometry")
>>> gdfi.crs
```
```
Traceback (most recent call last):
  File "../site-packages/geopandas/geodataframe.py", line 431, in crs
    return self.geometry.crs
  File ",../site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
  File ".../site-packages/geopandas/geodataframe.py", line 232, in _get_geometry
    raise AttributeError(msg)
AttributeError: You are calling a geospatial method on the GeoDataFrame, but the active geometry column ('geometry') is not present. 
There are no existing columns with geometry data type. You can add a geometry column as the active geometry column with df.set_geometry. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
  File .../site-packages/geopandas/geodataframe.py", line 433, in crs
    raise AttributeError(
AttributeError: The CRS attribute of a GeoDataFrame without an active geometry column is not defined. Use GeoDataFrame.set_geometry to set the active geometry column.
```

Is this behavior expected?

**Comment by m-richards** [comment]
This is an interesting question. Retrieving the CRS on GeoDataFrames without a valid geometry column was deprecated in 0.11 and removed in 0.12. In that sense this behaviour is expected - however (at least speaking for myself) I don't think we considered this case where the geometry column is lost by setting it as the dataframe index - I've never had a reason to do this before. If this pattern is actually used then I can see why the new behaviour might be confusing.

**Comment by martinfleis** [comment]
Index cannot be considered an active geometry column. I would say this is expected behaviour. If you set geometry as an index, you will need to retrieve CRS from the underlying array within the Index object. I would personally leave this as it is. You cannot expect any other geometry-specific method to work, why would CRS should work?

**Comment by snowman2** [comment]
> I've never had a reason to do this before

I wouldn't say that this behavior is recommended :smile: 

> I would personally leave this as it is.

That works.

Thanks all - this should be helpful in case someone else runs into this.
