### ISSUE TITLE
geodataframe.plot does not have any documentation

### ISSUE THREAD

**Issue by Casyfill** [geopandas/geopandas#264]
.plot_dataframe has a nice documentation - yet, I can't see it through `?` as I call .plot instead (a wrapper around .plot_dataframe

**Comment by jorisvandenbossche** [comment]
@Casyfill You are fully correct that the `plot` docstring should be updated to match this of `plot_dataframe`. See also #107

Regarding the first version of the title of this issue, "markersize does not work on geodataframe.plot", this should be solved in master after https://github.com/geopandas/geopandas/pull/260
