### ISSUE TITLE
gpd.GeoDataFrame.from_file()  key word arguments!

### ISSUE THREAD

**Issue by debboutr** [geopandas/geopandas#265]
Might be nice to add a kwarg that would force column names to uppercase in gpd.GeoDataFrame.from_file()

**Comment by jorisvandenbossche** [comment]
You can always easily do:

```
gdf.index = gdf.index.str.upper()
```

so I don't know if that would warrant a new keyword argument?

**Comment by debboutr** [comment]
very well thanks! I was trying it this way,  much simpler there.. Cheers!
