### ISSUE TITLE
BUG/VIS: alpha defaults conflict when plotting different geometry types.

### ISSUE THREAD

**Issue by IamJeffG** [geopandas/geopandas#266]
Historically polygons have been plotted with a default transparency of alpha=0.5,
whereas lines and points defaulted to fully opaque.  This is problematic for two
reasons:

Shapes from the same (heterogeneous) GeoSeries could end up styled differently from each other.

```
poly = Polygon([(1, 0), (2, 0), (2, 1)])
line = LineString([(0.5, 0.5), (1, 1), (1, 0.5), (1.5, 1)])
point = Point(0.75, 0.25)
df = GeoDataFrame({'geometry': [poly, line, point], 'values': [1, 2, 3]})
df.plot(color='red', linewidth=5, markersize=10)
```

![figure_6a](https://cloud.githubusercontent.com/assets/2002703/12222474/54bd8f34-b772-11e5-899a-ecf960ae8dec.png)

A legend cannot properly reflect the shapes of a heterogeneous GeoDataFrame. In fact right now, the legend won't match even a homogeneous GeoDataFrame of only Points or only Lines.

```
df.plot('values', linewidth=5, markersize=10, legend=True, categorical=True)
```

![figure_8a](https://cloud.githubusercontent.com/assets/2002703/12222477/5976c9be-b772-11e5-8fed-54acfb25688d.png)

One simple solution may be to default to full opacity for all polygons.

**Comment by jorisvandenbossche** [comment]
+ 1 for default of `alpha=1` 
(at least we should make the legend follow the same alpha)

**Comment by jorisvandenbossche** [comment]
Default alpha is now 1 for all geoms now  #318 is closed
