### ISSUE TITLE
BUG: Wrong map plot

### ISSUE THREAD

**Issue by KyloRen1** [geopandas/geopandas#2669]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

Here is the [link](https://colab.research.google.com/drive/1RSkbOaiS3SEvo4B7xq0Q4i3612FXYrfr?usp=sharing) to reproduce the issue 

It seems that geopandas supports the illegal annexation of Ukraine. 

The correct plot should look similar to this image
![Ukraine-map-flag](https://user-images.githubusercontent.com/35574157/206782289-4a1fe840-310c-4c2b-970d-468b7ab69821.jpg)

Слава Україні!

**Comment by martinfleis** [comment]
Hey,

I can assure we do not support it. I understand why you think that and admit that it is a reasonable from you. I have just posted a proposal for a solution to https://github.com/geopandas/geopandas/issues/2382#issuecomment-1344762545. Would that be acceptable for you?

May I also ask you to channel the discussion there? If you don't mind that I will close this issue to ensure all the relevant comments land in a single place. Please do not see this step as a signal of hostility.
