### ISSUE TITLE
DataFrame.plot() fails for PolygonZ GeoSeries

### ISSUE THREAD

**Issue by paulperry** [geopandas/geopandas#268]
Census shapefiles (e.g. https://www.census.gov/geo/maps-data/data/cbf/cbf_state.html ) have a Z dimension, even if they are all 0's.  GeoPandas reads them (which is better than what basemap readshapefile can do) but dies hard when plotting.  Ironically, displaying a shape in Jupyter will actually render properly.  This should either catch the error and throw a better exception, or, better,  strip the Z out and render.  To reproduce, download the shapefile linked above and run code below:

```
state_file = 'cb_2014_us_state_500k.shp'
states = gp.GeoDataFrame.from_file(state_file)
states.plot()

```

**Comment by jdmcbr** [comment]
I added handling for this in #211, so your code snippet works in the latest development version.

**Comment by paulperry** [comment]
I moved to geopandas: 0.1.0.dev- , and this is fixed for me.  Closed.  Thank you.

**Comment by jdmcbr** [comment]
@jorisvandenbossche Could you close this?

**Comment by jorisvandenbossche** [comment]
It would be nice to have a test for this, to ensure it keeps working.
