### ISSUE TITLE
BUG: to_postgis() option if_exists="append" fails to find SRID

### ISSUE THREAD

**Issue by george-j-thomas** [geopandas/geopandas#2681]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample

```python
import geopandas
from shapely.geometry import Point
from sqlalchemy import create_engine

URI="postgresql:///user:password@localhost:5432/test"
eng=create_engine(URI)

d = {'col1': ['name1', 'name2'], 'geometry': [Point(1, 2), Point(2, 1)]}
gdf = geopandas.GeoDataFrame(d, crs="EPSG:6344")
with eng.connect() as conn:
    gdf.to_postgis('table_name', conn, if_exists="append", schema='schema_name')

```

#### Problem description

If the table does not already exist, this works fine, and creates a new table.

If the table does exist, the ``AttributeError`` below is thrown. I confirmed in standard pandas and sqlalchemy that the SRID can be found with: 
```python
with eng.connect() as conn:
    pd.read_sql(sqlalchemy.text("SELECT Find_SRID('schema_name', 'table_name', 'geom');"), conn)

Output:
   find_srid
0       6344
```

```
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/user/.local/share/virtualenvs/env/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1931, in to_postgis
    geopandas.io.sql._write_postgis(
  File "/home/user/.local/share/virtualenvs/env/lib/python3.8/site-packages/geopandas/io/sql.py", line 428, in _write_postgis
    target_srid = connection.execute(
  File "/home/user/.local/share/virtualenvs/env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: "SELECT Find_SRID('schema_name', 'table_name', 'geom');"
```

#### Expected Output

Should be able to find the SRID and append to the table as expected.

#### Output of ``geopandas.show_versions()``

``0.12.2``

</details>

**Comment by latot** [comment]
This happens to me too, maybe the code to run sqlalchemy is not using ```sqlalchemy.text```?.

I have a workaround, use sqlalchemy 1 (not future) and pass the engine to geopandas, with that works for me.

**Comment by bunnefant** [comment]
Hi,
What do you mean by pass the engine to geopandas? I am also getting the exact same issue.

Thanks!

**Comment by felipempinto** [comment]
The main problem seems to be a piece of the code in the sql.py (entire path: "geopandas/io/sql.py") that is used to check if the SRID from the dataset you are trying to upload to PostGIS, has the same SRID of the table. If we remove the if statement from line 423 from the sql.py code, for example, the code works as it should (this is a workaround, but this does not solve the problem, and it will be a problem if the SRIDs are different). 

To solve the problem, as suggested here, we need to change the code like this:

From:
```
if if_exists == "append":
        # Check that the geometry srid matches with the current GeoDataFrame
        with _get_conn(con) as connection:
            # Only check SRID if table exists
            if connection.dialect.has_table(connection, name, schema):
                
                from sqlalchemy import text
                target_srid = connection.execute(
                    "SELECT Find_SRID('{schema}', '{table}', '{geom_col}');".format(
                        schema=schema_name, table=name, geom_col=geom_name
                    )
                ).fetchone()[0]

                if target_srid != srid:
                    msg = (
                        "The CRS of the target table (EPSG:{epsg_t}) differs from the "
                        "CRS of current GeoDataFrame (EPSG:{epsg_src}).".format(
                            epsg_t=target_srid, epsg_src=srid
                        )
                    )
                    raise ValueError(msg)
```
                    
To 

```
from sqlalchemy import text
if if_exists == "append":
        # Check that the geometry srid matches with the current GeoDataFrame
        with _get_conn(con) as connection:
            # Only check SRID if table exists
            if connection.dialect.has_table(connection, name, schema):
                
                target_srid = connection.execute(
                    text("SELECT Find_SRID('{schema}', '{table}', '{geom_col}');".format(
                        schema=schema_name, table=name, geom_col=geom_name
                    ))
                ).fetchone()[0]

                if target_srid != srid:
                    msg = (
                        "The CRS of the target table (EPSG:{epsg_t}) differs from the "
                        "CRS of current GeoDataFrame (EPSG:{epsg_src}).".format(
                            epsg_t=target_srid, epsg_src=srid
                        )
                    )
                    raise ValueError(msg)
```

It worked for my purposes here, but I could not create a new pull request, but it is the suggestion to solve this error.

**Comment by armstrys** [comment]
I also ran into this error and other strange type errors (unrelated to geopandas) using sqlalchemy 2.0.1. Downgrading to an earlier version by specifying sqlalchemy<2.0.0 in my environment install solved this issue and others.

**Comment by rietesh** [comment]
@felipempinto, why weren't you able to create a PR? I saw that there are no tests written for to_postgis()

**Comment by martinfleis** [comment]
@rietesh the tests are [here](https://github.com/geopandas/geopandas/blob/main/geopandas/io/tests/test_sql.py), the function that is called by `to_postgis` is called `_write_postgis` and is tested directly. See the implementation:

https://github.com/geopandas/geopandas/blob/00e3748c987f5b9a14b5df5233421710811d75bf/geopandas/geodataframe.py#L1948-L1950

**Comment by felipempinto** [comment]
@rietesh I didn't have time to do that, I started to create a new PR, but I got stuck in some errors during the testing phase, so I thought this could take more time than I had. So, I wrote the solution I found here, and this could help someone to create the PR.

And yes, there are tests already created, as explained by @martinfleis, for the write_postgis function, but I haven't created a PR yet, due to some other errors that showed up.

**Comment by rietesh** [comment]
I raised the PR to fix this bug #2807

**Comment by tjwebb** [comment]
Also hitting this issue.

**Comment by jorisvandenbossche** [comment]
@m-richards @rietesh was this fixed by https://github.com/geopandas/geopandas/pull/2846?

**Comment by jorisvandenbossche** [comment]
For others reading here, GeoPandas 0.13.0 was released today, which should include that fix.

**Comment by m-richards** [comment]
> @m-richards @rietesh was this fixed by #2846?

Yes it was, it was linked to close with #2807, which was superceded by #2846

**Comment by Rabijns** [comment]
I'm running into this issue, but with geopandas 0.14.3. Is it possible the bug has resurfaced?

**Comment by ranran9991** [comment]
Bug still exists.

**Comment by martinfleis** [comment]
@ranran9991 not the one specified in the post above. It may be that this is still the case for `geography` as noted above. Can't verify. Can you open a new issue outlining your problems?
