### ISSUE TITLE
DOC: printed PROJ ERROR log in online docs

### ISSUE THREAD

**Issue by MischaDy** [geopandas/geopandas#2683]
### Buggy behavior:
Below the code box in the [Reading Files section of the Getting Started page](https://geopandas.org/en/stable/getting_started/introduction.html#Reading-files), I get the following error message:
`ERROR 1: PROJ: proj_create_from_database: Open of /home/docs/checkouts/readthedocs.org/user_builds/geopandas/conda/stable/share/proj failed`
The output below that looks fine to me. Cf. this screenshot:

![grafik](https://user-images.githubusercontent.com/44754681/208923157-519a0da3-2484-407b-8d99-612df8b5a94b.png)

### Expected behavior:
No error message appearing.

### Steps to reproduce:
Visit the website at the above link.

### System Details

- Windows 10, version 22H2, build 19045.2364
- Browsers tested:
   - Firefox, version 108.0.1 (64-bit)
   - Chrome, official build, version 108.0.5359.125 (64-bit)
   - Edge, official build, version 108.0.1462.54 (64-bit)

----------

Please do let me know if this isn't the right place for this bug report, I'd be happy to move it.

**Comment by m-richards** [comment]
Hey @MischaDy, thanks for the report, I've also noticed this. Although it's not ideal to have warnings in the docs, it is fortunately non critical in this example.

**Comment by jorisvandenbossche** [comment]
It's indeed not an actual error (in the sense of a Python exception that interrupts the execution of the code), but a printed error log from PROJ / pyproj. But it _is_ annoying and distracting. 

This was also mentioned at https://github.com/geopandas/geopandas/issues/2652#issuecomment-1326668393. For some reason the environment created online for building the docs has this issue, but so we can't reproduce this locally (which makes it hard to investigate).

**Comment by martinfleis** [comment]
@nicholasbalasus there's some discussion in https://github.com/conda-forge/pyproj-feedstock/issues/130 but no solution as far as I can tell.
