### ISSUE TITLE
plot() with colormap=None still renders with colors

### ISSUE THREAD

**Issue by paulperry** [geopandas/geopandas#269]
Per this [thread on stackexchange](http://gis.stackexchange.com/questions/152920/changing-colours-in-geopandas) I thought `colormap=None` should render without colors.  I was trying to draw a background map and a foreground map:

```
ax = states.plot(column=None, colormap=None, linewidth=0.1)
ax = cbsa.plot(column='pct_screened', scheme='QUANTILES', k=5, 
        colormap='bwr', ax=ax, linewidth=0.1, legend=True)
```

But that didn't work.  Changing alpha=0 and/or color='white' works, but colormap=None seems more intuitive for blank backgrounds.

I'm on geopandas: 0.1.0.dev-

**Comment by jorisvandenbossche** [comment]
What is `colormap=None` currently doing? I think it is then using the default colormap?

So actually the goal is to be able to plot the polygons without any filling? In that case, `facecolor='none'` does the trick 
(matplotlib often uses the string 'none' instead of None to specify to do nothing, as None is often used to indicate to use the default)

**Comment by IamJeffG** [comment]
I'm not convinced there's a bug, but I do agree that the docs could be more clear. The docs never say what should happen if you pass `cmap=None` (which is that we force some default upon you). Also confusing is that that the docstring of `plot_dataframe` is inconsistent with its signature:

    def plot_dataframe(s, column=None, cmap=None, color=None, linewidth=1.0,
        # ...crop...
        cmap : str (default 'Set1')

**Comment by jorisvandenbossche** [comment]
This will be closed by https://github.com/geopandas/geopandas/pull/510 with the new defaults (default of cmap=None will give uniform color)
