### ISSUE TITLE
DOC: geoparquet docs page out of sync

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#2693]
https://geopandas.org/en/latest/docs/user_guide/io.html#apache-parquet-and-feather-file-formats page refers to the  0.1.0 geo-arrow-spec and not the newer geoparquet repo. I believe we also removed the corresponding warning text from the parquet io methods.

**Comment by jorisvandenbossche** [comment]
Indeed, that can use an update!

**Comment by jorisvandenbossche** [comment]
I am updating this text in https://github.com/geopandas/geopandas/pull/2663 while updating for the latest GeoParquet spec version.
