### ISSUE TITLE
QST: Calculate min, max and average width from multipolygons

### ISSUE THREAD

**Issue by phamkhactu** [geopandas/geopandas#2699]
I have question that: if i have polygons, can geopandas can give function to calculate width: min, max, aver like that:
![image](https://user-images.githubusercontent.com/42369268/210504029-3a01af79-7b63-4f1b-90f1-2302e71bd2f2.png)
Here is my data:
```
{ "type": "Feature", "properties": { "OBJECTID": 1.0, "SHAPE_Leng": 0.00057672519222000005, "SHAPE_Area": 5.191152e-09, "name": null, "rongMax": null, "rongMin": null, "rongTB": null }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 105.814052974000049, 21.009160664000035 ], [ 105.814018928000053, 21.00919353200004 ], [ 105.814021210000078, 21.009195662000025 ], [ 105.814026385000034, 21.009202952000066 ], [ 105.81405440900005, 21.009242426000071 ], [ 105.814090260000057, 21.009269388000064 ], [ 105.814124937000088, 21.009292263000077 ], [ 105.814203617000032, 21.009343118000061 ], [ 105.814214316000061, 21.009350654000059 ], [ 105.814223964000064, 21.009340076000058 ], [ 105.814170518000083, 21.009304149000059 ], [ 105.81414109900004, 21.009282088000077 ], [ 105.814117868000039, 21.009266112000034 ], [ 105.814087328000085, 21.009244852000052 ], [ 105.814074111000082, 21.009232288000078 ], [ 105.814072411000041, 21.009232829000041 ], [ 105.814058327000055, 21.009186317000058 ], [ 105.814055345000043, 21.009175664000054 ], [ 105.814052974000049, 21.009160664000035 ] ] ] ] } },

```
Thank you

**Comment by martinfleis** [comment]
Not out of the box. To do this, you'd actually need quite complex algorithm I believe as what you easily see visually here is not that simple to write as a code generalisable to any shape.

As a start, you can try creating oriented envelope with shapely and making a set of perpendicular lines to its longer axis. Those can then be intersected with the polygon and a length of each can be measured. That would likely work reasonably for this very elongated polygon but would not for others.

**Comment by jGaboardi** [comment]
xref https://github.com/shapely/shapely/issues/1706

**Comment by martinfleis** [comment]
Closing in favour of the discussion in shapely where it belongs more.
