### ISSUE TITLE
geopandas tools

### ISSUE THREAD

**Issue by bachirbac** [geopandas/geopandas#270]
I  could import geopandas.tools sjoin  but I  have the following message, any help please 

AttributeError                            Traceback (most recent call last)
<ipython-input-26-9766bf4ac838> in <module>()
----> 1 bin_stats = bin_the_midpoints(bins, midpoints)

<ipython-input-25-386ab0629c42> in bin_the_midpoints(bins, midpoints)
      3     m = midpoints.copy()
      4     reindexed = b.reset_index().rename(columns={'index':'bins_index'})
----> 5     joined = gpd.tools.sjoin(reindexed, m)
      6     bin_stats = joined.groupby('bins_index')['offset']                      .agg({'fold': len, 'min_offset': np.min})
      7     return gpd.GeoDataFrame(b.join(bin_stats))

AttributeError: module 'geopandas' has no attribute 'tools'

**Comment by jorisvandenbossche** [comment]
@bachirbac Can you provide a reproducible example? How did you do the import?

**Comment by jorisvandenbossche** [comment]
Closing this as we need more information to debug this.
