### ISSUE TITLE
Travis Python 2.6 PANDAS=master failing

### ISSUE THREAD

**Issue by micahcochran** [geopandas/geopandas#271]
I made a [fairly small change](https://github.com/geopandas/geopandas/compare/master...micahcochran:patch-1) that I didn't think would cause this type of [test failure](https://travis-ci.org/micahcochran/geopandas/builds/108072078).

Pandas has dropped support for Python 2.6 (https://github.com/pydata/pandas/issues/7718).  Now using OrderDicts, which aren't supported by Python 2.6.

I thought I should bring this issue up before I submit a failing Pull Request.  This is more important than my little PR.

Should the Python 2.6 for PANDAS master be [allowed-failures](https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail) or [exclude](https://docs.travis-ci.com/user/customizing-the-build#Excluding-Builds) it entirely?

**Comment by kjordahl** [comment]
If pandas has dropped 2.6 support, there's no point in trying to maintain it in geopandas. In the short term we can just exclude 2.6 for pandas master.

**Comment by jorisvandenbossche** [comment]
It's only pandas 0.18 that drops support for python 2.6. And even when 0.18 is released, I think we should look at the dependencies of the oldest pandas version geopandas supports (you can still use geopandas with pandas 0.17, which you can still use with python 2.6)

Of course we can choose to not support 2.6 anymore anyhow, but just wanted to point out there is still some point in maintaining support :-)

**Comment by jorisvandenbossche** [comment]
Sorry, I misread. Yes, indeed there is no point in keeping the test combination of python 2.6 and pandas master.

**Comment by micahcochran** [comment]
Since #272 has been merged, the code no longer has issues with testing on Travis.  Closing issue.
