### ISSUE TITLE
Multi index in geopandas

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [geopandas/geopandas#274]
Hi,

Is possible to do multi index in geopandas? 

I'll like to have two different indexs, one for the identification of the polygon and another index that is a Timeseries index.

Ho do I achieve this if possible?

Thanks

**Comment by jorisvandenbossche** [comment]
At the moment, the geometry column cannot be the index (and thus also not in a multi-index), so you can combine it with a DatetimeIndex and in this way have both. 
Is this what you want? If not, can you elaborate a bit?

**Comment by LorenzoBottaccioli** [comment]
@jorisvandenbossche I try to explain better. I want to have a data frame that have to index one with a unique ID for the polygon and one with a datetime index for each polygon.

Is this possible? How?

**Comment by martinfleis** [comment]
Geometry cannot be in the index and that is not likely to be different in the future. For more on advanced indexing and using MultiIndex see [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html#advanced). Closing.
