### ISSUE TITLE
Deprecate and remove geopandas.datasets module

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2751]
After the recent discussions about the contents of the `geopandas.datasets` module, especially the `naturalearth_lowres` dataset (see #2382 or #1510 but also #1041), we have decided to deprecate the module in the next release and remove it prior GeoPandas 1.0 (expected early 2024).

We know that removing the built-in datasets will cause a bit of friction, especially in creating tutorials and other study materials (like our own documentation), so we want to provide another easy solution to get some real-world data for illustration into GeoDataFrame. The current plan is to create a package similar to `xyzservices` or `pysal.examples` that would serve URLs to remote datasets served by existing open data providers. The idea is that instead of typing 

```py
geopandas.read_file(geopandas.datasets.get_path('nybb'))
```
where `get_path` returns a local path to a file installed with GeoPandas, we would do

```py
geopandas.read_file(new_package.get_path('nybb'))
```

where `new_package.get_path` return an URL GeoPandas can directly read.

The contents of the new package will be curated and will not include any data reflecting international politics, among other potentially hurtful topics.

GeoPandas was always a software project, not a data project, and the included datasets were meant to easily showcase the functionality for illustrational purposes. We believe that the proposed solution will swiftly replace the built-in solution, minimise the friction caused by the change and remove unnecessary stress for the project maintainers.

**Comment by martinfleis** [comment]
Given we will raise a warning now, we should probably look into replacement of the built-in datasets in our docs prior 0.13?

**Comment by martinfleis** [comment]
I have started drafting the new package with link here https://github.com/martinfleis/xyzdata. Happy to get any feedback. It is an early stage with no tests but it seems to work as expected.

**Comment by raybellwaves** [comment]
If curious xarray keeps tutorial datasets in a separate repo: https://github.com/pydata/xarray-data and will cache locally if desired: https://github.com/pydata/xarray/blob/main/xarray/tutorial.py

**Comment by martinfleis** [comment]
@raybellwaves that is basically the logic of `xyzdata`, also using pooch for caching. The only difference is that it may be shared among projects (at least geopandas and PySAL).

**Comment by martinfleis** [comment]
#2861 is merged. Moving milestone to 1.0 when the module will be removed.

**Comment by milyas009** [comment]
Hi Everyone, after GeoPandas 1.0 upgrade, how the following code can be written now?

world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
thaiplot = world.query('name == "Thailand"')

**Comment by m-richards** [comment]
per the error message this code produces you need to download the data yourself from natural earth. Geopandas does not provide datasets anymore.

**Comment by adretgeo** [comment]
> per the error message this code produces you need to download the data yourself from natural earth. Geopandas does not provide datasets anymore.

Does not answer the question.  Can an *example* please be shown to demonstrate effective syntax when referencing a downloaded dataset?  Thanks.
