### ISSUE TITLE
BUG: copy of empty GeoDataFrame becomes Pandas DataFrame

### ISSUE THREAD

**Issue by joooeey** [geopandas/geopandas#2765]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import copy
import geopandas as gpd

empty = gpd.GeoDataFrame()
print("original plain:", type(empty))  # GeoDataFrame
print("copied plain:", type(copy.deepcopy(empty)))  # DataFrame !!!!!!!!!!!!!!!!!!

geom = gpd.GeoDataFrame(columns=["geometry"])
print("original with geometry:", type(geom))  # GeoDataFrame
print("copied with geometry:", type(copy.deepcopy(geom)))  # GeoDataFrame
```

#### Problem description

When I [deepcopy](https://docs.python.org/3/library/copy.html) a geopandas.GeoDataFrame without a "geometry" column, the copy becomes a pandas.DataFrame. I looked on the main branches on Github and neither Pandas nor Geopandas override `__deepcopy__`. So I have no idea why this happens.

Stackoverflow users have suggested the workaround of using `GeoDataFrame.copy(deep=True)` but that has three drawbacks:
- It's not a true deep copy. For object columns, individual elements are still passed by reference [instead of being copied](https://stackoverflow.com/questions/66318160/truly-deep-copying-pandas-dataframes).
- It's not applicable when the GeoDataFrame itself is part of a compound object.
- It doesn't work with my versions (see show_versions below).

#### Expected Output

Copying a GeoDataFrame should result in another GeoDataFrame, not a DataFrame.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:16:33) [MSC v.1929 64 bit (AMD64)]
executable : C:\Users\user\anaconda3\envs\rqa\python.exe
machine    : Windows-10-10.0.19045-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : None
GDAL data dir: None
PROJ       : 9.1.0
PROJ data dir: C:\Users\user\anaconda3\envs\rqa\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.23.5
pandas     : 1.5.2
pyproj     : 3.4.1
shapely    : 2.0.0
fiona      : None
geoalchemy2: None
geopy      : None
matplotlib : 3.6.2
mapclassify: 2.4.3
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : 1.0.1

</details>

#### Source

I cross-posted some content from [StackOverflow](https://stackoverflow.com/questions/75173357/deep-copy-of-geodataframe-becomes-pandas-dataframe).

**Comment by m-richards** [comment]
Hey @joooeey, this is a consequence of #2060 where removing the geometry column from a geodataframe will return a dataframe instead. Where you construct an empty geodataframe as you have in your example and the geometry column was never present in the first place is noted specifically as #2130.

What you're seeing is not actually related to `deepcopy` at all, it's just an operation that triggers a call to `_constructor` inside pandas (for example `type(gpd.GeoDataFrame().assign(foo=4))` is a `pd.DataFrame`

**Comment by joooeey** [comment]
I'm just using the null object pattern within a compound object that contains a GeoDataFrame. Usually that's a GeoDataFrame with geographic and other data. For this I have a workaround: Using `gpd.GeoDataFrame(columns=["geometry"])` as the null object.
However, it took me a long time to find out what the problem actually is. I definitely view this as a bug since deepcopy should output the same as the input. I'll elaborate in issue 2130 so this problem doesn't get lost.
