### ISSUE TITLE
Name of a GeoSeries lost when assigned as geometry in GeoDataFrame constructor

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2770]
If I have a named GeoSeries and assign it as a geometry when creating a GeoDataFrame, that name is lost and I get back default 'geometry'. 

I thought there was an issue on this but I haven't found one so opening this one instead.

```py
import geopandas
import shapely

geopandas.GeoDataFrame(geometry=geopandas.GeoSeries([shapely.Point(0, 0)], name="my_name"))
```
```
                  geometry
0  POINT (0.00000 0.00000)
```

I guess we should check for existing name here before defaulting to `self._geometry_column_name` https://github.com/geopandas/geopandas/blob/d3d368641380a452fba21f32aeffd4a1e17e1901/geopandas/geodataframe.py#L316

**Comment by jorisvandenbossche** [comment]
Hmm, I would have thought we had tests for this. I would also expect the name to be preserved.

**Comment by m-richards** [comment]
>I thought there was an issue on this but I haven't found one so opening this one instead.
This was discussed in #2312 but the main topic and title of the issue is something else.

**Comment by m-richards** [comment]
I guess the question here is if this is a bug fix or a breaking change? It is not the best thing to issue deprecation warnings for, we'd have to add a flag to the constructor I'd guess?

**Comment by martinfleis** [comment]
I expected this to work so in my perception this is a bug.

**Comment by hydroEng** [comment]
Hello, is this bug appropriate for beginners? It seems like it's just a matter of checking if geometry.name exists, right? We can do a check if `hasattr(geometry,'name')` and assign new or existing name depending on the outcome. If that approach is OK I am happy to open a PR.
