### ISSUE TITLE
BUG: geopandas.read_file emits nan for missing string values, when reading FlatGeoBuf file with Fiona 1.9.0 - change in behaviour change from None values, if Fiona 1.8.22 is used

### ISSUE THREAD

**Issue by rfc-hv** [geopandas/geopandas#2783]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

Note: reproducible example script contains binary data generated by fiona 1.8.22. if you prefer not to read binary data, you can create the data yourself (see bonus script at end)

```python3
import geopandas as gpd

DEMO_FGB_DATA = b'fgb\x03fgb\x01\x9c\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x16\x00 \x00\x08\x00\x0c\x00\x07\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x14\x00\x16\x00\x00\x00\x00\x00\x00\x01D\x00\x00\x00\x1c\x00\x00\x00\x10\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00@\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00demo\x00\x00\x0e\x00\x10\x00\x08\x00\x07\x00\x00\x00\x00\x00\x0c\x00\x0e\x00\x00\x00\x00\x00\x00\x0b\x08\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00foo\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x08\x00\x04\x00\x06\x00\x00\x00\x0c\x00\x00\x00\x08\x00\x08\x00\x00\x00\x04\x00\x08\x00\x00\x00\x04\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

DEMO_FILENAME = 'demo.fgb'

with open(DEMO_FILENAME, 'wb') as f:
    f.write(DEMO_FGB_DATA)

gdf = gpd.read_file(DEMO_FILENAME, engine='fiona')
print(repr(gdf))

```

#### Problem description

The symptom I am describing is an unexpected change in behaviour of the `read_file` function.

When the Fiona 1.8.22 dependency is installed, when `geopandas.read_file` is used to read a FlatGeobuf layer that contains a string column, where some records have missing values for the string values, `geopandas` produces a geodataframe where the missing string values are encoded as python `None` values:

```
    foo                 geometry
0  None  POINT (0.00000 0.00000)
```

In contrast, when the new Fiona 1.9.0 dependency is installed, when we read the same input file in the same script, using the same version of `geopandas`, we produce a different geodataframe, where the missing values are encoded as numpy `nan` values:

```
   foo                 geometry
0  NaN  POINT (0.00000 0.00000)
```

The problem with this change from `None` to `nan` to represent missing string values is that it breaks code that expects `None` values.

It's unclear if `geopandas` is the correct place to report this issue -- I report it here as `geopandas` is the top level interface my client code uses, I don't directly depend upon Fiona, geopandas does, and it may help other geopandas users who are trying to understand the cause of similar backwards incompatible changes in behaviour.

#### Expected Output

I don't expect the output of `geopandas.read_file` to change due to upgrading the `Fiona` dependency that `geopandas` depends on from Fiona 1.8.22 to Fiona 1.9.0.  I'd prefer `geopandas` to indicate it is incompatible with Fiona 1.9 or signal there is a breaking change in `read_file`.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
executable : /home/worker/projects/debug_fiona/venv/bin/python3
machine    : Linux-5.15.0-58-generic-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.10.2
GEOS lib   : /usr/lib/x86_64-linux-gnu/libgeos_c.so
GDAL       : 3.5.3
GDAL data dir: /home/worker/projects/debug_fiona/venv/lib/python3.10/site-packages/fiona/gdal_data
PROJ       : 9.1.0
PROJ data dir: /home/worker/projects/debug_fiona/venv/lib/python3.10/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.24.2
pandas     : 1.5.0
pyproj     : 3.4.1
shapely    : 1.8.4
fiona      : 1.9.0
geoalchemy2: None
geopy      : None
matplotlib : None
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : None

</details>

##### bonus script to create input data used for this example

use fiona 1.8.22 when creating this file

```
import fiona

schema_props = OrderedDict([("foo", "str")])

record = {'geometry': {'type': 'Point', 'coordinates': (0, 0)}, 'properties': {"foo": None}}

with fiona.open("demo.fgb", "w", driver='FlatGeobuf', schema={"geometry": "Point", "properties": schema_props}) as c:
    c.write(record)
```

**Comment by jorisvandenbossche** [comment]
This is indirectly due to the following change in Fiona:

Using fiona 1.8:

```
>>> collection = fiona.open("demo.fgb")
>>> list(collection)[0]
{'type': 'Feature',
 'id': '0',
 'properties': OrderedDict([('foo', None)]),
 'geometry': {'type': 'Point', 'coordinates': (0.0, 0.0)}}
```

Using fiona 1.9:

```
>>> collection = fiona.open("demo.fgb")
>>> features = list(collection)
>>> features[0]
<fiona.model.Feature at 0x7f3e72a56110>
>>> features[0].__geo_interface__
{'geometry': {'coordinates': (0.0, 0.0), 'type': 'Point', 'geometries': []},
 'id': '0',
 'properties': {},
 'type': 'Feature'}
```

So the feature dictionary that geopandas gets out of the Fiona collection changed slightly: previously the "foo" property was present and explicitly had the value `None`, while now the property is missing if the data was missing. 
(I don't know if this was intentional by Fiona, that might be something to check over there)

And then it is the behaviour of the pandas.DataFrame constructor that depends on the value being None or not present:

```
>>> pd.DataFrame([{"foo": "string"}, {"foo": None}])
      foo
0  string
1    None

>>> pd.DataFrame([{"foo": "string"}, {}])
      foo
0  string
1     NaN
```

So this is not something geopandas has direct control over. 

Also in general, I would not recommend to rely on the exact missing value representation being `None`. Pandas will generally consider both None and np.nan as missing value indicators for object dtype (string) columns, and use them interchangeably. But even if you start with a DataFrame with None values, pandas tends to make those NaNs through operations (since pandas defaults to use NaN).

**Comment by rfc-hv** [comment]
@jorisvandenbossche - thank you for taking a look and triaging this.  your explanation makes sense. I agree this isn't something geopandas has control over

>  would not recommend to rely on the exact missing value representation being None. Pandas will generally consider both None and np.nan as missing value indicators for object dtype (string) columns, and use them interchangeably

that also sounds like a wise idea, thank you. it looks like https://pandas.pydata.org/docs/reference/api/pandas.isnull.html might be what i want instead, rather than explicit `if value is None` checks. `isnull` returns True for None and nan, and false for other non-missing values such as 0, False, etc.

**Comment by jorisvandenbossche** [comment]
Yes, using the pandas `isna()` function or method is the way to go

**Comment by jorisvandenbossche** [comment]
Closing this as I don't think there is any action to take on the geopandas side.
