### ISSUE TITLE
BUG: "CPLE_AppDefinedError: buildEllipsoid: non double value" when trying to read a shapefile using .read_file()

### ISSUE THREAD

**Issue by Royal4224** [geopandas/geopandas#2798]
- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
import geopandas as gpd

df = gpd.read_file("/Users/roy/Downloads/2014_nei_isrm_emissions/onroad.shp")

```

#### Problem description

I'm running this code cell in Jupyter Notebook. It resolves with the following error: 
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/68200979/220196898-bb423a20-8c2d-410e-ad16-0dd8828ae911.png">

I tried looking for this CPLE_AppDefinedError pretty extensively, but it seems the ones that I've come across aren't necessarily related to my issue. I tried passing in different shapefiles, which yields the same error message. I've also been able to verify that the shapefiles look good. Any help would be greatly appreciated!

#### Expected Output
DataFrame should be returned/created

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.11.0 | packaged by conda-forge | (main, Jan 15 2023, 05:44:48) [Clang 14.0.6 ]
executable : /Users/roy/opt/anaconda3/envs/InMAP/bin/python3.11
machine    : macOS-12.6-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.6.2
GDAL data dir: /Users/roy/opt/anaconda3/envs/InMAP/lib/python3.11/site-packages/fiona/gdal_data
PROJ       : 9.1.1
PROJ data dir: /Users/roy/opt/anaconda3/envs/InMAP/lib/python3.11/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.24.2
pandas     : 1.5.3
pyproj     : 3.4.1
shapely    : 2.0.1
fiona      : 1.9.1
geoalchemy2: None
geopy      : None
matplotlib : 3.7.0
mapclassify: 2.5.0
pygeos     : None
pyogrio    : 0.5.1
psycopg2   : None
pyarrow    : None
rtree      : 1.0.1

</details>

**Comment by jorisvandenbossche** [comment]
@Royal4224 this seems an issue with the Fiona dependency (https://github.com/Toblerity/Fiona, which does the actual reading of the file). Do you see an error as well when directly using it? Something like:

```
import fiona

with fiona.open("/Users/roy/Downloads/2014_nei_isrm_emissions/onroad.shp") as src:
    print(src.crs_wkt)
```

**Comment by Royal4224** [comment]
Yes, I do (same error message actually).
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/68200979/220199341-3a1015b9-b673-40a0-bdcb-8b68105862ed.png">
Would you recommend that I bring this issue over to that forum instead?

**Comment by jorisvandenbossche** [comment]
>  Would you recommend that I bring this issue over to that forum instead?

Yes, that would be good!

**Comment by jorisvandenbossche** [comment]
This was reported as https://github.com/Toblerity/Fiona/issues/1208 and further discussed there, so closing here.
