### ISSUE TITLE
DOC: include example notebooks in sphinx docs

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#280]
For greater visibility of those notebooks.

Several options I think: more manually converting with nbconvert to rst and including that (but can be automated, I think statsmodels does this), or maybe look into something like https://nbsphinx.readthedocs.org/en/0.2.5/

**Comment by nickeubank** [comment]
You ok with just doing in-lines like `pandas`? Just requires adding some lines in the `conf.py` file: https://ipython.org/ipython-doc/3/api/generated/IPython.sphinxext.ipython_directive.html

I'm doing that in #283 just because it's familiar.

**Comment by martinfleis** [comment]
I am trying to resolve this rather old issue. In a current situation, we are using `sphinx-gallery` to generate gallery of examples. However, it works only with specifically designed .py files. We have 9 examples in the master brach, but only 4 of them are shown within gallery, rest of the are not .py files but jupyter notebooks. That is the main issue at the moment.

There is a possibility to convert .ipynb files to .py to be readable by `sphinx-gallery`, but it would not work for interactive examples (like those using folium/leaflet), so it does not sound like a right pathway. The other option is to have all examples as .ipynb and use above mentioned `nbsphinx` to handle them. The main difference would be the need of inclusion of examples in TOC tree. `sphinx-gallery` just scan the folder and generate examples from every .py file there.

There might be other options as well, but I feel that it might be worth switching from `sphinx-gallery` to `nbsphinx` and keep all examples as jupyter notebooks. Before I will try to make a PR implementing it, I'd like to hear your thoughts on it. @jorisvandenbossche you mentioned before that you prefer `sphinx-gallery`. For what reason?
