### ISSUE TITLE
Docs for 0.2

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#281]
Trying to make a list of updates since 0.1.1 that need to be reflected in docs. [Judging by this from around first release](https://github.com/geopandas/geopandas/compare/a4a88c7e96c758f2d50e7af907b...master), I'm seeing:

* update requirements (and add installation instructions for each)
* Add `sjoin`
* New options for `plot`
* New options for `to_file`
* Add `iterfeatures`

Missing anything?

I may also re-organize the functions section (if people don't mind) into:

* Input / output
* Managing Projections
* Geometric manipulations
* Mapping

Also: do we have any spatial data loaded in the library a user can just import? Helpful for examples.

**Comment by jorisvandenbossche** [comment]
> Also: do we have any spatial data loaded in the library a user can just import? Helpful for examples.

Good idea. There are example data sets, but they are only included in the top-level `\examples` folder, and this is not distributed in the archives on pypi I think. Maybe open a separate issue for that. 
There is also the `download_nybb`  functions in https://github.com/geopandas/geopandas/blob/master/tests/util.py#L38, but also not distributed at the moment.

> I may also re-organize the functions section (if people don't mind) into:

I think that is fine. Maybe also split in mutliple pages ?

Further, besides updating the docs itself, we should also make a changelog/whatsnew page that lists those new features I think.

**Comment by jorisvandenbossche** [comment]
> New options for plot

Also changes in the keywords (eg axes -> ax, colormap -> cmap), old ones are deprecated.

**Comment by nickeubank** [comment]
@jorisvandenbossche Great. Will open a new issue for included data. Will submit skeleton for suggested doc updates shortly.

**Comment by nickeubank** [comment]
@jorisvandenbossche @kjordahl Any thoughts on where to put `overlay` in the doc architecture? Not sure if it goes with "geometric operations" (as a form of set operations), with "merging data" (since it relates different datasets, though it is qualitatively different from joins in that it creates new geometries) or on its own page.

**Comment by nickeubank** [comment]
List of last things to add after PRs processed:

- [ ] dissolve in docs
- [ ] change path for sjoin and overlay
- [ ] reference integrated data in doc examples

Others?

(Also need dissolve PR to fix some tweaks)

**Comment by jorisvandenbossche** [comment]
I will do a PR for the example data (unless you beat me to it)
