### ISSUE TITLE
Include example data in distribution

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#282]
Seems like it'd be helpful to have a simple spatial dataset included in the distribution that we can use when writing examples and which users can just import and play with (I know `igraph` does this). 

Something universal but not to big -- medium or low resolution map of country outlines? Maybe as a GeoSeries with also as a simple GeoDataFrame with population or something?

Here's public domain [shapefiles](http://www.naturalearthdata.com/) ([terms of use say no permission needed for any purpose](http://www.naturalearthdata.com/about/terms-of-use/))

**Comment by nickeubank** [comment]
[Discovered `pysal` has example data!](http://www.pysal.org/users/tutorials/examples.html)

Seems like makes more sense to just offer API to that than build our own.

**Comment by jorisvandenbossche** [comment]
I would personally in favor for still including *some* data in geopandas, as pysal is not that easy to install, eg because it is not yet python 3 compatible

**Comment by nickeubank** [comment]
@jorisvandenbossche OK. Do you like their API? In our context, it would look like they would live in `gdp.examples`.

**Comment by darribas** [comment]
As of [version 1.11](https://github.com/pysal/pysal/releases/tag/v1.11.0), PySAL is Python 3 compatible and has no dependencies other than numpy and scipy, plus it's pure Python. It's available through Pypi too, so it's as easy to install as it gets.

**Comment by jorisvandenbossche** [comment]
@darribas Aha good to hear! (I struggled with it last summer). But you should update the installation instruction in the docs then :-) http://pysal.readthedocs.org/en/latest/users/installation.html#install-pysal

**Comment by darribas** [comment]
@jorisvandenbossche Thanks very much for catching that! I've filed a [bug report](https://github.com/pysal/pysal/issues/787) so it should get fixed soon.
