### ISSUE TITLE
ENH: Function to show layers in a particular file

### ISSUE THREAD

**Issue by Robinlovelace** [geopandas/geopandas#2837]
As far as I can tell, the only way to see the layers in a particular file is to read the file first, e.g.

```python
import geopandas as gpd

# read the GeoPackage file
gdf = gpd.read_file('your_geopackage_file.gpkg')

# list the layer names
layer_names = list(gdf.name)
print(layer_names)
```

Would it be possible/useful to add a function that takes the file name as the first argument and returns the layers? This from the `sf` package could provide some inspiration: https://r-spatial.github.io/sf/reference/st_layers.html

Apologies in the like event I've missed something, fairly new to this space!

**Comment by martinfleis** [comment]
You can use either `pyogrio.list_layers(path)` or `fiona.listlayers(path)`. The code above will not work for that as `gdf` is only a single layer of that gpkg (the first one, unless specified).

We have discussed exposing this on geopandas level but want probably wait for when `pyogrio` becomes the default engine and expose pyogrio's functionality. While it is conceptually the same as fiona's, it returns a slightly different objects.

**Comment by Robinlovelace** [comment]
Thanks for the detailed response, makes sense: you can get the layers but need to use the data I/O engine because the output varies depending on which one use. Logical to add this enhancement after `pyorgrio` becomes default. Will take a look at the roadmap to get a handle on when that is. Learning as I go!

**Comment by martinfleis** [comment]
Probably early 2024.

**Comment by jorisvandenbossche** [comment]
We could also already add it earlier (if someone works on it) and provide a small shim for fiona? I think using the existing fiona APIs, it should be much work to have something that returns the same (getting the geometry type from `meta` dictionary).

**Comment by EwoutH** [comment]
I just worked with geopackage that had multiple layers, of which I didn't expect multiple layers in there at first, giving me unexpected data. While in the end I figured it out, I think some improvements in handeling geopackages with multiple layers are certainly possible.

A function that lists layer names would be useful. I think `read_file()` could also be improved when handeling multiple layers. The default behavior is to just silently load only the first layer it encounters. Something more explicit could be done there, for example:
1. It could require the `layer` keyword argument to be specified when loading a geopackage with multiple layers
2. It could warn that there are multiple layers and it only loads the first, if the `layer` argument isn't provided.

If you agree on how to explicitly handle multiple layers, I would be willing to write an PR for it.

**Comment by jorisvandenbossche** [comment]
> 2\. It could warn that there are multiple layers and it only loads the first, if the `layer` argument isn't provided.

That's actually what was just changed in pyogrio, see https://github.com/geopandas/pyogrio/issues/355 / https://github.com/geopandas/pyogrio/pull/362

**Comment by EwoutH** [comment]
That's great to hear, thanks!
