### ISSUE TITLE
BUG: ProjError: x, y, z, and time must be same size when reprojecting census shapefile

### ISSUE THREAD

**Issue by rdisalv2** [geopandas/geopandas#2874]
- [ yes ] I have checked that this issue has not already been reported.

- [ yes - 0.12.2 ] I have confirmed this bug exists on the latest version of geopandas.

- [ no ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# 1 Download and unzip US CBSA shapefile from US Census: https://www2.census.gov/geo/tiger/TIGER2017/CBSA/tl_2017_us_cbsa.zip (the error happens with other shapefiles too, this is just the one that I'm working with)

# 2 load the shapefile and try to reproject it

import geopandas as gpd
cbsa17 = gpd.read_file('tl_2017_us_cbsa.shp')
print(cbsa17.crs) # epsg:4269
cbsa17_latlon = cbsa17.to_crs('epsg:4326') # ProjError: x, y, z, and time must be same size

# this error occurs with geopandas 0.12.2, this code works fine with geopandas 0.10.2 (see also https://stackoverflow.com/questions/75872652/geopandas-to-crs-return-projerror-x-y-z-and-time-must-be-same-size).

```

#### Problem description

Current behavior: reprojecting a census tigerline shapefile throws an error
Desired behavior: reprojecting works

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]
executable : C:\Users\rdisa\anaconda3\python.exe
machine    : Windows-10-10.0.19043-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.8.0
GEOS lib   : None
GDAL       : 3.6.2
GDAL data dir: None
PROJ       : 6.2.1
PROJ data dir: C:\Users\rdisa\anaconda3\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.21.5
pandas     : 1.5.3
pyproj     : 2.6.1.post1
shapely    : 2.0.1
fiona      : 1.9.1
geoalchemy2: None
geopy      : None
matplotlib : 3.7.1
mapclassify: 2.5.0
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : 1.0.1

</details>

**Comment by martinfleis** [comment]
Can you show the full traceback and ideally share the file so we are able to reproduce the issue?

**Comment by martinfleis** [comment]
FIY, I am not able to reproduce the issue. The first thing I would recommend is to update PROJ and pyproj to latest versions to see if that fixes the issue.

**Comment by rdisalv2** [comment]
Thanks, I followed your advice but ended up having to uninstall and reinstall anaconda on the machine due to package problems. It works now! Here's my new geopandas.show_versions()

<details>

SYSTEM INFO
-----------
python     : 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:00:38) [MSC v.1934 64 bit (AMD64)]
executable : C:\Users\rdisa\anaconda3\python.exe
machine    : Windows-10-10.0.19043-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.2
GEOS lib   : None
GDAL       : 3.6.3
GDAL data dir: None
PROJ       : 9.2.0
PROJ data dir: C:\Users\rdisa\anaconda3\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.23.5
pandas     : 1.5.3
pyproj     : 3.5.0
shapely    : 2.0.1
fiona      : 1.9.3
geoalchemy2: None
geopy      : None
matplotlib : 3.7.1
mapclassify: 2.5.0
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : 1.0.1

</details>
