### ISSUE TITLE
ENH: simplify as in GRASSGIS v.generalize

### ISSUE THREAD

**Issue by sehHeiden** [geopandas/geopandas#2894]
I wish I could simplify neighbouring polygons, so that they still share the same border.
Normal simiplification results in empty space or overlapping between the polygons.
My current workaround is to use GRASSGIS v.generalize from qgis.

**Comment by martinfleis** [comment]
One (not very performant) way of doing so is illustrated in https://github.com/geopandas/geopandas/issues/1387. The topological simplification of polygonal coverage is currently being implemented in GEOS and once it propagates too shapely, we will surely expose it in GeoPandas. 

I'll close this issue in favour of #1387 but be assured that it is in the pipeline. I just don't know when we'll see it.
