### ISSUE TITLE
BUG: Possible bug in test_geodataframe.py, test_sjoin being skipped by impossible condition

### ISSUE THREAD

**Issue by chris-hedemann** [geopandas/geopandas#2899]
- [ x] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of geopandas.

- [x ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

This is the current test in test_geodataframe.py: 
```python
# Your code here
@pytest.mark.skipif(
        not (compat.USE_PYGEOS and compat.HAS_RTREE and compat.USE_SHAPELY_20),
        reason="sjoin needs `rtree` or `pygeos` dependency",
    )
    def test_sjoin(self, how, predicate):
        """
        Basic test for availability of the GeoDataFrame method. Other
        sjoin tests are located in /tools/tests/test_sjoin.py
        """
        left = read_file(geopandas.datasets.get_path("naturalearth_cities"))
        right = read_file(geopandas.datasets.get_path("naturalearth_lowres"))

        expected = geopandas.sjoin(left, right, how=how, predicate=predicate)
        result = left.sjoin(right, how=how, predicate=predicate)
        assert_geodataframe_equal(result, expected)
```

#### Problem description

I believe that the condition ``compat.USE_PYGEOS and compat.USE_SHAPELY_20`` means that this test is ALWAYS skipped, since ``USE_PYGEOS = not(USE_SHAPELY_20)``.

#### Expected Code

```python
# Your code here
@pytest.mark.skipif(
        not (compat.USE_PYGEOS or compat.HAS_RTREE or compat.USE_SHAPELY_20),
        reason="sjoin needs `rtree` or `pygeos` dependency",
    )
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 09:05:00) [Clang 14.0.6 ]
executable : -
machine    : macOS-13.3.1-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.2
GEOS lib   : None
GDAL       : 3.6.4
GDAL data dir: -
PROJ       : 9.2.0
PROJ data dir: -
PYTHON DEPENDENCIES
-------------------
geopandas  : 0+untagged.1761.g1f27f35.dirty
numpy      : 1.24.3
pandas     : 2.0.1
pyproj     : 3.5.0
shapely    : 2.0.1
fiona      : 1.9.3
geoalchemy2: 0.13.2
geopy      : 2.3.0
matplotlib : 3.7.1
mapclassify: 2.5.0
pygeos     : None
pyogrio    : None
psycopg2   : 2.9.3 (dt dec pq3 ext lo64)
pyarrow    : 12.0.0
rtree      : 1.0.1

</details>

**Comment by m-richards** [comment]
Thanks for this @chris-hedemann, I believe this is correct, a PR would certainly be welcome.

**Comment by chris-hedemann** [comment]
Hey @m-richards, no worries! Here is the PR.
