### ISSUE TITLE
geopandas.org versus geopandas.readthedocs.org

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#290]
@kjordahl you recently revived the read the docs for geopandas: https://github.com/geopandas/geopandas/pull/255, so it now is up to date: https://geopandas.readthedocs.org/

This is handy to have up to date docs for the development version, but we could also use it for the main landing page of http://geopandas.org/ ? Then we don't have two separate places with docs

http://docs.readthedocs.org/en/latest/canonical.html

**Comment by nickeubank** [comment]
Seems reasonable to me. I didn't even know geopandas.readthedocs.org existed!

**Comment by jorisvandenbossche** [comment]
@kjordahl It would be nice to decide on this as well for the 0.2 release. IMO the easiest would be to use the contents on the readthedocs one for geopandas.org as well, and it seems this is rather easy to use your own domain: http://docs.readthedocs.io/en/latest/canonical.html

**Comment by kjordahl** [comment]
Given that we don't understand why readthedocs builds are timing out (#333) , let's keep geopandas.org for release docs for now. I'll update the site after the 0.2 release.

**Comment by jorisvandenbossche** [comment]
The time out is solved, so the readthedocs pages are up to date again: http://geopandas.readthedocs.io/en/master/index.html#

**Comment by jorisvandenbossche** [comment]
This came up again after the 0.5 release. Having the geopandas.org docs separately hosted from geopandas.readthedocs.io gives some extra work (need to build the docs locally and push to gh-pages branch, need to think about this every release). 
The argument before seemed to have been the stability of readthedocs builds. That has been a problem recently as well, but that is mainly an issue for the "latest" development docs. Even when that build is failing, the last built "stable" is always available. So I think we could use geopandas.org for the stable readthedocs.

**Comment by martinfleis** [comment]
I agree, It would be ideal if we used geopandas.org as a custom domain (https://docs.readthedocs.io/en/latest/custom_domains.html) pointing at "stable" build. However, we needed the help of RTD support this time to make it work (rtfd/readthedocs.org/issues/5598). How reliable is it? We might run out of memory again, RTD might refuse to give us another increase and we might end with no up-to-date docs at all.

**Comment by jorisvandenbossche** [comment]
> we might end with no up-to-date docs at all.

I would say this is even an argument to point geopandas.org to readthedocs for now and use the geopandas.org url everywhere (in the readme, docs, ..), instead of the current readthedocs links (which we can start doing if geopandas.org points to the readthedocs version). That also makes it possible to, if we have a problem with readthedocs in the future, point geopandas.org again at gh-pages to keep things working without breaking urls. As long as we use the readthedocs url, we are indeed dependent on them to have up to date docs.

Of course, we could also investigate the options to move away from readthedocs (eg doctr on travis combined with hosting on gh-pages is a reasonable option I think). But given that readthedocs increased the build resources now, I would like to give them some time to see how it works out now.

**Comment by martinfleis** [comment]
> use the geopandas.org url everywhere (in the readme, docs, ..), instead of the current readthedocs links
That makes sense. Then we would have an absolute control and we can point geopandas.org wherever we want to. 
> But given that readthedocs increased the build resources now, I would like to give them some time to see how it works out now.
Okay, I'm up for it, since all builds are passing now.

**Comment by humitos** [comment]
Hi! I'm one of the maintainers at RTD. I'm very happy that you want to user RTD as your main documentation hosting :smiley: 

> Having the geopandas.org docs separately hosted from geopandas.readthedocs.io gives some extra work

Despite using or not RTD to host the documentation, I suggest you to use the domain that you control as a the main URL everywhere (`geopandas.org` or `docs.geopandas.org`). That way, you are not locked-in to any service.

> However, we needed the help of RTD support this time to make it work ([rtfd/readthedocs.org/issues/5598](https://github.com/rtfd/readthedocs.org/issues/5598)). How reliable is it? We might run out of memory again, RTD might refuse to give us another increase and we might end with no up-to-date docs at all.

Regarding your build time/memory out, I checked your builds and you are using only 200mb extra from the general limit. This is probably due a [known bug in `conda` that eats more memory than it should](https://github.com/conda/conda/issues/5003) when creating the environment. We hope this bug could be solved soon and your build probably will start using less memory after that automatically.

Besides, we could increase the time/memory limit in case you need more since you are not producing tons of builds in a day. 

Finally, we plan to do some improvements to our build process in the near future and this should allow us to build fast.

I hope this helps you to make a decision all together. Thanks!

**Comment by martinfleis** [comment]
Bumping up this issue as it is present again after 0.5.1 release. @jorisvandenbossche is there anything we can do about it? Ideally pointing geopandas.org to stable build on readthedocs?

**Comment by martinfleis** [comment]
We will have to touch DNS records anyway. After #1063 we have got following warning:
> The page build completed successfully, but returned the following warning for the `gh-pages` branch: 

> The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/en/articles/using-a-custom-domain-with-github-pages.

**Comment by martinfleis** [comment]
Resolved :). geopandas.org now points to the RTD build.
