### ISSUE TITLE
BUG: unable to do round trip IO with GPKG files

### ISSUE THREAD

**Issue by pmlpm1986** [geopandas/geopandas#2901]
- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of geopandas.

- [x ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### How to reproduce the problem

```python
from geopandas import GeoDataFrame, read_file
from shapely.geometry import Point
gdf = GeoDataFrame(
    {
      'data': [None,None],
      'new': [3.4,4.5], 
      'geometry': [Point(1, 2), Point(3,4)],
      },
    index=['a','b']
    )
gdf.to_file('test.gpkg')
gdf2 = read_file('test.gpkg')
print(gdf)
print(gdf2)
```

#### Problem description

I have using GeoDataFrame objects in a project that involves IO and the GPKG format and I have come across a potential bug.

Previously (with Fiona 1.8), I was able to write a file with a GeoDataFrame column of Nones and read it back as Nones too.

Now (with Fiona 1.9.3), I read that file as NaN, which requires me to do pre-processing before writing the file. The previous behaviour makes more sense to me but perhaps there is a reason for this change.

#### Expected Output

I expected to get an exact replica of the GeoDataFrame I previously saved. Instead, I got one with a column full of NaNs instead of Nones.

#### Cause

@jorisvandenbossche was able to trace this behaviour to the way the GeoDataFrame constructor loads features (here: https://github.com/Toblerity/Fiona/issues/1270).

### Fix

I implemented and tested a solution. It is a bit hacky and my tests were not especially comprehensive.

Currently, in version 0.13, we have:
```
@classmethod
def from_features(cls, features, crs=None, columns=None):
  (...)
  rows = []
  for feature in features_lst:
      # load geometry
      if hasattr(feature, "__geo_interface__"):                
          feature = feature.__geo_interface__
```
Instead, we could perhaps have:

```
@classmethod
def from_features(cls, features, crs=None, columns=None):
  (...)
  rows = []
  for feature in features_lst:
      # load geometry
      if hasattr(feature, "__geo_interface__"):                
          _properties = dict(feature["properties"].__dict__['_data'])
          feature = feature.__geo_interface__
          feature["properties"] = _properties
```

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
executable : /xxx/bin/python3
machine    : Linux-6.1.0-7-amd64-x86_64-with-glibc2.36

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.5.3
GDAL data dir: /yyy/python3.11/site-packages/fiona/gdal_data
PROJ       : 9.2.0
PROJ data dir: /yyy/python3.11/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.13.0
numpy      : 1.24.3
pandas     : 2.0.1
pyproj     : 3.5.0
shapely    : 2.0.1
fiona      : 1.9.3
geoalchemy2: None
geopy      : 2.3.0
matplotlib : 3.7.1
mapclassify: None
pygeos     : None
pyogrio    : 0.6.0
psycopg2   : None
pyarrow    : None
rtree      : 1.0.1

</details>

**Comment by martinfleis** [comment]
I have a tendency to say that this is an upstream issue but let's see how the discussion in Fiona issue evolves.

**Comment by theroggy** [comment]
This seems to have been solved upstream?
https://github.com/Toblerity/Fiona/issues/1270

**Comment by martinfleis** [comment]
Before closing this, we should probably add a test for this on our side.
