### ISSUE TITLE
ENH: simple, compact and reversible JSON interface

### ISSUE THREAD

**Issue by loco-philippe** [geopandas/geopandas#2904]
#### Is your feature request related to a problem?

Actually there is no JSON interface available.

#### Describe the solution you'd like

I propose a simple, compact and reversible interface. The solution exists for pandas data and will be simple to extend to geopandas.
[-> see Notebook example](https://nbviewer.org/github/loco-philippe/NTV/blob/main/example/example_pandas.ipynb)

#### API breaking implications

This feature  results in the addition of a new API (no modification of existing API)

#### Describe alternatives you've considered

No alternative (pandas JSON interface is not enough).

#### Additional context

pandas issue exists [(#53252)](https://github.com/pandas-dev/pandas/issues/53252)

**Comment by martinfleis** [comment]
See my comment over at https://github.com/pandas-dev/pandas/issues/53252#issuecomment-1565073502. I will close the issue as it is currently and upstream issue and if pandas decides to adopt the specification, we likely inherit it. Any geospatial flavour of JSON NTV would also need to go through the same process I touched in the pandas repo.
