### ISSUE TITLE
REGRESSION: handle URLs in read_file that are not automatically handled by Fiona / pyogrio

### ISSUE THREAD

**Issue by brendan-ward** [geopandas/geopandas#2908]
GeoPandas previously always read all bytes from a URL before passing those bytes to Fiona / pyogrio for reading.  In #2796, we removed this because it forced download of the entire (potentially large) file rather than leveraging capabilities built into specific file formats and GDAL for reading only subsets of that file from a remote URL.

However, this broke cases where GDAL (as used in Fiona / pyogrio) does not automatically detect the correct file format based on the file extension.  For example, a ZIP archive available via URL without a *.zip extension is not handled correctly.

Potential workarounds specified in [this comment](https://github.com/geopandas/geopandas/pull/2796#discussion_r1192877922).

**Comment by vlandau-vp** [comment]
I was about to post an new issue but I think this one already covers the problem I'm having. I'm getting a DriverError from Fiona when reading a file from a URL in 0.13.0 (but it worked fine in 0.12.2)

Here's the MWE:
```python
import geopandas as gpd
gpd.read_file('https://gis-calema.opendata.arcgis.com/datasets/59d92c1bf84a438d83f78465dce02c61_0.geojson')
```

Here's the full error message:
```
Traceback (most recent call last):
  File "fiona/ogrext.pyx", line 136, in fiona.ogrext.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: '/vsicurl/https://gis-calema.opendata.arcgis.com/datasets/59d92c1bf84a438d83f78465dce02c61_0.geojson?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 248, in _read_file
    return _read_file_fiona(
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 289, in _read_file_fiona
    with reader(path_or_bytes, **kwargs) as features:
  File "/usr/local/lib/python3.10/dist-packages/fiona/env.py", line 457, in wrapper
    return f(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/fiona/__init__.py", line 292, in open
    colxn = Collection(
  File "/usr/local/lib/python3.10/dist-packages/fiona/collection.py", line 243, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 588, in fiona.ogrext.Session.start
  File "fiona/ogrext.pyx", line 143, in fiona.ogrext.gdal_open_vector
fiona.errors.DriverError: '/vsicurl/https://gis-calema.opendata.arcgis.com/datasets/59d92c1bf84a438d83f78465dce02c61_0.geojson?outSR=%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D' not recognized as a supported file format.
```

Looks like this should be fixed by #2914?

**Comment by jorisvandenbossche** [comment]
@vlandau-vp thanks for the additional example! 
Unfortunately, that shows that my solution in #2914 is actually not sufficient .. Because there I am assuming that if the url has a file extension, it's fine to read it with `/vsicurl/`. But your example shows that this is also not a perfect check.

**Comment by jorisvandenbossche** [comment]
Updated the PR with a different approach (checking if the URL supports reading ranges), and this should fix it the last example in https://github.com/geopandas/geopandas/issues/2908#issuecomment-1572869891 as well (that url doesn't support reading ranges, so we will still download it up front)

**Comment by vlandau-vp** [comment]
Excellent, glad my use case was helpful. Thanks for all your work on geopandas!
