### ISSUE TITLE
add `get_geometry` method for GeoDataFrames?

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#291]
Right now, it looks like the only way to see which column is the active geometry column is to look at the `_geometry_column_name` attribute. But I was always taught users should never go near things that start with an underscore. 

Should we add a `get_geometry` to match `set_geometry`? Something that just gives back value of `_geometry_column_name`?

**Comment by jorisvandenbossche** [comment]
`gdf.geometry.name` ?

**Comment by nickeubank** [comment]
@jorisvandenbossche Does that work even if you have a column named "geometry"? How does it handle that collision?

**Comment by jorisvandenbossche** [comment]
the `geometry` attribute will always give you back the geometry, whether it is called geometry or not. So in this way, the actual also does not really matter

See here: https://github.com/geopandas/geopandas/blob/master/geopandas/geodataframe.py#L87

**Comment by nickeubank** [comment]
@jorisvandenbossche OK. 

I'm imaging a world where I have a column that ISN'T the "geometry column" (say I did `set_geometry('centroids')` and then wanted to access the column still called "geometry" (which is the name given by default) but is not the "geometry column" any more. gdf.geometry will return the "centroids" column, not the column still named "geometry"?

**Comment by jorisvandenbossche** [comment]
Yes, just like a column called 'mean', you will not be able to get with `df.mean`, but need to use `df['mean']`

**Comment by nickeubank** [comment]
Got it.

**Comment by jorisvandenbossche** [comment]
But again, this is not really explained in the docs.

Also, on your original idea, I would suspect `get_geometry` to give me back the actual data, not only the name. But for that there is of course already the `geometry` property.

**Comment by nickeubank** [comment]
Any thoughts on banning columns from being called "geometry"? Seems like this is a recipe for mass confusion when you have a column named "geometry" that is NOT the "geometry column"...
