### ISSUE TITLE
BUG: test suite fails due to 'pandas.core.util' has no attribute 'hashing' error in 3.10 dev

### ISSUE THREAD

**Issue by JamesGardiner** [geopandas/geopandas#2911]
- [x] I have checked that this issue has not already been reported.

- [] I have confirmed this bug exists on the latest version of geopandas.

- [] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Problem description

Test suites (specifically the ubuntu-latest, ci/envs/310-dev.yaml test) are intermittently failing with the following error: 

```FAILED geopandas/tests/test_extension_array.py::TestMethods::test_hash_pandas_object - AttributeError: module 'pandas.core.util' has no attribute 'hashing'```. This is causing pull requests to be marked as failing.

See https://github.com/geopandas/geopandas/actions/runs/5110922869/jobs/9187351485?pr=2877 for an example of the failure.

#### Expected Output
Test suites should pass.

#### Output of ``geopandas.show_versions()``
Only failing in CI

**Comment by martinfleis** [comment]
@jorisvandenbossche I suppose this is a pandas issue since the test is defined there, no? I am not aware of any place where we would override anything related.

**Comment by jorisvandenbossche** [comment]
Yes, this is indeed fully on the pandas side: fixing the import in https://github.com/pandas-dev/pandas/pull/53474

If it is annoying (I don't know how often it happens?), we can temporary fix it on our side until 2.0.3 is out (in one month)

**Comment by martinfleis** [comment]
Haven't seen it in wild and no report of seeing that outside of CI has been filed so I'd wait for pandas patch.

**Comment by JamesGardiner** [comment]
Closing as https://github.com/pandas-dev/pandas/pull/53474 has fixed this (was only occuring on git installs of the pandas dev branch from what I can see)
