### ISSUE TITLE
BUG: GeoDataFrame.from_features doesn't keep features id

### ISSUE THREAD

**Issue by ZaraGi** [geopandas/geopandas#2917]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---
#### Code Sample, a copy-pastable example
```python
feature_coll = {
    "type": "FeatureCollection",
    "features": [
        {
            "id": "a",
            "type": "Feature",
            "properties": {"col1": "name1"},
            "geometry": {"type": "Point", "coordinates": (1.0, 2.0)},
            "bbox": (1.0, 2.0, 1.0, 2.0),
        },
        {
            "id": "3",
            "type": "Feature",
            "properties": {"col1": "name2"},
            "geometry": {"type": "Point", "coordinates": (2.0, 1.0)},
            "bbox": (2.0, 1.0, 2.0, 1.0),
        },
    ],
    "bbox": (1.0, 1.0, 2.0, 2.0),
}
df = gpd.GeoDataFrame.from_features(feature_coll)
df
```

#### Problem description
The from_features GeoDataFrame constructor does not take into account the 'id' field of the features and the generated GeoDataFrame loses any reference to that field.

#### Expected Output
The expected output should be a GeoDataFrame with the index (or a column 'id') corresponding to the 'id' field of the features.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
executable : /home/usr/tmp-venv/bin/python
machine    : Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.4.3
GDAL data dir: /home/usr/tmp-venv/lib/python3.10/site-packages/fiona/gdal_data
PROJ       : 9.1.0
PROJ data dir: /home/usr/tmp-venv/lib/python3.10/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.13.1
numpy      : 1.23.5
pandas     : 2.0.1
pyproj     : 3.4.1
shapely    : 2.0.1
fiona      : 1.8.22
geoalchemy2: None
geopy      : None
matplotlib : 3.6.3
mapclassify: 2.5.0
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : 10.0.1
rtree      : 1.0.1

</details>

**Comment by martinfleis** [comment]
Hi, thanks for the report. This is a known limitation reported in #1208 with a proposed solution in #2003. I will close this as a duplication but feel free to follow the other issues I linked.

**Comment by ZaraGi** [comment]
Hi, thank you for the fast response. Sorry, I marked this issue as not reported because i couldn't fint the ones you linked.
