### ISSUE TITLE
Increase flexibility of `to_crs` function

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#292]
Right now, the CRS tools won't accept a proj4 string as a string -- it requires they be broken out into a dictionary. But behind the scenes is the pyproj library which parses proj4 strings quite well. 

I propose a small change to the `to_crs` implementation (PR #288) that would preserve current functionality (can still pass CRS as dictionaries) but also allow users to just pass proj4 strings.

**Comment by jorisvandenbossche** [comment]
Closed by #288
