### ISSUE TITLE
BUG: .explore() shows incorrect colors with scheme = 'UserDefined'

### ISSUE THREAD

**Issue by sofiecr** [geopandas/geopandas#2922]
#### Code Sample

```python
import geopandas as gpd
import geodatasets

chicago = gpd.read_file(geodatasets.get_path("geoda.chicago_commpop"))

bins=[25000, 50000, 75000, 100000]
chicago.plot(column='POP2010', scheme='UserDefined', classification_kwds={'bins': bins}, 
             legend=True, legend_kwds={'loc': 'upper left', 'bbox_to_anchor': (1, 1)})
```

```python
chicago.explore(column='POP2010', scheme='UserDefined', classification_kwds={'bins': bins}, tooltip=['POP2010'], legend=True)
```

#### Problem description

When using `scheme='UserDefined'` the colors differ when using `.plot()` and `.explore()`. 
In `.explore()` values between 75000 and 100000 are light green, whereas when using `.plot()` these are yellow. The legends for both visuals are the same though.

The problem seems to be that there are values in the dataset not included in the bins.
If I change this to `bins=[0, 25000, 50000, 75000, 100000]`, then the colors in `.explore()` are correct, but in `.plot()` an extra category is added to the legend, i.e. '-inf, 0.00', even though there is no data in this bin. 

#### Expected Output
I would expect `.plot()` and `.explore()` to show the same colors and legend.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
executable : [c:\Python310\python.exe](file:///C:/Python310/python.exe)
machine    : Windows-10-10.0.19044-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.5.2
GDAL data dir: [c:\Python310\lib\site-packages\fiona\gdal_data](file:///C:/Python310/lib/site-packages/fiona/gdal_data)
PROJ       : 9.1.0
PROJ data dir: [c:\Python310\lib\site-packages\pyproj\proj_dir\share\proj](file:///C:/Python310/lib/site-packages/pyproj/proj_dir/share/proj)

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.13.2
numpy      : 1.23.1
pandas     : 1.4.3
pyproj     : 3.4.0
shapely    : 1.8.5.post1
fiona      : 1.8.22
geoalchemy2: None
geopy      : 2.3.0
matplotlib : 3.6.3
mapclassify: 2.4.3
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : 11.0.0
rtree      : 1.0.1

</details>

**Comment by martinfleis** [comment]
Thanks for the report! Can confirm. Fix is up in #2923.
