### ISSUE TITLE
BUG: read_postgis not working with shapely 2.0.1

### ISSUE THREAD

**Issue by Fourthbus** [geopandas/geopandas#2924]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

Cannot read PostgreSQL with shapely 2+. This has been noticed also on [https://stackoverflow.com/questions/75223195/getting-attributeerror-module-shapely-geos-has-no-attribute-lgeos](https://stackoverflow.com/questions/75223195/getting-attributeerror-module-shapely-geos-has-no-attribute-lgeos). It would be good if this bug can be addressed.

#### Code Sample, a copy-pastable example

I tried to import geometry from PostgreSQL
```python
gdf = gpd.read_postgis(sql, con=engine, geom_col='geom' )
```

#### Problem description
Python returns error
```python
File ~\.conda\envs\*\lib\site-packages\geopandas\io\sql.py:163, in _read_postgis(sql, con, geom_col, crs, index_col, coerce_float, parse_dates, params, chunksize)
    152 if chunksize is None:
    153     # read all in one chunk and return a single GeoDataFrame
    154     df = pd.read_sql(
    155         sql,
    156         con,
   (...)
    161         chunksize=chunksize,
    162     )
--> 163     return _df_to_geodf(df, geom_col=geom_col, crs=crs)
    165 else:
    166     # read data in chunks and return a generator
    167     df_generator = pd.read_sql(
    168         sql,
    169         con,
   (...)
    174         chunksize=chunksize,
    175     )

File ~\.conda\envs\*\lib\site-packages\geopandas\io\sql.py:88, in _df_to_geodf(df, geom_col, crs)
     86 df[geom_col] = geoms = geoms.apply(load_geom)
     87 if crs is None:
---> 88     srid = shapely.geos.lgeos.GEOSGetSRID(geoms.iat[0]._geom)
     89     # if no defined SRID in geodatabase, returns SRID of 0
     90     if srid != 0:

AttributeError: module 'shapely.geos' has no attribute 'lgeos'
```

#### Output of ``geopandas.show_versions()``

<details>
SYSTEM INFO
-----------
python     : 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]
executable : ~\.conda\envs\*\python.exe
machine    : Windows-10-10.0.20348-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : None
GEOS lib   : None
GDAL       : 3.6.2
GDAL data dir: None
PROJ       : 8.2.1
PROJ data dir: ~\.conda\envs\*\lib\site-packages\pyproj\proj_dir\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.11.1
numpy      : 1.24.3
pandas     : 1.4.4
pyproj     : 3.3.1
shapely    : 2.0.1
fiona      : 1.9.1
geoalchemy2: None
geopy      : None
matplotlib : 3.5.3
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : 2.9.3 (dt dec pq3 ext lo64)
pyarrow    : 11.0.0
rtree      : 1.0.1

</details>

**Comment by martinfleis** [comment]
Make sure to update geopandas to at least version 0.12 but ideally 0.13. I see you have an outdated version in your env currently.

**Comment by Fourthbus** [comment]
Problem solved  by running
```bash
conda install -c conda-forge geopandas=0.13.2
```
