### ISSUE TITLE
Add function to create fishnet/grid

### ISSUE THREAD

**Issue by SpatLyu** [geopandas/geopandas#2928]
#### Is your feature request related to a problem?

I wish I could use geopandas to  create fishnet/grid

#### Describe the solution you'd like

Add a function to create fishnet/grid

#### API breaking implications

A function will be added

#### Describe alternatives you've considered
I'm a GIS major student. In my research and study life,a regular GIS operation is to create fishnet/grid. I use Python/R for geocomputation. I found in R library `sf` ,it has the function called `st_make_grid` which can create fishnet/grid.,But I can't find a similar function in geopandas,so I have writted one use shapely and geopandas to achieve it . Can geopandas team add it to geopandas?(Sorry ,I'm the first time to make suggestions for open source projects and I like geopandas very much . I hope I can use geopandas to apply all my vector data process task and I don't know how to pull my code to geopandas so I choose to open a feature request. I'm sorry if I've caused you any trouble)
#### Additional context

```python
# Your code here, if applicable
def make_grid(gdf,cellsize,what='polygons',square=True):
    
    '''
        gdf : object of class geodataframe;
        
        cellsize : numeric  with target cellsize;
        
        what : character; one of: "polygons" or "centers"
               
        square : logical; if FALSE, create hexagonal grid
    '''
    
    from shapely import geometry
    
    minX, minY, maxX, maxY =  gdf.bounds.values.reshape(-1,1)
    minX, minY, maxX, maxY =  minX[0], minY[0], maxX[0], maxY[0]
    x, y = (minX, minY)
    geom_array = []
    
    if square:
        while y <= maxY:
            while x <= maxX:
                geom = geometry.Polygon([(x,y), (x, y+cellsize), (x+cellsize, y+cellsize), (x+cellsize, y), (x, y)])
                geom_array.append(geom)
                x += cellsize
            x = minX
            y += cellsize
    else:
        i = 1
        while y <= maxY:
            while x <= maxX:
                geom = geometry.Polygon([(x,y-cellsize), 
                                         (x+pow(3,0.5)/2*cellsize, y-0.5*cellsize), 
                                         (x+pow(3,0.5)/2*cellsize, y+0.5*cellsize), 
                                         (x,y+cellsize),
                                         (x-pow(3,0.5)/2*cellsize, y+0.5*cellsize),
                                         (x-pow(3,0.5)/2*cellsize, y-0.5*cellsize), 
                                         (x,y-cellsize)])
                geom_array.append(geom)
                x += pow(3,0.5)*cellsize
                
            i += 1
            y += 1.5*cellsize
            
            if i % 2 == 0:   
                x = minX + pow(3,0.5)/2*cellsize
            else:
                x = minX
            

    gdf_grid = gpd.GeoDataFrame(geometry = geom_array,
                                crs = gdf.crs)
        
    if what == 'centers':
        gdf_grid = gpd.GeoDataFrame(geometry = gdf_grid.geometry.centroid,
                                    crs = gdf.crs)
        
    return gdf_grid  
```

**Comment by martinfleis** [comment]
Thanks for the suggestion! This has already been discussed in #2062 and is being implemented in #2197 (plus was discussed and partially included in #2363.

I'll close this as a duplication but feel free to continue discussion in #2197 or #2062.
