### ISSUE TITLE
ENH: preserve relative order in `clip`

### ISSUE THREAD

**Issue by fbunt** [geopandas/geopandas#2937]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

I wasn't sure if this behavior is intended so I left the BUG label.

#### Code Sample

```python
>>> import geopandas as gpd
>>> import numpy as np
>>> import shapely
>>>
>>> z = np.array([5, 2, 4, 0, 3, 1])
>>> gdf = gpd.GeoSeries.from_xy(z, z).to_frame("geometry")
>>> bbox = shapely.geometry.box(0, 0, 2, 2)
>>> gdf
                  geometry
0  POINT (5.00000 5.00000)
1  POINT (2.00000 2.00000)
2  POINT (4.00000 4.00000)
3  POINT (0.00000 0.00000)
4  POINT (3.00000 3.00000)
5  POINT (1.00000 1.00000)

>>> gdf.clip(bbox)
                  geometry
3  POINT (0.00000 0.00000)
5  POINT (1.00000 1.00000)
1  POINT (2.00000 2.00000)
```

#### Problem description

Clipping a `GeoDataFrame` produces a result that has been shuffled. It looks like the result is sorted based on a spatial index. This is not noted in the documentation and was not what I expected to happen.

#### Expected Output

I expected clip to maintain the relative order in the result or for this behavior to be documented.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)  [GCC 11.3.0]
executable : /home/fred/anaconda3/envs/rstools/bin/python3.9
machine    : Linux-5.15.0-73-generic-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.2
GEOS lib   : None
GDAL       : 3.7.0
GDAL data dir: /home/fred/anaconda3/envs/rstools/share/gdal
PROJ       : 9.2.1
PROJ data dir: /home/fred/anaconda3/envs/rstools/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.13.2
numpy      : 1.24.3
pandas     : 2.0.2
pyproj     : 3.6.0
shapely    : 2.0.1
fiona      : 1.9.4
geoalchemy2: None
geopy      : None
matplotlib : 3.7.1
mapclassify: 2.5.0
pygeos     : 0.14
pyogrio    : 0.6.0
psycopg2   : None
pyarrow    : 12.0.0
rtree      : 1.0.1

</details>

**Comment by martinfleis** [comment]
Thanks for the report. It is not necessarily a bug but it may be nice to preserve the order. The result of the query on spatial index is not sorted and we don't do anything to sort it. We may consider that, though. It just may not be needed for a lot of use cases and would add unnecessary step. Sorting of a large array can be expensive.

```py
>>> gdf.sindex.query(bbox, predicate="intersects")
array([3, 5, 1])
```

The solution would be to sort the query output here https://github.com/geopandas/geopandas/blob/5dd0c963faa854ffbc42f68459dc13097b3f2e56/geopandas/tools/clip.py#L50

**Comment by nicholas-ys-tan** [comment]
sindex seems to already have a sort function in it (technically not preserving the order if the data being fed is disordered).

Would it be worthwhile exposing the sort option as a kwarg in clip?

https://github.com/geopandas/geopandas/blob/5dd0c963faa854ffbc42f68459dc13097b3f2e56/geopandas/sindex.py#L47

**Comment by martinfleis** [comment]
> Would it be worthwhile exposing the sort option as a kwarg in clip?

If it solves the issue then it is a fairly minimal fix we should go for.
