### ISSUE TITLE
ENH: add attribute checking for an active geometry column

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2941]
It may be useful to have an attribute on a `GeoDataFrame` that tells a user if an active geometry column is set or not. In a use case in OSMnx (https://github.com/gboeing/osmnx/pull/1012), they pass dict-based data to the constructor but they do not know if the dict has a `geometry` or not. So they're then checking for a presence of a `"geometry"` column, which works but feels like we could do more to support such cases. If you are dealing with a more generic input, you may have an active geometry column called differently and checking for that is a bit unwelcoming at the moment.

I would propose to add an attribute like `GeoDataFrame.has_geometry` or `.has_active_geometry` that would check the contents of `_geometry_column_name` and return a boolean depending if it is `None` or a string. You can then safely retrieve `GeoDataFrame.geometry` or set a new column, depending on what you need.

**Comment by gboeing** [comment]
This sounds very helpful.

**Comment by martinfleis** [comment]
>  (although one could always do gdf.geometry.name for that, once you know that gdf.geometry will not raise an error)

I was having this workflow in mind but it may be actually better what you suggest as it simplifies other use cases and is not that complicated for the boolean check. I'll update #2943 accordingly.
