### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by pushkarnimkar** [geopandas/geopandas#2945]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

I tried running the example from [this](https://geopandas.org/en/v0.13.2/gallery/plotting_with_geoplot.html#Plotting-with-Geoplot) tutorial. There is an error in the tutorial notebook, and I could replicate that with the latest version of geopandas. I see the error first appeared when transitioning from v0.12.2 to v0.13.0.

#### Code Sample, a copy-pastable example

```python
# Here's the code from the tutorial
world = geopandas.read_file(
    geopandas.datasets.get_path('naturalearth_lowres')
)
geoplot.polyplot(world, figsize=(8, 4))
```

It throws the following error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/kaggle/lib/python3.11/site-packages/geoplot/geoplot.py:885, in polyplot.<locals>.PolyPlot.draw(self)
    884 try:  # Duck test for MultiPolygon.
--> 885     for subgeom in geom:
    886         feature = GeopandasPolygonPatch(
    887             subgeom, facecolor=facecolor, edgecolor=edgecolor, zorder=zorder,
    888             **kwargs
    889         )

TypeError: 'MultiPolygon' object is not iterable

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
Cell In[17], line 1
----> 1 geoplot.polyplot(world, figsize=(8, 4))

File ~/miniconda3/envs/kaggle/lib/python3.11/site-packages/geoplot/geoplot.py:901, in polyplot(df, projection, extent, figsize, ax, **kwargs)
    898         return ax
    900 plot = PolyPlot(df, figsize=figsize, ax=ax, extent=extent, projection=projection, **kwargs)
--> 901 return plot.draw()

File ~/miniconda3/envs/kaggle/lib/python3.11/site-packages/geoplot/geoplot.py:892, in polyplot.<locals>.PolyPlot.draw(self)
    890                 ax.add_patch(feature)
    891         except (TypeError, AssertionError):  # Shapely Polygon.
--> 892             feature = GeopandasPolygonPatch(
    893                 geom, facecolor=facecolor, edgecolor=edgecolor, zorder=zorder,
    894                 **kwargs
    895             )
    896             ax.add_patch(feature)
    898 return ax

File ~/miniconda3/envs/kaggle/lib/python3.11/site-packages/geopandas/plotting.py:129, in _PolygonPatch(polygon, **kwargs)
    125 from matplotlib.patches import PathPatch
    126 from matplotlib.path import Path
    128 path = Path.make_compound_path(
--> 129     Path(np.asarray(polygon.exterior.coords)[:, :2]),
    130     *[Path(np.asarray(ring.coords)[:, :2]) for ring in polygon.interiors],
    131 )
    132 return PathPatch(path, **kwargs)

AttributeError: 'MultiPolygon' object has no attribute 'exterior'
```
#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.11.3 | packaged by conda-forge | (main, Apr  6 2023, 08:57:19) [GCC 11.3.0]
executable : /home/nimkar/miniconda3/envs/kaggle/bin/python
machine    : Linux-5.4.0-150-generic-x86_64-with-glibc2.31

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.2
GEOS lib   : None
GDAL       : 3.7.0
GDAL data dir: /home/nimkar/miniconda3/envs/kaggle/share/gdal
PROJ       : 9.2.0
PROJ data dir: /home/nimkar/miniconda3/envs/kaggle/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.13.2
numpy      : 1.24.3
pandas     : 2.0.2
pyproj     : 3.5.0
shapely    : 2.0.1
fiona      : 1.9.4
geoalchemy2: None
geopy      : 2.3.0
matplotlib : 3.7.1
mapclassify: 2.5.0
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : 1.0.1

</details>

Excuse me if this is a duplicate issue, but I could not find one when I tried looking it up. Happy to help resolve this if this has not been addressed yet,

**Comment by martinfleis** [comment]
Thanks for the report. This is an issue in `geoplot` package which needs to change this line in their code:

```diff
- for subgeom in geom:
+ for subgeom in geom.geoms:
```
That is because MultiPolygons in shapely 2.0 are no longer iterable. There's nothing we can do on GeoPandas side, apart from removing that example from our documentation (which may be wise as it is broken for some time).

@ResidentMario (the author of geoplot) mentioned that he does not have time to maintain the project and it seems that it has been a bit abandoned since last year. Try opening an issue there and we may eventually try to reach to Aleksey and check what the optimal future of the package may be. 

Closing on our side as a bug outside our reach.

**Comment by ResidentMario** [comment]
Yeah, I definitely don't have as much time for OSS maintenance that I did when I was still in school and/or underemployed. 😅

I try to budget open source maintenance days from time to time, but it looks like it's been a year since the last time I did. How time flies...

I'll try to take a look this weekend.
