### ISSUE TITLE
GeoSeries.astype(object) no longer returns Series with pandas main

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2948]
Since 3 days ago, this snippet no longer returns a Series with an object dtype but a practically unchanged GeoSeries with a geometry dtype.

```py
from geopandas import GeoSeries
from shapely.geometry import Point

s = GeoSeries([Point(x, y) for x, y in zip(range(3), range(3))])
s.astype(object)
```

It causes [failures](https://github.com/geopandas/geopandas/actions/runs/5395983405/jobs/9799094074) of our CI. Not sure which change on pandas side caused this (maybe https://github.com/pandas-dev/pandas/pull/52132 ??) but it feels like a regression there. 

@jorisvandenbossche do you have an idea what is going on before I'll report it on pandas side?

**Comment by jorisvandenbossche** [comment]
Yes, that's indeed the relevant PR. It's on my TODO list to look into it and fix it on the pandas side

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/geopandas/geopandas/pull/3046
