### ISSUE TITLE
nybb_14aav no longer available (tests failing)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#295]
http://www.nyc.gov/html/dcp/download/bytes/nybb_14aav.zip gives a 'This page is not available' error.
And because of this all the tests that rely on downloading this are failing.

I would suggest to just include the data itself in the geopandas sources. 
But is there anyone who knows what the license of those data is? Are we allowed to include it?

**Comment by micahcochran** [comment]
Here the link to the webpage that contains the data.  Under the Bourgh Boundaries & Community Districts expandable drop down.
http://www1.nyc.gov/site/planning/data-maps/open-data/districts-download-metadata.page

Here is what the metadata states:
> This dataset is being provided by the Department of City Planning (DCP) on DCP’s website for informational purposes only. DCP does not warranty the completeness, accuracy, content, or fitness for any particular purpose or use of the dataset, nor are any such warranties to be implied or inferred with respect to the dataset as furnished on the website. DCP and the City are not liable for any deficiencies in the completeness, accuracy, content, or fitness for any particular purpose or use the dataset,or applications utilizing the dataset, provided by any third party.

This says nothing about redistribution.

City governments have different rules from the US Federal government (all works are public domain), but there are still some expectation that tax payers can get information.  That being said, it might be a good idea to email them about including their data, and if they do allow it state that it is provided by the New York City Planning Department.

If they do not allow it, I can think of a replacement of using municipal limits around some cities using US Census data (public domain data).

**Comment by micahcochran** [comment]
I submitted PR #296, but I think the long term solution would be to redistribute the nybb data with geopandas.

**Comment by jorisvandenbossche** [comment]
The data is accessible from the open data website from NYC: https://data.cityofnewyork.us/City-Government/Borough-Boundaries/tqmj-j8zm

In any case, I didn't find it explicitly stated that you can redistribute those data, but I think in the general definition of open data this notion is included.
