### ISSUE TITLE
NA handling in argsort compat with pandas

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#2967]
Pandas deprecated the current behaviour of NA handling in argsort in https://github.com/pandas-dev/pandas/pull/54219 which causes our CI to fail on dev. The reason is that we do not preserve the actual None in a GeometryArray [here](https://github.com/geopandas/geopandas/blob/8c00e10feed0f4299624b10f07b4ea79aba42d54/geopandas/array.py#L1324) but replace them eventually with 0, to be sorted at the beginning of the array. This was mostly consistent with pandas until now because they were using -1, so the result was the same. In a future version, NA values will be ordered last in pandas, which would mean that we need to use max int value instead, unless we want to cast the array no a nullable integer dtype or something like that and leave the NA handling to pandas.

The CI probably fails because there is no warning emitted because after a call to `_values_for_argsort`, there's no NA anymore.

I would probably add a similar deprecation on our side and switch from assigning 0 to assigning max int in 1.0. That way the behaviour would eventually be the same as pandas will have. Ideally, we would delegate this to pandas but that would come at a performance (and memory) cost.

**Comment by jorisvandenbossche** [comment]
> The reason is that we do not preserve the actual None in a GeometryArray [here](https://github.com/geopandas/geopandas/blob/8c00e10feed0f4299624b10f07b4ea79aba42d54/geopandas/array.py#L1324) but replace them eventually with 0, to be sorted at the beginning of the array

This should be fine, as pandas explicitly documents that those values are being ignored, and the sorting of nulls to the beginning or end of the array is handled by pandas. From the `_values_for_argsort` docstring:

> Functions that use this (e.g. ``ExtensionArray.argsort``) should ignore
> entries with missing values in the original array (according to
> ``self.isna()``). This means that the corresponding entries in the returned
> array don't need to be modified to sort correctly.

**Comment by m-richards** [comment]
I think we can close this one given that we no longer have this issue in CI, and it seems that this should be automatically handled by pandas in user code.
