### ISSUE TITLE
ENH: Set geometry column automatically when converting GeoSeries to GeoDataFrame

### ISSUE THREAD

**Issue by kadyb** [geopandas/geopandas#2974]
In `{sf}` when converting `sfc` (list) to `sf` (dataframe) the geometry column is set automatically, but in `{geopandas}` not? I suggest that the geometry would be set automatically when converting `GeoSeries` to `GeoDataFrame`.

```r
library("sf")

wkb = "01010000204071000000000000801A064100000000AC5C1441"
wkb = structure(list(wkb), class = "WKB")
sfc = st_as_sfc(wkb, EWKB = TRUE)
sf = st_as_sf(sfc)
st_geometry(sf)
#> Geometry set for 1 feature 
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 181072 ymin: 333611 xmax: 181072 ymax: 333611
#> Projected CRS: Amersfoort / RD New
#> POINT (181072 333611)
```

```python
import geopandas

wkb = "01010000204071000000000000801A064100000000AC5C1441"
gs = geopandas.GeoSeries.from_wkb([wkb])
gdf = geopandas.GeoDataFrame(gs)
gdf.geometry
#> AttributeError: You are calling a geospatial method on the GeoDataFrame, but the active geometry column to use has not been set. 
#> There are columns with geometry data type ([0]), and you can either set one as the active geometry with df.set_geometry("name") #> or access the column as a GeoSeries (df["name"]) and call the method directly on it.
```

**Comment by m-richards** [comment]
The existing idiomatic way of doing this is to either
```python
wkb = "01010000204071000000000000801A064100000000AC5C1441"
gs = geopandas.GeoSeries.from_wkb([wkb])
gdf = gs.to_frame()
```
or by providing the geoseries as the geometry column:
`gdf2 = geopandas.GeoDataFrame(geometry=gs)`

I suppose we could special case this, but given there are already two ways of doing this, I don't think it's essential.

**Comment by martinfleis** [comment]
It would be a special case that brings inconsistency so I am not sure I would support that. But truth is, that users may expect the behaviour @kadyb outlined above.

**Comment by kadyb** [comment]
Thanks! I think we can close. `geopandas.GeoDataFrame(geometry=gs)` is ok for me.
