### ISSUE TITLE
BUG: geometry and associated attributes lose their alignment in `clip`

### ISSUE THREAD

**Issue by martinzbl** [geopandas/geopandas#2977]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely.geometry import Polygon

# Creates dummy GeoDataFrame with polygons
def create_dummy_gdf(n_poly):
    polys = []
    for i in range(n_poly):
            polys.append(Polygon([(i, 0), (i+1, 0), (i+1, 1), (i, 1)]))
    return gpd.GeoDataFrame({'name': [f'poly_{i}' for i in range(n_poly)], 'geometry': polys})

# Creates dummy crop mask that clips first n polygons
def create_crop_mask(num_pol):
    return Polygon([(0, 0), (num_pol_to_crop - 0.5, 0), (num_pol_to_crop - 0.5, 1), (0, 1)])


gdf = create_dummy_gdf(20)
pol_to_check = 'poly_13'
crop_mask_16 = create_crop_mask(16)
crop_mask_17 = create_crop_mask(17)

# Clip gdf with two different masks
gdf_cropped_16 = gpd.clip(gdf, crop_mask_16)
gdf_cropped_17 = gpd.clip(gdf, crop_mask_17)
# prints
#       name                                                                                              geometry
#13  poly_13  POLYGON ((13.00000 0.00000, 14.00000 0.00000, 14.00000 1.00000, 13.00000 1.00000, 13.00000 0.00000))
#      name                                                                                              geometry
#13  poly_13  POLYGON ((13.00000 0.00000, 13.00000 1.00000, 14.00000 1.00000, 14.00000 0.00000, 13.00000 0.00000))
#       name                                                                                         geometry
#13  poly_13  POLYGON ((2.00000 0.00000, 2.00000 1.00000, 3.00000 1.00000, 3.00000 0.00000, 2.00000 0.00000))

```

#### Problem description

When performing a clipping operation on a GeoDataFrame, a situation may arise where the geometry and associated attributes lose their alignment. For instance, if we clip US states to only retain their western parts, it could lead to incorrect names for a number of states. An illustrative case involves polygon 13: prior to clipping, its geometry corresponds appropriately with its attributes, but after clipping, its geometry aligns with another polygon's shape, resulting in a mismatch between geometries and their associated attributes. This discrepancy tends to occur specifically when the GeoDataFrame contains over 16 geometries subsequent to the clipping process.

#### Expected Output
       name                                                                                              geometry
13  poly_13  POLYGON ((13.00000 0.00000, 14.00000 0.00000, 14.00000 1.00000, 13.00000 1.00000, 13.00000 0.00000))
      name                                                                                              geometry
13  poly_13  POLYGON ((13.00000 0.00000, 13.00000 1.00000, 14.00000 1.00000, 14.00000 0.00000, 13.00000 0.00000))
       name                                                                                         geometry
13  poly_13  POLYGON ((13.00000 0.00000, 13.00000 1.00000, 14.00000 1.00000, 14.00000 0.00000, 13.00000 0.00000))
#### Output of ``geopandas.show_versions()``

SYSTEM INFO
-----------
python     : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
executable : C:\SRDEV\python-env\flood5\Scripts\python.exe
machine    : Windows-10-10.0.22621-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.5.2
GDAL data dir: C:\SRDEV\python-env\flood5\lib\site-packages\fiona\gdal_data
PROJ       : 9.2.1
PROJ data dir: C:\SRDEV\python-env\flood5\lib\site-packages\pyproj\proj_dir\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.13.2
numpy      : 1.25.2
pandas     : 1.5.0
pyproj     : 3.6.0
shapely    : 2.0.1
fiona      : 1.8.22
geoalchemy2: None
geopy      : None
matplotlib : 3.7.2
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : 1.0.1
</details>

**Comment by martinzbl** [comment]
With geopandas 0.9.0 clipping works as expected.

**Comment by m-richards** [comment]
Are you able to replicate this in a fresh environment? I'm having some trouble reproducing your outputs, I've tried 0.13.2 and main against my environments with pandas 2, 1.5.2 and 1.4 installed.

**Comment by martinzbl** [comment]
I have tried and there was no issue (fresh env with geopandas 0.13.2 and pandas 2.0.3). But after forcing to reinstall pandas to 1.5.0 the issue was back. With pandas 1.5.2 there is no issue. So it seems that the bug is specifically coming from pandas 1.5.0 with combination of geopandas > 0.9.0. Weird.

**Comment by m-richards** [comment]
Thanks for that extra info, I thought this seemed familar, but now that you've linked it to pandas 1.5.0 I realised this is the same as #2558. Given it's an upstream issue and it's already been patched, I don't think there's any action to be taken by us.
