### ISSUE TITLE
BUG: pytz.exceptions.UnknownTimeZoneError: 'US/Eastern'

### ISSUE THREAD

**Issue by sebastic** [geopandas/geopandas#2979]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Problem description

tzdata (2023c-8) in Debian no longer provides the US timezones:
> ```
>   * Ship only timezones in tzdata that follow the current rules of geographical
>     region (continent or ocean) and city name. Move all legacy timezone symlinks
>     (that are upgraded during package update) to tzdata-legacy. This includes
>     dropping the special handling for US/* timezones. (Closes: #1040997)
> ```

This causes the test suite to fail with an exception:
```
pytz.exceptions.UnknownTimeZoneError: 'US/Eastern'
```
Using `America/New_York` instead resolves the issue:
```diff
--- a/geopandas/io/tests/test_file.py
+++ b/geopandas/io/tests/test_file.py
@@ -184,7 +184,7 @@ def test_to_file_bool(tmpdir, driver, ex


 TEST_DATE = datetime.datetime(2021, 11, 21, 1, 7, 43, 17500)
-eastern = pytz.timezone("US/Eastern")
+eastern = pytz.timezone("America/New_York")

 datetime_type_tests = (TEST_DATE, eastern.localize(TEST_DATE))

```

**Comment by jorisvandenbossche** [comment]
@sebastic thanks for the report!
