### ISSUE TITLE
BUG: Incomplete initialization of fiona

### ISSUE THREAD

**Issue by mousey92** [geopandas/geopandas#2987]
- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
>>> import geopandas as gpd
>>> gpd.io.file.fiona.supported_drivers["LIBKML"] = "rw"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'supported_drivers'
```

#### Problem description

When using GeoPandas, the file format I use most often aside from .shp is .kml, so I often have to start my code with enabling those in fiona. The only reference to this I found in the docs is to use 

 ```python
import fiona
fiona.supported_drivers["<driver>"] = "rw"
```

but I've found this can also be done with

```python
import geopandas as gpd
gpd.io.file.fiona.supported_drivers["<driver>"] = "rw"
```

However, this seems to only be enabled __after__ ```gpd.read_file``` is called, even if that fails.

```python
>>> import geopandas as gpd
>>> gpd.io.file.fiona.supported_drivers["LIBKML"] = "rw"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'supported_drivers'
>>> gdf = gpd.read_file("test.kml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Matthijs.Kramer\Mambaforge\envs\work\Lib\site-packages\geopandas\io\file.py", line 259, in _read_file
    return _read_file_fiona(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Matthijs.Kramer\Mambaforge\envs\work\Lib\site-packages\geopandas\io\file.py", line 303, in _read_file_fiona
    with reader(path_or_bytes, **kwargs) as features:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matthijs.Kramer\Mambaforge\envs\work\Lib\site-packages\fiona\env.py", line 457, in wrapper
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Matthijs.Kramer\Mambaforge\envs\work\Lib\site-packages\fiona\__init__.py", line 336, in open
    colxn = Collection(
            ^^^^^^^^^^^
  File "C:\Users\Matthijs.Kramer\Mambaforge\envs\work\Lib\site-packages\fiona\collection.py", line 252, in __init__
    self.guard_driver_mode()
  File "C:\Users\Matthijs.Kramer\Mambaforge\envs\work\Lib\site-packages\fiona\collection.py", line 273, in guard_driver_mode
    raise DriverError("unsupported driver: %r" % driver)
fiona.errors.DriverError: unsupported driver: 'LIBKML'
>>> gpd.io.file.fiona.supported_drivers["LIBKML"] = "rw"
>>> gdf = gpd.read_file("test.kml")
>>> gdf.shape
(923, 12)
```

Every time I try to first set the support using the gpd.io.file.fiona method and it fails, it leads to me pulling my hair out trying to figure out why. This is not really a problem, since I can simply remember to import fiona separately and set the read-write support for KML that way, but it still feels like fiona is not initialized properly, perhaps that can lead to other issues I've not found yet.

#### Expected Output

I expect fiona to be properly imported when geopandas is imported itself
```python
>>> import geopandas as gpd
>>> gpd.io.file.fiona.supported_drivers["LIBKML"] = "rw"
>>> gdf = gpd.read_file("test.kml")
>>> gdf.shape
(923, 12)
````

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]
executable : C:\Users\Matthijs.Kramer\Mambaforge\envs\work\python.exe
machine    : Windows-10-10.0.22621-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.2
GEOS lib   : None
GDAL       : 3.6.3
GDAL data dir: None
PROJ       : 9.2.0
PROJ data dir: C:\Users\Matthijs.Kramer\Mambaforge\envs\work\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.25.1
pandas     : 2.0.3
pyproj     : 3.6.0
shapely    : 2.0.1
fiona      : 1.9.3
geoalchemy2: None
geopy      : None
matplotlib : 3.7.2
mapclassify: 2.5.0
pygeos     : None
pyogrio    : None
psycopg2   : 2.9.3 (dt dec pq3 ext lo64)
pyarrow    : 11.0.0
rtree      : 1.0.1

</details>

**Comment by martinfleis** [comment]
Fiona is intentionally not initialized until needed to allow geopandas to run without fiona being installed at all. I would strongly recommend using 

```py
import fiona
fiona.supported_drivers["<driver>"] = "rw"
```

rather than `gpd.io.file.fiona.supported_drivers`. The latter is not a supported pattern.

I will close this but feel free to re-open if you think this shall be somehow solved on our side.

**Comment by mousey92** [comment]
That's a fair use case, agreed this is closed
