### ISSUE TITLE
CI: test failures in the dev build (with nightly pandas)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#2998]
There are currently a bunch of failures in the dev build (eg https://github.com/geopandas/geopandas/actions/runs/6048816668/job/16414905026)

* The argsort failure will be fixed by https://github.com/geopandas/geopandas/pull/2993
* Some failures are related to the `na_value` fixture. I tested changing the `GeometryDtype.na_value` to None, but that still gives a lot of test failures in our CI (although it might be fixed with pandas >= 2, see https://github.com/geopandas/geopandas/pull/2997). For now I am proposing to revert this specific change to the extension tests in pandas -> https://github.com/pandas-dev/pandas/pull/54930
* `geopandas/tests/test_pandas_methods.py::test_groupby_metadata` is failing, didn't yet investigate
* `geopandas/tools/tests/test_sjoin.py::TestNearest::test_sjoin_nearest_exclusive[None-expected0]` is failing, didn't yet investigate

**Comment by jorisvandenbossche** [comment]
> `geopandas/tests/test_pandas_methods.py::test_groupby_metadata` is failing, didn't yet investigate

Just posting the reproducer here from the tests:

```python
from geopandas import GeoDataFrame
from shapely import Point

crs = None

df = GeoDataFrame(
    {
        "geometry": [Point(0, 0), Point(1, 1), Point(0, 0)],
        "value1": np.arange(3, dtype="int64"),
        "value2": np.array([1, 2, 1], dtype="int64"),
    },
    crs=crs,
)

res = df.groupby("value2").apply(
    lambda x: geopandas.sjoin(x, x[["geometry", "value1"]], how="inner")
)
```

With pandas nightly, I see:

```
In [12]: res
Out[12]: 
                         geometry  value1_left  value2  index_right  value1_right
value2                                                                           
1      0  POINT (0.00000 0.00000)            0       1            0             0
       0  POINT (0.00000 0.00000)            0       1            2             2
       2  POINT (0.00000 0.00000)            2       1            0             0
       2  POINT (0.00000 0.00000)            2       1            2             2
2      1  POINT (1.00000 1.00000)            1       2            1             1

```

while with released pandas and geopandas, I see:

```
In [6]: res
Out[6]: 
                         geometry  value1_left  value2  index_right  value1_right
value2                                                                           
1      0  POINT (0.00000 0.00000)            0       1            0             0
       2  POINT (0.00000 0.00000)            2       1            0             0
       0  POINT (0.00000 0.00000)            0       1            2             2
       2  POINT (0.00000 0.00000)            2       1            2             2
2      1  POINT (1.00000 1.00000)            1       2            1             1
```

So it just seems to be a change in order of the rows within the group.

But it seems it's actually the `sjoin` that changed row order output, so not related to groupby:

With pandas nightly:
```
In [14]: group1 = df[df["value2"] == 1]

In [15]: geopandas.sjoin(group1, group1[["geometry", "value1"]], how="inner")
Out[15]: 
                  geometry  value1_left  value2  index_right  value1_right
0  POINT (0.00000 0.00000)            0       1            0             0
0  POINT (0.00000 0.00000)            0       1            2             2
2  POINT (0.00000 0.00000)            2       1            0             0
2  POINT (0.00000 0.00000)            2       1            2             2
```

while with released pandas this also gives the [0, 2, 0, 2] index order

**Comment by jorisvandenbossche** [comment]
Potentially related:

* https://github.com/pandas-dev/pandas/pull/54611

**Comment by m-richards** [comment]
> Potentially related:
> 
> * [BUG: merge not always following documented sort behavior pandas-dev/pandas#54611](https://github.com/pandas-dev/pandas/pull/54611)

From a bisect, this is the commit where our test started failing, and as expected, the behaviour change comes from the merge in `_frame_join` (specifically the second one in the chain), so I think we're safe to just update the values in the test.

**Comment by m-richards** [comment]
CI is now green on all of these so I think we can close this off.
