### ISSUE TITLE
Move `sjoin` to top namespace?

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#302]
Spatial joins seems pretty central to geopandas, and there's not much else in the `tools` namespace, so we're making the users learn a namespace for one function. Any interest in promoting it to the top namespace? 

I think it would also be more consistent with `pandas` -- `merge` and `concat` both live in the top namespace there.

**Comment by nickeubank** [comment]
Maybe `overlay` too?

**Comment by kjordahl** [comment]
Closed b y#303.
