### ISSUE TITLE
ENH: Mojo programming language support for geopandas

### ISSUE THREAD

**Issue by smoolya17** [geopandas/geopandas#3030]
#### Is your feature request related to a problem?
Currently we are developing a tool for a major broadband service provider which enables them to design and automate the design process of fiber layout for an entire continent. Geopandas though serves as an excellent library to be used alongwith python to visualise this layout of fibre data, problem arises when achieving real time performance requirement and security concerns. Security concerns because currently we are using pyinstaller to create the build for our design tool which uses python.

#### Describe the solution you'd like
Since the release of the new open source dynamic programming language mojo by modular which is designed to be a superset of python and is going to be an AI programming language in future. So pandas comes naturally to this new programming language. Also it has type safety features and security built inherently into it. Alongwith it's performance benchmarks comparable to the types of c++ and rust, geopandas if brought to this platform, can also majorly benefit because of the type safety features with is newly introduced 'let' and 'var' keywords. And also 'struct' keyword which can be used instead of class in python.

If we can have atleast basic features if geopandas of reading and writing mapinfo data or shape files in this programming language and also all of pandas data manipulation techniques as pandas is inherently supported by mojo. A seperate API imports for mojo geopandas can be created and reused
e.g. from geopandas.mojo import read_mapinfo

let data
data = read_mapinfo('C:/cable.tab')

#### API breaking implications

With the above API call there won't be any effect on the current api structure of geopandas 

#### Describe alternatives you've considered
I haven't considered any other alternatives. However would be interested to hear some of the perspectives on other implementations of python.

```

**Comment by martinfleis** [comment]
I don't think this is currently of interest to any of the core devs (though I may be wrong). Can you expand on what would such a support entail? I haven't looked into Mojo in detail.

Also, note that contrary to what you say, Mojo is not open source at the moment. Given that, it is unlikely that GeoPandas will have an interest in supporting Mojo.

**Comment by m-richards** [comment]
As you say mojo is designed as a superset of python, so geopandas should work as is out of the box with existing API. Dataframes (in pandas or geopandas) are not immutable so will not work with `let`.

Improvements to our type annotations are ongoing, and we are likely to focus our efforts on supporting established python static type checkers before experimental things like mojo, but discussions and contributions on how to achieve that would be welcome.

**Comment by smoolya17** [comment]
> I don't think this is currently of interest to any of the core devs (though I may be wrong). Can you expand on what would such a support entail? I haven't looked into Mojo in detail.
> 
> Also, note that contrary to what you say, Mojo is not open source at the moment. Given that, it is unlikely that GeoPandas will have an interest in supporting Mojo.

I guess you are wrong about mojo not being open source, while it can be easily be downloaded from https://developer.modular.com/download

What you might be referring is the cloud mojo engine which is an enterprise version which isn't open source

Also it has been incubated by  Chris lattner, original architect of Swift programming language and programming language in particular uses MLIR and LLVM technology in a compilation based environment. I understand is relatively new and it is only beneficial to AI developers at the moment as it is built to only support the AI community for now so it is a good excuse for now to not have geopandas to run on it.

The questions which is currently posted is very clearly answered here in the link below
https://docs.modular.com/mojo/faq.html
and it has a very active community to answer questions on it. 

I can bet on the captain of the ship Chris and his experienced team who raised a 100 million dollar investment lately from Google Ventures. Yes it is a work in progress so it could be safely said that geopandas support need not be extended for it
