### ISSUE TITLE
Unable to create concave hull in geoseries

### ISSUE THREAD

**Issue by Sidrcs** [geopandas/geopandas#3033]
- I have checked that this issue has not already been reported.
- I have confirmed this bug exists on the latest version of geopandas.

<b>Description of problem</b>: I created a GeoDataFrame from a CSV, which consists of columns Longitude, Latitude, and case, respectively. The case column is of object type and consists of "yes/no" values. The coordinates are in EPSG: 4326 (3D coordinates). I aim to create a concave hull (gift wrapping) around the points as tightly as possible.

- Step 1: I tried to create a list of Shapely Point objects through the iteration of GeoDataFrame
<code>coords_list = []
for row in gdf_ml_yes.itertuples():
    point = Point(float(row.Longitude), float(row.Latitude))
    coords_list.append(point)</code>

- Step 2: To create a GeoSeries object from coordinates list as mentioned above
<code>gdf_ml_yes_gs = gpd.GeoSeries(coords_list)</code>

- Step 3: To create a concave hull using the Geoseries object
<code> gdf_ml_yes_gs.concave_hull()</code>

Unfortunately, it does not return a concave hull, as mentioned in the documentation for <a href = https://geopandas.org/en/latest/docs/reference/api/geopandas.GeoSeries.concave_hull.html#geopandas.GeoSeries.concave_hull> GeoSeries.concave_hull()</a> method.

### Error

<details>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_3724\32573734.py in ?()
----> 1 gdf_ml_yes_gs.concave_hull()

~\anaconda3\envs\geo\lib\site-packages\pandas\core\generic.py in ?(self, name)
   5985             and name not in self._accessors
   5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

AttributeError: 'GeoSeries' object has no attribute 'concave_hull'

</details>

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)]
executable : C:\Users\Sidrcs\anaconda3\envs\geo\python.exe
machine    : Windows-10-10.0.19045-SP0

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.2
GEOS lib   : None
GDAL       : 3.7.0
GDAL data dir: None
PROJ       : 9.2.1
PROJ data dir: C:\Users\Sidrcs\anaconda3\envs\geo\Library\share\proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.13.2
numpy      : 1.24.3
pandas     : 2.0.2
pyproj     : 3.6.0
shapely    : 2.0.1
fiona      : 1.9.4
geoalchemy2: None
geopy      : None
matplotlib : 3.7.1
mapclassify: 2.5.0
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : 12.0.0
rtree      : 1.0.1

</details>

**Comment by martinfleis** [comment]
Concave hull is a new method in GeoPandas 0.14. You have older version in your environment.
