### ISSUE TITLE
BUG: geopandas.to_file( ..........., drive='GPKG' )

### ISSUE THREAD

**Issue by phisan-chula** [geopandas/geopandas#3034]
- [ ] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here
dfPSI.to_file( SCATTER_FILE.with_suffix('.gpck'), layer='Scatterer', drive='GPKG' )
```

#### Problem description
Tippo : drive='GPKG'     instead of driver='GPKG' 
#### Output of ``geopandas.show_versions()``
noerror but got Shapefile instead! 
<details>

(Pdb++) gpd.show_versions()

SYSTEM INFO
-----------
python     : 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
executable : /home/phisan/miniconda3/envs/dbdf/bin/python3
machine    : Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.6.4
GDAL data dir: /home/phisan/miniconda3/envs/dbdf/lib/python3.11/site-packages/fiona/gdal_data
PROJ       : 8.2.1
PROJ data dir: /home/phisan/miniconda3/envs/dbdf/lib/python3.11/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.13.2
numpy      : 1.25.2
pandas     : 2.0.3
pyproj     : 3.4.1
shapely    : 2.0.1
fiona      : 1.9.4.post1
geoalchemy2: None
geopy      : None
matplotlib : 3.7.1
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : 11.0.0
rtree      : None
(Pdb++)

</details>

**Comment by martinfleis** [comment]
This is not a bug. ESRI Shapefile is the default file format, unless we recognise a file extension or you specify `driver`. The file extension of GeoPackage is `.gpkg`, which you haven't used and any additional keyword arguments are passed to GDAL via fiona, which either uses them, or tosses them. You have made two mistakes in the line above (suffix and driver), there is nothing to fix on the GeoPandas side.

**Comment by jorisvandenbossche** [comment]
To be honest, ideally fiona would complain about unknown keyword arguments, so you get notified of your typo. 

With the upcoming version of GeoPandas, we are planning to switch to use `pyogrio` by default in `to_file`, and this engine actually does warn if you make such a typo:

```
In [42]: df = geopandas.GeoDataFrame({"col": [1, 2, 3]}, geometry=geopandas.points_from_xy(range(3), range(3)), crs="EPSG:4326")

In [43]: df.to_file("test.gpck", layer='Scatterer', drive='GPKG', engine="pyogrio")
...
ValueError: unrecognized option 'DRIVE' for driver 'ESRI Shapefile'

```
