### ISSUE TITLE
ENH: Implement `mask` argument for `read_file` with pyogrio backend

### ISSUE THREAD

**Issue by Jaapel** [geopandas/geopandas#3043]
#### Is your feature request related to a problem?

I wish I could use geopandas to open a file using the pyogrio backend using a mask to filter the incoming data.

#### Describe the solution you'd like

Currently, the `read_file` method raises an error when supplying the pyogrio backend with a mask. This mask functionality has recently been implemented there.

#### API breaking implications

This does not break the API.

#### Describe alternatives you've considered

I have considered using `pyogrio.read_dataframe` directly. This requires me to restructure my own code in a serious way, so I'd like to access this functionality via geopandas.

**Comment by Jaapel** [comment]
Thanks @martinfleis , I just noticed. Maybe this helps you: https://github.com/geopandas/geopandas/pull/3044 ?

**Comment by jensdebruijn** [comment]
Pyogrio 0.7 is out now with this feature! However, some minor changes also seem to be required in geopandas as an error is raised here: https://github.com/geopandas/geopandas/blob/1191533c5fc5e5859af9971a64d4f00bffe2b625/geopandas/io/file.py#L439.
