### ISSUE TITLE
overlay gives confusing error when passed `GeoSeries`

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#305]
Should either support or give informative error. Right now gives:

    In [6]: country_cores = overlay(countries, capital_buffer, how='intersection')
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-6-a69b51de5bcf> in <module>()
    ----> 1 country_cores = overlay(countries, capital_buffer, how='intersection')

    /Users/Nick/github/geopandas/geopandas/tools/overlay.py in overlay(df1, df2, how, use_sindex)
         85     # Collect the interior and exterior rings
         86     rings1 = _extract_rings(df1)
    ---> 87     rings2 = _extract_rings(df2)
         88     mls1 = MultiLineString(rings1)
         89     mls2 = MultiLineString(rings2)

    /Users/Nick/github/geopandas/geopandas/tools/overlay.py in _extract_rings(df)
         31     poly_msg = "overlay only takes GeoDataFrames with (multi)polygon geometries"
         32     rings = []
    ---> 33     for i, feat in df.iterrows():
         34         geom = feat.geometry
         35 

    /Users/Nick/github/pandas/pandas/core/generic.py in __getattr__(self, name)
       2665             if name in self._info_axis:
       2666                 return self[name]
    -> 2667             return object.__getattribute__(self, name)
       2668 
       2669     def __setattr__(self, name, value):

    AttributeError: 'GeoSeries' object has no attribute 'iterrows'

**Comment by jorisvandenbossche** [comment]
I think we should also support GeoSeries (but OK for first PR to already better error message)

**Comment by nickeubank** [comment]
@jorisvandenbossche Yup. Again, wanna create new issue and tag 0.3?
