### ISSUE TITLE
COMPAT: pandas BlockManager deprecation warnings

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3060]
DEV CI is generating a lot of deprecation warnings related to passing `BlockManager` or `SingleBlockManager` to a DataFrame or Series constructors respectively.

```
/home/runner/work/geopandas/geopandas/geopandas/geoseries.py:51: DeprecationWarning: Passing a SingleBlockManager to Series is deprecated and will raise in a future version. Use public APIs instead.
    return Series(data=data, index=index, **kwargs)
/home/runner/work/geopandas/geopandas/geopandas/geodataframe.py:138: DeprecationWarning: Passing a BlockManager to GeoDataFrame is deprecated and will raise in a future version. Use public APIs instead.
    super().__init__(data, *args, **kwargs)
```
I think that these are the affected bits on our side:

https://github.com/geopandas/geopandas/blob/8f2b4cc1b2cbb62aed716c9a187e800e79df3cd4/geopandas/geodataframe.py#L131-L138
https://github.com/geopandas/geopandas/blob/8f2b4cc1b2cbb62aed716c9a187e800e79df3cd4/geopandas/geodataframe.py#L1598-L1614
https://github.com/geopandas/geopandas/blob/8f2b4cc1b2cbb62aed716c9a187e800e79df3cd4/geopandas/geoseries.py#L40-L51

I have to admit that it is not immediately clear to me how shall we fix it.

**Comment by jorisvandenbossche** [comment]
https://github.com/geopandas/geopandas/pull/3046 is already partly addressing that

**Comment by m-richards** [comment]
Having a quick look, I think adding a `GeoDataFrame._constructor_from_mgr` should go most of the way towards addressing the rest of the warnings.

**Comment by martinfleis** [comment]
@jorisvandenbossche what is the timeline for these warnings to be in the stable release of pandas? We should aim to resolve them on our side before that as they are really noisy.

**Comment by jorisvandenbossche** [comment]
FWIW this is not _super_ critical. We should certainly try to fix this before it hits pandas stable, but even then those warnings won't be visible to users (unless they enable all warnings, like pytest. So definitly annoying enough to ensure latest geopandas doesn't have that) 
(next pandas 2.2 will be beginning of the next year)

**Comment by jorisvandenbossche** [comment]
But it probably make sense to do a 0.14.x release with those fixes (depending on the timeline for 1.0)

**Comment by martinfleis** [comment]
Yeah, another 0.14.x with this would be nice.

**Comment by martinfleis** [comment]
Resolved.

**Comment by akadouri** [comment]
Will there be a 0.14.x to include the fixes? 

Pandas 2.2.0 came out last week and I started seeing the DeprecationWarnings after upgrading (using GeoPandas 0.14.2) on application crashes & with pytest. I can suppress them, just flagging the issue.

```
../python3.9/site-packages/pandas/core/frame.py:706: DeprecationWarning: Passing a BlockManager to GeoDataFrame is deprecated and will raise in a future version. Use public APIs instead.
  warnings.warn(
../python3.9/site-packages/geopandas/geodataframe.py:1645: DeprecationWarning: Passing a SingleBlockManager to Series is deprecated and will raise in a future version. Use public APIs instead.
```

**Comment by martinfleis** [comment]
Yes, most likely quite soon, we just need to ensure to fix the regression this fix has caused.
