### ISSUE TITLE
BUG: `to_postgis()` not compatible with psycopg v3

### ISSUE THREAD

**Issue by dpprdan** [geopandas/geopandas#3061]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Problem description

The `to_postgis()` docs state:

> This method requires SQLAlchemy and GeoAlchemy2, and a PostgreSQL Python driver (e.g. psycopg2) to be installed.

I understand the "e.g." to mean that other drivers like psycopg (version 3) are/should be possible. 

However, `to_postgis()` or rather `_psql_insert_copy()` uses psycopg2's `copy_expert()` method:
https://github.com/geopandas/geopandas/blob/8f2b4cc1b2cbb62aed716c9a187e800e79df3cd4/geopandas/io/sql.py#L328

`copy_expert()` has been deprecated in psycopg in favor of [a single `copy()` method](https://www.psycopg.org/psycopg3/docs/basic/from_pg2.html#copy-is-no-longer-file-based). Hence, `to_postgis()` fails when used with a psycopg-enabled sqlAlchemy engine.

(More generally the use of a psycopg2 method means that `to_postgis()` only supports _that_ driver and not with any of the [other drivers supported by sqlAlchemy](https://docs.sqlalchemy.org/en/20/dialects/postgresql.html#dialect-postgresql), though I cannot say anything about their practical relevance. Except for [psycopg 3](https://www.psycopg.org/psycopg3/), the successor of psycopg2).

**Comment by martinfleis** [comment]
@dpprdan thanks for the report! Would you be willing to make a pull request adding a support for `psycopg` 3?
