### ISSUE TITLE
DOC: geocoding example is broken

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3064]
Geocoding example in rendered docs is broken. Probably due to many requests from RTD IPs. We may need to execute it manually and exclude from auto execution.

**Comment by jorisvandenbossche** [comment]
I rebuild the stable docs, and now it seems OK: https://geopandas.org/en/stable/docs/user_guide/geocoding.html (unless it was another page that was failing)

But longer term we might indeed want to exclude this from auto execution.

**Comment by martinfleis** [comment]
It is fine now both in stable and latest. Closing. We can reopen if the issue shows up again.
