### ISSUE TITLE
Raise when overriding a CRS via crs property setter

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3085]
When using `set_crs`, we raise a ValueError when the GeoSeries already has a CRS which is not equal to the passed CRS. But when assigning directly to .crs as `gdf.crs = 4326`, we just let user to override the existing CRS, which is a quite common error. 

I propose to add checks to crs property setter and allow assignment only when current crs is None (or equal but None feels safer) and point users either to `set_crs(crs, allow_override=True)` if they really want to override it or to `to_crs(crs)`, which in most cases will be what that actually wanted to do.

This will probably require a deprecation period where we first warn and then raise in a subsequent release. It would be nice to make that switch to raise in 1.0 but I don't think there's 0.15 coming in the meantime, so let's start with a warning.

**Comment by martinfleis** [comment]
Yes, we should surely do it for both.

**Comment by jorisvandenbossche** [comment]
The merged PR in the end also did it for GeoDataFrame, so we can close this issue (I started doing a PR for finishing this, but so then only updating the changelog -> https://github.com/geopandas/geopandas/pull/3333)

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/geopandas/geopandas/pull/3088
