### ISSUE TITLE
COMPAT: pandas main no longer considers numpy array equivalent to IntegerArray

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3093]
Our dev CI has new failures due to some changes on pandas main.

When testing a roundtrip of an `IntegerArray` column in `test_to_file_int32` and `test_to_file_int64`, which are read by fiona as floats, pandas stable is fine with the assertions as we pass `check_dtype=False`. However, on pandas main, the same assertion raises from `assert_class_equal` with 

```bash
E       AssertionError: GeoDataFrame.iloc[:, 0] (column name="data") are different
E       
E       GeoDataFrame.iloc[:, 0] (column name="data") classes are different
E       [left]:  ndarray
E       [right]: IntegerArray
```

It started 4 days ago. I am not certain which commit on pandas side has caused it but it is a bit unexpected, no?

**Comment by m-richards** [comment]
Yep, that does seem a bit odd to me, to permit different dtypes, yet fail because the array class is different. Unless it's to do with nullable integers, hence numpy vs pandas integer array?


(I'm travelling at the moment, so ability to look into things is pretty limited until I'm back)
