### ISSUE TITLE
ENH: Add "dissolve" method to GeoDataFrames

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#310]
Thinking of adding a `dissolve` method to GeoDataFrames. 

Essentially like `groupby` + `unary_union` -- pass a grouping variable, and all shapes within the group will be dissolved. It would also support an `aggfunc` option for aggregating values in associated data. 

For example, suppose I had a US county shapes:

                   state     population    geometry
    county1  CA           100            POLYGON
    county2  CA             50            POLYGON
    county1  VA            75            POLYGON
    county2  VA            25            POLYGON

 and I wanted US state shapes (counties are nested sub-units of states) and there was a column called "state" identifying the state in which each county is located, I could do something like:

    states = counties.dissolve(groupby='state', aggfunc='sum')

And I would get something like:

                    population geometry
          CA    150             POLYGON
          VA     100            POLYGON

Where the new polygons were the output of applying `unary_union` to all shapes in each state group. 

Thoughts?

**Comment by jorisvandenbossche** [comment]
This seems like a nice idea. 
I have only a question about the name `dissolve`. I am not a native English speaker, but to me dissolve has a notion of 'separate'/'break up' (but maybe that is wrong?). While we want to combine/union geoms here?

**Comment by nickeubank** [comment]
It's the term used in ArcGIS for the operation (
pro.arcgis.com/en/pro-app/tool-reference/data-management/dissolve.htm ).
The intuition is that the edges separating things are being dissolved.

**Comment by jorisvandenbossche** [comment]
And seems that QGIS uses the same term (and indeed "dissolving the shared boundaries" already makes more sense :-))

Just thinking: are there other things than 'union' that you would want to do in such a grouping operation? Maybe we would like to be able to do something like `gdf.groupby(..).union()`, so you can also do `gdf.groupby(..).intersection()`

**Comment by nickeubank** [comment]
closed by #311 and  #323
