### ISSUE TITLE
Hi there ,  I am trying to do extract NDVI and SHP file,  raster = r"ndvi.tif" and shp = '2021_ID-45.shp' . The CRS of both files is: EPSG:4326. but I get CRSError: Invalid input to create CRS each time. could anyone help me please? I am stuck for long time now ENH:

### ISSUE THREAD

**Issue by Sahar-2024** [geopandas/geopandas#3118]
#### Is your feature request related to a problem?

[this should provide a description of what the problem is, e.g. "I wish I could use geopandas to do [...]"]

#### Describe the solution you'd like

[this should provide a description of the feature request, e.g. "`GeoDataFrame.foo` should get a new parameter `bar` that [...]", try to write a docstring for the desired feature]

#### API breaking implications

[this should provide a description of how this feature will affect the API]

#### Describe alternatives you've considered

[this should provide a description of any alternative solutions or features you've considered]

#### Additional context

[add any other context, code examples, or references to existing implementations about the feature request here]

```python
# Your code here, if applicable

```

**Comment by martinfleis** [comment]
Please fill the report within the body of the issue, not in its title.
