### ISSUE TITLE
TST: failures on dev due to pandas replacing parametrization with fixtures

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3120]
It seems that pandas removed some explicit parametrisation from EA tests and replaced them with fixtures defined in their global conftest.py. Since we don't have those available on our side, we get errors.

I think it was done in https://github.com/pandas-dev/pandas/pull/56583 (I left a comment there to flag that). This needs to be fixed on their side.

Opening the issue here just as a reference so no one else debugs the same thing.

**Comment by jorisvandenbossche** [comment]
This has been fixed upstream in pandas
