### ISSUE TITLE
pyproj +init warning when saving a GeoDataFrame

### ISSUE THREAD

**Issue by apiszcz** [geopandas/geopandas#3122]
FYSA: saving geodataframe as a shapefile generates the following:

Lib\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

**Comment by martinfleis** [comment]
I doubt it. Are you using the latest geopandas? Can you include reproducible example and an information about your environment that comes via `geopandas.show_versions()`?

**Comment by apiszcz** [comment]
You are correct, geopandas 0.10.2, python 3.11.1.
Will upgrade to latest 0.14.1
Thank you.
