### ISSUE TITLE
BUG: Appending geometries to a shapefile

### ISSUE THREAD

**Issue by mayeroa** [geopandas/geopandas#3135]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely import Polygon

polygon_a = Polygon(((0, 0), (10, 0), (10, 10), (0, 10), (0, 0)))
polygon_b = Polygon(((20, 20), (40, 20), (40, 40), (20, 40), (20, 20)))

series_a = gpd.GeoSeries([polygon_a])
series_b = gpd.GeoSeries([polygon_b])

# Write to disk
series_a.to_file('./test.shp', mode='w')  # Create file because non existing yet
series_b.to_file('./test.shp', mode='a')  # ERROR : cannot append to the previous file
```

#### Problem description

The last command fails with the following error happening:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/envs/ffl/lib/python3.10/site-packages/geopandas/geoseries.py", line 612, in to_file
    data.to_file(filename, driver, index=index, **kwargs)
  File "/home/miniconda3/envs/ffl/lib/python3.10/site-packages/geopandas/geodataframe.py", line 1264, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/home/miniconda3/envs/ffl/lib/python3.10/site-packages/geopandas/io/file.py", line 612, in _to_file
    _to_file_fiona(df, filename, driver, schema, crs, mode, **kwargs)
  File "/home/miniconda3/envs/ffl/lib/python3.10/site-packages/geopandas/io/file.py", line 641, in _to_file_fiona
    colxn.writerecords(df.iterfeatures())
  File "/home/miniconda3/envs/ffl/lib/python3.10/site-packages/fiona/collection.py", line 558, in writerecords
    self.session.writerecs(records, self)
  File "fiona/ogrext.pyx", line 1397, in fiona.ogrext.WritingSession.writerecs
ValueError: Record does not match collection schema: [] != ['FID']
```

This seems that the `to_file` function with the "append" mode is not able to create and increment the FID column with fiona in order to properly write the shapefile.

#### Expected Output

I would expect to append the second geometry into the existing shapefile. 

Do you have a workaround or maybe I'm doing something wrong here...Any help would be welcomed. :)

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
executable : /home/miniconda3/envs/ffl/bin/python
machine    : Linux-5.15.0-60-generic-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.1
GEOS lib   : None
GDAL       : 3.6.4
GDAL data dir: /home/miniconda3/envs/ffl/lib/python3.10/site-packages/fiona/gdal_data
PROJ       : 9.3.0
PROJ data dir: /home/miniconda3/envs/ffl/lib/python3.10/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.2
numpy      : 1.23.5
pandas     : 2.1.1
pyproj     : 3.6.1
shapely    : 2.0.1
fiona      : 1.9.5
geoalchemy2: None
geopy      : None
matplotlib : 3.6.2
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : None
</details>

**Comment by theroggy** [comment]
Not sure, but I suppose because Shapefiles don't like it if there are no attribute columns, GDAL automagically adds an `FID` column if there are no attribute columns. Apparently fiona, the default I/O engine used by geopandas, doesn't want to add rows to a file if columns are missing in the data being written.

So here are some workarounds:
```
import geopandas as gpd
from shapely import Polygon

polygon_a = Polygon(((0, 0), (10, 0), (10, 10), (0, 10), (0, 0)))
polygon_b = Polygon(((20, 20), (40, 20), (40, 40), (20, 40), (20, 20)))

# workaround 1: use pyogrio as I/O engine
a_series = gpd.GeoSeries([polygon_a])
b_series = gpd.GeoSeries([polygon_b])

a_series.to_file("./test_pyogrio.shp", engine="pyogrio")
b_series.to_file("./test_pyogrio.shp", engine="pyogrio", append=True)
b_series.to_file("./test_pyogrio.shp", engine="pyogrio", append=True)
print(gpd.read_file("./test_pyogrio.shp", engine="pyogrio", fid_as_index=True))

# workaround 2: use another format than .shp
a_series.to_file("./test.gpkg", engine="pyogrio")
b_series.to_file("./test.gpkg", engine="pyogrio", append=True)
b_series.to_file("./test.gpkg", engine="pyogrio", append=True)
print(gpd.read_file("./test.gpkg", engine="pyogrio", fid_as_index=True))

# workaround 3: add any attribute column
a_gdf = gpd.GeoDataFrame({"anycolumn": [1]}, geometry=[polygon_a])
b_gdf = gpd.GeoDataFrame({"anycolumn": [2]}, geometry=[polygon_b])

a_gdf.to_file("./test.shp", mode="w")
b_gdf.to_file("./test.shp", mode="a")
b_gdf.to_file("./test.shp", mode="a")
print(gpd.read_file("./test.shp", engine="pyogrio", fid_as_index=True))
```

**Comment by mayeroa** [comment]
Thanks a lot for your quick answer and your help.
Your workarounds are very reasonable. I will use the first one for my scenario. Since `pyogrio` is faster than `fiona` for read/write operations, it is even more relevant. :)
