### ISSUE TITLE
CI: crashes in CI due to azure-core-cpp=1.11.0

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3140]
Since yesterday, we have strange crashes in tests, which are somehow caused by `azure-core-cpp=1.11.0`. I have just tested locally that with 1.10.3, everything is fine and updating to 1.11.0 ends with a lot of errors due to worker crashes due to segfaults. I _think_ that it happens when reading nybb, so a zipped shapefile.

No clue what has `azure-core-cpp` to do with this but would it be possible that is is somehow interfering with GDAL?

**Comment by jorisvandenbossche** [comment]
That package was indeed just updated (https://github.com/conda-forge/azure-core-cpp-feedstock/pull/10), and it's an indirect dependency of gdal (through tiledb, it seems)

**Comment by jorisvandenbossche** [comment]
The package is marked as broken for now, our CI is green again (well, there are still some other failures, but with a different cause ;))

**Comment by martinfleis** [comment]
Thanks!

**Comment by Hoxbro** [comment]
Hi, I just saw our [CI](https://github.com/holoviz/geoviews/actions/runs/7717639495/job/21052296204#step:6:63) fails because of the new patch of azure-core-cpp 1.11.0. A MRE:

``` python
import geodatasets as gds
import geopandas as gpd

file = gds.get_path('geoda airbnb')
gpd.read_file(file)
```

Will output a segmentation fault. 

I was not sure where to post this so I posted it here. Sorry if it is the wrong place.

**Comment by martinfleis** [comment]
@Hoxbro somewhere in upstream, probably https://github.com/conda-forge/tiledb-feedstock/issues/228 ? Not sure what the status of this issue is but it happens quite far from geopandas in practice.
