### ISSUE TITLE
Make pyproj optional?

### ISSUE THREAD

**Issue by micahcochran** [geopandas/geopandas#315]
[Fiona has a transform function](https://github.com/Toblerity/Fiona/blob/master/fiona/transform.py) that appears to be similar to pyproj's transform.  (Fiona's underlying GDAL/OGR calls PROJ.4 directly and it is a dependency.)  This function has been in Fiona since version 1.4.2 (released 2014-Oct-4).

`Geoseries.to_crs` is the only function that uses `pyproj.transform()` or pyproj itself for that matter.

Why keep it optional?  There has been past discussion #219 about using pyshp for `read_file()`, which pyproj would be required to make that happen.   This is a rather small amount of code.  Pyproj could still be required for Fiona versions before 1.4.2.

**Comment by nickeubank** [comment]
I was actually thinking increasing use of pyproj by making available full projection strings (thus my PR on pyproj https://github.com/jswhit/pyproj/pull/78 :)) -- information on projection units, for example, can be very helpful during analyses.

**Comment by micahcochran** [comment]
[GDAL/OGR has a much more robust library for Projection handling](http://www.gdal.org/classOGRSpatialReference.html). I started writing a library that would use a pyproj compatible library, but allow for exporting WKT and other various representations of a projection.  I used cffi instead of Cython, and it ended up being a few orders of magnitude slower than pyproj.

cffi definitely has some quirkiness similar to Cython.  I could revive the project if there is interest, but I don't remember how well it all worked.

**Comment by micahcochran** [comment]
I'm fine with this not happening.

**Comment by Juanlu001** [comment]
> I could revive the project if there is interest, but I don't remember how well it all worked.

Yes there is :)

**Comment by micahcochran** [comment]
GDAL uses PROJ.4 under the hood.  GDAL just adds more functionality with being able to interpret WKT and other projection definitions.

> I used cffi instead of Cython, and it ended up being a few orders of magnitude slower than pyproj.

That was a big issue of why I stopped working on it.   I was trying to make a transformation library that was mostly API compatible with pyproj's transformation capabilities, but also have a new nicer extended API.  (cffi could be slightly faster now, but I don't think it has made up that difference.)

With geopandas project's more recent focus on performance, I'm not so sure that coordinate transformation that is an order of magnitude (or more) slower would be welcome, unless it were optional.  ("Install pyproj for maximum performance.")

This new API was not even touching the Geod portion of the library for measuring distances, which GeographicLib could be used.  That doesn't matter for geopandas itself.

**Comment by micahcochran** [comment]
So I poked around Fiona and found that it already has [coordinate transformation functions](https://github.com/Toblerity/Fiona/blob/master/fiona/transform.py).  This look like it could be really easy to switch to.

I'd want to benchmark the change to see if using pyproj is faster.

**Comment by jorisvandenbossche** [comment]
Closing in favor of https://github.com/geopandas/geopandas/issues/1003 (discussion about switching to pyproj's CRS interface). 

I think the general idea now is to rely on pyproj on this, certainly now CRS conversion related functionalities are moving to PROJ in the general ecosystem.
