### ISSUE TITLE
TST: Make Pytest 8 xfail less verbose?

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#3169]
Just noticing that it's now (at least to me) a bit harder to actually find the test fails in CI - which is now using pytest 8. Failures no longer are no longer near the bottom, but rather towards the bottom, but after all the xfail assertion error messages. Wondering if we should change this so less is reported by default?

Perhaps that's just me though.

**Comment by jorisvandenbossche** [comment]
It seems we also have a bunch of actual failures that might also be related to pytest 8? (I don't see much other potentially related packages that updated versions the last week)

**Comment by martinfleis** [comment]
@m-richards can you point me to the report where this happens? From those few I clicked on, the failures and errors were on the very bottom as usual.

@jorisvandenbossche that was dev version of xyzservices broken by botched upstream PR in leaflet-provides. All green now.

**Comment by m-richards** [comment]
See https://github.com/geopandas/geopandas/actions/runs/7770406362/job/21190571888 for example - the errors are at the very bottom, but to see the error traceback you now have to scroll up through ~900 lines of xfailure tracebacks.

**Comment by jorisvandenbossche** [comment]
I don't fully understand how pytest intends this to be configured ..

An example test file where we have one xfailing test:

```
$ pytest geopandas/tests/test_op_output_types.py  -r fEx
================================== test session starts ================================================
platform linux -- Python 3.11.0, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/joris/scipy/repos/geopandas
configfile: pyproject.toml
plugins: anyio-4.0.0
collected 33 items                                                                                                                                                                                                

geopandas/tests/test_op_output_types.py .....x...........................     
================================ 32 passed, 1 xfailed in 0.79s ========================================

```

With the default settings of only showing the "extra test summary" for failures and Errors (`-r fE`), the above doesn't actually list which tests are xfailing (it just says there was 1 xfailed test)

When enabling the test summary for xfailures as well:

```
$ pytest geopandas/tests/test_op_output_types.py  -r fEx
===================================== test session starts ======================================
platform linux -- Python 3.11.0, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/joris/scipy/repos/geopandas
configfile: pyproject.toml
plugins: anyio-4.0.0
collected 33 items                                                                             

geopandas/tests/test_op_output_types.py .....x...........................                [100%]

========================================== XFAILURES ===========================================
____________________________________ test_loc_add_row[geom] ____________________________________

geom_name = 'geom'
nybb_filename = 'zip:///home/joris/scipy/repos/geopandas/geopandas/tests/data/nybb_16a.zip'

    @pytest.mark.parametrize(
        "geom_name",
        [
            "geometry",
            pytest.param(
                "geom",
                marks=pytest.mark.xfail(
                    reason="pre-regression behaviour only works for geometry col geometry"
                ),
            ),
        ],
    )
    def test_loc_add_row(geom_name, nybb_filename):
        # https://github.com/geopandas/geopandas/issues/3119
    
        nybb = geopandas.read_file(nybb_filename)[["BoroCode", "geometry"]]
        if geom_name != "geometry":
            nybb = nybb.rename_geometry(geom_name)
        # crs_orig = nybb.crs
    
        # add a new row
        nybb.loc[5] = [6, nybb.geometry.iloc[0]]
>       assert nybb.geometry.dtype == "geometry"
E       AssertionError: assert dtype('O') == 'geometry'
E        +  where dtype('O') = 0    MULTIPOLYGON (((970217.0223999023 145643.33221...\n1    MULTIPOLYGON (((1029606.0765991211 156073.8142...\n2    MUL...N (((1012821.8057861328 229228.2645...\n5    MULTIPOLYGON (((970217.0223999023 145643.33221...\nName: geom, dtype: object.dtype
E        +    where 0    MULTIPOLYGON (((970217.0223999023 145643.33221...\n1    MULTIPOLYGON (((1029606.0765991211 156073.8142...\n2    MUL...N (((1012821.8057861328 229228.2645...\n5    MULTIPOLYGON (((970217.0223999023 145643.33221...\nName: geom, dtype: object =    BoroCode                                               geom\n0         5  MULTIPOLYGON (((970217.0223999023 145643.3...    2  MULTIPOLYGON (((1012821.8057861328 229228.2645...\n5         6  MULTIPOLYGON (((970217.0223999023 145643.33221....geometry

geopandas/tests/test_op_output_types.py:170: AssertionError
=================================== short test summary info ====================================
XFAIL geopandas/tests/test_op_output_types.py::test_loc_add_row[geom] - pre-regression behaviour only works for geometry col geometry
================================ 32 passed, 1 xfailed in 0.86s =================================
```

The xfailed test is shown _both_ in the verbose printing of xfailures (like a test failure, pointing to the assert line that is failing), and in the test summary. 

I would personally like to keep the list of xfails in the short test summary (it gives them some visibility), but definitely don't want their verbose output. This is indeed way too verbose for something we know is happening, making it hard to check the verbose output of the actual tests.

Now, I don't see how I can get pytest to just show the short test summary for xfails. So then let's just disable xfails altogether for now, as it's more important to get rid of the verbosity.
