### ISSUE TITLE
Better plotting defaults

### ISSUE THREAD

**Issue by darribas** [geopandas/geopandas#318]
I propose to enhance the default appearance of simple plots. Currently, it is very dependent on the `matplotlib` defaults and hence not particularly well suited for the display of geographic data. An example:

``` python
# Load up dependencies and data
import matplotlib.pyplot as plt
import pysal as ps
import geopandas as gpd
shp = gpd.read_file(ps.examples.get_path('columbus.shp'))
```

The current first plot a user might encounter looks like this:

``` python
shp.plot()
```

![index](https://cloud.githubusercontent.com/assets/417363/15316523/4d9e528a-1c15-11e6-94f9-cc5e09c7c8d7.png)

I'm not sure about the details, but I propose the `plot()` method wraps some better defaults that make it more aesthetically pleasant (and also more cartographically useful). For example, the equivalent of:

``` python
f, ax = plt.subplots(1)
shp.plot(ax=ax, linewidth=0.5, edgecolor='0.5')
ax.set_axis_off()
plt.axis('equal')
plt.show()
```

![index](https://cloud.githubusercontent.com/assets/417363/15316555/7c091524-1c15-11e6-8d35-8d991b1597ce.png)

I think the appearance of default plots is behind much of the success of libraries such as `seaborn` or `ggplot2`. Being such a low-hanging fruit (at least relatively speaking), I think the 0.2 release should include a revamp of these defaults. I'm happy to issue at least an initial PR on this if there is interest. What do you think @kjordahl @jorisvandenbossche @nickeubank ?

**Comment by darribas** [comment]
Maybe we could even get some advice on this from @mwaskom from `seaborn`?

**Comment by mwaskom** [comment]
FWIW matplotlib will have better defaults in 2.0

**Comment by jorisvandenbossche** [comment]
@darribas Fully agree!

There are two things:

1. What do we want as defaults? And I think the ones you show, `linewidth=0.5, edgecolor='0.5'` (+ removing the axes) is already a good start.
  - As @mwaskom pointed out, matplotlib will have better defaults in 2.0, but I don't think they will be better for geopandas on all elements. For example, the default line width will be thicker, while we rather want the opposite I think (although depending on line vs polygon)
  - The colors is also something we should address. I personally find the example you show way too colorful (but mpl 2.0 might be an improvement here). Other possibility is to show uniform color when no `column` (based on which the colors can be determined) is specified

2. How do we apply those defaults? 

  - Do we just hardcode it as the defaults in the methods? Or de we use some style mechanism? 
  - In any case, I think we want that we only change the style for `plot` calls from `GeoDataFrame/GeoSeries` objects, and not change the style of other matplotlib figures (as the styling is rather specific to gis plots). And in this case, hard coding in the plot signature is probably the easiest solution (it is also what we do now).

@darribas Do you want to do some further proposal of defaults?

**Comment by kjordahl** [comment]
@darribas Absolutely! This would be great.

Let's tag it 0.3 so it doesn't hold us up on getting a 0.2 release out.

**Comment by darribas** [comment]
Cool, I'll try to get a PR going soon! I think we can get those mentioned above going and if other obvious ones are raised on this thread they can either be added here or later on. This wouldn't change the API anyway, so I think it's OK to move ahead with some and complement with others down the line.

**Comment by IamJeffG** [comment]
Regarding the defaults to be chosen: I'd suggest that we apply the same alpha value to both the edges and fill of shapes.

The current behavior of using differing alpha transparencies for these is a big pain: both currently and if we were to switch to mpl.Collections (ala #259).  Specifically it doesn't work well with heterogeneous geometry types (#266) and it means a big performance hit by plotting all polygons twice (once with alpha, once without).

**Comment by darribas** [comment]
Now #267 is merged, it'd make sense to relive this. I'd vote for the following defaults, which we use in PySAL, but please feel free to add/edit/chip in, I'm totally open to settle on something else:

* `linewidth=0.2` (for lines and polygon edges)
* `alpha=1.`
* `marker_size=20` (for points)
*  `figsize=(9,9)`
* `facecolor='#4D4D4D'`
* `edgecolor='#B3B3B3'`
* Axes removed (`ax.set_axis_off()`)
* Axes equal (`plt.axis('equal')`)

This creates a plot that looks like:

<img width="928" alt="screen shot 2016-12-29 at 17 52 14" src="https://cloud.githubusercontent.com/assets/417363/21550158/922d298a-cdef-11e6-83e3-6e9562e205e6.png">

In terms of how to actually implement these, I'd vote for @jorisvandenbossche's suggestion to hardcode them as it's currently done in `geopandas`. My idea would be to specifiy them at the top of the plotting module in all capitals (`LINEWIDTH`, `ALPHA`, etc.) and then use those var names throughout the plotting classes. But again, this is just a start thought.

What does the rest think?

**Comment by IamJeffG** [comment]
Implementation: I agree hardcoding at top is best. I view improving the default appearance (this issue) as separate from, say, adding a mechanism for programmatic styling.

Defaults: The only thing that seems off is forcing a figsize.  Currently we fallback to rc.figure.figsize, is there a reason that's not ideal anymore?  +1 to everything else!

**Comment by ResidentMario** [comment]
So, the `matplotlib 2.0.0` defaults are a huge improvement. Maybe updating mostly handles this?

xref #405

**Comment by darribas** [comment]
Does anyone have a sense for what a `geopandas` plot would look like with the new defaults? My sense is some things would probably be improved, but others might be specific to the display of spatial data (e.g. do we need axis when plotting a map?). It'd be great to have sense of what the new defaults "buy" us.

**Comment by QuLogic** [comment]
Here is your first figure with Matplotlib 2.0 (basically viridis instead of jet):
![figure_1-1](https://user-images.githubusercontent.com/302469/27992497-0acf6df2-6464-11e7-91b7-b92ea32202cc.png)

**Comment by darribas** [comment]
I'd say it'd be nice to have thinner/lighter border lines and remove the axis.

**Comment by ResidentMario** [comment]
Yes, I think your defaults from last year are definitely better. Maybe bump the `linewidth` up to 1? The third chart [here](http://www.residentmar.io/geoplot/examples/aggplot-collisions-1.html) would be an example of that.

**Comment by jdmcbr** [comment]
@darribas Are you still interested in making a PR? I'd personally lean toward something more of the appearance you suggested in your original post, rather than the matte appearance you suggested on December 29.

**Comment by jorisvandenbossche** [comment]
Another related issue is the default `alpha`. This issue argues for a default of 1: https://github.com/geopandas/geopandas/issues/266

**Comment by emiliom** [comment]
This is partly a question and partly a suggestion. For reference: matplotlib 2.0.0 and geopandas 0.2.1.

When plotting two polygon GeoDataframes together (one on top of the other), the polygon edges don't behave the same way as the faces/fills. My expectation is that the geometries/GeoDataframe "on top" (plotted last) should completely cover the first GeoDataframe. That does happen with the polygon faces, but not with the edges. The edges from the first GeoDataframe show through completely.

You can see this in action in [this notebook](https://github.com/emiliom/geopandas-tutorial-maptime/blob/master/notebooks/geopandas_intro.ipynb), in the plots in cells 25 & 26. Here's the code that generates the plot in cell 26, preceded by two plot defaults I set up at the start:
```python
import seaborn as sns
plt.style.use('bmh')

f, ax = plt.subplots(1, figsize=(10, 5))
oceans.plot(cmap='Paired', alpha=1, linewidth=0.2, ax=ax)
world.plot(alpha=1, ax=ax)
ax.set_ylim([-100, 100])
ax.set_title('Countries and Ocean Basins')
plt.axis('equal');
```

And the image that's generated, from a slightly older version of the notebook:
![map](https://geohackweek.github.io/vector/fig/04/geopandas_intro_62_0.png)
The lines in the middle of continents are the polygon edges from the first GeoDataframe, which I expected would be hidden (covered) by the polygon faces of the second GeoDataframe.

Reading through this issue (specially the [Jul 11, 2016 comments](#issuecomment-231821511) from @IamJeffG) and #266, it sounds like this behavior may be related to the use of different alpha values for faces and edges, and "plotting all polygons twice".

FYI, I discovered this issue last November while preparing a [tutorial on vector geospatial tools that features GeoPandas heavily](https://geohackweek.github.io/vector/04-geopandas-intro/). We're running the  ["GeoHackweek" event](https://geohackweek.github.io) again this year, in a month, and I'm revisiting the issues I ran into back then.

**Comment by emiliom** [comment]
I should add that "plotting all polygons twice" seems to explain (to me) why plot generation seems to be kind of slow.

**Comment by jorisvandenbossche** [comment]
@emiliom The plotting code has changed a lot since v0.2.1, so could you try that example with master, and check if you still have that problem? (or even better, with the branch of https://github.com/geopandas/geopandas/pull/502)

> plot generation seems to be kind of slow.

The changes to the plotting code also led to a big performance improvement. For points even ca 20x speedup, for lines/polygons around 3x / 4x speedup. So also for this, master should be faster.

**Comment by emiliom** [comment]
@jorisvandenbossche I've run my notebook (slightly updated version of [this](https://github.com/emiliom/geopandas-tutorial-maptime/blob/master/notebooks/geopandas_intro.ipynb)) on master. The bug/problem with polygon edge bleeding across two geodataframes is fixed! And man, plotting is much, much faster than v0.2.1. I see that a number of plotting defaults have changed, though not all the ones @darribas laid out on Dec 29.

This was all running on Python 2.7. I'll try 3.6 later in the week. But I doubt I'll be able to get to testing with the branch in #502 this week, sorry.

Very cool, thanks!!

**Comment by jorisvandenbossche** [comment]
Actually, maybe I have an even better ànd simpler proposal for now: remove all hardcoded defaults and fall back completely to new matplotlib defaults. 

This gives us for the above figure:

![index1](https://user-images.githubusercontent.com/1020496/29585232-b25e2af0-8786-11e7-9e5d-32e773dee237.png)

(reaons: matplotlib by default shows no edges anymore I think, so it 'looks' like you have a white edge. Only not sure that will work for all data)

and with a numerical column for coloring (and without turning off the axis):

![index2](https://user-images.githubusercontent.com/1020496/29585293-e7ca59a2-8786-11e7-8363-781e19eb6e31.png)

or with categorical column:

![index3](https://user-images.githubusercontent.com/1020496/29585315-fe09865c-8786-11e7-9523-1ab2695a92dd.png)

Full notebook exploring this: http://nbviewer.ipython.org/21d9eb8efdb8bfa3a418292285337b0a

The only question is maybe if we find the default markersize and default linewidth for plotting points and linestrings too big. Although that will depend a lot on what kind of data you are plotting, eg with the following plot I think is rather OK for default (although you would tweak it for an actual plot):


```
ax = plot_series(europe.boundary)
plot_series(europe_cities, color='C1', ax=ax, zorder=10)
ax.set_axis_off()
```

![index4](https://user-images.githubusercontent.com/1020496/29585771-a3dc8be6-8788-11e7-8086-cfdc111b8408.png)

**Comment by ResidentMario** [comment]
Looks great! This maximizes compatibility, which is a huge plus.

**Comment by jorisvandenbossche** [comment]
Are there strong opinions about keeping vs removing the axes by default? 

I started a PR to update the default look (https://github.com/geopandas/geopandas/pull/510), but for not did not yet deal with the axes.

**Comment by IamJeffG** [comment]
I prefer to keep axes by default.  Very often when I see a plot of geospatial data I will want to investigate more by pulling even more layers, and having the coordinates helps with this.

(At high zoom levels or very high coordinate values, e.g. [UTM](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system), matplotlib starts abbreviating the axis labels, which has its own pros and cons, but that is an issue for another day and anyway I don't have a better solution yet)

**Comment by darribas** [comment]
Hello, sorry for the absence, it's been a very busy summer. Unfortunately, I can't commit to much time on this right now, but happy to provide feedback. I like the proposed defaults a lot, particularly the last round by @jorisvandenbossche so +1 on those. My only concern with those would be whether there's the chance of an edge case where the fill color is white and the geometries plotted are not visible. Is that possible? If not, I'd definitely go with them.

In terms of the axes, my personal preference would be to have the default as off, it looks cleaner to me and 90% of the time I produce a map, I don't need the axis. But I can see the use of them. I'd definitely make clear that all you need is `ax.set_axis_on()` and `plot` could also have an option `axis` which defaults to `False`? It's adding more but sounds like an easy one.

**Comment by jorisvandenbossche** [comment]
@darribas Thanks for the feedback!

> My only concern with those would be whether there's the chance of an edge case where the fill color is white and the geometries plotted are not visible. Is that possible? If not, I'd definitely go with them.

I think that is a valid concern. However, for uniform coloring you can only get that if you specify white yourself, and then you should specify a different edgecolor yourself. But when using values with a cmap, if the cmap contains a white part, then we might have a problem. Will do a few tests.

> I'd definitely make clear that all you need is ax.set_axis_on() and plot could also have an option axis which defaults to False? It's adding more but sounds like an easy one.

Yes, I was planning to certainly clearly document it how to do if we don't add it by default (and the same if we would add it, how you can turn it off). 
Maybe adding a keyword is a good idea.

> Unfortunately, too close to the start of my course to get it on GDS this year as the university system won't let me update it. But it'll definitely go on the next iteration!

That's a pity .. Because it are really some nice improvements (the speed difference is very noticeable) 
Yesterday I ran the lab_2 on visualisation with the branch of #502 with the new defaults, and most things seemed to go fine (apart from that you will have to adjust the text a bit of course, and those aspects that you have to update on the style, as it doesn't match the new defaults anymore)

One thing I noticed, is that you used `plot_polygon` somewhere (you iterated over the individual geometries and plotted each of them using that). Do you think those are still useful? Because they are now gone, but it would be easy to add them back.

**Comment by jorisvandenbossche** [comment]
> > My only concern with those would be whether there's the chance of an edge case where the fill color is white and the geometries plotted are not visible. Is that possible? If not, I'd definitely go with them.

> I think that is a valid concern. However, for uniform coloring you can only get that if you specify white yourself, and then you should specify a different edgecolor yourself. But when using values with a cmap, if the cmap contains a white part, then we might have a problem. Will do a few tests.

So with the default colormap ('viridis'), this will never be a problem (the light spectrum only goes up to yellow):

```
df.plot('values')
```

![index](https://user-images.githubusercontent.com/1020496/29709211-d62ac496-898b-11e7-8400-9ffe80ff9427.png)

But with a colormap that goes up to white, it can be a problem:

```
df.plot('values', cmap='Reds')
```

![index1](https://user-images.githubusercontent.com/1020496/29709213-d7c98cb0-898b-11e7-8c0a-dc3575ba3de8.png)

although that needs a user action, so we *could* the user is then responsible for it.

**Comment by jorisvandenbossche** [comment]
So my PR with an update for the defaults is merged, defaulting to matplotlib defaults. 
But if you have further feedback (like the problem with the 'no edge + white color' from above), just post here! We can always to further tweaks.
