### ISSUE TITLE
ENH: parity between GeoDataFrame.to_json and GeoSeries.to_json

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3199]
> Hey, guys @jdmcbr @martinfleis , just bringing to your attention that while you fixed this issue for GeoDataFrame, id field is still obligatory for GeoSeries, there is no option to remove it. You might want to add it for GeoSeries as well.
>
> My version of geopandas is 0.14.2.

_Originally posted by @kiranzo in https://github.com/geopandas/geopandas/issues/1637#issuecomment-1958551545_
            

Some attributes shall be included in `GeoSeries.to_json` as well.

**Comment by nicholas-ys-tan** [comment]
Hi Martin,

I've submitted a PR that I believe address the issue. Thought this might be a good ticket to get my feet wet in OSS. Let me know if I've violated any conventions or you are not happy with the approach taken.
