### ISSUE TITLE
BUG: `join` does not preserve geometry attribute

### ISSUE THREAD

**Issue by nickeubank** [geopandas/geopandas#320]
See line 487 of `geopandas.py` for example.

**Comment by jorisvandenbossche** [comment]
This is actually maybe a duplicate of https://github.com/geopandas/geopandas/issues/247

**Comment by jorisvandenbossche** [comment]
The example of `merge` you added in https://github.com/geopandas/geopandas/pull/301 will also not fully work (what you show will work, but further manipulations using `geometry` won't work)

**Comment by jorisvandenbossche** [comment]
Duplicate of #247
