### ISSUE TITLE
BUG: Unable to append to a layer when using fiona backend

### ISSUE THREAD

**Issue by digital-idiot** [geopandas/geopandas#3217]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from owslib.wfs import WebFeatureService

wfs = WebFeatureService("https://data.3dbag.nl/api/BAG3D/wfs", version='2.0.0')

response1 = wfs.getfeature(
    typename="BAG3D:lod12",
    bbox=(204000.00016165, 486000.00045928, 207000.0001644 , 489000.00046109),
    method="Post",
    outputFormat="GML2",
    startindex=0,
    maxfeatures=500
)

response2 = wfs.getfeature(
    typename="BAG3D:lod12",
    bbox=(204000.00016165, 486000.00045928, 207000.0001644 , 489000.00046109),
    method="Post",
    outputFormat="GML2",
    startindex=500,
    maxfeatures=500
)

gdf1 = gpd.read_file(response1)
gdf2 = gpd.read_file(response2)

print(all(gdf1.columns == gdf2.columns))  # True: Attributes are identical
print(all(gdf1.dtypes == gdf2.dtypes))  # True: Data types are identical

## Just to be safe. Errors out either way
gdf1.set_index(['fid'])
gdf2.set_index(['fid'])

gdf1.to_file("/tmp/foo.gpkg", driver="GPKG", layer="Building", mode='w', engine="fiona")
gdf2.to_file("/tmp/foo.gpkg", driver="GPKG", layer="Building", mode='a', engine="fiona")  # Record does not match collection schema

```

#### Problem description

When trying to append features (see the minimum workable snippet above) to a layer of an existing `GPKG` , I encounter despite the attribute names and their respectiver DTypes of both the table are identical.

```python
ValueError: Record does not match collection schema
```
* Relevant Issue: #3135 

Workaround 2 & 3 mentioned [here](https://github.com/geopandas/geopandas/issues/3135#issuecomment-1880990453) does not work.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801]
executable : /home/abhisek/OTP_Project/venv/bin/python
machine    : Linux-6.7.7-1-MANJARO-x86_64-with-glibc2.39

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.3
GEOS lib   : None
GDAL       : 3.6.4
GDAL data dir: [masked]/venv/lib/python3.11/site-packages/fiona/gdal_data
PROJ       : 9.3.0
PROJ data dir: [masked]/venv/lib/python3.11/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.3
numpy      : 1.26.4
pandas     : 2.2.1
pyproj     : 3.6.1
shapely    : 2.0.3
fiona      : 1.9.5
geoalchemy2: None
geopy      : None
matplotlib : 3.8.3
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : None
</details>

**Comment by theroggy** [comment]
The error is a bit cryptic, but the problem is that in one of the rows in the second gdf, the "fid" value is the same as one of the rows in the first gdf. Because in GPKG the "fid" is used as primary key, there is an error if a duplicate "fid" is inserted.

If you e.g. rename the "fid" column to "fid_orig", the error disappears.

``` py
import geopandas as gpd
from owslib.wfs import WebFeatureService

wfs = WebFeatureService("https://data.3dbag.nl/api/BAG3D/wfs", version="2.0.0")

response1 = wfs.getfeature(
    typename="BAG3D:lod12",
    bbox=(204000.00016165, 486000.00045928, 207000.0001644, 489000.00046109),
    method="Post",
    outputFormat="GML2",
    startindex=0,
    maxfeatures=500,
)

response2 = wfs.getfeature(
    typename="BAG3D:lod12",
    bbox=(204000.00016165, 486000.00045928, 207000.0001644, 489000.00046109),
    method="Post",
    outputFormat="GML2",
    startindex=500,
    maxfeatures=500,
)

gdf1 = gpd.read_file(response1)
gdf2 = gpd.read_file(response2)

print(all(gdf1.columns == gdf2.columns))  # True: Attributes are identical
print(all(gdf1.dtypes == gdf2.dtypes))  # True: Data types are identical

# In the second gdf, there is a row with an fid that already occurs in the first gdf.
# As the fid column is reused as a primary key in GPKG, error.
gdf1 = gdf1.rename(columns={"fid": "fid_orig"})
gdf2 = gdf2.rename(columns={"fid": "fid_orig"})

gdf1.to_file("/tmp/foo.gpkg", driver="GPKG", layer="Building", mode="w", engine="fiona")
gdf2.to_file(
    "/tmp/foo.gpkg", driver="GPKG", layer="Building", mode="a", engine="fiona"
)  # Record does not match collection schema
```

**Comment by digital-idiot** [comment]
> The error is a bit cryptic, but the problem is that in one of the rows in the second gdf, the "fid" value is the same as one of the rows in the first gdf. Because in GPKG the "fid" is used as primary key, there is an error if a duplicate "fid" is inserted.
> 
> If you e.g. rename the "fid" column to "fid_orig", the error disappears.
> 
> ```python
> import geopandas as gpd
> from owslib.wfs import WebFeatureService
> 
> wfs = WebFeatureService("https://data.3dbag.nl/api/BAG3D/wfs", version="2.0.0")
> 
> response1 = wfs.getfeature(
>     typename="BAG3D:lod12",
>     bbox=(204000.00016165, 486000.00045928, 207000.0001644, 489000.00046109),
>     method="Post",
>     outputFormat="GML2",
>     startindex=0,
>     maxfeatures=500,
> )
> 
> response2 = wfs.getfeature(
>     typename="BAG3D:lod12",
>     bbox=(204000.00016165, 486000.00045928, 207000.0001644, 489000.00046109),
>     method="Post",
>     outputFormat="GML2",
>     startindex=500,
>     maxfeatures=500,
> )
> 
> gdf1 = gpd.read_file(response1)
> gdf2 = gpd.read_file(response2)
> 
> print(all(gdf1.columns == gdf2.columns))  # True: Attributes are identical
> print(all(gdf1.dtypes == gdf2.dtypes))  # True: Data types are identical
> 
> # In the second gdf, there is a row with an fid that already occurs in the first gdf.
> # As the fid column is reused as a primary key in GPKG, error.
> gdf1 = gdf1.rename(columns={"fid": "fid_orig"})
> gdf2 = gdf2.rename(columns={"fid": "fid_orig"})
> 
> gdf1.to_file("/tmp/foo.gpkg", driver="GPKG", layer="Building", mode="w", engine="fiona")
> gdf2.to_file(
>     "/tmp/foo.gpkg", driver="GPKG", layer="Building", mode="a", engine="fiona"
> )  # Record does not match collection schema
> ```

Thanks, that is indeed the actual problem. I knew `fid` is treated as primary key of the `sqlite` database, that is the reason I set it as index. But given the error message it did not occur to me that duplicate primary key is the problem.

**Comment by theroggy** [comment]
For completeness sake, regarding the `gdf.set_index(['fid'])`, two things to note:
- probably just an oversight, but `gdf.set_index` returns a new dataframe with the index set, so either use `gdf.set_index(['fid'], inplace=True)` or `gdf = gdf.set_index(['fid'])`
- when you actually set the index to the "fid" column, if the index name is "fid", it will still be used for the "fid" column/primary key. So in addition you need to set the index name to e.g. None, with gdf.index.name = None.
