### ISSUE TITLE
ENH: Add a Voronoi Diagram algorithm

### ISSUE THREAD

**Issue by BastienGauthier** [geopandas/geopandas#3227]
#### Is your feature request related to a problem?

This issue is not blocking, but simple suggestion : I wish I could use geopandas to do [Voronoï Diagram](https://en.wikipedia.org/wiki/Voronoi_diagram) from a point series, as for de delaunay_triangles fonction for exemple.

#### Describe the solution you'd like

GeoDataFrame.voronoi_diagram(*args, **kwargs) would be perfect

#### API breaking implications

No API breaking implication foreseen

#### Describe alternatives you've considered

I followed [this exemple](https://wellsr.com/python/python-voronoi-diagram-with-geopandas-and-geoplot/), with geoplot.voronoi fonction, but I feel this could be useful to have this function included in geopandas.

**Comment by martinfleis** [comment]
@BastienGauthier coming in GeoPandas 1.0 - https://github.com/geopandas/geopandas/pull/3177.
