### ISSUE TITLE
ENH: support reading and writing the geoarrow-based encodings of GeoParquet

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#3253]
Closely related to https://github.com/geopandas/geopandas/pull/3219, but focused on GeoParquet.

GeoParquet 1.1 added a bunch of encodings: https://github.com/opengeospatial/geoparquet/blob/main/format-specs/geoparquet.md#native-encodings-based-on-geoarrow

We should ensure we can both read and write files with such encoding for the geometry column(s).

For writing, we can have an `encoding` keyword which still defaults to `"WKB"`, but where can specify one of the new encodings as well (`"point"`, `"linestring"` etc). 
We could maybe also accept an additional value of `"geoarrow"` that will then infer the actual geometry-specific encoding from the data?

**Comment by m-richards** [comment]
Closed collectively by #3278 and #3275 which handle read and write respectively
