### ISSUE TITLE
ENH: inplace=True for .dissolve and .explode?

### ISSUE THREAD

**Issue by iboates** [geopandas/geopandas#3259]
#### Is your feature request related to a problem?

I would like to be able to specify `inplace=True` for `GeoDataFrame.dissolve` and `GeoDataFrame.explode` (as well for any other similar methods that lack that functionality)

#### Describe the solution you'd like

Just add and `inplace` parameter and make the gdf update itself similar to how it works for other methods in geopandas and pands

#### API breaking implications

I don't know

#### Describe alternatives you've considered

The typical way of doing a reflexive assignment

#### Additional context

Is there a reason why this isn't already the case? Like is it fundamentally incompatible with the rest of the library somehow? I'm willing to try this out myself unless you can tell me why I shouldn't bother trying.

**Comment by martinfleis** [comment]
Sorry to disappoint but we will probably go the other direction. There's an ongoing discussion on pandas to deprecate inplace keyword and we will follow.

**Comment by iboates** [comment]
Well, you can't fight the tide. Thanks for the heads up.

**Comment by iboates** [comment]
I feel like this is going to an absolute cataclysm when the deprecation finally goes live though

**Comment by martinfleis** [comment]
See the relevant discussion here https://github.com/pandas-dev/pandas/pull/51466 if you are interested in details.
