### ISSUE TITLE
BUG: Unable to open files with fiona where filepath contains a # character

### ISSUE THREAD

**Issue by scazz010** [geopandas/geopandas#3279]
#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
path = 'file:///dropbox/#02 Datastore/sample.shp'
gpd.io.util._parse_uri(path)
```

returns 

`('/dropbox/', '', 'file')`

#### Problem description

Any filepath being opened with fiona via gpd.read_file is parsed through vsi_path() in order to: 
```python
# Opening a file via URL or file-like-object above automatically detects a
# zipped file. In order to match that behavior, attempt to add a zip scheme
# if missing.
```

Which then passes through parseurl which splits on #s and drops part of my file path
#### Expected Output
`(/dropbox/#02 Datastore/sample.shp','', 'file')`

#### Suggested solution idea?

https://github.com/geopandas/geopandas/blob/5186e69d9b81b2bd73fce1d85f3852971d227f8e/geopandas/io/util.py#L27

Could also collect fragments from urlparse and join it to the URI

**Comment by m-richards** [comment]
Thanks for the report @scazz010, I can replicate this. Also seems to be an issue writing such files. Hopefully pretty straightforward to resolve.

**Comment by JamesParrott** [comment]
I think this is a feature, not a bug.  

Octothorps (`#`s) are reserved characters in URIs, denoting fragments at the end.

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Example_URIs

**Comment by m-richards** [comment]
> I think this is a feature, not a bug.
> 
> Octothorps (`#`s) are reserved characters in URIs, denoting fragments at the end.
> 
> https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Example_URIs

The issue describe here is to do with reading local file paths containing hashes - these are incorrectly inferred as uri fragments (as geopandas also supports reading from urls/s3/etc directly. 

If you have a real world example of where this fix may go wrong with URIs, feel free to share.
