### ISSUE TITLE
BUG: concat not working with GeoSeries

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#329]
Or at least, it does not result in a new GeoSeries.

```
In [4]: from geopandas import GeoSeries

In [5]: from shapely.geometry import Point

In [6]: gseries = GeoSeries([Point(i, i) for i in range(3)])

In [7]: pd.concat([gseries, gseries], ignore_index=True)
Out[7]:
0    POINT (0 0)
1    POINT (1 1)
2    POINT (2 2)
3    POINT (0 0)
4    POINT (1 1)
5    POINT (2 2)
dtype: object

In [8]: type(pd.concat([gseries, gseries]))
Out[8]: pandas.core.series.Series
```

But, I think that geopandas cannot solve this, as this is due to the pandas implementation of `concat` (where the return type of a Series is hardcoded: https://github.com/pydata/pandas/blob/db4382412d0e3ad97b7e0e986656a6e52a498c8d/pandas/types/concat.py#L67).

**Comment by debboutr** [comment]
if only a series, wouldn't this solve the problem...
`  gpd.GeoSeries(pd.concat([gseries,gseries], ignore_index=True))
Out[10]: 
0    POINT (0 0)
1    POINT (1 1)
2    POINT (2 2)
3    POINT (0 0)
4    POINT (1 1)
5    POINT (2 2)
dtype: object

type(gpd.GeoSeries(pd.concat([gseries,gseries], ignore_index=True)))
Out[11]: geopandas.geoseries.GeoSeries`

**Comment by martinfleis** [comment]
GeoPandas master correctly returns GeoSeries. Issue has been fixed in the meantime. Closing.
