### ISSUE TITLE
MAINT: Update the conda forge feedstocks for 1.0

### ISSUE THREAD

**Issue by m-richards** [geopandas/geopandas#3293]
I'm not across how conda-forge works, but it looks like we should update our feedstock dependencies before 1.0. A couple of things I noticed (looking here https://github.com/conda-forge/geopandas-feedstock/blame/main/recipe/meta.yaml):

- In #3263 I was experimenting with trying to not install pyproj via conda, when I noticed it's actually required in `geopandas-base`. Post #3203 this should be optional, and I suppose would move out into `geopandas`
- We should make `pyogrio` a dependency for `geopandas` (could remove fiona too, but I think it's probably better to leave it for now)
- We should remove `rtree` from `geopandas` since we now use the rtree implementation from pygeos via shapely 2.0
- we could (should? - I'm not sure to what extent conda-forge infers metadata from pyproject.toml metdata, it seems there's  a bot which submits PRs for releases, but then pins are updated manually?) update pins for packages, particularly shapely to 2.0

I'm happy to open a PR but would like to check if this sounds more or less right first.

**Comment by martinfleis** [comment]
Yes, but we'll need to do that once 1.0 is on PyPI to ensure the changes are not pushed to 0.14.4.

**Comment by jorisvandenbossche** [comment]
If we want to try out those things before the 1.0 release, we could package the RC on conda forge

**Comment by jorisvandenbossche** [comment]
Opened a PR to have the rc1 on conda-forge, so we can already check the recipe updates: https://github.com/conda-forge/geopandas-feedstock/pull/114

**Comment by martinfleis** [comment]
Closed by https://github.com/conda-forge/geopandas-feedstock/pull/114
