### ISSUE TITLE
API: (not?) preserving name of passed data to `GeoDataFrame(..., geometry=data)`

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#3312]
Consider the following example where we are constructing the geometry values from an existing column in the non-geo DataFrame (such as parsing WKT):

```python
>>> df = pd.DataFrame({"col": [0, 1, 2], "wkt": ["POINT (0 0)", "POINT (1 1)", "POINT (2 2)"]})
>>> df 
   col          wkt
0    0  POINT (0 0)
1    1  POINT (1 1)
2    2  POINT (2 2)
>>> geopandas.GeoDataFrame(df[["col"]], geometry=shapely.from_wkt(df["wkt"]))
   col          wkt
0    0  POINT (0 0)
1    1  POINT (1 1)
2    2  POINT (2 2)
```

Since #3237 the result now has an active geometry column called "wkt", while previously this would have given "geometry". The output you get with pandas 0.14 for the above example:

```
   col                 geometry
0    0  POINT (0.00000 0.00000)
1    1  POINT (1.00000 1.00000)
2    2  POINT (2.00000 2.00000)
```

In the idea that we always want to preserve the name if the passed data has one, the above makes sense of course. However, I think this might be a bigger impact that we have been considering in context of the change to `set_geometry`. 

In any case, the current changelog only focus on the behaviour change for `set_geometry`:

> The behaviour of `set_geometry` has been changed when passed a (Geo)Series `ser` with a name.
  The new active geometry column name in this case will be `ser.name`, if not None, rather than
  the previous active geometry column name. This means that if the new and old names are
  different, then both columns will be preserved in the GeoDataFrame. To replicate the previous
  behaviour, you can instead call `gdf.set_geometry(ser.rename(gdf.active_geometry_name))` (#3237).

while the bigger user impact of this change will come from the `GeoDataFrame(...)` constructor that passes the `geometry` parameter down to `set_geometry`. So at a minimum we should update the changelog.

cc @m-richards

**Comment by jorisvandenbossche** [comment]
cc @m-richards

**Comment by martinfleis** [comment]
I understand the concern that it may have impact in downstream code. But I also think that the reason this will have an impact is that users got used to the old behaviour which was wrong. And as shown in our reactions in #2770, we sort of assumed that this should preserve the name. 

If I'm reading this correctly, this is a dilemma about 
- not breaking the code by keeping the behaviour people are used to but which is also considered wrong
- potentially breaking downstream code by enforcing the behaviour that we assumed already works

We could potentially catch this and raise a warning that this will break in future (i.e. 2.0) to avoid a hard breakage here but eventually get where we want to be. It is just one of those warnings impossible to silence if you don't care how is the column called, when both before and after lead to the same behaviour like in the case of that lonboard notebook.

The argument that the name may not represent what is there, i.e. it may say `wkt` even if it is a geometry is a bit responsibility of a user. They need to have a (Geo)Series with a name `wkt` first.

I am not sure about the best way forward here but I don't feel great about keeping the behaviour that we agreed on is wrong (and I still think is wrong).

**Comment by martinfleis** [comment]
We've been discussing this with @brendan-ward today and he came with another proposal. Keep the change as is but try to intercept potential issue coming from the change of the active column name. That is when a user try to access `"geometry"` column that does not exist. In case of getting the column, we can possibly throw better error than simple pandas missing column. In case of setting it (`gdf["geometry"] = gdf.centroid`), we might assume that user wants to override existing  active geometry and warn that it does not happen. 

Not sure if these are the ideal cases as if you intentionally want to do that, there's no reason why you should not and no way of silencing these. But one more idea to the mix.

**Comment by m-richards** [comment]
>I understand the concern that it may have impact in downstream code. But I also think that the reason this will have an impact is that users got used to the old behaviour which was wrong. And as shown in our reactions in https://github.com/geopandas/geopandas/issues/2770, we sort of assumed that this should preserve the name.

When I first commented on #2770 I was less than convinced this was a bug, I let it go then as I didn't really have anything concrete besides a hunch that this might break things (I think if you're writing idomatic geopandas code this is less likely to have an impact, but if you're not as familiar with the library this might be confusing). 

Definitely agree we should update the changelog if we keep this behaviour (goal of #3237 was to solve the set geometry API before 1.0, I didn't give much thought to this case), we're breaking an invariant that `gdf = GeoDataFrame(... geometry=...)` always had a column called "geometry" in it (ideally you're using gdf.geometry and not accessing it via column name, but inevitably not everyone will do that. 

In principle we can do this, it sounds like a variation on the warning we already do in `_persist_old_default_geometry_colname`, but we'd want to be wary of false positive warnings, since that would also be quite confusing.

**Comment by jorisvandenbossche** [comment]
> * not breaking the code by keeping the behaviour people are used to but which is also considered wrong

I think the "considered wrong" is a bit strongly stated. From re-reading the issues, there was clearly the expectation even among some of us that this case would preserve the (Geo)Series' name (that was my first thought as well). And not doing that would definitely give some inconsistency with `set_geometry`. 
But I think it is certainly "explainable" to say that when passing values to the `geometry` keyword in the default `GeoDataFrame` constructor, this _always_ creates a "geometry" column. And that if you want to use a custom column name, you can do that with `set_geometry()` or if the column is already in the data specify that name (`GeoDataFrame(data, geometry="my_geom")`).

> That is when a user try to access `"geometry"` column that does not exist. In case of getting the column, we can possibly throw better error than simple pandas missing column. In case of setting it (`gdf["geometry"] = gdf.centroid`), we might assume that user wants to override existing active geometry and warn that it does not happen.

For direct uses of `df["geometry"]`, making the error message more informative with including a note about that your active geometry column is named differently and you might have wanted to select that column instead sounds as a good and straightforward idea (and something we could maybe even do regardless of this discussion?). 
But I think such code will also regularly happen deeper down in functions, where the error message might be less helpful, or the KeyError being caught to then do something different, etc. So I think it will be hard to cover all cases that will break properly.

And indeed for the setitem case, if you actually intended to do that, it's an annoying warning to get rid off.

---

Personally, I don't feel very strongly about the current (released) behaviour of GeoDataFrame being "wrong". I would maybe rather think of it as "convenient", and while the change to preserve the (Geo)Series' name is a good change in terms of consistency, my feeling is that it introduces typical behaviour that is not really an improvement. And at that point I might favor convenient over consistent .. 

Generally, unless you do something very explicit (like create a new geometry column and then calling `set_geometry`, or calling `rename_geometry`), most users will typically get a geometry column named "geometry" (I think all our constructors and IO methods will by default give you "geometry"). And I think that is a good thing, because it is nice to have the same name most of the time, is easier for newcomers, reduces cognitive load, etc (there is not really a reason to use a different name, unless you have a very specific reason to want that, but that is not very common I think).

And so this change is 1) backwards incompatible (with quite some chance of breaking actual code, I think), and 2) most of the time (my guess) not necessarily a change that the user necessarily wants, I think. At that point, I am not really sure it is worth it to fix the inconsistency.

**Comment by m-richards** [comment]
> Point taken. I am fine with keeping the behaviour as it was. We just need to be explicit about that in the docstring and point to `set_geometry` if you want to preserve the name.

I would also lean towards reverting the behaviour in `__init__` as I think that's the least controvertial option. I can open a PR?

**Comment by martinfleis** [comment]
I think we came to a conclusion in https://github.com/geopandas/geopandas/pull/3337 and this can be closed.
