### ISSUE TITLE
BUG: legend and actual colors in plot are inverted

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [geopandas/geopandas#3323]
- [x] I have checked that this issue has not already been reported.

Similar issue (but no satisfying answer):
- #1277
- probably others but not sure which ones

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

I opened [an issue with matplotlib](https://github.com/matplotlib/matplotlib/issues/28348) which redirected me here.

---

#### Code Sample, a copy-pastable example

```python
import matplotlib.cm as cm
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

data = gpd.read_file('https://raw.githubusercontent.com/JosephBARBIERDARNAL/misc-dataviz/main/country-co2/data.geojson')
# load the colormap
cmap = cm.Greens
background_color = 'white'
text_color = 'black'

# legend values
value_ranges = [0, 2, 4, 6, 8, 10, 12]
labels = ['0-2 t', '2-4 t', '4-6 t', '6-8 t', '8-10 t', '10-12 t', '12+ t']
def create_legend_elements(cmap, value_ranges, labels):
    legend_elements = []
    n = len(value_ranges)
    for i in range(n-1):
        value = (value_ranges[i] + value_ranges[i+1]) / 2 / value_ranges[-1]  # Normalize the value to [0, 1]
        legend_elements.append(Patch(facecolor=cmap(value), label=labels[i]))
    return legend_elements
legend_elements = create_legend_elements(cmap, value_ranges, labels)

# initialize the figure
fig, ax = plt.subplots(figsize=(10, 10), dpi=300)
fig.set_facecolor(background_color)

# create the plot
data.plot(ax=ax, cmap=cmap, edgecolor='black', linewidth=0.5)

# annot norway and sweden
norway = data.loc[data['country'] == 'Norway']['co2Capita'].values[0]
sweden = data.loc[data['country'] == 'Sweden']['co2Capita'].values[0]
fig.text(0.35, 0.67, f'Norway: {norway}', fontsize=8, fontweight='bold', color='black')
fig.text(0.45, 0.62, f'Sweden: {sweden}', fontsize=8, fontweight='bold', color='black')

# custom axis
ax.set_xlim(-11, 41)
ax.set_ylim(32, 73)
ax.set_axis_off()

# add the patches to the plot area as a legend
rectangle_width = 2
rectangle_height = 1.5
legend_x = 35
legend_y_start = 65
legend_y_step = 1.5
for i, element in enumerate(legend_elements):
    ax.add_patch(plt.Rectangle((legend_x, legend_y_start - i * legend_y_step), rectangle_width, rectangle_height,
                               color=element.get_facecolor(), ec='black'))
    ax.text(legend_x + 2.5, legend_y_start - i * legend_y_step + 0.7, element.get_label(), 
            fontsize=12, color=text_color, va='center')
    
# add colorbar
cax = inset_axes(ax, width='5%', height='50%', loc='center left')
sm = plt.cm.ScalarMappable(cmap=cmap, norm=plt.Normalize(vmin=0, vmax=12))
sm._A = []
cbar = plt.colorbar(sm, cax=cax)
                 
plt.show()
```

<img width="752" alt="Screenshot 2024-06-05 at 15 33 38" src="https://github.com/matplotlib/matplotlib/assets/79746670/4d7352a5-45cf-4f84-983c-869c550357f8">

#### Problem description

I'm not sure if it's a bug or just me not using the functions well enough, but I think that when I add a colour bar or create a legend, the colors are "inverted" (see the plots below) and therefore unreliable.

When I add a legend manually or create a color bar, the legend values are not consistent with the map values. This is illustrated by the values for Sweden (**dark colour but low value**) and Norway (**light colour but high value**). The colours in the legend illustrate the opposite behaviour (**dark color = high value**).

#### Expected Output

The graph should looks like:

<img width="750" alt="Screenshot 2024-06-05 at 15 34 59" src="https://github.com/matplotlib/matplotlib/assets/79746670/8760f295-8591-41fc-9e59-b0cc470eb755">

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.1.0.2.5)]
executable : [/Users/josephbarbier/Desktop/misc-viz/venv/bin/python](https://file+.vscode-resource.vscode-cdn.net/Users/josephbarbier/Desktop/misc-viz/venv/bin/python)
machine    : macOS-14.5-arm64-arm-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.3
GEOS lib   : None
GDAL       : 3.6.4
GDAL data dir: [/Users/josephbarbier/Desktop/misc-viz/venv/lib/python3.10/site-packages/fiona/gdal_data](https://file+.vscode-resource.vscode-cdn.net/Users/josephbarbier/Desktop/misc-viz/venv/lib/python3.10/site-packages/fiona/gdal_data)
PROJ       : 9.3.0
PROJ data dir: [/Users/josephbarbier/Desktop/misc-viz/venv/lib/python3.10/site-packages/pyproj/proj_dir/share/proj](https://file+.vscode-resource.vscode-cdn.net/Users/josephbarbier/Desktop/misc-viz/venv/lib/python3.10/site-packages/pyproj/proj_dir/share/proj)

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.4
numpy      : 1.26.4
pandas     : 2.2.2
pyproj     : 3.6.1
shapely    : 2.0.4
fiona      : 1.9.6
geoalchemy2: None
geopy      : None
matplotlib : 3.9.0
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : None

**Comment by nicholas-ys-tan** [comment]
Not sure what the colours in your first plot are tied to, but you need to specify which column has the values to plot in:

`data.plot(ax=ax, cmap=cmap, edgecolor='black', linewidth=0.5)`

change to:

`data.plot(ax=ax, column='co2Capita', cmap=cmap, edgecolor='black', linewidth=0.5)`

The output I get is:

![image](https://github.com/geopandas/geopandas/assets/39729063/ab90445a-3385-4737-b2a3-3505f26cde96)

**Comment by JosephBARBIERDARNAL** [comment]
aaaaah that makes sense! thanks for the explanation.

I guess the issue can be closed if this is not considered as a bug
