### ISSUE TITLE
BUG: RoundTrip (de)serialization using GeoJSON driver results in unequal DataFrames

### ISSUE THREAD

**Issue by Jaapel** [geopandas/geopandas#3324]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

Not sure how to reproduce the bug without the (small and open) example data:

#### Code Sample, a copy-pastable example
```python
def test_geojson_roundtrip(tmp_path: Path):
    gdf1 = gpd.read_file(
        "https://raw.githubusercontent.com/Deltares/hydromt/v1.0.0-alpha1/tests/data/naturalearth_lowres.geojson"
    )
    new_path = tmp_path / "world.geojson"
    gdf1.to_file(new_path, driver="GeoJSON")
    gdf2 = gpd.read_file(new_path)
    gpd.testing.assert_geodataframe_equal(gdf1, gdf2)```
```

#### Problem description

While working on some ETL tooling, I found out that deserialization of a geojson file using GeoPandas DataFrame results in an `AssertionError`.

```text
AssertionError: 1 out of 177 geometries are not equal.
E           Indices where geometries are not equal: [14] 
```

#### Expected Output
No `AssertionError`.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:43:09) [GCC 12.3.0]
executable : /home/jaapel/miniforge3/envs/hydromt-dev/bin/python
machine    : Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.12.1
GEOS lib   : None
GDAL       : 3.8.2
GDAL data dir: /home/jaapel/miniforge3/envs/hydromt-dev/share/gdal
PROJ       : 9.3.1
PROJ data dir: /home/jaapel/miniforge3/envs/hydromt-dev/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.14.4
numpy      : 1.26.3
pandas     : 2.1.4
pyproj     : 3.6.1
shapely    : 2.0.2
fiona      : 1.9.5
geoalchemy2: None
geopy      : None
matplotlib : 3.8.2
mapclassify: 2.6.1
pygeos     : None
pyogrio    : 0.7.2
psycopg2   : None
pyarrow    : 14.0.2
rtree      : 1.1.0

</details>

**Comment by theroggy** [comment]
The problem seems to be that the naturalearth_lowres.geojson has an invalid geometry at row 14.

Testing equality on an invalid geometry gives undefined behaviour... and here it leads to inequality. Even if you compare gdf1 with itself you get as a result that it is not equal.

Once the invalid geometry is made valid, they result in equality...

Test script leading to this conclusion:

```
import difflib
from pathlib import Path
import tempfile

import geopandas as gpd
import geopandas.testing
import shapely


tmp_path = Path(tempfile.gettempdir())
gdf1 = gpd.read_file(
    "https://raw.githubusercontent.com/Deltares/hydromt/v1.0.0-alpha1/tests/data/naturalearth_lowres.geojson"
)
new_path = tmp_path / "world.geojson"
gdf1.to_file(new_path, driver="GeoJSON")
gdf2 = gpd.read_file(new_path)

# Compare
# gpd.testing.assert_geodataframe_equal(gdf1, gdf2)
print(f"{(shapely.equals(gdf1.iloc[14].geometry, gdf2.iloc[14].geometry))=}")

# Compare wkts
wkt1 = shapely.to_wkt(gdf1.iloc[14].geometry, rounding_precision=99)
wkt2 = shapely.to_wkt(gdf2.iloc[14].geometry, rounding_precision=99)
print(f"{(wkt1==wkt2)=}")

# Check validity of the invalid row gdf1 with itself
print(f"{(shapely.equals(gdf1.iloc[14].geometry, gdf1.iloc[14].geometry))=}")

# First make them valid, then check equality of those
gdf1_14_valid = shapely.make_valid(gdf1.iloc[14].geometry)
gdf2_14_valid = shapely.make_valid(gdf2.iloc[14].geometry)
print(f"{(shapely.equals(gdf1_14_valid, gdf2_14_valid))=}")
```
Output:
```
(shapely.equals(gdf1.iloc[14].geometry, gdf2.iloc[14].geometry))=False
(wkt1==wkt2)=True
(shapely.equals(gdf1.iloc[14].geometry, gdf1.iloc[14].geometry))=False
(shapely.equals(gdf1_14_valid, gdf2_14_valid))=True
```

**Comment by martinfleis** [comment]
Thanks @theroggy!

**Comment by Jaapel** [comment]
Thanks @theroggy !
I wonder how I created an invalid entry. Thanks for your code example!

**Comment by theroggy** [comment]
> Thanks @theroggy ! I wonder how I created an invalid entry. Thanks for your code example!

Not sure, but a possible reason might be that because geojson is a text format, coordinates have to be converted from the typical double floating point representation used in most formats to textual. This conversion implies rounding effects... and often additional rounding is applied to avoid having a lot of decimals in the files. This rounding can easily lead to invalid polygons...

**Comment by Jaapel** [comment]
@theroggy I will be more careful with geojson then!
