### ISSUE TITLE
Python crashes when trying df.to_file() with windows & Py32 env

### ISSUE THREAD

**Issue by philippschw** [geopandas/geopandas#334]
I noticed that geopandas fails to write data back to a shapefile under windows, with ubuntu in virtualbox it works fine.

**Info on system configuration and environment**
```
Windows 8, 64-bit operating system
Python 32bit, latest Enthought Python Distribution (EPD)
Geopandas version:  0.1.1
Fiona version:  1.6.2
```

**Used code:**
```
shapefile = 'data/shapefile/ShapefileName.shp'
df = gp.GeoDataFrame.from_file(shapefile)
df.to_file('MyGeometries.shp', driver='ESRI Shapefile')
```

**Comment by jorisvandenbossche** [comment]
@philippschw Could you be able to share a shapefile with which you have this problem? I used geopandas on Windows to write shapefiles, and did not see this problem (so certainly not a general windows problem)

**Comment by philippschw** [comment]
@jorisvandenbossche I am using the natural earth country dataset, you can download from here: 
[http://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/](http://www.naturalearthdata.com/downloads/50m-cultural-vectors/50m-admin-0-countries-2/
)
or from dropbox:
[https://www.dropbox.com/s/bs7fjv0uaerxn5h/shapefile.7z?dl=0](https://www.dropbox.com/s/bs7fjv0uaerxn5h/shapefile.7z?dl=0
)

**Comment by philippschw** [comment]
I reinstalled everything and tried to replicate my working Linux environment (which does not really work because I am dependent on the provided windows  binariess). Nevertheless, the problem persists also with the development version of geopandas in this env:
```
GDAL 1.11.4
Fiona 1.6.3
0.1.0.dev-dc4b548
```

**Working setup in Linux:**

```
GDAL: 1.11.2
Fiona: 1.6.0
Geopandas: 0.1.0.dev- 
```

**Comment by kjordahl** [comment]
I can't reproduce this either. The issue is almost certainly a compiled library you're using. I suggest you try reproducing directly in Fiona and file a bug report with Enthought.

**Comment by philippschw** [comment]
Ok, thank you will do.

**Comment by bidhya** [comment]
I am having the same problem of Python crashing when trying to save a shapefile on windows using to_file command from Geopandas dataframe. I didn't have this issue before. So it must be due to updates to some libraries, but I just noticed this error now. If someone has a solution/suggestion, please let me know. I am on windows 10 with 32 bit Python version 2.7, with the following version of libraries
`fiona     : 1.6.3
geopandas : 0.1.0.dev
gdal      : 1.11.4`

**Comment by jorisvandenbossche** [comment]
@bidhya How did you install those libraries?

**Comment by philippschw** [comment]
I did not change anything on my installation setup but I noticed that I am able to use _**to_file**_ when I import geopandas explicitly with:
`from geopandas import GeoSeries, GeoDataFrame
`
instead of 

`import geopandas as gp
`

I am still testing, it could also be related to other modules I am loading but maybe this helps to identify the problem.

**Comment by philippschw** [comment]
I do not know why but unfortunately, the described approach works sometimes but not always.

**Comment by micahcochran** [comment]
Does the crash give an error message?

**Comment by bidhya** [comment]
It just says python stopped working and crash. I use anaconda Python, but I downloaded the GIS libraries from this site http://www.lfd.uci.edu/~gohlke/pythonlibs/ as per instructions given here : http://geoffboeing.com/2014/09/using-geopandas-windows/

I installed the geopandas libraries from this github repository.

**Comment by jorisvandenbossche** [comment]
@bidhya Can you try installing the GIS libraries with conda (from the conda-forge channel)?

```
conda install - conda-forge gdal fiona geopandas ..
```

And see if you still have the same problem?

**Comment by bidhya** [comment]
@jorisvandenbossche I removed all the GIS libraries and installed them as per your instruction. I was able to install gdal, pyproj, and shapely from "conda-forge" channel, but the "Fiona" library installed from this channel crashes with error. So I installed fiona from http://www.lfd.uci.edu/~gohlke/pythonlibs/. 

Also while installing geopandas from conda-forge, I got the following error
The following specifications were found to be in conflict:
  - geopandas
  - qt -> jpeg 8d
Use "conda info <package>" to see the dependencies for each package.

Therefore, I installed geopandas from git directly. Still the problem persists - Python crashes on using the command "to_file" to save a geopandas dataframe to shapefile.

If someone have solved the problem, please let me know.

**Comment by jorisvandenbossche** [comment]
@bidhya Sorry to hear you still have problems with, but thanks for trying!

The fact that fiona crashes when you install it from `conda-forge`, can you report it over there? (and include the error message you see) https://github.com/conda-forge/fiona-feedstock

The conflict you get when trying to install geopandas from conda-forge, can you report this at the geopandas conda-forge tracker? https://github.com/conda-forge/geopandas-feedstock I suppose this is a problem with matplotlib dependency (which python version are you using? As for 3.5 there are problems with matplotlib)

**Comment by ac120374** [comment]
I have the same issue. I use Python 3.4 and 0.2.1 version of geopandas. For me gdf.to_file doesn't work after I join a table to it. If I save it before the join, it works.

**Comment by ulisessol7** [comment]
Did anybody found a solution to this?

**Comment by ac120374** [comment]
As others pointed out, it appears to be incompatibility issues between versions of OS, Python and each specific dependency of geopandas. I found out that wrong version of Python was installed on my machine (python 32bit on 64bit machine). I have reinstalled right version of python, then downloaded all the dependencies again. And it works now with no issues. I did it on different machines (at my two different jobs) with both Pyhton3 and Python2; it works when installed properly.

**Comment by ulisessol7** [comment]
Thanks for the reply ac120374 , I am running portable versions of python (32 bit & 64 bit), I managed to install geopandas on my 64 bit python but I kept getting the error on my 32 bit installation. Did you used the http://www.lfd.uci.edu/~gohlke/pythonlibs/ for you 32 bit installation?

**Comment by ac120374** [comment]
Yes, I used Christoph Gohlke wheels for all the dependencies, but as I said, my mistake was that my machine had 32bit version of Python while the machine's processor is 64bit. I originally downloaded the wheels for 32bit Python therefore. Once I deleted the wrong version of Python and installed the 64bit one and downloaded the wheels again (now for OS-compatible Python), it worked. So, it doesn't look like there is a bug in any of the geopandas versions, but rather all the dependencies are less forgiving of the incompatibility issues that are usually not noticeable in other packages.

**Comment by ulisessol7** [comment]
Thanks again, I understand now.

**Comment by jorisvandenbossche** [comment]
To be clear, as far as I understand, possible problems in this issue have nothing to do with geopandas itself, but with its dependencies (just to say that the exact version of geopandas itself should not be of importance). 
I also want to note that I don't have any problems with the latest versions installed with conda from the conda-forge channel. If you have problems with that, please report!

**Comment by bidhya** [comment]
Sometimes when the output directory is not specified properly, it crashes the whole python shell without any warming. That is, the output directory has to exist already.
