### ISSUE TITLE
Drop Python 3.9 and require Python 3.10+

### ISSUE THREAD

**Issue by EwoutH** [geopandas/geopandas#3355]
With the GeoPandas 1.0 release out (congratulations!), would this be a good time to start dropping Python 3.9 support (for future releases and development)?

- [SPEC-0](https://scientific-python.org/specs/spec-0000/#support-window) supports dropping 3.9 for 8 months already
- Pandas just dropped 3.9 support: https://github.com/pandas-dev/pandas/pull/58238

Of course existing release will stay available for Python 3.9, including 1.0. This would only affect future releases.

**Comment by martinfleis** [comment]
We generally follow SPEC0 so this will surely happen for 1.1.

**Comment by jorisvandenbossche** [comment]
I would just wait a bit with actually doing this, as for the first weeks we might want to cut a possible 1.0.x directly from main (as long as no new features landed yet)

**Comment by kloczek** [comment]
I've been trying to upgrade code using pyupgrade and after that pytest started showing new failing units.
Even `pyupgrade --py38-plus` generated patch messes with pytest.

**Comment by m-richards** [comment]
Thanks @kloczek for having a look, generally when doing this upgrade we don't tend to use pyupgrade but are instead focused purely on updating CI for python versions and also the minimum versions of our dependencies. (I think though once we have upgraded to python 3.9+ we could look at using pyupgrade to see if there are any old code patterns we could modernise)

**Comment by kloczek** [comment]
I must correct myself.
After upgrade to latest `pyupgrade` everything is OK so it would be good to filter all code over this tool to drop older python versions support (I've tested that up to --py310-plus).
It would be good to filter all code over `ruff` as well.

**Comment by kloczek** [comment]
Thank you.

**Comment by EwoutH** [comment]
With Python 3.9 being dropped, and Python 3.13 releasing in a week, this might be a great time to iron out the last bugs/warnings:
- https://github.com/geopandas/geopandas/issues/3400

I don't know exactly what this repos system with the CI envs files is, otherwise I would have opened an PR.
