### ISSUE TITLE
concat incompatibility with pandas main

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3372]
There's an issue caused by https://github.com/pandas-dev/pandas/pull/59141 resulting in our concat [failing](https://github.com/geopandas/geopandas/actions/runs/9817406953/job/27108741741). Still trying to figure out if it should be fixed here or there.

**Comment by martinfleis** [comment]
Will likely be fixed by https://github.com/pandas-dev/pandas/pull/59195

**Comment by m-richards** [comment]
dev is passing again now that is merged
