### ISSUE TITLE
to_crs doesn't take _geometry_column_name into account

### ISSUE THREAD

**Issue by krvkir** [geopandas/geopandas#339]
When I have geodataframe with geometry column named e.g. 'geom', and convert the dataframe to another crs, new column named 'geometry' is created.

Is this intentional? I think that more predictable behaviour would be to rewrite the old geometry column instead of creating new one.

(Using version 0.2.0.dev cloned form this repo.)

**Comment by kjordahl** [comment]
This is due to a bug in `set_geometry()`. It can be reproduced with `df.set_geometry(df.geometry)`, which will introduce a new `geometry` column for any `GeoDataFrame` using a different geometry column name.
