### ISSUE TITLE
BUG: fiona.path module is being deprecated in 1.10.0 

### ISSUE THREAD

**Issue by philiporlando** [geopandas/geopandas#3390]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [ ] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd

gdf = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/geopandas/io/file.py", line 259, in _read_file
#     return _read_file_fiona(
#   File "/home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/geopandas/io/file.py", line 280, in _read_file_fiona
#     if _is_zip(str(path_or_bytes)):
#   File "/home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/geopandas/io/file.py", line 164, in _is_zip
#     parsed = fiona.path.ParsedPath.from_uri(path)
# AttributeError: module 'fiona' has no attribute 'path'. Did you mean: 'Path'?
```

#### Problem description

The fiona package has announced that the `fiona.path` module will be deprecated in `1.10.0`. This deprecation breaks `geopandas.read_file()`, specifically `_read_file_fiona()`. More details [here](https://github.com/Toblerity/Fiona/blob/759d31ebcf2e715efa631894ea81fc4bba848f4b/CHANGES.txt#L82-L86).

I'm seeing an `AttributeError: module 'fiona' has no attribute 'path'. Did you mean: 'Path'?` error when trying to upgrade fiona to the latest pre-release version, `1.10b2`, on a personal project ([fgdb-to-gpkg](https://pypi.org/project/fgdb-to-gpkg/)). I'm documenting this bug [here](https://github.com/philiporlando/fgdb_to_gpkg/pull/24).

#### Expected Output

The above reprex should run without error. Downgrading to `fiona 1.9.6` avoids this issue.

The geopandas package will need to be updated to handle this deprecation. `_read_file_fiona()` should run successfully regardless of which version of fiona is used. 

#### Output of ``geopandas.show_versions()``

<details>

```
geopandas.show_versions()

SYSTEM INFO
-----------
python     : 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
executable : /home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/bin/python
machine    : Linux-5.15.0-116-generic-x86_64-with-glibc2.35

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.4
GEOS lib   : None
GDAL       : 3.8.4
GDAL data dir: None
PROJ       : 9.3.0
PROJ data dir: /home/porlando/.local/share/virtualenvs/fgdb_to_gpkg-TVksE44w/lib/python3.10/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.12.2
numpy      : 1.26.4
pandas     : 2.2.2
pyproj     : 3.6.1
shapely    : 2.0.5
fiona      : 1.10b2
geoalchemy2: None
geopy      : None
matplotlib : None
mapclassify: None
pygeos     : None
pyogrio    : None
psycopg2   : None
pyarrow    : None
rtree      : None
```

</details>

**Comment by martinfleis** [comment]
Please update your version of geopandas. 0.12 is very outdated and 1.0 is compatible with Fiona 1.10.

**Comment by philiporlando** [comment]
My mistake. Thanks for letting me know.
