### ISSUE TITLE
Resolve FutureWarning: GeometryArray._reduce will require a keepdims parameter

### ISSUE THREAD

**Issue by EwoutH** [geopandas/geopandas#3403]
One of our tests came up with a strange error:
```
tests/test_osmnx.py::test_bearings
  /home/runner/work/osmnx/osmnx/osmnx/convert.py:506: FutureWarning: <class 'geopandas.array.GeometryArray'>._reduce will require a keepdims parameter in the future
    dupes = edges[mask].dropna(subset=["geometry"])
```
I think it's caused by Pandas moving towards their 3.0 release, and specifically this deprecation that's being dropped, as part of their effort:
- https://github.com/pandas-dev/pandas/pull/52788

Could it be that GeoPandas needs to update it's 
`‎GeometryArray._reduce` method with an `keepdims: bool = False` argument, since that inherits/overwrites the updated `Array._reduce`?

https://github.com/geopandas/geopandas/blob/cd932d1f127f39ff13e84d12f20de80efbe579c9/geopandas/array.py#L1640-L1648

Or is this an issue with how `_reduce` is called, possible in this repo or outside of it?

**Comment by martinfleis** [comment]
Are you able to provide a minimal reproducible example triggering this warning? Our dev CI does not produce it at the moment.

**Comment by EwoutH** [comment]
Sorry, at this time I don't have time to create one, and can only offer a link to [the error](https://github.com/EwoutH/osmnx/actions/runs/10432783367/job/28893833020#step:8:33) and from where [it originates](https://github.com/gboeing/osmnx/blob/94b7e7358e88a68ef4f07344c8d03c0da140f775/tests/test_osmnx.py#L148). I know it's a lousy report, sorry.

Feel free to close this issue.

**Comment by jorisvandenbossche** [comment]
The warning points to https://github.com/gboeing/osmnx/blob/94b7e7358e88a68ef4f07344c8d03c0da140f775/osmnx/convert.py#L506, which is:

```
    mask = edges["uvk"].duplicated(keep=False)
    dupes = edges[mask].dropna(subset=["geometry"])
```

where `edges` is a geodataframe

(it's a bit strange that this causes that .., and ideally the warning would have pointed to the code deeper down that actually caused this ..)
