### ISSUE TITLE
Drop defaults channel from CI

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#3437]
I propose we drop the defaults channel from our CI matrix. Right now, it fails because it pulls the latest numpy but shapely 2.0.4, raising those collection errors fixed in shapely 2.0.6 and there's nothing we can do about that. I can pin numpy to 2.0.x until they fix it but it will stay pinned for 2 years...

I don't remember if it ever uncovered any issue and the versions there are out of our hands. In my eyes, it comes with trouble and no value, hence I'd drop it.

**Comment by m-richards** [comment]
Agree with this, it only ever seems to cause issues. We already prefer conda-forge in the installation docs, but we could be more explicit in recommending not to use defaults since it is often so far out of date.

**Comment by martinfleis** [comment]
>  since it is often so far out of date.

and since it has license implications.
