### ISSUE TITLE
GitHub pages build errors

### ISSUE THREAD

**Issue by kjordahl** [geopandas/geopandas#345]
The GitHub pages build of the docs in the `gh-pages` branch of this repository (served at http://geopandas.github.io/geopandas, which is the source for geopandas.org), has a couple errors in it.
- The version is incorrectly shown as "0.2-py3.5.egg". That may be a sphinx issue in my environment, as the version shows up correctly when importing.
- At least two figures are missing due to PySAL import errors on this page: http://geopandas.org/aggregation_with_dissolve.html

We should rebuild and deploy the released docs.

**Comment by jorisvandenbossche** [comment]
> The version is incorrectly shown as "0.2-py3.5.egg". That may be a sphinx issue in my environment, as the version shows up correctly when importing.

Not sure what the reason would be for this ..

> At least two figures are missing due to PySAL import errors on this page: http://geopandas.org/aggregation_with_dissolve.html

Do you have PySAL installed?

> We should rebuild and deploy the released docs.

Or, we could also point geopandas.org to readthedocs (and then we don't have to manually build and deploy the docs)

**Comment by jorisvandenbossche** [comment]
There are also 'KeyBoardInterrupt' errors at this page: http://geopandas.org/set_operations.html

**Comment by jorisvandenbossche** [comment]
> The version is incorrectly shown as "0.2-py3.5.egg". That may be a sphinx issue in my environment, as the version shows up correctly when importing.

http://geopandas.readthedocs.io/en/master/ has the same problem, but locally I don't see this problem.

@kjordahl Can you give me access to the readthedocs settings for geopandas? Then I can see how to build docs for a released version.

**Comment by kjordahl** [comment]
> Do you have PySAL installed?

Yes, but there was a relative import error in my python 3.5 env:

```
//anaconda/envs/py35/lib/python3.5/site-packages/pysal/cg/__init__.py in <module>()
      3 """
----> 4 from shapes import *
      5 from standalone import *

ImportError: No module named 'shapes'
```

> Can you give me access to the readthedocs settings for geopandas? 

Done.

**Comment by jorisvandenbossche** [comment]
> > Can you give me access to the readthedocs settings for geopandas?
> Done.

Thanks! I have reduced the number of versions you can see on readthedocs to now only 'stable', 'latest' and the 'version' tags (not 'master', 'doc-mock-dependencies' and 'doc-readthedocs-requirements' anymore)

**Comment by jdmcbr** [comment]
@jorisvandenbossche I'm able to build docs locally with my system install; in particular, I don't see the KeyboardInterrupt errors. I tried to create an environment with the packages specified in the environment.yaml file, and am running into what seems to be an unsatisfiable dependency issue.

**Comment by jorisvandenbossche** [comment]
Yes, and on readthedocs they are also built fine: http://geopandas.readthedocs.io/en/latest/aggregation_with_dissolve.html

I would personally let `geopandas.org` use what is hosted on readthedocs, but for now we can just update the `gh-pages` branch in the repo here. Let's just make sure we update it when releasing 0.3

So I think this can actually be closed? (also the  "0.2-py3.5.egg" version tag is solved since 0.2.1)

**Comment by jdmcbr** [comment]
@jorisvandenbossche Would it be possible to just go straight to directing geopandas.org to redirect to what is on readthedocs? Though I don't know what would be involved in that.

I took a crack at a PR to update the gh-pages, but got stymied first by lack of any shared history (I'd created a bare repo and put the docs in there, but then couldn't make a PR) and then by different mess when I created a new branch from the existing gh-pages branch and then tried to build the docs again.

I think we should leave this open until what is hosted at geopandas.org is updated, whatever the path taken to do that.

**Comment by jorisvandenbossche** [comment]
>  Would it be possible to just go straight to directing geopandas.org to redirect to what is on readthedocs? 

Yes, that is certainly possible, but that is something that @kjordahl will need to do. And it should also be possible to show what is hosted on readthedocs, but keep the geopandas.org url. 
But until such a redirect is in place, we can update the ghpages branch to update the website.

> I took a crack at a PR to update the gh-pages, but got stymied first by lack of any shared history (I'd created a bare repo and put the docs in there, but then couldn't make a PR) and then by different mess when I created a new branch from the existing gh-pages branch and then tried to build the docs again.

Yeah, I didn't do it myself yet, so not sure how to do it exactly. But if that would make it easier, for the gh-pages branch it is certainly fine to directly push to that branch without making a PR. 
I think the easiest is to make a second clone of geopandas, where you check out the gh-pages branch and delete all history. Then you can copy the built docs over there and push. See eg https://daler.github.io/sphinxdoc-test/includeme.html

**Comment by jdmcbr** [comment]
@jorisvandenbossche That simplified matters a bit. Thanks for the direction; before starting this exercise, I'd misunderstood the process by which the docs on geopandas.org were generated, so went down (in retrospect) a couple of not-very-productive paths. In any case, the docs are updated, and I think the aforementioned issues are now fixed.

@daidoji @kuanb

**Comment by jorisvandenbossche** [comment]
Looks good, thanks a lot!
