### ISSUE TITLE
.plot() function not responding

### ISSUE THREAD

**Issue by debboutr** [geopandas/geopandas#346]
I pip installed geopandas and added all of the dependencies here:
   [http://geopandas.org/contributing.html](url)

seems like matplotlib should be a dependency.  After installing it, I try to run through the first example:
`p1 = Polygon([(0, 0), (1, 0), (1, 1)])
p2 = Polygon([(0, 0), (1, 0), (1, 1), (0, 1)])
p3 = Polygon([(2, 0), (3, 0), (3, 1), (2, 1)])
g = gpd.GeoSeries([p1,p2,p3])
g.plot()'

and I get a plot window that pops up, but is Not Responding and then kills my kernel.

![pyplot](https://cloud.githubusercontent.com/assets/7052993/15977031/3d4a7c5c-2f0b-11e6-8308-a300941d861b.PNG)

If I just run:
    >>> p1
in the console it dipslays the geometry of the triangle there.
![p1](https://cloud.githubusercontent.com/assets/7052993/15977128/c0ffeb18-2f0b-11e6-925f-71449525916c.PNG)

 Not sure what's going on

**Comment by jorisvandenbossche** [comment]
If you look at http://geopandas.org/install.html, you will see matplotlib is listed as optional dependency (but indeed would be good to mention that as well in the contributing guide).

Does plotting a simple plot (without geopandas) work? Or does that hang as well?

**Comment by debboutr** [comment]
using magic operator seemed to do the trick
`%matplotlib`

...not sure what the magic is, it was failing in spyder as well as jupyter notebook for me prior.
