### ISSUE TITLE
BUG:visualisation of using categorical feature for colour

### ISSUE THREAD

**Issue by Gabriel-Kissin** [geopandas/geopandas#3478]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of geopandas.

- [x] (optional) I have confirmed this bug exists on the main branch of geopandas.

---

#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
import geodatasets
import matplotlib.pyplot as plt

gdf = gpd.read_file(geodatasets.get_path('geoda.us_sdoh'))
gdf['state'] = gdf['state'].astype('category')

fig, axs = plt.subplots(1, 3, figsize=(16, 8))

gdf.plot(column='state', ax=axs[0])
axs[0].set_title('original categorical data')

gdf['state'] = gdf['state'].cat.add_categories(['country_' + str(i+1) for i in range(400)])
gdf.plot(column='state', ax=axs[1])
axs[1].set_title('with 400 additional categories')

gdf['state'] = gdf['state'].astype(str)
gdf.plot(column='state', ax=axs[2])
axs[2].set_title('workaround - convert to strings')

plt.show()
```

#### Problem description

When visualising geo data on a map, and colouring regions/points using one of the dataset columns. If that column is categorical, and there are many categories, the colouring can go wrong.   

For example, if we had a dataset of regions in all countries and states in the world. But we only want to visualise the regions of the USA; and we want to colour by state. After we filter for just the USA, the states column (if it is categorical) will still have unused categories, for all other countries of the world - they have been filtered out, but the categories still exist. And this makes the plot go awry.

![image](https://github.com/user-attachments/assets/f8dc778a-6a8d-4534-ab26-a33c0dc1ee7f)
In the above, the middle plot is when 400 additional categories have been added which aren't present in the data being visualised. If that number is changed to 500, the states are all blue.  

In my use case, the dataset is large and the column to colour with has to be categorical to save memory. However when this isn't an issue, a workaround is to simply convert the filtered dataset to strings (third ax). Alternatively, one can use `cat.remove_unused_categories()` on the column after filtering.

#### Expected Output

Unused categories should be ignored when colouring the map; the second ax should look the same as the first.

#### Output of ``geopandas.show_versions()``

<details>

SYSTEM INFO
-----------
python     : 3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.3.9.4)]
executable : [/opt/homebrew/opt/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/opt/python)@3.12/bin/python3.12
machine    : macOS-15.1-arm64-arm-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.11.4
GEOS lib   : None
GDAL       : 3.8.5
GDAL data dir: [/Users/gabriel.kissin/Library/Python/3.12/lib/python/site-packages/pyogrio/gdal_data/](https://file+.vscode-resource.vscode-cdn.net/Users/gabriel.kissin/Library/Python/3.12/lib/python/site-packages/pyogrio/gdal_data/)
PROJ       : 9.3.0
PROJ data dir: [/Users/gabriel.kissin/Library/Python/3.12/lib/python/site-packages/pyproj/proj_dir/share/proj](https://file+.vscode-resource.vscode-cdn.net/Users/gabriel.kissin/Library/Python/3.12/lib/python/site-packages/pyproj/proj_dir/share/proj)

PYTHON DEPENDENCIES
-------------------
geopandas  : 1.0.1
numpy      : 1.26.4
pandas     : 2.2.2
pyproj     : 3.6.1
shapely    : 2.0.6
pyogrio    : 0.9.0
geoalchemy2: 0.15.2
geopy      : 2.4.1
matplotlib : 3.8.4
mapclassify: 2.8.0
fiona      : None
psycopg    : None
psycopg2   : None
pyarrow    : 17.0.0
</details>

**Comment by martinfleis** [comment]
That's not a bug in geopandas. By default, geopandas uses `tab10` categorical colormap from matplotlib, which has 10 unique colours. If there's more categories, we just have to recycle the colours for multiple classes, resulting in the reported behaviour. If you need a categorical map with more unique categories, you should explicitly pass a colormap that supports that number of categories.

**Comment by Gabriel-Kissin** [comment]
> That's not a bug in geopandas. By default, geopandas uses `tab10` categorical colormap from matplotlib, which has 10 unique colours. If there's more categories, we just have to recycle the colours for multiple classes, resulting in the reported behaviour. If you need a categorical map with more unique categories, you should explicitly pass a colormap that supports that number of categories.

The middle plot above is only making use of two of `tab10`'s colours: blue and orange

**Comment by Gabriel-Kissin** [comment]
> On top of that - unusued categories are intentionally preserved in mapping to ensure consistency across subsets based on the same categorical.

Ah OK that makes sense. Why is it though that all the states got given blue (and orange) - does that indicate something about how the colours are assigned? E.g. when using `tab10`, blue is always given to the first 10% of categories?

**Comment by martinfleis** [comment]
> Why is it though that all the states got given blue (and orange) - does that indicate something about how the colours are assigned? E.g. when using tab10, blue is always given to the first 10% of categories?

Yeah. You can assume that the cmap is _stretched_ to fit the number of classes. It does not "cycle" through.

**Comment by Gabriel-Kissin** [comment]
> > Why is it though that all the states got given blue (and orange) - does that indicate something about how the colours are assigned? E.g. when using tab10, blue is always given to the first 10% of categories?
> 
> Yeah. You can assume that the cmap is _stretched_ to fit the number of classes. It does not "cycle" through.

OK. I guess cycling would solve the issue in this particular contrived case, but not in general. 

The only other thing I can think of is instead of using `tab10` as a default, to construct a cmap with enough categories to match either the number of unique values (with non-categorical data) or the number of categories. But I guess that is covered under [this separate ENH request](https://github.com/geopandas/geopandas/issues/2804).

**Comment by m-richards** [comment]
Something we could do is warn  the user if the plotting code receives more than 10 categories, noting they will be cycled and they should supply a custom colourmap?
