### ISSUE TITLE
ENH: dekgl/lonboard backend for explore

### ISSUE THREAD

**Issue by knaaptime** [geopandas/geopandas#3490]
newer visualization libraries, specifically [lonboard](https://developmentseed.org/lonboard), are much more performant than folium and have some other really nice rendering features (like 3d extrusion). It would be awesome to have a method like `explore` (or a keyword argument that governs the backend) that generates a lonboard.Map instead of a folium.Map. Something like this is a fairly crude first cut, but works nicely for my applications, so curious if there's interest in exploring this

```python
from lonboard import viz
from lonboard.colormap import apply_categorical_cmap, apply_continuous_cmap
from mapclassify.util import get_color_array
from matplotlib import colormaps
from warnings import warn

# explore but with deckgl... er, decksplore :P

def dexplore(
    gdf,
    variable=None,
    cmap="viridis",
    scheme="quantiles",
    k=6,
    categorical=False,
    elevation=None,
    extruded=False,
    elevation_scale=1,
    alpha=1,
    layer_kwargs=None,
    map_kwargs=None,
    classify_kwargs=None,
    nan_color=[255, 255, 255, 255],
    color=None,
    wireframe=False,
):
    if map_kwargs is None:
        map_kwargs = dict()
    if classify_kwargs is None:
        classify_kwargs = dict()
    if layer_kwargs is None:
        layer_kwargs = dict()
    if isinstance(elevation, str):
        if elevation in gdf.columns:
            elevation = gdf[elevation]
        else:
            raise ValueError(
                f"the designated height column {elevation} is not in the dataframe"
            )

    # only polygons have z
    if ["Polygon", "MultiPolygon"] in gdf.geometry.geom_type.unique():
        layer_kwargs["get_elevation"] = elevation
        layer_kwargs["extruded"] = extruded
        layer_kwargs["elevation_scale"] = elevation_scale
        layer_kwargs["wireframe"] = wireframe

    LINE = False  # set color of lines, not fill_color
    if ["LineString", "MultiLineString"] in gdf.geometry.geom_type.unique():
        LINE = True
    if color:
        if LINE:
            layer_kwargs["get_color"] = color
        else:
            layer_kwargs["get_fill_color"] = color
    if variable is not None:
        if variable not in gdf.columns:
            raise ValueError(
                f"the designated column {variable} is not in the dataframe"
            )
        if categorical:
            color_array = _get_categorical_cmap(gdf[variable].values, cmap)
        elif scheme is None:
            color_array = apply_continuous_cmap(
                values=gdf[variable], cmap=colormaps[cmap], alpha=alpha
            )
        else:
            color_array = get_color_array(
                gdf[variable],
                scheme=scheme,
                k=k,
                cmap=cmap,
                alpha=alpha,
                nan_color=nan_color,
                **classify_kwargs,
            )

        if LINE:
            layer_kwargs["get_color"] = color_array

        else:
            layer_kwargs["get_fill_color"] = color_array
    m = viz(
        gdf,
        polygon_kwargs=layer_kwargs,
        scatterplot_kwargs=layer_kwargs,
        path_kwargs=layer_kwargs,
        map_kwargs=map_kwargs,
    )

    return m


def _get_categorical_cmap(categories, cmap):
    colors = colormaps[cmap].colors
    colors = (np.array(colors) * 255).astype(int)
    unique_cats = np.unique(categories)
    n_cats = len(unique_cats)
    n_colors = colors.shape[0]
    if n_cats > n_colors:
        warn("the number of unique categories exceeds the number of available colors")
        floor = (n_cats // n_colors) + 1
        colors = np.vstack([colors] * floor)
    temp_cmap = dict(zip(unique_cats, colors))
    fill_color = apply_categorical_cmap(categories, temp_cmap)
    return fill_color

```

cc @kylebarron

**Comment by knaaptime** [comment]
updated. this version should handle continuous or categorical plots too, which I think makes the signature about as compatible with `plot` or `explore` as possible. here's a notebook https://gist.github.com/knaaptime/6f6c4f1ae7ce6b156b4cfbcc6b029f98

**Comment by martinfleis** [comment]
We have briefly discussed exposing some form of an API to plug in different plotting engines some time ago (maybe even before `explore` existed) but never came with an actual idea how to do that. The idea was that an external package would "register" itself and become exposed from our API afterwards without us writing and maintaining the implementation. 

What I can say for sure is that we cannot maintain another plotting implementation here, we're out of capacity. That is why I like the approach `hvplot` takes as they add a new method on a GeoDataFrame while maintaining all the code there.

**Comment by knaaptime** [comment]
Figured you might say that (which is why I dropped the code into an issue instead of PR ;))

there isn’t a ton of code beyond what lonboard’s own viz method provides except classification handling. Maybe thats worth incorporating upstream in longboard, maybe not. I suppose it’s a long enough function that I’ll end up sticking it somewhere if not

**Comment by knaaptime** [comment]
> That is why I like the approach hvplot takes as they add a new method on a GeoDataFrame while maintaining all the code there.

I guess I should take another look cause I thought subclassing like that was a big no no

**Comment by martinfleis** [comment]
That's not subclassing, that's extending using the accessor API - https://pandas.pydata.org/docs/development/extending.html
