### ISSUE TITLE
Plotting points with a colormap (cmap)

### ISSUE THREAD

**Issue by davidbailey** [geopandas/geopandas#350]
Recently when working with colormaps applied to Points, I discovered the following two issues. I'm open to creating a pull request to fix them, but this will change default behaviors that people may be using.
1. If the DataSeries specified as "column" in GeoDataFrame.plot() contains any NaN values, the colormap will not work. This is because the normalization algorithm sets both the min and max values of the series to NaN and therefore all points plot with the same color. The workaround is to drop all NaN values from the series before setting it as the column, or manually setting the vmin and vmax. Should this function drop all NaN values automatically before normalizing?
   (https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L371)
2. Because the default marker is 'o' and the default markersize is 2, all points appear black (because of outlines) and colormaps do not appear to work. This is fixed by changing the marker to '.' or by increasing the markersize, but that is not documented or intuitive to me.
   (https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L52)

Examples of the workarounds/fixes are here: https://github.com/davidbailey/py/blob/master/speeds2.py#L35 and https://github.com/davidbailey/py/blob/master/speeds2.py#L38
with the resulting plot here: https://raw.githubusercontent.com/davidbailey/py/master/speeds2.png

**Comment by jorisvandenbossche** [comment]
> Should this function drop all NaN values automatically before normalizing?

Yes, that sounds sensible. Although you should check to which color the NaNs are converted to, as this could give a non-desirable result (so maybe dropping them would make more sense).
PR welcome!

> Because the default marker is 'o' and the default markersize is 2, all points appear black (because of outlines)

Yep, but, this will probably going to change when using collections for plotting (there is a WIP PR). So maybe we should revisit this after that.

**Comment by ResidentMario** [comment]
xref #405

**Comment by martinfleis** [comment]
GeoPandas now drops NaNs when plotting (#1156) and has different default with no outlines covering the actual color.
