### ISSUE TITLE
Point out getting back pandas.plot methods in the documentation 

### ISSUE THREAD

**Issue by ResidentMario** [geopandas/geopandas#354]
Hello,

I think that this library ought to work as hard as possible to ensure that it's seamlessly compatible with `pandas`. That is, ideally, except in the cases where this is impossible, a `GeoSeries` and `GeoDataFrame` should allow the user access to all of the basal `pandas` `Series` and `DataFrame` methods.

`plot()` strikes me as being poorly placed, in this respect. At the moment the `geopandas` plot overrides the `pandas` one with the `geopandas` geographical plotter. This is a nice feature to have, but I don't really get why it has to exist at `plot()`&mdash;where it overwrites existing `pandas.plot` methods&mdash;and not at, say, `geoplot()`.

This is not _that_ hand to work around. `pandas` plotting methods make no sense for a `GeoSeries`, and for `GeoDataFrame` you can convert back:

```
pd.DataFrame(gdf).plot
<pandas.tools.plotting.FramePlotMethods object at 0x0000000008FE4F60>
```

Probably this has been the case for too long for changing it to be viable, given backwards compatibility and all that. Still, I think it'd be worth the effort to more explicitly point the trick above out in the documentation so that at least people have a better sense of how to get their old plotting methods back.

**Comment by ResidentMario** [comment]
I still think this is important. xref #405

**Comment by martinfleis** [comment]
All pandas plotting methods are now available via `GeoDataFrame.plot.<type>` which resolves this issue.
