### ISSUE TITLE
How to specify legend position so that it doesn't cover the map ?

### ISSUE THREAD

**Issue by sylvaticus** [geopandas/geopandas#355]
Hello, is there any way to specify a position/characteristic (number of columns, font size, width..) for the legend so that it doesn't cover the map (like you can see in Out[13] here: https://gist.github.com/jorisvandenbossche/7b30ed43366a85af8626 )

Cheers

**Comment by ResidentMario** [comment]
`geoplot` does this with a `legend_kwargs` argument (as used elsewhere), doesn't think the current `geopandas` plotter does it. xref #405.

**Comment by jdmcbr** [comment]
Closed by #434.
