### ISSUE TITLE
Allow 'k' number of classes greater than 9 for choropleth schemes

### ISSUE THREAD

**Issue by mlyons-tcc** [geopandas/geopandas#356]
Setting a maximum value of 9 for choropleth schemes is unnecessarily limiting.

**Comment by jorisvandenbossche** [comment]
Yes, I agree. Interested in doing a PR to change this?

**Comment by mlyons-tcc** [comment]
Yes. Is there a desire to catch k in range within geopandas or just leave it to the underlying module (e.g. PySAL). For Fisher Jenks, PySAL allows k to be from 1 to the number of unique values, and raises ValueErrors.

If you think geopandas should have a range check on k, do you have an opinion on a max k?

**Comment by jorisvandenbossche** [comment]
I think we could just leave it to PySAL to handle the `k` value
