### ISSUE TITLE
Use Fisher_Jenks_Sampled for large set of values to plot

### ISSUE THREAD

**Issue by mlyons-tcc** [geopandas/geopandas#357]
Instead of using `Fisher_Jenks` from PySAL, geopandas should be using `Fisher_Jenks_Sampled` so that performance can be optimized for plotting large datasets with the 'fisher_jenks' `scheme`.

The defaults for `Fisher_Jenks_Sampled` should be set such that it performs the current behavior of `Fisher_Jenks`. `pct` and `truncate` parameters can be passed down through the `plot` method's **kwargs.

**Comment by mlyons-tcc** [comment]
I'm not particularly a fan of the logic for truncate in `Fisher_Jenks_Sampled`. You'd think that the number of points used would correlate with the number of classes, k. I don't know if it's worth owning logic in geopandas though.

Thoughts?

**Comment by jorisvandenbossche** [comment]
I am not very familiar with PySAL's schemes. 
@darribas thoughts?

**Comment by jdmcbr** [comment]
#876 provides access to all classifiers, which I think obviates this.
