### ISSUE TITLE
Invalid scheme should raise exception instead of being modified to 'Quantiles'

### ISSUE THREAD

**Issue by mlyons-tcc** [geopandas/geopandas#359]
IMO, an invalid, unsupported, or typo scheme should not [revert to using Quantiles](https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L324). Warning messages aren't always visible, and an unsupported scheme being used is clearly an error scenario. I think an exception should be raised.

**Comment by jorisvandenbossche** [comment]
Sounds sensible!
