### ISSUE TITLE
Release 0.2 reports version "0+unknown"

### ISSUE THREAD

**Issue by micahcochran** [geopandas/geopandas#361]
Under pip the geopandas release 0.2 is being reported as "0+unknown"
```
$ pip3 list | grep geopandas
geopandas (0+unknown)
```
Even when I upgrade it uninstalls "geopandas (0+unknown)" and then installs "geopandas (0+unknown)".

At this very moment, it is not really causing me any problem.  I could see there being issues with future releases or if someone need to install a particular version of geopandas for testing purposes.

**Comment by jorisvandenbossche** [comment]
Ah .. good catch. The same issue seems to appear with conda. Probably I did something wrong with the `versioneer`. Maybe it would be a good idea to release a 0.2.1 that is just the 0.2 release but with a correct version string?

**Comment by darribas** [comment]
@jorisvandenbossche Could the 0.2.1 also include plotting with polygon collections (and maybe prettier defaults)? If that came early enough, I'd be able to use it for [my course](http://darribas.org/gds15/) in september! :)

**Comment by jorisvandenbossche** [comment]
@darribas I wouldn't necessarily wait for that (it's just figuring out what went wrong, and tagging/uploading wheels again). But could certainly try to make a 0.3 with the plotting stuff by september! (I have to take some time to review the collection PR ..)

**Comment by darribas** [comment]
Sounds reasonable. Re. collection plotting, I was tweaking our PySAL implementation last week at SciPy and the performance boost is substantial. I plotted PySAL's `NAT.shp` example in about 7 seconds w/ `geopandas` and in under half a second with PySAL's viz. In case you want to peek, it's in [this branch](https://github.com/darribas/pysal/blob/geotable_plot/pysal/contrib/viz/geotable_plot.ipynb). I can let you guys know once we merge into `PySAL` master.

**Comment by micahcochran** [comment]
> Maybe it would be a good idea to release a 0.2.1 that is just the 0.2 release but with a correct version string?

I've got no problem with that.

**Comment by jorisvandenbossche** [comment]
OK, I uploaded a new version 0.2.1 (just with the version fix) to PyPI! 
Will also update the conda-forge package and the docs website

**Comment by ocefpaf** [comment]
> Will also update the conda-forge package

Did that in https://github.com/conda-forge/geopandas-feedstock/pull/13 :wink:
