### ISSUE TITLE
Is this library abandoned?

### ISSUE THREAD

**Issue by Casyfill** [geopandas/geopandas#365]
Just wondering - there are no commits and no pull requests declined/confirmed. Is it abandoned?

**Comment by jorisvandenbossche** [comment]
No, certainly not, see also https://github.com/geopandas/geopandas/issues/276 (there was even a release less than two months ago). It's more the case of several maintainers not having the bandwidth (anymore) to response timely. (which does not make it less of a problem of course ..)
I will try to answer some of the issue (and your mail) this week.

**Comment by jorisvandenbossche** [comment]
BTW, thanks for your concern (which was maybe not clear from my answer). Also, it can sometimes always help to ping/add a comment to an issue or PR where you are waiting on a response. If you do this in a polite way, it is certainly not seen (IMO) as rude but rather helpful. 
There are oftentimes for a maintainer many issues to keep track of, and a small ping can help remember a certain issue needing attention.

**Comment by Casyfill** [comment]
thank you for your answer, Joris!
And thank your for the advice !
