### ISSUE TITLE
test_geodataframe - NYC Burrough shape file name has changed

### ISSUE THREAD

**Issue by upandacross** [geopandas/geopandas#368]
util.py line 49 calls for nybb_16a.zip - current file name is nybb_16c.zip

Full url:
http://www1.nyc.gov/assets/planning/download/zip/data-maps/open-data/nybb_16c.zip

**Comment by jorisvandenbossche** [comment]
Thanks for noticing! 
We probably better just include a version in our source code, if there is no stable URL. It is not that large.

**Comment by nickwg03** [comment]
I made this pull request (https://github.com/geopandas/geopandas/pull/373) before seeing this issue to fix the file name, but it would probably be much less work to just include nybb_16a.zip in the source code seeing that nybb_16c.zip has shapefiles with differing attributes and/or number of columns. Numerous current tests fail as a result of the changes between the two zip files.

If someone still has a copy of nybb_16a.zip, it would be great to include that file in the source code or in a dropbox somewhere as opposed to nybb_16c.zip, which would require fixing several of the tests.

**Comment by micahcochran** [comment]
Here's a copy of [nybb_16a.zip](https://github.com/geopandas/geopandas/files/555970/nybb_16a.zip)

That should be a stable link ->   https://github.com/geopandas/geopandas/files/555970/nybb_16a.zip

**Comment by nickwg03** [comment]
Okay, I changed the link to the one @micahcochran referenced above in this PR (https://github.com/geopandas/geopandas/pull/373) and that seems to do the trick. Nosetests are passing again.
