### ISSUE TITLE
Several examples in documentation aren't working

### ISSUE THREAD

**Issue by daidoji** [geopandas/geopandas#370]
Stacktraces appear on the readthedocs site in several of the overlay examples.

http://geopandas.org/set_operations.html

**Comment by jorisvandenbossche** [comment]
@daidoji Thanks for noticing. 
Locally they work fine for me (can you check if they work for you as well?). Possibly something to do witht that they take to long for readthedocs, as a `KeyboardInterrupt` is a strange error

**Comment by jdmcbr** [comment]
Closing as duplicate of #345.
