### ISSUE TITLE
bbox filter from read_file doesn't take advantage of fiona filtering

### ISSUE THREAD

**Issue by nickwg03** [geopandas/geopandas#371]
In line: https://github.com/geopandas/geopandas/blob/master/geopandas/io/file.py#L28

The function goes through the trouble of checking if `bbox` is not null, but just calls `f` in `from_features` just the same.

Line 28 just needs to be changed to the intended `f_filt` to return filtered results or non-filtered if no bbox is passed in.

**Comment by jorisvandenbossche** [comment]
@nickwg03 Good catch! Do you want to make a pull request to fix this?

**Comment by nickwg03** [comment]
Sure, I'll make the fix here in the next day or so.

**Comment by MRigal** [comment]
I was about to report the same :)
Thanks @jorisvandenbossche
