### ISSUE TITLE
Dissolve does not work if geopandas is imported after gdal

### ISSUE THREAD

**Issue by Auerilas** [geopandas/geopandas#375]
Hi,

I just ran into a strange bug where the dissolve method will not work properly if geopandas is imported after gdal.

```
import gdal
import geopandas as gpd

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world = world[['continent', 'geometry']]
continents = world.dissolve(by='continent')

                                                                  geometry
continent                                                                 
Africa                                                                  ()
Antarctica                                                              ()
Asia                                                                    ()
Europe                                                                  ()
North America                                                           ()
Oceania                                                                 ()
Seven seas (open ocean)  POLYGON ((68.935 -48.62500000000001, 69.58 -48...
South America                                                           ()
```

versus

```
import geopandas as gpd
import gdal

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world = world[['continent', 'geometry']]
continents = world.dissolve(by='continent')

                                                                  geometry
continent                                                                 
Africa                   (POLYGON ((49.54351891459575 -12.4698328589405...
Antarctica               (POLYGON ((-159.2081835601977 -79.497059421708...
Asia                     (POLYGON ((120.7156087586305 -10.2395813940878...
Europe                   (POLYGON ((-52.55642473001839 2.50470530843705...
North America            (POLYGON ((-61.68000000000001 10.76, -61.105 1...
Oceania                  (POLYGON ((173.0203747907408 -40.9190524228564...
Seven seas (open ocean)  POLYGON ((68.935 -48.62500000000001, 69.58 -48...
South America            (POLYGON ((-68.63401022758316 -52.636370458874...
```

Needless to say, this was causing quite a headache and took me a long time to sort out. Also, it seems to be restricted to cases where MultiPolygons are involved.

Hope this helps!

**Comment by Auerilas** [comment]
I did some more playing around with this, and the order of geopandas import also influences matplotlib.Basemap. If I import gdal BEFORE geopandas, Basemap works fine (but dissolve does not). If I import gdal AFTER geopandas, Basemap gives an Assertion Error and crashes Python (but dissolve functions properly).

I don't know if this is a problem with geopandas or gdal, because even if geopandas is not involved, the order matters (i.e. if I import basemap before gdal, it gives an assertion error). It seems strange to me that the order of import should matter this much.

**Comment by micahcochran** [comment]
Python GDAL wrappers are quirky and very C-like.  Fiona, which geopandas uses to read geospatial data files, uses GDAL C library under its hood.   I suspect there is some interaction going on between those gdal and Fiona libraries.

My advice is to minimize the use python gdal library.

**Comment by sgillies** [comment]
The problem here is known as DLL Hell. Fiona is a C extension that links GDAL, GEOS, PROJ. Python's GDAL bindings have C extensions that link GDAL, GEOS, PROJ. If you import modules that link different library versions or libraries compiled to different specifications, you will experience all sorts of errors. Sometimes it may seem like there is a proper import order to follow, but that is not the case. The only solutions are 1) don't import conflicting extension modules, or 2) get your extension modules exclusively from a single packaging system (conda-forge, say, or build from source on your computer) that keeps the shared libraries coherent.

**Comment by ResidentMario** [comment]
@jorisvandenbossche  I think this should be closed as a wontfix. This is a packaging problem (use `conda` and `conda-forge`!) and not something that can be fixed in the source code.
