### ISSUE TITLE
Hard coded parameters for legend

### ISSUE THREAD

**Issue by bidhya** [geopandas/geopandas#377]
I can make a legend for the categorical variable easily, by just passing legend=True.

However, many parameter here seems to be hardcoded for this legend function. I cannot change the marker,  makersize, or even the placement of the legend. I am interested to know if it is possible to change these hard-coded default values for legend.

**Comment by ResidentMario** [comment]
xref #405 (feature of the port)

**Comment by jdmcbr** [comment]
See #434. `plot` now accepts a `legend_kwds` argument with which you can control legend appearance.
