### ISSUE TITLE
'GIS-like' operations

### ISSUE THREAD

**Issue by carsonfarmer** [geopandas/geopandas#38]
Currently, GeoPandas has several 'overlay' operations (such as `intersect`, `difference`, `union`, etc), which in their current implementation, perform one-to-one spatial overlays on the aligned GeoSeries. While this is useful (particularly if the Indexes of the two GeoSeries' have some useful meaning), many GIS users may find this behavior slightly confusing. Instead, a user may expect to perform a one-to-many overlay comparison between the calling GeoSeries and the input GeoSeries (e.g., for each geometry in the calling GeoSeries, 'difference' it with all 'other' geometries and return the resultant 'differenced' geometry). For this, a spatial index is important to avoid unnecessary overlay comparisons.

A potential API for this type of operation may be something like:

```python
def difference(self, other, by_geom=True):
    """
    Return the set-theoretic difference of each geometry with 
    *other*. This function is used to 'erase' parts of the 
    input geometies that overlap the other geometries.

    Parameters
    ----------
    other: GeoSeries or BaseGeometry
        Series of difference geometry objects
    by_geom: bool
        Should difference be applied by individual geometries,
        or across the whole GeoSeries? `by_geom`=False is the 
        normal GIS-type operation between 'layers', whereas 
        `by_geom`=True is equivalent to geoms - other
    """
...
```

These types of operations would be greatly enhanced (enabled) by a comprehensive spatial index implementation. This would enable something like `obj1.geo_align(obj2)` to be applied before the overlay operation when `by_geom=False`.

**Comment by perrygeo** [comment]
Closing for now. If something's missing from sjoin and overlay, let's bring up a new issue.
