### ISSUE TITLE
Custom color for each polygon

### ISSUE THREAD

**Issue by willhaslam** [geopandas/geopandas#387]

**Comment by willhaslam** [comment]
After spending all day on this I figured it out I could just loop through my categories and set the facevalue and plot them that way

**Comment by jorisvandenbossche** [comment]
@willhaslam With geopandas master, you can actually use the `plot_polygon_collection` function (which is used by the `.plot()` method on a GeoDataFrame under the hood). Something like this then works:

```
from geopandas.plotting import plot_polygon_collection

fig, ax = plt.subplots()
ax.set_aspect('equal')
plot_polygon_collection(ax, gdf['geometry'], gdf['colors'], plot_values=False)
```

Small example with this: http://nbviewer.jupyter.org/gist/jorisvandenbossche/57d392c085901eb4981054402b37b6b1
