### ISSUE TITLE
UTF-8 encoding with to_file() function

### ISSUE THREAD

**Issue by raphadasilva** [geopandas/geopandas#391]
Hi,

I've just used Geopandas to achieve something quite simple : sorting lines in a shapefile by name, then reindex, and finally resave the file. Before the treatment with Gp, my file was encoded with UTF-8.

Two options. In the first one, I add the encoding as an attribute of the from_file() function :

```
from geopandas import GeoDataFrame
gdf = GeoDataFrame.from_file('my_file.shp', encoding = 'utf-8')
[sorting, manipulation, etc]
gdf.to_file('my_file.shp', driver='ESRI Shapefile')
```
But got this error :
`ERROR:Fiona:Failed to encode property 'name' value 'Place Crève Cœur'`

Second case : only one attribute with from_file() function :
```
from geopandas import GeoDataFrame
gdf = GeoDataFrame.from_file('my_file.shp')
[sorting, manipulation, etc]
gdf.to_file('my_file.shp', driver='ESRI Shapefile')
```

And it gave me this error :
`WARNING:Fiona:CPLE_AppDefined in b"One or several characters couldn't be converted correctly from UTF-8 to ISO-8859-1.\nThis warning will not be emitted anymore."`

I looked in the source code and saw that encoding (especially in UTF-8) is not an option of from_file() function. Too bad, I think it will be a very useful update !

NB : sometimes, I just reload the second command in a notebook and the Gp saved my file with UTF-8 encoding. Very strange...

**Comment by jdmcbr** [comment]
@raphadasilva I don't believe that that is because `geopandas` is not passing the `encoding` argument (certainly, `encoding` is passed with `**kwargs` in both `to_file` and `read_file` in the most recently released `geopandas`). I think the discussion in https://github.com/Toblerity/Fiona/issues/510 may be useful.
