### ISSUE TITLE
No easy way to get geometry length/area in metric units?

### ISSUE THREAD

**Issue by cauebs** [geopandas/geopandas#397]
I don't quite understand projections and such, but I tried some things and found no easy way to do this.
I ended up calculating the great_circle distance from each point in the geometry to the next.
So, is there a better way to do this already?
Thanks in advance :)

**Comment by perrygeo** [comment]
Projecting your data from it's original coordinate reference system to another (in metric units) is the mechanism to accomplish this. See http://geopandas.org/projections.html#re-projecting
