### ISSUE TITLE
Plotting choropleth malfunctions when NaN values are present

### ISSUE THREAD

**Issue by jdcaballerov** [geopandas/geopandas#402]
Having NaN's causes malfunctioning of choropleths .  When using quantiles as scheme some values are omitted, with fisher_jenks there are cases where no breaks are computed.

**Comment by jorisvandenbossche** [comment]
@jdcaballerov Can you give a small example?

**Comment by jdcaballerov** [comment]
I have listings (points)  with a column loaded with a urban_sector (census tract id: URBID)

Then new column is added on the geopandas.geodataframe.GeoDataFrame (name: tracts) with a normal counts procedure  as follows:

`tracts['count'] = tracts['URBID'].map(listings['URBID'].value_counts())
`

a choropleth is generated with the following code:

```
f = plt.figure(figsize=(12, 12))
ax = f.gca()
kw = dict(column='counts', k=5, cmap="Blues", alpha=1, legend=True, edgecolor='gray', linewidth=0.5)
tracts.plot(scheme='fisher_jenks', ax=ax, **kw)
ax.set_axis_off()
```

Then the first of the [Images](https://imgur.com/a/HeGkr) is generated, if the tracts line is made to fillna as follows:

`tracts['count'] = tracts['URBID'].map(listings['URBID'].value_counts()).fillna(0)
`
 then sencond of the [Images](https://imgur.com/a/HeGkr) is generated as is the expected result.

**Comment by ljwolf** [comment]
Pretty sure this is due to the way PySAL handles missing values:

```python
>>> import pysal as ps

>>> ary = np.random.normal(0,1,size=100)
>>> ary = np.concatenate((ary, [np.nan]*50))

>>> ps.Quantiles(ary, k=10)

               Quantiles                
 
Lower            Upper             Count
========================================
         x[i] <= -1.253               75
-1.253 < x[i] <= -0.839               15
-0.839 < x[i] <= -0.420               15
-0.420 < x[i] <= -0.011               15
-0.011 < x[i] <=  0.341               15
 0.341 < x[i] <=  1.090               15
 1.090 < x[i] <=    nan                0
   nan < x[i] <=    nan                0
   nan < x[i] <=    nan                0
   nan < x[i] <=    nan                0

>>> ps.Fisher_Jenks(ary, k=4)
            Fisher_Jenks           
 
Lower          Upper             Count
======================================
      x[i] <= nan               150
nan < x[i] <= nan                 0
nan < x[i] <= nan                 0
nan < x[i] <= nan                 0
```

Maybe, before classification, these could get assigned into their own class, and then the remainder classified?

**Comment by jdcaballerov** [comment]
Exactly, that's how the values usually show up.

**Comment by jorisvandenbossche** [comment]
I think this is fixed by https://github.com/geopandas/geopandas/pull/1156 by masking out the missing values before plotting / passing to mapclassify (and it includes a way to have a different styling for the missing values as well)
