### ISSUE TITLE
Drop python 2.6 / 3.3 support

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#407]
We currently still have a python 2.6 and 3.3 build on travis (which are currently failing because latest numpy dropped support for those python versions: https://docs.scipy.org/doc/numpy-dev/release.html#numpy-1-12-0-release-notes). Also latest pandas does not support 3.6 and 3.3 anymore.

Any objections to removing support here as well?

(Note this is theoretically not necessary, as we support also older versions of numpy/pandas that do support 2.6/3.3)

**Comment by kjordahl** [comment]
@jorisvandenbossche no objections from me for dropping Python 2.6/3.3 support. It entirely makes sense to follow the numpy and pandas projects here.

**Comment by jorisvandenbossche** [comment]
We can probably at the same time also bump the matplotlib and pandas versions (currently testing matplotlib 1.2.3 and 0.15.2)
