### ISSUE TITLE
to_json should either include CRS to convert to wgs84

### ISSUE THREAD

**Issue by wassname** [geopandas/geopandas#412]
Geopandas dataframes can be in any CRS, but when exported to geojson the CRS is not exported. So we should either export the CRS or convert to the default (wgs84 according the geojson spec).

What do you think?

**Comment by jorisvandenbossche** [comment]
That sounds like a good idea. Specification is here: http://geojson.org/geojson-spec.html#coordinate-reference-system-objects. The main question will be how to convert the crs in an appropriate object/string to put in the json.

Do you know if this is supported for reading geojson?

**Comment by wassname** [comment]
I agree it's hard to convert from a pyproj projections to either a link or named CRS like in the geojson spec. The other approach is easy and standards complaint.

If you look at the [2016 geojson spec](https://tools.ietf.org/rfc/rfc7946.txt )

> Specification of coordinate reference systems has been removed,
>       i.e., the "crs" member of [GJ2008] is no longer used.

They recommend not using a CRS (doesn't seem very future proof when we upgrade from wgs84 as the world standard), which is easy for us to implement. If there is a CRS defined we use to_crs(epsg=4326) when exporting. And when importing from geojson we use epsg=4326 as the default. I can make a PR for this if you like?

**Comment by sgillies** [comment]
@jorisvandenbossche I'd like to remind you that https://tools.ietf.org/html/rfc7946 is the official GeoJSON spec.

@wassname when WGS84 is no longer the world standard used by most commercial GPS devices, RFC 7946 will be obsoleted and a new RFC will be published.

**Comment by rutgerhofste** [comment]
Hi All, i would recommend to stick with the official geoJSON spec. This improves integration with other packages such as Mapbox / Earth Engine.

**Comment by jorisvandenbossche** [comment]
Yes, I don't think there is disagreement on sticking to the official GeoJSON spec (my comment above was based on looking at the old spec ..). 
So PRs are welcome!

(note that in the end, it is of course still the final responsibility of the user, because if there is no CRS defined for the data, geopandas can also not convert it to WGS84 and you can still write 'invalid' geojson)

**Comment by martinfleis** [comment]
@astrojuanlu #416 was merged.

**Comment by jorisvandenbossche** [comment]
I does not _necessarily_ close this issue though. While we decided to not reproject to WGS84 by default (but provide a keyword to do it), we still don't include the original CRS in the geojson output.

**Comment by martinfleis** [comment]
Let's reopen it then and close with #2151.
