### ISSUE TITLE
Leverage Shapely Speedups?

### ISSUE THREAD

**Issue by kuanb** [geopandas/geopandas#417]
From http://toblerity.org/shapely/manual.html#performance:

```
>>> from shapely import speedups
>>> speedups.available
True
>>> speedups.enable()
```

It appears that this has the potential to be useful in improving performance times for geometric operations in Geopandas. Two questions:

1. Is this assumption correct?
2. If so, how might one best go about implementing it to improve, say, the `sjoin` or `buffer` operations? Would a simple `speedups.available` check and attempt to `enable()` be an acceptable modification? Would I be missing something critical?

**Comment by nickeubank** [comment]
I'm not sure how much those actually offer in terms of speed ups unfortunately. Here's a little test of my own (on a 8-core mac):

![screen shot 2017-05-02 at 7 38 35 pm](https://cloud.githubusercontent.com/assets/9683693/25646653/3fdcd126-2f6f-11e7-909f-2ec359523335.png)

**Comment by jorisvandenbossche** [comment]
In the meantime, `shapely.speedups` has been removed in shapely 2.0 and shapely has in general become faster. So closing this issue.
