### ISSUE TITLE
Variable reuse in plot_dataframe function

### ISSUE THREAD

**Issue by Kython89** [geopandas/geopandas#432]
The variable `k` is used as a parameter to the method and then later used for iteration as the key in a `(k, v)` pair if `categorical` is true.  `k` is then passed to pysal assuming that the value is what was passed in when `k` was a parameter.  However `k` is now the last value it was set to while iterating.  The end result is that `k` is either wrong or invalid and the default value of 5 is used in pysal.

**Comment by mlyons-tcc** [comment]
The logic shouldn't even allow categorical and scheme to get set at the same time. PySAL schemes won't work when the data is objects.

If scheme is set, you'd think that the logic would try to cast to float before deciding to switch to categorical mode. And if it does switch to categorical mode, it shouldn't execute the scheme.
