### ISSUE TITLE
Tab completion freezes in Jupyter

### ISSUE THREAD

**Issue by mangecoeur** [geopandas/geopandas#436]
I came across a strange bug using GeoPandas in Jupyter with IPython 6 - when I invoke tab-completion on a GeoDataFrame, it freezes the kernel (stuck in 'busy' mode with 100% CPU). This doesn't happen with a regular pandas DataFrame. No crash so no stack trace unfortunately.

This affects both the latest conda-forge release and installing from the latest commit.

**Comment by ResidentMario** [comment]
I'm not seeing this issue when using IPython 6 on Ubuntu.

**Comment by mangecoeur** [comment]
Apologies this turned out to be a general issue with Jupiter and ipython 6 with large datasets on my machine.

**Comment by jorisvandenbossche** [comment]
@mangecoeur have you reported this to IPython ? Because tab completion should not hang with larger datasets

**Comment by mangecoeur** [comment]
@jorisvandenbossche I didn't report it yet, on inspection it could also be issues in my own environment. Will clean things up on my end and report if still having problems
