### ISSUE TITLE
default plot command is slow

### ISSUE THREAD

**Issue by DOSull** [geopandas/geopandas#439]
This isn't a bug just a known issue. See e.g., 
http://stackoverflow.com/a/33753927
The problem is associated with not using the pyplot collections to perform plotting. I've written code based on the above post as a local workaround, but I'm not enough of a coder for it to be any good for production.
Is there any chance of this being prioritized for near-future releases? The problem is bad enough to make geopandas unattractive as a teaching option for me.

**Comment by jorisvandenbossche** [comment]
In the meantime, this should be improved in master, as now matplotlib Collections are used. So if you want to use this, you can install geopandas master (not too difficult as this is a pure python package), or wait until the next release. 
You are certainly correct that this was a serious impediment on using geopandas.
