### ISSUE TITLE
Line/Polygon to dictionary of point geodataframes

### ISSUE THREAD

**Issue by hal98x** [geopandas/geopandas#446]
I am building some pre-processing routines for 3D visualization of GIS data and I have several line and polygon shapefiles with multiple features that I want to extract the points from and create a dictionary of point geodataframes. The attributes for each point would be copied from the attributes for the feature they originated from. This I suspect is easy to do, but I am not quite sure how to index into the linestring within a geodataframe. Any help would be greatly appreciated. If you would like to get a virtual pat on the back you can go to the following GIS stack exchange question and provide your answer their. 

https://gis.stackexchange.com/questions/238533/how-do-i-extract-points-from-a-linestring-or-polygon-data-frame-and-make-a-dicti

**Comment by ozak** [comment]
@hal98x it sounds like you want to use a spatial join ``gp.tools.sjoin``? I am a bit confused since you talk about points but you say your original shapefiles are polygons and lines. Check out the [docs](http://geopandas.org/mergingdata.html) for the spatial join.

**Comment by hal98x** [comment]
Ozak I figured out a workaround that doesn't use geopandas, but this would be a nice geoprocessing feature to have in documented in geopandas.  

Here is what I am trying to do
1.  read Line or Polygon shapefile with multiple features (geopandas does this easily)
2. extract points from each feature in the geodataframe and store along with attribute data in another geopandas data frame.
3. wrap all feature dataframes into a dictionary with the key  being one of the attributes like name or ID. 

3D software I have needs the points not a linestring so I need to parse the features and extract the points. I like the geodataframe because I can easily add attributes to the data so it would be nice to keep the same format until I am done processing the data.

**Comment by ozak** [comment]
@hal98x I think the ``explode`` function may do what you want.

```python
dataframe.geometry.explode()
```
generates a geopandas series that you should be able to merge with the original one to assign properties you are interested in. You may need to do it more than once if you have different types of geometries and also to go polygon -> lines -> points.

**Comment by hal98x** [comment]
@ozak awesome thank you. Do you know where I can find documentation on the exploded data class and all its methods?

**Comment by ozak** [comment]
@hal98x no idea, but the exploded dataframe is just a pandas dataframe as far as I saw, so you should be able to work on it as in pandas. I think you will just use the ``merge`` function with the ``left_index=True`` and ``right_index=True`` options. You may need to reset one level of the index if I am not mistaken.

**Comment by jdmcbr** [comment]
@hal98x It sounds like `explode` does achieve roughly what you're looking for? There's an open issue (#174) about having `explode` return a new dataframe such that the new, e.g., `Polygon` geometries created from breaking up `MultiPolygon` instances would have the attributes associated with the `MultiPolygon` from which they came. There's also a comment therein with a couple lines for achieving this behavior with the current behavior of `explode`: https://github.com/geopandas/geopandas/issues/174#issuecomment-63126908. I'll close this in favor of that issue, but can re-open this if this is a distinct issue.
