### ISSUE TITLE
Add hatch argument to plot()

### ISSUE THREAD

**Issue by adamboche** [geopandas/geopandas#449]
Some matplotlib components have a [`hatch`](https://matplotlib.org/examples/pylab_examples/hatch_demo.html) argument. If multiple features of a polygon are represented, using color for all of them can be overwhelming, so hatch is useful.

```
ax1.bar(range(1, 5), range(1, 5), color='red', edgecolor='black', hatch="/")
ax1.bar(range(1, 5), [6] * 4, bottom=range(1, 5), color='blue', edgecolor='black', hatch='//')
```
![hatch_demo](https://user-images.githubusercontent.com/19828875/27165059-71379050-5146-11e7-9ae1-0feb328c4752.png)

**Comment by jdmcbr** [comment]
@adamboche This functionality has actually now been implemented (in #267). There has not been a release since that change. In the meantime, if you'd like to use this functionality, you can install from master.
