### ISSUE TITLE
Return `total_bounds` as an array?

### ISSUE THREAD

**Issue by choldgraf** [geopandas/geopandas#458]
Would it be possible to set the `total_bounds` attribute so that it's an array instead of a tuple? E.g., just throw in an `np.array` here:

https://github.com/geopandas/geopandas/blob/46e4033a4ae6a002af9637c894c0e12d37b6487a/geopandas/base.py#L279

The reason for this is that many plotting packages (e.g., cartopy) take bounds in a different order, so it's convenient to be able to do something like `bounds[[0, 2, 1, 3]]`

**Comment by choldgraf** [comment]
(I'm happy to make this PR if folks are friendly to it)

**Comment by jorisvandenbossche** [comment]
I can't think of any problem by doing that? (I mean incompatibilities by assuming a tuple when it will now return an array) 
If so, I am fine with that.

(one thing I think of is that you would now be able to change an element of the returned property (without effect), without it raising an error, like `df.total_bounds[0] = 10`, but that doesn't seem like a major problem)
