### ISSUE TITLE
Expand committers

### ISSUE THREAD

**Issue by mrocklin** [geopandas/geopandas#462]
Of the current PRs it looks like a few are waiting for review.  This is not surprising, reviewing takes time and volunteer time is hard to come by.  

However, given this situation I wonder if it makes sense to expand the list of people with commit rights. This might energize some upcoming developers and keep things moving. 

cc'ing @jorisvandenbossche, who seems to have been doing most of the maintenance recently.

**Comment by mrocklin** [comment]
To be clear, I have no interest or experience to be a committer myself.  However there appear to be a few people who have submitted decent-looking PRs recently that might be considered.

**Comment by jdmcbr** [comment]
I think this is no longer so relevant. :smile:
