### ISSUE TITLE
expose Mapzen Search geocoding service

### ISSUE THREAD

**Issue by drewda** [geopandas/geopandas#468]
GeoPy includes [support](https://github.com/geopy/geopy/pull/183) for geocoding using [Mapzen Search](https://mapzen.com/documentation/search/).

Would be useful to expose this as a provider through `geopandas.geocode`.

**Comment by jorisvandenbossche** [comment]
@drewda that shouldn't be difficult to add. Do you want to make a PR for this?

**Comment by drewda** [comment]
Thank you, @jdmcbr and @jorisvandenbossche!
