### ISSUE TITLE
convex hull not found

### ISSUE THREAD

**Issue by mehdipira** [geopandas/geopandas#483]
I'm trying to do a convex hull on polygon shapefile but I keep getting this error:
AttributeError: 'Series' object has no attribute 'convex_hull'
any ideas?

**Comment by jdmcbr** [comment]
@mehdipira I suspect you've done some sort of operation in pandas that resulted in loss of geometry awareness of your geometry column (e.g., `pd.concat`). It would be easier to be sure with greater detail, including a minimal reproducible example that shows your problem. This sort of

**Comment by mehdipira** [comment]
@jdmcbr Here's the code:
import fiona
from geopandas.geodataframe import GeoDataFrame
burbs = GeoDataFrame.from_file(r'...\LocalityBoundaries.shp')
burbs.to_crs({'init': 'epsg:4326'})
burbs['geometry'].convex_hull

it throws this error:
AttributeError                            Traceback (most recent call last)
<ipython-input-78-1e8561c50e28> in <module>()
----> 1 burbs['geometry'].convex_hull

C:\Anaconda3\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
   2742             if name in self._info_axis:
   2743                 return self[name]
-> 2744             return object.__getattribute__(self, name)
   2745 
   2746     def __setattr__(self, name, value):

AttributeError: 'Series' object has no attribute 'convex_hull'

**Comment by jdmcbr** [comment]
@mehdipira Have you looked to see what `burbs['geometry']` contains?

**Comment by mehdipira** [comment]
@jdmcbr It contains:
0       POLYGON ((114.7375250737649 -26.64195816178604...
1       POLYGON ((113.7713268306901 -23.13518786108191...
2       POLYGON ((114.9914120416768 -34.10011856481477...
3       POLYGON ((115.1991714265167 -34.2762307888874,...
4       POLYGON ((115.1546487683603 -34.13088170022101...
5       POLYGON ((115.1705208101143 -33.71897301625078...
6       POLYGON ((115.1785911998845 -34.27840350392611...
7       POLYGON ((115.2364740250128 -33.6560215564669,...
8       POLYGON ((115.2456949567262 -34.20676505363272...
9       POLYGON ((115.420717309865 -33.6467402471108, ...
10      POLYGON ((115.7215261858759 -33.65685237071236...
11      POLYGON ((115.7573461653938 -33.52139578581377...
12      POLYGON ((115.9254720841552 -33.48040473081322...
13      POLYGON ((115.9021138992239 -33.875545878431, ...
14      POLYGON ((115.9663275059921 -33.66982069767945...
15      POLYGON ((116.023944261573 -34.45334446878487,...
16      POLYGON ((116.1115898978397 -33.97084561724531...
17      POLYGON ((116.182787948969 -33.51277189706553,...
18      POLYGON ((116.0889577673337 -33.8770791520442,...
19      POLYGON ((116.2082454234669 -34.40566975401964...
20      POLYGON ((115.6536370586739 -33.34516020806566...
21      POLYGON ((115.6477219216441 -32.60955197777432...
22      POLYGON ((115.6738406025761 -33.38603908526167...
23      POLYGON ((115.6322183762946 -32.71037846416376...
24      POLYGON ((115.6964956715572 -33.34941926263056...
25      POLYGON ((115.7166907217975 -33.36914436749795...
26      POLYGON ((115.7463606754182 -32.55343165734199...
27      POLYGON ((115.6830008632802 -32.78282244329461...
28      POLYGON ((115.7964021881908 -32.30966819845016...
29      POLYGON ((115.7540494371356 -32.56015944782704...
                              ...                        
1664    POLYGON ((115.8788884137902 -31.86370114558824...
1665    POLYGON ((115.9131709427132 -31.85550710877592...
1666    POLYGON ((115.8885748624376 -31.91525758957586...
1667    POLYGON ((115.9960339628012 -32.17814944564607...
1668    POLYGON ((115.9834932525959 -32.14713060631279...
1669    POLYGON ((116.0219612569435 -32.16573699252955...
1670    POLYGON ((116.0670376655349 -31.86762133377649...
1671    POLYGON ((116.0763673245026 -31.9421988146089,...
1672    POLYGON ((116.1241267523696 -31.9367917606115,...
1673    POLYGON ((116.1536182413012 -31.86332605541991...
1674    POLYGON ((117.4808017396584 -31.64272296854378...
1675    POLYGON ((115.7826097245612 -32.36562413579085...
1676    POLYGON ((115.8336926748369 -32.11339503848328...
1677    POLYGON ((115.8842121656396 -32.21294582714493...
1678    POLYGON ((115.7662459863955 -32.09853822681508...
1679    POLYGON ((115.763599596037 -32.3256711515623, ...
1680    POLYGON ((115.7896970428143 -32.14912375304522...
1681    POLYGON ((115.7643343816114 -32.10991550091622...
1682    POLYGON ((115.8117813880063 -32.2777963188581,...
1683    POLYGON ((115.8985289731939 -32.19412187466071...
1684    POLYGON ((115.8166899702202 -32.14076382439868...
1685    POLYGON ((115.8390021774508 -32.12992883149508...
1686    POLYGON ((115.743551382771 -32.33379832872673,...
1687    POLYGON ((115.8422555293599 -32.17340590310621...
1688    POLYGON ((115.8818418053234 -32.22303871427863...
1689    POLYGON ((115.7663743412732 -32.1510763173963,...
1690    POLYGON ((115.775039832201 -32.11077122338403,...
1691    POLYGON ((115.838540194886 -32.12745895004816,...
1692    POLYGON ((115.8409019777212 -32.23347097070318...
1693    POLYGON ((115.8596086534098 -32.12911883230925...
Name: geometry, dtype: object

**Comment by jorisvandenbossche** [comment]
Hmm, that's a bit strange. Some other questions:

- what is the version of pandas and geopandas? (`pd.__version__`)
- what is the output of `type(burbs)`, `type(burbs.geometry)` and `type(burbs['geometry'])` ?
- does `burbs.convex_hull` work?
- does another simple geometry operation (eg `.area`) work?

In the end, the easies to help would be that you can provide a reproducible example (that we can run as well)

**Comment by mehdipira** [comment]
@jorisvandenbossche 

- what is the version of pandas and geopandas? (pd.__version__) pandas is '0.19.2' and geopandas is '0.2.1'
- what is the output of type(burbs), type(burbs.geometry) and type(burbs['geometry']) ?
type(burbs): geopandas.geodataframe.GeoDataFrame
type(burbs.geometry): geopandas.geoseries.GeoSeries
type(burbs['geometry']): pandas.core.series.Series
- does burbs.convex_hull work? yes, the output is 
0    POINT (114.6321382645443 -26.82723805297927)
1      POINT (113.773676024059 -23.1437607243292)
2    POINT (115.0461052227363 -34.12428942837108)
3    POINT (115.1425622512195 -34.30362308656871)
4    POINT (115.1340954393069 -34.18504649162127)
dtype: object
- does another simple geometry operation (eg .area) work?
no it doesn't.

However, I've found out that when I do by a single index, it works. e.g.;
burbs['geometry'][0].convex_hull or burbs['geometry'][0].area or
burbs['geometry'][1].convex_hull or burbs['geometry'][1].area, ....

**Comment by jorisvandenbossche** [comment]
OK, that is helpful! 
Can you show the output of `burbs._geometry_column_name` ? 
Do you have multiple columns with geometrical objects?

So there is going something wrong when accessing the geometry with the `['geometry']` syntax. 
As when you use the attribute `burbs.geometry` it works fine (which is a good workaround for you now, but of course would be good to understand why this is happening). 

> However, I've found out that when I do by a single index, it works. e.g.;

This is because then you access a single shapely Polygon object, and on this one the `convex_hull` attribute works again

**Comment by mehdipira** [comment]
@jorisvandenbossche 
burbs._geometry_column_name: 'centroid_column'

burbs.columns: Index(['ABS_Number', 'AREA_DERIV', 'DATE_TIME_', 'FEATURE_NU', 'LAND_ID_NU',
       'Legal_area', 'NAME', 'POSTCODE', 'RENDER_NOR', 'USAGE_CODE',
       'geometry', 'land_type', 'centroid_column',  'Area'],
      dtype='object')
![table](https://user-images.githubusercontent.com/14327463/29197432-effe0a3c-7e6d-11e7-9a08-65e78898581a.png)

**Comment by jdmcbr** [comment]
@mehdipira Despite the name, the active `geometry` column is the one named "centroid_column", and the column named "geometry" is not actually treated as a geometric object for operations. See http://geopandas.org/data_structures.html#geodataframe for more information, including how to switch which column is the active geometry.

**Comment by mehdipira** [comment]
@jdmcbr and @jorisvandenbossche Yes, that was the issue. Now by setting the right geometry, all works now. Thank you. I appreciate it.

**Comment by jorisvandenbossche** [comment]
@mehdipira However it is a bit strange how you got those two geometry columns? Did you already have them directly after reading the shapefile? Because that should not be possible I think
