### ISSUE TITLE
Question about overlays

### ISSUE THREAD

**Issue by jliebrand** [geopandas/geopandas#485]
Sorry, wasn't sure where the best place was for this question - it's not an issue or bug.. so feel free to close this and tell me to go elsewhere if this is not the right place for it :-)

I'm feeling a little stupid here, but if I have a df with mixed Polygons and Points, the overlay fails. As it only supports (multi)polygons. But why? Should I filter out Points and handle those differently myself via a spatial join or something?  Just not sure I understand why Points would be treated differently?

**Comment by jorisvandenbossche** [comment]
AFAIK, it is just that the current implementation only supports Polygons. So there is no inherent reason and Points could be supported.

Current workaround could be adding a very small buffer around the points (but of course this could influence the actual result depending on the kind of data)

**Comment by martinfleis** [comment]
Support for all geom types implemented in #1110. Closing.
