### ISSUE TITLE
Update isnull: add isna alias to follow upstream pandas

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#503]
see https://github.com/pandas-dev/pandas/pull/16972

We have an overridden isnull method -> need to update to also include isna

**Comment by jdmcbr** [comment]
@jorisvandenbossche We'll just keep `isnull` indefinitely as an alias (which seems to be what pandas is doing)? It also seems that we need `notnull` and `notna`. As it stands, `notnull` doesn't actually work for empty geometries. I'll put in a PR for this soon.

**Comment by jdmcbr** [comment]
Closed by #517.
