### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_empty' 

### ISSUE THREAD

**Issue by rmmariano** [geopandas/geopandas#511]
Hello everyone,

I'm trying to read a shapefile, but I'm having a little problem...
When I try to reproject the shapefile, it raise an exception. So far, so good, I can reproject with QGIS, so I have did it.
After that I have tried to plot the shapefile, it has "worked". It plot the shapefile, but it raise an exception together...
The error is always: " AttributeError: 'NoneType' object has no attribute 'is_empty' "'
I don't know what mistake I'm doing...

Could someone helps me?

The code is in my account (section Testing GeoPandas): 
https://github.com/rmmariano/CAP386_intro_data_science/blob/dev_rodrigo/projeto/crimes_baltimore/crimes_baltimore.md#testing-geopandas

Thanks in advance,

**Comment by jorisvandenbossche** [comment]
That sounds like: https://github.com/geopandas/geopandas/issues/509

Is it possible you have upgraded shapely to 1.6.0 in the last few days? (or created a new environment which will automatically have installed the latest version)

**Comment by rmmariano** [comment]
Hello jorisvandenbossche,

Thanks for your help.

I had did it and another error has started to appear...
The new error was: "OSError: Could not find libspatialindex_c library file"
I had tried to solve it, following some notes on web, like:
https://github.com/gboeing/osmnx/issues/45
https://github.com/Toblerity/rtree/issues/56
But it has not worked...

So I had tried to install other packages:
http://jspeis.com/installing-rtree-on-mac-os-x/
https://packages.ubuntu.com/trusty/libspatialindex-dev

Well, the second error has stoped of appear, however the old error (AttributeError: 'NoneType' object has no attribute 'is_empty') has came back again...

Somewhere on web has said that the problem can be the version of some packages, like GDAL.
When I had tried to upgrade it, the follow error appears:

    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    extensions/gdal_wrap.cpp:3168:22: fatal error: cpl_port.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of GDAL
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fwqtdm8e/gdal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sgwq5irx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-fwqtdm8e/gdal/

Do you have another idea?

Thanks in advance,

**Comment by jorisvandenbossche** [comment]
> Well, the second error has stoped of appear, however the old error (AttributeError: 'NoneType' object has no attribute 'is_empty') has came back again...

This means that you successfully re-installed libspatialindex, since you don't get the error anymore. The "AttributeError: 'NoneType' object has no attribute 'is_empty'" can only be solved by downgrading shapely, or making sure you do not have missing values in the geometry column, or to wait until a fix for that is made to geopandas (I hope to do that in one of the coming days)

For the gdal issue I can't help

**Comment by rmmariano** [comment]
Hello jorisvandenbossche,

What is the better version of Shapely? 1.5.17? I can downgrade it.
I can wait to fix too, it is not a problem. I'm just testing the geopandas, because I would like to work with it in a Data Science project that I'm doing. In the moment, I'm ploting my shapefiles with the basic of matplotlib.

Thanks in advance.

Regards.

**Comment by jorisvandenbossche** [comment]
Yes, that version of shapely will work fine with current geopandas. 
If you just want to keep working with your current set-up, I think if you do:

```
df = df[df.geometry.notnull()]
```

should make sure you don't have missing values in the geometry column, and then you should also not have those problems.

**Comment by jorisvandenbossche** [comment]
I am going to close this one in favor of issue #509

**Comment by rmmariano** [comment]
Hello jorisvandenbossche,

This piece of code has worked. Thank you so much. 
I will be waiting for the geopandas update.

> I am going to close this one in favor of issue #509

It's all right.

Regards,
