### ISSUE TITLE
DOC: document new plotting features + set_axis_off

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#524]
eg legend=True for colorbar

**Comment by standakozak** [comment]
I would like to document the set_axis_off() method. Should it be mentioned in the docstring of the plot function or in User Guide - Mapping and plotting tools?

**Comment by martinfleis** [comment]
In the user guide. Thanks!

**Comment by martinfleis** [comment]
I think that all these features are now documented.
