### ISSUE TITLE
BUG: facecolor does not work with points

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#526]

**Comment by ustroetz** [comment]
Hi @jorisvandenbossche,

 I tried to reproduce this bug but I couldn't. I created Jupyter Notebook to show the behavior: https://github.com/ustroetz/geopandas/blob/master/examples/plotting.ipynb

If you believe this example adds value, I am happy to submit it as a PR. 

Do you have more information to reproduce the bug you mentioned?

**Comment by jdmcbr** [comment]
@jorisvandenbossche I'm also not sure what this issue is referencing.

**Comment by jorisvandenbossche** [comment]
Hmm, I trying to remember why I opened this ... Given the example of @ustroetz, I can't directly imagine what it could be (might be that it was dependent on the matplotlib version .., although it also seems to be in the tests). 
So let's close. If I do remember again, we can always re-open :-)
