### ISSUE TITLE
Refactor: concat fails with dict crs attribute

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#527]
In the geopandas-cython branch, we added a `geopandas.concat` method that mimicks `pandas.concat`. This method however still fails when the crs attribute is a dict.

See https://github.com/geopandas/geopandas/pull/514

**Comment by jdmcbr** [comment]
@jorisvandenbossche I think I'm missing something. My reading of this is that when combining two (or more) frames with `pd.concat`, that operation would fail if the frame has a `crs` attribute with type dict. So I was expecting the following to fail, but it worked fine so far as I can see:

```
In [17]: gdf = gpd.read_file(gpd.datasets.get_path('nybb'))

In [18]: gdf.crs
Out[18]: 
{'datum': 'NAD83',
 'lat_0': 40.16666666666666,
 'lat_1': 40.66666666666666,
 'lat_2': 41.03333333333333,
 'lon_0': -74,
 'no_defs': True,
 'proj': 'lcc',
 'units': 'us-ft',
 'x_0': 300000,
 'y_0': 0}

In [19]: pd.concat([gdf, gdf])
Out[19]: 
   BoroCode       BoroName     Shape_Leng    Shape_Area  \
0         5  Staten Island  330470.010332  1.623820e+09   
1         4         Queens  896344.047763  3.045213e+09   
2         3       Brooklyn  741080.523166  1.937479e+09   
3         1      Manhattan  359299.096471  6.364715e+08   
4         2          Bronx  464392.991824  1.186925e+09   
0         5  Staten Island  330470.010332  1.623820e+09   
1         4         Queens  896344.047763  3.045213e+09   
2         3       Brooklyn  741080.523166  1.937479e+09   
3         1      Manhattan  359299.096471  6.364715e+08   
4         2          Bronx  464392.991824  1.186925e+09   

                                            geometry  
0  (POLYGON ((970217.0223999023 145643.3322143555...  
1  (POLYGON ((1029606.076599121 156073.8142089844...  
2  (POLYGON ((1021176.479003906 151374.7969970703...  
3  (POLYGON ((981219.0557861328 188655.3157958984...  
4  (POLYGON ((1012821.805786133 229228.2645874023...  
0  (POLYGON ((970217.0223999023 145643.3322143555...  
1  (POLYGON ((1029606.076599121 156073.8142089844...  
2  (POLYGON ((1021176.479003906 151374.7969970703...  
3  (POLYGON ((981219.0557861328 188655.3157958984...  
4  (POLYGON ((1012821.805786133 229228.2645874023...  
```

**Comment by jorisvandenbossche** [comment]
@jdmcbr sorry for the issue without much explanation (I was quickly adding a bunch of possible issues to work on for the euroscipy sprint) 
The issue is about the geopandas-cython branch, where we added a `geopandas.concat` method that mimicks `pandas.concat`, and this method has that issue

**Comment by jorisvandenbossche** [comment]
Updated the description. I used 'refactor' in the issue title, but maybe we need a better tag to make clear the issue is related to the cython refactor? (eg putting "[geopandas-cython]" in the issue title, or using a github label for it)

**Comment by mrocklin** [comment]
I think I've already resolved this in
https://github.com/geopandas/geopandas/commit/2270a4ff6a9812bddc7cfb2301dfd95b5d5204c8

I've been pushing directly to the geopandas-cython branch from time to
time.  I apologize for the stealth workflow

**Comment by jorisvandenbossche** [comment]
Indeed closed by https://github.com/geopandas/geopandas/commit/2270a4ff6a9812bddc7cfb2301dfd95b5d5204c8
