### ISSUE TITLE
TST: create test suite for overlay based on wiki example

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#533]
See the wiki example here: http://wiki.gis.com/wiki/index.php/Overlay (right side there is a figure with all results for the overlay of two shapes for the different types)

It would be nice to convert that example to some geopandas code to emulate it, and then convert it to tests (to have a better test suite for the `overlay` function)

**Comment by dapp1990** [comment]
I'd like to tackle this issue. Is there any further information do I need to know before starting the implementation?

**Comment by jorisvandenbossche** [comment]
@dapp1990 that would be great!

I don't think so, just that it *might* be that some of the tests you are going to write will fail (just so you know it is not *necessarily* an error in your code, although I expect this not being the case). 
I would start with just trying to mimic the examples from wiki page (and you can already share that here if you want), en then afterwards convert it into tests.

**Comment by dapp1990** [comment]
Thanks for the info @jorisvandenbossche, I'm starting then.

**Comment by dapp1990** [comment]
Hey @jorisvandenbossche ,

Here are my examples. If you give green light and I can convert them in proper tests, using overlay function.

```python
from shapely.geometry import box
import matplotlib.pyplot as plt

a = GeoDataFrame([{'geometry': box(0, 2, 6, 6)}])

b = GeoDataFrame([{'geometry': box(4, 0,10,4)}])

intersection = GeoDataFrame([{'geometry': box(4, 2,6,4)}])

union = GeoDataFrame([{'geometry': box(0, 2, 6, 6)}, {'geometry': box(4, 0,10,4)}])

a_difference_b = GeoDataFrame([{'geometry': box(0, 2, 4, 6)}, {'geometry': box(4, 4,6,6)}])

b_difference_a = GeoDataFrame([{'geometry': box(4, 0, 6, 2)}, {'geometry': box(6, 0,10,4)}])

symmetric_difference = GeoDataFrame([{'geometry': box(0, 2, 4, 6)}, {'geometry': box(4, 4,6,6)}, {'geometry': box(4, 0, 6, 2)}, {'geometry': box(6, 0,10,4)}])

a_identity_b = GeoDataFrame([{'geometry': box(0, 2, 6, 6)}])

b_identity_a = GeoDataFrame([{'geometry': box(4, 0,10,4)}])
```

Here the GeoDataFrames on plots:

![a](https://user-images.githubusercontent.com/5913521/34909764-93d2e5d4-f8a7-11e7-8fff-442b5758d77d.png)
![b](https://user-images.githubusercontent.com/5913521/34909765-9c29713a-f8a7-11e7-832e-365e0d1c4ff3.png)
![intersection](https://user-images.githubusercontent.com/5913521/34909766-a326a4a8-f8a7-11e7-8eac-55fc126a1af1.png)
![union](https://user-images.githubusercontent.com/5913521/34909768-ae18ea4c-f8a7-11e7-8295-22df360d917d.png)
![a difference b](https://user-images.githubusercontent.com/5913521/34909770-b3bf391a-f8a7-11e7-99ca-79945b32eb83.png)
![b difference a](https://user-images.githubusercontent.com/5913521/34909771-b8fd7590-f8a7-11e7-83b8-546eeb825056.png)
![symmetric difference](https://user-images.githubusercontent.com/5913521/34909776-c169b90a-f8a7-11e7-9bda-be1ef4045516.png)
![a identity b](https://user-images.githubusercontent.com/5913521/34909777-c823c1c8-f8a7-11e7-85cc-2398e5676d18.png)
![b identity a](https://user-images.githubusercontent.com/5913521/34909778-cc9e673a-f8a7-11e7-80fc-b376948db1db.png)

**Comment by dapp1990** [comment]
Hi @jorisvandenbossche,

I've started to implement the tests and I came out with the following code

''''
class TestOverlayWikiExample:

    def setup_method(self):
        self.layer_a = GeoDataFrame([{'geometry': box(0, 2, 6, 6)}])

        self.layer_b = GeoDataFrame([{'geometry': box(4, 0, 10, 4)}])

        self.intersection = GeoDataFrame([{'geometry': box(4, 2, 6, 4)}])

        self.union = GeoDataFrame(
            [{'geometry': box(0, 2, 6, 6)}, {'geometry': box(4, 0, 10, 4)}])

        self.a_difference_b = GeoDataFrame(
            [{'geometry': box(0, 2, 4, 6)}, {'geometry': box(4, 4, 6, 6)}])

        self.b_difference_a = GeoDataFrame(
            [{'geometry': box(4, 0, 6, 2)}, {'geometry': box(6, 0, 10, 4)}])

        self.symmetric_difference = GeoDataFrame(
            [{'geometry': box(0, 2, 4, 6)}, {'geometry': box(4, 4, 6, 6)},
             {'geometry': box(4, 0, 6, 2)}, {'geometry': box(6, 0, 10, 4)}])

        self.a_identity_b = GeoDataFrame([{'geometry': box(0, 2, 6, 6)}])

        self.b_identity_a = GeoDataFrame([{'geometry': box(4, 0, 10, 4)}])

    def test_intersection(self):
        df_result = overlay(self.layer_a, self.layer_b, how="intersection")
        assert df_result.geom_equals(self.intersection).bool()

    def test_union(self):
        df_result = overlay(self.layer_a, self.layer_b, how="union")
        assert df_result.geom_equals(self.union).bool()

    def test_a_difference_b(self):
        df_result = overlay(self.layer_a, self.layer_b, how="difference")
        assert df_result.geom_equals(self.a_difference_b).bool()

    def test_b_difference_a(self):
        df_result = overlay(self.layer_b, self.layer_a, how="difference")
        assert df_result.geom_equals(self.b_difference_a).bool()

    def test_symmetric_difference(self):
        df_result = overlay(self.layer_a, self.layer_b,
                            how="symmetric_difference")
        assert df_result.geom_equals(self.symmetric_difference).bool()
''''

Unfortunately all of them are failing, except ´test_intersection´.  You mentioned that some of my tests might fail. So I just wondering whether I correctly implemented or not.

Thanks in advance.

**Comment by jorisvandenbossche** [comment]
@dapp1990 That looks like a good start!

> So I just wondering whether I correctly implemented or not.

I ran your code and only looked at one failing case: union. In this case it is your construction code. You made up an expected result as a dataframe with two rows with the two original polygons in layer_a and layer_b. However, in the union, we effectively want a different result (have a look at what `overlay` currently does) where the overlapping and non-overlapping parts between the geometries as splitted. 
If you visualize `df_result.plot(cmap='Set1')` (with different colors for each geometry) you will better see what I mean.

**Comment by abhinav9414** [comment]
May I try to do this.

**Comment by martinfleis** [comment]
@abhinav9414 Yes, thank you! 

I think it is fair to say that the previous attempt is not going to go forward after 3 years :).

**Comment by abhinav9414** [comment]
thank you, I am starting this issue :)

**Comment by abhinav9414** [comment]
Hi @martinfleis,
I was working on the issue for past few days and I had a question related to same. Where do I add these tests? Does it go in `tests/test_overlay.py`, `tools/test/test_tools.py` or do I create a new file in the `tools/test` folder itself? I am almost done with writing test and will open a PR soon.

**Comment by martinfleis** [comment]
@abhinav9414 `tests/test_overlay.py ` will be a good place. Thanks!
