### ISSUE TITLE
ENH: expose all geopy geocoding services

### ISSUE THREAD

**Issue by jdmcbr** [geopandas/geopandas#539]
The current behavior of the geocoding (and reverse) functionality in GeoPandas takes a service provider as a string, which is then mapped to a `geopy.geocoders` instance with a hard coded dict. Instead of taking a string (and, for at least some deprecation time period, in addition), we could take a `geopy.geocoders` class as an argument. In addition to providing access to lots of services (in addition to Mapzen, explicitly requested in #468), when `geopy` adds or removes services, we wouldn't need to worry about keeping up. The different services already accept different args/kwargs, and thus the user must already have familiarity with the different services if, e.g., using an API key for the service. I'd suggest still leaving GoogleV3 as the default, so the experience for most users wouldn't change at all. In general, the call would change from

    df = gpd.tools.geocoding.reverse_geocode([Point(-71.0594869, 42.3584697), Point(-77.0365305, 38.8977332)], 
                                              provider='nominatim')

to 

    df = gpd.tools.geocoding.reverse_geocode([Point(-71.0594869, 42.3584697), Point(-77.0365305, 38.8977332)], 
                                              provider=geopy.geocoders.Nominatim)

Anything I'm missing here? If not, happy to implement this change.

**Comment by jorisvandenbossche** [comment]
Yes, certainly OK to start allowing the actual class instead of string. 
I *think* I would leave the current strings as is, as it otherwise would break a lot of code and is somewhat convenient, but we can also deprecate.
