### ISSUE TITLE
Unable to load GeoDataFrame from geodatabase file

### ISSUE THREAD

**Issue by sr-murthy** [geopandas/geopandas#540]
I am getting a strange timeout error when trying to load a geodatabase file using `geopandas` (version `0.2.1`) inside a Docker container (image has Ubuntu 16.04 LTS, Python version 2.7.13.

    In [1]: import geopandas
    In [2]: import os
    In [3]: polys = geopandas.GeoDataFrame.from_file(os.path.join('/my/data/folder/', 'VRG_01.gdb'), layer='VRG')
    Killed
    root@75d68acd876e:#

I see the `Killed` message on the console about 5-6 minutes after the `geopandas.GeoDataFrame.from_file()` call.

Previously this used to work, and there is nothing wrong with the underlying data file. I've tried upgrading `geopandas` to `0.3.0`, which is the latest on PyPi, and also Ubuntu (to 17.04), but I have the same problem.

**Comment by jorisvandenbossche** [comment]
> Previously this used to work

Do you know what changed since then? Did you eg upgrade fiona or gdal versions?

**Comment by sr-murthy** [comment]
No, nothing changed so far as I know - the `requirements.txt` was as follows:

    geopandas==0.2.1
    pandas==0.19.2
    Rtree==0.8.3

When I first noticed the issue with that timeout happening (on iPython in an Ubuntu 16.04 container) I manually upgraded `geopandas` to the latest `0.3.0`, but I don't see how that could have caused issues. I know that `fiona` is a dependency of `geopandas` and will be whatever version that `geopandas` requires.

**Comment by jorisvandenbossche** [comment]
>  I know that fiona is a dependency of geopandas and will be whatever version that geopandas requires.

`fiona` is the library that does the import/export, so probably related to why this is failing or not. So I think it is important to see whether this version changed. Geopandas does not require any specific version, and it is quite possible that fiona got updated when geopandas did not.

**Comment by sr-murthy** [comment]
The latest version of `Fiona` is `1.7.9.post1`, but I did not update this in my local development system, where the problem is, or in the test environment where it does work. I will have to check on the what the differences are, but we are not specifically installing a version of `Fiona` in either - it's just whatever is installed as part of `geopandas`.

**Comment by jorisvandenbossche** [comment]
> we are not specifically installing a version of Fiona in either - it's just whatever is installed as part of geopandas.

Yes, I understand that, but still it is probably the version of `fiona` that is relevant to this issue (when installing geopandas, it will just install the latest available `fiona`, but `fiona` can also get updated due to other updates independent from geopandas)

What I would suggest is to try opening the file with `fiona` itself and see if that works:

```
with fiona.open(os.path.join('/my/data/folder/', 'VRG_01.gdb'), layer='VRG') as src:
    # just checking meta data
    print(src.meta)
    # actually reading first record
    print(next(src)
```

to further investigate what the issue could be.

**Comment by jorisvandenbossche** [comment]
@sr-murthy do you still have this issue? Do you also get this error when running the small snippet above?

**Comment by sr-murthy** [comment]
Hi, I haven't tested it since first reporting this issue. It was probably a memory problem, and I am not able to reproduce it.

**Comment by jorisvandenbossche** [comment]
OK, good to know!

**Comment by mluck** [comment]
The `Killed` message is a Docker out-of-memory error. I have gotten this with large files using geopandas `.read_file()` and `.to_crs()`. But if I increase the memory allocated to Docker some of the `Killed` messages can be avoided.
