### ISSUE TITLE
Support for 'virtual file systems' (e.g. zip, gzip, tar)

### ISSUE THREAD

**Issue by jreades** [geopandas/geopandas#541]
It looks like `fiona` > 1.6 has support for virtual file systems built from compressed archives but that this has not been enabled in geopandas (or, at least, I can't figure out the magical incantation that would do this). 

Since [`geopandas.read_file()`](https://github.com/geopandas/geopandas/blob/master/geopandas/io/file.py) is simply forwarding open calls to `fiona` it should be _fairly_ straightforward to add this to `geopandas`, although I happen to think that the `fiona` syntax is pretty horrendous. 

I think that I _could_ do this via a PR but don't think it's appropriate to simply offer what could be a major change without consulting first. If we were to stick to the `fiona` syntax then something like this should work:

```python
gdf = gpd.read_file(
                 '/OA/OA_2011_London_gen_MHW.shp', 
                 vfs=os.path.join('zip://',os.getcwd(),'Data','OA.zip')
)
```

But a more user-friendly (if potentially confusing for users who are familiar with low-level `fiona` commands) approach might be:
```python
gdf = gpd.read_file(
                  os.path.join('zip://',os.getcwd(),'Data','OA.zip'), 
                  layer='OA_2011_London_gen_MHW.shp')
```
`layer` might have specific meanings to you guys and to fiona so perhaps that's not the best approach, but it would be a little more straightforward if there were some simple matching on the name of the file rather than requiring the user to first do `zip -l OA.zip` to figure out what's there and how to refer to it correctly using an absolute path (which the vfs approach technically requires).

**Comment by jreades** [comment]
Sorry, here's the file I'm using.
[OA.zip](https://github.com/geopandas/geopandas/files/1280120/OA.zip)

**Comment by sgillies** [comment]
@jreades I'd like to point out that the Fiona 1.7 syntax above is going away in favor of the syntax employed in Rasterio today. In 1.8, the URI for your zipped shapefile will be `zip:///path/to/OA.zip!OA/OA_2011_London_gen_MHW.shp` (following the lead of Apache VFS URIs). For zipfiles containing exactly one shapefile layer with no directories, the URI could simply be `zip:///path/to/OA.zip` because Fiona will default to the first (and only) layer in a zip archive.

I recommend that GeoPandas not use the existing `vfs` argument for `fiona.open()` or at least be aware that there will be a deprecation warning about it in 1.8.

**Comment by jreades** [comment]
@sgillies: Well that looks like a substantially nicer syntax. It looks like fiona is at 1.7.9, what's the timetable for releasing 1.8? If that's the schema then I'd _guess_ it might 'just work' with geopandas since the whole path/URL is forwarded directly to fiona without any validation that I can see.

**Comment by jorisvandenbossche** [comment]
That's good news that `fiona` will get a more user-friendly interface for zip files! (as I also struggled a bit with it earlier).

@jreades Note that some things already work without using the `vsf` keyword. Eg: 

```
In [9]: path = geopandas.datasets.get_path('nybb')

In [10]: path
Out[10]: 'zip:///home/joris/miniconda3/lib/python3.5/site-packages/geopandas/datasets/nybb_16a.zip'

In [11]: geopandas.read_file(path)
```

But (I think) that is only for zip files with no subdirs and a single shapefile.

> I recommend that GeoPandas not use the existing vfs argument for fiona.open()

We are not doing that, just passing through kwargs. So users he make use of this passing through and use `vsf` will just get the deprecation warnings from fiona, which is OK I think.

**Comment by martinfleis** [comment]
Zip files are now fully supported through fiona, including folders and different files (https://geopandas.readthedocs.io/en/latest/io.html). Same applies for tar. Issue resolved.
