### ISSUE TITLE
Should dropping the geometry column produce a Pandas dataframe?

### ISSUE THREAD

**Issue by mrocklin** [geopandas/geopandas#544]
If I do an operation with loses the geometry column like 

    df[['a', 'b', 'c']]

or 

    df.drop('geometry')

Should I get back a vanilla Pandas DataFrame?

To be clear, the current answer is "no".  I'm curious if there is value to changing the current behavior.

**Comment by jorisvandenbossche** [comment]
Yes, it seems to make sense to me to return a DataFrame in those occasions, as it would otherwise be an invalid GeoDataFrame anyhow.

**Comment by ResidentMario** [comment]
A `GeoDataFrame` with `geometry=[]` is still a `GeoDataFrame`. I wouldn't say it's invalid, no? And implicit type mutation strikes me as bad.

If you really want it, `pd.DataFrame(gdf.values)` will give it to you.

**Comment by jorisvandenbossche** [comment]
This is similar to selecting a single column from a GeoDataFrame: this also does not give a GeoSeries, but a Series:

```
In [5]: df = geopandas.GeoDataFrame({'a': [1, 2], 'b': [3, 4]}, geometry=[Point(1, 1), Point(2, 2)])

In [6]: df['a']
Out[6]: 
0    1
1    2
Name: a, dtype: int64

In [7]: type(df['a'])
Out[7]: pandas.core.series.Series
```

and I think this makes sense (only getting the geometry column will give a GeoSeries). Given this, I think it also makes sense to return a DataFrame for multiple columns (that do not contain the geometry column):

```
In [8]: df[['a', 'b']]
Out[8]: 
   a  b
0  1  3
1  2  4

In [9]: type(df[['a', 'b']])
Out[9]: pandas.core.frame.DataFrame
```

Actually, @mrocklin I get here already a DataFrame. Did you test this on master or on the geopandas-cython branch ?

> A GeoDataFrame with geometry=[] is still a GeoDataFrame. I wouldn't say it's invalid, no?

Not sure what you mean with `geometry=[]` ? The question is here is not about "no data in the geometry column" but "no geometry column" which is somewhat different.

You can actually create such a GeoDataFrame without geometry with the constructor and not passing any geometries (but then you get an error once you do something geometrical):

```
In [12]: df = geopandas.GeoDataFrame({'a': [1, 2], 'b': [3, 4]})

In [13]: df
Out[13]: 
   a  b
0  1  3
1  2  4

In [14]: type(df)
Out[14]: geopandas.geodataframe.GeoDataFrame

In [15]: df.geometry
...
AttributeError: No geometry data set yet (expected in column 'geometry'.

In [16]: df.geom_type
...
AttributeError: No geometry data set yet (expected in column 'geometry'.

**Comment by ResidentMario** [comment]
w.r.t. geometry I meant a `gpd.GeoDataFrame(geometry=[])` declaration. In this case the geometry column is set, but set to an empty list. All functions behave as expected.

You can get a construct with actual length using:

    gpd.GeoDataFrame({'a': [1], 'b': [2]}, geometry=[None]).geometry

Admittedly these are tangential edge cases.

I strongly associate `GeoSeries` with geometries and didn't even realize constructs like `gpd.GeoSeries(['a', 'b'])` were legal. Very well, I suppose you are right.

**Comment by jorisvandenbossche** [comment]
Ah, yes, an empty GeoDataFrame (no rows) can certainly exist. But in that case it also has the geometry column:

```
In [160]: df = geopandas.GeoDataFrame({'a': [], 'b': []}, geometry=[])

In [161]: df
Out[161]: 
Empty GeoDataFrame
Columns: [a, b, geometry]
Index: []

In [162]: type(df)
Out[162]: geopandas.geodataframe.GeoDataFrame

In [163]: df.columns
Out[163]: Index(['a', 'b', 'geometry'], dtype='object')
```

So I was rather thinking about the case there is data, but no geometry column:
```
In [165]: df = geopandas.GeoDataFrame({'a': [1, 2], 'b': [3, 4]})

In [166]: df
Out[166]: 
   a  b
0  1  3
1  2  4

In [167]: type(df)
Out[167]: geopandas.geodataframe.GeoDataFrame
```

This last one could be a DataFrame.

> gpd.GeoDataFrame({'a': [1], 'b': [2]}, geometry=[None]).geometry

This is fine I think, since we support missing values in the geometry column. So this is such a case.

> didn't even realize constructs like gpd.GeoSeries(['a', 'b']) were legal.

Yes, that is a similar case. Currently that returns a GeoSeries, but in the cython refactor branch it makes sense to return a Series (but currently raises error, see discussion here: https://github.com/geopandas/geopandas/issues/473#issuecomment-329620408)

**Comment by jwilson8767** [comment]
Personally, I don't want things to change types unexpectedly. If I want a DataFrame I can already do:
`df = pd.DataFrame(gdf[[col for col in gdf.columns if col != gdf._geometry_column_name]])`

I would be open to having a helper method to get a dataframe without the geometry column though.

**Comment by jorisvandenbossche** [comment]
@jwilson8767 The question is to what extent is it *useful* that it stays a GeoDataFrame, as none of the extra geometry-related methods will work, and possibly also some over the methods of DataFrame that we override might break if there is no geometry.

**Comment by kuanb** [comment]
Perhaps instead of "automatically" converting to a DataFrame, would adding a `.to_dataframe()` (maybe `.to_pandas()` or something) method be acceptable? 

This would be similar to the pattern present on Series, which allows them to be turned into dataframe with `.to_frame()`.

**Comment by mxfh** [comment]
> Perhaps instead of "automatically" converting to a DataFrame, would adding a `.to_dataframe()` (maybe `.to_pandas()` or something) method be acceptable?
> 
> This would be similar to the pattern present on Series, which allows them to be turned into dataframe with `.to_frame()`.

Support to have a straight forward and descriptive reverse method.

Like in the NYC TAXI demo, where you could only temporarily want a geometry to do the spatial joins, but you are happy with only IDs of Areas afterwards.

https://gist.github.com/jorisvandenbossche/67be41a246c1281d7046b31690988321
