### ISSUE TITLE
Shell is not a LinearRing Error

### ISSUE THREAD

**Issue by TCurran4589** [geopandas/geopandas#556]
Hello - I tried opening a shp file with geopandas and I keep getting thrown the error "Shell is not a linearring" error, but when I open the shape file in QGIS and R the shape file appears. Suggestions?

**Comment by sgillies** [comment]
@TCurran4589 that error message is from the GEOS library. Is there any chance you can attach or link to the shapefile so that we can debug this?

**Comment by TCurran4589** [comment]
sure - https://www2.census.gov/geo/tiger/TIGER2016/TRACT/tl_2016_17_tract.zip

**Comment by TCurran4589** [comment]
I resolved this issue - I believe it had to do with geopandas and how it was installed. I resolved it by using:

`conda remove geopandas`

I originally installed via conda-forge channel

and then installing via pip:

`pip install geopandas`

I also went through and installed some packaged via homebrew, but I am not sure if that made a difference.

Thnaks!

**Comment by jorisvandenbossche** [comment]
@TCurran4589 It's a bit strange that it makes a difference (as geopandas is just a pure python package). Do you know whether in the `pip install geopandas` it reinstalled other dependencies as well?

**Comment by jerrykhong** [comment]
@TCurran4589 which homebrew packages did you install? I'm experiencing the same issue with shapefile/geopandas and getting 'Shell is not a LinearRing Error' . Thanks!

**Comment by denadai2** [comment]
Still there, even without conda

**Comment by adah1972** [comment]
I encountered the problem in an Anaconda environment. Reinstalling just geopandas via pip, as TCurran4589 did, solved my problem.

**Comment by utkarshshukla2912** [comment]
I got it solved by updating to shapely-1.6.4.post2 on MAC

**Comment by davefoote** [comment]
Has anyone found a real reason for this? I have been randomly updating and trying to match versions that work but sometimes spend hours before I can actually get geopandas to run in a new environment. Has anyone found a clear and simple protocol to get geopandas to consistently function on a new MacOS environment? Conda has never worked for this on my machine, btw, although I do use it for less touchy packages. Would be great if geopandas actually worked most of the time.

**Comment by martinfleis** [comment]
@davefoote 
```
conda create -n geo_env
conda activate geo_env
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda install geopandas
```
doesn't work for you? It works perfectly on my Mac all the time. How did you install geopandas?

**Comment by pmallas** [comment]
In my case, testing up a simple test case works fine:

from shapely.geometry import Polygon
p =  [(88, 2), (88, 3), 
      (89, 3), (89, 2)] 
s = Polygon(p)

No error here. If I do a "import gdal" before the shapely  import, I get the error.  If reverse the import order, no problem.

**Comment by trngbich** [comment]
> In my case, testing up a simple test case works fine:
> 
> from shapely.geometry import Polygon
> p = [(88, 2), (88, 3),
> (89, 3), (89, 2)]
> s = Polygon(p)
> 
> No error here. If I do a "import gdal" before the shapely import, I get the error. If reverse the import order, no problem.

Solved my problem also (shapely v.1.6.4-post1, gdal 2.3.3). Do you know why it is so?

**Comment by pmallas** [comment]
I don't know and don't really have the time right now to look into it further. But I am glad to hear that someone else benefited from my observation.  It just seems likely that if someone is using shapely, he/she is using gdal in some fashion as well and the ordering of the imports is important.

**Comment by sgillies** [comment]
Hey folks, the good news is the import order issue (only that issue, mind, there are other conda and conda/pip combination issues affecting people who have commented on this issue) is solved in the latest shapely 1.7 pre-release. See https://github.com/Toblerity/Shapely/pull/735#issuecomment-503885247 for some details. If you are using pip (attention: don't mix pip and conda packages!) you can get the pre-release with `python -m pip install -U --pre shapely`.

**Comment by shiweihappy** [comment]
I test this:
```
from shapely.geometry import Polygon
p = [(88, 2), (88, 3),
(89, 3), (89, 2)]
s = Polygon(p)
print(s)
```

when I use pycharm then got error:  "Shell is not a LinearRing Error",
but when I use jupyter lab it is ok。

**Comment by ridoluc** [comment]
I found out that pygeos was causing the error and solved it uninstalling the package: `pip uninstall pygeos`

**Comment by MeldaS** [comment]
> No error here. If I do a "import gdal" before the shapely import, I get the error. If reverse the import order, no problem.

This finally worked for me! 

I have literally spent days cleaning up my Python environment and doing a fresh install of each package extremely carefully using Homebrew and pip3. Despite all my efforts, I faced the same "Shell is not a LinearRing Error". Adding "import shapely" to the top of my script solved this issue! 

Before doing that, I uninstalled Shapely and reinstalled it using: `pip install shapely --no-binary shapely` Not sure if that helped, but it wasn't sufficient on its own. The error only disappeared when I imported Shapely before other packages.

My fresh install may have helped with this issue and other issues I had been facing with GDAL paths, EPSG csv files, EPSG not found errors (even though the code was in the csv), Rasterio errors, etc.

**Comment by galadREAL** [comment]
I came to this post from googling the same error message and just wanted to share what fixed it for me: Reinstalling geopandas:
`pip3 uninstall geopandas
conda install geopandas`

(I thought that geopandas was via pip at first, that's why I uninstalled with it instead of conda)

**Comment by masgra** [comment]
```'Shell` is not a LinearRing'``` 

this error caused my script to breach up on a Ubuntu cluster when I used the Conda installation. 
I tried it with a pure pip install environment but this did only cause that the error now also showed the related exception: 

```IllegalArgumentException: Shell is not a LinearRing ```

which I was able to catch. Long story short, I found that calculations on EMPTY POLYGON led to this error message.
