### ISSUE TITLE
Fix repr method of geodataframe (geopandas-cython branch)

### ISSUE THREAD

**Issue by brendancol** [geopandas/geopandas#558]
Seems like the `GeometryArray` needs `__repr__` method help, but not totally sure. @mrocklin you mentioned this was a simple fix. Can you point me in the right direction?

Example 1:
```python
import geopandas as gpd
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
print(world)
```
throws exception:
```
AxisError: axis 1 is out of bounds for array of dimension 1
```

Example 2:
```python
import geopandas as gpd
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
dissolved = world.dissolve(by='continent')
print(dissolved)
```
throws exception:
```
TypeError: Argument 'arr' has incorrect type (expected numpy.ndarray, got GeometryArray)
```

**Comment by jorisvandenbossche** [comment]
Yes, this is a known issue with the geopandas-cython branch. The repr itself works when using pandas master (try `df.head()`), but it's the 'truncated repr' that fails (so when you want to show more rows than the `pd.options.display.max_rows` setting, default of 60).

It's not that easy to fix, as it is actually `pd.concat` which fails (cfr https://github.com/pandas-dev/pandas/issues/17283). And that requires some changes in pandas (not that easy but doable I think, see that issue).

But before we fix concat, I think we should add some workarounds to geopandas-cython branch. We can override the `repr` method, and provide a patched implementation. Possibilities:

- check for the number of rows of the dataframe, and switch to the 'info' view to at least not get an error. Some pseudo-code:

    ```
    def __repr__(self):
        if len(self) > pd.options.display.max_rows:
            with pd.option_context('display.large_repr', 'truncate'):
                super(self).__repr__()
        else:
            super(self).__repr__()
    ```

- Try to mimic the correct display by using `geopandas.concat` or by combining the display of the first 30 and last 30 rows.

**Comment by jorisvandenbossche** [comment]
This now works correctly with the latest released version of pandas. 
So it is still not working with older versions of pandas, but I don't think fixing that is a priority for the cython branch.

**Comment by jorisvandenbossche** [comment]
We are now using the vectorized operations from PyGEOS (and in the future Shapely), and with the ExtensionArray work in pandas, this now works as expected.
