### ISSUE TITLE
GeoDataFrame constructor doesn't work on geometry-only DataFrame [cython]

### ISSUE THREAD

**Issue by andreas-h** [geopandas/geopandas#559]
(see http://disq.us/p/1mi03gt)

With geopandas 0.3.0, the following worked in a notebook:

    geoms = [shapely.geometry.Point(1, 1)]
    df = gpd.GeoDataFrame(geometry=geoms)
    geoms

However, in the *geopandas-cython* branch, I get a `ValueError: not enough values to unpack (expected 1, got 0)`.

**Comment by jorisvandenbossche** [comment]
Thanks for reporting! 
That seems one case we are missing with the new constructor. 

The problem it now assumes you always pass data:

https://github.com/geopandas/geopandas/blob/07cba932c551a185a3fdf8950f66d9cd31f332ea/geopandas/geodataframe.py#L68

So the above line fails if no `args` were passed (like in your case). So it should be easy to check for this, and if not assign `None` to `arg` I think.

**Comment by andreas-h** [comment]
Should I go ahead and create a PR replacing line 68 with

    [arg] = args if len(args) else [None]

and provide a test?

**Comment by jorisvandenbossche** [comment]
Yes, that is certainly welcome! (and yes, with a test)

**Comment by jorisvandenbossche** [comment]
We are now going forward with PyGEOS (to be integrated in Shapely) instead of the cython branch (see https://github.com/geopandas/geopandas/issues/1155, already available in master), and this issue is fixed and tested in master.
