### ISSUE TITLE
Problems with sjoin [cython]

### ISSUE THREAD

**Issue by andreas-h** [geopandas/geopandas#560]
(see http://disq.us/p/1mi0e59)

The following works in 0.3.0, but not on the *geopandas-cython* branch:

    testpoint = [shapely.geometry.Point(1, 1)]
    testgrid = [shapely.geometry.Polygon(((0, 0), (2, 2), (0, 2), (2, 0))).convex_hull]
    df = gpd.GeoDataFrame({'dummy_id': np.arange(len(testpoint))}, geometry=testpoint)
    pts = gpd.GeoDataFrame({'dummy_id': np.arange(len(testgrid))}, geometry=testgrid)
    gpd.sjoin(df, pts, op='within')

On the *geopandas-cython* branch, I get a `TypeError: Argument 'arr' has incorrect type (expected numpy.ndarray, got GeometryArray)`

**Comment by jorisvandenbossche** [comment]
As I replied on the discussion, this is probably the `repr` that is causing this. You can check this by doing:

```
result = gpd.sjoin(df, pts, op='within')
result.head()
```

If it is only failing on the second line, then it is the repr. Note that the repr does work when using pandas master.

**Comment by andreas-h** [comment]
Sorry, Disqus was slow in showing your reply ...

You're correct, and the error is indeed in the repr, so I'll go ahead and close this.

**Comment by jorisvandenbossche** [comment]
Thanks for trying out anyhow! And probably we should make it clearer what the known issues are with the branch, and that you need pandas master to have the basic repr working.
