### ISSUE TITLE
DISCUSS: handling of missing vs empty geometries

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#601]
With the cython refactor we have some discussion about how empty and/or missing data need to be handled.

So there are two different concepts:

- missing geometries, represented by NaN / None
- empty geometries, represented by actual shapely objects, but which are empty (no coordinates, `is_empty` attribute gives True)

And the question is what the "missing data handling" functions do with both of those: `isna`, `fillna`, `dropna`.

Currently, in geopandas master those functions regard both missing and empty as 'missing'. 
In the cython refactor, things didn't work yet but are being fixed in https://github.com/geopandas/geopandas/pull/582, and there we are currently opting to let `isna`/`fillna`/`dropna` for now only work on actual missing data.

Here is a notebook that explores a bit those concepts: http://nbviewer.jupyter.org/gist/jorisvandenbossche/704c799d80a00aef4b1244b97282235a

So the questions are: what is the preference in how to handle missing / empty data ? 
Are we fine with having `isna`/`fillna`/`dropna` only see missing data by default? (which is a change compared to master, but you still have the `.is_empty` property that indicates which rows contain empty geometries) 
If so, do we need a keyword for those functions to specify that empty should be regarded as missing (something like `empty_as_na=True`) ? Or should we have a utility function to convert empty to missing?

cc @geopandas/collaborators

**Comment by jorisvandenbossche** [comment]
With the cython refactor we have some discussion about how empty and/or missing data need to be handled.

So there are two different concepts:

- missing geometries, represented by NaN / None
- empty geometries, represented by actual shapely objects, but which are empty (no coordinates, `is_empty` attribute gives True)

And the question is what the "missing data handling" functions do with both of those: `isna`, `fillna`, `dropna`.

Currently, in geopandas master those functions regard both missing and empty as 'missing'. 
In the cython refactor, things didn't work yet but are being fixed in https://github.com/geopandas/geopandas/pull/582, and there we are currently opting to let `isna`/`fillna`/`dropna` for now only work on actual missing data.

Here is a notebook that explores a bit those concepts: http://nbviewer.jupyter.org/gist/jorisvandenbossche/704c799d80a00aef4b1244b97282235a

So the questions are: what is the preference in how to handle missing / empty data ? 
Are we fine with having `isna`/`fillna`/`dropna` only see missing data by default? (which is a change compared to master, but you still have the `.is_empty` property that indicates which rows contain empty geometries) 
If so, do we need a keyword for those functions to specify that empty should be regarded as missing (something like `empty_as_na=True`) ? Or should we have a utility function to convert empty to missing?

cc @geopandas/collaborators

**Comment by jdmcbr** [comment]
I've never myself encountered a situation where I cared to distinguish between an empty geometry and a null value, but on that point, I found the example in the notebook of looking at the area fairly interesting in thinking about it.

    ￼>>> s.area
    0    0.0
    1    NaN
    2    NaN
    3    0.0
    4    0.0
    dtype: float64

Some other geometric operations also make a distinction between a NaN and an empty geometry, so it seems useful for `*na` functions to do so as well. The current behavior of `is_empty`, which returns `False` for `NaN`, seems correct. I think an `empty_as_na` keyword though is a good idea for the `*na` functions, though I'd lean towards the keyword defaulting to `False`.

**Comment by mrocklin** [comment]
I'm somewhat inclined to keep empty and missing as entirely separate concepts with separate methods to determine them.  If people need to mix or transform then they could use normal binary or setitem operations

    s[s.is_empty()] = None
    s.is_empty() | s.isna()
