### ISSUE TITLE
intersection series method

### ISSUE THREAD

**Issue by dfolch** [geopandas/geopandas#606]
I am trying to do an intersection of lines and polygons. I understand that this does not work with the `overlay` function. In earlier versions of geopandas I used [GeoSeries.intersection](http://geopandas.org/reference.html#GeoSeries.intersection), but I am not able to make it work now. Here is a [toy example](https://gist.github.com/dfolch/e2f946f9fee25fa4a5bfe621028db933) and here is an attempt to replicate the [NYC boroughs example](https://gist.github.com/dfolch/2237230abc7c97b6742cac6e9190888e) from the docs.

**Comment by jdmcbr** [comment]
@dfolch I just tried out the example in the NYC boroughs gist you posted, and everything worked as expected. That is, what you defined as `holes` plotted a bunch of objects, and what you called `boros_with_holes` plotted the `boros` frame with holes in the locations of the circles. Can you provide more information about your installation?

**Comment by dfolch** [comment]
Running geopandas version 0.3.0. Installed using conda-forge on OSX. I used the [trick of listing conda-forge first](https://conda-forge.org/docs/conda-forge_gotchas.html) in the condarc file.

**Comment by dfolch** [comment]
I was running shapely 1.6.2. When I rolled it back to 1.5.17 the toy example and the NYC boroughs example both worked. This is all in python 2.7.

**Comment by jorisvandenbossche** [comment]
@dfolch Thanks for trying to figure this out. 
Could you try to see if you also get the failure without using geopandas? (as the error seems to happen at the shapely level). Eg:

```
LineString([(1,3), (3,3)]).intersection(Polygon([(0,0), (2,0), (2,2), (0,2)]))
```

(or one of the other combinations of linestrings/polygons)

**Comment by dfolch** [comment]
@jorisvandenbossche Thanks for the simpler test. I can confirm it's on the shapely side (or my installation). I'll post over there. Thanks.

```
In [1]: import shapely

In [2]: shapely.__version__
Out[2]: '1.5.17.post1'

In [3]: from shapely.geometry import Polygon, LineString

In [4]: bits = LineString([(1,1), (1,3)]).intersection(Polygon([(0,0), (2,0), (2,2), (0,2)]))

In [5]: list(bits.coords)
Out[5]: [(1.0, 1.0), (1.0, 2.0)]
```

```
In [1]: import shapely

In [2]: shapely.__version__
Out[2]: '1.6.2'

In [3]: from shapely.geometry import Polygon, LineString

In [4]: bits = LineString([(1,1), (1,3)]).intersection(Polygon([(0,0), (2,0), (2,2), (0,2)]))
No handlers could be found for logger "shapely.geos"
---------------------------------------------------------------------------
TopologicalError                          Traceback (most recent call last)
<ipython-input-4-e86c844044b5> in <module>()
----> 1 bits = LineString([(1,1), (1,3)]).intersection(Polygon([(0,0), (2,0), (2,2), (0,2)]))

/Users/dfolch/anaconda2/envs/gisprog3/lib/python2.7/site-packages/shapely/geometry/base.pyc in intersection(self, other)
    618     def intersection(self, other):
    619         """Returns the intersection of the geometries"""
--> 620         return geom_factory(self.impl['intersection'](self, other))
    621 
    622     def symmetric_difference(self, other):

/Users/dfolch/anaconda2/envs/gisprog3/lib/python2.7/site-packages/shapely/topology.pyc in __call__(self, this, other, *args)
     68             err = TopologicalError(
     69                     "This operation could not be performed. Reason: unknown")
---> 70             self._check_topology(err, this, other)
     71         return product
     72 

/Users/dfolch/anaconda2/envs/gisprog3/lib/python2.7/site-packages/shapely/topology.pyc in _check_topology(self, err, *geoms)
     37                     "Likely cause is invalidity of the geometry %s" % (
     38                         self.fn.__name__, repr(geom)))
---> 39         raise err
     40 
     41 

TopologicalError: This operation could not be performed. Reason: unknown
```
