### ISSUE TITLE
Some ideas from PyData

### ISSUE THREAD

**Issue by jtratner** [geopandas/geopandas#62]
Had some ideas from PyData that could be useful sugar:
- [x] <del>autoconvert geometry on setting crs (and validate) eg string rep set becomes dict under the hood</del> (not doing this)
- [ ] add tests to make sure that getitem with 'geometry' returns the column named geometry, not the overall geometry.
- [ ] pick a default unit spec
- [ ] keep track of geo units on columns
- [ ] allow remembering geo data when you have multiple columns and switch geometries with set_geometry.

**Comment by martinfleis** [comment]
All above implemented in #1101 and #1339.

- Units are stored in pyproj.CRS - `crs.axis_info[0].unit_name` and `crs.axis_info[1].unit_name`.
- We keep track of CRS with geo data on GeometryArray level.
- `getitem` is already tested.
