### ISSUE TITLE
Plot points with 3 dimensions?

### ISSUE THREAD

**Issue by lecardozo** [geopandas/geopandas#622]
Does geopandas plotting API allow for 3-dimensional graphs out of the box? Something like this: :point_down: 
![image](https://user-images.githubusercontent.com/8867239/33219037-57186ea4-d127-11e7-89d8-08b785102411.png)

The graph above was built using mpl_toolkits.mplot3d.Axes3D and adds a time variable to the map.

Didn't find anything about 3D plots in the docs. Sorry if I missed something!

**Comment by jdmcbr** [comment]
@lecardozo There is currently no explicit support for three dimensional plotting. The plotting API is currently fairly lightweight, and at least with my limited experience with 3d plotting in matplotlib, it seems like it would take some considerable effort to variously handle 3d linestrings, point plots, and polygons (scatter plots of points would be pretty easy, but are also fairly easy for a user to get without support, using  `zs=gdf.apply(lambda geom: geom.z)`). I'd personally be inclined to keep it as such for the time being, but it is an interesting issue to consider.

**Comment by lecardozo** [comment]
Thanks for clarifying about the plotting API! Have to agree that dealing with points in 3d looks like much easier than dealing with linestrings and polygons (and possibly a mix of those) :+1: .

**Comment by alibama** [comment]
is this still sleeping?

**Comment by martinfleis** [comment]
@alibama There are currently no plans to implement 3D plotting within GeoPandas. As @jdmcbr  explained above, it would need a lot of effort and the use case for it is fairly limited. How would you use this feature?

**Comment by alibama** [comment]
i'm working with the movingpandas library and gps data with a focus on interior 3d data... it's a mess

**Comment by alibama** [comment]
specifically i'm trying to visualize stuff like stairs and elevators to help improve ADA wayfinding...

**Comment by hibicustea123** [comment]
@lecardozo may I know how did you plot the 3D figure? did you use geopandas to read the shapefile?

**Comment by jdmcbr** [comment]
@emongold We are open to PRs if someone wants to implement this. Though perhaps most straightforward would be to add a page to the documentation with some tips/tricks for producing 3d plots, without needing to try capture all the possibilities, but give some ideas to users looking to produce 3d plots.
