### ISSUE TITLE
Proposal: import PostGIS table exported as CSV

### ISSUE THREAD

**Issue by pintergreg** [geopandas/geopandas#623]
Besides direct PostGIS reading support I think i would be nice if there was a method for reading a PostGIS table exported as CSV. When a PostGIS table is exported, the geometry is represented as WKB. So I think there should be a `read_postgis_csv` method that reads CSV then converts the specified column to geometry.

* Do you think a feature like this would be useful for general?
* What other use cases should be handled?
    * The code snippet below assumes there is one column that contains geometry and its name is not "geometry".

``` python
def read_postgis_csv(filename, geometry):
    """ Reads a PostGIS table exported as CSV and creates a geometry column from
    the one specified by the 'geometry'

    """
    gdf = gpd.GeoDataFrame.from_csv(filename)
    gdf["geometry"] = gdf[geometry].apply(lambda x: shapely.wkb.loads(x, hex=True))
    return gdf
```

I created this issue for discussion, if this proposal is accepted I eventually implement the feature and send a PR.

ps: I know `from_csv` is deprecated, the snippet is only for demonstrating the idea

**Comment by jdmcbr** [comment]
@pintergreg Thanks for the suggestion. I think this feature falls under the heading of an existing issue, in #603, so I'll close this issue (if after looking at other issue, you disagree, I'm happy to re-open this one). As your explanation highlights though, the `hex` keyword may need to vary depending upon the context in which a csv with a geometry column was written. As @jorisvandenbossche wrote in #603, I think the main challenge here is a sensible API to cover the different situations.

**Comment by pintergreg** [comment]
> I think the main challenge here is a sensible API to cover the different situations.

I couldn't agree more.
