### ISSUE TITLE
Plot points with markersize variable according to dataframe column

### ISSUE THREAD

**Issue by h4k1m0u** [geopandas/geopandas#624]
Hi,

Does the `GeoDataFrame.plot()` method support a `markersize` argument taking its value from a `column` in the dataframe. similarly to how the `column` argument works with `cmap` to affect the color?

It seems to me that it doesn't as I got an error when I've set `markersize='population'`, but is there a workaround?

**Comment by jdmcbr** [comment]
@h4k1m0u `geopandas` does not currently offer such a feature, but that does seem like a good addition, so a pull request to implement that would be welcome.

**Comment by josephmabe** [comment]
@h4k1m0u a workaround that I found was to iterate through the rows in the dataframe, and create a subplot that takes the markersize argument from each individual row. 

e.g. if you have column 'Marker Size' in GeoDataFrame, then on top of your base plot you can add code similar to:

for i in range(0,len(GeoDataFrame)):
    GeoDataFrame.geometry.iloc[i:i+1].plot(ax = ax, markersize = GeoDataFrame['Marker Size'].iloc[i])

Hope that helps?
