### ISSUE TITLE
Overlay issue

### ISSUE THREAD

**Issue by ramsinghdayal** [geopandas/geopandas#632]
I have two .fits files, in one .fits file, there is information about data and other .fits file have information about latitude and longitude. So how can I overlay latitude longitude grid on data using astropy ?

**Comment by jdmcbr** [comment]
@ramsinghdayal A question focused on geopandas usage would be better directed to stackoverflow.com. There's a geopandas tag there you can use, and questions there generally get attention within a few days. Though adding a clearer explanation of what you're trying to do and an example of what you've tried would likely improve your chances of getting an answer.
