### ISSUE TITLE
Bug or missing feature? (buffered points don't plot)

### ISSUE THREAD

**Issue by michaelaye** [geopandas/geopandas#636]
Using Python 3.6 and GeoPandas 0.3.0 I get this unintuitive behavior (I'm still a newb with shapely, maybe it makes sense?):

![screenshot 2018-01-10 23 57 07](https://user-images.githubusercontent.com/69774/34812286-4a7c0b1e-f662-11e7-96d6-04f642331c4b.png)

I would expect two simple polygons being plotted, as the GeoPandas manual looks like it shouldn't have a problem with plotting Polygonal Shapely objects?

**Comment by jorisvandenbossche** [comment]
That certainly does not make sense, but I also can't reproduce it. I correctly see two overlapping circles plotted in matplotlib if I try the following code:

```
import geopandas
from shapely.geometry import Point
s = geopandas.GeoSeries([Point(1,0), Point(2,0)])
s.buffer(10).plot()
```

**Comment by michaelaye** [comment]
Confirmed, wow, an innocent astropy import is breaking this!
Try this line just before your code to see it fail (inside my Jupyter notebook, up to date with conda-forge):

```python
from astropy import units as u
```

**Comment by michaelaye** [comment]
caused by a rotten setup, sorry for the noise.

**Comment by jorisvandenbossche** [comment]
OK, no problem (in any case, I installed astropy, and doing that import does not break it in my environment)
