### ISSUE TITLE
Can geopandas make a quick spatial query?

### ISSUE THREAD

**Issue by giser-yugang** [geopandas/geopandas#640]
I have two sets of data, one is the point type, and the other is the LineString type
The point data are as follows:
```
geometry
0       POINT (415588.231977552 3391939.381635312)
1       POINT (415587.899353286 3391933.620958935)
2      POINT (415589.6309109587 3391934.494040198)
3      POINT (415590.6561590391 3391930.828531844)
4      POINT (415598.9578661992 3391926.440975915)
5      POINT (415595.9963999433 3391927.572519553)
6      POINT (415595.1340967293 3391927.579280694)
7      POINT (415591.4793568922 3391925.834619201)
8       POINT (415575.979625279 3391928.726976327)
9       POINT (415580.1108166897 3391930.13539896)
10     POINT (415580.0515083554 3391934.790824829)
11     POINT (415582.6925112355 3391929.450158627)
12     POINT (415584.1175159487 3391927.887330284)
13     POINT (415585.2368362513 3391923.999418919)
...
```

The LineString data are as follows:
```
geometry
0      LINESTRING (416237.1842227532 3384482.11665018...
1      LINESTRING (416588.8932837959 3383265.80647952...
2      LINESTRING (416485.8614128018 3382898.33446779...
3      LINESTRING (416588.8932837959 3383265.80647952...
4      LINESTRING (416789.8422055047 3383172.87624058...
5      LINESTRING (416875.0523955021 3384726.78753317...
6      LINESTRING (416731.1424401619 3384660.63360928...
7      LINESTRING (416731.1424401619 3384660.63360928...
8      LINESTRING (416789.8422055047 3383172.87624058...
9      LINESTRING (416735.9428852141 3384645.30190919...
10     LINESTRING (406307.5368301229 3394235.45235726...
...
```

I don't see the content of the spatial query in the document.I would like to ask if geopandas can quickly find out the nearest LineString for every point?
And I have tens of millions of points and tens of thousands of LineString.Can someone help me? Thanks in advance

**Comment by jorisvandenbossche** [comment]
@giser-yugang Can you provide a reproducible example? 

Something like that should certainly be possible. If it will be performant enough on so many data I am not sure. 
You can eg take a look at https://gis.stackexchange.com/questions/222315/geopandas-find-nearest-point-in-other-dataframe

**Comment by giser-yugang** [comment]
@jorisvandenbossche Thank you very much, this is very helpful to me. I plan to use Rtree index on so many data.

**Comment by adriangb** [comment]
@jorisvandenbossche should this be closed as stale?

**Comment by martinfleis** [comment]
Yep. Thanks for a ping.
