### ISSUE TITLE
Check whether crs is the same when transforming

### ISSUE THREAD

**Issue by kjordahl** [geopandas/geopandas#65]
Currently, the `to_crs` method will always do a transformation, even if the requested crs is the same as the current one.  This could be improved with a simple dictionary check to skip if the crs is equal.  A more involved check would need to determine whether coordinate systems are equivalent even if the PROJ.4 parameters are not equal.

An example of different crs mappings that refer to the same projection is

```
crs1 = {'datum': 'NAD83', 'ellps': 'GRS80', 'proj': 'utm', 'units': 'm', 'zone': 18, 'no_defs': True}
crs2 = {'init': 'epsg:26918', 'no_defs': True}
```

which both represent [UTM zone 18N](http://spatialreference.org/ref/epsg/26918).

**Comment by yobuntu** [comment]
I think pyproj will now skip transformations if crs are the same which make the check almost useless.
see https://pyproj4.github.io/pyproj/html/optimize_transformations.html

**Comment by micahcochran** [comment]
> I think pyproj will now skip transformations if crs are the same which make the check almost useless.
see https://pyproj4.github.io/pyproj/html/optimize_transformations.html

It does as of pyproj version 2.1.2, see [pyproj CHANGELOG](https://github.com/pyproj4/pyproj/blob/master/sphinx/history.rst).

**Comment by snowman2** [comment]
I would recommend using pyproj.CRS.is_exact_same for skipping transformations. Even though pyproj does skip the transformation, you can skip even iteration over an empty operation with this check.

**Comment by jorisvandenbossche** [comment]
Indeed, it would still be beneficial to skip on the geopandas level, so we don't need to reconstruct the geometries from the unconverted coordinates.
