### ISSUE TITLE
Raise error when trying to write empty dataframes

### ISSUE THREAD

**Issue by hunterowens** [geopandas/geopandas#657]
Currently, the behavior when writing an empty dataframe is counter-intuitive (`ValueError: Geometry column cannot contain mutiple geometry types when writing to file.`). Would it be possible to add  a check and more helpful exception?

**Comment by jorisvandenbossche** [comment]
Yes, that should not be difficult to raise a more informative error message. The current check happens here: https://github.com/geopandas/geopandas/blob/master/geopandas/io/file.py#L134. We could add a check that checks for `if df.empty: ...`. 
PR welcome!

**Comment by cr458** [comment]
@jorisvandenbossche I can take this, if needed!

**Comment by jorisvandenbossche** [comment]
That's certainly welcome!

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/geopandas/geopandas/pull/663
