### ISSUE TITLE
Projection EPSG:2154

### ISSUE THREAD

**Issue by Axlrck** [geopandas/geopandas#658]
Hello, I have a problem with a projection,

```
path_shape = 'C:/shapes.txt'
df = pd.read_csv(path_shape, sep=',')

geometry = [Point(xy) for xy in zip(df.shape_pt_lon, df.shape_pt_lat)]

crs = fiona.crs.from_epsg(4326)
geo_df = GeoDataFrame(df, crs=crs, geometry=geometry) # WGS84 proj

new_crs = fiona.crs.from_epsg(2154)
geo_df.to_crs(crs=new_crs, inplace=True)

geo_df.to_file(driver='ESRI Shapefile', filename='C:/Users/ppad/Desktop/data.shp')
```

At the end, my .prj file is empty. 

But, when i work on another shape file, the projection is epsg:102110 and not 2154 

Have you got an idea ?

Thx ;)

**Comment by jorisvandenbossche** [comment]
Can you provide a reproducible example? 
Can you show the result for printing `geo_df.crs` before writing to a shapefile?

> But, when i work on another shape file, the projection is epsg:102110 and not 2154

What do you mean with this?

**Comment by Axlrck** [comment]
The result is of `geo_df.crs` is : {'init': 'epsg:2154', 'no_defs': True}

> But, when i work on another shape file, the projection is epsg:102110 and not 2154

In fact when a open a shape file with epsg=2154 and i write it in another folder, the projection change into epsg:102110 : 

```

path_shape = 'C:/commune_scot.shp'

geo_df = gpd.read_file(path_shape)
print(geo_df.crs)

# print : {'proj': 'lcc', 'lat_1': 49, 'lat_2': 44, 'lat_0': 46.5, 'lon_0': 3, 'x_0': 700000, 'y_0': 6600000, 'ellps': 'GRS80', 'units': 'm', 'no_defs': True}

geo_df.to_file(driver='ESRI Shapefile', filename='C:/Users/ppad/Desktop/test.shp')
# epsg is QGIS = 102110
```

This projection seems to be good but the name is not correct

**Comment by jorisvandenbossche** [comment]
It will be very hard to help without a reproducible example.

As a test, the following creates a correct .prj file for me:

```
In [18]: import geopandas

In [20]: df = geopandas.read_file(geopandas.datasets.get_path('nybb'))

In [24]: df = df.to_crs(epsg=2154)

In [25]: df.crs
Out[25]: {'init': 'epsg:2154', 'no_defs': True}

In [26]: df.to_file('test_crs.shp')
```

Does it for you?

> In fact when a open a shape file with epsg=2154 and i write it in another folder, the projection change into epsg:102110 

Did you check the written `.prj` file? 
Both numbers are Lambert-93 systems. It might be that QGIS interpreted the .prj file differently (I don't know the difference between both)

**Comment by Axlrck** [comment]
You right, I have tried to run the code on another PC and the projection worked in the both cases (from a txt file and a shp file) with this final code : 
```
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point
import fiona


if __name__ == '__main__':

    path_df = '/Users/Axl/Simouv/GTFS/SQL/QGIS/shapes.txt'
    df = pd.read_csv(path_df, sep=',')

    geometry = [Point(xy) for xy in zip(df.shape_pt_lon, df.shape_pt_lat)]
    crs = fiona.crs.from_epsg(4326)
    geo_df = gpd.GeoDataFrame(df, crs=crs, geometry=geometry)

    new_crs = fiona.crs.from_epsg(2154)
    geo_df.to_crs(crs=new_crs, inplace=True)
    geo_df.to_file(driver='ESRI Shapefile', filename='/Users/Axl/Desktop/shapes.shp')

    path_df2 = '/Users/Axl/Simouv/GTFS/SIG/StopsGTFS2017.shp'
    df2 = gpd.read_file(path_df2)

    print(df2.crs)
    df2.to_crs(new_crs, inplace=True)
    print(df2.crs)
    df2.to_file(driver='ESRI Shapefile', filename='/Users/Axl/Desktop/stops.shp')
```
The console prints 
```
/usr/local/bin/python3.6 /Users/Axl/Desktop/TestProjection.py
{'proj': 'lcc', 'lat_1': 49, 'lat_2': 44, 'lat_0': 46.5, 'lon_0': 3, 'x_0': 700000, 'y_0': 6600000, 'ellps': 'GRS80', 'units': 'm', 'no_defs': True}
{'init': 'epsg:2154', 'no_defs': True}
```

<img width="1214" alt="capture d ecran 2018-01-30 a 19 27 48" src="https://user-images.githubusercontent.com/29508142/35583929-b53bf57c-05f3-11e8-9f18-228662cf4170.png">

<img width="1220" alt="capture d ecran 2018-01-30 a 19 33 42" src="https://user-images.githubusercontent.com/29508142/35584182-87cd673c-05f4-11e8-94ca-93531fd13057.png">

<img width="726" alt="capture d ecran 2018-01-30 a 19 26 20" src="https://user-images.githubusercontent.com/29508142/35583852-7e0b7cee-05f3-11e8-9790-1da8644a5d3a.png">

Maybe the problem comes from an old version of QGIS. It works with : 
• QGIS  2.18.15
• geopandas 0.3.0
• pandas 0.21.0

In the .prj file I have : 
```
PROJCS["RGF93_Lambert_93",GEOGCS["GCS_RGF93",DATUM["D_RGF_1993",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["standard_parallel_1",49],PARAMETER["standard_parallel_2",44],PARAMETER["latitude_of_origin",46.5],PARAMETER["central_meridian",3],PARAMETER["false_easting",700000],PARAMETER["false_northing",6600000],UNIT["Meter",1]]
```

Thanks 👍

**Comment by micahcochran** [comment]
> But, when i work on another shape file, the projection is epsg:102110 and not 2154

One note [102110 is an ESRI code](http://spatialreference.org/ref/esri/rgf-1993-lambert-93/), some GIS software misidentifies that as an EPSG code.  I took a quick look at spatialref at ESRI:102110 and EPSG:2154.  Those seem very similar.

**Comment by jorisvandenbossche** [comment]
OK, closing, as this seems solved
