### ISSUE TITLE
Q: is there a way to do some spatial interpolation?

### ISSUE THREAD

**Issue by TichyProgs** [geopandas/geopandas#665]
I have a df with many series each consistin of feature name and either yes or no value. The feature names are connected with a geojson with them. But for some of the features I have not a simgle record so I can’t calculate the percentage of ie. yeses.
So I would like to interpolate so that I get the most propable value for each of those empty features and then I’ll be able to create a dictionary with every festure nae and it’s yes to no percentage or if it didn’t get any then the interpolated propable one if you know what I mean

propably a rookie thing but excuse me please

**Comment by jorisvandenbossche** [comment]
It's probably better to ask such questions at eg StackOverflow. In any case, a small reproducible example code will help (also for on StackOverflow)

**Comment by ljwolf** [comment]
I've done something like this using [scikit.neighbors.KNeighborsRegressor](http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html) or [PySAL `lag_categorical`](https://github.com/pysal/pysal/blob/master/pysal/weights/spatial_lag.py#L89).
