### ISSUE TITLE
BUG? overlay with overlapping geometries in input layer

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#666]
From https://stackoverflow.com/questions/48655331/geopandas-overlay-intersection-doesnt-work-as-expected

I made a small reproducible and illustrating script:

```
store = geopandas.GeoDataFrame({'store_area': [1, 2],
                                'geometry': [Polygon([(0, 0), (3, 0), (3, 3), (0, 3)]),
                                             Polygon([(2, 2), (5, 2), (5, 5), (2, 5)])]})
area = geopandas.GeoDataFrame({'geometry': [Polygon([(1, 1), (1, 4), (4, 4), (4, 1)])]})

ax = store.plot(alpha=0.5)
area.plot(ax=ax, facecolor='none', edgecolor='red', linewidth=2)
```
![image](https://user-images.githubusercontent.com/1020496/35910674-a50ab12a-0bf7-11e8-8f66-873c44b979f3.png)

This produces:

```
>>> geopandas.overlay(store, area, how='intersection')

   store_area                                       geometry
0           1  POLYGON ((3 2, 3 1, 1 1, 1 3, 2 3, 2 2, 3 2))
1           2  POLYGON ((3 2, 3 3, 2 3, 2 4, 4 4, 4 2, 3 2))
2           1            POLYGON ((2 3, 3 3, 3 2, 2 2, 2 3))
```

So the small overlapping square in the middle is a separate feature in the result (it also got the 'store_area' of 1, while it is actually contained in both 1 and 2). 

I am not fully sure what *should* be the result, but it looks like this should be 2 features (that still overlap). That is also what QGIS 'intersection' overlay operation does.

**Comment by jorisvandenbossche** [comment]
Actually, when trying @ozak 's implementation from here https://github.com/geopandas/geopandas/pull/338#issuecomment-290303715, that already gives the probably desired result of two features.

**Comment by ozak** [comment]
Indeed, that was one of the issues it addresses. I had noted something similar when comparing with the output of the  original ``overlay`` function.
