### ISSUE TITLE
Maps with Layers tutorial doesn't work

### ISSUE THREAD

**Issue by taimur38** [geopandas/geopandas#676]
Whenever I specify `ax=anything`, a blank map is output.

python 3.6.4
matplotlib 2.1.2
geopandas 0.3.0

```python
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
cities = gpd.read_file(gpd.datasets.get_path('naturalearth_cities'))
cities = cities.to_crs(world.crs)

fig, ax = plt.subplots()
# displays blank axes
ax.set_aspect('equal')
world.plot(ax=ax, color='white', edgecolor='black')
# <matplotlib.axes._subplots.AxesSubplot at 0x7fe0dd4500b8>
# <matplotlib.figure.Figure at 0x7fe0dd3f8710>

cities.plot(ax=ax, marker='o', color='red', markersize=5)
# <matplotlib.axes._subplots.AxesSubplot at 0x7fe0dd4500b8>
# <matplotlib.figure.Figure at 0x7fe104448ef0>

plt.show() # nothing
plt.savefig("test2.png") # file is a white rectangle
```

plotting any of these independently displays the expected output

**Comment by jdmcbr** [comment]
@taimur38 With same package versions, I wasn't able to reproduce on my computer. I'm assuming this was all in a Jupyter notebook? When you say "plotting any of these independently", do you mean something like `cities.plot(marker='o', color='red', markersize=5)`? What is your OS?

**Comment by taimur38** [comment]
@jdmcbr yeah, was all done on jupyter notebook. And yeah that is what I meant by independently. My OS is arch linux on the 4.15.5 kernel

**Comment by jorisvandenbossche** [comment]
If you create a figure with `fig, ax = plt.subplots()`, I think you need to use `fig.savefig()` instead of `plt.savefig()`. 
Also, when using `%matplotlib inline`, it is no needed to manually call `plt.show()`

**Comment by taimur38** [comment]
@jorisvandenbossche with fig.savefig() I do manage to get the correct figure saved as a png, thank you.

but I still can't get anything to show inline

**Comment by jorisvandenbossche** [comment]
Closing this as I don't think there is anything to do on the geopandas side. But please further comment if you still have problems with this!
