### ISSUE TITLE
Inconsistent behaviour when updating geometry column

### ISSUE THREAD

**Issue by avnovikov** [geopandas/geopandas#681]
When I was trying to update geometry column in the recommended 'pandas way' I ran in to a bug

```
gdf_h.loc[:,'geometry'] = valid_geoms
gdf_h._geometry_array.data
Out[38]: <memory at 0x33161edc8>
```
Result is as expected if making straightforward assignment

```
gdf_h.geometry = valid_geoms
gdf_h._geometry_array.data
Out[31]:
array([140412034515464, 140412034487336, 140412303007800, ...,
       140412261305528, 140412261306008, 140412261306728], dtype=uint64)
```

I'm running 
geopandas                 1.0.0.dev                py36_1    conda-forge/label/dev
geos                      3.6.2                h5470d99_2

**Comment by jorisvandenbossche** [comment]
Thanks for the report! (and for trying out geopandas-cython). 
Yes, that doesn't seem right. Not directly sure where to fix this though (will need to take a closer look). Currently for `.loc`, we rely on the pandas method and do not override this. With the new extension array interface (coming soon to pandas), this seems to be working correctly.

**Comment by martinfleis** [comment]
Cython branch is no longer under active development. Closing as outdated.
