### ISSUE TITLE
DOC: add page on how to construct GeoDataFrame from existing DataFrame

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#689]
Eg if you have 

- two columns with x, y
- a column with the WKT format

**Comment by mrahim** [comment]
Sounds good, should it be an example gallery or a subsection ?

**Comment by jorisvandenbossche** [comment]
Hmm, not sure, maybe a gallery example is fine. Unless you see a good place to fit it in the user guides.

If there are any of the other ideas here: https://github.com/geopandas/geopandas/issues/529 that you would be familiar with, that's also welcome (or any other typical example workflow that you are using yourself).

General improvement of docstrings (adding examples, more explanation) is also very useful: https://github.com/geopandas/geopandas/issues/107
