### ISSUE TITLE
Bug? ( AttributeError: Unknown property legend_kwds)

### ISSUE THREAD

**Issue by kartikdesikan** [geopandas/geopandas#694]
I upgraded to geopandas 0.3.0 version. 

While trying 
gdf.plot(column="%Change",cmap='summer',legend=True,legend_kwds={'loc':'bottom right'})
I get the following error
AttributeError: Unknown property legend_kwds

Any ideas? Traceback is ([traceback-legend.txt](https://github.com/geopandas/geopandas/files/1828110/traceback-legend.txt))

**Comment by jorisvandenbossche** [comment]
@kartikdesikan Thanks for the report. This did work before 0.3.0? 
I thought this was only added recently in https://github.com/geopandas/geopandas/pull/434 (in the development version, not yet released).

Note however that in your case above, the `legend_kwds` won't necessarily have effect. If your data is numeric, then you will get a colorbar and not a legend, and the `legend_kwds` will be ignored.

**Comment by kartikdesikan** [comment]
It didn't work before 0.3.0 either, but that is most likely as I had a very pretty old version of geopandas. I updated this using conda fyi.

Thanks for the pointer, but the column here is categorical and not numeric, hence I am receiving a legend.

**Comment by jdmcbr** [comment]
Thanks @kartikdesikan; this does work in master (#434 was not included in the 0.3.0 release), so will close this.
