### ISSUE TITLE
ENH: give missing data distinct pattern in choropleth plots

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#695]
From http://ramiro.org/notebook/geopandas-choropleth/, it would be nice if geopandas could give the missing values in your column a distinct pattern from the used color map (eg just blank, or shaded).

cc @yaph

**Comment by yaph** [comment]
I did some research to see how a pattern can be added in matplotlib and updated the notebook. There is a ``patch`` option that can be used. Thought I'd share because I wasn't aware of it.

**Comment by jorisvandenbossche** [comment]
Thanks, similar notebook with an example here: http://nbviewer.jupyter.org/gist/jorisvandenbossche/bb1cc71f94aa3e8f2832f18dd12f6174 

I think the main question will be how to expose this to the user. We could have a `missing_style_kwargs` keyword (or shorter name), where you can specify the style for the missing records. 
Other question is if we want a default behaviour for this.

**Comment by yaph** [comment]
I think the default should stay as it is, this way the user gets a warning about missing data when trying to plot it. An additional dict with options for missing data is probably a good choice. I suggest using ``color`` and ``hatch`` as keys to be consistent with matplotlib's parameter names.
