### ISSUE TITLE
broken link in documentation

### ISSUE THREAD

**Issue by gcamargo1** [geopandas/geopandas#696]
In page : http://geopandas.org/mapping.html

The link for pysal is broken: http://pysal.org/1.2/library/esda/mapclassify.html

**Comment by micahcochran** [comment]
It looks like they added `/en/` (for English) to the URL:
http://pysal.readthedocs.io/en/1.2/library/esda/mapclassify.html

Should this really just point to the latest version? (which is 1.14)
http://pysal.readthedocs.io/en/latest/library/esda/mapclassify.html

**Comment by jdmcbr** [comment]
Thanks for the report. This was actually just resolved in #693, so readthedocs is up-to-date, but the docs on geopandas.org are what are hosted on gh-pages, so need to be rebuilt to reflect the update.

**Comment by jdmcbr** [comment]
I updated just that page on geopandas.org (I would have updated everything, but the geocoding example wasn't working) so now the link is up-to-date.
