### ISSUE TITLE
colorbar same height as plot area

### ISSUE THREAD

**Issue by rbuffat** [geopandas/geopandas#702]
Personally, I prefer when the colorbar has the same height as the plot area. This is currently not necessarily the case when legend=True is set in .plot().

I adapted the example from https://matplotlib.org/mpl_toolkits/axes_grid/users/overview.html#axesdivider to manually create a colorbar with same height as the plot area for geopandas plots: https://github.com/rbuffat/matplotlibhelper/blob/6abfbaf624173ce791aabbe498fed2a639f01b0f/myplotlib.py#L168-L181

I want to ask if this is of interest for geopandas and should be integrated directly into geopandas. If so, I could start working on a PR.

As a disclaimer, for my plots it looks like it works fine, but I don't know if it can break things I have not touched yet.

**Comment by mrahim** [comment]
Hi @rbuffat ,

It looks very interesting indeed.
As mentioned in #697 , such feature is in discussion.

**Comment by jdmcbr** [comment]
Closed by #894
