### ISSUE TITLE
Missleading exception rise when trying to_file in an empty GeoDataFrame

### ISSUE THREAD

**Issue by Imanflow** [geopandas/geopandas#705]
First I saw this issue #138 , but I think is not exactly the same, since it was talking about some elements without geometry. Here I talk about a totally empty GDF. The error is easily reproducible with:

```
`g = gpd.GeoDataFrame()`
`g['geometry'] = None`
`g.to_file('testburro.shp')`
```
it raises this error: 

```
    raise ValueError("Geometry column cannot contain mutiple "
ValueError: Geometry column cannot contain mutiple geometry types when writing to file.
```

Which I find totally misleading, maybe something more like: 'Empty GDF can not be written to file'?

This part is in geopandas/io/file.py, in fuctions `_common_geom_type and infer_schema`, both called in line 60.

I think `__common_geom_type` could return for instance 'empty' in line 107, and check for it in line 89, giving a different error.

What do you think?

**Comment by jdmcbr** [comment]
@Imanflow Thanks for the report; this was actually addressed in #663, so if you try your above example on the master branch, it returns `ValueError: Cannot write empty DataFrame to file.`, a rather more transparent error message.
