### ISSUE TITLE
ENH: Beginnings of a Geo groupby

### ISSUE THREAD

**Issue by jtratner** [geopandas/geopandas#71]
It would be great to be able to pass a collection of polygons to groupby and then end up with a {polygon: rows-contained-within-polygon} grouping.  I'm focusing on the idea of points grouped by polygon as an abstraction, but it seems like it would be similar for most geometries.

---

Some context under the hood from pandas (not particularly complicated):

Index objects have a `groupby` method takes in an ordered collection of objects and returns a group:

``` python
>>> index = Index(range(6))
>>> index.groupby(np.array(['a', 'a', 'b', 'c', 'a', 'c']))
{'a': [0L, 1L, 4L], 'b': [2L], 'c': [3L, 5L]}
```

which is how you end up with the groups in the `GroupByObject`. However, the grouper is required to be the same length as the index/NDFrame, which doesn't really make sense for geometry operations.

---

For our purposes makes sense to allow an arbitrarily long set of polygons and then group geometries by containment.

```
geo_groupby(points, polygons) --> {poly1: indices_of_points, poly2: indices_of_points...}
```

My understanding is that this would be trivial to handle if we had an R-tree mapping `points --> integer position` and then queried for the points that intersect with an arbitrary polygon.

Eventually we could skip the step of calling groupby on the Index and try to hook into pandas internals, but for now, it might be easier to just create an array of polygons for pandas to group by hashing, i.e.:

```
{poly1: [0, 3, 5], poly2: [1, 2], poly3: [4]} --> [poly1, poly2, poly1, poly4, poly1]
```

It does some duplicate work (because it'll group on the hash of each polygon), but it makes our own code much simpler.

This makes sense for grouping an arbitrary GeoSeries a single time if you don't shuffle or make any other changes (or if we used an integer index) and is probably a good place to start.  Things will get a little more complicated if we want to reuse the same R-tree across multiple objects -- maybe we can come up with some sort of intermediate hash mapping (or buckle down and create a GeoIndex :P).  Don't have any great ideas, but reusing Categorical could be an easy way to handle this. (i.e. a geo column would be an integer column internally to pandas, but we keep track of a separate categorical that translates those integers to level labels, or maybe have a 'hidden' integer column).

**Comment by prithwi** [comment]
Was wondering whether this can also lead to something of a spatial resample function?

for example: with a lat-lon grid based system, one may want a resampled GeoDF with a resolution of 10m in radial distance?

**Comment by martinfleis** [comment]
The original idea can be achieved by `sjoin`. The other idea floated here is now implemented as `dissolve`. 

Resampling can be in one form achieved by sjoin and dissolve together or using the dedicated `tobler` package.
