### ISSUE TITLE
Failing to Install via Conda/Pip/Git

### ISSUE THREAD

**Issue by fillipefeitosa** [geopandas/geopandas#712]
Using miniconda, failing to install Geopandas usign all the 3 methods described on the tutorial. Here is my output:

```
(jupyter) pi@raspberrypi:~ $ pip install git+git://github.com/geopandas/geopandas.git

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+git://github.com/geopandas/geopandas.git
Cloning git://github.com/geopandas/geopandas.git to /tmp/pip-req-build-5_r4_9k_
Collecting pandas (from geopandas==0.3.0+60.gce8f70c)
  Using cached 

https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz

  Could not find a version that satisfies the requirement numpy==1.9.3 (from versions: )

No matching distribution found for numpy==1.9.3
```
Can anyone please help? I intend to use it with Jupyter notebooks, already configured.
This is my numpy version:

```
import numpy
numpy.version.version
'1.14.0'
```
Cant find this 1.9.3 on the site though... Am I doing something wrong?

**Comment by jorisvandenbossche** [comment]
It's on pandas that it is failing, not geopandas, see here for more information: https://github.com/pandas-dev/pandas/issues/20775. Best to install pandas first separately

**Comment by jorisvandenbossche** [comment]
If you are using conda, you can do `conda install geopandas` instead of installing it with pip.

**Comment by fillipefeitosa** [comment]
I am using Raspberry Pi 3 model B, with miniconda
Here is my output:
```
(jupyter) pi@raspberrypi:~ $ conda install geopandas
Fetching package metadata .....

PackageNotFoundError: Package missing in current linux-armv7l channels: 
  - geopandas

Close matches found; did you mean one of these?

    geopandas: pandas

```

**Comment by ocefpaf** [comment]
You should get it from conda-forge:

```shell
conda install -c conda-forge geopandas
```

Ideally you should create a new environment with the packages you will use with:

```shell
conda create --name GEO -c conda-forge geopandas ...
```

**Comment by fillipefeitosa** [comment]
Thanks for your response @ocefpaf 

It seems that geopandas does not like arm7.
```
(jupyter) pi@raspberrypi:~ $ conda install -c conda-forge geopandas
Fetching package metadata .......

PackageNotFoundError: Package missing in current linux-armv7l channels: 
  - geopandas

Close matches found; did you mean one of these?

    geopandas: pandas, django-pandas

```

I know that the best thing is to create the separate enviroment, but right now I have limited resources, and I Need a Jupyter Notebook to run different kinds of libs... Right now does not seem right to configure one dedicated to use with geopandas

**Comment by fillipefeitosa** [comment]
Is there anyway to hard-install geopandas? It seems that it is not supported on rapsberry pi

```
(jupyter) pi@raspberrypi:~ $ conda search geopandas --channel conda-forge
Fetching package metadata .......
(jupyter) pi@raspberrypi:~ $ 

```

**Comment by fillipefeitosa** [comment]
Thanks for your response. I posted the same question as commented.
