### ISSUE TITLE
How to define boundary numbers without decimal points - Choropleth

### ISSUE THREAD

**Issue by realcodingmonster** [geopandas/geopandas#713]
**Problem**     
The numbers in a legend has the decimal points (eg. 0.00-4.80 at the top of the legend box), when I want them to be integers without decimal points. All I care is that the boundary values are integers. It doesn't matter whether a certain region in a choropleth is labelled as the category A or B, as long as the A, B and other categories are separated by the integer values so that legend box shows only integer separations.

 It's because I am making these maps for publishing articles after the Korean election is over. It would be much easier for the newspaper readers to have the integer numbers in legend!

**My current graph**  
![eng](https://user-images.githubusercontent.com/34431729/39658689-318706d6-5053-11e8-8b8a-3837ee59e1a9.png)

**My code**  

    import geopandas as gpd
    import matplotlib.pyplot as plt
    
    plt.xkcd()
    seoul=gpd.read_file('../json/seoul_municipalities_geo.json')
    # You can download the same file from the Github below
    # https://github.com/southkorea/seoul-maps/tree/master/juso/2015/json

    data_result.plot(figsize=(14,10),linewidth=0.25, edgecolor='black', column='ESRI_PK',cmap='Blues',scheme='quantiles',legend=True)
    
    for index,row in seoul.iterrows():
        xy=row['geometry'].centroid.coords[:]
        xytext=row['geometry'].centroid.coords[:]
        plt.annotate(row['SIG_ENG_NM'],xy=xy[0], xytext=xytext[0],  horizontalalignment='center',verticalalignment='center')
        plt.axis('off')
        
    plt.show()

  [1]: https://i.stack.imgur.com/VUleG.jpg

**Comment by jdmcbr** [comment]
@realcodingmonster Unless I'm misunderstanding, this looks like a usage question for which stackoverflow is the more appropriate venue (and I see that you've already posted there). @jorisvandenbossche most notably, but other members of the community here, myself included, keep an eye on those sorts of questions, so there's no need to post in both places.
