### ISSUE TITLE
How to fill the color in choropleth map in absolute value, rather than relative value?

### ISSUE THREAD

**Issue by realcodingmonster** [geopandas/geopandas#714]
**Problem**     
I need to make a series of choropleth maps every one hour after the election is over. As the poll is counted, I need to fill the color in choropleth map of seoul to show how many poll is counted. For example, the stronger the color, the bigger percentage of total poll is counted.

What geopandas does for me is to fill in the colors based on relative values of different region's vote counting rate. What I want is, however, that vote counting rate is shown in absolute value.

For example, let's assume that we have 3 regions, A,B,and C in total. 
At 7 p.m. the vote counting rates of each region are : {'A':10%, 'B':20%, 'C':30%}
At 8 p.m., {'A':30%, 'B':50%, 'C' : 80%}
...
At 12 p.m., {'A': 80%, 'B':90%,'C':100%}

Geopandas always fills in A region the lightest color, while C region the strongest color. It's because at every time, A has the lowest voting rate out of three regions. However, what I want to show in a map is that I want A's color would get stronger as time goes by since the voting rates of A region also gets bigger.

 

**Screenshot of the problem**  
![eng](https://user-images.githubusercontent.com/34431729/39658717-b720e6ea-5053-11e8-8b10-26baa86886c6.png)
I want the color filling in regions of seoul will get stronger when I put a series of seoul maps together. It would allow people to see how many votes are counted just by looking at colors when the time goes by after the election is over and more votes are counted.

**My code**  

    import geopandas as gpd
    import matplotlib.pyplot as plt
    
    plt.xkcd()
    seoul=gpd.read_file('../json/seoul_municipalities_geo.json')
    # You can download the same file from the Github below
    # https://github.com/southkorea/seoul-maps/tree/master/juso/2015/json

    final_pic=data_result.plot(figsize=(14,10),linewidth=0.25, edgecolor='black', column='ESRI_PK',cmap='Blues',scheme='quantiles',legend=True)
    for index,row in seoul.iterrows():
        xy=row['geometry'].centroid.coords[:]
        xytext=row['geometry'].centroid.coords[:]
        plt.annotate(row['SIG_ENG_NM'],xy=xy[0], xytext=xytext[0],  horizontalalignment='center',verticalalignment='center')
        plt.axis('off')

**Comment by jdmcbr** [comment]
See comment in #713.
