### ISSUE TITLE
set axes('equal') on any axes, not just unprovided ones? 

### ISSUE THREAD

**Issue by ljwolf** [geopandas/geopandas#715]
Hey,

got a bug report about some workshop code over in [ljwolf/geopython](https://github.com/ljwolf/geopython) noting that, whenever we map onto a multi-map figure, geopandas will not set the axes to `equal`. This means that any time you do a subplot with geopandas, you have to set those axes to equal manually for projected data to work right. 

Is this intended?

**Comment by ljwolf** [comment]
I should note this happens [here for series](https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L254) and [here for frames](https://github.com/geopandas/geopandas/blob/master/geopandas/plotting.py#L393).

**Comment by jorisvandenbossche** [comment]
Yes, so as can be seen in the linked code, we only set the axis aspect to `equal` if no `ax` is passed (so when fig/ax are created by geopandas). 
So currently, if you create the figure yourself (eg for having subplots), you indeed need to set the aspect yourself. 

I think this is intended, but the question is thus: do we want to extend this and *always* set the aspect to equal? Are there cases that the user would not want this?

**Comment by jorisvandenbossche** [comment]
Closed by #718
