### ISSUE TITLE
DOC: import geopandas recommendation

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#716]
Now in most places, we do

```
import geopandas as gpd
```

and it is certainly good to be consistent.

However, I wanted to check what the appetite is for changing this to a version without the aliasing. So just `import geopandas`, and then `geopandas.read_file(..)`, `geopandas.sjoin(..)`, ...
In case you use eg `GeoDataFrame` a lot, you can also do `from geopandas import GeoDataFrame`. 

The reason for this is that from some recent conversations, I got convinced that ideally, you choose a package name such that you don't need to shorten the import, as doing that creates additional overhead (it is less directly recognizable in the code where something is coming from if you are less familiar with the package, you get different aliases used in the wild, ..). 
I personally think `geopandas` is short enough (and you typically use mainly method calls) to not need an alias, but on the other hand, it might also be a bit late to change this.

**Comment by jdmcbr** [comment]
I'm with @kuanb on this one; so long as `import pandas as pd` is the standard, sticking with `import geopandas as gpd` seems like it is fairly clear.

**Comment by jorisvandenbossche** [comment]
Based on some discussions at Scipy, I think I am going to go forward and change this for the docs (I don't think that we should necessarily do the same as pandas, that's a much bigger package to change). But everybody is of course still free to do whatever he/she wants! :-)

**Comment by jorisvandenbossche** [comment]
https://github.com/geopandas/geopandas/pull/774
