### ISSUE TITLE
Unexpected behaviour when using e.g. .intersects(), .within()

### ISSUE THREAD

**Issue by asmith26** [geopandas/geopandas#720]
```
import shapely
import geopandas as gpd

p1 = shapely.geometry.Polygon([(0,0), (1,0), (1,1), (0,1)])
p2 = shapely.geometry.Polygon([(1,1), (2,1), (2,2), (1,2)])

s1 = gpd.GeoSeries([p1])
s2 = gpd.GeoSeries([p2])

s1.intersects(s2)

# Returns:  0    True
#           dtype: bool
```

However
```
p3 = shapely.geometry.Polygon([(1,1), (2,1), (2,2), (1,2)])

s2 = gpd.GeoSeries([p2, p3])

s1.intersects(s2)

# Returns:  0    True
#           1    False
#           dtype: bool
```
whilst I would expect `True`, `True`.

From https://github.com/geopandas/geopandas/issues/317#issuecomment-219516157, I learned that:
> When providing a GeoDataFrame/Series to GeoDataFrame.intersects, it will first align the calling object and provided object (match rows with **matching index**)

Thus I propose 2 solutions:
1. Make this behaviour clearer in the [documentation](http://geopandas.org/reference.html).
2. Possibly change geopandas to perform the expected behaviour.

Thanks for this awesome library!

**Comment by martinfleis** [comment]
Duplication of #750
