### ISSUE TITLE
Is there a prompt way to check a "not" spatial join?

### ISSUE THREAD

**Issue by aborruso** [geopandas/geopandas#726]
Hi,
I use `gpd.sjoin(points, polygons, op='within',how="inner")` to check if some points touch some polygons.

Is there a direct way to have the inverse, all the points that do not touch polygons?

Something like  `gpd.sjoin(points, polygons, op='within',how="outer")`.

Thank you

**Comment by jdmcbr** [comment]
I think `points.loc[points.disjoint(polygons.unary_union)]` might be what you're looking for?

**Comment by aborruso** [comment]
@jdmcbr thank you
