### ISSUE TITLE
Documentation updates to sjoin geopandas docs

### ISSUE THREAD

**Issue by lwasser** [geopandas/geopandas#732]
Hi All,
I'm working on class lessons and would really love to improve the geopandas documentation. To begin i'd like to update [sjoin docs](http://geopandas.org/mergingdata.html#spatial-joins) to include descriptions of the various arguments (which is actually quite good in the code). Are you amendable to my creating a PR with that update? i'm adding it to my lessons - so minus well add it here too - if it is acceptable to you all! :)

My update to this page would look something like:
```
### Sjoin Arguments:

The `op` argument specifies how geopandas decides whether or not to join the attributes of one object to another. There are three different join options:

* `intersects`: Returns True if the boundary and interior of the object intersect in any way with those of the other.
* `within`: Returns True if the object’s boundary and interior intersect only with the interior of the other (not its boundary or exterior).
* `contains`: Returns True if the object’s interior contains the boundary and interior of the other object and their boundaries do not touch at all.

<a href ="http://toblerity.org/shapely/manual.html#binary-predicates" target = "_blank">You can read more about each type here.</a>
 
The `how` argument accepts following options:

* 'left': use keys from left_df; retain only left_df geometry column
* 'right': use keys from right_df; retain only right_df geometry column
* 'inner': use intersection of keys from both dfs; retain only
          left_df geometry column 
```
Please let me know if this addition is reasonable and if you'd like me to contribute this in a different way! i'd like to work on some other parts of the docs too but i figured i'd start here.
Many thanks for your consideration.
leah

**Comment by jorisvandenbossche** [comment]
@lwasser That would be really great!

Already quick feedback: the "Returns True if" will sound a bit strange to a user I think, as it does not really return true, it rather combines the rows if that condition is true.

**Comment by lwasser** [comment]
oh wonderful. thanks @jorisvandenbossche . I have forked the repo and i'll work on some edits to the page and will submit a PR. i welcome any and all line by line feedback on my additions. i just want my students to have an easier time using geopandas because it really is fantastic. :) expect a PR in the next day!

**Comment by lwasser** [comment]
Can you kindly clarify this statement for me @jorisvandenbossche  ? i would like to understand how the op arguments vary with polygons and line so i can clarify! 

`these are all equivalent when joining points to polygons, but differ when joining polygons to other polygons or lines`

Many thanks!

**Comment by jorisvandenbossche** [comment]
Hmm, I actually don't think that statement is *completely* true. 
It is correct that 'intersects' and 'within' are often equivalent for a point-in-polygon join (unless the points fall exactly on a border of the polygon), but for polygon-polygon joins, 'itersects' and 'within' are clearly different. 

But given that it is not fully correct, maybe you can just remove it.

**Comment by lwasser** [comment]
Ok wonderful. Thank you. Last question. 
Should i edit the .rst file only to update the docs? I read through the pandas documentation about updating docs (as it was linked in your contributing file). but i didn't see a make.py file in your docs file nor did i see a build/html directory. This made me wonder if your doc contributing workflow was slightly different from pandas.

Many thanks for any guidance. Once i submit one pr i will better understand how to more efficiently update documentation!

**Comment by jorisvandenbossche** [comment]
Editing the .rst file is good. 
In principle you can also build the docs locally (that's what the `make.py` is doing in pandas, in geopandas we have a Makefile, so on linux/mac it is `make html`), but for a relatively small change, you can also directly push the .rst changes.

**Comment by lwasser** [comment]
Thank you very much @jorisvandenbossche  here is my initial pr.

https://github.com/geopandas/geopandas/pull/733

I welcome any and all comments / suggestions/ feedback.

**Comment by jorisvandenbossche** [comment]
Closing this issue, as the mentioned PR https://github.com/geopandas/geopandas/pull/733 has been merged long time ago.
