### ISSUE TITLE
jupyter notebook (and lab) kernel dies when showing geometry column

### ISSUE THREAD

**Issue by ljwolf** [geopandas/geopandas#736]
Hey, not sure if this is a jupyter update, or what, but I'm getting kernel death on:

```python
import geopandas as gpd
path = gpd.datasets.get_path('nybb')
df = gpd.read_file(path)
df.head()
```
but no death when
```python
df.drop('geometry', axis=1).head()
```
in both firefox and chrome in both jupyter notebook (5.0.0) and lab (0.32.1) using geopandas (0.3.0) on linux (ubuntu & arch). If this can't replicate, fine, but I've tried all I know how to fix it.

**Comment by jorisvandenbossche** [comment]
Hmm, I cannot replicate this (notebook 5.4 or jupyterlab 0.32.1)

Python version? And what shapely / geos version? and how installed? (conda/conda-forge/pip)

Do you see any messages in the console output where you started the notebook?

**Comment by jorisvandenbossche** [comment]
Do you also have it when you do `df.geometry` or `df.geometry.values` ?

**Comment by ljwolf** [comment]
Yes on `df.geometry`, no on `values`, so maybe it's a segfault in the wkt in shapely. I'll rip it up and see if it's just outdated `.so` files somewhere.

**Comment by ljwolf** [comment]
Yeah, looks like it's lower/beyond this. Checking the logs: 

`python: geos_ts_c.cpp:289: char* {anonymous}::gstrdup_s(const char*, std::size_t): Assertion `0 != out' failed.`

happens right when the `df.head()` call is made.

**Comment by shubham2323** [comment]
How did you solve this issue??

**Comment by Luke-Shaw** [comment]
I'm using conda: many things I tried didn't work (updating any/all packages and trying older versions), but what was successful fixing this issue was a complete Anaconda uninstall and reinstall.
