### ISSUE TITLE
buffer not being created in same unit as crs

### ISSUE THREAD

**Issue by Taveras318** [geopandas/geopandas#737]
I have a geodataframe with crs = {'init': 'epsg:2263'}
these are my points:
`students.plot()`
![image](https://user-images.githubusercontent.com/24798202/41061903-2a829f68-69a2-11e8-9006-099b64be5281.png)

if I run the following code:
```
buffs = students.geometry.buffer(50)
buffs.plot()
```
I get the following plot:
![image](https://user-images.githubusercontent.com/24798202/41061515-dd70f0b8-69a0-11e8-8909-d275ea939129.png)

How do I create buffers measure in feet around my points?

**Comment by jorisvandenbossche** [comment]
@Taveras318 Are you sure the data is in the EPSG:2263 system? According to http://epsg.io/2263 it should have a much bigger range (higher values for x / y than are on the plot). From the plot it rather looks your data is in latitude/longitude degrees. 

Can you show a full code example?

**Comment by Taveras318** [comment]
@jorisvandenbossche Thank you for the reply.

So my data is originally in lat,long. I then run this code 
```
def make_geodf(df,lat,lng):
    geometry = [Point(xy) for xy in zip(lat, lng)]
    crs = {'init': 'epsg:4326'} #http://www.spatialreference.org/ref/epsg/2263/
    geo_df =gp.GeoDataFrame(df,crs=crs, geometry=geometry) 
    return geo_df
```
Does that not re-project the data? If not what should I do?

**Comment by jorisvandenbossche** [comment]
You still have to actually convert it with `to_crs`:

```
crs = {'init': 'epsg:4326'} #http://www.spatialreference.org/ref/epsg/2263/
geo_df =gp.GeoDataFrame(df,crs=crs, geometry=geometry) 
geo_df = geo_df.to_crs(epsg=2263)
```

**Comment by Taveras318** [comment]
@jorisvandenbossche 
My apologies, initially I was actually running 
```
def make_geodf(df,lat,lng):
    geometry = [Point(xy) for xy in zip(lat, lng)]
    crs = {'init': 'epsg:2263'} #http://www.spatialreference.org/ref/epsg/2263/
    geo_df =gp.GeoDataFrame(df,crs=crs, geometry=geometry) 
    return geo_df
```
Now I am running 
```
def make_geodf(df,lat,lng):
    geometry = [Point(xy) for xy in zip(lat, lng)]
    crs = {'init': 'epsg:4326'} #http://www.spatialreference.org/ref/epsg/2263/
    geo_df =gp.GeoDataFrame(df,crs=crs, geometry=geometry)
    geo_df = geo_df.to_crs(epsg=2263)
    return geo_df
```
and I am getting these results, which still look quite off.
![image](https://user-images.githubusercontent.com/24798202/41106534-32ffb01c-6a3e-11e8-81f5-5ede305b66e4.png)

appreciate the help.

**Comment by jorisvandenbossche** [comment]
@Taveras318 just to be clear (I don't know the data), what is exactly "looking off"? 
What is it that seems wrong? Maybe also plot the data before and after doing the buffer, as it might not be related to that.

**Comment by jorisvandenbossche** [comment]
And I also just see, a possible reason there is something wrong, is because you switched latitude and longitude (it should be `zip(lng, lat)` instead, as longitude is x and latitude is y)

**Comment by Taveras318** [comment]
@jorisvandenbossche thank you very much!
