### ISSUE TITLE
[Question] -Unary_union

### ISSUE THREAD

**Issue by JakeMinerva** [geopandas/geopandas#738]
I am new to using geopandas and didnt know where else to ask this question. 
I am trying to group points into clusters, to do so I want to buffer the points, then dissolve the buffers so that I have a set of polygons, I can do a spatial join of the points to the dissolved buffers. This will give me an indication of which points are in the same cluster. 
The issue I am having is that after I buffer the points, If I use unary_union to dissolve the buffers I get a multipolygon. 
So my question is, is there a better way to do this so that the result of my dissolve is a geoseries or a gdf? And if not how can I get the multipolygon back into a gdf so I can continue to work with it.
Thanks, I will appreciate any help

**Comment by debboutr** [comment]
it seems like you want to do a spatial join to find points w/in each buffered point? if so, you can iterate each buffer and do a sjoin to find the points w/in it. _this seems more like a Q for gisstackexchange_

**Comment by JakeMinerva** [comment]
I do want to do a spatial join but not on each buffered point, on dissolved buffered points (aka buffer with dissolve). Okay I will post to gisstackexchange

**Comment by JakeMinerva** [comment]
https://gis.stackexchange.com/questions/285595/buffer-with-dissolve-geopandas-unary-union-multipolygon
