### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by mazzma12** [geopandas/geopandas#743]
Minor issue, but the link [remotesensing.org.](https://www.remotesensing.org/geotiff/proj_list) is broken in your doc on the page [managing projections](geopandas.org/projections.html#managing-projections)

**Comment by jdmcbr** [comment]
Thanks! Just removed that from the source, though that won't be appear on geopandas.org until we release, and won't appear on readthedocs until we fix our recent build issues.
