### ISSUE TITLE
Passing `cap_style` kwarg to buffer

### ISSUE THREAD

**Issue by mazzma12** [geopandas/geopandas#744]
`shapely` implements several kwarg for the `shapely.geometry.base.BaseGeometry.buffer()` method but only 2 are available in `geopandas`.
I would like to authorize the use of the `cap_style` argument to have a square buffer for example. 

Is it designed for a matter of compatibility ? Or maybe did the other kwarg have appeared recently.

**Comment by jorisvandenbossche** [comment]
@mazzma12 Thanks for the idea. There was no good reason for this, and in the meantime it has already been fixed in master: https://github.com/geopandas/geopandas/pull/535. This will be included in the next release
