### ISSUE TITLE
GeoDataFrame.to_file fail on date column

### ISSUE THREAD

**Issue by leblancfg** [geopandas/geopandas#746]
Similar to #437, I get a `ValueError` when trying to pass a datetime / timestamp column to `to_file`:

~~~python
import geopandas as gpd
import pandas as pd

gdf = gpd.read_postgis(query, con)  # These are defined elsewhere

# Make sure 'year' is type 'datetime'
gdf['year'] = pd.to_datetime(gdf['year'], format='%Y')

gdf.to_file('test.shp')

>>> ValueError: Invalid field type <class 'pandas._libs.tslib.Timestamp'>
~~~

Discussion and workaround solution are [on StackOverflow](https://gis.stackexchange.com/questions/281895/changing-shapefiles-field-type-using-fiona/):

~~~python
schema = gpd.io.file.infer_schema(gdf)
print(schema)

>>> {'geometry': 'Point',
     'properties': OrderedDict([('npri_id', 'int'),
                   ('facility', 'str'),
                   ('year', 'int'),
                  ...])}
~~~

In my example, I want to change `year`'s datatype to datetime.

~~~python
schema['properties']['year'] = 'datetime'
gdf.to_file('test.shp', schema=schema)
~~~

Which does indeed work, as tested on ArcGIS Desktop.

Suggest this be integrated in GeoDataFrame's `to_file` logic so that the user doesn't have to manually do these steps.

**Comment by leblancfg** [comment]
Also, see https://github.com/Toblerity/Fiona/issues/572

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/geopandas/geopandas/pull/728
