### ISSUE TITLE
suggestion: Dissolve entire GDF by default

### ISSUE THREAD

**Issue by skoeb** [geopandas/geopandas#752]
If I want to merge all polygons in a gdf, the current workflow is:
gdf['Constant'] = 1
gdf.dissolve('Constant')

I suggest that by default, this should be an easy one liner. 
gdf.dissolve()

**Comment by jorisvandenbossche** [comment]
And you don't want `gdf.geometry.unary_union` ? 
That would be sufficient if you are only interested in the dissolved geometries. If you also want the aggregated columns, then you of course need the `dissolve`.

**Comment by martinfleis** [comment]
Duplication of more recent #1380.
