### ISSUE TITLE
Geocoding doesn't work with latest version of geopy

### ISSUE THREAD

**Issue by choldgraf** [geopandas/geopandas#753]
In the latest geopy, they removed the Yahoo geocoder. Geopandas checks for this and throws an exception, even if "yahoo" isn't specified as the provider.

https://github.com/geopy/geopy/blob/12c3fc5b292f36d465242d0c1776a0fbbaacbde5/docs/changelog_1xx.rst#changelog

**Comment by jdmcbr** [comment]
I think this is a duplicate of #739, which was resolved on master (and for which I made a very similar comment...).

**Comment by jorisvandenbossche** [comment]
.. :-)

**Comment by choldgraf** [comment]
yep! working off of master got it working, thanks folks :-)
