### ISSUE TITLE
Default of 'geom' vs gpd 'geometry' geom column name

### ISSUE THREAD

**Issue by tgrushka** [geopandas/geopandas#755]
There seems to be an inconsistency in that read_postgis and read_sql expect a geometry column of 'geom' (which is standard in PostGIS) vs. the GeoPandas expected 'geometry' column name.

To make PostGIS imported GeoDataFrames play nicely and consistently (when merging, for example), I either have to:
1. Rename my column 'geom AS geometry' in SQL, and set geom_col = 'geometry';
2. Somehow rename the column later, which doesn't seem to work:

gdf = gdf.rename({'geom': 'geometry'}, axis = 1)

... BUT, that causes errors in functions such as gpd.overlay, which EXPECTS the column to be named 'geom', fails if it's been renamed to 'geometry', YET OUTPUTS a gdf with geom column renamed to 'geometry'!!!

This seems like a bug. It's either a bug in the sql function not returning the geom column (whatever it's name) as the expected GeoDataFrame 'geometry' column, or a bug in the other GeoPandas functions requiring 'geometry' as the column name for their input.

Seems like we're reinventing the wheel here somewhere. Some people like 'geometry' and others like 'geom'. Why can't we just pick one, stick with it, and make it import seamlessly regardless of data source?

**Comment by ljwolf** [comment]
Where, specifically, does this create an issue coming from postgis? I'm a bit confused as to your question... geopandas is fairly consistent in referring to `table.geometry` as the geometry, even though that obejct's column name can change. You don't have to query `geom as geometry` and use `geom_col='geometry'` (your option 1)... you can get away with using only `geopandas.read_postgis(..., geom_col='whatever_you_use_in_the_database')`

### An example.  

I use `the_geom` in my postgis database as the name of the geometry column for some of my data I loaded when I was at [CARTO](https://github.com/carto/cartoframes). 

Now, when I query that:

```python
import geopandas as gpd
# say my connection is known as `cxn`

table = gpd.read_postgis('select * from house2016 limit 2', eng, geom_col='the_geom')
```
This means the table's active geometry column is named `"the_geom"`. So, they're stored in the column named `the_geom`:
```python
table['the_geom']
0    POLYGON ((-94.61783299999999 36.49943799999993...
1    POLYGON ((-94.48585705008509 33.63876820841313...
Name: the_geom, dtype: object
```
and the "active" geometry is this series as well:
```python
table.geometry # is the same as table['the_geom']
0    POLYGON ((-94.61783299999999 36.49943799999993...
1    POLYGON ((-94.48585705008509 33.63876820841313...
Name: the_geom, dtype: object
```
Note that `table.geometry.name` tells you the column name of the active geometry, which does not itself have to be `'geometry'`. You can name it whatever you like, and `read_postgis(...,geom_col='whatever_you_like')` will set it correctly on read.

Regardless of what `table.geometry.name` is, we can use geopandas like normal, even though the active geometry column isn't named `geometry`:
```python
table['buffers'] = table.buffer(2)
```
Now, say we want to switch or rename this column (your option 2). The `.geometry` attribute always points to the "active" geometry for the table, even though it can be named whatever you like:
```python
print(table.geometry.name)
# shows 'the_geom'
```
If you want to rename or switch geometry columns, you should use the `set_geometry` function:
```python
table.set_geometry('buffer', inplace=True)
print(table.geometry.name) # is now 'buffer'
table.rename({'the_geom':'shapes'}, axis=1, inplace=True)
table.set_geometry('shapes', inplace=True)
print(table.geometry.name) # is now 'shapes'
```

If you use `read_postgis(...,geom_col='whatever_the_database_column_name_is')`, are things fine on read?

**Comment by jorisvandenbossche** [comment]
Not much to add to the excellent explanation of @ljwolf! 
@tgrushka please note if that clears things up or not. PRs to clarify this better in the documentation are also always welcome.

One thing I was wondering, is that "renaming" your geometry column is not *that* easy, as now it always takes two steps (renaming + setting geometry column again):

```
gdf = gdf.rename(columns={'old_name': 'new_name'}).set_geometry('new_name')
```

would we like to try to simplify this? (a 'rename_geometry' or some other better way?)

**Comment by alephcero** [comment]
When uploading a GeoDataFrame to PostGIS it would be useful to have a method like this
```
to_postgis(...,geom_col='whatever_the_database_column_name_is')
```
This way, we can relly on the 'geom' standard in PostGIS. We could rename the active geometry column to `geom` before uploading it to postgis

**Comment by MaxDragonheart** [comment]
Any news about this issue?

**Comment by martinfleis** [comment]
@MaxDragonheart regarding the original report, that seems to be not an issue in fact. As per the suggestion above, `rename_geometry` has been implemented.

Regarding @alephcero's comment, no action has been taken but if you want your geometry column to be called `"geom"` in PostGIS, the current assumption is that you use `rename_geometry` before using `to_postgis`.

Or is there anything else you had in mind?

**Comment by MaxDragonheart** [comment]
I've the same need of @alephcero with `to_postgis`. I had to be much clearer into my first post, sorry.

**Comment by martinfleis** [comment]
@MaxDragonheart the discussion on that is in #1656. It got a bit stale as there was no response when I wanted to clarify the issue. Can you maybe describe your use case and the optimal solution (not necessary code-wise, just the behaviour) in #1656?

Since I don't think the report in the first post of this issue (re `read_postgis`) is valid anymore, I'll close this now and discussion on `to_postgis` can happen in #1656.
