### ISSUE TITLE
Pandas 0.23 .ix compatibility warning - new version release?

### ISSUE THREAD

**Issue by kuanb** [geopandas/geopandas#757]
The last released version of Geopandas, 0.3.0, utilized pandas methods that are being deprecated.

Example: `.ix` is used in `overlay.py`: https://github.com/geopandas/geopandas/blob/e48af9b2f990c333bc6c59c0f566cd919a3338d1/geopandas/tools/overlay.py#L145

This results in the following warning:
```
.../site-packages/geopandas/tools/overlay.py:145: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing
```

This issue has since been resolved (master of Geopandas no longer utilizes `.ix`). I wonder if it would be acceptable to put out a candidate for a 0.3.1 Geopandas version release. Is there anything preventing that? We can always peg to a specific git commit, but it seems sufficient work has progressed on Geopandas since Aug of 2017 to merit a new release. Also, this would "pair well" with the fact that pandas 0.23 has been released.

**Comment by jorisvandenbossche** [comment]
Yeah, I know a new release is long overdue .. But I want to get https://github.com/geopandas/geopandas/pull/429 in first for a 0.4.0. 

We could indeed think about a 0.3.1, but the question is a bit whether we then want to backport other fixes.

**Comment by kuanb** [comment]
I'm going to close this as there is no further action required with this issue.
