### ISSUE TITLE
ENH: ability to specify varying buffer sizes

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#767]
Now only a single fixed buffer size for the full GeoSeries can be specified, we could expand that to a different value for each geometry by passing a array/series of the same length.

**Comment by mthh** [comment]
Hi!

It would be nice to have this new feature!
(and I guess it's also possible to use the same approach for the `distance` argument of the `interpolate` method)

Can I assign myself for this task?

**Comment by jorisvandenbossche** [comment]
@mthh Yes, PRs are welcome!
