### ISSUE TITLE
mitigate none-to-zero issues

### ISSUE THREAD

**Issue by ljwolf** [geopandas/geopandas#776]
In light of toblerity/fiona#604, it may be helpful to warn users of the unexpected behavior if we can detect their configuration. 

It makes me nervous that this bug so clearly affects scientific users. We may read large datasets not knowing whether there are missing values. Often, it is not under the user's control whether there is missing values in their data or not. This now explains an inconsistency between my laptop and lab computers on some statistical tests I was conducting. 

If a warning is not appropriate, could we then remove our suggestion on how to install geopandas using `pip` in the `README`?

**Comment by jorisvandenbossche** [comment]
> If a warning is not appropriate, could we either remove our suggestion on how to install geopandas using pip in the README?

I was going to update that anyhow before the release (putting conda first, and saying that with pip you need to install the dependencies as well)

But, to come to your actual suggestion. I am not sure if we can easily detect how fiona is installed

**Comment by ljwolf** [comment]
Bummer. 

If we can't, I think altering the documentation would be sufficient.

**Comment by jorisvandenbossche** [comment]
Good news! Fiona is doing a bug-fix release: https://github.com/Toblerity/Fiona/issues/608
