### ISSUE TITLE
Conda install fails, no 0.4.0 available in Anaconda repository

### ISSUE THREAD

**Issue by deeplook** [geopandas/geopandas#788]
I'm trying to install geopandas on a fresh Anaconda3 (Py3.6) build on OSX using `conda install -c conda-forge geopandas`, but I'm getting a confusing output like this below, listing only v. 0.3.0. And effectively, 0.4.0 is not listed here: https://repo.anaconda.com/pkgs/main/osx-64/ or https://repo.anaconda.com/pkgs/main/linux-64/. Is there any workaround?

```
(base) $ conda install -c conda-forge geopandas
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - geopandas
Use "conda info <package>" to see the dependencies for each package.
```

Apparently I can install 0.4.0 with `pip install geopandas`, but I'm not sure this really gets all dependencies right.

**Comment by jorisvandenbossche** [comment]
Hmm, that's strange, since you specify `-c conda-forge`. 
We have built 0.4 packages for the conda-forge channel, but indeed Anaconda did not yet do that for the defaults channel.

But normally then installing it from the conda-forge channel should do that. And it is in any case a very confusing / non-informative error message of conda ..

cc @ocefpaf

**Comment by ocefpaf** [comment]
I'm re-building the stack so some inconsistencies may happen in the next few days.
I'll get back here once I finish some keys re-builds to check if this one got sorted out.

**Comment by ocefpaf** [comment]
@jorisvandenbossche @deeplook  I detect that `qt`, via `matplotlib` here, is the culprit. I'm rebuild everything to get there but `qt` is a very hard and it should take a while for me to finish.

**Comment by jorisvandenbossche** [comment]
@deeplook is this issue resolved for you in the meantime?

**Comment by ocefpaf** [comment]
@deeplook at the moment the state of conda when dealing with multiple channels is completely broken. See https://github.com/conda/conda/issues/7626

I recommend you to use only `defaults` if you don't need `conda-forge` packages, or only `conda-forge` if you do.

**Comment by jorisvandenbossche** [comment]
OK, closing this one.

**Comment by ocefpaf** [comment]
> OK, closing this one.

It was never a geopandas issue BTW. It is a conda/conda-forge issue.
