### ISSUE TITLE
How to install geopandas in pipenv without condas in Python 3.7

### ISSUE THREAD

**Issue by milieu** [geopandas/geopandas#793]
I was previously running into clang issues when I ran a straight `pipenv install geopandas`. After forays into using condas, then realizing I didn't strictly need condas to install dependencies and that conda and pipenv don't play well together for this particular project despite being able [to point pipenv to the condas libraries](https://github.com/pypa/pipenv/issues/1469#issuecomment-371810107) (Compiled C wasn't able to handle changed pathing once in a `pipenv shell`?)...

I ended up removing my condas environment, and doing this in my pipenv:

```
pipenv install numpy
pipenv install pandas
pipenv install shapely
pipenv install fiona
pipenv install six
pipenv install cython
pipenv install git+https://github.com/jswhit/pyproj.git#egg=pyproj
pipenv install geopandas
```

PyProj needed to be installed from the git repository because their PyPI is outdated: https://github.com/jswhit/pyproj/issues/136

Verified that is works by doing a `pipenv --rm` and `pipenv install` from scratch and importing geopandas successfully in a python repl after `pipenv shell`

**Comment by milieu** [comment]
Hopefully this saves someone all the time it took me to figure the above out

**Comment by chazanov** [comment]
Pip is not good, better use your distro's package manager!

**Comment by dheerajchand** [comment]
Not to derail, but why do you suggest not using `pip`?

**Comment by jorisvandenbossche** [comment]
There are good use cases of `pip`, but the problem with pip, specifically for the geospatial stack, is that it will not install all the required dependencies properly (specifically non-python ones like gdal, proj, libspatialindex). 
I personally recommend to use `conda`, and there all non-python dependencies are packaged as well and properly handled.

**Comment by milieu** [comment]
¯\_(ツ)_/¯ I figured we had a troll

I was using pipenv and not condas simply because I didn't want to introduce a new setup flow to the project I was working with

If I started using condas I'd probably already have the whole app Dockerized for deployment at that point

**Comment by mayanksuman** [comment]
@jorisvandenbossche It is possible to install geospatial stack using pip. For example to install pygdal confirming to system gdal, I use following command on debian box
```shell
pip3 install  GDAL==$(gdal-config --version) --global-option=build_ext  --global-option=-I/usr/include/gdal
```
That being said the problem with geopandas installation on python3.7 is actually pyproj as the last version uploaded on [PyPI](https://pypi.org/project/pyproj/#files) is more than 2yrs old.

**Comment by martimpassos** [comment]
Does this apply to Windows or Unix only? For me the issue is with `pipenv install fiona`, caused by GDAL. I know this is a known issue and I've been in and out of it for the past two years. Had solved it by using Docker in my project but now would like to drop it and use a pipenv venv only. I dug stackoverflow, youtube and whatnot, even managed to properly install GDAL by using the wheel available [here](https://www.lfd.uci.edu/~gohlke/pythonlibs), but Fiona always fails to install inside the virtual environment. The closest I could get was `pipwin` installing it but as I understand it this also installs it globally. Are there any news on how to install geopandas in a Windows 10 machine with pipenv instead of Conda?

**Comment by milieu** [comment]
@martimpassos if I were developing on a Windows machine I'd try using WSL - I've had someone in my workplace say they had a good experience with it. https://docs.microsoft.com/en-us/windows/wsl/install-win10 -- and then once I had a WSL setup ready then using linux dependencies as usual 🤞

**Comment by milieu** [comment]
Closing this issue since my goal in opening this was as a PSA on how to solve this.
