### ISSUE TITLE
binder ImportError

### ISSUE THREAD

**Issue by jGaboardi** [geopandas/geopandas#797]
When launching a binder and opening the notebooks in `examples/` there are `ImportError` for:

- `matplotlib` (choropleths, overlays, and spatial_joins) 

- `pysal` (choropleths)

This seems to be due to `matplotlib` and `pysal` not being declared as dependencies in `requirements.txt`. I am aware they are not `geopandas` dependencies, but in order to run the binder interactively maybe a separate `binder.yml` must be built? I am not exactly sure how to solve this issue.

**Comment by jorisvandenbossche** [comment]
Yep, thanks for the report. We might also want to add a environment.yml file instead (for using conda).

Also, the latest sphinx gallery has the option to launch binder from their examples, so that is also something that we could check.

**Comment by jGaboardi** [comment]
@jorisvandenbossche good ideas. I am also looking to implement this in [pysal/spaghetti](https://github.com/pysal/spaghetti) since most notebooks require plotting and some other non-dependency library.

**Comment by jorisvandenbossche** [comment]
Basically, if there is a `environment.yml` file, binder will take this first and not the `requirements.txt`, see https://mybinder.readthedocs.io/en/latest/using.html#preparing-a-repository-for-binder

**Comment by jorisvandenbossche** [comment]
In geopandas' case, we already have such a file for the documentation: https://github.com/geopandas/geopandas/blob/master/doc/environment.yml, so maybe we could somehow re-use that

**Comment by martinfleis** [comment]
I believe that our binder environment works properly now (on main).
