### ISSUE TITLE
Empty overlay intersection causes error

### ISSUE THREAD

**Issue by ozak** [geopandas/geopandas#799]
The new implementation of ``overlay`` generates an error if the intersection is empty. Here is a reproducible code:

```python
import geopandas as gpd
from geopandas.tools import overlay
from shapely.geometry import Polygon
polys1 = gpd.GeoSeries([Polygon([(0,0), (2,0), (2,2), (0,2)]),Polygon([(2,2), (4,2), (4,4), (2,4)])])
polys2 = gpd.GeoSeries([Polygon([(-1,-1), (-3,-1), (-3,-3), (-1,-3)]),Polygon([(-3,-3), (-5,-3), (-5,-5), (-3,-5)])])
df1 = gpd.GeoDataFrame({'geometry': polys1, 'df1':[1,2]}, crs={'init': 'epsg:4326', 'no_defs': True})
df2 = gpd.GeoDataFrame({'geometry': polys2, 'df2':[1,2]}, crs={'init': 'epsg:4326', 'no_defs': True})
gpd.tools.overlay(df1, df2, 'intersection')
```

I will try to provide a PR tonight.

**Comment by jorisvandenbossche** [comment]
Closed by #800

**Comment by jorisvandenbossche** [comment]
For people searching for it, the error was: KeyError: "['__idx1' '__idx2'] not found in axis"

**Comment by jorisvandenbossche** [comment]
Yes, thanks @drnextgis

**Comment by martinfleis** [comment]
@GCBallesteros Can you provide an example code? This should not happen.

**Comment by GCBallesteros** [comment]
@martinfleis  Sure thing. At the bottom you have two GDrive links to tiny feather files that can reproduce the issue. The code in that case is simply:
```
import geopandas as gpd

gdf1 = gpd.read_feather("gdf_1.feather")
gdf2 = gpd.read_feather("gdf_2.feather")

gpd.overlay(gdf1, gdf2)
```
I also created a small pyenv to reproduce the problem. Its pip freeze follows:
```
attrs==21.2.0
certifi==2021.10.8
click==8.0.3
cligj==0.7.2
Fiona==1.8.20
geopandas==0.10.1
munch==2.5.0
numpy==1.21.2
pandas==1.3.3
pyarrow==5.0.0
pyproj==3.2.1
python-dateutil==2.8.2
pytz==2021.3
Rtree==0.9.7
Shapely==1.7.1
six==1.16.0
```

DataFrame 1: https://drive.google.com/file/d/1QclfH3k51Lu0kux9ImY3vznRrt5bdmLE/view?usp=sharing
DataFrame 2: https://drive.google.com/file/d/1t2Ub6Iy3OrssWQZj2YY-6DofdKsBKXDP/view?usp=sharing
