### ISSUE TITLE
testing.py functions are not included in readthedocs API reference

### ISSUE THREAD

**Issue by goldenberg** [geopandas/geopandas#805]
I was just about to implement an `assert_geodataframes_almost_equal`, and decided to first go hunting and found the recently exposed `geopandas.testing` methods.

But they don't seem to be listed in the readthedocs API reference https://geopandas.readthedocs.io/en/latest/reference.html

It would be great to expose their docs here for users. See #707 for the implementation of exposing these methods.

**Comment by jorisvandenbossche** [comment]
@goldenberg that's a good point! PR to add those is very welcome

**Comment by goldenberg** [comment]
I'd be happy to put together a PR, but could use a pointer to how to do it, and rebuild the docs. Is this something that's configured here: https://github.com/geopandas/geopandas/blob/master/doc/source/conf.py

Thanks!

**Comment by jorisvandenbossche** [comment]
You can add it to https://github.com/geopandas/geopandas/blob/master/doc/source/reference.rst (I would add a similar autosummary table as currently for the "API pages" entry (https://github.com/geopandas/geopandas/blob/master/doc/source/reference.rst#api-pages), but then separate for "testing utilities" or something like that.

There is some explanation about building the documentation here: https://geopandas.readthedocs.io/en/latest/contributing.html#updating-the-documentation, but it is rather short, so if you have any other questions, don't hesitate to ask!
