### ISSUE TITLE
Add checks to `contains` so that it fails when a non `shapely` object is passed

### ISSUE THREAD

**Issue by mazzma12** [geopandas/geopandas#809]
From the documentation of `GeoDataFrame.contains()`: 

```python
Parameters
----------
other : GeoSeries or geometric object
    The GeoSeries (elementwise) or geometric object to test if is
    contained.
```
In version `0.0.4` passing a `GeoDataFrame` or a "full" `GeoSeries` pass silently but returns only `False`,  which is misleading. 

Here is an example to reproduce:
```python
import geopandas as gpd

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
capitals = gpd.read_file(gpd.datasets.get_path('naturalearth_cities'))
world.contains(capitals.iloc[1:]).sum() # shall fail
world.contains(capitals.geometry.iloc[:3]).sum() # shall fail ? 
world.contains(capitals.geometry.iloc[3]).sum() # works
```

I do not know in what extent type checking is easy to do, but I think it would be great to let it fails explicitly. I find also that the mention of " GeoSeries (elementwise) " in the doc is not really clear to me.
If by this it refers to `gdf.geometry.iloc[x]` it is only a shapely object. That could be misleading, as passing a `GeoSeries` might lead to a case described above. 

EDIT: Maybe a clearer description found in this article : https://michelleful.github.io/code-blog/2015/04/29/geopandas-manipulation/  at  #Clearing up a Pandas misunderstanding

**Comment by jorisvandenbossche** [comment]
Thanks for the report! 
This is expected behaviour, but indeed can be surprising / confusing. Related to https://github.com/geopandas/geopandas/issues/750, and the documentation can certainly be improved.

**Comment by mazzma12** [comment]
Nice, it's really related indeed, I see that you pointed the problem out already. I think we can close this one as duplicated and continue the discussion there.

**Comment by jdmcbr** [comment]
Thanks @mazzma12. For future reference, you can close your own issues.
