### ISSUE TITLE
How to cite Geopandas in an academic paper?

### ISSUE THREAD

**Issue by cossatot** [geopandas/geopandas#812]
Hi all, and thanks for the wonderful work.

I'm writing a couple papers detailing a [database of the world's seismically-active faults](https://github.com/GEMScienceTools/gem-global-active-faults/) which relies heavily on GeoPandas for the geoprocessing, and I would like to credit the developers for their very useful efforts. What's the preferred way of citing it?  Is there any interest in making a DOI through Zenodo or other means?  Are there any recent or authoritative papers or conference presentations?

Thanks!
Richard

**Comment by jorisvandenbossche** [comment]
@cossatot Nice to hear GeoPandas is being used for such a project!

Unfortunately, there is currently not really a way to cite GeoPandas. I have the vague plan to write a paper for JOSS (https://joss.theoj.org/), but it is not in the top of my to do list .. 
What I could (and maybe should) do is making a doi with Zenodo for the last release. Would that be suitable for you?

**Comment by ocefpaf** [comment]
> What I could (and maybe should) do is making a doi with Zenodo for the last release. 

While I agree that a JOSS paper would be nice a Zenodo DOI is quick and solve the citation problem in the short-term. +1 for that. (I have use for it right away :smile:)

**Comment by jorisvandenbossche** [comment]
The only problem is that I did not find an easy way to automatically generate a Zenodo release for an *existing* github release, seems you can only do that for new releases after enabling the integration ...

**Comment by ocefpaf** [comment]
Yes. that is annoying :-(

You'll have to re-issue a dummy release of the current release just to get the first DOI minted.

**Comment by cossatot** [comment]
@jorisvandenbossche a Zenodo DOI would work fine--this is what I use personally. I agree that it's a pain to go back and make a duplicate release, though.  Thanks!

**Comment by jorisvandenbossche** [comment]
I will try to at least make a Zenodo DOI for the upcoming 0.5 release.

Anybody advice on how to handle authorship? Adding all contributors to a certain release (but what with people who contributed to earlier releases)? Or listing the current core devs? (but then the question is still who to list of the historical core devs ...)

**Comment by martinfleis** [comment]
I would follow the example of QGIS (https://www.qgis.org/en/site/getinvolved/faq/index.html). They recommend citing as “`QGIS Development Team (YEAR). QGIS Geographic Information System. Open Source Geospatial Foundation Project. http://qgis.osgeo.org`", so GeoPandas might be similar. If you put authors as GeoPandas Development Team it feels safe to me and everyone can then look who is in the team of contributors.

**Comment by jorisvandenbossche** [comment]
I wanted to look into this again, to activate Zenodo, now the 0.5 release is (finally) imminent. 

But it appears I already unknowingly activated it (probably by looking at it last time) .. ;), and it already made a DOI for the 0.4.1 release: https://zenodo.org/record/2585849

I am not sure how it automatically created the author list. It put the two maintainers (in github permissions meaning, Kelsey and me) first, but then I don't really see a line it it. 
In any case, that made the manual choice on who to add as author a bit less urgent ..

**Comment by martinfleis** [comment]
Closed by #979
