### ISSUE TITLE
libncurses.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by aborruso** [geopandas/geopandas#818]
Hi, 
I have a mybinder project with these [settings](https://github.com/aborruso/bashnotebook/tree/master/binder) and the docker machine is created without problems.

When I import geopandas I have

    ImportError: libncurses.so.6: cannot open shared object file: No such file or directory

I know that it's not a geopandas problem but probably a conda one (see [here](https://github.com/conda-forge/pypy3.5-feedstock/issues/7)) but I do not how to solve and it's possible that someone of you knows how to  do it.

Thank you

**Comment by jorisvandenbossche** [comment]
It's rather an issue for conda-forge feedstock: https://github.com/conda-forge/geopandas-feedstock/

But, some things: is there a reason you are pinning libgdal to something very specific? (it should actually also not be needed to add gdal, libgdal, poppler to the environment file, as those are dependencies of geopandas anyway). 
Another thing: it should not be needed to install any gdal related libraries with apt.txt (eg the spatialite in there)

**Comment by aborruso** [comment]
@jorisvandenbossche ok thank you.

I'm doing a test with a cleaner environment. Than I will write to geopandas-feedstock

**Comment by shaunstoltz** [comment]
ImportError: libncurses.so.6: cannot open shared object file: No such file or directory
