### ISSUE TITLE
supports for ax in .plot() 

### ISSUE THREAD

**Issue by stevencollinscn** [geopandas/geopandas#825]
I'm trying to plot four maps and put them into a 2x2 matrix and tried two of them first with the following code.
```
fig, ax = plt.subplots(1, 2, figsize=(10,10))
# making a map
gdf.plot(column='urban', 
         cmap='Blues', 
         scheme='QUANTILES', k=4, 
         legend=True, ax=ax[0][0])
gdf.plot(column='rural', 
         cmap='Blues', 
         scheme='QUANTILES', k=4, 
         legend=True, ax=ax[0][1])
```
I got a error that `TypeError: 'AxesSubplot' object does not support indexing`. I'm a little bit confused. Does this mean that the `.plot()` in geopandas does not support `ax` yet? If so, is there any way that I can still plot a matrix map? Thanks in advance for any help.

**Comment by stevencollinscn** [comment]
@ljwolf  I'm tried to format legend such as specifying the precision and change its place on the map. Is there any place I can find some doc for that?

**Comment by stevencollinscn** [comment]
@ljwolf thanks buddy. It seems that there is a lack of support for numerical legend in matplotlib to specifying the precision. 

Btw, I passed `style_kwds = {'edgecolor': 'white', 'linewidth': 2}` in `.plot()` , but got and error that `Unknown property style_kwds`. Am I missing something?

**Comment by ljwolf** [comment]
I guess you could round the array before plotting it.
Yes, those arguments should be passed one by one. 

When you see a function with a call signature like:

```python
def function(first_arg, common_option=True, **extra_options):
   ...
```
That `**` means every keyword argument after `common_option` will be caught in `extra_options`. It's [part of the language](https://docs.python.org/dev/tutorial/controlflow.html#keyword-arguments). This is what the geopandas `plot` documentation means when it puts the `**` in front of `style_kwds`.

**Comment by stevencollinscn** [comment]
@ljwolf I'm reading Paysal's doc [here ](https://pysal.readthedocs.io/en/latest/library/esda/mapclassify.html#pysal.esda.mapclassify.Quantiles)and didn't really get an idea of how to round the numbers on legend.

Thank you for clarifying this for me buddy.

**Comment by StevenLi-DS** [comment]
@ljwolf I posted a solution [here](https://stackoverflow.com/questions/52503899/format-round-numerical-legend-label-in-geopandas). I wonder if there is any way to simplify the workflow. Could you pls take a look.
