### ISSUE TITLE
.sjoin() returns no rows in the geodataframe

### ISSUE THREAD

**Issue by stevencollinscn** [geopandas/geopandas#826]
version: `'0.4.0'`

I‘m trying to do a spatial join with geopandas. I have a `.csv ` file that contains latitude and longitude columns and each pair of them represent an observation.  I also have one `.shp` file that contains polygons for census tracts. I wish to have a new column in my `.csv` file to tell me in which census tract each observation occurs (the `.shp` file contains a GEOID column).

I read the post [here ](https://medium.com/@bobhaffner/spatial-joins-in-geopandas-c5e916a763f3) and transfered my dataframe to a geodataframe. However, after the `sjoin()`, the geodataframe contains no rows. Here's my code and files. Am I missing something?

```
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

# loading polygons layer
gdf_polygons = gpd.read_file('nyc_tracts.shp')
gdf_polygons.crs = {'init': 'epsg:4269'}

# loading dataframe containing lat and long
df = pd.read_csv('NYPD_Complaint_2015.csv')
df = df.head(1000)
df.head()

# convert lat & long to geometry
points = df.apply(lambda x : Point([x['latitude'], x['longitude']]), axis=1)
points.head()
# create a points layer
gdf_points = gpd.GeoDataFrame(df, geometry=points)
gdf_points.crs = gdf_polygons.crs
gdf_points.head()

# spatial join
sjoin = gpd.sjoin(gdf_polygons, gdf_points, how='inner', op='intersects')
sjoin.head()
```
[sjoin.zip](https://github.com/geopandas/geopandas/files/2390947/sjoin.zip)

**Comment by perrygeo** [comment]
@stevencollinscn - your `points` dataframe has the coordinate order reversed. Using `Point([x['longitude'], x['latitude']])` should resolve it.

**Comment by stevencollinscn** [comment]
@perrygeo Thanks, buddy. It works. 

Should the `longitude` always goes first and  `latitude` goes second in all cases? or it only applies to this dataset? Is there any way (doc or something) I can tell when to use which order?  

Btw, how's the the perfermance of `.sjoin()` in comparision to QGIS? Have it optimaized with Cython?

**Comment by stevencollinscn** [comment]
found some answers [here](http://geopandas.org/gallery/create_geopandas_from_pandas.html#sphx-glr-gallery-create-geopandas-from-pandas-py).

**Comment by perrygeo** [comment]
Most geographic software encodes geographic coordinates as (lon, lat) pairs based on the mathematical convention for cartesian coordinates: X (east-west) first, Y (north-south) second. 

There are some exceptions (check out https://macwright.org/lonlat/) but in general (lon, lat) is [the preferred order](https://macwright.org/2016/07/15/longitude-latitude-is-the-right-way.html).

**Comment by stevencollinscn** [comment]
@perrygeo Thanks, man. This is really helpful. Btw, why is geopandas so fast for sj????

**Comment by perrygeo** [comment]
Compared to the QGIS implementation, I'm not sure. There has been a lot of work on geopandas `sjoin` performance including vectorizing operations, spatial indexing and calling into C code for intensive operations (GEOS, numpy, etc). But without looking at the QGIS implementation in depth, it's hard to know how they differ.

**Comment by stevencollinscn** [comment]
@perrygeo Thanks to everyone who has contributed to geopandas!!!
