### ISSUE TITLE
overlay() returns dataframe without CRS

### ISSUE THREAD

**Issue by poplarShift** [geopandas/geopandas#836]
```
import geopandas as gpd
df = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
print(df.crs)
print(gpd.overlay(df,df,how='union').crs)
```
> {'init': 'epsg:4326'}
> None

Is this expected behaviour even if both CRS match (which they should if you overlay them in the first place)?

**Comment by jorisvandenbossche** [comment]
@poplarShift What version of GeoPandas are you using? 
Using the latest 0.4.0, I seem to get the correct result (`overlay` got a big refactor in that release, so it might have been fixed along the way)

```
In [9]: import geopandas

In [10]: df = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))

In [11]: geopandas.overlay(df, df, how='union').crs
Out[11]: {'init': 'epsg:4326'}

In [12]: geopandas.__version__
Out[12]: '0.4.0'
```

**Comment by poplarShift** [comment]
My bad, I was still on 0.3.0 in that environment. Thanks a lot!
