### ISSUE TITLE
Installing geopandas on Windows 7

### ISSUE THREAD

**Issue by jtamerius** [geopandas/geopandas#839]
I am having all sorts of trouble setting up geopandas in Windows 7 using conda. Does anybody have a sure-fire way of getting it running?

**Comment by ocefpaf** [comment]
Unfortunately the mixing of channels is a no-no at the moment. You will have success if you eliminate one channel of the other (`conda-forge` or `defaults`). B/c `conda-forge` does not provide a `scipy` on Windows I recommend you to try an all `defaults` on Windows.

**Comment by lwasser** [comment]
FWIW I have been using conda-forge for all things windows and spatial with some success (short of the current pyproj issue) :) this is the envt that i have my students using 

https://github.com/earthlab/earth-analytics-python-env

**Comment by jtamerius** [comment]
After spending 15 hours on this over the past few days I *think* I finally got it to work. The major stumbling block for me was getting around geopandas/pyproj issue[ #830](https://github.com/geopandas/geopandas/issues/830). After failing to downgrade pyproj, I finally got this [temporary fix](https://github.com/geopandas/geopandas/issues/830#issuecomment-426116505) to work. Phew... I was about to throw in the towel :-)

**Comment by jdmcbr** [comment]
@jtamerius Glad you got it working, though sorry it involved so much work on your part!
