### ISSUE TITLE
ValueError: Invalid field type <class 'pandas._libs.tslib.Timestamp'>

### ISSUE THREAD

**Issue by fahadkhan469** [geopandas/geopandas#840]
Hi everyone,

What I have is a very basic problem, I found some other discussions on it but couldn't solve it for my code. Basically I trying to create point shapefiles from spreadsheet information. The spreadsheet contains the following items/ columns:

"No.", "Well name", "Easting", "Northing", "Elev.", "Time".

I am using the following code to load the spreadsheet and export the information into shapefiles.

```
import pandas as pd
from shapely.geometry import Point, LineString, Polygon
import geopandas
well_df = pd.read_excel('C:/new_wells_2017-18.xlsx')

well_df['geometry'] = well_df.apply(lambda x: Point((float(x.Easting), float(x.Northing))), axis=1)
geo_df = geopandas.GeoDataFrame(well_df, geometry='geometry')
geo_df.crs = {'init' :'epsg:32637'} 
#my coordinates are in UTM (Zone 37N), I'm not sure if I'm correctly assigning the projection.

geo_df.to_file('C:/new_wells_2017-18.shp', driver='ESRI Shapefile')
```

After I run this the following error pops up:

**ValueError: Invalid field type <class 'pandas._libs.tslib.Timestamp'>**

N.B.: The "time" column I have in my dataframe is in dd/mm/yyyy format, not sure if that's something with the date. If anyone can help I'd be greatful - this might be a simple problem in Python but I'm new with the use of Python (but I've been used GIS for a long time).

**Comment by jdmcbr** [comment]
Timestamps aren't supported in shapefile writing. You might convert the time column to a string before the `to_file` step like so:

```
geo_df["Time"] = geo_df["Time"].astype("str")
geo_df.to_file('C:/new_wells_2017-18.shp', driver='ESRI Shapefile')
```

**Comment by fahadkhan469** [comment]
Hi, thanks a lot! I was able to run the code and eventually create the shapefile. But when I view it on ArcMap, nothing shows up. The attribute table of the shapefile is also blank. Can you help?

**Comment by fahadkhan469** [comment]
Hi, nevermind I've just fixed the latter issue. There was a problem with the filepath I was specifying. Thanks a lot for your help.
