### ISSUE TITLE
sjoin: raise informative error if no GeoDataFrame is passed

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/geopandas#841]
See eg https://gis.stackexchange.com/questions/298478/perform-sjoin-in-geopandas-leads-toattributeerror-geoseries-object-has-no-a/298479#298479 
We can detect this case and provide a better error message.

**Comment by awa5114** [comment]
Should this be closed? It appears to have been merged in the referencing issue #842?

**Comment by jdmcbr** [comment]
Good catch @awa5114, thanks.
