### ISSUE TITLE
Deprecation Warning with fiona 1.8b1

### ISSUE THREAD

**Issue by vesnikos** [geopandas/geopandas#845]
using a `debian:buster` docker image

installed Fiona with 
> pip install git+https://github.com/Toblerity/Fiona.git@1.8b1

I got this __warning__ today: 
```python
/usr/local/lib/python2.7/dist-packages/geopandas/io/file.py:108: FionaDeprecationWarning: Use fiona.Env() instead.
  with fiona.drivers():
No handlers could be found for logger "rasterio._gdal"
```

**Comment by jorisvandenbossche** [comment]
@vesnikos Thanks for the report! 
I was also just testing Fiona 1.8 (https://github.com/geopandas/geopandas/pull/844, https://github.com/Toblerity/Fiona/issues/647), and saw the same. So we will have to update our code to use `Env` instead (depending on the fiona version). 


PRs always welcome!
