### ISSUE TITLE
May I fix a spelling issue in your contributing file? compatibile vs compatble

### ISSUE THREAD

**Issue by lwasser** [geopandas/geopandas#848]
Good evening @jorisvandenbossche et al. I found a minor spelling error in the contributing file while reviewing it to use for a package we are working on! `compatibile` should be `compatible`. 

May I submit a PR to fix? :)  It will take all of 2 seconds!

```
Style
-----

- GeoPandas supports python 2 (2.6+) and python 3 (3.2+) with a single
  code base.  Use modern python idioms when possible that are
  compatibile with both major versions, and use the
```

**Comment by jdmcbr** [comment]
@lwasser No need to ask! Please feel free to submit a PR directly. In general, I think it is great to create an issue before making a PR if the PR would take a fair amount of time to put together and also have a reasonable chance of ultimately not being incorporated. In a case like this, it is easiest to just make the PR. Thanks!

**Comment by lwasser** [comment]
done! :) thanks again @jdmcbr

**Comment by jorisvandenbossche** [comment]
@lwasser Thanks! 

That let's me think: we actually don't support Python 2.6 anymore .. We should update that as well one time.

**Comment by lwasser** [comment]
@jorisvandenbossche sure thing. I"m happy to do that! i'll submit another PR and will let you guys comment as you see fit.
