### ISSUE TITLE
Load a csv with geopandas

### ISSUE THREAD

**Issue by SylvainLan** [geopandas/geopandas#865]
Hello, 
I'm quite new to geopandas and I have some data that I would like to store as a csv and re-open it afterwards. 
The problem with the `read_file` method is that the float entries are read as strings, so I have to use `pd.read_csv` and after turn this df into a geoDataFrame. 
Here is a sample of code to illustrate my issue : 
```
import pandas as pd
import geopandas as gpd

gdf = gpd.GeoDataFrame()
gdf['A'] = [1., 2.5, 3.]
gdf.to_csv('test.csv')

df1 = pd.read_csv('test.csv')
gdf1 = gpd.read_file('test.csv')

print(type(df1['A'][0]))
print(type(gdf1['A'][0]))
```

Is this behavior expected ? If yes what is the workaround to store/load gdf properly ?

Thanks

**Comment by andygarfield** [comment]
This seems to be the default CSV driver behavior in GDAL. [Fiona's docs](https://github.com/Toblerity/Fiona/blob/master/fiona/drvsupport.py#L6) recommend using python's built in CSV parser.

Though, a simple workaround would be to convert the pandas DataFrame to a GeoDataFrame.
```python
import pandas as pd
import geopandas as gpd

gdf = gpd.GeoDataFrame()
gdf['A'] = [1., 2.5, 3.]
gdf.to_csv('test.csv')

df = pd.read_csv('test.csv')
gdf = gpd.GeoDataFrame(df)

print(type(df['A'][0]))
print(type(gdf['A'][0]))
```
Output
```
<class 'numpy.float64'>
<class 'numpy.float64'>
```

**Comment by SylvainLan** [comment]
Thanks ! I'll use the python CSV parser then.
