### ISSUE TITLE
gpd.to_file could support GeoDataFrames with multiple geometry types

### ISSUE THREAD

**Issue by galak75** [geopandas/geopandas#867]
# Context

Since [Fiona 446](https://github.com/Toblerity/Fiona/issues/446) resolution (see [PR 539](https://github.com/Toblerity/Fiona/pull/539)), `fiona.open` allows to provide a schema with a list of geometry types, or even any types (using `Unknown` keyword)

# Current behaviour
Currently, `gpd.to_file` fails for the following cases (using `GeoJSON` OGR driver):
* a gdf containing a shape type and the corresponding Multi shape type (e.g. `Polygon` and `MultiPolygon`): the inferred schema contains only the simple shape type (e.g. `Polygon`), but then fiona raises the error below:
  ```
     File "fiona/ogrext.pyx", line 1182, in fiona.ogrext.WritingSession.writerecs
   fiona.errors.GeometryTypeValidationError: Record's geometry type does not match collection schema's geometry type: 'MultiPolygon' != 'Polygon'
  ```
* a gdf containing containing heterogeneous geometries (e.g. `Point`s and `Polygon`s) directly fails in `gpd.to_file` with the error below:
  ```
  ValueError: Geometry column cannot contain mutiple geometry types when writing to file.
  ```
# Suggested improvement
I suggest to support writing `GeoDataFrame`s with multiple geometry types (without having to provide a schema): the inferred schema would just contain a list of geometry types (following Fiona new behaviour); 

OGR drivers supporting multiple geometry types would succeed; others would probably fail anyways...

Let me know if there is a case I did not think about.

# Ready to contribute
I would be glad to provide a PR if this functionality is desired (I already have some additional unit tests showing the current behaviour)

**Comment by galak75** [comment]
@bnaul sorry for the delay, I was trying to figure out the best way to include Fiona new behavior into geopandas.
 #827 is addressing partly the problem: one use case that might fail with this PR is a gdf having Polygon and MultiPolygon geometries.

I'm working on suggesting another PR (adding a lot of unit tests on both functions `file.infer_schema` and `gdf.to_file`)

let's keep in touch to fix all this

**Comment by jorisvandenbossche** [comment]
@bnaul @galak75 Looking at this now, I think it is nice to actually explicitly list all the geometries that are in the geodataframe, so fiona gets all the information we can give it (and so it can already decide to let pass through eg Polygon/MultiPolygon combo for Shapefiles). 
I think always having "Unknown" as done in #827 will also work for fiona, but that means that you only get a error message while already writing, while with specifying the actual types, we can let fiona error early.

So summary, it's fine that #827 is merged, but can still merge #870 in addition to improve upon this.

**Comment by awa5114** [comment]
Has this been implemented yet? I am having other problems with GeometryCollections for example: https://github.com/geopandas/geopandas/issues/953

**Comment by jorisvandenbossche** [comment]
@awa5114 this will be in the next release. But the input / output for different geometry types as discussed here is not related to the problem with plotting you are seeing in #953

**Comment by awa5114** [comment]
Is there a way to circumvent this or is this a situation where I have to write a function to clean up the gdf before writing to file?

**Comment by jorisvandenbossche** [comment]
Currently there is not yet a way, and you will have to clean the geometries yourself. See also the discussion in https://github.com/geopandas/geopandas/issues/834. But I think it would be interesting to add some functionality for this in geopandas (functionality to convert your geometries to a certain geometry type, like you have https://postgis.net/docs/ST_Multi.html and http://postgis.net/docs/ST_Force_Collection.html in PostGIS)

**Comment by awa5114** [comment]
I just wrote this function and tested it for a simple use case. Might be useful to others who have similar problems:

```
def flatten_gdf_geometry(gdf, geom_type):
    geometry = gdf.geometry
    flattened_geometry = []

    flattened_gdf = geopandas.GeoDataFrame()

    for geom in geometry:
        if geom.type in ['GeometryCollection', 'MultiPoint', 'MultiLineString', 'MultiPolygon']:
            for subgeom in geom:
                if subgeom.type==geom_type:
                    flattened_geometry.append(subgeom)
        else:
            if geom.type==geom_type:
                flattened_geometry.append(geom)

    flattened_gdf.geometry=flattened_geometry

    return flattened_gdf

```

**Comment by josemarfdc** [comment]
> I just wrote this function and tested it for a simple use case. Probably not the best but might be useful to others who have similar problems:
> 
> ```
> def flatten_gdf_geometry(gdf, geom_type):
>     geometry = gdf.geometry
>     flattened_geometry = []
> 
>     flattened_gdf = geopandas.GeoDataFrame()
> 
>     for geom in geometry:
>         if geom.type in ['GeometryCollection', 'MultiPoint', 'MultiLineString', 'MultiPolygon']:
>             for subgeom in geom:
>                 if subgeom.type==geom_type:
>                     flattened_geometry.append(subgeom)
>         else:
>             if geom.type==geom_type:
>                 flattened_geometry.append(geom)
> 
>     flattened_gdf.geometry=flattened_geometry
> 
>     return flattened_gdf
> ```

@awa5114 I believe this functionality is implemented with `gdf.explode()`

**Comment by awa5114** [comment]
@josemarfdc Indeed it is... I tried it and it works. Thank you very much.
