### ISSUE TITLE
cmap/norm not persisting when passed as arguments

### ISSUE THREAD

**Issue by story645** [geopandas/geopandas#869]
Mentioned this briefly on gitter, but I'm having trouble with my color map and norm persisting across multiple calls to plot on version 0.4.0. xref:#730, #420. 

First I set up a cmap and norm:
```python
import matplotlib as mpl
cmap = mpl.cm.viridis_r
norm = mpl.colors.BoundaryNorm([4e7, 6e7, 8e7, 1e8, 2e8, 4e8, 1e9, 1.2e9], cmap.N)
```
I get the colors I expect when using the .plot method on the entire geodataframe:
```python
_ = geoAO.plot('AwardOutrightAdjusted', ax=ax, cmap=cmap, norm=norm)
```
![index](https://user-images.githubusercontent.com/1300499/49424026-5a17c700-f767-11e8-9086-ea4b95eff444.png)

But when I try to break the dataframe up using subplots or inset axes, the insets/subplots don't respect the cmap/norm I've set. [also tried explicitly setting the facecolor as a test and that didn't work either].
__Just Alaska__
![index5](https://user-images.githubusercontent.com/1300499/49424541-e4acf600-f768-11e8-9085-542e7f63545c.png)
```python
fig, ax = plt.subplots()
geoAO[geoAO['postal'].str.match('AK')].plot('AwardOutrightAdjusted', ax=ax, cmap=cmap, norm=norm)
```
__inset__
![indexinset](https://user-images.githubusercontent.com/1300499/49424216-f0e48380-f767-11e8-82c3-625f376a2cd6.png)
```
fig, ax = plt.subplots(figsize=(15,10))
im = geoAO[~geoAO['postal'].isin(['AK','HI'])].plot('AwardOutrightAdjusted', ax=ax, cmap=cmap, norm=norm)
                                                    
axa = ax.inset_axes([-127, 23, 10, 10], transform=ax.transData)
_ = geoAO[geoAO['postal'].str.match('AK')].plot('AwardOutrightAdjusted', ax=axa, cmap=cmap, norm=norm)

axh = ax.inset_axes([-75, 25, 9, 9], transform=ax.transData)
_ = geoAO[geoAO['postal'].str.match('HI')].plot('AwardOutrightAdjusted', ax=axh, cmap=cmap, norm=norm)
```
__gridspec__
![indexsub](https://user-images.githubusercontent.com/1300499/49424168-d0b4c480-f767-11e8-9d41-09bf1d6cc3f0.png)
```python
import matplotlib.gridspec as gridspec
gs = gridspec.GridSpec(2, 2, width_ratios=[2,1])
fig = plt.figure()
ax1 = fig.add_subplot(gs[:,0])
ax2 = fig.add_subplot(gs[0,1])
ax3 = fig.add_subplot(gs[1,1])

_ = geoAO[~geoAO['postal'].isin(['AK','HI'])].plot('AwardOutrightAdjusted', ax=ax1, cmap=cmap, norm=norm)
_ = geoAO[geoAO['postal'].str.match('AK')].plot('AwardOutrightAdjusted', ax=ax2, cmap=cmap, norm=norm)
_ = geoAO[geoAO['postal'].str.match('HI')].plot('AwardOutrightAdjusted', ax=ax3, cmap=cmap, norm=norm)
```

**Comment by ImportanceOfBeingErnest** [comment]
I found that this works fine if giving each `plot` call a new instance of the same norm, in the sense of 

```
norm1 = mpl.colors.BoundaryNorm([4e7, 6e7, 8e7, 1e8, 2e8, 4e8, 1e9, 1.2e9], cmap.N)
norm2 = mpl.colors.BoundaryNorm([4e7, 6e7, 8e7, 1e8, 2e8, 4e8, 1e9, 1.2e9], cmap.N)

mainland.plot(..., norm=norm1, ax=ax1, legend=False)
alaska.plot(..., norm=norm2, ax=ax2, legend=False)

# now create colorbar manually
fig.colorbar(ax1.collections[0], ax=ax1)
```

To fix this:

https://github.com/geopandas/geopandas/blob/8a61854a156434e0c5377f5eae3a352362f6c9a4/geopandas/plotting.py#L106-L109

needs to look like

    if values is not None:
        collection.set_array(np.asarray(values))
        collection.set_cmap(cmap)
        if not kwargs.get("norm", None):
            collection.set_clim(vmin, vmax)

same for other collections.

Also,

https://github.com/geopandas/geopandas/blob/8a61854a156434e0c5377f5eae3a352362f6c9a4/geopandas/plotting.py#L513

needs to look like

        norm = style_kwds.get("norm", None)
        if not norm:
            norm = Normalize(vmin=mn, vmax=mx)
