### ISSUE TITLE
Plot categories changed in 0.4.0

### ISSUE THREAD

**Issue by fmaussion** [geopandas/geopandas#877]
My apologies if this was raised before, I haven't had the time to do a proper issue search. 

The following code used to create a multicolor plot in geopandas 0.3.0 but not 0.4.0 (or master).

Here the file: [clusters.tar.gz](https://github.com/geopandas/geopandas/files/2667357/clusters.tar.gz)

```python
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib

print(gpd.__version__)
print(matplotlib.__version__)
df = gpd.read_file('tar://clusters.tar.gz')
df.plot(column='cluster_id', edgecolor='k', cmap='YlOrRd');
```

Outputs:

```
0.4.0
3.0.2

/home/mowglie/.pyvirtualenvs/py3/lib/python3.5/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
/home/mowglie/.pyvirtualenvs/py3/lib/python3.5/site-packages/numpy/core/_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
/home/mowglie/.pyvirtualenvs/py3/lib/python3.5/site-packages/matplotlib/colors.py:512: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
```

![index](https://user-images.githubusercontent.com/10050469/49798135-dc911f80-fd41-11e8-916a-0b0363b47c87.png)

And in 0.3:

```
0.3.0
3.0.2

/home/mowglie/.pyvirtualenvs/py3/lib/python3.5/site-packages/matplotlib/colors.py:512: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
```
![index](https://user-images.githubusercontent.com/10050469/49798337-52958680-fd42-11e8-96a9-e7d84bbaca77.png)

**Comment by fmaussion** [comment]
(note: also the warning is a bit annoying but this is maybe my data)

**Comment by jGaboardi** [comment]
[The warning seems to be thrown by `numpy`, maybe due to `NaN`s in your dataset.](https://github.com/Unidata/netcdf4-python/issues/766)

**Comment by fmaussion** [comment]
sorry for not seeing that, too much on my plate right now -> removing NaNs also solves the plot.

It used to be more robust in geopandas v0.3, though. Should I leave the issue open?

**Comment by martinfleis** [comment]
It is caused by changes in #770. Removing NaNs solves the issue only partially. In 0.3 you those shapes with NaNs were also plotted. I think they should be plotted, just with no value. Opinions?

**Comment by fmaussion** [comment]
> I think they should be plotted, just with no value. Opinions?

I agree: like matplotlib's imshow or pcolormesh where NaNs are displayed with white (default) or any color specified by the user in cmap.set_bad()

**Comment by martinfleis** [comment]
Got it. `mn = values.min() if vmin is None else vmin` and `mx = values.max() if vmax is None else vmax` are both returning `nan`. That's why it does not plot colours - it is passing range from nan to nan. 
Previous version was passing Series, which ignores NaNs in min() and max(). Now it is passing numpy array which returns NaN for min() and max(),
I'll make PR to fix it.
