### ISSUE TITLE
Error import geopandas.io

### ISSUE THREAD

**Issue by RuizGeo** [geopandas/geopandas#89]
Traceback (most recent call last):
When I imported the library geopandas the following error occurred:

File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/geopandas/**init**.py", line 6, in <module>
    from geodataframe import GeoDataFrame
  File "/usr/local/lib/python2.7/dist-packages/geopandas/geodataframe.py", line 12, in <module>
    import geopandas.io
ImportError: No module named io

I installed the geopandas library using the command in the terminal (Ubuntu 12.04):
 pip install geopandas

The error occurred because the io folder was not installed, so I created this folder within the geopandas and copy these files into it
https://github.com/kjordahl/geopandas/commit47f25eea93fc3ad1129f972848d14b8c71828c77
The problem was solved.

**Comment by rafapereirabr** [comment]
I did what you suggested,  but I'm still getting the following error. Any idea? I'm a bit lost here.

Command "python setup.py egg_info" failed with error code 1 in C:\users\rafa\appdata\local\temp\pip-build-xcoxnv\shapely

**Comment by kjordahl** [comment]
@rafapereirabr That looks like an error with installing Shapely. Can you successfully `pip install shapely` on its own?

**Comment by rafapereirabr** [comment]
Hi @kjordahl , yeap. I'm having problems to install Shapely as well. I've tried installing Shapely using pip and using git and I get this error message in both cases. Any idea of what I'm doing wrong ?

> PS C:\Users\rafa> pip install shapely
Collecting shapely
  Using cached Shapely-1.5.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\rafa\appdata\local\temp\pip-build-oun81u\shapely\setup.py", line 38, in <module>
        from shapely.libgeos import geos_version_string, geos_version, \
      File "shapely\libgeos.py", line 187, in <module>
        lgeos = CDLL("geos.dll")
      File "C:\Users\rafa\Anaconda\lib\ctypes\__init__.py", line 365, in __init__
        self._handle = _dlopen(self._name, mode)
   **WindowsError: [Error 126] The specified module could not be found**

    ----------------------------------------
>**Command "python setup.py egg_info" failed with error code 1 in c:\users\rafa\appdata\local\temp\pip-build-oun81u\shapely**

**Comment by kjordahl** [comment]
@rafapereirabr You might look at this for installing on Windows: http://geoffboeing.com/2014/09/using-geopandas-windows/
Some package binary has not been installed correctly (not geopandas, but one of the dependencies).

**Comment by rafapereirabr** [comment]
@kjordahl , that was really helpful ! Thanks !
