### ISSUE TITLE
Consistent legend colors over subplots 

### ISSUE THREAD

**Issue by eotp** [geopandas/geopandas#893]
I am plotting two maps, each associated with a column (`c1`, `c2`), and with a legend. 
I want a consistent coloring for the two maps, however, as in right map one categorical feature is missing (`feature1`), the colors change too.

Basically I am looking for a way of mapping a color to a specific categorical feature over subplots, both shown on the map as well as in the legend, no matter if the actual feature value is in the selected column or not. 

```
from shapely.geometry import Polygon
from matplotlib import colors   
import matplotlib.pyplot as plt
import geopandas as gpd

# create sample data
p1 = Polygon([(0.5, 0.5), (1, 0.5), (1, 1), (0.5, 1)])
p2 = Polygon([(0, 0), (0.5, 0), (0.5, 0.5), (0, 0.5)])
p3 = Polygon([(0, 0.5), (0.5, 0.5), (0.5, 1), (0,1)])
gdf = gpd.GeoDataFrame({"c1" : ["feature1","feature2","feature3"],
                        "c2" : ["feature2","feature3","feature3"]},
                       geometry=gpd.GeoSeries((p1,p2,p3)))

# colormap
hmap = colors.ListedColormap(['lightgrey', 'red', 'lightblue'])

# ploting
fig, ax = plt.subplots(ncols=2)
gdf.plot(column="c1", legend=True, categorical=True, cmap=hmap, ax=ax[0])
gdf.plot(column="c2", legend=True, categorical=True, cmap=hmap, ax=ax[1])
```

![test](https://user-images.githubusercontent.com/11331549/50737326-13831580-11c8-11e9-9b9b-fd60210415b8.png)

**Comment by kerooksblog** [comment]
Hi, I'm facing a similar issue plotting points with different ranges of values. I'd like to be able to compare the different plots with an unique legend.

I tried to understand if there were solutions in matplotlib that could be used for this particular case. I've found two cases:
- [Multiple Image](https://matplotlib.org/3.1.1/gallery/images_contours_and_fields/multi_image.html#sphx-glr-gallery-images-contours-and-fields-multi-image-py)
- [Subplots Adjust](https://matplotlib.org/3.1.1/gallery/subplots_axes_and_figures/subplots_adjust.html#sphx-glr-gallery-subplots-axes-and-figures-subplots-adjust-py)

I'm quite new in coding and actually I'm not really sure if this could help, but is there any way to make something similar with geopandas? 

``` python
N1 = 10
points_1 = gpd.GeoSeries(Point(i, i) for i in range(N1))
values_1 = np.arange(N1)
N2 = 4
points_2 = gpd.GeoSeries(Point(i, i) for i in range(N2))
values_2 = np.arange(N2)

df1 = gpd.GeoDataFrame({"geometry": points_1, "values": values_1})
df2 = gpd.GeoDataFrame({"geometry": points_2, "values": values_2})

fig = plt.figure()
fig.set_size_inches(10, 10)

ax1=plt.subplot(221) 
df1.plot(ax=ax1, column='values', legend = True)

ax2=plt.subplot(222) 
df2.plot(ax=ax2, column='values', legend = True)

plt.show()
```
![legend](https://user-images.githubusercontent.com/17175539/67012329-7dcecc00-f0f1-11e9-82db-5b0cab311238.png)

**Comment by kerooksblog** [comment]
Thanks @martinfleis for your kind answer. I've tried it, but it looks like the output persists in the old way, without changes in colours or in legend for the second plot

**Comment by martinfleis** [comment]
@kerooksblog are you using recent version of geopandas? 0.6.0 or 0.6.1?

**Comment by kerooksblog** [comment]
Ops, sorry. I was sure it was the last one. My fault, with the 0.6.1 it works. Sorry and thanks again @martinfleis
