### ISSUE TITLE
Problem with pltoting multiple polygons?

### ISSUE THREAD

**Issue by elmerehbi** [geopandas/geopandas#895]
I cannot seem to be able to replicate this example where not all polygons show well. Might I be missing some module? Or what could be the problem?

![screenshot from 2019-01-10 15-17-32](https://user-images.githubusercontent.com/3155152/50974236-11cc9100-14eb-11e9-94f3-ad66ef929ca0.png)

![screenshot from 2019-01-10 15-19-35](https://user-images.githubusercontent.com/3155152/50974282-2dd03280-14eb-11e9-8221-7779053a510e.png)

```
p1 = Polygon([(0, 0), (1, 0), (1, 1)])
p2 = Polygon([(0, 0), (1, 0), (1, 1), (0, 1)])
p3 = Polygon([(2, 0), (3, 0), (3, 1), (2, 1)])
g = GeoSeries([p1, p2, p3])
g.plot()
```

[source](http://geopandas.org/geometric_manipulations.html)

**Comment by martinfleis** [comment]
Polygon p1 and polygon p2 are on top of each other, you have to specify transparency to see both of them. Use `g.plot(alpha=0.5)`.

**Comment by elmerehbi** [comment]
@martinfleis  Awesome. Thank you
