### ISSUE TITLE
QUESTION: Zip Files Documentation

### ISSUE THREAD

**Issue by linwoodc3** [geopandas/geopandas#897]
Where is the documentation on reading zip files directly with `geopandas`?  I ask because I'm willing to do a quick pull requests for the docs to add.

If this does not exist, would maintainers be open to a simple doc update; I'll do the pull request. 

I found the example in a [Scipy 2018 tutorial here](https://render.githubusercontent.com/view/ipynb?commit=57afd9a46a75b281adb0d36b0492142eb7ca29c9&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f67656f70616e6461732f7363697079323031382d67656f7370617469616c2d646174612f353761666439613436613735623238316164623064333662303439323134326562376361323963392f30312d696e74726f64756374696f6e2d67656f7370617469616c2d646174612e6970796e62&nwo=geopandas%2Fscipy2018-geospatial-data&path=01-introduction-geospatial-data.ipynb&repository_id=137507083&repository_type=Repository#Importing-geospatial-data).

I looked on the `geopandas` page and github and didn't find an explicit mention. This is a useful feature as a lot of ESRI shapefiles get shipped around.  Hopefully the GeoPackage spec takes over completely, but having the `zip` example would help.  Maybe it's obvious to some but it wasn't to me for a long time.
Example:

```python
# download zipped country file from https://gadm.org/download_country_v3.html
states = gpd.read_file('zip:///Users/linwood/Downloads/cb_2017_us_state_500k.zip') # read in zip
```

**Comment by jdmcbr** [comment]
@linwoodc3 Thanks for raising this. A note on reading zipfiles directly as above would be a welcome addition in https://github.com/geopandas/geopandas/blob/master/doc/source/io.rst

**Comment by ardieorden** [comment]
@linwoodc3 @jorisvandenbossche Hi, I'd like to take on this issue!

**Comment by sgillies** [comment]
This feature isn't as well documented in https://fiona.readthedocs.io/en/latest/README.html#collections-from-archives-and-virtual-file-systems as I'd like, I'll work on that, too.

Keep in mind that `fiona.open("zip://data.zip")` (which is what read_file calls) is only useful when data.zip contains a single vector dataset in the root of the zip file. If the dataset is in a folder in the zip file you must extend the identifier like `zip://data.zip!folder`. If there are multiple datasets in that folder you must also specify the filename like `zip://data.zip!folder/file.shp`.

**Comment by ardieorden** [comment]
Thanks for the info @sgillies !
