### ISSUE TITLE
Add to documentation: How to plot unfilled polygons onto another map

### ISSUE THREAD

**Issue by uvchik** [geopandas/geopandas#898]
It was really hard for me to find out that the facecolor of a plot has to be `'none'` instead of `None` to plot an unfilled polygon. I needed it to plot two tables into one figure (see below).

We could add an information to the API-documentation:
```diff
**style_kwds : dict
    Color options to be passed on to the actual plot function, such as edgecolor, facecolor,
-   linewidth, markersize, alpha.
+   linewidth, markersize, alpha. Use 'facecolor='none' to get an unfilled polygon.
```

Or we could add an example to the ["Making maps" section](https://geopandas.readthedocs.io/en/latest/mapping.html).

What do you think? 

![windzonen_ohne_text](https://user-images.githubusercontent.com/4760584/51471354-c5007a00-1d76-11e9-98ff-74f63f647a8e.png)

```python
ax = df1.plot(column='windzone', edgecolor='#888888', linewidth=0.5, cmap=my_blue)
df2.plot(edgecolor='black', alpha=1, facecolor='none', ax=ax, linewidth=1.5)
plt.show()
```

**Comment by jdmcbr** [comment]
Using `"none"` to get no facecolor applied is getting a little into the details of `matplotlib` to feel like it is appropriate to incorporate into the API docs for `geopandas` (FWIW, `None` means "do the default thing" in most contexts, which happens in this case to _not_ mean "don't plot a faceolor at all"). An additional example in the making maps section would be welcome (or a modification, e.g., changing `base = world.plot(color='white', edgecolor='black')` to `base = world.plot(facecolor='none', edgecolor='black')` under the Method 1 header).

**Comment by jorisvandenbossche** [comment]
Exactly because this is such a detail of matplotlib (so many people will not know) but *is* a common use case, I feel that it would actually be useful to mention this explicitly.

So I would personally be fine with a PR doing the diff above, but as @jdmcbr says, an additional example in the maps section would also be very welcome!

**Comment by ljwolf** [comment]
The fact that `facecolor='none'` is so in the weeds is why I prefer doing `world.boundary.plot()`. I find that to be both more explicit and clear, but I'm not sure if there's a performance penalty for it.

**Comment by uvchik** [comment]
@ljwolf That it also a good idea. If you prefer it you can just ignore my PR. In that case we could just add an example to help users like me in the future. But as I wrote in the PR I will not have time until March to think of a good example.

**Comment by jdmcbr** [comment]
I guess from personal experience, there are enough "gotchas" in `matplotlib` that noting them all in the docs of `geopandas` feels a little too much. But I don't have a particularly strong opinion about that.

**Comment by uvchik** [comment]
I tested the solution of @ljwolf and found out that it is faster in my case and the more I think about it I like it better than my solution. Therefore, I will close my PR. I still think we should add an example.

**Comment by ardieorden** [comment]
Hi, I'd like to take on this issue!
