### ISSUE TITLE
Geopandas for Python 3.7 to_file makes all numerical datatypes "double"

### ISSUE THREAD

**Issue by dingobar** [geopandas/geopandas#908]
Hi,

I discovered this bug after installing a fresh environment in anaconda, not realizing that geopandas now supports python 3.7: `gpd.to_file('out.shp', driver='ESRI-Shapefile')` will output all numerical dtypes as double. I have tested float64, int64 and all the other integer-types in numpy (int8, int32...).

**Steps to reproduce:**
- Import a shapefile containing an integer
- Write the resulting geodataframe to a shapefile, and check the datatype with ArcCatalog/QGIS/equivalent

**Comment by jorisvandenbossche** [comment]
Thanks for the report! Do you know if this is specific to Python 3.7?

**Comment by dingobar** [comment]
It seems to be a 3.7 specific issue as my 3.6 venv works just fine.

**Comment by jdmcbr** [comment]
@dingobar Can you provide more detail about how you're creating the environment, as well as your OS? I did

    conda create -name gpd-double python==3.7 geopandas

in both Linux and Windows, then

    gdf = gpd.read_file(gpd.datasets.get_path("nybb"))
    gdf.to_file("test.shp")

and confirmed that the `BoroCode` column was an int, as expected.

![image](https://user-images.githubusercontent.com/666108/52392256-d96e9300-2a55-11e9-9ac8-0a59fe12d691.png)

**Comment by jorisvandenbossche** [comment]
@dingobar can you provide some more information that @jdmcbr asked about? And if possible, provide a reproducible example?

**Comment by dingobar** [comment]
Hi all,

Since posting this issue I have switched jobs and I am no longer able to reproduce the issue. I imagine the issue was with versioning, as I remember reinstalling the conda environment solved the issue.
