### ISSUE TITLE
Segmentation fault when Geopandas imported while using Click and Rasterio

### ISSUE THREAD

**Issue by jerheff** [geopandas/geopandas#910]
I'm cross posting a segmentation fault that I'm running into since the issue is due to some interaction of Geopandas, Rasterio, and Click.  In the replication example, importing Geopandas causes a Rasterio function to throw a segmentation fault.  When I remove the Geopandas import the seg fault goes away.

More info here: https://github.com/mapbox/rasterio/issues/1612

**Comment by jdmcbr** [comment]
Closed per https://github.com/mapbox/rasterio/issues/1612
