### ISSUE TITLE
intersection() raises exception when empty

### ISSUE THREAD

**Issue by martinfleis** [geopandas/geopandas#912]
Hi, I've encountered error which is not affecting 0.4.0 but master only. Intersection of geodataframe and Linestring will cause an Exception when such intersection is empty, instead of providing empty GeoSeries.

    import geopandas as gpd
    from shapely.geometry import LineString
    gpd.__version__
    '0.4.0+53.g39e724b'

    line = LineString([(0, 0), (1, 1)])
    line_gdf = LineString([(2, 2), (3, 3)])

    gdf = gpd.GeoDataFrame(geometry=gpd.GeoSeries(line_gdf))

    gdf.intersection(line)

    ---------------------------------------------------------------------------
    Exception                                 Traceback (most recent call last)
    <ipython-input-24-0c1daf0de3cb> in <module>
    ----> 1 gdf.intersection(line)

    ~/anaconda3/envs/momepy/lib/python3.6/site-packages/geopandas/base.py in intersection(self, other)
        507             intersection with.
        508         """
    --> 509         return _binary_geo('intersection', self, other)
        510 
        511     #

    ~/anaconda3/envs/momepy/lib/python3.6/site-packages/geopandas/base.py in _binary_geo(op, left, right)
         46         data = np.array([getattr(s, op)(right) for s in left.geometry],
         47                         dtype=object)
    ---> 48         return GeoSeries(data, index=left.index, crs=left.crs)
         49     else:
         50         raise TypeError(type(left), type(right))

    ~/anaconda3/envs/momepy/lib/python3.6/site-packages/geopandas/geoseries.py in __init__(self, *args, **kwargs)
         41         crs = kwargs.pop('crs', None)
         42 
    ---> 43         super(GeoSeries, self).__init__(*args, **kwargs)
         44         self.crs = crs
         45         self._invalidate_sindex()

    ~/anaconda3/envs/momepy/lib/python3.6/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
        273             else:
        274                 data = _sanitize_array(data, index, dtype, copy,
    --> 275                                        raise_cast_failure=True)
        276 
        277                 data = SingleBlockManager(data, index, fastpath=True)

    ~/anaconda3/envs/momepy/lib/python3.6/site-packages/pandas/core/series.py in _sanitize_array(data, index, dtype, copy, raise_cast_failure)
       4163     elif subarr.ndim > 1:
       4164         if isinstance(data, np.ndarray):
    -> 4165             raise Exception('Data must be 1-dimensional')
       4166         else:
       4167             subarr = com._asarray_tuplesafe(data, dtype=dtype)

    Exception: Data must be 1-dimensional

And the same thing on master:

    import geopandas as gpd
    from shapely.geometry import LineString
    gpd.__version__
    '0.4.0'

    line = LineString([(0, 0), (1, 1)])
    line_gdf = LineString([(2, 2), (3, 3)])

    gdf = gpd.GeoDataFrame(geometry=gpd.GeoSeries(line_gdf))

    gdf.intersection(line)
    0    ()
    dtype: object

I'll try to investigate what happened to fix it, but I am not sure I'll have time to do it sooner than next week.

**Comment by jorisvandenbossche** [comment]
A quick check: are you using the same pandas version for both? (or which pandas version are you using?)

**Comment by martinfleis** [comment]
Yes, '0.23.4' on both. I just tried to clone environment with stable and update only Geopandas to master and the issue is still there.

**Comment by jorisvandenbossche** [comment]
The reason is the following:

```
In [11]: line = LineString([(0, 0), (1, 1)]) 
    ...: line_gdf = LineString([(2, 2), (3, 3)]) 
    ...: gdf = gpd.GeoDataFrame(geometry=gpd.GeoSeries(line_gdf))                                                                                                                                                                                                                                                                  

In [12]: [s.intersection(line) for s in gdf.geometry]                                                                                                                           
Out[12]: [<shapely.geometry.collection.GeometryCollection at 0x7f93353afc88>]

In [13]: np.array([s.intersection(line) for s in gdf.geometry])                                                                                                                 
Out[13]: array([], shape=(1, 0), dtype=float64)
```

So the conversion to a numpy array goes wrong (it "unpacked" the geometry collection, resulting in a 2D array of shape (1, 0)). Before (geopandas 0.4.0), we passed the list directly to the `GeoSeries` constructor, and pandas has some utility to convert the list to an array ensuring it stays 1D, apparently. So we can check how pandas does that (or again, relying on pandas to do it).

Thanks for the catch!
