### ISSUE TITLE
[geopandas-cython] pandas 0.24 ExtensionArray

### ISSUE THREAD

**Issue by jwilson8767** [geopandas/geopandas#925]
I've been trying to get geopandas-cython working with pandas 0.24 and have discovered that there were several breaking changes in the ExtensionArray api. Additionally, I note that GeometryArray does not even subclass [ExtensionArray](https://github.com/pandas-dev/pandas/blob/master/pandas/core/arrays/base.py), is this api really that new or am I missing something? I'd be happy to start a PR with what I have working so far if that would be helpful, but thought I'd open a discussion here first.

**Comment by jorisvandenbossche** [comment]
There are open PRs for this, see https://github.com/geopandas/geopandas/pull/701 (for cython branch) and  https://github.com/geopandas/geopandas/pull/835 (for master). 
I hope to get back to those at some points, but it will not be in the first few weeks. So if you want to take over, very welcome!

https://github.com/geopandas/geopandas/pull/701 was started before 0.24, so will probably also need some updates for the ExtensionArray changes in pandas 0.24

**Comment by jwilson8767** [comment]
Nice! I totally didn't find those when I looked. I'll dig in and see what I can do.
