### ISSUE TITLE
Cannot import geopandas in Jupyter Notebook

### ISSUE THREAD

**Issue by mmschmitz** [geopandas/geopandas#927]
I included the following commands, and nothing else, into my Jupyter notebook (installed yesterday, 2 March 2019):
```
# load libraries
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd

```

From these commands, I got the following error:

```
> `---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-d60e075e60fa> in <module>
      5 import matplotlib.pyplot as plt
----> 6 import geopandas as gpd
      7 #from geopandas import GeoSeries, GeoDataFrame
      8 

ModuleNotFoundError: No module named 'geopandas'
`
```

**Comment by jorisvandenbossche** [comment]
How did you install geopandas?

**Comment by mmschmitz** [comment]
I used the conda distribution to install it, per the instructions in http://geopandas.org/install.html. I can double-check my installation, though.

**Comment by mmschmitz** [comment]
Feel free to close the issue - I figured it out, and it was kind of stupid. 

I thought I'd installed geopandas via Conda... but I'd actually forgotten to install _for all users_ in Conda using the administrative privileges on my computer. :)

(Be aware about the installation process, future users!)
