### ISSUE TITLE
Small fixes needed to work with pandas 0.24 [cython]

### ISSUE THREAD

**Issue by avnovikov** [geopandas/geopandas#936]
Cython geopandas will not work with pandas 0.24. Small changes in the import statements required. PR is on the way.

**Comment by avnovikov** [comment]
Somehow PR didn't pass through.
_block.py
-from pandas.core.internals import Block, NonConsolidatableMixIn, BlockManager
+from pandas.core.internals.blocks import Block, NonConsolidatableMixIn
+from pandas.core.internals.managers import BlockManager

**Comment by martinfleis** [comment]
Cython branch is no longer under active development. Closing as outdated.
