### ISSUE TITLE
geoseries.rotate has no effect

### ISSUE THREAD

**Issue by Casyfill** [geopandas/geopandas#937]
```
from shapely.geometry import Point
import geopandas as gp

A = [Point(*coords) for coords in ((0,0), (1,1), (-1,-1))]
AA = gp.GeoSeries(A)
AA
>>> 0      POINT (0 0)
1      POINT (1 1)
2    POINT (-1 -1)
dtype: object
```

And same after rotation:
```
AA.rotate(90)
>>> 0      POINT (0 0)
1      POINT (1 1)
2    POINT (-1 -1)
dtype: object
```

**Comment by Casyfill** [comment]
Sorry - figured out it just rotates every object around it's own origin - not geoSeries center/origin

**Comment by jorisvandenbossche** [comment]
Yes, it indeed works elementwise. I suppose you will need to turn it into a MultiPoint (with unary_union) to do such a rotation

**Comment by Casyfill** [comment]
Oh no I just fed it a tuple with centroid coordinates- worked perfectly
