### ISSUE TITLE
Logo Proposal for GeoPandas

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#938]
A great python package deserves a great logo!

**Comment by magtanggol03** [comment]
Hi @StevenLi-DS, would love to work on this! Maybe I can get your thoughts on the ideal logo for GeoPandas and I can make it for you? 

Just in case you want to verify, here's my portfolio haha: https://magtanggol03.github.io/

**Comment by jbednar** [comment]
https://github.com/geopandas/geopandas/pull/786
