### ISSUE TITLE
to_file function do not respect schema columns name

### ISSUE THREAD

**Issue by zioalex** [geopandas/geopandas#945]
Trying to write to a data file and the reload it to compare them but the schema is different:
```
import geopandas as gpd
schema = gpd.io.file.infer_schema(segments_df)
print(input_schema)
{'geometry': 'LineString', 'properties': OrderedDict([('identifier', 'str'), ('start_node_ref', 'str'), ('end_node_ref', 'str'), ('length', 'float')])}
segments_df.to_file(dumpfile,schema=schema)

test_dataframe = gpd.read_file(dumpfile)

test_dataframe.info()
segments_df.info()
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
identifier    3 non-null object
start_node    3 non-null object
end_node_r    3 non-null object
length        3 non-null float64
geometry      3 non-null object
dtypes: float64(1), object(4)
memory usage: 200.0+ bytes
<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
identifier        3 non-null object
start_node_ref    3 non-null object
end_node_ref      3 non-null object
geometry          3 non-null object
length            3 non-null float64
dtypes: float64(1), object(4)
memory usage: 200.0+ bytes
```
I didn't find a good way to preserve the original schema!

**Comment by jorisvandenbossche** [comment]
Can you clarify what is the difference between both that you are pointing at?

**Comment by jorisvandenbossche** [comment]
Looking a bit better, I see two differences:

- the column order: `read_file` will always put the geometry column last
- the column names: this is a limitation of shapefiles that they have a limit of 10 characters, so that is the reason the column names are truncated.

Regarding the data types I don't see a difference.

**Comment by zioalex** [comment]
Yep I meant the column names. Any way to keep the same names?

**Comment by jorisvandenbossche** [comment]
There is no way around this limitation (except for not using shapefiles, see eg http://switchfromshapefile.org/ with some more background)

**Comment by zioalex** [comment]
Thanks @jorisvandenbossche will read it. Meanwhile I faked it truncating the column name on the fly while doing the test.

**Comment by jorisvandenbossche** [comment]
Since the actual issue (limitation of shapefiles) if out of scope of geopandas itself, going to close this issue.
