### ISSUE TITLE
error loading included polygon datasets

### ISSUE THREAD

**Issue by bryan-woods** [geopandas/geopandas#947]
world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))

yields a lot of errors like...
Shell is not a LinearRing
Shell is not a LinearRing
Shell is not a LinearRing
IllegalArgumentException: geometries must not contain null elements

It's getting lots of null geometries...

~/miniconda3/envs/nagini/lib/python3.7/site-packages/shapely/geometry/base.py in wkt(self, **kw)
    365     def wkt(self, **kw):
    366         """WKT representation of the geometry"""
--> 367         return WKTWriter(lgeos, **kw).write(self)
    368 
    369     @property

~/miniconda3/envs/nagini/lib/python3.7/site-packages/shapely/geos.py in write(self, geom)
    360         """Returns WKT string for geometry"""
    361         if geom is None or geom._geom is None:
--> 362             raise ValueError("Null geometry supports no operations")
    363         result = self._lgeos.GEOSWKTWriter_write(self._writer, geom._geom)
    364         text = string_at(result)

ValueError: Null geometry supports no operations

**Comment by jorisvandenbossche** [comment]
@bryan-woods Everything was OK in the end?

**Comment by bryan-woods** [comment]
It's something environment related. If I install geopandas via conda it works fine. But when I installed contextily and cartopy, also using conda, it caused the problem with geopandas loading files. I managed to circumvent it by running through a container where it all worked. Something is not right in the conda stack, but I don't know what the problem is.

**Comment by jorisvandenbossche** [comment]
Can you show the output of `conda list` in the environment that is not working?

**Comment by bryan-woods** [comment]
[My conda environment](https://github.com/geopandas/geopandas/files/2992258/conda_env.txt)

**Comment by jorisvandenbossche** [comment]
I recommend to install everything with `conda`. Looking at your environment, it seems you installed geopandas and its dependencies with pip, but then cartopy with conda. GeoPandas and cartopy have some dependencies in common, but the binaries from conda and pip are not compatible.
