### ISSUE TITLE
Silent bigint conversion issue

### ISSUE THREAD

**Issue by kuanb** [geopandas/geopandas#952]
Large integers are converted to 2147483647 if they exceed this value during export to Shapefile. Conversion occurs silently and, unless users are familiar with 2147483647 and aware that it is the largest value for a 32-bit integer, may become confused as to what had occurred.

How to recreate:

First, create a GeoDataFrame with a large value.
```
import geopandas as gpd
from shapely.geometry import Polygon

gdf = gpd.GeoDataFrame(
    {'vals': [25**10]},
    geometry=[Polygon([[1,2],[1,3],[4,3],[2,2]])],
)
```
Here, the resulting GDF's `vals` column has `dtype` of `int64`.

Exporting the file and re-reading it in will result in the value having been converted.
```
gdf.to_file('shapefile_with_bigint')
gpd.read_file('shapefile_with_bigint').head()
```

Screencap of this occurring:
![image](https://user-images.githubusercontent.com/6053396/54844732-cd9d0000-4c94-11e9-97c6-0364195f5293.png)

What should be done?
If BIGINT value cannot be exported to Shapefile, I suggest throwing an error and forcing the user to come up with a solution, like converting the values to strings.

**Comment by jorisvandenbossche** [comment]
@kuanb thanks for the report!

What version of fiona are you using?

I see the correct behaviour with fiona 1.8:

```
In [1]: import geopandas as gpd 
   ...: from shapely.geometry import Polygon 
   ...:  
   ...: gdf = gpd.GeoDataFrame( 
   ...:     {'vals': [25**10]}, 
   ...:     geometry=[Polygon([[1,2],[1,3],[4,3],[2,2]])], 
   ...: ) 

In [2]: gdf.to_file('shapefile_with_bigint.shp') 
   ...: gpd.read_file('shapefile_with_bigint.shp').head()
Out[2]: 
             vals                             geometry
0  95367431640625  POLYGON ((1 2, 1 3, 4 3, 2 2, 1 2))

In [4]: geopandas.__version__                 
Out[4]: '0.4.1'

In [5]: import fiona 

In [6]: fiona.__version__     
Out[6]: '1.8.4'
```

**Comment by kuanb** [comment]
Hi @jorisvandenbossche thank you for the really quick  response.

I was working in a notebook with the following:
```
gpd.__version__
0.4.0

fiona.__version__
1.7.11.post2
```

I then upgraded to fiona v1.8.6 and behavior was as expected - that is, big ints were handled as expected.

So; looks like this was my fault. Apologies and thanks again for the follow up!

**Comment by jorisvandenbossche** [comment]
No problem, and thanks for the confirmation that the fiona version fixed it!

**Comment by kuanb** [comment]
@jorisvandenbossche any reason why geopandas only limits fiona to `fiona>=1.0.1`? Would it be appropriate to enforce gpd to use >=0.18 given this observation?
