### ISSUE TITLE
geopandas fails to plot GeometryCollection

### ISSUE THREAD

**Issue by awa5114** [geopandas/geopandas#953]
It looks like geometry collections are not supported by the geopandas `plot` feature. The following will generate an empty plot.
```
import shapely
import geopandas
a = shapely.geometry.LineString([(0, 0), (1, 1), (1,2), (2,2)])
b = shapely.geometry.LineString([(0, 0), (1, 1), (2,1), (2,2)])
x = a.intersection(b)
gdf = geopandas.GeoDataFrame(geometry=[x])
gdf.plot();
```

Am I doing something wrong or is this a bug ? If so how to fix or workaround? Thanks.

**Comment by jorisvandenbossche** [comment]
Thanks for the report! I don't think you are doing something wrong, this is a bug (or, a not yet supported case). It would be a nice enhancement to actually support this.

**Comment by awa5114** [comment]
You're welcome, I'm noticing this may be a more fundamental problem, since trying to write the geodataframe to a file causes problems as reported here https://github.com/geopandas/geopandas/issues/867. Is there a way to prevent the intersection from generating GeometryCollections, MultiPolygons, or anything that would be problematic when plotting/writing to a file?

**Comment by jorisvandenbossche** [comment]
It might certainly be a more general problem that GeometryCollections are less good supported and tested, but the underlying code-related problem for the I/O or the plotting here are completely independent of each other. 

> Is there a way to prevent the intersection from generating GeometryCollections, MultiPolygons, or anything that would be problematic when plotting/writing to a file?

Not sure about that, sorry. I think the intersection does that here by definition, because of the layout of the two lines (you can't represent the result as a LineString). 

Something that geopandas can do is provide functionality to make sure you have a uniform geometry type, as some formats need that (eg if you have a mixture of Polygons and MultiPolygons, make sure that everything is converted to MultiPolygons)

**Comment by awa5114** [comment]
The functionality to ensure uniform geometry type is implemented already? What specific methods are you referring to? That might solve my problem, if I can convert everything to linestring for example...

**Comment by jorisvandenbossche** [comment]
No, it is something that GeoPandas could provide, but currently doesn't.

**Comment by ljwolf** [comment]
To reiterate @jorisvandenbossche's point, there's not really a way to express `x` as a "uniform geometry type" :/

The main idea behind the `GeometryCollection` in OGC is to wrap a `MULTI-`type shape with heterogeneous types. In your example... `x` has both point and linestring components: 
```python
list(x.geoms)
[<shapely.geometry.point.Point at 0x7fba55a66828>,
 <shapely.geometry.linestring.LineString at 0x7fba55a66b00>]
```
What is the intended "uniform" type for those in your data?

You could "explode" `x` to get its constituent parts, if that helps:
```python
gds.explode()
                  geometry
0 0            POINT (2 2)
  1  LINESTRING (0 0, 1 1)
```
This should let you plot all the elements fine using `gdf.explode().plot()`. 
But, if you wanted to write that out to a file, you'd have the heterogeneous type problem discussed in #867

**Comment by awa5114** [comment]
Is anyone working on this enhancement? If not I could try to pick it up at some point...

**Comment by jorisvandenbossche** [comment]
Not that I am aware of, so feel free to pick it up. If you have any questions, don't hesitate to ask here.
