### ISSUE TITLE
Clipping example for docs

### ISSUE THREAD

**Issue by deppen8** [geopandas/geopandas#956]
I often find myself "clipping" a line or polygon geometry by some other polygon geometry. For example, clipping a `GeoDataFrame` of road boundaries by another `GeoDataFrame` of state or county boundaries. 

Would an example of this be useful for the Examples Gallery? I work with geopandas a lot in my research and would be happy to put this together if desired.

My clipping code is something like this:

```python
def clip(lines_polys: gpd.GeoDataFrame, by: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    # Create a single polygon object for clipping
    poly = by.geometry.unary_union
    spatial_index = lines_polys.sindex

    # Create a box for the initial intersection
    bbox = poly.bounds

    # Get a list of ids for each object that overlaps the bounding box and subset the data to just those objects
    sidx = list(spatial_index.intersection(bbox))
    thing_sub = lines_polys.iloc[sidx]

    # Clip the data - with these data
    clipped = thing_sub.copy()
    clipped['geometry'] = thing_sub.intersection(poly)

    # Return the clipped layer with no null geometry values
    return clipped[clipped.geometry.notnull()]
```

**Comment by StevenLi-DS** [comment]
@deppen8 
I had the same issue before:
https://github.com/geopandas/geopandas/issues/790#issuecomment-413039213
