### ISSUE TITLE
geopandas and dependencies confirmed installed, Spyder says geopandas does not exist?

### ISSUE THREAD

**Issue by johnnytriple3** [geopandas/geopandas#960]
Hello,
Performed conda install for geopandas and dependencies and confirmed, new environment, Spyder IDE on Windows 10. 
When attempting "import geopandas", returns error stating 'no module named geopandas'. Added conda-forge channel, as well, not sure what else to do. 

Any help would be great!

**Comment by jorisvandenbossche** [comment]
@johnnytriple3 you probably installed geopandas in a different environment as the one you are running in Spyder. 
So either you need to install Spyder in the same environment, or select the correct Python interpreter in the Spyder settings (to point to the environment in which geopandas is installed)

**Comment by jorisvandenbossche** [comment]
Since we got no further reply, I am going to close this issue. But feel free to comment if you still have problems!
