### ISSUE TITLE
How to add label to colobar when legend=True?

### ISSUE THREAD

**Issue by cfrancois7** [geopandas/geopandas#961]
I wish to use geopandas to make my map, but I don't a way to define the label of the colorbar.

```
fig, ax = plt.subplots(1, figsize=(10,6))
ax.xaxis.set_label_text('xlabel')
ax.yaxis.set_label_text('ylabel')
ax.set_title("Title")
map = data.plot(column="MYDATA", ax=ax, legend=True)
```
I labelized the x and y axes but not the colorbar.
Otherwise I have to desactivated the legend and pass though matplotlib, it is very ugly.

**Comment by StevenLi-DS** [comment]
@cfrancois7 This's more like a StackOverflow question.

I believe you have to create a color yourself and then modify it for now

```python
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.colors as colors

# generate data
gdf = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

# # create the colorbar
norm = colors.Normalize(vmin=gdf.pop_est.min(), vmax=gdf.pop_est.max())
cbar = plt.cm.ScalarMappable(norm=norm, cmap='RdBu')

# plot
fig, ax = plt.subplots(figsize=(15, 7))
# with no normalization
gdf.plot(column='pop_est', cmap='RdBu', legend=False, ax=ax)

# add colorbar
ax_cbar = fig.colorbar(cbar, ax=ax)
# add label for the colorbar
ax_cbar.set_label('I am a label')
```
It seems like folks are talking about adding a abliity for this kind of control by adding a `colorbar_kwds`: https://github.com/geopandas/geopandas/issues/697

**Comment by martinfleis** [comment]
@cfrancois7 you can now pass colorbar kwargs to `legend_kwds` (#1102). Thanks for raising the issue.
