### ISSUE TITLE
Huge performance breakdown since pyproj 2.0.0

### ISSUE THREAD

**Issue by yobuntu** [geopandas/geopandas#963]
The method used by geopandas to transform crs  is 1000 times slower since pyproj 2.0.
a new method can be 100 times faster instead of 1000 times slower.
see : https://pyproj4.github.io/pyproj/html/optimize_transformations.html
see: #962  for an implementation exemple (i couldn't make it pass CI since i don't know how to require pyproj>2

**Comment by jorisvandenbossche** [comment]
Closed by https://github.com/geopandas/geopandas/pull/962
