### ISSUE TITLE
Update to pyproj > 2.1 or switch to different package for crs transformations

### ISSUE THREAD

**Issue by mullenkamp** [geopandas/geopandas#965]
Hi all,

The current implementation of CRS transformations uses an old version of pyproj (1.9.6). Newer versions have added significant improvements (#963 and [pyproj change log](https://pyproj4.github.io/pyproj/html/history.html)). These have addressed some of the prior deficiencies and issues from version 1. There has also been talk of replacing pyproj with fiona or gdal implementations (#315 ). 

I think it would be important to make a decision about which path to take rather than to continue to use an outdated package version as it hampers people like me who'd like to use the newer capabilities of pyproj > 2.1, but I can't have the package coexist with geopandas.

Thanks

**Comment by jorisvandenbossche** [comment]
Thanks for the question! I think the longer term goal is definitely to use proj4/pyproj, and even to better integrate with it (eg use the new CRS class as the `GeoDataFrame.crs` attribute). Short term we will need to wait somewhat on adoption of it throughout the ecosystem (eg have an installable gdal / fiona that is compatible with it). 
I will answer tomorrow a bit more in depth, or create a new issue about the challenges going forward. See also https://github.com/geopandas/geopandas/pull/962 for a first PR that should make the current geopandas work better with pyproj 2.

**Comment by jorisvandenbossche** [comment]
Closing this in favor of the new issue I opened at https://github.com/geopandas/geopandas/issues/1003. Feedback there more than welcome!
