### ISSUE TITLE
Installing from conda-forge fails on python 2.7

### ISSUE THREAD

**Issue by scottlynn73** [geopandas/geopandas#966]
Hi,
I am trying to install geopandas into a fresh conda environment with python 2.7- trying to install 0.3.0 but I'm getting the error below.

![image](https://user-images.githubusercontent.com/12271098/55739811-b9d9f380-5a21-11e9-9227-27435b001cb9.png)

**Comment by ocefpaf** [comment]
Please open conda-forge packaging question in the `geopandas` feedstock: https://github.com/conda-forge/geopandas-feedstock/issues

Can you try issuing these commands:

```shell
conda config --add channels conda-forge  # ensure you have conda-forge on top of defaults
conda config --set channel_priority strict  # activate strict channel
conda create --name TEST python=2.7 geopandas  # create an isolated env
conda activate TEST  # activate the env
python -c "import geopandas; print(geopandas.__version__)"  # test geopandas
```

For more info please see: https://conda-forge.org/docs/user/tipsandtricks.html

PS: everything works for me on Linux but I see you are on Windows. I'll try to check that later today.

**Comment by jorisvandenbossche** [comment]
Since there were no further updates, I am going to close this issue. But @scottlynn73 , if the commands that @ocefpaf mention above do not help, feel free to further ask or open an issue at https://github.com/conda-forge/geopandas-feedstock/issues
