### ISSUE TITLE
Could not find file libspatialindex_c library

### ISSUE THREAD

**Issue by lyncher33** [geopandas/geopandas#988]
Upon importing geopandas library I am getting error stating "OSError: Could not find libspatialindex_c library file".  This is in a Databricks notebook running on Apache Spark 2.4.0.  The notebook has been running without error for several weeks.  Now suddenly getting this error?

**Comment by martinfleis** [comment]
Hi, thanks for the report. 

How did you install geopandas and its dependencies? libspatialindex is one of the dependencies of rtree so you may try to follow installation instructions of rtree (http://toblerity.org/rtree/install.html). However, if you install all packages from `conda-forge` as explained in documentation (https://geopandas.readthedocs.io/en/latest/install.html) this should not happen. Could you post what `conda list` shows?

**Comment by lyncher33** [comment]
Thanks for the prompt response martinfleis.  I believe we installed both geopandas and rtree via PyPI but I will have to double-check as I am not the admin.  Likewise, I will advise the admin to attempt to reinstall using conda-forge if possible.

**Comment by martinfleis** [comment]
I will close this now as it is probably installation/dependency issue which is covered in documentation. If the problem persists even after installation from `conda-forge` let us know.

**Comment by renelikestacos** [comment]
so, what If I don't want to use Conda, is there any alternative?

**Comment by martinfleis** [comment]
@renelikestacos follow instructions: http://geopandas.org/install.html#installing-with-pip or https://geoffboeing.com/2014/09/using-geopandas-windows/. Alternatively, you can use Docker image (like this one https://github.com/darribas/gds_env).
