### ISSUE TITLE
Attribute Error in Fiona when calling Pandas

### ISSUE THREAD

**Issue by cg-david** [geopandas/geopandas#989]
Before I installed geopandas, I used 

`conda install fiona shapely pyproj rtree`

(I already have pandas on my machine) to satisfy all dependencies. Afterwards tried 

`conda install --channel conda-forge geopandas`

as well as

`conda install geopandas`

But even with `conda update -all` I get 

`AttributeError: type object 'fiona.ogrext.FeatureBuilder' has no attribute '__reduce_cython__' `

when I call geopandas in python. Did I mess up something, or does someone has this issue as well? Thanks

**Comment by jorisvandenbossche** [comment]
@cg-david can you check your fiona install? 


```
import fiona
fiona.__version__
```

**Comment by jorisvandenbossche** [comment]
And also, can you show the result of `conda list` ?

There is something wrong with the `fiona` package (which is being used by GeoPandas to read files)

**Comment by cg-david** [comment]
Hi @jorisvandenbossche, thanks for taking your time!
Fiona version is `'1.8.6'`

Output of `conda list` (quite long :D )

`
# packages in environment at /opt/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
affine                    2.2.2                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.7                    py37_0  
anaconda-project          0.8.2                    py37_0  
asn1crypto                0.24.0                   py37_0  
astroid                   2.2.5                    py37_0  
astropy                   3.1.2            py37h7b6447c_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.1.0                   py37_1  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                      py37_1  
backports.os              0.1.1                    py37_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
beautifulsoup4            4.7.1                    py37_1  
bitarray                  0.9.0            py37h7b6447c_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
blosc                     1.15.0               hd408876_0  
bokeh                     1.1.0                    py37_0  
boost-cpp                 1.67.0               h14c3975_4  
boto                      2.49.0                   py37_0  
bottleneck                1.2.1            py37h035aef0_1  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.1.23                     0  
cairo                     1.14.12              h8948797_3  
cartopy                   0.17.0           py37hbb7e04d_1  
cdsapi                    0.1.4                    pypi_0    pypi
certifi                   2019.3.9                 py37_0  
cffi                      1.12.3           py37h2e261b9_0  
cftime                    1.0.3.4          py37hdd07704_0  
chardet                   3.0.4                    py37_1  
click                     7.0                      py37_0  
click-plugins             1.1.1                      py_0  
cligj                     0.5.0                    py37_0  
cloudpickle               0.8.1                      py_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.1                    py37_0  
conda                     4.6.14                   py37_0  
conda-build               3.17.8                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
contextlib2               0.5.5                    py37_0  
cryptography              2.6.1            py37h1ba5d50_0  
curl                      7.64.1               hbc83047_0  
cycler                    0.10.0                   py37_0  
cython                    0.29.7           py37he6710b0_0  
cytoolz                   0.9.0.1          py37h14c3975_1  
dask                      1.2.0                      py_0  
dask-core                 1.2.0                      py_0  
dbus                      1.13.6               h746ee38_0  
decorator                 4.4.0                    py37_1  
defusedxml                0.6.0                      py_0  
descartes                 1.1.0                    py37_0  
distributed               1.27.1                   py37_0  
docutils                  0.14                     py37_0  
entrypoints               0.3                      py37_0  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                he6710b0_0  
fastcache                 1.0.2            py37h14c3975_2  
filelock                  3.0.10                   py37_0  
fiona                     1.8.6            py37hf242f0b_3    conda-forge
flask                     1.0.2                    py37_1  
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.9.1                h8a8886c_1  
freexl                    1.0.5                h14c3975_0  
fribidi                   1.0.5                h7b6447c_0  
future                    0.17.1                   py37_0  
g2clib                    1.6.0                h838ce51_4  
gdal                      2.4.1            py37hf242f0b_0    conda-forge
geographiclib             1.49                       py_0    conda-forge
geopy                     1.19.0                     py_0    conda-forge
geos                      3.7.1                he6710b0_0  
geotiff                   1.4.2                h9c7010b_0  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.4.0            py37h7b6447c_0  
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.56.2               hd408876_0  
glob2                     0.6                      py37_1  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py37h10f8cd9_2  
graphite2                 1.3.13               h23475e2_0  
greenlet                  0.4.15           py37h7b6447c_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.9.0            py37h7918eee_0  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf4                      4.2.13               h3ca952b_2  
hdf5                      1.10.4               hb1b8bf9_0  
hdfeos2                   2.20                 h64bfcee_0  
hdfeos5                   5.1.16               hccfc538_4    conda-forge
heapdict                  1.0.0                    py37_2  
html5lib                  1.0.1                    py37_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py37_0  
imageio                   2.5.0                    py37_0  
imagesize                 1.1.0                    py37_0  
importlib_metadata        0.9                      py37_0  
intel-openmp              2019.3                      199  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.5.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
isort                     4.3.17                   py37_0  
itsdangerous              1.1.0                    py37_0  
jasper                    1.900.1              hd497a04_4  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4.1                      py_0  
jedi                      0.13.3                   py37_0  
jeepney                   0.4                      py37_0  
jinja2                    2.10.1                   py37_0  
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1               h1bed415_0  
jsonschema                3.0.1                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.35.5           py37hf63ae98_0  
jupyterlab_server         0.2.0                    py37_0  
kealib                    1.4.10            h1978553_1003    conda-forge
keyring                   18.0.0                   py37_0  
kiwisolver                1.1.0            py37he6710b0_0  
krb5                      1.16.1               h173b8e3_7  
lazy-object-proxy         1.3.1            py37h14c3975_2  
libarchive                3.3.3                h5d8350f_5  
libboost                  1.67.0               h46d08c1_4  
libcurl                   7.64.1               h20c2e04_0  
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgdal                   2.4.1                hdb8f723_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15                 h63c8f33_5  
libkml                    1.3.0                h590aaf7_4  
liblief                   0.9.0                h7725739_2  
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.37               hbc83047_0  
libpq                     11.2                 h20c2e04_0  
libsodium                 1.0.16               h1bed415_0  
libspatialindex           1.8.5                h20b78c2_2  
libspatialite             4.3.0a              hb08deb6_19  
libssh2                   1.8.2                h1ba5d50_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10               h2733197_2  
libtool                   2.4.6                h7b6447c_5  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                he19cac6_0  
libxslt                   1.1.33               h7d1a2b0_0  
llvmlite                  0.28.0           py37hd408876_0  
locket                    0.2.0                    py37_1  
lxml                      4.3.3            py37hefd8a0e_0  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h49e0be7_2  
mapclassify               2.0.1                      py_0  
markupsafe                1.1.1            py37h7b6447c_0  
matplotlib                3.0.3            py37h5429711_0  
matplotlib-base           3.0.3            py37h5f35d83_1    conda-forge
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2019.3                      199  
mkl-service               1.1.2            py37he904b0f_5  
mkl_fft                   1.0.12           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0  
more-itertools            7.0.0                    py37_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.1                hdf1c602_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.6.1            py37hfd86e86_1  
multipledispatch          0.6.0                    py37_0  
munch                     2.3.2                    py37_0  
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.5.0                      py_0  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  he6710b0_1  
netcdf4                   1.4.2            py37h808af73_0  
networkx                  2.3                        py_0  
nltk                      3.4.1                    py37_0  
nose                      1.3.7                    py37_2  
notebook                  5.7.8                    py37_0  
numba                     0.43.1           py37h962f231_0  
numexpr                   2.6.9            py37h9e4a6bb_0  
numpy                     1.16.3           py37h7e9f1db_0  
numpy-base                1.16.3           py37hde5b4d6_0  
numpydoc                  0.9.1                      py_0  
olefile                   0.46                     py37_0  
openjpeg                  2.3.0                h05c96fa_1  
openpyxl                  2.6.2                      py_0  
openssl                   1.1.1b               h7b6447c_1  
owslib                    0.17.1                     py_0  
packaging                 19.0                     py37_0  
pandas                    0.24.2           py37he6710b0_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
pango                     1.40.14              he752989_2    conda-forge
parso                     0.4.0                      py_0  
partd                     0.3.10                   py37_1  
patchelf                  0.9                  he6710b0_3  
path.py                   12.0.1                     py_0  
pathlib2                  2.3.3                    py37_0  
patsy                     0.5.1                    py37_0  
pcre                      8.43                 he6710b0_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.0.0            py37h34e0f95_0  
pip                       19.1                     py37_0  
pixman                    0.38.0               h7b6447c_0  
pkginfo                   1.5.0.1                  py37_0  
pluggy                    0.9.0                    py37_0  
ply                       3.11                     py37_0  
poppler                   0.67.0            h2fc8fa2_1002    conda-forge
poppler-data              0.4.9                         0  
postgresql                11.2                 h20c2e04_0  
proj4                     5.2.0                he6710b0_1  
prometheus_client         0.6.0                    py37_0  
prompt_toolkit            2.0.9                    py37_0  
pseudonetcdf              3.0.1                      py_0    conda-forge
psutil                    5.6.2            py37h7b6447c_0  
psycopg2                  2.7.6.1          py37h1ba5d50_0  
ptyprocess                0.6.0                    py37_0  
py                        1.8.0                    py37_0  
py-lief                   0.9.0            py37h7725739_2  
pycodestyle               2.5.0                    py37_0  
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37h14c3975_9  
pycurl                    7.43.0.2         py37h1ba5d50_0  
pyepsg                    0.4.0                    py37_0  
pyflakes                  2.1.1                    py37_0  
pygments                  2.3.1                    py37_0  
pykdtree                  1.3.1            py37hdd07704_2  
pylint                    2.3.1                    py37_0  
pynio                     1.5.5            py37h8b983ae_0    conda-forge
pyodbc                    4.0.26           py37he6710b0_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.0                      py_0  
pyproj                    1.9.6            py37h14380d9_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.14.11          py37h7b6447c_0  
pyshp                     2.1.0                      py_0  
pysocks                   1.6.8                    py37_0  
pytables                  3.5.1            py37h71ec239_0  
pytest                    4.4.1                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.5.0                    py37_0  
pytest-doctestplus        0.3.0                    py37_0  
pytest-openfiles          0.3.2                    py37_0  
pytest-remotedata         0.3.1                    py37_0  
python                    3.7.3                h0371630_0  
python-dateutil           2.8.0                    py37_0  
python-libarchive-c       2.8                      py37_6  
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py37hdd07704_1  
pyyaml                    5.1              py37h7b6447c_0  
pyzmq                     18.0.0           py37he6710b0_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 0.5.7                    py37_1  
qtconsole                 4.4.3                    py37_0  
qtpy                      1.7.0                    py37_1  
rasterio                  1.0.22           py37h5b3f9e8_1    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py37_0  
rope                      0.14.0                     py_0  
rtree                     0.8.3                    py37_0  
ruamel_yaml               0.15.46          py37h14c3975_0  
scikit-image              0.15.0           py37he6710b0_0  
scikit-learn              0.20.3           py37hd81dba3_0  
scipy                     1.2.1            py37h7c811a0_0  
seaborn                   0.9.0                    py37_0  
secretstorage             3.1.1                    py37_0  
send2trash                1.5.0                    py37_0  
setuptools                41.0.1                   py37_0  
shapely                   1.6.4            py37h86c5351_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.12.0                   py37_0  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1                    py37_0  
snuggs                    1.4.3                      py_0  
sortedcollections         1.1.2                    py37_0  
sortedcontainers          2.1.0                    py37_0  
soupsieve                 1.8                      py37_0  
sphinx                    2.0.1                      py_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-applehelp   1.0.1                      py_0  
sphinxcontrib-devhelp     1.0.1                      py_0  
sphinxcontrib-htmlhelp    1.0.2                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.2                      py_0  
sphinxcontrib-serializinghtml 1.1.3                      py_0  
sphinxcontrib-websupport  1.1.0                    py37_1  
spyder                    3.3.4                    py37_0  
spyder-kernels            0.4.4                    py37_0  
sqlalchemy                1.3.3            py37h7b6447c_0  
sqlite                    3.28.0               h7b6447c_0  
statsmodels               0.9.0            py37h035aef0_0  
sympy                     1.4                      py37_0  
tblib                     1.3.2                    py37_0  
terminado                 0.8.2                    py37_0  
testpath                  0.4.2                    py37_0  
tk                        8.6.9             h84994c4_1001    conda-forge
toolz                     0.9.0                    py37_0  
tornado                   6.0.2            py37h7b6447c_0  
tqdm                      4.31.1                   py37_1  
traitlets                 4.3.2                    py37_0  
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h14c3975_0  
urllib3                   1.24.2                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.15.2                     py_0  
wheel                     0.33.1                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
wrapt                     1.11.1           py37h7b6447c_0  
wurlitzer                 1.0.2                    py37_0  
xarray                    0.12.1                     py_0  
xerces-c                  3.2.2                h780794e_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.1.7                      py_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.3.1                he6710b0_3  
zict                      0.1.4                    py37_0  
zipp                      0.3.3                    py37_1  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
`

Again thanks for taking your time!

**Comment by jorisvandenbossche** [comment]
So you have a mixture of packages from the default channel and from conda-forge, which is not recommended (there can be binary incompatibilities between the packages), see the note here https://geopandas.readthedocs.io/en/latest/install.html#using-the-conda-forge-channel

Since you have most of the default channel, can you try to force install fiona (and gdal, libgdal) again? (to have them from the default channel)?

**Comment by cg-david** [comment]
Okay, I removed fiona, gdal and libgdal with `conda remove` and installed them new without -c conda-forge. 

Within the uninstall process, I got the following warning:

```
The following packages will be REMOVED:

  fiona-1.8.6-py37hf242f0b_3
  gdal-2.4.1-py37hf242f0b_0
  libgdal-2.4.1-hdb8f723_0
  pynio-1.5.5-py37h8b983ae_0
  rasterio-1.0.22-py37h5b3f9e8_1
```


Within the installation process, I got the following warning:

```
The following packages will be SUPERSEDED by a higher-priority channel:

  fontconfig         conda-forge::fontconfig-2.13.1-he4413~ --> pkgs/main::fontconfig-2.13.0-h9420a91_0
  libdap4            conda-forge::libdap4-3.19.1-hd48c02d_~ --> pkgs/main::libdap4-3.19.1-h6ec2957_0
  libuuid            conda-forge::libuuid-2.32.1-h14c3975_~ --> pkgs/main::libuuid-1.0.3-h1bed415_2
```

Now `import geopandas as gpd` works. I also re-installed pynio and rasterio (as well `conda install -c conda-forge xarray cartopy pynio pseudonetcdf` **without** `-c conda-forge`) from the default channel and see, if everything works as well. 

I didn't knew that conda-forge and the default channel could lead to clashes. I always thought conda-forge was the newer and better maintained channel. Anyways, thanks for your help again! I hope the thread helps other people as well :+1:

**Comment by jorisvandenbossche** [comment]
> I always thought conda-forge was the newer and better maintained channel

Conda-forge is indeed often more (or quicker) up to date with latest releases. But, unfortunately, the packages from both channels are not always binary compatible, so therefore it is advisable that you choose to either go fully for conda-forge, or either stick with the versions available on the default channel (installing extra pure python packages from conda-forge should not be a problem).

But glad it is solved that way! (closing this issue then)
