### ISSUE TITLE
DOC: detailing docstring and add lon & lat as args in points_from_xy()

### ISSUE THREAD

**Issue by StevenLi-DS** [geopandas/geopandas#991]
I'm so glad to see the `gpd.points_from_xy()` function in `0.5.0` . The function needs two args:

```python
geometry = gpd.points_from_xy(df.longitude, df.latitude)
gdf = gpd.GeoDataFrame(df, geometry=geometry)
```
This requires the users to know the order of longitude and latitude. I wonder if they could be optional args so that the users don't have to remember the order so
either
`geometry = gpd.points_from_xy(lon=df.longitude, lat=df.latitude)`
or 
`geometry = gpd.points_from_xy(lat=df.latitude, lon=df.longitude)`
works.

**Comment by martinfleis** [comment]
Hi, that sounds like a reasonable idea to me. I don't see why not, it clarifies the arguments. If we keep the order it still remains compatible with current version.

Would you be willing to do a PR for that?

**Comment by StevenLi-DS** [comment]
@martinfleis I would love to but given my python programming skill, I'm not able to do that. Sorry about that.

**Comment by martinfleis** [comment]
No worries. Thanks for the idea, hope it will be implemented soon.

**Comment by jorisvandenbossche** [comment]
> This requires the users to know the order of longitude and latitude. 

I think it is in any case good for a user to have some understanding of it .. 

But agree that explicit keyword names can make that more readable. For some bikeshedding on the naming, I would rather go for `lon` and `lat`.

**Comment by jorisvandenbossche** [comment]
Actually, in the original PR, there was a case made against adding lon/lat: https://github.com/geopandas/geopandas/pull/75#issuecomment-28706436

**Comment by StevenLi-DS** [comment]
@jorisvandenbossche I actually remembered that someone talked about this with me when I was using `Point` in Shapely. https://github.com/geopandas/geopandas/issues/826 I get all NaNs due to the order misspecification. But I just tried and the `points_from_xy` seems to accept the order misspecification. This might be error prone for the users since for some reasons all the .csv dataset I have always have latitude first and longitude second. 

I think maybe at least this order requirement should be added to the docstring and return an error message to remind the users in the case of misspecification.

**Comment by jorisvandenbossche** [comment]
Adding it to the docstring is certainly a good idea! 

Giving an error message is not really possible I think, as it is difficult to detect (most often switching lon and lat gives *some* location on earth, just not the one you wanted).

**Comment by awa5114** [comment]
This is already the case I think? `x` and `y` are already optional arguments... See below example

```
>>> import geopandas
>>> x = [1,2,3]
>>> y = [4,5,6]

>>> test1 = geopandas.points_from_xy(x=x, y=y)
>>> test2 = geopandas.points_from_xy(y=y, x=x)
>>> for point in test1:
>>>     print(point.xy)
    
(array('d', [1.0]), array('d', [4.0]))
(array('d', [2.0]), array('d', [5.0]))
(array('d', [3.0]), array('d', [6.0]))
>>> for point in test2:
>>>     print(point.xy)
    
(array('d', [1.0]), array('d', [4.0]))
(array('d', [2.0]), array('d', [5.0]))
(array('d', [3.0]), array('d', [6.0]))
```

There is nothing to implement here.... should this issue be closed?

**Comment by StevenLi-DS** [comment]
@awa5114 I actually think x and y is hard to remember and in many dataset I use they are stored as Lon and lat...

**Comment by martinfleis** [comment]
On the other hand, some people use Geopandas to handle abstract datasets where latitude and longitude doesn’t really make sense while x and y works always. Even though you have to remember which is x and which y.

**Comment by awa5114** [comment]
So then what is needed to close this issue? I would like to submit a PR but am unsure what needs to be done here...

**Comment by StevenLi-DS** [comment]
@awa5114 seems like folks have different ideas on this one. I will close this issue now, but I think to add the specification about lon and lat in the docstring for some users like me who deal with dataframe would be very helpful.

**Comment by StevenLi-DS** [comment]
@martinfleis I keep seeing folks getting errors due to the misspecification of the lat and lon order. Any way `lat` and  `lon` can be added as args in the function?

**Comment by martinfleis** [comment]
@StevenLi-DS looking back to this issue and related discussion, we have decided to add a doctrine explaining `lat` `lon` vs `x` `y`, but it never happened. Do you think it would be enough to put it there? I hoped that example in documentation is clear enough: `geopandas.points_from_xy(df.Longitude, df.Latitude)`. 

I don't want to use `lat` `lon` instead of xy for the reasons listed and linked above. And having `points_from_xy(x=None, y=None, lat=None, lon=None, z=None)` and letting user choose doesn't seem very elegant.

**Comment by StevenLi-DS** [comment]
@martinfleis 
I respect the decision. I shouldn't have closed this issue...My bad.
I think it would be great to add it to the doc and the docstring since the function haven't been listed in the doc. (btw, I think this "API Pages" should be changed to "Top-level functions")
![image](https://user-images.githubusercontent.com/33796896/62397282-62691180-b543-11e9-9bc1-e3c625df3a38.png)

It seems there is already an example:
http://geopandas.org/gallery/create_geopandas_from_pandas.html#from-longitudes-and-latitudes

**Comment by martinfleis** [comment]
@StevenLi-DS example was added in the same PR as the function itself. 

I'll keep this open until we will make a PR adding `points_from_xy` to docs (apart from example) with enhanced docstring explaining `lon` `lat` issue. 

Regarding your note on API pages, I feel that our reference guide deserves much more attention. I'll draft some ideas, including this as separate issue.

**Comment by StevenLi-DS** [comment]
@martinfleis That would be great. In fact, I happen to have some ideas. If you don't mind I will open one.

**Comment by StevenLi-DS** [comment]
It has been a while. Could someone pls add the lon and lat info to the following doc?

https://geopandas.org/reference/geopandas.points_from_xy.html#geopandas.points_from_xy

**Comment by martinfleis** [comment]
@SteveLi-DS we are in the middle of complete refactoring of documentation (see #). At one point, we will get to this issue as well and by 0.9 release, lot/lan example will be included here.

**Comment by StevenLi-DS** [comment]
@martinfleis thanks the new site looks great!
